### ISSUE TITLE
FP

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#10]
www.ks.cn

This is portal of government of Kunshan, a city in Jiangsu province.

Blocked as a malicious domain in Urlhaus and even some DNS services because of a single file infected with macro virus

https://urlhaus.abuse.ch/url/1393110/

**Comment by hagezi** [comment]
Flagged as phishing: [Virus Total](https://www.virustotal.com/gui/url/5088b91af2f7962e0e54ca3ad92c52878bd4cc65d56cf026b306db686512504d)

As long as it is flagged and it is on more blocklists, I will not remove it. Furthermore, the HTTPS certificate of the website is invalid.

Please report the domain directly to URLhaus and/or put it on your personal whitelist.

**Comment by hagezi** [comment]
http://www.ks.gov.cn/ is the "official" domain and it is not blocked.

www.ks.gov.cn: 121.32.243.73
www.ks.cn: 121.32.243.75
ks.cn: 222.92.84.170)
