### ISSUE TITLE
OnePlus analytics domain

### ISSUE THREAD

**Issue by Dynasty-Dev** [hagezi/dns-blocklists#100]
![image](https://user-images.githubusercontent.com/89283708/206939237-478d5222-0ecb-4e3c-b4bf-52c1b0c7f30e.png)
analytics.oneplus.cn

**Comment by hagezi** [comment]
Thanks, added.

**Comment by hagezi** [comment]
@Dynasty-Dev 

Look at the result of the query in AGH. If I check with dig, the result is NXDOMAIN, so it is dead. That's why it was removed from my lists.
By the way, there is an Ultimate version of my lists. ;)

**Comment by Dynasty-Dev** [comment]
> @Dynasty-Dev
> 
> Look at the result of the query in AGH. If I check with dig, the result is NXDOMAIN, so it is dead. That's why it was removed from my lists. By the way, there is an Ultimate version of my lists. ;)

That is very strange, it was queried recently by my adguard home instance. 

Also thank you for taking my suggestion! I am still trying it in my browser in adguard home, but so far everything is excellent
