### ISSUE TITLE
Suggestion of New Fake Source

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#1001]
Inspired by Mozilla's acquisition of Fakespot, I found a new source of fake shops and scam. 

https://www.fakeshop.at/en/faq/faq-the-fake-shop-detector/

> Which fake shops does the Detector know?

We cooperate closely with the [Watchlist Internet](https://www.watchlist-internet.at/ueber-uns/), an independent information platform on Internet fraud and fraud-like online traps from Austria. The Watchlist Internet receives around 500 suspicious reports from users every week, which are checked. Fake shops are listed on a public [list of fraudulent online shops](https://www.watchlist-internet.at/liste-betruegerischer-shops/), other dubious shops can be found on the [list of problematic shops.](https://www.watchlist-internet.at/liste-problematischer-shops/)

https://github.com/stonecrusher/filterlists-pihole/blob/master/watchlist-internet-ph.txt

**Comment by hagezi** [comment]
Thank you. I already use the fake lists. I extract the domains directly from https://www.watchlist-internet.at/
