### ISSUE TITLE
help.servicedeskplus.com

### ISSUE THREAD

**Issue by mitchplze** [hagezi/dns-blocklists#1002]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

help.servicedeskplus.com

### Why should the domain(s) be unblocked?

This is a legitimate help site for a legitimate product

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by hagezi** [comment]
@mitchplze fixed.
