### ISSUE TITLE
Curve credit card blocked since recent update

### ISSUE THREAD

**Issue by johnny77a** [hagezi/dns-blocklists#1009]
Hi,
sisce recent update Curve credit card stopped working. After a little digging, list is blocking these domains below. Payments cannot be made, login or using app on phone is impossible if these adresses are not whitelisted.

*.apollo-graphql-gateway.production.curve.app
*.client-orchestrator.production.curve.app
*.clientapi.production.curve.app
*.account-code-verification.production.curve.app
*.auth.production.eu-west-1.curve.app
*.account-subscriptions.production.curve.app

**Comment by hagezi** [comment]
Thanks, will be removed from Ultimate. 

Source: antipopads-re @adroitadorkhan
