### ISSUE TITLE
False positive: quicns.com

### ISSUE THREAD

**Issue by Alex9001** [hagezi/dns-blocklists#1012]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Personal

### Which domain(s) should be unblocked?

quicns.com

### Why should the domain(s) be unblocked?

This is used by https://quic.cloud, a CDN for WordPress.

Blocking quicns.com also blocks every website that uses quic.cloud as cdn. Examples are bayareatechpros.com, bestoffwindows.com , etc..

![Screenshot_20230505_180514](https://user-images.githubusercontent.com/2770710/236590028-c62d7210-55c5-4fa6-8eda-85154976762a.png)

**Comment by iam-py-test** [comment]
Listed in https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt
