### ISSUE TITLE
revanced.io

### ISSUE THREAD

**Issue by Sam-Oak** [hagezi/dns-blocklists#1013]
### Which domain(s) should be blocked?

revanced.io

### Why should these domain(s) be blocked?

It's not the official website. The real one is `revanced.app`, which redirects to `github.com/revanced`.

Other fake sites: https://redd.it/1327o38

**Comment by iam-py-test** [comment]
Listed in uBlock Origin badware risks: https://github.com/uBlockOrigin/uAssets/pull/17469#issuecomment-1514941748
