### ISSUE TITLE
d.ghostery.com

### ISSUE THREAD

**Issue by marcoclg19** [hagezi/dns-blocklists#1015]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

The uninstallation page of the Ghostery extension is blocked.

### Why should the domain(s) be unblocked?

Install Ghostery extension and uninstall it.

**Comment by marcoclg19** [comment]
Ops... I have only just seen #329!

**Comment by hagezi** [comment]
@marcoclg19 Allow d.ghostery.com is ok, the collect domains remain blocked.
