### ISSUE TITLE
Little Snitch Mini Integration

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#102]
Hi,

just want to inform you, that Little Snitch is bringing a new product called 'little snitch mini' with systemwide blocklist integration for macOS.

https://obdev.at/de/products/beta-teaser/index.html

That would be a perfect way to have your blocklists integrated.

**Comment by hagezi** [comment]
Thank you, I will have a look.

**Comment by hagezi** [comment]
@pictosun 
Do you have the possibility to test lists in lsrules format?
Do you know if there is a size limit?
I had read something about a maximum of 200000 rules.

**Comment by hagezi** [comment]
@pictosun 
Little Snitch Testversion of Pro++: https://raw.githubusercontent.com/hagezi/dns-data-collection/main/userdata/pro.plus.lsrules

**Comment by pictosun** [comment]
> @pictosun
> Little Snitch Testversion of Pro++: https://raw.githubusercontent.com/hagezi/dns-data-collection/main/userdata/pro.plus.lsrules

Hi. Sorry for the late feedback. Within LS Mini they're working. But also the 'Adblock' Format was working fine.

**Comment by pictosun** [comment]
Obdev does also have suggested blocklists within LS Mini. 

Just give it a try and talk to them (support@obdev.at) and try to get on this list.
Their Actual list is:
- Peter Lowe
- Ad Away
- Anti PopAds
- URLhaus
- NoCoin
- KADHosts
- OISD
- 1Hosts Lite
- Anudeep
- Sinfonietta Porn-Block
- Sinfonietta gambling

**Comment by hagezi** [comment]
Ok, thanks. Since apparently the Adblock format is supported - hadn't found anything about it - I won't offer lists in LS format.
I'll write to them.
