### ISSUE TITLE
Don't put all subdomains into hostage in general for some badware-users using "wellknown" (reputated?) blog-hosters

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/dns-blocklists#1021]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Badware Hoster

### Which domain(s) should be unblocked?

googleblog.com
blogspot.com

### Why should the domain(s) be unblocked?

It seems to be overblown to block **all** subdomains of googleblog.com because of some user content with badware. This could also be interpreted as some kind of "denial of service" that a single user (or some more) can get a complete service unavailable for users using this blocklist.
Or didn't I understand the description right "Blocks known free hosters that **also** host badware…" and this blocklist is not useful for me only? 🤔

**Comment by hagezi** [comment]
The description is correct, you are blocking hosters - completely - that also host badware. Blogspot is known for hosting "badware blogs" as well, tens of subdomains can be found on malware lists.
I would classify `googleblog.com` as a false positive here, it will be removed.
