### ISSUE TITLE
Whitelist xtracloud.net

### ISSUE THREAD

**Issue by gnadgnaoh** [hagezi/dns-blocklists#1023]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

xtracloud.net

### Why should the domain(s) be unblocked?

The Qualcomm Location XTRA Service generates and provides accurate Satellite positions for extended periods of time to a mobile device. This assistance data is provided in compact form and allows the mobile device to perform positioning for an extended period of time (up to seven days). The assistance data files are made available to a Data Distribution Network for global distribution.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/984

**Comment by hagezi** [comment]
@gnadgnaoh fixed.

ping source @symbuzzer

**Comment by symbuzzer** [comment]
> @gnadgnaoh fixed.
> 
> ping source @symbuzzer

I wont remove these sir, sorry.

Please look: https://community.e.foundation/t/qualcomm-chipsets-data-collection-linked-to-the-a-gps-service-in-e-os/48982

Thanks for informing but:)

**Comment by hagezi** [comment]
Based on GrapheneOS's comment at https://teddit.net/r/privacy/comments/12yii9u/comment/jhojlr7/ and since A-GPS is also used in emergencies, I removed the domains.
