### ISSUE TITLE
Outlook does not send emails successfully; long delay before sending

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#1024]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

```
pipe.aria.microsoft.com
browser.events.data.microsoft.com
```

### Why should the domain(s) be unblocked?

FYI: This only applies to adblock lists. The issue is unrelated to DNS lists; these can still be blocked at the DNS-level. **Please allowlist for adblock lists only.**

Outlook will show a "sending" box for over a minute, and it leaves you wondering if the email was delivered.

Well, turns out, sometimes Outlook doesn't send them depending on what's blocked. I've had a few emails that I sent the last two months never sent successfully.

`browser.events.data.microsoft.com` seems to resolve the major issue on my end. There is still a slight delay with `pipe.aria.microsoft.com` so I allowlisted that, too.

My current workaround: https://github.com/yokoffing/filterlists/commit/dc9e5c7673af082acc1c998456cf06d721c3deba
```
||pipe.aria.microsoft.com^$badfilter,domain=outlook.live.com|outlook.office.com
||browser.events.data.microsoft.com^$badfilter,domain=outlook.live.com|outlook.office.com
```

**Comment by hagezi** [comment]
They are all DNS lists, the AdBlock lists are generated and compressed based on the domain lists. Either I unblock it for all formats or I don't.

What I don't understand is that it's not relevant for DNS? What is the difference if I use the AdBlock list in uBlock or in a network-wide blocker like AdGuard Home? In terms of behaviour, it should make no difference whether the domain is blocked by uBlock or by the upstream DNS (AdGuard Home, NextDNS, ...).

**Comment by yokoffing** [comment]
There have been a handful of cases that cause no issues when blocked at DNS-level, but that do cause issues when blocked in the browser (adblockers). This is one of those cases.

I'm not saying I understand why; I just know my experience 😆

**Comment by hagezi** [comment]
Thanks, crazy, I'll unblock that for the Pro++. In the non-aggressive lists, the MS events are already unblocked.
