### ISSUE TITLE
msmcompare.com (scam)

### ISSUE THREAD

**Issue by AidanGee7** [hagezi/dns-blocklists#1025]
**Which domain(s) should be blocked?**
- msmcompare.com

**Why should these domain(s) be blocked?**
- Fake MoneySuperMarket site. (https://www.moneysupermarket.com/ is the real one).
- Once you fill out the form on the page, you will be contacted by high-pressure "salesmen" (Scammers). Who will end up taking your life savings.

I originally received the link via a spam email promising high interest investment returns.

Thank you!

**Comment by durablenapkin** [comment]
Queued, thanks

**Comment by iam-py-test** [comment]
Fixed in my list as well, thanks @AidanGee7
