### ISSUE TITLE
recruitics.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#1028]
### Which AdBlocker/DNS cloud service do you use?

uBlock, ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

`recruitics.com`

### Why should the domain(s) be unblocked?

Job posting on LinkedIn. When not using an adblocker like uBlock Origin (where I can click and bypass the redirect URL), the page does not load.

Example: `https://jsv3.recruitics.com/redirect?rx_cid=475&rx_jobId=12231835-3&rx_url=https%3A%2F%2Fwww.prodivnet.com%2Fjob%2Fsenior-content-manager-writer-b2b-remote-freelance-los-angeles-california-12231835%3Frx_job%3D12231835-3%26rx_medium%3Dpost%26rx_paid%3D0%26rx_r%3Dnone%26`

![Screenshot 2023-05-10 at 11 25 21 PM](https://github.com/hagezi/dns-blocklists/assets/11689349/d8a0a30f-ad77-4372-88d5-54112ea0fd2d)

**Comment by hagezi** [comment]
FYI @Alex-302 (DNS/Spyware Filter)
