### ISSUE TITLE
*.blackfire.io

### ISSUE THREAD

**Issue by 0xDSousa** [hagezi/dns-blocklists#1029]
### Which AdBlocker/DNS cloud service do you use?

Other

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

*.apm.blackfire.io (and other domains under *.blackfire.io)

### Why should the domain(s) be unblocked?

Hi, I'm Diogo and I'm work for Platform.sh. 

[Blackfire.io](https://www.blackfire.io/) is one of our products, an observability suite used by developers to optimise their websites, with the APM domain being used to render that service.

Customers that use these lists may end up inadvertently blocking themselves out of using our product. As all metrics it collects are authorised and enabled by the developers, we believe it should not be blocked.

Best regards,
Diogo Sousa
Manager, Security Engineering & Operations
Platform.sh

**Comment by hagezi** [comment]
Ping Source @badmojr
