### ISSUE TITLE
jsrdn.com

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#1031]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### Other

❁‿❁

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

jsrdn.com

### Why should the domain(s) be unblocked?

Breaks site layout, videos and more on `Distro.tv`

**Comment by hagezi** [comment]
Need to be unblocked:
```
a.jsrdn.com
c.jsrdn.com
s.jsrdn.com
tv.jsrdn.com
```
