### ISSUE TITLE
Ad Domain

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1033]
### Which domain(s) should be blocked?

adsturn.com

### Why should these domain(s) be blocked?

Ad Serving Service

**Comment by hagezi** [comment]
Is already blocked in all list versions, have I missed something?

**Comment by xRuffKez** [comment]
Maybe my Pihole had Schluckauf. Thanks for checking.

**Comment by xRuffKez** [comment]
vast.adsturn.com

I guess it would be better to wildcard this domain?

**Comment by hagezi** [comment]
@xRuffKez `adsturn.com` is completely blocked in all lists:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/d3557886-f75c-4950-97c6-2786d14fe95e)

```
Blocklists:
 - 1Hosts.Lite     BLOCKED
 - 1Hosts.Mini     BLOCKED
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      BLOCKED
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        BLOCKED
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
```
