### ISSUE TITLE
Add "Lightswitch05 - Ads & Tracking"

### ISSUE THREAD

**Issue by HoVeRzzz** [hagezi/dns-blocklists#1034]
### Which domain(s) should be blocked?

Add the following blocklist:
"Lightswitch05 - Ads & Tracking"
https://www.github.developerdan.com/hosts/
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

### Why should these domain(s) be blocked?

The blocklist is very good and well maintained.

**Comment by iam-py-test** [comment]
[Isn't that list in maintenance mode](https://github.com/lightswitch05/hosts/issues/356) or has something changed?

**Comment by hagezi** [comment]
Yes @iam-py-test.

Thanks @HoVeRzzz, but this is already covered by my Ultimate extension. I see no more value to take over the complete lists, that "inflates" the lists only unnecessarily. 

So the counter question, what are you missing that is not blocked in Ultimate?

**Comment by HoVeRzzz** [comment]
I suggested this because I use "HaGeZi - Multi PRO", and the list I linked in the issue blocks a lot of domains that "HaGeZi - Multi PRO" doesn't block. And since I used the list I linked I never found a false positive. I think it is a good complement for the pro version. Keep up the good work, and thanks for the answer.

**Comment by hagezi** [comment]
The recommended list definitely belongs to the category of aggressive lists. Light to Pro is balanced. I then recommend you to switch to the Pro++ or Ultimate.

**Comment by HoVeRzzz** [comment]
Thanks for the answer once again. I already tried all of the lists (including Pro++ or Ultimate) and these specific ones had loads of false positives. Nowadays I am using PRO and I am liking it (a bit too soft, but it is pretty good).

**Comment by hagezi** [comment]
Then you should report the false positives. Recently there have been some changes in the aggressive lists, maybe you start another attempt with the Pro++. I would be surprised if there were really so many false positives.

**Comment by HoVeRzzz** [comment]
I totally will give it another try, and report the false positives!

**Comment by AAraonWPaul** [comment]
Also isn't this list no longer maintained?

**Comment by hagezi** [comment]
Thank you, this is the only way to make the lists better. Without the community they are simply nothing. There are a lot of people here who have contributed massively and have a large share in the fact that the lists are so effective. You can't do that on your own.

**Comment by hagezi** [comment]
> Also isn't this list no longer maintained?

https://github.com/lightswitch05/hosts/issues/356
