### ISSUE TITLE
[False Positive] ht.youporn.com

### ISSUE THREAD

**Issue by AAraonWPaul** [hagezi/dns-blocklists#1035]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

`ht.youporn.com`

### Why should the domain(s) be unblocked?

Can't watch any videos.

Steps to reproduce:

1. Block `ht.youporn.com`

2. Visit `youporn.com`

3. Click on any video

4. Try playing the video

5. You'll realize you can't and that there is just a black box because this domain is blocked

6. Unblock the domain

7. Reload the page (after like 10 seconds because block ttl is 10)

8. Enjoy the video

**Comment by AAraonWPaul** [comment]
Congrats on 1k stars HaGeZi, just saw 999 at the top so I thought I should be the 1000th

**Comment by hagezi** [comment]
@AAraonWPaul,thanks for the 1000 and congratulations!

`ht.youporn.com` is not the problem, but `phncdn.com` is completely blocked. Will be fixed.

ping source: @bongochong

**Comment by hagezi** [comment]
Tested it again, `ht.youporn.com` can stay blocked, PH CDN must be unblocked.

**Comment by bongochong** [comment]
Good timing. Was just going through some backend stuff to prepare for the next update. `phncdn.com` is being sourced from AdGuard DNS and EasyList's core list on my end by the way.

**Comment by AAraonWPaul** [comment]
> Tested it again, `ht.youporn.com` can stay blocked, PH CDN must be unblocked. Or have I missed something @AAraonWPaul?

Yes, that was it, thank you. Just realized that whitelisting this also fixes the pornhub.com site layout. Thanks again!
