### ISSUE TITLE
revolut-pl-id.com

### ISSUE THREAD

**Issue by darkfence** [hagezi/dns-blocklists#1039]
### Which domain(s) should be blocked?

revolut-pl-id.com

### Why should these domain(s) be blocked?

It’s Revolut phishing link that is trying to tap for users data.

**Comment by iam-py-test** [comment]
I get a 404. Do you have a specific link?

**Comment by darkfence** [comment]
As I see, you have to use a user agent that indicates you are using a mobile device. When using _Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1_ in Firefox site opens correctly. While using _Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0_ it returns 404.

**Comment by iam-py-test** [comment]
Ok, thanks. My sandbox was a desktop. Added to my list.
