### ISSUE TITLE
kro.kr

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [hagezi/dns-blocklists#104]
https://github.com/badmojr/1Hosts/issues/887

**Comment by hagezi** [comment]
No, this is falgged by many security vendors, when it is no longer flagged, I will remove it.

**Comment by Dynasty-Dev** [comment]
So you literally said its malicious yourself, yet youre trying to get someone to whitelist it so you can access one of your services? Thats what local whitelists is for lmao..
