### ISSUE TITLE
TIF Source Suggestion

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#1043]
Stumbled upon this blocklist: https://github.com/braveinnovators/url-blocklist

Translated description:
> Filter list (blocklist) of phishing sites that trick Ukrainians into accessing online banking system accounts, payment card details, confidential information, and money. Only fraudulent web resources are added to the filter, which are aimed specifically at citizens of Ukraine and which are not included in other available filters.

Uses GPLv3 License.
Rudimentary false positive test showed no domains found in the toplist:
```
~ $ comm -12 <(sort url-blocklist-domains.txt) Scam-Blocklist/data/toplist.txt
```

**Comment by hagezi** [comment]
Thanks, added to TIF.
