### ISSUE TITLE
Dogino/Discord-Phishing-URLs Intentionally Removed?

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#1044]
Couldn't help but notice https://github.com/Dogino/Discord-Phishing-URLs was removed from your sources. Was this by accident?

**Comment by hagezi** [comment]
Was automatically disabled, probably because overweigend dead domains are included, I'll take another look.

**Comment by hagezi** [comment]
25600 Domains / 19293 dead ...

**Comment by hagezi** [comment]
However, I have added them back.
