### ISSUE TITLE
Tracker for Sega Games

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1046]
### Which domain(s) should be blocked?

garry.sgaas.net
hull.sgaas.net
sgaas-vpc-garry-public-elb-644092612.eu-west-1.elb.amazonaws.com

### Why should these domain(s) be blocked?

https://steamcommunity.com/app/809890/discussions/0/1640917367347099488/

**Comment by xRuffKez** [comment]
d1o5qsee7g1r89.cloudfront.net

**Comment by hagezi** [comment]
Thanks, will be added.
