### ISSUE TITLE
Might be interesting...

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1049]
I've found a site which could be interesting to find unwanted domains for several services:
https://hosts.gameindustry.eu/

Found the site while investigating a tracker domain from Sega games. #1046

**Comment by hagezi** [comment]
Thanks, I'll take a look.

**Comment by xRuffKez** [comment]
Github Hosts repo from this Site:
https://github.com/KodoPengin/GameIndustry-hosts-Template/

**Comment by hagezi** [comment]
@xRuffKez I have examined there main template, 19000 domains, of which a lot (1000+) false positives that definitely have no place on any list and paralyze entire services. I'm still looking at the other lists, but I think nothing else awaits me there.

Definitely nothing you should use 1:1 as a source.

**Comment by hagezi** [comment]
@xRuffKez With the gaming template a similar picture, I wonder what Facebook CDNs, Instagram, Bing, Google client domains and co have to do with gaming trackers.

Closing ...
