### ISSUE TITLE
False Positve Website: 365digitalconsulting[.]com

### ISSUE THREAD

**Issue by fakeJAVL** [hagezi/dns-blocklists#1054]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole, Other

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Personal

### Which domain(s) should be unblocked?

365digitalconsulting[.]com

### Why should the domain(s) be unblocked?

Kindly remove the website 365digitalconsulting[.]com, website has already been cleaned.

**Comment by hagezi** [comment]
Still flagged by Google Safebrowsing, if the flag is removed, then it also disappears from the lists.

https://transparencyreport.google.com/safe-browsing/search?url=365digitalconsulting.com
