### ISSUE TITLE
New domains?

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#1056]
### Which domain(s) should be blocked?

lazybumblebee.com
93cae558b644d2041eb2ae87388b949411828e3941b8029ca11bf069.com
04697a0ddea24c610de68229dadbc4390c37813647c2827bbc1f9041.com
480bbdf9664629877bc67d2094ca011cc759f779887c3337e8ae8bfd.com
06119add5f6aebd69e3e38a1417fd14972f44442f6828416c46959b1.com
e68eaebc30768a673848927c2b8c8e38c38fd42312e367bca04fc622.com
a9578781b503d168069d979b9403961d411db5f2495fe956cd410157.com
ec493033cd4df851f1b6e08aed8098776469a6baee4a4ebb78974a7e.com
6ad5d7a9aa285849df0f7a776f52d17a861901df9fdcda9db9b3404d.com
5f154926ee0c17ce06289b7825d08fb877f8ebe8d635b65622ce8a2f.com
93cae558b644d2041eb2ae87388b949411828e3941b8029ca11bf069.com
84205da4e6c0ebafe117a3939511ec17d7eb484b06a66e4a67f123e3.com
ab87cc9ec2c76f1c4f6d2703ef9e0d56008bc98b157cc3af10a5bfbd.com
a1401dff39c8fdcba6f437a5b06706d1413c89636d5fee6cce27cc99.com
1a81c87423210199b8232f0bbcc8bd5c6e7e54078768629b407811e9.com
0063450bb8e5e3369ef8c167a463d15c01527283b79bd266bb19b23e.com
a016967c8c783c38e555ae97b38fe0566ad9b398d255e32e833f160d.com
89f5318ce93d828ab801f693bf6d1bf4ba587299f920697b486e751c.com
a9e5f222f1029c111ccc360e6a6dc2bdb29fcb9b684736946ab10e90.com
4fa3df6bdd29062d8558b55bb06fb2885592fcf83cf99e4909483c81.com
7726f27549de609644ca54296d723a4704ca5663d4e6072fc21ff4c4.com
07aa269c0e76550c929640c170af557c7371753ba1b580236d7fa0a4.com
bee6ef6c32228ebf3be3b3dfbbe01853c3f675fa036e1595a0ab64c4.com
0df921ae7136d731950edfdd4876e3ee9759a5c2e63fafe0d43f45cf.com
c0c3eda58e8cefc764eb2be4a530e2a91bb1edb958be470aa94443d8.com
64e98469810bd13e2b45e52d19d6fddfe333b3528350d8cfa792d478.com
3850274698301a9ed25f86e97b2ea9eee4cc8f893e6a78e42006f4fb.com
bf53f4f482ba8b1513d570a748dcbee90cde062c8c91eae4304f2b57.com

### Why should these domain(s) be blocked?

Hi Gerd,

I hope you're well. 

I found a random long domain in the 'allowed' section of my family AGH logs: 

```
s.93cae558b644d2041eb2ae87388b949411828e3941b8029ca11bf069.com
```

Upon investigation using `securitytrails.com`, and with further digging through my logs, it and its associated domains all appear to be telemetry and advertisement related. Some are hosted behind Cloudflare, making further investigation difficult; but others are on individual providers such as Hetzner and servers.com. Their known affiliated domains and subdomains are all tied back to domains you already block, such as `bidmachine.io`, `appodealx.com`, `blueduckredapple.com`, `appbaqend.com`, `thecatmachine.com` and `everstop.io`. 

The related domains not already on your list(s), emanating from the same IP and domains as those you already block, are included here for your consideration. I removed them as a block from my personal blocklist, ~~I hope the formatting is acceptable for you~~. I have amended the formatting after seeing how it rendered in the initial Issue. 

These domains seem to be mostly appearing in my logs when my wife uses what I would consider suspicious/junk apps on her iPhone(!). Alas, user education can only go so far. 

Best wishes,

Lee / Rainmaker

**Comment by hagezi** [comment]
Thanks Lee, will be added.

**Comment by RainmakerRaw** [comment]
> Thanks, domain(s) has been added to the allowlist and will be removed in the next update.

@hagezi Just to check, that the auto reply was in error and that you haven't actually accidentally added them to the whitelist?! 😀

**Comment by hagezi** [comment]
@RainmakerRaw I wanted to see if you noticed. LOL, no, was my fault, was a long day ...
