### ISSUE TITLE
Should new TLD .zip be added on 'Most Abused TLDs'?

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [hagezi/dns-blocklists#1058]
According to the following text, the _.zip_ TLD can be used to do malicious phishing: [The dangers of Google's .zip TLD](https://medium.com/@bobbyrsec/the-dangers-of-googles-zip-tld-5e1e675e59a5)

A more extended discussion about: [New ZIP domains spark debate among cybersecurity experts](https://www.bleepingcomputer.com/news/security/new-zip-domains-spark-debate-among-cybersecurity-experts/)

I'm not a cybersecurity expert, and I want to understand the community's thoughts on this topic and if we need to block this TLD.

**Comment by hagezi** [comment]
Thank you, from my point of view the TLD should be blocked. What do you think @yokoffing, @iam-py-test?

**Comment by yokoffing** [comment]
It’s already blocked on my list and the NextDNS guide.

**Comment by PauloGoncalvesBH** [comment]
> It’s already blocked on my list and the NextDNS guide since yesterday.

I also blocked on yesterday (and added it to your guide :D what a coincidence)

**Comment by yokoffing** [comment]
Of course, we'll monitor for any breakage. But it's so new, I would only assume malicious domains come from it until after some time.

**Comment by yokoffing** [comment]
From the Bleeping Computer [article](https://www.bleepingcomputer.com/news/security/new-zip-domains-spark-debate-among-cybersecurity-experts/):

> Earlier this month, [Google introduced](https://www.blog.google/products/registry/8-new-top-level-domains-for-dads-grads-tech/) eight new top-level domains (TLD) that could be purchased for hosting websites or email addresses.
> 
> The new domains are .dad, .esq, .prof, .phd, .nexus, .foo, and for the topic of our article, the .zip and .mov domain TLDs.

We may want to consider `.mov` as well, [e.g.](https://www.blog.google/products/registry/8-new-top-level-domains-for-dads-grads-tech/):

```
||mov^$denyallow=david.mov
||zip^$denyallow=url.zip
```

**Comment by yokoffing** [comment]
Update: [Google's Zip Domains Are WORSE Than I Thought](https://youtu.be/V82lHNsSPww)
- Twitter, LinkedIn, Reddit auto-convert existing `.zip` text to links. Example: the malicious old `42.zip`.
- Gmail, Outlook, iCloud do not convert `.zip` (yet).
- IT departments around the world are already recognizing it as a threat and mass blocking all `.zip` TLDs.
- `.mov` domains pose similar risks as a common video file extension.
- The best solution would be for Google to stop selling `.zip` and `.mov` domains and refund buyers.

**Comment by iam-py-test** [comment]
I'm no security expert, so my opinion clearly doesn't mean much, but I personally think software autolinking things which "look like domains" is a problem with the software not the TLD; .zip just makes it worse due to it's prevalence as a file extension.

**Comment by yokoffing** [comment]
> Also, FYI, this isn't meant as an attack on you

@iam-py-test I didn't read your comment as negative at all. Not in the slightest 😆

**Comment by yokoffing** [comment]
@iam-py-test I've been watching NSCU videos for awhile, and I just now realized that one of those dudes is Peter Lowe 🤯

**Comment by iam-py-test** [comment]
Off topic, but NSCU is awesome (been watching their videos for a year or something).

**Comment by yokoffing** [comment]
[Clever ‘File Archiver In The Browser’ phishing trick uses ZIP domains](https://www.bleepingcomputer.com/news/security/clever-file-archiver-in-the-browser-phishing-trick-uses-zip-domains/)
- A new phishing kit uses ZIP domains to trick users into thinking they are opening a ZIP archive. The kit displays fake WinRAR or File Explorer windows in the browser that claim to be opening a ZIP file from a .zip domain.
- This is meant to trick users into downloading malicious files or entering their credentials.
- The fake WinRAR windows even have a fake security scan feature.
- The ZIP domains can also be abused when Windows automatically tries to open them when a user searches for a file name that matches the domain.
