### ISSUE TITLE
archive.org = piracy?

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/dns-blocklists#1059]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Threat Intelligence Feeds, DoH/VPN/TOR/Proxy Bypass, Badware Hoster, Anti Piracy

### Which domain(s) should be unblocked?

archive.org

### Why should the domain(s) be unblocked?

As [Wikipedia](https://de.wikipedia.org/wiki/Internet_Archive) says I don't believe that it's main focus is be a piracy hoster:

> Das Internet Archive in [San Francisco](https://de.wikipedia.org/wiki/San_Francisco) ist ein [gemeinnütziges](https://de.wikipedia.org/wiki/Gemeinn%C3%BCtzigkeit) Projekt, das 1996 von [Brewster Kahle](https://de.wikipedia.org/wiki/Brewster_Kahle) gegründet wurde und seit 2007 den offiziellen Status einer Bibliothek hat. Gestartet wurde es als reines [Webarchiv](https://de.wikipedia.org/wiki/Web-Archivierung), bei dem man mit der sogenannten Wayback Machine archivierte [Websites](https://de.wikipedia.org/wiki/Website) betrachten kann. Schon von 1999 an wurde es um weitere Archive erweitert, so dass sie nunmehr eine [digitale Bibliothek](https://de.wikipedia.org/wiki/Digitale_Bibliothek) ist, die bedeutende Sammlungen von Texten und Büchern, Audiodateien, Videos, Bildern und Software umfasst. Das Internet Archive hat sich die [Langzeitarchivierung](https://de.wikipedia.org/wiki/Langzeitarchivierung) digitaler Daten in frei zugänglicher Form zur Aufgabe gemacht und legt dabei auch Wert auf Zugangsmöglichkeiten für blinde oder anders eingeschränkte Nutzer.

> Neben der Funktion als Archiv versteht sich das Internet Archive auch als [Aktivist](https://de.wikipedia.org/wiki/Aktivist) für ein offenes und freies Internet sowie den Erhalt und die Verbreitung [gemeinfreier](https://de.wikipedia.org/wiki/Gemeinfreiheit) Werke.[[1]](https://de.wikipedia.org/wiki/Internet_Archive#cite_note-1)

Are you sure that you want to block the complete Internet Archive? :-?

**Comment by hagezi** [comment]
It is a piracy list and at archive.org you can also download modded and illegal apks or other illegal software. It is a bypass, so it is blocked in the piracy blocklist.

**Comment by iam-py-test** [comment]
I understand your argument, but respectfully, I would like to disagree. The list description states:
> Blocks websites and services that are mainly used for illegal distribution of copyrighted content.

And while archive.org is used for piracy, it isn't _mainly_ used for it, nor is that it's intended purpose.
Just my one cent.

**Comment by berkaykrc** [comment]
I cannot access https://www.wayback.archive.org/

**Comment by hagezi** [comment]
https://www.wayback.archive.org/ is dead/doesn't exist (NXDOMAIN)

Use wayback.archive.org or web.archive.org
