### ISSUE TITLE
Online DNS Service

### ISSUE THREAD

**Issue by marcoclg19** [hagezi/dns-blocklists#106]
I discovered this DNS where you can use your blocklists. If you want, you could add it to the section. 
I have yet to try it out though ;)

https://dnswarden.com/
https://www.reddit.com/r/PrivacyGuides/comments/xw0ov3/dnswarden/

**Comment by hagezi** [comment]
Thank you, I will add the service.

**Comment by Dynasty-Dev** [comment]
> Thank you, I will add the service.

You should also add 'Technitium' it supports both hosts and domains.

**Comment by hagezi** [comment]
Added.

**Comment by marcoclg19** [comment]
@hagezi I have seen that you have updated your RegEx rules. However, your AdGuardDNS file is not updated with those. 
I don't know if I have explained myself.

**Comment by hagezi** [comment]
@marcoclg19 
I have splitted the RegEx into Black and White. I have just updated the AdGuardDNS Settings.
https://github.com/hagezi/files/tree/main/adguarddns

**Comment by marcoclg19** [comment]
Hello, @hagezi.
I am really happy that your list is getting these accomplishments. Now you can also include ControlD! I hope you are happy too. Congratulations!

https://kb.controld.com/en/3rd-party-filters
https://controld.com/free-dns

**Comment by marcoclg19** [comment]
In my opinion, the DNS section could be rewritten in a more simplified and clearer way... (keep the file for AdGuard DNS anyway, which is always useful xd)

**Comment by hagezi** [comment]
Thanks @marcoclg19!

Yes, the DNS section is not "optimal". What do you think it should look like?

**Comment by marcoclg19** [comment]
> Yes, the DNS section is not "optimal". What do you think it should look like?

Maybe a **single table** with two columns: the one on the left with the name of the DNS service and in the other column all the information needed to understand how to use each of them. That's all I have in mind for now.

**Comment by hagezi** [comment]
@marcoclg19 added: https://github.com/hagezi/dns-blocklists#controld

**Comment by hagezi** [comment]
I'll see how I do it with the online DNS section, I think in a table will be difficult there are DoH, DoT, QUIC, Mobileconfig, IPv4, IPv6 ...

**Comment by marcoclg19** [comment]
I have tried many DNS but do not know which one to use definitively. From your experience, what would you recommend?

**Comment by hagezi** [comment]
They are all usable, a question is whether it may be a free or paid service. Furthermore, it plays a role how the ping from your region to the DNS service is. There are no big differences in the features of the paid services. For me, none stands out clearly. I had no problems with NextDNS, AdGuardDNS or ControlD.
Of course, you are most flexible if you set up your own DNS on a cheap or free VPS, e.g. with AdGuard Home.

**Comment by marcoclg19** [comment]
> it plays a role how the ping from your region to the DNS service is. 
How can i test this? Is there some easy online tool that allows me to do so?

**Comment by marcoclg19** [comment]
Sorry if this is a bit off-topic, as I am curious, I wanted to understand from an expert like you, what you use as an adblocker on your browser and on iOS :)

**Comment by hagezi** [comment]
Desktop: uBlock
iOS: AdGuard
DNS: NextDNS/AdGuardDNS/ControlD

**Comment by marcoclg19** [comment]
> @marcoclg19 I have splitted the RegEx into Black and White. I have just updated the AdGuardDNS Settings. https://github.com/hagezi/files/tree/main/adguarddns

Hi, I cannot import the file to AdGuardDNS. It gives me an error.
https://raw.githubusercontent.com/hagezi/files/main/adguarddns/hagezi_dns_server_settings.json

**Comment by hagezi** [comment]
https://github.com/hagezi/files/blob/main/adguarddns/hagezi_dns_server_settings.json

![grafik](https://user-images.githubusercontent.com/104343908/221788153-f44e0c4d-1d58-4ee8-81d8-e5b1667fdf71.png)

![grafik](https://user-images.githubusercontent.com/104343908/221788203-71667ee9-e245-4d72-9e7e-828c159ec7ea.png)

See: https://www.howtogeek.com/devops/how-to-download-single-files-from-a-github-repository/

**Comment by marcoclg19** [comment]
> See: https://www.howtogeek.com/devops/how-to-download-single-files-from-a-github-repository/

Yes, I had already done it but it doesn't work...

![image](https://user-images.githubusercontent.com/108359740/221883396-ba40f352-7be2-47f4-a13a-ad4cc8b72b71.png)

**Comment by hagezi** [comment]
Fixed, please try again ...
