### ISSUE TITLE
Cannot access my hosted Nextcloud instance due to this rule: ||opsserver.ch^

### ISSUE THREAD

**Issue by thai-taco** [hagezi/dns-blocklists#1066]
My provider is opsone.ch

I believe this is the offending line:
||opsserver.ch^

The NextDNS allow rule I used to get it working again is:
*.opsserver.ch

**Comment by iam-py-test** [comment]
Listed in 1Hosts Pro/Xtra

**Comment by thai-taco** [comment]
Should I report it their instead?
