### ISSUE TITLE
cmp.dmgmediaprivacy.co.uk

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#1067]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

cmp.dmgmediaprivacy.co.uk

### Why should the domain(s) be unblocked?

Comments blocked https://www.dailymail.co.uk/sciencetech/article-12094091/Scientists-reveal-make-perfect-cup-tea-agree-method.html#comments

**Comment by hagezi** [comment]
fixed.
