### ISSUE TITLE
seo.spot.im

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#1068]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

seo.spot.im

### Why should the domain(s) be unblocked?

Comments blocked https://www.ign.com/articles/best-apple-watch-deals

**Comment by hagezi** [comment]
fixed.
