### ISSUE TITLE
dooood.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#1069]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

dooood.com

### Why should the domain(s) be unblocked?

alternate domain from doodstream.com

**Comment by hagezi** [comment]
fixed.
