### ISSUE TITLE
FP monitor.ppcprotect.com

### ISSUE THREAD

**Issue by Ry3nlNaToR** [hagezi/dns-blocklists#107]
Am currently using the PRO++ version of your list for the last few days zero issues, originally was using Oisd and 1Hosts lite but wanted something a bit more aggressive, your list is a good mix of other more aggressive lists but with whitelisted domains and aggressive, Keep up the good work.

On topic the pro plus list seems to block monitor.ppcprotect.com the listing comes from AdGuard DNS filter rule: ||ppcprotect.com^ .

The domain was loaded after clicking ad on google search results, the domain seems to be for pay per click anti-fraud protection, so probably ok to whitelist since its only going to get requested on clicking the ad link.

![Screenshot 2022-12-16 19 42 29](https://user-images.githubusercontent.com/49639150/208182716-76ee3913-1c1b-4c8e-974a-e6e116cc46af.png)

**Comment by hagezi** [comment]
Thanks, removed.
