### ISSUE TITLE
istyle.hu Webshop issue

### ISSUE THREAD

**Issue by szl1973** [hagezi/dns-blocklists#1072]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

istyle.hu

### Why should the domain(s) be unblocked?

Cannot finalised an order in the Webshop, because the list blocks the choosing of the payment option.

**Comment by hagezi** [comment]
@szl1973 istyle.hu is not blocked in my lists.

**Comment by hagezi** [comment]
@szl1973 Unblocking c.seznam.cz fixes the problem?

**Comment by szl1973** [comment]
Yes
