### ISSUE TITLE
phish.report is not phishing

### ISSUE THREAD

**Issue by BlackWolfWoof** [hagezi/dns-blocklists#1077]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

phish.report

### Why should the domain(s) be unblocked?

phish.report is a site that easily makes it possible to report phishing sites.
Also i found it in https://github.com/hagezi/dns-blocklists/main/domains/tif.txt no clue what category that is in so i just selected Multi PRO++

**Comment by hagezi** [comment]
@BlackWolfWoof  `phish.report` is not blocked in the current version of my lists.

**Comment by BlackWolfWoof** [comment]
@hagezi I do not know which list would be https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/tif.txt
It is blacklisted there
![Screenshot](https://blackwolfwoof.com/s/afrD87Zd/preview)

**Comment by hagezi** [comment]
Update the lists in Pi-hole. In the current version of the TIF, the domain is no longer blocked.
