### ISSUE TITLE
Wildcard rules for Black & White list

### ISSUE THREAD

**Issue by Dynasty-Dev** [hagezi/dns-blocklists#108]
Your personal wildcard still blocks this domain. You have both 
||googleadservices.com^
@@||www.googleadservices.com^$important ! Referral Google search results

But it still gets blocked.

**Comment by hagezi** [comment]
I don't understand why a domain that was unblocked with $important is still blocked?

I'll test this tomorrow ...

**Comment by hagezi** [comment]
@Dynasty-Dev, works as expected

`googleadservices.com` - blocked

![grafik](https://user-images.githubusercontent.com/104343908/208285990-acd85f15-844a-499f-9193-06be4171da25.png)

`www.googleadservices.com` - unblocked

![grafik](https://user-images.githubusercontent.com/104343908/208286010-dc6ad9d1-5703-4b90-b620-a862052a2b99.png)

**Comment by hagezi** [comment]
And in AGH:

![grafik](https://user-images.githubusercontent.com/104343908/208286203-fb7fb8fc-ab21-4a5d-9514-ae290cd890e1.png)

**Comment by Dynasty-Dev** [comment]
> And in AGH:
> 
> ![grafik](https://user-images.githubusercontent.com/104343908/208286203-fb7fb8fc-ab21-4a5d-9514-ae290cd890e1.png)

That’s really weird, it’s not working for me

**Comment by Dynasty-Dev** [comment]
@hagezi it seems you fixed it in the update, when you removed the comment next to the white list it worked

**Comment by Dynasty-Dev** [comment]
Latest update broke it again @hagezi 

Is this done on purpose? There are other rules that break things for example the microsoft events rule breaks self.events.data.microsoft.com

**Comment by hagezi** [comment]
The list is actually only used as an optimisation for the AdguardDNS Black & White list. It was not designed to be used outside of this.
I would need to add some whitelist entries to make it usable on its own.

**Comment by hagezi** [comment]
@Dynasty-Dev fixed
