### ISSUE TITLE
NSFL/NSFW Domain

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1080]
### Which domain(s) should be blocked?

crazyshit.com

### Why should these domain(s) be blocked?

!TRIGGER WARNING!

Site contains explicit hard content against humanity.
Contains images/videos and blogs against races, ethnies, terror, suicide, disgusting kind of porn fetishes, hate speech, and intolerance of minors.

I don't know which list would fit, but it's definetly a site for psychopaths.

**Comment by hagezi** [comment]
I do not maintain a NSFW list. The best NSFW list is the oisd NSFW. The domain is already on this list: https://nsfw.oisd.nl/
