### ISSUE TITLE
static.adsafeprotected.com

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#1081]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Other

O . o

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

static.adsafeprotected.com

### Why should the domain(s) be unblocked?

Anti adblock script

**Comment by hagezi** [comment]
https://slayterdev.github.io/tracker-radar-wiki/domains/adsafeprotected.com.html

This is definitely something for your personal allowlist if it leads to restrictions somewhere.
