### ISSUE TITLE
smtx.belfius.be

### ISSUE THREAD

**Issue by orosseel** [hagezi/dns-blocklists#1090]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

smtx.belfius.be

### Why should the domain(s) be unblocked?

Belfius is a Belgian bank. I am concerned about the functionality of the app when blocking this domain. Maybe everything should even be allowed from belfius.be.

**Comment by hagezi** [comment]
What doesn't work because of the blocking?

The domain is a disguised omtrdc.net CNAME tracker.
