### ISSUE TITLE
cdn.braze.eu

### ISSUE THREAD

**Issue by orosseel** [hagezi/dns-blocklists#1091]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

cdn.braze.eu

### Why should the domain(s) be unblocked?

Images fail to load in an email from Dutch bank Bunq.

**Comment by hagezi** [comment]
This is something for your personal allowlist.

https://slayterdev.github.io/tracker-radar-wiki/domains/braze.eu.html

Is not unblocked in my lists.
