### ISSUE TITLE
Fakenews | Scam

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1098]
### Which domain(s) should be blocked?

jakedstake.com
improtants.space
### Why should these domain(s) be blocked?

https://jakedstake.com/?placement=Instagram_Feed&adset_name=26+&ad_name=ede3+7Agensy2&ad_id=6317599534335&fb=2123576367848369&buyer=ZOID&netProbitiya2k23=w0tth3b3stGmev3R&fbclid=PAAabpbNFuMp39sngV4NbKWCTgssSdhwLn0VpanYVIOtMB6MUueXMiyx_SqjM_aem_th_ASfYmLmR165hilrTjSvgBjXHnI2xeDJabEV3u_TpIEzWdUdqKmH0NN2RPjjEDUl9JpJkCJNYuZLoIpD6PwP4II5Y&external_browser_redirect=true

**Comment by xRuffKez** [comment]
https://jakedstake.com/?_lp=1&_token=uuid_9184g9dritd_9184g9dritd6477172fe11541.06643871

**Comment by xRuffKez** [comment]
![Screenshot_20230531_114524_Samsung Internet](https://github.com/hagezi/dns-blocklists/assets/92758042/39bb64d8-7d12-407f-b7fe-522a343c5a80)

**Comment by xRuffKez** [comment]
`
![Screenshot_20230531_114804_Samsung Internet](https://github.com/hagezi/dns-blocklists/assets/92758042/9af8d967-943d-441d-80fb-f681eceb2ff3)
`

**Comment by xRuffKez** [comment]
![Screenshot_20230531_114804_Samsung Internet](https://github.com/hagezi/dns-blocklists/assets/92758042/c96522c7-1930-4686-badf-28a6bc5554b6)

**Comment by xRuffKez** [comment]
The normal root domain site pretends to be a normal AI tech site

**Comment by durablenapkin** [comment]
Thank you, queued

**Comment by iam-py-test** [comment]
Added to my list as well, thanks.
FYI @xRuffKez you can put URLs in ` to prevent them from being turned into links
