### ISSUE TITLE
Pizza Hut Australia

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#1107]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Personal

### Which domain(s) should be unblocked?

https://www.pizzahut.com.au

### Why should the domain(s) be unblocked?

Unable to select delivery or pickup location for pizza when using HaGeZi HaGeZi Personal Black & White.

Error message a user gets when trying to enter an address or postcode is `Sorry, we couldn't find any results for 2000`

Potentially whitelisting one of these domains resolves the issue but I haven't dug into it in great depth.

```
@@||optimizely.com^$important
@@||sentry-cdn.com^$important
```

**Comment by hagezi** [comment]
@gyCfjSnO 
Very poor website design, add `js.sentry-cdn.com` to your personal allowlist. I will not unblock this for the masses.
