### ISSUE TITLE
Amazon app usability issue

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#111]
Greetings, Gerd! I hope you're well. 

I am now solely using your lists in AdGuard Home (Pro++, TIF and Encrypted DNS).

In the Amazon UK app, I can't see my previous orders in the my account section (person icon at the bottom of the app). In the place where photos of my recent ordered items should be, a button suggests 'Retry', but with no results. Among the many (correctly) blocked Amazon domains in the DNS logs, this stood out: 

```
Domain

appx.transient.amazon.co.uk
Response details
Elapsed
0.39 ms
Rule(s)

||appx.transient.amazon.co.uk^
HaGeZi Pro++

Response
AAAA: :: (ttl=10)
Response code
NOERROR
```
Adding this to custom rules / whitelist allows the recent orders to load appropriately: 

```
@@||*appx.transient.amazon.*^
```

Though for now, I replaced it with `||appx.transient.amazon.co.uk^$badfilter` so I remember to remove the rule once the list is (hopefully) fixed. 

Please might you consider adding this to your whitelist? I have some other domains and tweaks to suggest, but I will wait until after the festive period when time is less constrained. 

Best wishes,

Lee

**Comment by hagezi** [comment]
@RainmakerRaw Thank you very much, also for the detailed explanations. I see no reason not to remove the domain, so I removed it.

If you have any other recommendations, keep them coming.

Thanks for your help,
Gerd

**Comment by hagezi** [comment]
ping @badmojr
