### ISSUE TITLE
ic3.events.data.microsoft.com & teams.events.data.microsoft.com

### ISSUE THREAD

**Issue by nishaddesilva** [hagezi/dns-blocklists#1114]
### Which domain(s) should be blocked?

teams.events.data.microsoft.com
ic3.events.data.microsoft.com

### Why should these domain(s) be blocked?

These domains are blocked even by 1Hosts (Mini). But even in Hagezi PRO list these two domains are not blocked. 
Are they false positives? Any reason to not block them in your filter?
Thanks!

**Comment by hagezi** [comment]
There are some problems with Office online in the browser when the `*.events.data.microsoft.com` domains are blocked, so they have been unblocked in the Light to Pro non-aggressive lists.

**Comment by nishaddesilva** [comment]
Thanks for the clarification!
