### ISSUE TITLE
Spam TLD List

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#112]
Hello, I have been using your blocklists’ for about a day now and they are amazing, no false positives. However in your TLD blocklist the xyz entry has a lot of false positives. Can you add the ru and kp TLD from nextdns configuration? Thanks.

**Comment by devipasigner** [comment]
> The blocking of some country-specific TLDs such as ru would lead to the internet being blocked in the corresponding region. That's why TLDs like cn, ru and others are not on the list. If they are not relevant for your region, put them on your personal block list.
> 
> If you use TLD blocklists, you will also have to whitelist one or the other, for xyz more or less depending on the region.

Well, ok I guess I will copy your rules into my custom filter rules and strip xyz since that is the only problematic one. I understand the ru but can you update yokoffing tlds?

**Comment by hagezi** [comment]
Removed xyz, what are you missing from yokoffing TLDs?

**Comment by devipasigner** [comment]
> Removed xyz, what are you missing from yokoffing TLDs?

I made a GitHub repo so I can easily add it from yokoffing, when I get home I will post, thank you

**Comment by devipasigner** [comment]
> Removed xyz, what are you missing from yokoffing TLDs?

||kp^
||pw^
||top^
||cfd^

**Comment by devipasigner** [comment]
@hagezi urgent! fix needed! https://github.com/AdguardTeam/HostlistCompiler/issues/42

**Comment by hagezi** [comment]
@devipasigner Thank you, I had already seen the issue. It is actually only relevant when you send the list through the HostCompiler. It also works in the current format.
However, I will adapt the format so that the entries are also compatible with the validation of the HostCompiler.

I will add your TLDs, top should already be on it.

**Comment by hagezi** [comment]
@devipasigner rule sytnax fixed (https://github.com/AdguardTeam/HostlistCompiler/issues/42#issuecomment-1359106308) and missing TLDs added, please check.

Thanks for your help,
Gerd

**Comment by devipasigner** [comment]
> @devipasigner rule sytnax fixed ([AdguardTeam/HostlistCompiler#42 (comment)](https://github.com/AdguardTeam/HostlistCompiler/issues/42#issuecomment-1359106308)) and missing TLDs added, please check.
> 
> Thanks for your help, Gerd

Nice no problem, thank you for these awesome filter lists!

**Comment by devipasigner** [comment]
> @devipasigner rule sytnax fixed ([AdguardTeam/HostlistCompiler#42 (comment)](https://github.com/AdguardTeam/HostlistCompiler/issues/42#issuecomment-1359106308)) and missing TLDs added, please check.
> 
> Thanks for your help, Gerd

It seems updates are not automated. .garden was added recently

**Comment by hagezi** [comment]
The TLD is on the list ...
