### ISSUE TITLE
ichnaea.netflix.com

### ISSUE THREAD

**Issue by dwinnert** [hagezi/dns-blocklists#1133]
### Which domain(s) should be blocked?

ichnaea.netflix.com

### Why should these domain(s) be blocked?

It's described as a Netflix logging/client endpoint for client info, and/or responsible for autoplaying previews. Blocking causes no issues with logging, or with previews, and Netflix works the same whether it's blocked, or not blocked.

Seems it would be worth it to block it.

**Comment by dwinnert** [comment]
> This prevents Netflix from continuing to play videos where you stopped or paused them. Quite annoying when you watch on one device and want to continue watching on another where you left off.

Weird, as it causes zero issues with me being able to play videos where I left off. I use Netflix on a Roku and a Windows 11 PC/Firefox and a partially watched movies starts at the same place on both devices.

I'll just add a custom rule.

Thanks for all your work!

**Comment by hagezi** [comment]
@dwinnert I had put it on the Allowlist myself because I had problems switching from Netflix in the browser to Netflix on the AppleTV when I switched in a series episode.
I will test it again in the next few days.

**Comment by hagezi** [comment]
I tested it once between browser and iPhone iOS app, now it seems to be like you said. I'll test it again on the AppleTV in a few days, until then I'll block `ichnaea*.netflix.com` in the aggressive lists.
