### ISSUE TITLE
Hackster.io layout messed up

### ISSUE THREAD

**Issue by hann315** [hagezi/dns-blocklists#1140]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

prod.hackster-cdn.online

### Why should the domain(s) be unblocked?

Blocked prod.hackster-cdn.online domain messed up the hackster.io website because is the source of their CSS.

**Comment by hagezi** [comment]
Thanks, ping @yokoffing, exclude `hackster-cdn.online`

**Comment by yokoffing** [comment]
done

**Comment by hagezi** [comment]
@hann315 fixed
