### ISSUE TITLE
Adware list from malwaretips.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#1142]
Can you add that list to complete the TIF segment?
https://malwaretips.com/blogs/category/adware/

Sorry, I dont have resource and time to do sorting up manually.

**Comment by hagezi** [comment]
Thank you, I'll see what's missing.

**Comment by hagezi** [comment]
@MagicalAlchemist adware will be added to all lists (light to ultimate) during the next update and will be updated automatically on a cyclical basis.
