### ISSUE TITLE
[false positive] tracking.totalexpress.com.br

### ISSUE THREAD

**Issue by pedrolucasmag** [hagezi/dns-blocklists#1147]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

tracking.totalexpress.com.br

### Why should the domain(s) be unblocked?

This domain is specifically designed for tracking orders within Total Express, a Brazilian logistics company, it is not a web tracker.

**Comment by iam-py-test** [comment]
I get NXDOMAIN for that website

**Comment by pedrolucasmag** [comment]
> I get NXDOMAIN for that website

Sorry! Correct domain is tracking.totalexpress.com.br
