### ISSUE TITLE
Experiments with Light - a couple of suggestions

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#1150]
### Which domain(s) should be blocked?

`covatic.io`

`tm-awx.com`

### Why should these domain(s) be blocked?

Greetings Gerd!

Since yokoffing posted about Light, I have given it a trial as I had just migrated my DNS and WireGuard server back to OpenBSD anyway. Honestly, my block stats are still pretty much the same as they always were on Pro - though Firebase isn't so strictly blocked of course. The only real difference is that my users (family) stopped complaining about little breakages in apps. 👍🏻 

That said, the aforementioned two root domains now keep showing up as Allowed, but they were blocked before on more aggressive lists. Here are the details: 

(1) `mobile-cvc-ire-cvc-stg.covatic.io`

Covatic measure how and when users interact with apps. It doesn't seem to be at all required for functionality. Their actual public facing website for details of the company, sales etc is at `covatic.com` if people might ever wish to read it; so blocking `||covatic.io^` at the root to kill their telemetry has no impact that I have seen (I've been blocking it for a while now). 

(2) `feliz-web.data.tm-awx.com`
`mab.data.tm-awx.com`

These are present in Pro++ last time I checked. In Light, there *are* related domains blocked (`||felix.data.tm-awx.com^` and `||reach-id.orbit.tm-awx.com^`) but not the above two. I can't find out much about this domain, but blocking it at root with `||tm-awx^` stopped all the variations showing up in my Allowed logs, and again no user reports of breakage or any impact at all for many weeks now. 

Perhaps you could consider these for Light - Pro, or maybe you already have some knowledge of them and their lack of inclusion? As always, thanks for the hard work and the excellent lists! 

Best wishes,

Lee / Rainmaker

**Comment by hagezi** [comment]
Thanks for the support Lee, I see no reason not to add these domains.
