### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by MasterKia** [hagezi/dns-blocklists#1151]
For similar issues, see:
- https://github.com/AdroitAdorKhan/EnergizedProtection/issues/46
- https://github.com/bongochong/CombinedPrivacyBlockLists/issues/14
- https://github.com/blocklistproject/Lists/discussions/670

Your [license](https://github.com/hagezi/dns-blocklists/blob/6ade22b98f19e11c5dee9dc057c843eb09b41270/LICENSE.md) is incompatible with most, perhaps all, the host sources you list and aggregate here.

Some (or most) licenses require at least **attribution**, so you need to actually specify the licenses of _each_ list you're using (something like this):
https://github.com/EnergizedProtection/block#sources

**Comment by hagezi** [comment]
Apart from the fact that you cannot license or copyright lists that simply contain existing domains, in my opinion, every file contains a header. For the lists that contain only my own entries, this is MIT.
For the lists that also consist of other sources, no license is listed.

For the sources used at https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md there is the following note: _(for the individual licenses of the sources, see the source files or source repositories!)_

**Comment by hagezi** [comment]
> Also, Licensing the whole aggregated list as MIT creates the false illusion that _**everything**_ in this repo is under that license, which clearly is not.

This is indeed confusing, so the license was shown in the header of the doamin lists if it is MIT.
But I have no problem removing the license file from the repository.

**Comment by hagezi** [comment]
License has been removed.
