### ISSUE TITLE
Protected

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#1154]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

totalav.com
install.protected.net
totaladblock.com

### Why should the domain(s) be unblocked?

It appears Total AV's website and most, if not all their subdomains snuck into all the blocklists. `install.protected.net` is also needed to download the trial of Total AV. protected.net is associated with Total AV. `totaladblock.com` is their ad blocker.

**Comment by hagezi** [comment]
This is badware and remains blocked.

**Comment by markangus2b** [comment]
After looking more into this program, I completely agree with you. Ugh I am such an idiot. Countless horror stories of people trying to cancel and being charged 100s of dollars. 

While I've heard of the name before, I recently saw them referenced on Kim Komando's website and figured she was trustworthy. I guess not. Here is the article with Total AV as a sponsor of her.
https://www.komando.com/security-privacy/bad-apps-hiding-malware/888369/?utm_medium=nl&utm_source=tctnw&utm_content=2023-06-11

Thank you Gerd for being on top of everything! 🥇
