### ISSUE TITLE
Payback iOS app start issue

### ISSUE THREAD

**Issue by lyrad87** [hagezi/dns-blocklists#1155]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

adsdk.adfarm1.adition.com

### Why should the domain(s) be unblocked?

I installed the Payback iOS app and every time I wanted to use the app, it immediately closed. When I checked the logs, I saw the above mentioned domain and added it to my personal Allowlist. The app started normally again afterwards and I was able to log in. I disabled the domain again and the app starts and works normally now even though the domain is blocked. So just the initial load of the app didn’t work at first. It’s fine if you want to leave it blocked and this is something for the personal Allowlist but thought I at least mention it here.

**Comment by hagezi** [comment]
I also use the PayPal app on iOS and cannot reproduce the problem. The domain is also not called in my region.

This is a popular ad domain, so I would not like to unblock it. Apart from that, it is pretty cheeky to link the function of such an app to such a domain. I would write to the support.

**Comment by lyrad87** [comment]
Ok, fair enough. It started suddenly. The app was working fine for months but after one of the last updates I started having the described issue. Just took my time now to find the cause of the issue and it was the mentioned domain. It’s blocked now again and everything works as it should. I’ll mention it to their support but I doubt they will do anything about it. Thanks for the reply and enjoy the rest of your evening.

**Comment by lyrad87** [comment]
Ok, fair enough. It started suddenly. The app was working fine for months but after one of the last updates I started having the described issue. Just took my time now to find the cause of the issue and it was the mentioned domain. It’s blocked now again and everything works as it should. I’ll mention it to their support but I doubt they will do anything about it. Thanks for the reply and enjoy the rest of your evening.
