### ISSUE TITLE
Why is Gibson Research Corporation blacklisted?

### ISSUE THREAD

**Issue by XenHat** [hagezi/dns-blocklists#1157]
I find the [Gibson Research Corporation](https://www.grc.com/intro.htm) website fairly useful to debug network issues, and I don't really see anything wrong with it.

Is there some story I'm not aware of about this domain or their authors to justify it being blocked?

**Comment by hagezi** [comment]
grc.com is not blocked.

**Comment by XenHat** [comment]
> grc.com is not blocked.

![image](https://github.com/hagezi/dns-blocklists/assets/980408/a023e1ff-fdb1-4fc8-8b4d-fb6cb032afa4)

![image](https://github.com/hagezi/dns-blocklists/assets/980408/d235ab05-71a6-4f55-b708-c34058bd009d)

**Comment by hagezi** [comment]
OK, I hadn't checked the anti piracy list, it will be removed in the next update.

**Comment by hagezi** [comment]
fixed.
