### ISSUE TITLE
Spotify web player is not working gae2-spclient.spotify.com

### ISSUE THREAD

**Issue by lthedetective** [hagezi/dns-blocklists#1158]
please fix this issue

**Comment by lthedetective** [comment]
Currently using ultimate with controld.

**Comment by lthedetective** [comment]
gae2-spclient.spotify.com 
I think this is the domain

**Comment by hagezi** [comment]
ping source @bongochong

**Comment by hagezi** [comment]
@lthedetective fix is online

**Comment by bongochong** [comment]
Thanks @hagezi! Fixing this as well. Appears to have slipped in very recently.
