### ISSUE TITLE
FP ipinfo.io

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#116]
Hi Gerd,

The Ultimate lists is blocking `ipinfo.io`, an info site displaying information about the user's IP address(es). The domain can also be called by CLI/terminal apps to display the user IP. 

I know the lists have different approaches and sources, but I also note that the pro.plus.txt and pro.txt both block specifically `pixel.ipinfo.io` but not the main root domain. Ultimate, on the other hand, only blocks `ipinfo.io`. 

I would personally consider this a false positive (unless there's something I missed?). In that case, I would request/suggest you remove `ipinfo.io` from Ultimate, and replace it instead with the more targeted `pixel.ipinfo.io` as per the other lists. 

Best wishes,

Lee

**Comment by hagezi** [comment]
Thanks Lee, you 're right. Removed. I will add `pixel.ipinfo.io` on next full update.

ping @lassekongo83: https://github.com/lassekongo83/Frellwits-filter-lists/blob/a984408ecb7dfbfde99d1a431c7751b6144ee084/Frellwits-Swedish-Hosts-File.txt#L510

Thanks for your help,
Gerd
