### ISSUE TITLE
falsely blocked

### ISSUE THREAD

**Issue by aykirito** [hagezi/dns-blocklists#1166]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

http://void-scans.com/
http://hiperdex.com/

### Why should the domain(s) be unblocked?

this two domain is webtoon comic sites.

**Comment by hagezi** [comment]
`void-scans.com` ist not blocked, i can access the site via NextDNS using Ultimate.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/a31f4e42-cee7-4981-a02e-16825353c4b9)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/7ca7debf-1c83-41f8-8033-128914b69196)
