### ISSUE TITLE
AppSpot

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#1168]
### Which domain(s) should be blocked?

`*.appspot.com`

### Why should these domain(s) be blocked?

Sorry for the addition, Gerd @hagezi. I forgot this one for my BMW App issue (#1167), which is now closed. I noted in my logs also that `bmw-a4a.appspot.com` is targeted when the BMW app is open. Again, there seems to be no detriment to the user when it is blocked. 

Light currently includes no less than 91 subdomains of [AppSpot](https://whotracks.me/trackers/google_appspot.html), a Google cookie-based tracker. Is it possible to again clean up all these extra entries, and instead block just `||*.appspot.com^`, or even the root domain (I don't know if it provides anything useful on its home page)? Otherwise, if that's not possible I'm once again sorry to ask you to please consider adding the specific URL `||bmw-a4a.appspot.com^` instead. 

Thanks (again!).

Lee / Rainmaker

**Comment by hagezi** [comment]
You can't block appspot.com completely, that breaks some things.
