### ISSUE TITLE
Add “uttheeeds.xyz”

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#117]
On the free movie streaming site soap2day.to I get a malicious spam notification on my iPhone to add the uttheeeds.xyz calendar to my iphone.

**Comment by hagezi** [comment]
Thanks, will be added on the next full update in a few hours.

**Comment by devipasigner** [comment]
> Thanks, will be added on the next full update in a few hours.

Thank you .
By the way I noticed that this domain is already on 1hosts xtra, the only list that has it. I also noticed that it finds a ton of ad domains not found on other lists, honestly very impressed. Any idea what source it’s using to find these so quickly?

**Comment by devipasigner** [comment]
I’m considering adding 1hosts xtra to my blocklists in AdGuard home with your whitelist and blocklists.

**Comment by devipasigner** [comment]
Would you consider using it as a source in pro plus and ultimate? Or are you worried about potential false positives. Though I will say in my 3 days of using it with your pro plus referral whitelist and regular pro plus whitelist I’ve only experienced one minor false positive

**Comment by devipasigner** [comment]
current list im using in my household
![image](https://user-images.githubusercontent.com/113001348/209030225-f71416d8-af87-4da7-a75d-d5676a393034.png)
![image](https://user-images.githubusercontent.com/113001348/209030244-c4f44267-5bd6-4ebd-808f-426dbf66da86.png)

**Comment by hagezi** [comment]
@devipasigner 
I think in Xtra services for NRDs (new registered domains), top lists and certain search patterns are used to find such domains. I don't know though, just a guess.

Xtra is not an option for the Pro++, it is too strict and has too many potential false positives for the masses.

For the Ultimate I could think about adopting the Xtra, at least in parts. But I'm not sure if I really want to do that, it also involves some maintenance.
But, I will try to transfer the domains of the Xtra to the Ultimate, which are on the Umbrella 1 Million Toplist. I will use an extended whitelist to minimize potential false positives.

**Comment by hagezi** [comment]
Try the ultimate with referral whitelist only.

**Comment by devipasigner** [comment]
> Try the ultimate with referral whitelist only.

The Pro Plus referral whitrlist or general one?

**Comment by devipasigner** [comment]
> Try the ultimate with referral whitelist only.

Difference between https://raw.githubusercontent.com/hagezi/dns-data-collection/main/data/pro.plus-removed-referral.txt
and 
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist-referral.txt

**Comment by devipasigner** [comment]
> @devipasigner I think in Xtra services for NRDs (new registered domains), top lists and certain search patterns are used to find such domains. I don't know though, just a guess.
> 
> Xtra is not an option for the Pro++, it is too strict and has too many potential false positives for the masses.
> 
> For the Ultimate I could think about adopting the Xtra, at least in parts. But I'm not sure if I really want to do that, it also involves some maintenance.

Thank you I understand

**Comment by hagezi** [comment]
> > Try the ultimate with referral whitelist only.
> 
> 
> 
> Difference between https://raw.githubusercontent.com/hagezi/dns-data-collection/main/data/pro.plus-removed-referral.txt
> 
> and 
> 
> https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist-referral.txt

One is the list of removed domains, the other is the whitelist.
There is also a special version of the referral whitelist for use in AGH:
https://github.com/hagezi/dns-blocklists/blob/main/adblock/whitelist-referral.txt

**Comment by devipasigner** [comment]
> > > Try the ultimate with referral whitelist only.
> > 
> > 
> > Difference between https://raw.githubusercontent.com/hagezi/dns-data-collection/main/data/pro.plus-removed-referral.txt
> > and
> > https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist-referral.txt
> 
> One is the list of removed domains, the other is the whitelist. There is also a special version of the referral whitelist for use in AGH: https://github.com/hagezi/dns-blocklists/blob/main/adblock/whitelist-referral.txt

Thank you Gerd and Merry Christmas! I do have a few questions regarding the allowlists.

1. what’s the difference between the removed domains and whitelisted domains? The white listed domains does contain the removed domains too right?

2. Is it better to use the Pro Plus removed domains or general allowlist? Is the allowlist the removed domains from all lists(light, pro, pro plus, ultimate)?, if so then surely I wouldn’t want to use it because I wouldn’t get the benefits of the pro plus list?
3. How come each multi list has different whitelisted referral domains?

**Comment by hagezi** [comment]
I use whitelists to generate my block lists. The domains on the whitelist are removed during generation. The removed domains are shown on the removed lists.

**Comment by devipasigner** [comment]
> 

So using the pro plus removed domains is the same as using the whitelist, correct?

**Comment by hagezi** [comment]
On the whitelist are also preventive entries, such as google.com, which do not necessarily have to appear in the removed lists, because they were not on the source, so they were not removed.

So no, removed is not identical with the whitelist.
