### ISSUE TITLE
daumcdn.net

### ISSUE THREAD

**Issue by green1052** [hagezi/dns-blocklists#1174]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

daumcdn.net

### Why should the domain(s) be unblocked?

its cdn

**Comment by green1052** [comment]
@hagezi

**Comment by green1052** [comment]
![image](https://github.com/hagezi/dns-blocklists/assets/34261355/0ec52a28-1e6d-4d1e-b154-0ff488a0ed03)

**Comment by green1052** [comment]
not wokring

**Comment by green1052** [comment]
last update 06/21/23

**Comment by hagezi** [comment]
daumcdn.net not blocked, blocked are:

```
adimg.daumcdn.net
img-ad-img-vp.daumcdn.net
m1.daumcdn.net
t1.daumcdn.net
t1.daumcdn.net.edgesuite.net
```

Which of them lead to which restrictions?

**Comment by green1052** [comment]
t1.daumcdn.net

**Comment by hagezi** [comment]
Thanks, added to allowlist:

```
t1.daumcdn.net
t1-wg2vgaja.kgslb.com
t1.daumcdn.net.edgesuite.net
m1.daumcdn.net
m1-daum-apcajdmm.kgslb.com
```
