### ISSUE TITLE
GoodbyeAds Spotify

### ISSUE THREAD

**Issue by Eow2022yia** [hagezi/dns-blocklists#1177]
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt

Hi there,

Would you please consider adding GoodbyeAds Spotify to the Plus++ and Ultimate lists?

This can reduce Spotify ads and it does not break the app/website.

Thank you.

**Comment by hagezi** [comment]
Domains that do not restrict any functions are already blocked.

**Comment by Eow2022yia** [comment]
Hi there,

May I please ask. Has this list been directly added into yours?

Or only parts of them?

**Comment by hagezi** [comment]
No, I do not use this list as a source.

**Comment by Eow2022yia** [comment]
> No, I do not use this list as a source.

Oh, could you use it?

**Comment by hagezi** [comment]
No
