### ISSUE TITLE
Add Zerodot1 and other anti cryptojacking miners litsts

### ISSUE THREAD

**Issue by trimechee** [hagezi/dns-blocklists#1178]
### Which domain(s) should be blocked?

Hello, thank you very much for these amazing revolutionary blocklists recommanded by many users and experts ! 🥇 💯 

https://github.com/yokoffing/NextDNS-Config#blocklists-1

https://github.com/yokoffing/filterlists

Please i have request : the fundamental problem in the web actually is the dangerous crypto currency mining who can ruin us and cause harm to ecology and it is the main threat on the internet, the pirates use sophisticated techniques like using a very small power of our processor without realising it and without clicking on any link despite your web browser is up to date,
and Webassembly Tehnology (WASM) is enabled by default in web browsers but

WebAssembly may be used, just like JavaScript, to “steal” processing power instead of data. In 2019, an analysis of 150 different Wasm modules found out that about 32% of them were used for cryptocurrency-mining.

https://training.linuxfoundation.org/blog/webassembly-security-now-and-in-the-future/

Though Wasm has been around for a few years, it rose to prominence more recently when it was used for cryptocurrency mining in browsers. This opened a Pandora's box of potential malicious uses of Wasm.

https://www.virusbulletin.com/virusbulletin/2018/10/dark-side-webassembly/

So I think it's necessary for the average user who does not care about Crypto sites to have peaceful mind that the resources of his computer are not stolen, Zerodot1 is very famous and his list used by many famous software, and it doesn't matter  
this block evenlegitimate  crypto miners because mayn people don't use cryptoans  some miners use so sophisticated techniques to only use a small amount of CPU power which makes it undetectable....
so my suggestion is to add  zerodot1 lists to the list "Threat Intelligence Feeds - Increases security significantly!" 

because in the sources of the list TIF , i don't see zedot1 list 

 https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#tif

and plesase it will be great to add also zerodot1 lists to Multi PRO - Extended protection or Multi PRO++ - Maximum protection or Multi ULTIMATE - Aggressive protection !

i search and ifnd these amazing anti cryptojacking lists,  it will be great to integrate them to Multi PRO++ - Maximum protection or Multi ULTIMATE - Aggressive protection !
 Thank you :)

https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issuable_template=CryptoMiner
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt
https://blocklistproject.github.io/Lists/adguard/crypto-ags.txt
https://blocklistproject.github.io/Lists/crypto.txt
https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_UBO.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_browser
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser_AdBlock.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_optional
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_optional.txt
https://raw.githubusercontent.com/olbat/ut1blacklists/master/blacklists/cryptojacking/domains

### Why should these domain(s) be blocked?

There is many dangerous hidden secret crypto domains !

**Comment by hagezi** [comment]
Thank you, the ZeroDot lists practice cryptocensorship, which has nothing to do with cryptojacking. That's why I don't use them as a source.

I'll have a look at the other lists, but most of them probably contain a lot of dead domains and inflate the lists without providing any real added value.

I have already reached a list size where you have to decide exactly what to add and what not. Cryptojacking is also blocked by other sources used.

**Comment by iam-py-test** [comment]
> https://blocklistproject.github.io/Lists/adguard/crypto-ags.txt
> https://blocklistproject.github.io/Lists/crypto.txt

These two are the same list in two different formats. Also [(sadly) the BlocklistProject lists seem to currently be unmaintained](https://github.com/blocklistproject/Lists/commits/master).
> https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt

This doesn't seem to be a huge list, and it relies a lot of regexes which won't work in this list (I think)
