### ISSUE TITLE
Spotify Song Links (Android)

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#1179]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

api2.branch.io

### Why should the domain(s) be unblocked?

With this domain blocked, Spotify song links don't redirect to the Android app properly. Specifically, the track will not display or play within the Android app. I am using a Samsung Galaxy S22. The Windows version of Spotify doesn't appear to be affected.

Example
https://open.spotify.com/track/3Ea8cCWHFBWy8XaDRO7fK7?si=m6vWyyQCRvua4DSJ3g1uOg

**Comment by hagezi** [comment]
No problems on iOS. branch.io is a popular tracker and therefore something for the personal allowlist.
