### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by tsweet64** [hagezi/dns-blocklists#1181]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole, uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++, Threat Intelligence Feeds, Most Abused TLDs

### Which domain(s) should be unblocked?

Threat intelligence feed: `files.catbox.moe`
Most Abused TLDs: `lemmy.zip`, `toast.ooo`, `audioforyou.top`

### Why should the domain(s) be unblocked?

`files.catbox.moe` is a legitimate and moderately widely used file & image hosting site (often for images on forums, etc). It presumably is sometimes used to host malicious files (much like cdn.discordapp.com often is) but the site itself is not malicious.

`lemmy.zip` and `toast.ooo` are lemmy instances, and `audioforyou.top` is a music site.

**Comment by hagezi** [comment]
ping for TLD exclusion:

@yokoffing : `lemmy.zip`
@dandelionsprout : `toast.ooo` and `audioforyou.top`
