### ISSUE TITLE
question with hosts Multi pro++

### ISSUE THREAD

**Issue by gallegonovato** [hagezi/dns-blocklists#1185]
Good afternoon @hagezi

Thank you very much for your help and time.

One question if you don't mind. I have been using your hosts for some time now. And today looking a little more in depth I see that you use StevenBlack's source. 

I use from StevenBlack in Adaway the Unified hosts + fakenews + gambling + porn + social that would be https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

But porn pages didn't visit any ever. That's why I thought to remove it and since you use StevenBlack's for the hosts. Leave yours Multi pro++. And if that put the StevenBlack addon fakenews + gambling + gambling + social https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social-only/hosts . 

I also use the one of D3ward that I do not know if it is included in the Multi pro++? and the one of GoodbyeAds that also I do not know if it subtracts?

I don't know if I'm doing it right or I'm getting confused.

Thanks for your help and time.

**Comment by hagezi** [comment]
The sources used are listed here: https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md

In addition, own extensions are used.
