### ISSUE TITLE
Bing Chat - Page Context

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#1186]
I’m having trouble with the Page Context feature in Bing Chat’s sidebar in Edge. [This feature is supposed to show me relevant information from the web based on my chat conversation](https://www.microsoft.com/en-us/edge/features/bing-chat)[1](https://www.microsoft.com/en-us/edge/features/bing-chat). However, it doesn’t work when I block any bing.com domain.

Can you please confirm if this is a bug or a configuration issue? I’ve tried whitelisting the bing.com domain and the Page Context feature works fine then

**Comment by hagezi** [comment]
@gyCfjSnO Can you please check which domain exactly leads to the behaviour? I can't test it at the moment.

**Comment by markangus2b** [comment]
@gyCfjSnO I enabled the "Page Context" feature on Edge and could not reproduce what you described above. I have included a screenshot in order to ensure we are on the same page.

https://1drv.ms/i/s!AsONhnQnF9H0ge1BYWsSBiZKcDTg3w?e=QWUsq0

**Comment by hagezi** [comment]
@markangus2b Thanks for testing, 
I have now also been able to test and cannot reproduce the problem.
