### ISSUE TITLE
Include easyprivacy blocklist and adguard cname blocklist

### ISSUE THREAD

**Issue by lthedetective** [hagezi/dns-blocklists#1188]
### Which domain(s) should be blocked?

these blocklists have many cname trackers not found in ultimate 
https://easylist.to/easylist/easyprivacy.txt
https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt

### Why should these domain(s) be blocked?

they have a lot of cname trackers not found in ultimate

**Comment by hagezi** [comment]
Hi,

- EasyPrivacy is included
- AdGuard disguised CNAME Trackers is not a list that should be used 1:1 as a block list, it rather serves as documentation, that's also what the AdGuard team says. CNAME trackers are already blocked in my lists. The list contains a lot of "rubbish", if you sort it out, 15% of the over 300000 domains remain.
- Blocking `firebaseinstallations.googleapis.com` breaks some Apps.

**Comment by lthedetective** [comment]
some cname of domains such as 

path1.xtracloud.net
path3.xtracloud.net

are blocked by easyprivacy but not blocked by hagezi lists

**Comment by hagezi** [comment]
Yes, that is correct and for good reason:

```
Optimized mobile GPS Data - A-GPS Qualcomm - also used in emergencies
# https://teddit.net/r/privacy/comments/12yii9u/comment/jhojlr7/
# https://github.com/hagezi/dns-blocklists/issues/1023
path1.xtracloud.net
path2.xtracloud.net
path3.xtracloud.net
```
