### ISSUE TITLE
yt3.ggpht.com

### ISSUE THREAD

**Issue by DSnva** [hagezi/dns-blocklists#1191]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

yt3.ggpht.com

### Why should the domain(s) be unblocked?

https://i.imgur.com/byvjI3I.png  
Because of this, some of the channel icons on YouTube disappeared.

By the way. In one country, this domain was blocked at the government level. https://reestr.rublacklist.net/ru/record/4285828/
And all because of one picture: https://yt3.ggpht.com/F02Qk_T2Hlip9e8MfUkuy_0yE2YYj_HK9O086UTnySiuUvM4uH8ZlEepgXvpsjY9NGjvvL-Pd_ID_Q=s640-nd-v1

**Comment by hagezi** [comment]
Besides Google, there are also some apple doamins, the contaminated source is https://raw.githubusercontent.com/Cats-Team/AdRules/main/ad-domains.txt this is now flying out completely. @Cats-Team
