### ISSUE TITLE
Google Play App Downloads

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#1192]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

play.googleapis.com

### Why should the domain(s) be unblocked?

While this appears to be a prevalent tracker. Blocking this domain blocks apps from downloading on Google Play Store.

**Comment by hagezi** [comment]
Besides Google, there are also some apple doamins, the contaminated source is https://raw.githubusercontent.com/Cats-Team/AdRules/main/ad-domains.txt this is now flying out completely. @Cats-Team
