### ISSUE TITLE
Possible scam

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#1193]
### Which domain(s) should be blocked?

coinaps.com

### Why should these domain(s) be blocked?

I got this DM on twitter 

Hi, . 🚀 Get 500 USDT NOW! 🔥 [@tingsonpatricia](https://twitter.com/tingsonpatricia)

🚨This guy is giving away 500 USDT to everyone! And also shows how to trade crypto in + in his profile - [@tingsonpatricia](https://twitter.com/tingsonpatricia)
 🚀🚀🚀🚀

🔥🔥🔥 Do not miss the chance to get 500 USDT 💸 from crypto exchange, all information you will find here! [@tingsonpatricia](https://twitter.com/tingsonpatricia)
  🔥🔥🔥 

💥 Here you can learn how to buy 📉 cheap and sell more expensive 📈 crypto, as well as get 500 USDT for free! 😱😱😱 [@tingsonpatricia](https://twitter.com/tingsonpatricia)

**Comment by iam-py-test** [comment]
Add to my list. Thank you

**Comment by durablenapkin** [comment]
Queued, thanks
