### ISSUE TITLE
Huge amount of the internet is being blocked due to OCSP servers being blacklisted

### ISSUE THREAD

**Issue by t3dium** [hagezi/dns-blocklists#1198]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

amazontrust.com (and its subdomains)
ocsp.godaddy.com
ocsp.pki.goog
ocsp.globalsign.com

Are some of the ones i found, there may be more

### Why should the domain(s) be unblocked?

The false positives above leads to firefox (when having ocsp set to hard fail mode) refusing to load a lot of websites:

![librewolf_yCMc6T5TfW](https://github.com/hagezi/dns-blocklists/assets/83690012/135fca53-ec96-4e66-bb8d-eea2d9116799)

**Comment by iam-py-test** [comment]
I don't see any of those listed in ULTIMATE. Maybe they are being blocked via CNAME

**Comment by hagezi** [comment]
@t3dium 

Update the list, there was a contaminated intermediate state yesterday because an allowlist was used as a blocklist in one source, details: https://github.com/AdguardTeam/HostlistsRegistry/issues/239#issuecomment-1601610003

I fixed this yesterday and the source was removed.

**Comment by t3dium** [comment]
ah my lists were a bit outdated, i can confirm the issue's fixed after updating them
