### ISSUE TITLE
tradehq.com

### ISSUE THREAD

**Issue by pceiley** [hagezi/dns-blocklists#1200]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

tradehq.com

### Why should the domain(s) be unblocked?

This is a legitimate site used by tradespeople to send quotes.

**Comment by hagezi** [comment]
Flagged as phishing by Phishing Army and therefore blocked. I'll take a closer look later.

**Comment by hagezi** [comment]
It is still actively marked as phishing:

https://www.phishtank.com/phish_detail.php?phish_id=8155552&frame=details

The operator of the site should request a removal of the flags if the domain is "clean", then the domain will also disappear from my lists.
