### ISSUE TITLE
onnetwork.tv

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#1205]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

cdn.onnetwork.tv
video.onnetwork.tv

### Why should the domain(s) be unblocked?

Video playback is blocked
https://www.meczyki.pl/newsy/bayern-monachium-dogadal-sie-z-nowa-gwiazda-mistrzowie-niemiec-coraz-blizej-upragnionego-transferu/214854-n
![Zrzut ekranu z 2023-06-27 17-09-27](https://github.com/hagezi/dns-blocklists/assets/125269947/1a8aef04-6e38-4ae9-a39a-ccec5a53d171)

**Comment by hagezi** [comment]
Thanks @flav0ring, I had already noticed, so I put the following on the Allowlist:

```
cdn*.onnetwork.tv
video*.onnetwork.tv
```

Gerd
