### ISSUE TITLE
Add fafr.fun to allowlist

### ISSUE THREAD

**Issue by hann315** [hagezi/dns-blocklists#1214]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

fafr.fun

### Why should the domain(s) be unblocked?

I own this domain and use it only for AdGuard Home DNS on public server. The root domain name isn't used for any website.

<img width="960" alt="image" src="https://github.com/hagezi/dns-blocklists/assets/64533786/d0fdbdd8-78c9-487e-b65f-d5abc2cadcda">

**Comment by hagezi** [comment]
ping @yokoffing for exclusion

**Comment by yokoffing** [comment]
done
