### ISSUE TITLE
A few false positive

### ISSUE THREAD

**Issue by Ry3nlNaToR** [hagezi/dns-blocklists#122]
Hi, A few false positives static.cdn.responsys.net the rule is from the personal list that domain was used for static content e.g. images in a marketing email I received, that domain seems to be used for Oracle Responsys Campaign Management https://www.oracle.com/uk/cx/marketing/campaign-management/.

The 2nd one was wab.performfeeds.com the rule was ||performfeeds.com^ from personal list  that domain is used by  [Stats Perform](https://www.statsperform.com/)  sports data provider blocking that domain broke the game stats and live steam on a betting site I think it was Bet365 I don't bet my self a other member of the household was;n't too happy 😆.

Just wondering how the personal list compiled is it just purely own entry  or is it based on another list.

**Comment by hagezi** [comment]
Thanks, removed.

The list is based on my manually maintained blacklist and various DNS logs from my environment using services such as domain categorisation, Tracker Radar, top lists and so on.
I'll have to take a closer look at why the domains ended up on the list. Apparently there is still potential for optimisation here.

**Comment by Ry3nlNaToR** [comment]
> Thanks, removed.
> 
> The list is based on my manually maintained blacklist and various DNS logs from my environment using services such as domain categorisation, Tracker Radar, top lists and so on. I'll have to take a closer look at why the domains ended up on the list. Apparently there is still potential for optimisation here.

Hi thanks for the insight how you compile that list, no system is going to be perfect some fp are always going to happen.

Am away for a number of days over the Christmas holidays  I've temporarily disabled you're list on the Adguard home running back at my place just in case any more FP and am not around to fix, if I really needed to I can vpn to my home lan, at the moment am running OISD with 1Host lite with you're whitelist and refers whitelist so should be a quite safe config for any breaks.
