### ISSUE TITLE
(Broken app) mobile-data.onetrust.io

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#123]
Season's greetings, Gerd.

Certainly there's no rush for this at Christmas! However, our traditional Christmas Eve takeout meal was interrupted, because the app failed to load due to a network error caused by Ultimate (which I am still testing). The responsible domain was `mobile-data.onetrust.io`. 

Pro and Pro++ both block some onetrust domains (actually, 26 in Pro++), but Ultimate blocks from the root domain `onetrust.com`, as well as some others: 

```
||onetrust.cc^
||onetrust.com^
||cookies-data.onetrust.io^
||mobile-data.onetrust.io^
```

It is the last domain here that caused issues with legitimate app function. 

OneTrust seems to be an anti-fraud and consent/cookies company. Several other domains belonging to this company were blocked while using the app, including `cdn-ukwest.onetrust.com`, but they did *not* need to be whitelisted for the app to work. The only domain breaking functionality was `mobile-data.onetrust.io`. Perhaps you could consider whitelisting it?

As an aside, it seems that that other discovered URL `cdn-ukwest.onetrust.com` is not included in any of your lists (except Ultimate, because of the root domain `||onetrust.com^`). Maybe you could also consider adding `||cdn-*.onetrust.com^` to Pro++ to catch these CDNs?

All the best to you, with thanks for all your efforts.

Lee

**Comment by hagezi** [comment]
Merry Christmas and once again a big thank you Lee for your help and support. I was knocked out by soup coma after Christmas dinner yesterday - I'm getting old. ;)

I have removed the domain from the Ultimate. I'll add the CDNs later.
I'll leave the issue open until it's done.

Happy holidays to you and your family,
Gerd

**Comment by RainmakerRaw** [comment]
> Merry Christmas and once again a big thank you Lee for your help and support. I was knocked out by soup coma after Christmas dinner yesterday - I'm getting old. ;)

Alas, that makes two of us! :) Merry Christmas, Gerd and family. I hope you have a wonderful day. CDNs can wait!

**Comment by hagezi** [comment]
The following CDNs have been added:
```
cdn-ukwest.onetrust.com
cdn-apac.onetrust.com
cdn-au.onetrust.com
```
They will be added to the lists in the next update.
