### ISSUE TITLE
American Express 2fa

### ISSUE THREAD

**Issue by kchen8898** [hagezi/dns-blocklists#1233]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT

### Which domain(s) should be unblocked?

omns.americanexpress.com

### Why should the domain(s) be unblocked?

Required for 2fa login. See https://discourse.pi-hole.net/t/omns-americanexpress-com-shouldnt-be-blacklisted-needed-for-2fa/50363

**Comment by hagezi** [comment]
Thanks, blocked because it is a disguised `omtrdc.net` Tracker, CNAME `americanexpress.com.ssl.d2.sc.omtrdc.net`, will be removed.

**Comment by Alex-302** [comment]
@hagezi it was excluded in our filter many years ago)
https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/05a2602ff73349a47aa0efe862af6e35f024d316/Filters/exclusions.txt#L832
![image](https://github.com/hagezi/dns-blocklists/assets/8361299/6bbb8dff-a8c0-42e8-8619-3a99e560b3a2)
