### ISSUE TITLE
listrakbi.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#1238]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS, ControlD

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT, Multi PRO++

### Which domain(s) should be unblocked?

Listrak is listed as Customer Interaction in WhoTracks.Me / Ghostery database. Blocking it breaks the email subscription preferences at `https://www.andrewchristian.com/prefcenter`.

You don't have it as an option above, but this also affects HaGeZi's Personal DNS Blocklist.

If I set my DNS to Cloudfare in Chrome, and "trust" Listrak in Ghostery, the page loads.

### Why should the domain(s) be unblocked?

```
https://cdn.listrakbi.com/scripts/script.js?m=VWo1O9CF0GF2&v=1
https://s1.listrakbi.com/VWo1O9CF0GF2/session/getIds?callback=ltkCallback7683&gsid=755a7482-fa4a-462a-82df-40e32dd67ff6&_sid=938b9a8b-b37f-49cb-ad0f-f188e8b1c695&_tid=VWo1O9CF0GF2&ps=null&dps=true
https://bl.listrakbi.com/api/ActivityEvents/PageBrowse
https://bl.listrakbi.com/api/ActivityEvents/PageBrowse
https://cdn.listrakbi.com/css/animate.min.css
https://at1.listrakbi.com/activity/VWo1O9CF0GF2?vuid=443
```

**Comment by yokoffing** [comment]
Test on your end: With using uBlock Origin, I got the page to load if I allowed `cdn.listrakbi.com`.

my filters:
```
@@||services.listrak.com^
@@||cdn.listrakbi.com/scripts/script.js^
||listrakbi.com^
```

**Comment by hagezi** [comment]
https://slayterdev.github.io/tracker-radar-wiki/domains/listrakbi.com.html

`listrakbi.com` belongs to the categories _Ad Motivated Tracking, Advertising, Analytics, Audience Measurement, Third-Party Analytics Marketing, Action Pixels_ and therefore blocked in my personal blocklist, furthermore also by some other lists

```
Blocklists:
 - 1Hosts.Lite     BLOCKED
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      BLOCKED
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        BLOCKED
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   BLOCKED
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            OK
 - QuidsUp.NOTRACK BLOCKED
 - StevenBlack     OK
```

I will unblock the CDN only for the non-aggressive lists to bypass the adblock detection. What do you mean @yokoffing?

**Comment by yokoffing** [comment]
> I will unblock the CDN only for the non-aggressive lists to bypass the adblock detection.

Yeah. That's what's needed here.

I didn't do too deep a dive. I was focused on troubleshooting breakage in-the-moment, as my partner was trying to unsubscribe from their emails.

Looks like there's **Listrakbi.com** and **Listrak.com**.

`cdn.listrakbi.com` allows `services.listrak.com`  to load. The former is needed to access `https://www.andrewchristian.com/prefcenter` and allow users to unsubscribe from their emails.
