### ISSUE TITLE
PRO Plus RPZ: Domainname length overflow 

### ISSUE THREAD

**Issue by mtheofy** [hagezi/dns-blocklists#1245]
Hi, 

Thanks for your work on the blocklist! A very valuable resource.

I am using the RPZ PRO Plus feed with unbound. Today I had to restart the resolver and unbound failed giving this error:
`2023-07-05T23:25:35.102738+03:00 sushi unbound: [840:0] error: parse error /etc/unbound/rpz/pro.plus.rpz 740810:256: Domainname length overflow
2023-07-05T23:25:35.103443+03:00 sushi unbound: [840:0] error: error parsing zonefile /etc/unbound/rpz/pro.plus.rpz for pro.plus.rpz.`

I opened the file and in line 740810 I noticed these two entries that exceed the 256 character limit.

`babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles CNAME .
*.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles CNAME .`

Manually deleting them from the RPZ file, fixed the problem.

These look like they are created through a concatenation operation.

Thanks again,
Marcos

**Comment by hagezi** [comment]
Thanks, WTF, via 1Hosts Pro, will be removed. I should adjust my valid Doamin examination ...

**Comment by hagezi** [comment]
Domain can be resolved:

```
; <<>> DiG 9.16.42-Debian <<>> algs.ir.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40124
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;algs.ir.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles. IN A

;; ANSWER SECTION:
algs.ir.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles. 5 IN A 18.195.223.182
algs.ir.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles. 5 IN A 18.197.102.72
algs.ir.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles. 5 IN A 3.77.57.56
algs.ir.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles. 5 IN A 18.156.163.177
algs.ir.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles. 5 IN A 18.192.209.254

;; Query time: 31 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Wed Jul 05 23:00:12 CEST 2023
;; MSG SIZE  rcvd: 362
```

**Comment by hagezi** [comment]
Because unbound can't handle it, I'm going to remove it anyway. It's actually a bug in Unbound, because the domain and the length is valid.

**Comment by mtheofy** [comment]
> Because unbound can't handle it, I'm going to remove it anyway. It's actually a bug in Unbound, because the domain and the length is valid.

I was about to ask you. I found out the same [here](https://github.com/NLnetLabs/unbound/issues/285). 
Thanks

**Comment by mtheofy** [comment]
For completeness sake, the second line (that begins with *.) exceeds the char limit.

**Comment by hagezi** [comment]
I use the following regex to check if it is a valid domain:

`(?=^.{4,253}$)(^(?:[a-zA-Z0-9](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+([a-zA-Z]{2,}|xn--[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$)`

**Comment by mtheofy** [comment]
> (?=^.{4,253}$)

You are hitting the goal post by using 253. If you add the 8 chars of " CNAME ." this is 256 characters that exceeds unbound's limit (255 I guess). Again, this is the case of the '*.' entry.

**Comment by hagezi** [comment]
`*.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles CNAME .` 
has a total length of 255 characters, the domain 245 characters

**Comment by mtheofy** [comment]
> `*.babol-ads.ir.tavansanatyazd.com.mesbahmousavi.ir.pegahzanjan.com.pezhvaktadbir.com.mortezaeskandari.ir.nurasoft.ir.jenabchap.com.kalanel.ir.barantee.net.ganjsaffron.com.cmmt.ir.jameema.ir.moshaverbashi.com.karyab-online.ir.kavirmotor.motorcycles CNAME .` has a total length of 255 characters, the domain 245 characters

I stand corrected. I was misled by the unbound's error message that quotes the number 256. I added `/usr/bin/awk 'length < 255'` in bash script pipeline that will filter out anything >=255

**Comment by hagezi** [comment]
Yes, the maximum domain length should not exceed 244 characters. 244+8+2
