### ISSUE TITLE
softwareupdates.amazon.com

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#1252]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home, Other

### Other

knot-resolver

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

softwareupdates.amazon.com

### Why should the domain(s) be unblocked?

Hello Gerd,

I think this one is self-explanatory. The Pro++ list is currently blocking updates to Amazon devices. Please can you remove? :) 

Best wishes,

Lee / Rainmaker

**Comment by hagezi** [comment]
WTF ...

**Comment by iReadTOS** [comment]
If it is possible to remove it, this is also blocked under ultimate as well.
