### ISSUE TITLE
OISD removed as a source?

### ISSUE THREAD

**Issue by nishaddesilva** [hagezi/dns-blocklists#1254]
Hi,

Was OISD removed from used sources because having it was redundant? Or any othe reason?

Thanks!

**Comment by hagezi** [comment]
As with the Light list, I have also switched to my own compiled extension for the Multi. Partly also with the Pro and the following lists. The quality of the lists was not affected by this.

**Comment by nishaddesilva** [comment]
For a ControlD user with only PRO list enabled should any other list be enabled or is just PRO list enough?

**Comment by hagezi** [comment]
Yes, Pro is enough. If you want more, try the Pro++.
