### ISSUE TITLE
Most Abused TLDs

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#1264]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

fmhy.ml

### Why should the domain(s) be unblocked?

Piracy guide and lemmy instance

**Comment by hagezi** [comment]
Thanks, ping @yokoffing for exclusion.

**Comment by yokoffing** [comment]
done
