### ISSUE TITLE
Most Abused TLDs

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#1265]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

lemmygrad.ml
aussie.zone
iusearchlinux.fyi
dormi.zone
crystals.rest

### Why should the domain(s) be unblocked?

 lemmy instances

**Comment by cinatime** [comment]
ping @yokoffing for exclusion.

**Comment by hagezi** [comment]
exclude `iusearchlinux.fyi` and `crystals.rest` from SpamHAUS TLDs
