### ISSUE TITLE
Maybe block this CNAME: **`cdn-dysxb.com`**?

### ISSUE THREAD

**Issue by vhpcdpgl** [hagezi/dns-blocklists#1286]
`www.f8ww.com` =>    CNAME `fgh.pt.cdn-dysxb.com`
`m.f8ww.com` =>    CNAME `fgh.mb.cdn-dysxb.com`

Some of others:
```
bdo.pt.cdn-dysxb.com
haon-jp.cdn-dysxb.com
rya.ke.maintain.cdn-dysxb.com
haon-seoul.cdn-dysxb
maintain.cdn-dysxb.com
```
Info:

```
https://urlscan.io/domain/cdn-dysxb.com
https://urlscan.io/search/#domain:%22cdn-dysxb.com%22
https://urlscan.io/search/#page.domain%3A(cdn-dysxb.com)
```
So can we block:
```
mb.cdn-dysxb.com
pt.cdn-dysxb.com
cdn-dysxb.com
```
?
_Originally posted by @vhpcdpgl in https://github.com/hagezi/dns-blocklists/issues/1284#issuecomment-1631828662_

**Comment by vhpcdpgl** [comment]
@hagezi

**Comment by vhpcdpgl** [comment]
`wintbr.com` => CNAME `axt.pt.cdn-dysxb.com`

**Comment by hagezi** [comment]
Yes, CNAMES will be added to gambling list.
