### ISSUE TITLE
Please check "myflixer.to" is being blocked

### ISSUE THREAD

**Issue by Domsicols** [hagezi/dns-blocklists#13]
It is a legitimate site for watching tv shows and movies.

Thanks in advance

**Comment by hagezi** [comment]
Hi, 

this Domain is flagged as malicious: https://www.virustotal.com/gui/domain/myflixer.to

I have checked the domain myself and see no reason to block it. Domain will be removed.

**Comment by hagezi** [comment]
Thanks, removed.
