### ISSUE TITLE
Native Tracker TikTok Extended (Fingerprinting) List Generation

### ISSUE THREAD

**Issue by ctaylor4874** [hagezi/dns-blocklists#1301]
Hello, I'd like to add the Native Tracker TikTok Extended (Fingerprinting) list to Adguard Home in addition to the pro list I'm using. Can we generate an Adblock list for it?

**Comment by hagezi** [comment]
Thank you, I can do that. I'll get to work on that in the next few days.

**Comment by hagezi** [comment]
@ctaylor4874 https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.tiktok.extended.txt
