### ISSUE TITLE
Edge Enterprise Sync

### ISSUE THREAD

**Issue by danclay** [hagezi/dns-blocklists#1304]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

edge-enterprise.activity.windows.com
edge.activity.windows.com
api.aadrm.com
api.aadrm.de
api.aadrm.cn

### Why should the domain(s) be unblocked?

These domains are used for edge enterprise sync as shown on section 4 of [https://learn.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync#issue-stuck-at-setting-up-sync-or-couldnt-connect-to-the-sync-server-retrying](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync#issue-stuck-at-setting-up-sync-or-couldnt-connect-to-the-sync-server-retrying). I noticed at least api.aadrm.com in the block list which was preventing Edge from syncing to my enterprise account. I do not know the other uses for these domains such as potential tracking.

**Comment by hagezi** [comment]
Hi, thanks

Not blocked in my Lists:
```
edge-enterprise.activity.windows.com
edge.activity.windows.com
```

`api.aadrm.*` will be unblocked.

Gerd
