### ISSUE TITLE
chrony.tuxfamily.org

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#1309]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home, NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++, Dynamic DNS, Badware Hoster, Most Abused TLDs, Anti Piracy, Gambling

### Which domain(s) should be unblocked?

chrony.tuxfamily.org

### Why should the domain(s) be unblocked?

This is the domain for Chrony(NTP) FAQ.

**Comment by hagezi** [comment]
Blocked in free hoster list because it is a free hoster ... ;)

**Comment by travisboss** [comment]
Touche
