### ISSUE TITLE
akamaihd

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#1311]
### Which AdBlocker/DNS cloud service do you use?

Other

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

see link; i’m currently traveling / out of the country.

### Why should the domain(s) be unblocked?

see https://www.reddit.com/r/nextdns/comments/150xwpr/firetv_app_downloads_blocked_with_hagezi/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1

**Comment by hagezi** [comment]
Thanks, my mistake, I'll remove the domain right away.
