### ISSUE TITLE
TMZ.com

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#1312]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Personal

### Which domain(s) should be unblocked?

TMZ.com

### Why should the domain(s) be unblocked?

Because it's not on any other list when checking [adtidy](https://urlfilter.adtidy.org/v1/checkDomain?domain=tmz.com) & [Blocklist Tools](https://blocklist-tools.developerdan.com/entries/search?q=tmz.com)

**Comment by hagezi** [comment]
@gyCfjSnO https://github.com/hagezi/dns-blocklists/issues/1302

**Comment by gyCfjSnO** [comment]
> @gyCfjSnO #1302

No other Blocklist has the domain blocked and it's not appropriate to chuck a domain on the list because someone tweeted that they're spreading fake news.

**Comment by hagezi** [comment]
@gyCfjSnO 

In principle I agree with you, but I had understood it to mean that the site mainly spreads fakenews. Ping @cinatime for clarification.

Whether it is blocked elsewhere or not is irrelevant to me. If it spreads mostly fakenews, it remains blocked, if not, it will be unblocked again.

I can't judge that conclusively and I don't have the time to analyse the news published there. I have relied on @cinatime.

**Comment by hagezi** [comment]
@gyCfjSnO  @cinatime

Since TMZ seems to be quite popular and there seem to be enough people reading this, I will unblock the domain for now. 

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/12d3ebd2-8adf-4d13-9b12-49912f3e3552)
