### ISSUE TITLE
Block "geolocation.onetrust.com"

### ISSUE THREAD

**Issue by HoVeRzzz** [hagezi/dns-blocklists#1325]
### Which domain(s) should be blocked?

geolocation.onetrust.com

### Why should these domain(s) be blocked?

Geolocation domain that doesn't break sites' usage
![image](https://github.com/hagezi/dns-blocklists/assets/103826368/cbe3b520-6bfe-4dca-96d3-b6e5ebfe9403)

**Comment by hagezi** [comment]
Blocking annoyances via DNS is always such a thing, especially if it somehow has to do with cookies.

Blocking annoyances should mostly be left to content blockers.

This domain interferes with Soundcloud and other sites in certain regions and is therefore on the Allow list.
