### ISSUE TITLE
Using "Encrypted DNS Servers only" with Diversion

### ISSUE THREAD

**Issue by BillyJoeJimBob** [hagezi/dns-blocklists#1329]
The DOH only list https://github.com/hagezi/dns-blocklists/blob/main/statistics.md#doh does not include the following lists from DOH-VPN-PROXY-BYPASS https://github.com/hagezi/dns-blocklists/blob/main/statistics.md#doh-vpn-proxy-bypass:

https://raw.githubusercontent.com/oneoffdallas/dohservers/master/list.txt

https://raw.githubusercontent.com/SystemJargon/blocklists/main/lists/categories/dns-dot-quic-doh/TheGreaterWall-dns-dot.txt

I am just interested in blocking encrypted DNS servers using Diversion, these 2 lists are not 100% overlapping with your DoH list. In your opinion would adding these lists to the DoH only list add any benefit over just using the DoH list (or cause issues)?

Thank you.

**Comment by hagezi** [comment]
That should make no difference, which DoH domains are you missing?

**Comment by BillyJoeJimBob** [comment]
I'm not aware of any specific missing domains.  I noticed that those 2 lists are included in the larger DOH-VPN-PROXY-BYPASS list but not the smaller DOH only list and wanted to know if they provided any further coverage of encrypted DNS servers.  If not, I'll just keep using the DOH list by itself, it's working great and much more up to date.  Thanks.

**Comment by hagezi** [comment]
I have checked it, it makes no difference in the end result. The lists have been removed, especially as they are no longer maintained.
