### ISSUE TITLE
FP stacksocial.com

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#133]
Dear Gerd, 

I hope you're recovering well from your Christmas indulgences!

The Ultimate list is blocking `stacksocial.com`, which for its faults does provide significant genuine discounts on software/goods. I see that Pro++ is simply blocking affiliate subdomains (in the format of `partners*.stacksocial.com`), but Ultimate blocks the domain root. Please consider whitelisting the root domain, and perhaps import the blocks from Pro++? Just a suggestion.  

All the best for a happy and prosperous new year in 2023.

Lee

**Comment by hagezi** [comment]
Thanks Lee, removed. The next update of the Ultimate will add the subdomains.

ping source: @kees1958

Thanks for the support and happy new year,
Gerd
