### ISSUE TITLE
(fake/scam) maxdebrid.com, debridlink.com, hotdebrid.com,

### ISSUE THREAD

**Issue by gototheskinny** [hagezi/dns-blocklists#1330]
### Which domain(s) should be blocked?

[https://maxdebrid.com](https://maxdebrid.com) [https://debridlink.com](https://debridlink.com) [https://hotdebrid.com](https://hotdebrid.com)
scam sites. exact same as : [https://github.com/hagezi/dns-blocklists/issues/409](https://github.com/hagezi/dns-blocklists/issues/409)

### Why should these domain(s) be blocked?

https://github.com/hagezi/dns-blocklists/issues/409 same reasons. mirror sites of https://github.com/hagezi/dns-blocklists/issues/409

**Comment by iam-py-test** [comment]
Added, thanks
