### ISSUE TITLE
Oxy.Cloud

### ISSUE THREAD

**Issue by badkill23** [hagezi/dns-blocklists#1333]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

download.oxy.st

### Why should the domain(s) be unblocked?

file hosting site

**Comment by hagezi** [comment]
Thanks, blocked because it is flagged. Source URLhaus malware. I will check ...

**Comment by hagezi** [comment]
https://www.virustotal.com/gui/url/ed6f960fcb673ee9dbf0e13a707f39418fa76641ca1da4102e0cdc6fbcb39de5

https://www.urlvoid.com/scan/download.oxy.st/

**Comment by iam-py-test** [comment]
There was only ever one URL and it has been taken down: https://urlhaus.abuse.ch/host/download.oxy.st/

**Comment by hagezi** [comment]
Thanks @iam-py-test
