### ISSUE TITLE
dr-farfar.com

### ISSUE THREAD

**Issue by 3xploiton3** [hagezi/dns-blocklists#1336]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

dr-farfar.com

### Why should the domain(s) be unblocked?

regular website, content provide software internet marketing

**Comment by hagezi** [comment]
Blocked because flagged as scam.

Source @durablenapkin @iam-py-test

We will check this.

**Comment by hagezi** [comment]
I checked it out, it doesn't seem to be a scam, but something for the anti piracy list.

**Comment by iam-py-test** [comment]
This seems to be from https://github.com/hagezi/dns-blocklists/issues/1116
I am looking into this

**Comment by durablenapkin** [comment]
Will whitelist: falls under piracy and not scam. Original reporter probably clicked on an ad on one of the third-party download links.
