### ISSUE TITLE
Amazon / FireTV / Alexa domains

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#134]
Greetings Gerd,

Me again! As promised last week, here are some extra Amazon/Alexa/FireTV domains. Most are not currently in your lists.

```
# Amazon/Alexa/FireTV
||andr-25-aftkmst12-641002610.api.amazonvideo.com^
||api.eu.amazonalexa.com^
||arcus-uswest.amazon.com^
||aviary.amazon.*^
||avs-alexa-19-eu.amazon.com^
||dcape-na.amazon.com^
||dp-gw-na.amazon.com^
||ftv-smtv.ntp-fireos.com^
||mads-eu.amazon.com^
||mas-ext-eu.amazon.com^
||o2r2hew432.execute-api.us-east-1.amazonaws.com^
||prod.amazoncrl.com^
```
We do have some FireTV 4K sticks, a Ring doorbell and an Echo Show 5. I dislike Amazon as a company, but the products are unfortunately very good and hard to say 'no' to when on sale! So, we lock them down instead (firewall, DNS). I hope you find these useful. We have found no breakage in functionality in any of the listed devices, Alexa still works fine, TV and video streaming works fine, etc. 

The only thing I still cannot block (and I have tried!) is the 'Sponsored' banner at the top of the FireTV home screen. If you know a trick, please do share it!

Best wishes as always,

Lee

**Comment by hagezi** [comment]
Hi Lee,

`aviary.amazon.*` blocked in light - ultimate
`mads*.amazon.com` blocked in light-ultimate

The following domains interfere with Alexa/Sonos/... (api and internet connection) as far as I know:
api.eu.amazonalexa.com
avs-alexa-*-eu.amazon.com

See (CNAME `a2z.com`):
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/809
https://github.com/easylist/easylist/issues/9474

For the others I have to do some research first, they are not found on common blocklists either. You would have to check with a proxy what is transferred when calling.

As for the sponsored ads, you can not block them completely, it once worked with `aviary.amazon.*`. But it does not seem to work completely anymore.

Thanks,
Gerd

**Comment by hagezi** [comment]
`mas-ext*.amazon.com` breaks Hulu, Shopping, possibly other services.

Don't like to block Amazon Apis, it's actually preprogrammed that there will be problems somewhere with external services:
```
*.api.amazonvideo.com
*.api.*.amazonalexa.com
*.execute-api.*.amazonaws.com
```

On some whitelists because of FireTV registration, downloads, ...
see: https://github.com/anudeepND/whitelist/issues/115
```
dcape-na.amazon.com 
arcus-uswest.amazon.com
```

I think it is only used to synchronize the time, not a tracker:
`ftv-smtv.ntp-fireos.com`

Required for the initial installation of a FireTV Stick:
see: https://github.com/EnergizedProtection/block/issues/616
`prod.amazoncrl.com`

Can't find anything concrete about the following domain, do you have the possibility to analyze with a proxy what is transmitted there?
`dp-gw-na.amazon.com`

So right now I don't see anything blockable without causing problems. It may be problem-free for individual users, but probably not for the masses.
Therefore I recommend you to leave them on your personal blacklist for now.

How do you see it?

Cheers,
Gerd

**Comment by RainmakerRaw** [comment]
Gerd, excellent as always. You clearly are ahead of me here, and as is usual your lists can be trusted to block the crud while allowing the necessary domains. Alas I promised to provide the list, and you helped me improve it. One small other domain remains, namely `advertising.amazon.dev`. 

In Ultimate, it is blocked as four subdomains: 

```
||actionable-video-ads.advertising.amazon.dev^
||track.pixel.prod-eu.turntable.sonic.advertising.amazon.dev^
||track.prod-eu.turntable.sonic.advertising.amazon.dev^
||track.pixel.prod-na.turntable.sonic.advertising.amazon.dev^
||track.prod-na.turntable.sonic.advertising.amazon.dev^
```
But in light-pro++ there is no mention. Is this for any reason? I have moved back to pro/++ for now (less complaints in the family, I had no time to sit and troubleshoot today due to commitments) but for now I manually blacklisted `||advertising.amazon.dev^`. Does anything good come from that subdomain, or could we block it at source rather than all the (five) subdomains currently in Ultimate? Are they left out of light>pro++ for a reason? 

As always, my best,

Lee

**Comment by hagezi** [comment]
Thanks for that, I see no reason not to block advertising.amazon.dev completely. I simply overlooked it. Thanks for the tip, will block it in all lists.

**Comment by hagezi** [comment]
added.

**Comment by kdrcoding** [comment]
I know its weird to ask but where do i add this on my router or do i need adblocker app? can someone help me out here plz ty

**Comment by RainmakerRaw** [comment]
Wow, what a necro @Mkadir1999! I'm not entirely sure I understand your question, or its relevance to this old bug report. Are you asking about blocking the `||advertising.amazon.dev^` subdomain (the topic of this chat), or are you asking how to use Hagezi's blocklists themselves?  
  
If the former, they're already blocked in the main lists. If the latter, this isn't the place to ask for high level tech support/guides. Regardless, you can add Hagezi's lists in a DNS server app like AdGuard Home, Pi-Hole, Unbound, or use an online DNS provider like ControlD and select his lists in that service using the online control panel. The [Recommendation](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#recommendation) in the project's README/home page will help, or you can use your favourite search engine to query how to set up ad blocking DNS.
