### ISSUE TITLE
tom.itv.com (ITV X streaming app ads)

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#1356]
### Which domain(s) should be blocked?

`tom.itv.com`

### Why should these domain(s) be blocked?

Hi Gerd,

I hope you're well. The British TV station ITV has a streaming app called ITVX, which shows ads during the (many) commercial breaks during playback of shows. All your lists block *most* of the rogue domains contacted by this streaming service, but only `pro.txt` and above successfully block the ads from actually being shown. 

I have investigated, and the domain `tom.itv.com` is missing in `light.txt` and `multi.txt`, and is crucial to blocking ads in the app/player. I tested with Pro++, and the player shows no ads at all. Then I downgraded from Pro++ to Light to test, and ads were again shown. After manually blacklisting `||tom.itv.com^` while using Light, the ads went away again. 

The app is still able to log in to the user's ITV account, and I see no loss of functionality after 2 days of testing. Would you please consider also adding this domain to Light and Multi so that all lists cover this streaming service adequately? Thanks for all your work! 

Best wishes,

Lee / Rainmaker

**Comment by hagezi** [comment]
Thanks Lee, will be added.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/1984
