### ISSUE TITLE
False site amazonforum.com

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#136]
amazonforum.com Shouldn’t be at a blacklist.

**Comment by hagezi** [comment]
Blocked by CNAME `d1bd3wxsyuz0t7.cloudfront.net`, flagged as phishing: https://www.virustotal.com/gui/domain/d1bd3wxsyuz0t7.cloudfront.net

Flagged by Google Safebrowsing

![grafik](https://user-images.githubusercontent.com/104343908/210110319-ee80a449-c708-43b0-b218-1df09172392b.png)

sources: @badmojr @notracking @elliotwutingfeng @stevenblack @FiltersHeroes  hole.cert.pl  hblock.molinero.dev

**Comment by hagezi** [comment]
I have checked this and believe it was incorrectly flagged. I will remove the domain.

https://otx.alienvault.com/indicator/domain/www.amazonforum.com
https://otx.alienvault.com/indicator/domain/d1bd3wxsyuz0t7.cloudfront.net

**Comment by notracking** [comment]
fixed, thanks!
