### ISSUE TITLE
wpnrtnmrewunrtok.xyz

### ISSUE THREAD

**Issue by Eow2022yia** [hagezi/dns-blocklists#1363]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS, ControlD, RethinkDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

wpnrtnmrewunrtok.xyz
camvideo.wpnrtnmrewunrtok.xyz
camvideo12.wpnrtnmrewunrtok.xyz

### Why should the domain(s) be unblocked?

Video streams at camwhores.tv are being blocked:

This is due to the following domains being blocked:

wpnrtnmrewunrtok.xyz
camvideo.wpnrtnmrewunrtok.xyz
camvideo12.wpnrtnmrewunrtok.xyz

Steps to reproduce:
Tried to load videos with wpnrtnmrewunrtok.xyz and sub-domains whitelisted, videos load successfully.

Thank you.

**Comment by hagezi** [comment]
Do you have an example link, I can't reproduce this.

**Comment by Eow2022yia** [comment]
> Do you have an example link, I can't reproduce this.

Watch a video on camwhores.tv using your blocklist, it most likely won't work due to wpnrtnmrewunrtok.xyz being blocked.

Use without it (wpnrtnmrewunrtok.xyz being unblocked) the video should load successfully (unless the video itself is broken).

**Comment by hagezi** [comment]
Videos work for me, the domain is also not called up in my region, possibly only for certain videos. But I did some research and will allow the domain.

**Comment by Eow2022yia** [comment]
> Videos work for me, the domain is also not called up in my region, possibly only for certain videos. But I did some research and will allow the domain.

Thank you @hagezi :)
