### ISSUE TITLE
Trustev.com

### ISSUE THREAD

**Issue by johnwaldo** [hagezi/dns-blocklists#1377]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

trustev.com

### Why should the domain(s) be unblocked?

Trustev.com is a fraud prevention domain for TransUnion. Blocking trustev.com is preventing services from loading credit card related services from a major card issuer.

Whitelisted *trustev.com and verified service loads.

**Comment by iam-py-test** [comment]
Listed in Pro and above. Also blocked in 1Hosts Lite and above
