### ISSUE TITLE
False positive for cosmote.net

### ISSUE THREAD

**Issue by mtheofy** [hagezi/dns-blocklists#1384]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

rpz

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

cosmote.net

### Why should the domain(s) be unblocked?

Hi, this domains is used by Cosmote, the #1 ISP in Greece (cosmote.gr). The cosmote.net domain is used by network services and it's usually not public facing. I found out because the speedtest CLI failed.

Here's dig output using the ISP's DNS servers.

```dig speedtest2.cosmote.net @2a02:587:101:0:195:170:0:1

; <<>> DiG 9.18.17-1+0~20230719.88+debian12~1.gbpa39f8f-Debian <<>> speedtest2.cosmote.net @2a02:587:101:0:195:170:0:1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57473
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 4c139de4122c73de52354c2964ce0796f60c71fb76ee707b (good)
;; QUESTION SECTION:
;speedtest2.cosmote.net.                IN      A

;; ANSWER SECTION:
speedtest2.cosmote.net. 1621    IN      CNAME   speedtestn.cosmote.net.
speedtestn.cosmote.net. 2099    IN      A       94.143.176.189
```

I see these entries in the Threat Intelligence AND the Pro++ DNS Blocklist rpz feed 

```
cosmote.net CNAME .
*.cosmote.net CNAME .
```
Thanks for the excellent work in the blocklists

**Comment by hagezi** [comment]
Flagged by Google Safebrowsing:  https://transparencyreport.google.com/safe-browsing/search?url=cosmote.net

**Comment by hagezi** [comment]
I have checked this, from my point of view wrongly marked by Google.

**Comment by mtheofy** [comment]
Thanks for looking into it.

**Comment by hagezi** [comment]
@mtheofy fixed.
