### ISSUE TITLE
blocklist for technitium

### ISSUE THREAD

**Issue by kalle07** [hagezi/dns-blocklists#139]
only a hint ...
technitiumDNS accept also HOSTs files  with 0.0.0.0

**Comment by hagezi** [comment]
Thanks, but the wildcard list is compressed and therefore much smaller and more efficient. Since technitiumDNS supports this, I have not listed it on hosts. Using compressed lists is definitely the better choice.

**Comment by devipasigner** [comment]
> Thanks, but the wildcard list is compressed and therefore much smaller and more efficient. Since technitiumDNS supports this, I have not listed it on hosts. Using compressed lists is definitely the better choice.

Then you should also remove Pi-hole from hosts. Theres no point in using Hosts if it supports Domains. Smaller file size because of the unnecessary 0.0.0.0’s.

**Comment by hagezi** [comment]
The number of domains is relevant, not the file size.

**Comment by devipasigner** [comment]
> The number of domains is relevant, not the file size.

Hmm, yes however why would a Pi-hole user want to use Hosts instead of Domains? The 0.0.0.0 is stripped so it’s completely useless

**Comment by hagezi** [comment]
Pi-hole supports both formats and the number of domains is the same in both formats, so Pi-Hole is also listed with both formats. In the first versions of PiHole only hosts were supported.

**Comment by devipasigner** [comment]
> Pi-hole supports both formats and the number of domains is the same in both formats, so Pi-Hole is also listed with both formats. In the first versions of PiHole only hosts were supported.

I know but i guess you can list it if you want!! Im just saying no point in using hosts if it supports domains

**Comment by hagezi** [comment]
@kalle07 Please note, wildcard format is not yet supported. Have adapted the ReadMe. See: https://github.com/hagezi/dns-blocklists/issues/205
My mistake, I overlooked during the test that I had activated Advanced Blocking.
