### ISSUE TITLE
crontab.guru

### ISSUE THREAD

**Issue by denis-g** [hagezi/dns-blocklists#1415]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole, uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

https://crontab.guru

### Why should the domain(s) be unblocked?

Helpful site for devs.

```shell
$ pihole -q crontab.guru

Match found in https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-adblock.txt:
  ||guru^
```

**Comment by hagezi** [comment]
For pi-hole, you have to whitelist the domain yourself, as the denyallow modifier is not supported. For the others, I add them as an exception.
