### ISSUE TITLE
Next one: usefathom.com

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#142]
Shouldn’t be on a blacklist I think

usefathom.com

**Comment by hagezi** [comment]
Hi @pictosun ,

It is a Google Analytics alternative that uses fingerprinting Api:

https://slayterdev.github.io/tracker-radar-wiki/domains/usefathom.com.html

Why do you think it is false positive? Does it lead to restrictions somewhere?

You could discuss about unblocking the main domain and leaving the CDNs blocked. However, I would do this only for the list versions light, multi and pro.
Users of more aggressive lists like the pro++ and ultimate expect such domains to be completely blocked as long as they don't lead to massive functionality restrictions.

What is your opinion on this?

Thanks,
Gerd

**Comment by pictosun** [comment]
Hi. Thx for the feedback.

That's what I meant. Same as plausible.io (looks like they use fathom).

Light, Multi and Pro would be good to have the domain unblocked. Rest blocked. Good idea!

**Comment by hagezi** [comment]
Thank you, we'll do it that way.
