### ISSUE TITLE
"Spar" shopping app issues with blocks on "emarsys.net"

### ISSUE THREAD

**Issue by jostrasser** [hagezi/dns-blocklists#1421]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

me-client.eservice.emarsys.net
me-inbox.eservice.emarsys.net
mobile-events.eservice.emarsys.net
mobile-sdk-config.gservice.emarsys.net

### Why should the domain(s) be unblocked?

Blocking these domains are breaking functionalities in the "Spar" app (customer notifications, ...):
https://apps.apple.com/at/app/spar/id6448124258

**Comment by hagezi** [comment]
Can you please check if unblocking mobile-events.eservice.emarsys.net is really necessary?

**Comment by jostrasser** [comment]
> Can you please check if unblocking mobile-events.eservice.emarsys.net is really necessary?

Hi! I installed the app freshly on a testing device and can confirm that `mobile-events.eservice.emarsys.net` is note required. Sorry, my mistake!

**Comment by jostrasser** [comment]
Great, thanks Gerd! :)
