### ISSUE TITLE
Mozilla blog blocked

### ISSUE THREAD

**Issue by XioR112** [hagezi/dns-blocklists#1427]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

blog.mozilla.org is blocked because of wp.wpenginepowered.com domain.

Fragment from Pi-hole logs:

Aug 14 19:42:28: query[A] blog.mozilla.org from 192.168.1.18
Aug 14 19:42:28: forwarded blog.mozilla.org to 127.0.0.1#5335
Aug 14 19:42:28: reply blog.mozilla.org is <CNAME>
Aug 14 19:42:28: reply wp.wpenginepowered.com is blocked during CNAME inspection
Aug 14 19:42:28: gravity blocked blog.mozilla.org is 0.0.0.0

### Why should the domain(s) be unblocked?

It's Mozilla blog.

**Comment by hagezi** [comment]
Not blocked in the current version, please update your lists.

**Comment by XioR112** [comment]
Sorry my mistake, it was blocked by Badware Hoster Blocklist.

**Comment by hagezi** [comment]
wpenginepowered.com is in the right place there ...

**Comment by XioR112** [comment]
Ok, sorry for bothering You.

**Comment by hagezi** [comment]
No problem. ;)
