### ISSUE TITLE
Some service/website is blocked

### ISSUE THREAD

**Issue by hann315** [hagezi/dns-blocklists#1428]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL, Most Abused TLDs

### Multi NORMAL
ccms.shopee.io
patronus.idata.shopeemobile.com
c-api-bit.shopeemobile.com
endpoint.mms.shopee.co.id
pdamtbwkotasmi.co.id

### Most abused TLDs
userscript.zone
jav.guru

### Why should the domain(s) be unblocked?

Shopee domains is used for their fintech service, like SPayLater. I faced a problem when I went to SPayLater page, it won't loaded until I unblocked those domains.

pdamtbwkotasmi.co.id is a Water Utility Company in my city.

www.userscript.zone is tampermonkey userscript repository.

jav.guru is... you know...

**Comment by hagezi** [comment]
ping @yokoffing for `userscript.zone` exclusion

**Comment by yokoffing** [comment]
https://github.com/yokoffing/filterlists/commit/4b2ce9e6a4dd063314d71677592a85a345d7516d
