### ISSUE TITLE
Feature request: provide an AdGuard-compatible version of "Allowlist Referral"

### ISSUE THREAD

**Issue by ameshkov** [hagezi/dns-blocklists#1437]
Hello!

I noticed an interesting list among the ones that you maintain:
https://github.com/hagezi/dns-blocklists/blob/main/whitelist-referral.txt

Unfortunately, it cannot be added to AdGuard in its current form.

Could you please consider proving a compatible version?

It basically means that rules should look like this: `@@||domain.com^`

**Comment by hagezi** [comment]
Hi Andrey @ameshkov, you can find an optimised version for AdGuard at:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt

**Comment by ameshkov** [comment]
Oh, cool, thank you!
