### ISSUE TITLE
Unblock Crashlytics 

### ISSUE THREAD

**Issue by nasiralamreeki** [hagezi/dns-blocklists#1439]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT

### Which domain(s) should be unblocked?

firebase-settings.crashlytics.com

### Why should the domain(s) be unblocked?

Currently this is blocked by Multi - Light and as I understand it this domain is used for Crashlytics / Firebase API calls to transmit app crash reports.

**Comment by hagezi** [comment]
Crashlytics and co. remain blocked, please put it on your personal permission list if you want to unblock it.

I know this is debatable, as with sentry, bugsnag, instabug and co. But I have decided to keep them blocked in my lists.
