### ISSUE TITLE
FP: cloudcache.tencentcs.com

### ISSUE THREAD

**Issue by zutzo** [hagezi/dns-blocklists#1444]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

||tencentcs.com^

![](https://github.com/hagezi/dns-blocklists/assets/126886178/eff91368-1a4a-4d5f-a16a-ea9cd49dd92d)

### Why should the domain(s) be unblocked?

![](https://github.com/hagezi/dns-blocklists/assets/126886178/2c7e3771-26f5-47c5-b0be-3ddbc3d4c3da)

https://cloudcache.tencentcs.com/qcloud/ui/static/console_aside_v4/410589ad-fecb-4ac5-94a9-2c2139ce5569.svg

**Comment by hagezi** [comment]
Thanks @zutzo, wrongly blocked by ThreatFox, will be removed in the next update.
https://threatfox.abuse.ch/browse.php?search=ioc%3Atencentcs.com
