### ISSUE TITLE
ubiservices.data.ubi.com

### ISSUE THREAD

**Issue by ericafterdark** [hagezi/dns-blocklists#1453]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT

### Which domain(s) should be unblocked?

ubiservices.data.ubi.com

### Why should the domain(s) be unblocked?

Saving a Ubisoft PlayStation game is not possible.

**Comment by hagezi** [comment]
FYI @Alex-302:

Rule:  `||tagcommander.com^`

`data.ubi.com` CNAME `redirect622.tagcommander.com`

**Comment by Alex-302** [comment]
Thanks, fixed.
Will check later if `@@` rule is required.

**Comment by ericafterdark** [comment]
Thank you @hagezi & @Alex-302
