### ISSUE TITLE
FP : lanzouw.com

### ISSUE THREAD

**Issue by zutzo** [hagezi/dns-blocklists#1462]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

lanzouw.com

### Why should the domain(s) be unblocked?

This is a network disk, I don't think he should be blocked

Example: https://yoyodadada.lanzouw.com/b01domlli#8w1g

![](https://github.com/hagezi/dns-blocklists/assets/126886178/ba9eb449-f888-4bce-b783-632b9785843e)
I saw his other domains exist here too, I would recommend you to check which upstream rule caused the wrong blocking.

**Comment by hagezi** [comment]
@zutzo 
Flagged by ThreatFox and therefore on the list:
https://threatfox.abuse.ch/browse.php?search=ioc%3Awww.lanzouw.com
