### ISSUE TITLE
A friend’s shop 

### ISSUE THREAD

**Issue by Ontime88** [hagezi/dns-blocklists#1475]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL, Multi PRO

### Which domain(s) should be unblocked?

saddog-official.com

### Why should the domain(s) be unblocked?

A legitimate shop, which is run by my friend

**Comment by hagezi** [comment]
via @jarelllama scam block list
