### ISSUE TITLE
laposte.fr customer account login broken

### ISSUE THREAD

**Issue by etenduehalo02** [hagezi/dns-blocklists#1479]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Other

Safari and Firefox tracking protection disabled, uBlock origin disabled as well

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

cdn.tagcommander.com (blocked)
try.abtasty.com (blocked)
s.go-mpulse.net (blocked)

### Why should the domain(s) be unblocked?

When using NextDNS on MacBook and iPhone, set up following yokoffing's guide, laposte.fr website is working but trying to connect to my customer account is showing a totally blank screen after login.

Disabling NextDNS through MacOS app temporary solves the issue.

It looks like connecting to my customer account is calling : 
e6858.dscx.akamaiedge.net
newassets.hcaptcha.com
hcaptcha.com
ocsp2.globalsign.com
moncompte.laposte.fr
s.go-mpulse.net (blocked)
pki-goog.l.google.com
ocsp.pki.goog
cdn.tagcommander.com (blocked)
try.abtasty.com (blocked)
fonts.googleapis.com
e209045.b.akamaiedge.net
www.laposte.fr

**Comment by hagezi** [comment]
These are all blocked domains after the login process and which ones did you have to allow?

`cdn.tagcommander.com` is only blocked in the aggressive lists, not in Normal. So the blocking cannot come from the Multi Normal.

**Comment by hagezi** [comment]
I created an account, logged it out again and I logged in again. I could not reproduce the problems described.

I tested with the Ultimate.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/5ac93330-48fb-48e5-8d0c-184302119bc9)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/6ff38f2d-2e6c-4e6c-981b-5759914ecd92)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/64e52cc0-9f9e-4f1a-886b-34e2b4b77b1d)

**Comment by etenduehalo02** [comment]
Hi! 
cdn.tagcommander.com is indeed blocked by NextDNS' native "Block Disguised Third-Party Trackers" functionnality.
La Poste's website is now working like a charm after disabling this option and whitelisting cdn.tagcommander.com
Thanks for having given it a glance and for your response.
