### ISSUE TITLE
False Positive: https://www.doi.org/

### ISSUE THREAD

**Issue by marleen741** [hagezi/dns-blocklists#1487]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

https://www.doi.org/

### Why should the domain(s) be unblocked?

This is the official domain of the DOI Foundation. A DOI, or Digital Object Identifier, is a string of numbers, letters and symbols used to uniquely identify an article or document, and to provide it with a permanent web address (URL). Please remove this ban, as it is clearly a false positive.  Thank you.

**Comment by hagezi** [comment]
@marleen741 
Thank you, but the domain is not blocked in my lists. Have I missed something?
