### ISSUE TITLE
Possible blocklists to add

### ISSUE THREAD

**Issue by marleen741** [hagezi/dns-blocklists#1488]
Please consider adding [DandelionSprout's](https://github.com/DandelionSprout/adfilt) regional bloclists to Hagezi (Normal). [Serbo-Croatian filter](https://github.com/DandelionSprout/adfilt/blob/master/SerboCroatianList.txt) to be precise. Thank you.

**Comment by hagezi** [comment]
Thanks, already included:
https://github.com/hagezi/dns-blocklists/blob/6a2c980cc4108210c9f425533abe0bbc95fcd24a/sources.md?plain=1#L269
