### ISSUE TITLE
New m.stripe.com domain

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1499]
### Which domain(s) should be blocked?

m.stripe.network
m.stripe.com

### Why should these domain(s) be blocked?

Equivalent to m.stripe.com
(Also in denylist of hBlock List)

https://mtlynch.io/stripe-recording-its-customers/

**Comment by hagezi** [comment]
`m.stripe.com` is allowed:
```
# Payments on various sites
# Includes chat, email messaging, customer support, and other interaction tools.
```

**Comment by xRuffKez** [comment]
Okay, thanks for reporting that it's whitelisted
