### ISSUE TITLE
Why is "browser.sentry-cdn.com" not being block? But according to the included list. It should be with the D3Ward Hosts? Thus making it only 99%  blocked host in that website. Thank you in advance

### ISSUE THREAD

**Issue by Domsicols** [hagezi/dns-blocklists#15]
![image](https://user-images.githubusercontent.com/104392824/179559417-913ee2e4-18ea-4581-8d14-7444004e224a.png)

![image](https://user-images.githubusercontent.com/104392824/179559612-3d1576ae-a6f2-497c-aba6-8adbc0f4961a.png)

**Comment by hagezi** [comment]
Fixed in pro.
