### ISSUE TITLE
Source list for each list 

### ISSUE THREAD

**Issue by lordraiden** [hagezi/dns-blocklists#1502]
Is possible to know which source lists are included with each version of your block lists.
I would like to avoid overlaps

**Comment by hagezi** [comment]
No, it is not a simple 1:1 takeover of sources. I have switched from native sources to my extensions. These are compiled individually for each list version using toplilsts (Umbrealla, Cloudflare, ...) and domain categorisation. 

Only AdGuard, EasyList and uBlock lists are used as native lists. Normal to Ultimate includes all EasyList, AdGuard and uBlock filters incl. wildcard rules (converted to possible domains using CISCO/STATVOO/Cloudflare/Chrome/Majestic Toplists), simplified for DNS.

Which sources have been examined and are partly included can be found here:
https://github.com/hagezi/dns-blocklists/blob/main/sources.md

You can see how the individual lists are composed here:
https://github.com/hagezi/dns-blocklists/blob/main/statistics.md

All list versions were designed for use as a stand-alone list. The individual levels offer the possibility to decide how aggressive it may be.

**Comment by lordraiden** [comment]
@hagezi 
thanks for the quick reply

Please take a loook to the following lists, I have check and they don't appear in sources.md

Phishing URL Blocklist (PhishTank and OpenPhish)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt

Phishing Army | The Blocklist to filter Phishing
https://phishing.army/download/phishing_army_blocklist_extended.txt

Curben - Malicious URL Blocklist
https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt

Curben - Phishing URL Blocklist
https://malware-filter.gitlab.io/malware-filter/phishing-filter-agh.txt

**Comment by hagezi** [comment]
@lordraiden 

Phishing URL Blocklist (PhishTank and OpenPhish) / Curben - Phishing URL Blocklist
https://github.com/hagezi/dns-blocklists/blob/6bd2b44ee0d6365c3b4b4f515ed9d87532113dce/sources.md?plain=1#L118

Phishing Army
https://github.com/hagezi/dns-blocklists/blob/6bd2b44ee0d6365c3b4b4f515ed9d87532113dce/sources.md?plain=1#L138

Curben - Malicious URL Blocklist
https://github.com/hagezi/dns-blocklists/blob/6bd2b44ee0d6365c3b4b4f515ed9d87532113dce/sources.md?plain=1#L121
