### ISSUE TITLE
assets-global.website-files.com

### ISSUE THREAD

**Issue by pokegamer5547** [hagezi/dns-blocklists#1504]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

assets-global.website-files.com

### Why should the domain(s) be unblocked?

Breaks the font in sites like https://www.esper.io/blog/

**Comment by bongochong** [comment]
Thanks @hagezi! Just fixed on this end.
