### ISSUE TITLE
grs.dbankcloud.com - Native Tracking (Huawei)

### ISSUE THREAD

**Issue by Divaltor** [hagezi/dns-blocklists#1507]
### Which domain(s) should be blocked?

grs.dbankcloud.eu

### Why should these domain(s) be blocked?

The mirror for domains like `grs.dbankcloud.cn`, `grs.dbankcloud.com` and so on

**Comment by hagezi** [comment]
grs.dbankcloud.eu is dead:

```
; <<>> DiG 9.16.42-Debian <<>> grs.dbankcloud.eu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 51631
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;grs.dbankcloud.eu.             IN      A

;; AUTHORITY SECTION:
dbankcloud.eu.          150     IN      SOA     monkey.dnspod.net. enterprise3dn                                         sadmin.dnspod.com. 1689729732 3600 180 1209600 180
```

**Comment by hagezi** [comment]
@Divaltor I will exclude it from the dead list so that it still appears as blocked.

**Comment by eusgoogle** [comment]
> `grs.dbankcloud.eu` is dead:
> 
> ```
> ; <<>> DiG 9.16.42-Debian <<>> grs.dbankcloud.eu
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 51641
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;grs.dbankcloud.eu.             IN      A
> 
> ;; AUTHORITY SECTION:
> dbankcloud.eu.          150     IN      SOA     monkey.dnspod.net. enterprise3dn                                         sadmin.dnspod.com. 1689729732 3600 180 1209600 240
> ```

**Comment by eusgoogle** [comment]
ANTYCZNA TOŻSAMOŚĆ EGZOPLANETA 702B

**Comment by eusgoogle** [comment]
HY1006110111LG-B2-1
>PC+ABS-GF10M652975<BN-65/DB02-7145
EUH10:25BFBS-1983-WARSZAWA-35M-XII`biblia Papi Hator Czarnowski Rafał
II0E TYP HERKULES
