### ISSUE TITLE
Google Services High Memory Usage

### ISSUE THREAD

**Issue by emyaqin** [hagezi/dns-blocklists#1510]
So basically, whenever I use the Multi Pro and Multi Pro++ hosts file on my Android phone, the Google services (Play Service, Chrome, Gboard, etc) memory usage just soaring high like 10x than it should be.

**Comment by hagezi** [comment]
Probably the lists are too big for your available phone resources. Try the Light or use a cloud DNS service like AdGuardDNS, NextDNS, ControlD, ,,,

**Comment by emyaqin** [comment]
No, cause before today's update, everything works fine. I've been using the hosts file since few months back

![Screenshot_20230831-214028_Settings](https://github.com/hagezi/dns-blocklists/assets/74818814/b2b1c1cf-5982-461a-ab29-c38aef53b91a)
![Screenshot_20230831-215052_Settings](https://github.com/hagezi/dns-blocklists/assets/74818814/609a125e-5d3c-49c1-84f4-d096d217d44e)
Here's a comparison with and without the hosts file

**Comment by emyaqin** [comment]
![Screenshot_20230831-220333_Settings](https://github.com/hagezi/dns-blocklists/assets/74818814/22598ddc-df8b-421a-bd1a-d970fc066729)
Same issue with multi normal. I didn't use any app to use the hosts file, I just put it into my system/etc/ folder, but when I use the multi light with AdAway, the issues still there too

**Comment by hagezi** [comment]
I can't imagine it's because of blocked domains, but who knows. Try another list, like OISD small or big:

https://small.oisd.nl/hosts
https://big.oisd.nl/hosts

I assume that you have restarted the smartphone?

Which smartphone manufacturer are you using?

**Comment by emyaqin** [comment]
I got no issue with the small, but the same issue with the big one, and yes, I do restart my phone to make everything's fresh. I'm using Samsung Galaxy A20 running stock OneUI 3.1 (Android 11)

**Comment by hagezi** [comment]
I always suspect the size as the cause, for whatever reason this is only occurring now. I've looked through the light commits for the last 2 days and can't find any "obvious" domains that have been added.

And the memory grows immediately when you add the list?

Do you have the possibility to deliver the blocked domains?

**Comment by emyaqin** [comment]
I've been doing some rollback and it seems that the commit from 3 days ago is the one without issue for me and size is not the issue here cause its also a big hosts file. Here's the last working commit for me https://github.com/hagezi/dns-blocklists/tree/e00acab634f196ce0fe0c2f2d6d043b658ac4de3

**Comment by hagezi** [comment]
@emyaqin 
I have compared the light from the commit that works with the commit from earlier this morning that does not work.

Since then, 2487 domains have been added:
[light-added.txt](https://github.com/hagezi/dns-blocklists/files/12495193/light-added.txt)

I think we need logs of what is being blocked.

**Comment by hagezi** [comment]
@emyaqin 
I minimised the Light in the host version in the last build, can you please test this one:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/light.txt

**Comment by hagezi** [comment]
@emyaqin is there anything new about the problem?
