### ISSUE TITLE
Binomo

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#1512]
### Which domain(s) should be blocked?

daftar-binomo.website
online-binomo.com
binomo-id.pro
binomoindonesia.com
www.binomoweb.org
www.binomo.vip
binomoweblogin.com
binomo2022.net
www.binom0-web.com
binomorupiah-id.com
binomo.broker
binomo-brokers.com

### Why should these domain(s) be blocked?

Binomo is Binary option platform and has a history of the biggest fraud/scam in Indonesia.

**Comment by iam-py-test** [comment]
Added, thanks.
