### ISSUE TITLE
Need Blocklist recommendation 

### ISSUE THREAD

**Issue by Krishna-art-dev** [hagezi/dns-blocklists#1516]
What is your recommended Blocklist for most of your user

**Comment by hagezi** [comment]
Pro ;)

**Comment by RelvinArsenio** [comment]
If using the light version only, what do you think?
Do you still recommend it for everyday use?
@hagezi

**Comment by Krishna-art-dev** [comment]
> 

And what's the difference between pro and pro++

**Comment by hagezi** [comment]
> If using the light version only, what do you think? Do you still recommend it for everyday use? @hagezi

Compared to the Light, the Normal also blocks a few more trackers, pop-up ads and more malware domains. I see no reason not to switch from the Light to the Normal, unless you use the Light because of its smaller size.

But I would combine any list, no matter which version, with the TIF if possible.

**Comment by Krishna-art-dev** [comment]
> > If using the light version only, what do you think? Do you still recommend it for everyday use? @hagezi
> 
> Compared to the Light, the Normal also blocks a few more trackers, pop-up ads and more malware domains. I see no reason not to switch from the Light to the Normal, unless you use the Light because of its smaller size.
> 
> But I would combine any list, no matter which version, with the TIF if possible.

Nextdns TIF is same as yours? Because nextdns doesn't have your TIF in blocklists

While in other hands adguard dns have your TIF and Normal Blocklist

So which dns server you gonna recommend for using nextdns or adguard. if nextdns's TIF is like yours I think then nextdns is better it have your pro Blocklist and and list so have choices

**Comment by hagezi** [comment]
> > 
> 
> And what's the difference between pro and pro++

https://github.com/hagezi/dns-blocklists#proplus:

_"More aggressive version of the Multi PRO blocklist. It may contain few false positive domains that limit functionality. Therefore it should only be used by experienced users. Furthermore, an admin should be available to unblock incorrectly blocked domains. Reported false positive domains will be removed from the list!"_

The Pro++ is a more aggressive list, which means that it partially blocks trackers that can lead to functional restrictions.

**Comment by RelvinArsenio** [comment]
> > If using the light version only, what do you think? Do you still recommend it for everyday use? @hagezi
> 
> Compared to the Light, the Normal also blocks a few more trackers, pop-up ads and more malware domains. I see no reason not to switch from the Light to the Normal, unless you use the Light because of its smaller size.
> 
> But I would combine any list, no matter which version, with the TIF if possible.

How about the comparison of False Positives between Normal and Light?

**Comment by Krishna-art-dev** [comment]
> > > 
> > 
> > 
> > And what's the difference between pro and pro++
> 
> https://github.com/hagezi/dns-blocklists#proplus:
> 
> _"More aggressive version of the Multi PRO blocklist. It may contain few false positive domains that limit functionality. Therefore it should only be used by experienced users. Furthermore, an admin should be available to unblock incorrectly blocked domains. Reported false positive domains will be removed from the list!"_
> 
> The Pro++ is a more aggressive list, which means that it partially blocks trackers that can lead to functional restrictions.

I checked your pro blocklists statistics there I found adguard firstparty ublock origin first party easylist firstparty

And in pro ++ statistics it was adguard multiparty ublock origin multiparty easylist multiparty I was thinking what was it what the difference between it

**Comment by hagezi** [comment]
> Nextdns TIF is same as yours? Because nextdns doesn't have your TIF in blocklists

I don't know which sources NextDNS uses, so I can't make a statement about that. But I think they are similar. NextDNS does not accept combined external TIF lists, they use, according to their statements, only native sources and security services. That is the reason why the TIF is not included.
 
> So which dns server you gonna recommend for using nextdns or adguard. if nextdns's TIF is like yours I think then nextdns is better it have your pro Blocklist and and list so have choices

Both are good services, take what suits you best.

**Comment by hagezi** [comment]
> How about the comparison of False Positives between Normal and Light?

Almost identical.

**Comment by hagezi** [comment]
> And in pro ++ statistics it was adguard multiparty ublock origin multiparty easylist multiparty I was thinking what was it what the difference between it

Multiparty = $third-party, see https://adguard.com/kb/de/general/ad-filtering/create-own-filters/#third-party-modifier

**Comment by Krishna-art-dev** [comment]
Does notracking admin accepted your offer?
Btw I have no more issue you can close this comment 

Thanks for replying

**Comment by hagezi** [comment]
> Does notracking admin accepted your offer?

You mean this?
https://github.com/notracking/hosts-blocklists/issues/900#issuecomment-1608227432

I have not received any direct feedback.
