### ISSUE TITLE
Adblock list too long for Little Snitch

### ISSUE THREAD

**Issue by joshuaks** [hagezi/dns-blocklists#1521]
```
Little Snitch: Version 5.7 (6290)
HaGeZi List: Multi ULTIMATE
Format: Adblock
HaGeZi List URL: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt
```

Hi:

Related to [Issue 102](https://github.com/hagezi/dns-blocklists/issues/102).

When I attempted to import "Multi ULTIMATE" by url into Little Snitch, it threw an error related to the amount of entries. It won't accept anything with more than 200,000 entries. This concern was briefly mentioned [here](https://github.com/hagezi/dns-blocklists/issues/102#issuecomment-1356833755). Attached is a screenshot below.

Because Little Snitch (Mini) accepts Adblock format, could a Little Snitch specific list be generated from that into several files?

 
![Error screenshot](https://github.com/hagezi/dns-blocklists/assets/5505155/4a476dc3-3221-438d-9326-a2211490b270).

If there's any way I can help or provide more assistance please let me know!

**Comment by hagezi** [comment]
The size is not supported, it is limited to 200000 entries, for whatever reason. Use the light version instead.

**Comment by joshuaks** [comment]
Thank you.
