### ISSUE TITLE
Just a different question 

### ISSUE THREAD

**Issue by Krishna-art-dev** [hagezi/dns-blocklists#1522]
[Brave says it supports ublock origin filter syntax ](https://support.brave.com/hc/en-us/articles/6449369961741-How-do-I-manage-Ad-Block-filters-in-Brave-#:~:text=Brave%20is%20broadly%20compatible%20with,the%20adblock%2Drust%20issue%20tracker.) 

Doesn't it mean it also supports adguard filters?
Ublock origin supports adguard filters syntax
Checked in [filterlists.com](https://filterlists.com/)
[Adguard syntax is compatible with ublock origin](https://filterlists.com/lists/adguard-base-filter-adguard-for-chromium) and [adguard filter ublock syntax version is compatible with ubo ](https://filterlists.com/lists/adguard-base-filter-ublock-origin) so that's mean adguard is compatible with brave? Do you have any idea of it?

I have another question related to this if adguard syntax isn't compatible with brave then adguard filter that is in ubo syntax that gonna work in brave?

**Comment by hagezi** [comment]
Then take a look at the lists offered in Brave. This answers your question, among them are AdGuard lists ....

**Comment by Krishna-art-dev** [comment]
> Then take a look at the lists offered in Brave. This answers your question, among them are AdGuard lists .... uBlock and AdGuard lists are based on the AdBlock format.

There are ublock origin and adblock plus format like syntax and I no support for adguard syntax I tried and adguard syntax base filter gave some false positives and adguard list based on ubo syntax was working fine. I got my ans thanks for replying
