### ISSUE TITLE
OKX Amplitude

### ISSUE THREAD

**Issue by Divaltor** [hagezi/dns-blocklists#1527]
### Which domain(s) should be blocked?

^https://okx.com/amplitude$

### Why should these domain(s) be blocked?

They send analytics to this route (probably self-hosted Amplitude or proxy to it)

I guess it should be blocked starting from Light\Normal tier list

_I'm using Pro++_

**Comment by hagezi** [comment]
My lists are pure DNS lists, no URLs can be blocked in them, only domains. This is something for content blocker lists.

**Comment by Divaltor** [comment]
> My lists are pure DNS lists, no URLs can be blocked in them, only domains. This is something for content blocker lists.

Thanks for response
