### ISSUE TITLE
Block "jnn-pa.googleapis.com"

### ISSUE THREAD

**Issue by HoVeRzzz** [hagezi/dns-blocklists#1529]
### Which domain(s) should be blocked?

jnn-pa.googleapis.com

### Why should these domain(s) be blocked?

First of all, thank you for all your amazing work.

"It is one of the most frequently called domains in my experience. I blocked it several months ago for testing purposes and never encountered any problems. It might be a good addition to the blocklists."

**Comment by JacobDrivers** [comment]
This being blocked stopped YouTube live videos from working after 20 seconds or so. This happened out of nowhere it seems, randomly… It was so weird. NextDNS still blocks “jnn-pa.googleapis.com” — So, for anyone using it, whitelist it.

**Comment by nemobis** [comment]
That's still the case, blocking `jnn-pa.googleapis.com` will make some music videos stop after ~35 seconds. Not all of them, probably only those with some kind of protection.
