### ISSUE TITLE
yundabao.cn

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#153]
http://www.yundabao.cn/priceserver.aspx

a firm specialized in packing websites into apps

included in TI list

**Comment by hagezi** [comment]
@sr093906 Thanks, removed.

**Comment by ShadowWhisperer** [comment]
Site will not load for me, but it will remain blocked on my list.
Appears to be (have been) used to spread fake "hookup" sites.

https://safeweb.norton.com/report/show?url=yundabao.cn
https://www.siteadvisor.com/sitereport.html?url=yundabao.cn
https://sitecheck.sucuri.net/results/yundabao.cn
