### ISSUE TITLE
SpamTLDs: Allow `fonts.nexus` and `uvc.nexus`

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#1535]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home
uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

ping @yokoffing for exclusion:

`fonts.nexus`
`uvc.nexus`

### Why should the domain(s) be unblocked?

...
My name is Erdit, I am a co-founder of NexusPIPE, a cybersecurity company. We utilise the .nexus TLD for our font service and for our CAPTCHA - it seems your blocklist just straight-up assumes all .nexus TLDs are malicious, which has been reported to us by a few of our clients.

Please could you review our domains (https://fonts.nexus/ and https://uvc.nexus/ respectively) and remove them from your blacklist? That would be greatly appreciated.

Thank you very much,
...

**Comment by yokoffing** [comment]
done

**Comment by 3rdit** [comment]
Cheers, I appreciate your speedy fix for this!
