### ISSUE TITLE
DNS Bypass

### ISSUE THREAD

**Issue by NeWONEx** [hagezi/dns-blocklists#1539]
### Which domain(s) should be blocked?

cf-images.eu-west-1.prod.boltdns.net

### Why should these domain(s) be blocked?

I found out that request going through my Adguard and when I went through your DNS Bypass blocklist didn't find it.

**Comment by iam-py-test** [comment]
That domain seems to be used for hosting images, ie `https://www.iplt20.com/`

**Comment by hagezi** [comment]
Thank you, it is not a DNS bypass.
