### ISSUE TITLE
False positive: ls.apple.com

### ISSUE THREAD

**Issue by mahtd** [hagezi/dns-blocklists#1547]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

ls.apple.com

### Why should the domain(s) be unblocked?

Breaks Apple Maps search and directions. These are the domains that I see come through when trying to use Apple Maps:

```
configuration.ls.apple.com
gsp-ssl.ls.apple.com
gsp64-ssl.ls.apple.com
gspe1-ssl.ls.apple.com
gspe12-ssl.ls.apple.com
gspe19-ssl.ls.apple.com
gspe35-ssl.ls.apple.com
```

**Comment by hagezi** [comment]
WTF ...

**Comment by hagezi** [comment]
Sorry, fixed ..
