### ISSUE TITLE
Sling TV Error 11-100

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#1551]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

p-geo.movetv.com

### Why should the domain(s) be unblocked?

Blocking this domain causes error 11-100 and doesn't allow me to login to Sling TV via the web browser. It appears my Firestick is affected as well. When I tried to open the app, I also got an error message.

**Comment by hagezi** [comment]
Thanks, fixed with last update.
