### ISSUE TITLE
adblock-lean openwrt  TIF dnsmasq failed to download

### ISSUE THREAD

**Issue by shown19** [hagezi/dns-blocklists#1554]
Hi as the title says, I can't seem to integrate  Threat Intelligence Feeds  dnsmasq link, others are working it just this failed when I invoke always download failed despite that it is accessible. Is there something you could suggest a fix for this or this is adblock-lean issue?

**Comment by hagezi** [comment]
Both links work, I don't know why it doesn't, is it too big maybe?

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif.txt
https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/dnsmasq/tif.txt

**Comment by shown19** [comment]
> Both links work, I don't know why it doesn't, is it too big maybe?
> 
> https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif.txt https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/dnsmasq/tif.txt

now that I think about it,  I changed the adblock-lean default maximum size and it worked. Thank you very much, everything looks good now.
