### ISSUE TITLE
Google Voice

### ISSUE THREAD

**Issue by lwittwer** [hagezi/dns-blocklists#1558]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

stun.l.google.com

### Why should the domain(s) be unblocked?

Cannot start Google Voice call while this URL is blocked.

**Comment by hagezi** [comment]
Not blocked in the current list versions.
