### ISSUE TITLE
PopUp ads

### ISSUE THREAD

**Issue by Krishna-art-dev** [hagezi/dns-blocklists#1559]
### Which domain(s) should be blocked?

mwjkteucypb.com
fepseqdkfyfjc.com

### Why should these domain(s) be blocked?

Because it shows pop up ad in hdmovie2 website

**Comment by Krishna-art-dev** [comment]
One more url uoeeyfrfpayvlp.com
It seems like server is just changing every hour i 
![1000005459](https://github.com/hagezi/dns-blocklists/assets/121063162/ed0efd77-1089-4df7-afd0-eec40d0c4ced)
This type of pop up is coming once I blocked that site it's gone but after a hour that pop up comes from a new server is there any way to prevent this?

**Comment by hagezi** [comment]
I found the following domains on the IPs of the reported domains and added them to the pop-up extension. The pop-up extension is fully included in the Pro, Pro++ and Ultimate versions, and only partially included in the Light and Multi versions.

139.45.197.168:
```
16-merchant-s.com
5-internads-7.com
73-j-pinnable.com
aabproxytests.top
acwtivljspmtwwb.com
adb7rtb.com
agloogly.com
ahoxirsy.com
airdoamoord.com
aivoonsa.xyz
allcommonblog.com
allfreshposts.com
allhugeblog.com
allhugenewz.com
astaicheedie.com
astouthy.net
augladraugne.com
aunsagoa.xyz
aursaign.net
avuthoumse.com
baubogla.com
beemauhu.xyz
beenoper.com
bhnxuppheq.com
biznewsinsider.com
bolofoak.net
boomouso.xyz
bouptosaive.com
bsgeneral.com
c-4fambt.com
ceekougy.net
cesebsir.xyz
chaiptut.xyz
chengoassa.com
chijauqybb.xyz
coaraije.com
daigrouchest.com
daugloon.net
dausoofo.net
denetsuk.com
dicheeph.com
dichoabs.net
dimpuxoh.net
doobaupu.xyz
dossouwe.net
duftoagn.com
echoachy.xyz
edoumeph.com
eengange.com
eensoans.com
eepsukso.com
eeroalse.net
ekaurord.com
emoticappfriends.com
eptobeemeeps.com
etougais.net
fauvauth.com
finbiznews.com
gargoowi.com
gaupsaur.xyz
gauthawhum.com
ginsicih.xyz
glaimtug.com
glazegha.com
gleegloo.net
glekrush.com
gloomseb.net
gloustoa.net
goucejugra.com
gouloupt.com
gqascjujvuaopck.com
grachompoa.com
grangilo.net
grauhoat.xyz
grauroocm.com
grawhoonrdr.com
grecheer.com
greezoob.net
griksoud.net
grooseem.net
grounolrou.com
grurooka.com
hauphoak.xyz
hhvbdeewfgpnb.xyz
hightopnews.com
hoonaptecun.com
hoowooze.net
houjachy.com
ilinouck.net
iloacmoam.com
ilumtoux.net
interbuzznews.com
interstitial-07.com
ipodreevess.com
irepheethooh.com
jaftouja.net
jaubeebe.net
jauchuwa.net
jaukaipt.net
jaumevie.com
jehobsee.com
joponeet.com
joudotee.com
keegesta.com
kertazoa.net
know-whos-spying.com
know-whos-watch.com
koabukedosi.com
koadoasi.net
koocoofy.com
kuglouhaize.com
l44mobileinter.com
lawerauz.net
livesharepersonals.com
lurgafty.net
mestoaxo.net
moaglail.xyz
mocmubse.net
naunoulu.net
naupseko.com
neehoose.com
newsfeedzscrollz.com
nhrtxuxipugjcdr.com
ninoglostoay.com
noazauro.net
nooroapo.com
nugrudsu.xyz
oakaumou.xyz
ojxfugjtghdg.com
oopukrecku.com
oordoughy.com
oorouglu.com
ooxookrekaun.com
ouglotso.net
ougribot.net
ouphotha.net
ourhotstories.com
ourtopstories.com
ousinouk.xyz
ozobsaib.com
paifouth.com
peezanoo.net
pheerdoudeem.com
pheselta.net
phirgese.com
phoampoa.com
phoobsoo.net
pimpoopo.com
plandappsb.com
pooptoom.net
prelandtest01.com
psikoofack.com
ptaissud.com
ptaulratch.com
ptetchie.net
ptouksox.com
pulsersurvey.com
pulserviral.com
raijoolu.xyz
reager30.com
risausso.com
roachoavi.com
rodroord.net
saiceezu.xyz
saikeela.net
saishait.net
saiwhute.com
sauptoacoa.com
seehaucu.net
sexeecmo.xyz
shabsaco.net
shauxeel.com
sheecmee.xyz
shexawhy.net
shoahoom.com
shuglaursech.com
shujoocm.com
shumsooz.net
shungawy.com
shusacem.net
shuwhims.com
sitsaraubs.com
staixemo.com
stansoam.com
starsaug.com
stazumik.net
steessay.com
stotchou.com
streaming-illimite4.com
taigrooh.net
theactualnewz.com
thechargenews.com
theelrou.net
thompaur.com
toajephu.com
topfreenewsfeed.com
totaltopposts.com
trading21s.com
u-50-rbdm.com
upsajeve.com
ushoofop.com
ustithoo.net
uvoovoachee.com
vaunaupt.com
vignerez.net
viralnewsobserver.com
vjxrwliwcoiby.com
voadeezu.net
voaseera.net
voosegou.xyz
vounaipu.net
vvguceexpcibtev.xyz
w65mymobile.com
wauthaik.net
wazensee.net
wegleelr.com
whepsezu.net
whertinu.com
whoavaud.net
wholenicenews.com
wholewowblog.com
whoumtip.xyz
wiglurto.xyz
worldviralnewz.com
wouthula.xyz
wupoughu.com
yourcommonfeed.com
yourtopnews.com
yourviralnewz.com
zaicasoawoul.com
zauglust.net
zausosti.net
zekeeksaita.com
zoukooso.com
zugloopt.com
```

139.45.197.168:
```
lgdmconwvygoo.com
noxdgqcm.com
opkinglerr.com
vcchuqcxjbbww.com
xdakyafmvsd.xyz
ywxstcxkjutw.com
```

**Comment by Krishna-art-dev** [comment]
Thanks gonna check tomorrow if it still pops or it get blocked thanks

**Comment by Krishna-art-dev** [comment]
Sure

**Comment by Krishna-art-dev** [comment]
No need to wait, server got changed again 
tqgrrfssodfo.com this is the new server

**Comment by hagezi** [comment]
Yes, these are generated doamins, hard to catch them all.

**Comment by Krishna-art-dev** [comment]
Btw which hdmovie2 website u checked hdmovie2.codes or hdmovie2.link I was talking about hdmovie2.codes

**Comment by Krishna-art-dev** [comment]
> Yes, these are generated domains, hard to catch them all.

Hmm then what can we able to do?

**Comment by hagezi** [comment]
Not very much, they also change over time. When you report a domain, I check which IP is behind it and see which domains still point to the IP. I then add these.

If you use a content blocker in your browser, you shouldn't see any pop-ups.

**Comment by hagezi** [comment]
Which version of my blocklist are you using? Pro or higher?

**Comment by Krishna-art-dev** [comment]
> Which version of my blocklist are you using? Pro or higher?

Pro

**Comment by Krishna-art-dev** [comment]
> Not very much, they also change over time. When you report a domain, I check which IP is behind it and see which domains still point to the IP. I then add these.
> 
> If you use a content blocker in your browser, you shouldn't see any pop-ups.

Hmm browser on my phone so using brave browser but I am still getting these popup and only solution I found for these on Android is using kiwi browser with extention firefox with extention or ghostry browser and gecko based browser is wonky on these site and in kiwi browser extension doesn't work correctly like adguard adblocker's webrtc block and the only open I have is brave browser and Chinese browser works fine with extentions but it tracks user a lot ulog something I don't remember It sends data on that 

Do you have any recommendations for anything for mobile?

**Comment by hagezi** [comment]
I use Safari with Ghostery on iPhone and as DNS AdGuard Home with the Pro and I don't see any popups on the page in my test.

**Comment by hagezi** [comment]
Tested with Brave on iOS, I don't see any popups with that either.

**Comment by Krishna-art-dev** [comment]
I am using Android

**Comment by Krishna-art-dev** [comment]
Using any filters? On brave or just brave on iOS is better idk

**Comment by hagezi** [comment]
Standard installation of Brave. I have not changed any settings.

Even with Chorme on iOS, only DNS with the Pro, I don't see any pop-ups. Crazy ...

**Comment by Krishna-art-dev** [comment]
Fresh new brave browser with default settings just changed the filtering mode to aggressive

**Comment by Krishna-art-dev** [comment]
Why video isn't uploading 😑

**Comment by Krishna-art-dev** [comment]
Are you using adguard home with tif? Le me check it tif blocks it

**Comment by hagezi** [comment]
Yes with TIF, is my test system, had downgraded to Pro for testing. Normally I use Ultimate + TIF for testing.

The domains you blocked are not even accessed by me, I checked the DNS logs. Maybe only under Android, or in a certain region ...

**Comment by Krishna-art-dev** [comment]
> Yes with TIF, is my test system, had downgraded to Pro for testing. Normally I use Ultimate + TIF for testing.
> 
> The domains you blocked are not even accessed by me, I checked the DNS logs. Maybe only under Android, or in a certain region ...

I am also not able to open that websites but I used it in my denylist it blocks those popups let me send you screen recording

**Comment by hagezi** [comment]
I believe you. Report the domains you find, I'll block them, that's all we can do at the moment.

**Comment by Krishna-art-dev** [comment]
> I believe you. Report the domains you find, I'll block them, that's all we can do at the moment.

Hmm

**Comment by Krishna-art-dev** [comment]
https://photos.app.goo.gl/VGMj1dy4neS7prBS6

Here server got changed so I blocked it in dns level but it's slow so I blocked it with brave and see then no pop up

**Comment by hagezi** [comment]
I have added the domains from the IP range, they are included in the next update of the Pro. Then let's see what's still missing.

https://myip.ms/browse/sites/1/ipID/139.45.197.160/ipIDii/139.45.197.170

**Comment by Krishna-art-dev** [comment]
Do you think that pervious generated server will gonna be use again? 
It's changing every hour now it's srycnaas.com
I think it's not worth to be in dns Blocklist if it's just keep changing everytime 
I will say just wait for tomorrow if same dns request comes again then keep it in your blocklists

**Comment by hagezi** [comment]
![image](https://github.com/hagezi/dns-blocklists/assets/104343908/b47f20ab-6506-466d-a513-7679386e7f46)

**Comment by Krishna-art-dev** [comment]
On Android I had to add other filters to block more

**Comment by hagezi** [comment]
As I said, the pop-ups don't appear on iOS because the behaviour is different. I also don't get the pop-ups in Chrome without content blocker and I don't see the pop-up doamins in the DNS log.

The domains are probably being used again, but new ones are also being registered. Pop-up ads are the plague.

I think we can close this.

**Comment by Krishna-art-dev** [comment]
Yes

**Comment by HellboyPI** [comment]
There is a solution. Use NextDNS or Cloudflare Gateway as your upstream DNS provider. They have the option "Block new registered domains". 

Most of these spam domains are NRD-s. Until the spam domain, example, spamxz132.com gets on a blocklist, this option should block it.

**Comment by Krishna-art-dev** [comment]
> There is a solution. Use NextDNS or Cloudflare Gateway as your upstream DNS provider. They have the option "Block new registered domains".
> 
> Most of these spam domains are NRD-s. Until the spam domain, example, spamxz132.com gets on a blocklist, this option should block it.

Thanks brother I had forgotten about that option that should fix the issue because the server changes every hour and they don't use previous servers so this should fix this

**Comment by Krishna-art-dev** [comment]
@hagezi the server I reported you should remove it from your blocklists because they change server every hour and didn't uses previous once 
It just gonna be a waste in you best dns Blocklist 
![1000005555](https://github.com/hagezi/dns-blocklists/assets/121063162/69acaceb-ee31-469c-9300-a6bcfca773f3)
See servers are keep generating 
Previous once isn't being used

I don't know about other domains that you showed me they should be serving ads on different part of site or somewhere else idk and it's reported by a lot of people that should mean that's ads server, gonna have to check it but how idk

But for auto generated new server you should delete it 

I have one question adguard for Android app blocks a lots of dns request without any filters lists being used on them does adguard home also does this? I had seen when using adguard for Android that dns request had been blocked without any filters (good job adguard)

**Comment by Krishna-art-dev** [comment]
And is there a way to used regex based supports for unblocking domain because piracy sites are keep getting blocked and they change their domain (while keeping their name) and come again that's why I had turned off block new registrated domain Previously
