### ISSUE TITLE
ahrtv.cn and others

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#156]
https://www.ahrtv.cn/

api.map.ahrtv.cn
post.i.api.ahrtv.cn

Anhui Radio and Television Station

included in TI list

**Comment by hagezi** [comment]
ping sources: @notracking @sjhgvr @stamparm

**Comment by hagezi** [comment]
@sr093906 Thanks, removed.

**Comment by notracking** [comment]
Whitelisted, thanks!
