### ISSUE TITLE
Brave telemetry

### ISSUE THREAD

**Issue by th3m** [hagezi/dns-blocklists#1571]
### Which domain(s) should be blocked?

variations.brave.com

### Why should these domain(s) be blocked?

Brave on startup sends a request to `variations.brave.com`. Brave uses this to turn on and off features. There isn't a way to disable this as of yet. (Ref: [https://github.com/brave/brave-browser/issues/15711](url))

I suggest this domain to be blocked at least in the more aggressive lists like Pro++ and Ultimate.

Sources:
[https://www.reddit.com/r/brave_browser/comments/n71we0/just_helping_everybody_out_how_to_disable_all/](url)
[https://spyware.neocities.org/articles/brave](url)
[https://www.kuketz-blog.de/einstellungen/#brave-desktop](url)

**Comment by iam-py-test** [comment]
FYI, all your links are broken

**Comment by hagezi** [comment]
links fixed
