### ISSUE TITLE
To Remove auto generated server from your blocklists 

### ISSUE THREAD

**Issue by Krishna-art-dev** [hagezi/dns-blocklists#1573]
I checked they don't use there pervious generated server so there is no good blocking them or not 

And I also noticed one thing blocking that server that, the pop up redirect us to blocked pop ups that comes before

Means the auto generated server still come to my log but it didn't shows any pop ups when the server is blocked, in which the pop up redirect us 

ilmtudcgmqxa.com
cdn.freeimagecdn.net
duty-halt-i-253.site
tqgrrfssodfo.com
uoeeyfrfpayvlp.com
fepseqdkfyfjc.com
mwjkteucypb.com
Iwmheajc.com
log-training-i-254.site
temptation-gradient-i-250.site
jmqrogtmvfo.com
srycnaas.com
hvikgqco.com

These are the server that I perviously told to block remove them from you blocklists as they didn't do anything there it is just a waste server 

But keep those server that it redirect to 
Like haustoam.com 
         savaurdy.net and I only know about these 2

And the one you showed me 
This https://github.com/hagezi/dns-blocklists/issues/1559#issuecomment-1717182493 it must be reported by lots of people that's why keep it

**Comment by hagezi** [comment]
The few domains on the list do not "hurt". If they are dead or inactive at some point, they will automatically be removed from the list.

**Comment by Krishna-art-dev** [comment]
Hmm I thought you remove the list manually that's why I told this 
Then there is nothing to worry
