### ISSUE TITLE
sunglasseshut / ray-ban block

### ISSUE THREAD

**Issue by hyder365** [hagezi/dns-blocklists#1575]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

custom

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT

### Which domain(s) should be unblocked?

smetrics.ray-ban.com
smetrics.sunglasshut.com

### Why should the domain(s) be unblocked?

The domains "images.ray-ban.com" and "assets.sunglasshut.com" contain the product images on these two sunglasses websites. Neither of them are directly in the list, but it seems the list is still blocking them. I'd appreciate any help figuring out why.

https://www.sunglasshut.com/us/ray-ban/rb3183-805289018926
https://www.ray-ban.com/usa/sunglasses/RB3183%20MALE%20rb3183-black/805289528791

These two pages are mostly blank because of the aforementioned domains being blocked.

**Comment by hagezi** [comment]
Can't reproduce:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/f8d25933-144a-4ad2-84f3-ce06c328ba72)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/a0e80668-1e06-4338-a569-0a43f34959e0)

**Comment by hagezi** [comment]
This is a DNS server problem, not a blocklist problem:

_REFUSED results when the DNS name server refuses to perform operations for policy reasons. For example, a particular device may be blocked if it is abusing the nameserver. Or, a particular operation, such as a zone transfer, might be forbidden._

**Comment by hagezi** [comment]
OK.

If you deactivate the block list, does it work?

Deactivate it and post the output of:

`dig assets.sunglasshut.com`
`dig images.ray-ban.com`

**Comment by hagezi** [comment]
Ok, you get the same CNAMEs as me, these are not blocked either.

**Comment by hagezi** [comment]
I don't understand why the domains don't resolve, I have no problems, tested with Ultimate:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/a27fff96-683c-41fa-99d1-960c3377f554)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/943633db-191b-43ac-874d-30c0aa8c2771)

**Comment by hagezi** [comment]
Yes, that is the cause. ;)

**Comment by hagezi** [comment]
So lists that block such elementary things as edgesuite.net, I would remove immediately. ;)
