### ISSUE TITLE
It's strange

### ISSUE THREAD

**Issue by RelvinArsenio** [hagezi/dns-blocklists#1584]
Why is this still blocked on NextDNS?
Even though when I checked on HaGeZi's Light DNS Blocklist, it's no longer there.
I'm also not using NextDNS filters.
Moreover, this has already been reported here. https://github.com/hagezi/dns-blocklists/issues/498

### Attacment
![image](https://github.com/hagezi/dns-blocklists/assets/88470966/fa120232-e20c-4282-b6bc-620ef19c23e8)

### Block List
![image](https://github.com/hagezi/dns-blocklists/assets/88470966/088fd85e-b8b0-4250-9c76-b5f8e8e3b7c5)

**Comment by hagezi** [comment]
`||optimizely.com^` is blocked, will be fixed for light in the next update.
