### ISSUE TITLE
(UK) Channel 4 streaming ads

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#1587]
### Which domain(s) should be blocked?

||ads-pres.channel4.com^
||cdn.ss.anno.channel4.com^
||ic.channel4.com^

### Why should these domain(s) be blocked?

Greetings Gerd, 

I hope you're well? It's been quite some time since I filed an issue, which is testament to the ever-improved quality of your lists. Unfortunately, last week I encountered long, mandatory ad breaks on the UK's channel 4 streaming service. Every few minutes, one must endure 2 minutes of advertisements. Additionally, when pausing the stream a full screen overlay static ad appears until you resume playback. Your Pro++ list blocked some domains (I didn't test lower level lists), but the ads remain. 

Blocking the additional domains listed above has left the streaming service perfectly functional, but the ads now simply don't appear any more. It's possible to watch whole shows in a single take without interruption, and I see no side effects from the blocks in the 4 streaming app. Please can you add these domains? 

Thanks!

Lee / Rainmaker

**Comment by hagezi** [comment]
Thanks Lee! ;)
