### ISSUE TITLE
ShallaList is now defunct

### ISSUE THREAD

**Issue by cbuijs** [hagezi/dns-blocklists#1590]
Just as heads-up, in the [sources](https://github.com/hagezi/dns-blocklists/blob/main/sources.md) doc it is mentioned that these sources are used:
```
https://raw.githubusercontent.com/cbuijs/shallalist/master/adv/domains
https://raw.githubusercontent.com/cbuijs/shallalist/master/tracker/domains
```
Shallalist has been discontinued and these sources should be removed.

Cheers,
-Chris.

**Comment by hagezi** [comment]
Thanks Chris, I looked into it at the time but didn't use it.

**Comment by cbuijs** [comment]
Gotcha, no problemo!
