### ISSUE TITLE
Add "SS" websites

### ISSUE THREAD

**Issue by ymhcanada** [hagezi/dns-blocklists#1592]
### Which domain(s) should be blocked?

sanctioned-suicide.net
sanctioned-suicide.org

### Why should these domain(s) be blocked?

We would like to request the addition of two website domains associated with Sanctioned Suicide (SS) to the blocklist.

These domains have been identified as platforms that promote and discuss suicide methods, including those involving substances and gases, as mentioned in the [analysis conducted by the University of Padua](https://thesis.unipd.it/retrieve/3f2c4551-edf3-494f-9fc6-ff39821ac254/Sartori_Elisa.pdf). The analysis highlighted the presence of methods such as Hydrogen Sulfide, Sodium Azide, and Nembutal on the Sanctioned Suicide forum.

While this scenario does not fit into any of the categories on the list you keep, please feel free to close this issue if you believe it is not applicable.

**Background Information:**

Sanctioned Suicide is an internet forum known for its open discussion and encouragement of suicide and suicide methods. The forum has garnered widespread scrutiny for its promotion of suicide.

Wikipedia
https://en.wikipedia.org/wiki/Sanctioned_Suicide

Letter from the Members of Congress
https://trahan.house.gov/uploadedfiles/doj_sanctioned_suicide_letter_final_dec21.pdf

The New York Times investigation
https://www.nytimes.com/interactive/2021/12/09/us/where-the-despairing-log-on.html

University of Padua analysis
https://thesis.unipd.it/retrieve/3f2c4551-edf3-494f-9fc6-ff39821ac254/Sartori_Elisa.pdf

Fix The 26
https://fixthe26.com/category/stop-sanctioned-suicide/

The presence of websites like Sanctioned Suicide, which openly discuss and encourage suicide methods, poses significant harm to online users. These platforms can have a detrimental impact on individuals who may already be vulnerable or struggling with mental health issues. By providing a space for the exchange of detailed information on suicide methods, these websites can potentially facilitate and normalize self-harm behaviors. This can further exacerbate feelings of hopelessness, isolation, and despair among individuals who are already contemplating suicide. Moreover, the exposure to such content can potentially trigger and influence vulnerable individuals, pushing them towards dangerous actions. It is crucial to take proactive measures to restrict access to these harmful websites in order to protect individuals and promote a safer online environment.

**Comment by hagezi** [comment]
@ymhcanada thank you for the details and the topic.

One can debate whether blocking is in some way censorship. But, I have read up and I think that such domains belong on the block list - I was shocked. That's why I have blocked them in all list versions.

**Comment by ymhcanada** [comment]
Thank you very much @hagezi - adding them to a blocklist is a small step but it still means a lot to us and the families we know. We appreciate your diligence and effort in maintaining the project! 
(While I acknowledge that censorship may not offer a definitive solution, the severity of harm caused by this website cannot be underestimated and warrants blocking.)

**Comment by xRuffKez** [comment]
> @ymhcanada thank you for the details and the topic.
> 
> One can debate whether blocking is in some way censorship. But, I have read up and I think that such domains belong on the block list - I was shocked. That's why I have blocked them in all list versions.

There is no excuse for such domains.
