### ISSUE TITLE
Please consider unblock monitoring.<region>.amazonaws.com

### ISSUE THREAD

**Issue by tatchiu-leung-form3** [hagezi/dns-blocklists#1598]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

monitoring.eu-west-2.amazonaws.com

### Why should the domain(s) be unblocked?

Somehow AWS CloudWatch metrics graph is not shown. It's blocked by `monitoring.eu-west-2.amazonaws.com`. I believe the same applies to all AWS regions like `monitoring.us-east-1.amazonaws.com`

![image](https://github.com/hagezi/dns-blocklists/assets/119341091/0f951aec-99d9-45d5-aea8-af0db6bf391f)

If I unblock the rule, the graph shows correctly.

![image](https://github.com/hagezi/dns-blocklists/assets/119341091/a9db03d9-ffde-48f7-887d-665642e0b3e0)

**Comment by hagezi** [comment]
@tatchiu-leung-form3 added `monitoring.*.amazonaws.com` to the allow list.

**Comment by hagezi** [comment]
Thank you @Retold3202. I've noticed that too. It also seems to be used for tracking. Therefore I will block `monitoring.*.amazonaws.com` in the next release in the aggressive lists and in the native amazon list.
