### ISSUE TITLE
iOS  insufficient blocking

### ISSUE THREAD

**Issue by Domsicols** [hagezi/dns-blocklists#16]
Can you block more bad domains specifically in iOS? Im using adguard for iOS btw.Take for example the screenshot i added. And maybe there is even more that is considered as a tracker etc. Thank you in advance

![image](https://user-images.githubusercontent.com/104392824/179800129-eaa1a5a1-aafd-41ab-b042-566ccc7e97be.png)

**Comment by hagezi** [comment]
Fixed in pro after next auto update.

**Comment by Domsicols** [comment]
> Fixed in pro after next auto update.

Thank you so much! Really love your blocklist!
