### ISSUE TITLE
LinkedIn Blocked

### ISSUE THREAD

**Issue by FrenchToucan** [hagezi/dns-blocklists#1600]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

LinkedIn.com

### Why should the domain(s) be unblocked?

Social media site

**Comment by hagezi** [comment]
Blocked by CNAME `www-linkedin-com.l-0005.l-msedge.net`. Will be fixed asap.

**Comment by hagezi** [comment]
Fixed.
