### ISSUE TITLE
nexus TLD: lostark.nexus and more

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#1602]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home, uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

@Yokoffing

`lostark.nexus`

further potential exclusions, see https://github.com/hagezi/dns-blocklists/issues/1602#issuecomment-1728349139

### Why should the domain(s) be unblocked?

Lost Ark Nexus is a community made non-profit website and hub for a large array of community assets most notably the Community Guides. The purpose of this site is to help redirect users to various community resources that may or may not be created by the Lost Ark Nexus or Community Guide team.

**Comment by hagezi** [comment]
"nexus" sites to check via toplists:

```
1tamilmv.nexus
cdev.nexus
cdn.fonts.nexus
dontorrent.nexus
go.nexus
idr45.nexus
lemmy.nexus
mastodon.nexus
mycelial.nexus
nimbus.nexus
panopticon.nexus
sakti55.nexus
supergates.nexus
totals.nexus
```

**Comment by yokoffing** [comment]
I've re-evaluated `.nexus`. It no longer seems to deserve a title of "likely threat". I will just remove it from the list.

**Comment by hagezi** [comment]
Thanks @yokoffing
