### ISSUE TITLE
Can't update Brave and Install Extensions from Brave.

### ISSUE THREAD

**Issue by lunecrescent** [hagezi/dns-blocklists#1603]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

https://go-updater.brave.com
https://laptop-updates.brave.com

### Why should the domain(s) be unblocked?

go-updater.brave.com: Extensions download and updates
laptop-updates.brave.com: Brave browser update and download

**Comment by hagezi** [comment]
Thankse, fixed with last update.
