### ISSUE TITLE
Block Yandex AD services

### ISSUE THREAD

**Issue by DonCossacks** [hagezi/dns-blocklists#1607]
### Which domain(s) should be blocked?

strm.yandex.ru
strm.yandex.net

### Why should these domain(s) be blocked?

Provides advertising or advertising-related services such as data collection, behavioral analysis or retargeting.

**Comment by hagezi** [comment]
Blocking `strm.yandex.ru` breaks video previews on `hd.kinopoisk.ru`, example:
https://hd.kinopoisk.ru/film/42a2ca705b9548f58ec9055853acaa23?content_tab=overview&episode=1&season=1

Blocked:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/69cd6661-efdb-4ed1-8153-a65d907dffdd)

Unblocked:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/306118f6-f97e-4d93-917b-78ba6db87210)


Blocked in all lists:
`log.strm.yandex.ru`

I haven't found any restrictions for `strm.yandex.net` yet, so I will only block it in the aggressive lists for the time being.

Or do you have more details on this?

**Comment by DonCossacks** [comment]
On fontanka.ru there are ads with following addresses
ext-strm-m9-1528-30.strm.yandex.net
ext-strm-marert23.strm.yandex.net

**Comment by hagezi** [comment]
Thank you, I will block the subdomains.

**Comment by DonCossacks** [comment]
Thank you!
