### ISSUE TITLE
Homeconnect Household Device Tracking

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1618]
### Which domain(s) should be blocked?

t.homeconnecthca.com

### Why should these domain(s) be blocked?

Domain to Track usage of Homeconnect Household Devices such as Washing Mashine, Dryer, Fridge etc.

**Comment by ptrsmk** [comment]
I suspect these should be added, but I'm not certain:
t.rna.homeconnecthca.com
ha-ws.rna.homeconnecthca.com
rna.comws.homeconnectegw.com

**Comment by hagezi** [comment]
@ptrsmk Do you have details of what the domains are used for?

**Comment by hagezi** [comment]
@xRuffKez 
I took a closer look, `t.homeconnecthca.com` seems to be used for time synchronisation, not for tracking.

```
ntpdate -q t.homeconnecthca.com
server 13.248.208.126, stratum 4, offset -0.000233, delay 0.04019
server 76.223.84.183, stratum 4, offset +0.000018, delay 0.03918
30 Apr 16:52:32 ntpdate[2319982]: adjust time server 76.223.84.183 offset +0.000018 sec
```
```
ntpdate -q t.rna.homeconnecthca.com
server 174.129.136.207, stratum 4, offset -0.001186, delay 0.13246
server 50.19.184.61, stratum 4, offset -0.001209, delay 0.13203
30 Apr 16:53:42 ntpdate[2319987]: adjust time server 50.19.184.61 offset -0.001209 sec
```

**Comment by xRuffKez** [comment]
Oh, well that's good to know. Honestly never had issues with my mashines at home... but ntp is important by any mean.

Sorry for the false accusation, let's revert the blockage.

**Comment by hagezi** [comment]
Logging domains are:

```
logs.v2.homeconnectegw.com
production.reu.logs.v2.homeconnectegw.com
production.rna.logs.v2.homeconnectegw.com
```
