### ISSUE TITLE
dtsrd.gov.cn

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#162]
https://dtsrd.gov.cn/

People's Congress of Datong, Shanxi Province

included in TI list

**Comment by hagezi** [comment]
ping sources: @bongochong @laniksj @sjhgvr

**Comment by bongochong** [comment]
Thanks for the heads up. This was on a bunch of well-known anti-malware lists, and consistently flagged as suspicious by Google and other search engines, for quite a while. That apparently changed over the past few months. Will dig into it a bit more and if all seems OK then I'll make sure it's excluded from my lists.

**Comment by hagezi** [comment]
@sr093906 Thanks, removed.
