### ISSUE TITLE
Smartsheet

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1620]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

*.smartsheet.com

### Why should the domain(s) be unblocked?

Legit Site for managing workflow.

**Comment by hagezi** [comment]
Fixed: https://github.com/hagezi/dns-blocklists/commit/afa0d222b2afd517edf3367bf502a80d73359ed8
