### ISSUE TITLE
Bypass with startpage

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#1621]
### Which domain(s) should be blocked?

eu-browse.startpage.com

### Why should these domain(s) be blocked?

Not covered in DNS bypass list.
Above domain is a proxyservice and can be used to bypass DNS blocking.

**Comment by hagezi** [comment]
Added: https://github.com/hagezi/dns-blocklists/commit/69e2cc9e7e48c8384518e60d21eafc056a9aca65
