### ISSUE TITLE
Unblock AlmaWeb (Student portal of Leipzig University)

### ISSUE THREAD

**Issue by andrewille** [hagezi/dns-blocklists#1622]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

almaweb.uni-leipzig.de

### Why should the domain(s) be unblocked?

This is the regular platform for students of Leipzig University which is used to manage courses, grades, documents etc.
I really can't make up my mind why it is blocked.

**Comment by hagezi** [comment]
Thanks, via Phishing Database, will be removed.

**Comment by hagezi** [comment]
ping @mitchellkrogza
