### ISSUE TITLE
AdGuard iOS: wifi bug with large DNS lists

### ISSUE THREAD

**Issue by Zsombe** [hagezi/dns-blocklists#1623]
Hello!

I found a bug in AdGuard for iOS v4.5.0. When i subscribe to Threat Intelligence Feeds i lost my WiFi connection. But when i unsubscribe from TIF, my WiFi connection go back.
I'm using iPhone 13 Pro, iOS 17.0 and i subscribed to the following DNS lists: HaGeZi's Gambling DNS blocklist, HaGeZi's TIF DNS blocklist and HaGeZi's Pro DNS blocklist.

This is a DNS list or software bug? Or the 1+ million block rules the reason?

**Comment by hagezi** [comment]
This occurs in AdGuard iOS when the sum of all DNS rules exceeds approximately 535000 rules.

**Comment by Zsombe** [comment]
Thanks @hagezi! So it is an AdGuard for iOS bug, am i right?

**Comment by hagezi** [comment]
Yes

**Comment by Zsombe** [comment]
Thank you!

@ameshkov could you be so kind to fix this bug please?

**Comment by hagezi** [comment]
@Zsombe open an issue here:
https://github.com/AdguardTeam/AdguardForiOS/issues

**Comment by ameshkov** [comment]
Well, the problem is that this is not a bug. iOS has some **very** strict limitations on RAM usage and AG for iOS technically won't be able to consume lists larger than 200-300k domains.

**Comment by hagezi** [comment]
Then it should be prevented in the application that too large lists can be added.
