### ISSUE TITLE
Unblock t.sidekickopen01-eu1.com reported safe by virustotal

### ISSUE THREAD

**Issue by micceo** [hagezi/dns-blocklists#1624]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

t.sidekickopen01-eu1.com

### Why should the domain(s) be unblocked?

Ran a search on this site and it looks like they had some flagging 2022 hreported by this site: ttps://any.run/report/dcfde47b0dcd7fa921bb8a0bf6d083fee2dbf63f967b78b98180eb1b29e7d2d6/adcc30bc-6712-46c2-b509-28ea0eeb1dfa

But seems to be clean now according to other services such as virustotal.com

Best regards, micce

**Comment by micceo** [comment]
Hi and thanks for the swift response!

Have distributor who uses a service at that hostname t.sidekickopen01-eu1.com. They link to their quotation in html and pdf-formats.

But maybe it's a tracker after all, but reported safe. It redirect to their companies own page after clicking on the link which looks like this (I've manipulated it so doesn't link to the real information.)

https://t.sidekickopen01-eu1.com/Ctc/W5+23284/djSMnt04/JjTbTjqZW50lYqz6lZ3pk[...lots of other chars like a 1000...]3W8p5k-P8s3FCVf21XXTq04

**Comment by hagezi** [comment]
Thanks, it's a referral tracker, will be removed with the next update.

**Comment by micceo** [comment]
Awesome quick handling of this, KUDOS! I'm deeply impressed.
