### ISSUE TITLE
stisa.org.cn

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#163]
http://stisa.org.cn/

electronic information and software industry association of shantou in Guangdong province

included in TI list

**Comment by hagezi** [comment]
ping sources: @notracking @sjhgvr @stamparm

**Comment by hagezi** [comment]
@sr093906 Thanks, removed.

**Comment by devipasigner** [comment]
Great work! I am curious though, how are these false positives being found? Must be careful with malware domains..

**Comment by sjhgvr** [comment]
https://safeweb.norton.com/report/show?url=stisa.org.cn

**Comment by notracking** [comment]
Whitelisted, thanks!
