### ISSUE TITLE
Postnord

### ISSUE THREAD

**Issue by mvnixon** [hagezi/dns-blocklists#1633]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

postnord.com
tracking.postnord.com

### Why should the domain(s) be unblocked?

Main postal delivery service in the nordics. tracking.postnord.com is the subdomain to allow users to track their parcels.

**Comment by hagezi** [comment]
fixed.
