### ISSUE TITLE
Cookie notice from https://www.unilad.com/ blocked

### ISSUE THREAD

**Issue by arturstat** [hagezi/dns-blocklists#1634]
I am using HaGeZi - Multi NORMAL blocklist under NextDNS service.
The list is blocking the cookie notice on https://www.unilad.com/
Without accepting the cookie policy the website does not work as intended.
This is what you should see:
<img width="1802" alt="Screenshot 2023-09-27 024246" src="https://github.com/hagezi/dns-blocklists/assets/57625194/4e68aed4-fcd0-4733-bb85-c9acdd4e6ab0">

**Comment by hagezi** [comment]
Thanks, will be fixed on next update.
