### ISSUE TITLE
[false positive] minecraft.wiki is blocked

### ISSUE THREAD

**Issue by MIOGMIOG** [hagezi/dns-blocklists#1639]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

minecraft.wiki

### Why should the domain(s) be unblocked?

Minecraft wiki is moving from fandom to this domain, but its blocked by multi ultimate blocklist

**Comment by hagezi** [comment]
@MIOGMIOG Was mistakenly flagged by Quad9 and therefore ended up on the TIF and ULTIMATE. Has been fixed in Quad9. I will remove the domain asap.

**Comment by hagezi** [comment]
@MIOGMIOG fixed.
