### ISSUE TITLE
Blacklist technical-service.net - blocking Ads on bild.de

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#164]
Have a look at technical-service.net

Looks like a new blacklist entry.

**Comment by hagezi** [comment]
@pictosun 
`te.technical-service.net` has been unblocked so that the ntv.de livestream starts in the browser. This means that the rule for the main domain no longer exists.

blocked is
```
te-static.technical-service.net
tr.technical-service.net
```

**Comment by hagezi** [comment]
Should be blocked in Ultimate, but it is not. I have corrected this, it will be completely blocked in Ultimate with the next update.

**Comment by pictosun** [comment]
> `te.technical-service.net` has been unblocked so that the ntv.de livestream starts in the browser. This means that the rule for the main domain no longer exists.

For me ntv.de livestream is working without any issues even when whole domain is blocked.

**Comment by hagezi** [comment]
@pictosun - disbale your browser content blocker and try again. ;)

**Comment by pictosun** [comment]
Tried it. Works without any issues. Using a browser without any 
Also checked the DNS log and ntv.de is not querying any technical-service.net domains at all.

**Comment by hagezi** [comment]
I just double checked, live stream is only running with unblocked technical-service.net:

https://www.n-tv.de/mediathek/livestream/24-Stunden-ntv-Livestream-article9511936.html

**Comment by pictosun** [comment]
Crazy. For me totally different. No query/lookups to technical-service.net while watching  ntv.de livestream.

**Comment by hagezi** [comment]
On mobile (Safari iOS) it works for me without unblocking, on desktop with Firefox, Edge, Chrome, Chromium I have to unblock the domain so that the stream starts.

**Comment by pictosun** [comment]
I'm using macOS Desktop. Maybe other routing within apple devices?

**Comment by hagezi** [comment]
I have only tested it on "Windoof", test again tomorrow on macOS. On iOS I have Safari Tracking Protection off, `te.technical-service.net` appears in the AGH DNS log and is blocked, the stream starts anyway. On Windows Desktop the domain must be unblocked.

**Comment by pictosun** [comment]
Will also Test other systems tomorrow. 

What kind of connection do you have? Cable with AVM Fritz.box or other connection?

**Comment by hagezi** [comment]
I tested again on iOS, had AdGuard active in Safari, so the livestream was running. If I switch off AdGuard or use another browser, the video does not start. So the same behaviour as under Windows. Under MacOS with IP and tracking protection switched off, the same behaviour.
It doesn't matter which internet you use, mobile, SVDSL or fibre. I would have been surprised if that had played a role.

If the domain is not visible in your DNS log, then it is likely that some queries are bypassing your DNS.

**Comment by pictosun** [comment]
> If the domain is not visible in your DNS log, then it is likely that some queries are bypassing your DNS.

Maybe this could be the case, but I don't know how to force everything going to my Pi-Hole, so that I can prevent bypassing.

**Comment by hagezi** [comment]
Which is a popular mistake in the configuration:
If your Internet supports IPv4 and IPv6 and you also have the router DHCP assign an IPv6 address to the clients locally, then you must also assign the IPv4 and the IPv6 of your local DNS to the clients via DHCP or manually. If you only assign the IPv4, then all IPv6 queries will bypass the local DNS.

**Comment by pictosun** [comment]
Don't have IPv6 running. Thinking about that Apple devices do some kind of DoT/DoH for some stuff. Even without setting up private relay or something else.

**Comment by hagezi** [comment]
Yes, if you have "Hide Ip Address" enabled for the network or in Safari, then it could be. If you use PiHole, Private Relay is blocked by default. In AGH you can enable it manually under Services.
You can also try using my DoH bypass list.

**Comment by pictosun** [comment]
Yes - will go and try it. Also send you an email as it contents a little bit 'private' content concerning this point.

Maybe you can find the time and give a short answer. Would be nice.

And thanks for the perfect service in general!

**Comment by hagezi** [comment]
No problem, I'll answer you later. Close here, and we'll sort out the rest via email.
