### ISSUE TITLE
bestreamwise.com Misinformation 

### ISSUE THREAD

**Issue by Xandar-YT** [hagezi/dns-blocklists#1642]
### Which domain(s) should be blocked?

https://bestreamwise.com/

### Why should these domain(s) be blocked?

They are providing misinformation about pirated streams allowing access to your bank account.

**Comment by MIOGMIOG** [comment]
LMAO, totally agree
![cursedbillboard](https://i.imgur.com/iNUV4T4.jpeg)

**Comment by hagezi** [comment]
https://torrentfreak.com/bestreamwise-iptv-anti-piracy-campaign-begins-with-fake-site-scam-231003/

**Comment by Xandar-YT** [comment]
> https://torrentfreak.com/bestreamwise-iptv-anti-piracy-campaign-begins-with-fake-site-scam-231003/

Lmfao this is full of crap
