### ISSUE TITLE
Block ebook/epub scam download 

### ISSUE THREAD

**Issue by And96** [hagezi/dns-blocklists#1652]
`https://scribdbook.top`

`https://librilibs.com`

`https://dleggere.com`

**Comment by And96** [comment]
https://mujib-store28.blogspot.com

**Comment by iam-py-test** [comment]
Would you mind adding ` around the malicious URLs so people don't accidentally click them.
Thanks

**Comment by And96** [comment]
Yes obviously. Thanks for the suggestion!

**Comment by iam-py-test** [comment]
Thank you for reporting these.

**Comment by iam-py-test** [comment]
Added, thanks
Related:
```
xn4iqv.succyarthyry.com (whole domain can be blocked)
unkinerecle.com
```
From: https://web.archive.org/web/20231002191235/https://tria.ge/231002-w6m2xadg3s/behavioral1
