### ISSUE TITLE
cdn.eu1.exponea.com

### ISSUE THREAD

**Issue by Boulder08** [hagezi/dns-blocklists#1654]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

cdn.eu1.exponea.com

### Why should the domain(s) be unblocked?

It was whitelisted in #1613 , but still blocked.

**Comment by hagezi** [comment]
Sorry, fixed on next update.

**Comment by hagezi** [comment]
@Boulder08 It was only blocked in the aggressive lists, not in the Pro.

**Comment by hagezi** [comment]
No, my mistake, eu1.exponea.com was still blocked. I had overlooked the rule.
