### ISSUE TITLE
dc.dqa.samsung.com

### ISSUE THREAD

**Issue by nightznero** [hagezi/dns-blocklists#1657]
Helloz!

I have a question about rule from topic. I've noticed this adress is pinged few times a day in Samsung phone. I see its blocked on Pro++ but on Pro didn't find it here. And here is my question,if its pinged by the system but its not on Pro list,does its contain any usefull informations like Samsung sync or smthg or its just another tracker and can be easily blocked? Would be nice if anyone have informations and would share em here.
Best Regards, NIGHTZNERO.

**Comment by hagezi** [comment]
Device Quality Agent (DQA) is a programme that monitors data connections on Samsung devices.

If DQA detects a problem with the connection, it automatically turns off Wi-Fi to prevent further problems.
