### ISSUE TITLE
Vimeo blocked

### ISSUE THREAD

**Issue by dmbmke** [hagezi/dns-blocklists#1659]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

vimeo.com

### Why should the domain(s) be unblocked?

 It's a reputable video host and shouldn't be blocked by default.

**Comment by hagezi** [comment]
Thanks, will be removed asap ...
