### ISSUE TITLE
Malware Domains

### ISSUE THREAD

**Issue by AAraonWPaul** [hagezi/dns-blocklists#166]
Hello 👋 good blocklists, these popup malware domains should be added, I got them from sports streaming sites:

nielviok.cf
kallarann.gq
jandin.gq
web.quoabide.top
milfme.com
web.zoneimage.site
dylacha.tk
waumari.tk
web.tumbleceq.in
web.squirmaccess.site
web.benefitcolor.xyz
track.findb.news
web.zoombleat.top
web.grittyago.xyz
wineshasi.cf
web.spywax.site
xonanere.ga
karindal.ga
web.aeratevenal.site
web.cannondate.top
deugahat.gq
web.acidicadorn.top
leelabea.cf
girlsfinder.life
beladra.cf
freychang.fun
web.actgrovel.site
ysiquaarac.ga
nielviok.cf
web.grincanis.site
web.spurtparole.top
llantana.ml
web.datelovetime.xyz
lhamad.gq
web.jazztunnel.top
quinete.ga
web.blandfain.site
web.hanfallow.online
web.groupabet.site
tracking.lovematchflirt.com
tracking.latedreamdate.com
web.gristwattle.online

**Comment by hagezi** [comment]
Thank you, will check and add them.

**Comment by hagezi** [comment]
Added, will be included in the lists with the next full update.

**Comment by hagezi** [comment]
Included
