### ISSUE TITLE
有广告的网站

### ISSUE THREAD

**Issue by biange200** [hagezi/dns-blocklists#167]
http://www.cibaipuki.com/

**Comment by hagezi** [comment]
What should I do with it?

**Comment by biange200** [comment]
I thought you were also responsible for filtering ads, but you're only responsible for adding rule sources.

**Comment by hagezi** [comment]
You send me a link and expect me to see brightly what to do with it?

I don't see ads:

![grafik](https://user-images.githubusercontent.com/104343908/211056083-af852d4d-efc4-4992-a8a7-2188982768fd.png)

**Comment by hagezi** [comment]
added
