### ISSUE TITLE
data.meethue.com

### ISSUE THREAD

**Issue by jondagle** [hagezi/dns-blocklists#1672]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

data.meethue.com

### Why should the domain(s) be unblocked?

Hello, first time reporting here. 
data.meethue.com appears to be necessary for firmware updates for the hub and devices. diag(nostic).meethue.com seems unblocked, though it is reported as a telemetry site in some reddit threads. Maybe these are mixed up on your list?

**Comment by hagezi** [comment]
Hi @jondagle, 

thanks for your support and the advice.

`data.meethue.com` will be removed in the next update.

`diagnostics.meethue.com` is unblocked because it seems to be used for "out of home" control and software update check, see here: https://github.com/hagezi/dns-blocklists/issues/208#issuecomment-1397562623

Could you test this and see if it is correct?

Cheers,
Gerd

**Comment by jondagle** [comment]
Thank you very much. And thank you for your great list! 

Unfortunately I cannot test that since I don't use the Hue app/account for out of home access. However, this thread seems to confirm diag.meethue.com is related to out of home access.
https://www.reddit.com/r/pihole/comments/13sdwl3/hue_lights_hub/

I thought diag was just a new name for diagnostics.meethue.com (not many posts refer to the former), but they yield different IPs from DNS...
`~% dig @8.8.8.8 data.meethue.com +short  
54.216.117.174
3.251.22.95
52.211.152.148 
~ % dig @8.8.8.8 diag.meethue.com +short  
99.80.116.23
46.51.188.91
52.48.41.28 
~ % dig @8.8.8.8 diagnostics.meethue.com +short
34.117.13.189`

**Comment by hagezi** [comment]
Thanks, I'll leave the domain unblocked for now. I have someone else in my circle of acquaintances who can test it. Thank you for your effort.
