### ISSUE TITLE
data-api.eva.ua

### ISSUE THREAD

**Issue by Fqwe1** [hagezi/dns-blocklists#1679]
### Which domain(s) should be blocked?

data-api.eva.ua

### Why should these domain(s) be blocked?

Tracking

**Comment by hagezi** [comment]
@Fqwe1 Thanks, do you have a recorded payload or more details about the domain, what is being tracked?

**Comment by Fqwe1** [comment]
Marked as a beacon in uBlock Origin and sends a device type and current page

**Comment by hagezi** [comment]
Thanks. ;)
