### ISSUE TITLE
False Positive - app.link.nba.com

### ISSUE THREAD

**Issue by AAraonWPaul** [hagezi/dns-blocklists#168]
Need it to access NBA all star voting: (and any other service redirect)

Test:  https://rpt.rs/3YIBtSz
https://celtics.com/voteJB

**Comment by hagezi** [comment]
Thanks, will be removed.

ping source: @notracking

**Comment by hagezi** [comment]
removed.

**Comment by notracking** [comment]
Thanks, also whitelisted 'clickdimensions.com' as this a CNAME.
