### ISSUE TITLE
Please add a new rule list

### ISSUE THREAD

**Issue by biange200** [hagezi/dns-blocklists#1680]
https://github.com/sbwml/halflife-list
![Screenshot_20231007_225555.jpg](https://github.com/hagezi/dns-blocklists/assets/37582806/2b5c0c03-b348-4521-a03d-c6f3fbd4c059)

**Comment by hagezi** [comment]
The individual lists (EasyList, ...), which contain extractable rules for DNS, are already used.
https://github.com/hagezi/dns-blocklists/blob/main/sources.md

https://github.com/hagezi/dns-blocklists/blob/main/sources.md
