### ISSUE TITLE
List of unsafe websites

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#1685]
Unsafe Sites / Software by fmhy.net
 Free Media Heck Yeah, is an open-source community-driven platform that provides a collection of resources across various categories.

https://gist.githubusercontent.com/Rust1667/df78d493cf3c00340c535d93e303c4f9/raw

This list includes some popular websites like opera and McAfee it's a bit too Aggressive, you might want to look into it

**Comment by hagezi** [comment]
Thanks, I'll have a look at the list.

**Comment by iam-py-test** [comment]
FYI that list is technically in violation of GPL as the fitgirl entries are copied from uBlock Origin's badware list, but this list isn't licensed under GPLv3 and doesn't even attribute the uBo team.

**Comment by hagezi** [comment]
@iam-py-test It is a list of public domains that can be found in various places on the net, what do you want to "license"?

**Comment by iam-py-test** [comment]
```adblock
||fitgirl-repacks.*^$all,domain=~fitgirl-repacks.site
||fitgirl-repack.*^$all,domain=~fitgirl-repacks.site
||fitgirlrepacks.*^$all,domain=~fitgirl-repacks.site
||fitgirlrepack.*^$all,domain=~fitgirl-repacks.site
||fitgirls-repack.*^$all,domain=~fitgirl-repacks.site
||fitgirl-repacks-site.org^$doc,domain=~fitgirl-repacks.site
```
Copy-pasted out of uBo's badware list: https://github.com/uBlockOrigin/uAssets/blob/204cf372f0be4a97240ed74ca84cb8de88d3c208/filters/badware.txt#L3358C15-L3358C15

**Comment by hagezi** [comment]
Yes, that is unpleasant.

**Comment by hagezi** [comment]
List seems to be down now `404: Not Found`

**Comment by iam-py-test** [comment]
Interesting...
