### ISSUE TITLE
False Positive - [tnt-ea.com]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#169]
I have this issue when using pro++, when this link got blocked, i can't login in battlefield mobile game.

Link : tnt-ea.com

I can login after whitelisting it.

**Comment by hagezi** [comment]
Thanks, removed.

Ping source: @badmojr @anudeepnd

**Comment by anudeepND** [comment]
Thanks for notifying @hagezi, it wi be removed in the next update
