### ISSUE TITLE
Skyticket

### ISSUE THREAD

**Issue by Naxterra** [hagezi/dns-blocklists#1694]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

skyticket.sky.de

### Why should the domain(s) be unblocked?

It is WOWTV Germany subscription page. (Streaming service)

**Comment by hagezi** [comment]
Thanks, will be fixed asap.
