### ISSUE TITLE
trackjs.com

### ISSUE THREAD

**Issue by Slipi089** [hagezi/dns-blocklists#1698]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

capture.trackjs.com

### Why should the domain(s) be unblocked?

The Paradox Launcher of the star trek invinite game cannot establish a connection without this domain.

**Comment by hagezi** [comment]
Error Tracker, will not be unblocked for Ultimate:
https://slayterdev.github.io/tracker-radar-wiki/domains/trackjs.com.html
