### ISSUE TITLE
JB Hi-Fi Phishing website - block request

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#170]
Can you kindly please block `https://jbhivi.store/`

It is a phishing website and targets https://jbhifi.com.au, they have [put up a post on Facebook warning the public and in the screenshot is the URL](https://m.facebook.com/JBHiFi/photos/a.214773761888730/6299810073385038/?type=3&mibextid=Nif5oz)

**Comment by hagezi** [comment]
Thanks, will be added.

**Comment by hagezi** [comment]
Included
