### ISSUE TITLE
parrot Sec os 

### ISSUE THREAD

**Issue by Amateur-God** [hagezi/dns-blocklists#1701]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Fake, Threat Intelligence Feeds, DoH/VPN/TOR/Proxy Bypass

### Which domain(s) should be unblocked?

parrotsec.org

### Why should the domain(s) be unblocked?

this domain is a secure domain for a Linux Penetration testing OS, im not sure why it would be blocked as a malicious domain, it is in the ```Match found in https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/doh-vpn-proxy-bypass.txt:
  ||parrotsec.org^```

**Comment by hagezi** [comment]
@Amateur-God Thanks, it was not blocked as a malicious domain, but in the bypass list because it allows you to bypass your DNS. That's why it's also included in https://github.com/hagezi/dns-blocklists#bypass.
