### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Krishna-art-dev** [hagezi/dns-blocklists#1705]
Using nextdns with your pro Blocklist 

>![Screenshot_2023-10-14-12-24-51-90_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/hagezi/dns-blocklists/assets/121063162/f45f18b1-07f7-435a-895f-2f21b88bdec9)>

Using your pro Blocklist adblock version on brave browser

>![Screenshot_2023-10-14-12-25-04-46_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/hagezi/dns-blocklists/assets/121063162/9c731d95-91d3-47f3-8778-c2ce6e13221c)>

Can you tell me why that weird text is coming when using just DNS and why it goes away when using it in brave browser
Blocking pinkleo.pro domain blocks that weird text and that close button that you can see on bottom above search button

**Comment by hagezi** [comment]
With DNS Blocking you can only block the resolution of a domain. Content blockers can be used to hide page content, block executed scripts on pages and ...

**Comment by Krishna-art-dev** [comment]
Blocking pinkleo.pro blocks all that weird text and that close button goes away without using your Blocklist in brave just using your Blocklist in DNS

**Comment by hagezi** [comment]
Yes, because Brave hides the blocked content, if you only block it using DNS, the placeholder is visible.

**Comment by Krishna-art-dev** [comment]
Thanks
