### ISSUE TITLE
mntzrlt.net and chillx.top

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#171]
Hagezi Ultimate

**Site:** `https://www.cnn.com/cnn-underscored/reviews/best-webcam`
- Click second product link "Microsoft Lifecam HD-3000" -> `https://knl.mntzrlt.net/shop-rest/api/track/v2/1382/6/11946?oi=7716147823&xp=11&mk=USD_EN&tu=https%3A%2F%2Fwww.walmart.com%2Fip%2FMicrosoft-LifeCam-HD-3000-for-Business-web-camera%2F20636486`
- With uBO, as long as `mntzrlt.net` is allowed at DNS level, the user is warned but can still navigate to the page.
   - I'm unsure about AdGuard.
- `mntzrlt.net` **prevents navigation if blocked at the DNS level** -- at least for me.

**Site:** `https://www.pressplay.top/movies/puss-in-boots-the-last-wish/`

- allowlist `chillx.top` for video to work

**Comment by hagezi** [comment]
Thanks, removed.
