### ISSUE TITLE
INFO/NextDNS: Block lists are shown as up-to-date, but they are not.

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#1712]
Under privacy, the block lists are shown as recently updated, but in the background they do not seem to be up-to-date.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/b4d2abd8-8838-4c37-bf14-26b2cbe6e593)

**Example domain:** `so.n11.com`

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/82cb701d-18cb-47b9-8dd3-1b4ac614bccb)

Supposedly blocked by my Light, Multi, Pro, Pro++ and Ultimate lists, the domain is no longer on the lists since yesterday. In other DNS services, the domain is also not blocked using my lists.

The same applies to OISD, the domain is not included, but is shown by NextDNS as blocked by OISD.

```
curl -s https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt | grep -P '(\.|^)n11\.com$'

*.athena-event-provider.n11.com
*.ckozwx.n11.com
*.h.n11.com
*.ipr.n11.com
*.metrics.n11.com
*.tx.n11.com
```

**Furthermore, domains that are new on the lists are also not blocked in NextDNS.**

**Example domain:** `c.amazon-adsystem.com`

Blocked in Ultimate, but not with NextDNS using Ultimate:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/cb93cbee-d509-4142-8217-019a914809f4)

```
curl -s https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt | grep -P '(\.|^)c\.amazon\-adsystem\.com$'

*.c.amazon-adsystem.com
```

I have opened a ticket in the help forum: https://help.nextdns.io/t/p8yhdgm

FYI: @sjhgvr @yokoffing @romaincointepas @rs

Cheers,
Gerd

**Comment by rs** [comment]
Thanks for the heads up, we identified the issue that started this week-end. We are working on a resolution.

**Comment by rs** [comment]
Should be fixed now.

**Comment by hagezi** [comment]
Thanks @rs, fixrd.

**Comment by ijuliank** [comment]
> Should be fixed now.

Hi @rs can you please unban me from the nextdns github
