### ISSUE TITLE
When Your Pro Blocklist will come in adguard. You have written coming soon, means this week or when?

### ISSUE THREAD

**Issue by Krishna-art-dev** [hagezi/dns-blocklists#1713]

**Comment by hagezi** [comment]
It is currently on their development environment for testing. When the test is completed, it will be transferred to production. I can't say how long that will take.

**Comment by hagezi** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/pull/378 soon ...

**Comment by hagezi** [comment]
In AdGuard DNS (https://adguard-dns.io), the following of my block lists are now available:

- Multi Normal, Pro, Pro++, Ultimate
- Threat Intelligence Feeds
- Gambling
- Anti Piracy
- Referral Allowlist
