### ISSUE TITLE
False positive: asusiran.com

### ISSUE THREAD

**Issue by Chocolate4U** [hagezi/dns-blocklists#1714]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT

### Which domain(s) should be unblocked?

asusiran.com

### Why should the domain(s) be unblocked?

`asusiran.com` is an Iranian online retailer selling laptops, computer parts and other electronic devices. It isn't related to ads or ad services.

**Comment by hagezi** [comment]
Compromised websites (JackalControl C2)

https://securelist.com/goldenjackal-apt-group/109677/

`[hxxps://asusiran[.]com/wp-content/themes/woodmart/inc/modules/cache[.]php](https://opentip.kaspersky.com/https%3A%2F%2Fasusiran.com%2Fwp-content%2Fthemes%2Fwoodmart%2Finc%2Fmodules%2Fcache.php/?utm_source=SL&utm_medium=SL&utm_campaign=SL)`

**Comment by Chocolate4U** [comment]
It seems that it has been resolved, as kaspersky no longer reports them as malicious
```
https://opentip.kaspersky.com/https%3A%2F%2Fasusiran.com%2Fwp-content%2Fplugins%2Fpersian-woocommerce%2Finclude%2Fclass-cache.php
https://opentip.kaspersky.com/https%3A%2F%2Fasusiran.com%2Fwp-content%2Fthemes%2Fwoodmart%2Finc%2Fmodules%2Fcache.php
```
Also no reputable AV reports them as malicious on VirusTotal
```
https://www.virustotal.com/gui/url/752d8cbc55937a83b07d7db887571bc40fe7949be72b41e400df00d339caddca/detection
https://www.virustotal.com/gui/url/b925f19c0a0f59261e83538681f63aa556f8989d541e78dd06b6fed21e7e178a/detection
```

**Comment by hagezi** [comment]
Thank you, I was just checking.
