### ISSUE TITLE
False Positive: online.unionbankph.com

### ISSUE THREAD

**Issue by jmanalansan** [hagezi/dns-blocklists#1716]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

online.unionbankph.com

### Why should the domain(s) be unblocked?
It is the primary URL/hostname for the bank's online banking services.
Unable to access the bank's mobile app and web banking

![ScreenShot 2023-10-17 at 04 19 39@2x](https://github.com/hagezi/dns-blocklists/assets/1277299/ed4a0207-0db3-4562-a8af-89ebe3331fa4)

**Comment by hagezi** [comment]
ping @scafroglia93 `blocklists-various`

**Comment by hagezi** [comment]
@jmanalansan will be fixed asap.

**Comment by hagezi** [comment]
@jmanalansan Fixed, should also be fixed in ControlD in the next half hour.

**Comment by scafroglia93** [comment]
fixed

Il giorno mar 17 ott 2023 alle ore 10:37 Gerd ***@***.***> ha
scritto:
