### ISSUE TITLE
imasdk.googleapis.com

### ISSUE THREAD

**Issue by Sly777** [hagezi/dns-blocklists#1717]
### Which domain(s) should be blocked?

imasdk.googleapis.com

### Why should these domain(s) be blocked?

The IMA SDK is a Google Ads SDK that allows developers and publishers to show interactive and video ads on their websites and mobile apps.

Maybe this wouldn't fit on light and normal but currently I'm using Pro++ and it doesn't block it unfortunately. I'm using nextDNS and this subdomain is blocked by "NextDNS Ads & Trackers Blocklist"

**Comment by hagezi** [comment]
Thanks, bit Videos on websites and apps that use this software development kit cannot start if the domain is blocked.

That is why it has been unblocked in most block lists. Blocking is left to browser content blockers, which can decide for which website the domain can be blocked or not. I can't block it for the masses via DNS.

**Comment by Sly777** [comment]
Thanks for the information @hagezi  👍
