### ISSUE TITLE
Enhancement: Fix the Used Sources page

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#172]
Tweak `Used Sources` page so that [Ultimate](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#ultimate) only shows lists that are not used in [Pro.Plus](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#proplus).

This matching the formatting of the three earlier lists.

**Comment by hagezi** [comment]
For the sources used, the actual sources used for the build process are shown per list.
Since the whitelisting process is somewhat more moderate for the more aggressive lists, the sources are read in and processed again. Therefore, they are also listed again for pro.plus and ultimate.
