### ISSUE TITLE
[SCAM] "healy world"

### ISSUE THREAD

**Issue by MIOGMIOG** [hagezi/dns-blocklists#1724]
### Which domain(s) should be blocked?

```
healy.world
www.healy.world
my.healy.world
healyworld.net
www.healyworld.net
partner.healyworld.net
healy.shop
www.healy.shop
asia.healy.shop
au.healy.shop
canada.healy.shop
eu.healy.shop
india.healy.shop
japan.healy.shop
korea.healy.shop
mexico.healy.shop
thailand.healy.shop
us.healy.shop
```

### Why should these domain(s) be blocked?

This company makes "medical devices" that claim absulute bizzare things, that seem (and are) physically impossible plus their website is filled with stock photos and their cheapest "medical device" (small platic cube that has baterry, few led lights and microusb port in it) costs more than 400 dollars. Theres no way that this isnt a scam lmao
U can also read more about it on reddit: https://www.reddit.com/r/antiMLM/comments/z61vrv/the_science_behind_healy_a_lesser_talked_about_mlm/
https://www.reddit.com/r/MLM/comments/iltvpk/anyone_heard_of_healy_pseudomedical_device/
Also this lmfao https://www.reddit.com/r/antiMLM/comments/xrmaar/speechless/
Edit 1:
this company also has android apps that have "location" and other suspicious permissions, so its probably also spyware/malware (I didnt test which domains these apps are pinging, so its probably good to analyze these apps to find other potential spyware? domains)
https://play.google.com/store/apps/details?id=air.net.healyworld.healy
https://play.google.com/store/apps/details?id=world.healy.healy
https://play.google.com/store/apps/details?id=net.healyworld.healadvisor
https://play.google.com/store/apps/details?id=de.timewaver.timewaver
https://play.google.com/store/apps/details?id=net.healyworld.healadvisoranalyse
Edit 2: these apps have a lot of downloads (around 50k - 100k) so its not that small problem, I think it is pretty bad problem

**Comment by hagezi** [comment]
@MIOGMIOG I see it like you, but the blocking will certainly annoy some people. Let's see how long it takes before the first one reports them as false positives.

**Comment by MIOGMIOG** [comment]
> @MIOGMIOG I see it like you, but the blocking will certainly annoy some people. Let's see how long it takes before the first one reports them as false positives.

well, I think that type of people this "scam?" is made for doesnt even know how to install an adblocker so I would be very surprised if someone reports this as false positive lol
also these domains got added to KAD, stevenblack and OISD lists which Im proud of :D
