### ISSUE TITLE
Is the Finnish Easylist Addition included?

### ISSUE THREAD

**Issue by 70T** [hagezi/dns-blocklists#1726]
Is the [Finnish Easylist Addition](https://github.com/finnish-easylist-addition/finnish-easylist-addition) included in the sources for your blocklists (specifically Pro++, since that's what I'm using)? I couldn't find it on the sources page. Should it be included in your opinion?

I'm going through my NextDNS filters and am wondering if it'd be redundant to include the list separately. If it's not included, is there any specific reason for it?

**Comment by hagezi** [comment]
Thanks @70T, I had overlooked this, it will be included in the next update (16:00 UTC).
