### ISSUE TITLE
Fake Keepass site

### ISSUE THREAD

**Issue by th3m** [hagezi/dns-blocklists#1729]
### Which domain(s) should be blocked?

xn--eepass-vbb.info

### Why should these domain(s) be blocked?

source:
[https://arstechnica.com/security/2023/10/google-hosted-malvertising-leads-to-fake-keepass-site-that-looks-genuine/](url)

**Comment by iam-py-test** [comment]
FYI the link is broken
Thanks

**Comment by th3m** [comment]
fixed thanks
