### ISSUE TITLE
sitereview.symantec.com

### ISSUE THREAD

**Issue by SeriousHoax** [hagezi/dns-blocklists#1730]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

`sitereview.symantec.com`

### Why should the domain(s) be unblocked?

It's a website from Symantec to check website's reputation. It's a legit site so, it should be unblocked.

**Comment by iam-py-test** [comment]
I have reported a false positive: https://gitlab.com/malware-filter/phishing-filter/-/merge_requests/9
It seems someone submitted a report from Symantec for a phishing site to PhishTank as a phishing website.
Thanks

**Comment by SeriousHoax** [comment]
@hagezi @iam-py-test Just to let you guys know that at the time of me writing this, even Quad9 DNS is blocking the site. So, looks like the original PhishTank false positive issue hasn't been fixed yet. 
An alternative for this website is: `https://sitereview.bluecoat.com/` and another one under the Norton name is: `https://safeweb.norton.com/`. 
These two are not blocked.

**Comment by iam-py-test** [comment]
> the original PhishTank false positive issue hasn't been fixed yet

I don't think anyone has been able to even report a false positive to PhishTank yet, due to them restricting who can get an account.
