### ISSUE TITLE
gs.statcounter.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#1740]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

gs.statcounter.com

### Why should the domain(s) be unblocked?

Cannot open the stat counter website.

https://en.m.wikipedia.org/wiki/StatCounter

**Comment by hagezi** [comment]
https://slayterdev.github.io/tracker-radar-wiki/domains/statcounter.com.html

**Comment by hagezi** [comment]
Because they use generic domains like `c*.statcounter.com` and others, `*. statcounter.com` remains completely blocked in Ultimate.

**Comment by yokoffing** [comment]
> Because they use generic domains like `c*.statcounter.com` and others, `*. statcounter.com` remains completely blocked in Ultimate.

That's fair. I don't want to completely allowlist them in other lists.

Wouldn't `statcounter.com` and `www.statcounter.com` be sufficient for everything but Ultimate?

**Comment by yokoffing** [comment]
I do not want to unblock `c.statcounter.com` or others.

**Comment by hagezi** [comment]
`gs.statcounter.com` is on the allowlist, this also unblocks `statcounter.com` and `www.statcounter.com`. They were already unblocked for the non-aggressioven lists, and will be unblocked for the Pro++ with the next update.

**Comment by Marko-98** [comment]
@hagezi (gs.)`statcounter.com` is blocked in Pro++ again. Can we get it unblocked? Thanks!🙂

**Comment by hagezi** [comment]
Why? It's tracking, and Pro++ is an aggressive list.

**Comment by Marko-98** [comment]
`gs.statcounter.com` shows statistics about browsers, OS and device marketshare per region and country. Based on your previous comment
> `gs.statcounter.com` is on the allowlist, this also unblocks `statcounter.com` and `www.statcounter.com`. They were already unblocked for the non-aggressive lists, and will be unblocked for the Pro++ with the next update.

I thought it's blocked by mistake.

**Comment by hagezi** [comment]
`www.statcounter.com/counter/counter.js` is a tracking script from Statcounter that websites use for analytics. That is why the root domain is blocked, and consequently all subdomains as well. Being added to the aggressive lists won't change that either.

**Comment by hagezi** [comment]
@Marko-98 

In the code, the script reads the page referrer, page title, current URL, and screen width and height before assembling tracking requests. It also uses cookies, localStorage, and sessionStorage to manage visitor uniqueness and session state when those storage options are available.

The same file contains logic for click tracking, download detection, exit-link detection, and ad-click handling. It sends data to Statcounter endpoints such as t.php and click.gif under the Statcounter domain.

**Comment by Marko-98** [comment]
@hagezi Thanks for detailed explanation. If that's the case, then alright; I completely agree it should be blocked in all blocklists if it isn't already.

Thanks again! 🙂
