### ISSUE TITLE
freedium.cfd

### ISSUE THREAD

**Issue by pidus** [hagezi/dns-blocklists#1742]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

https://freedium.cfd/

### Why should the domain(s) be unblocked?

It is a Medium paywall bypasser.

[Example](https://freedium.cfd/https://medium.com/@PurpleGreenLemon/what-exactly-did-kotlin-learn-from-java-55f566659b8d)

**Comment by hagezi** [comment]
via `cfd` TLD on https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt

ping @dandelionsprout for exclusion.

**Comment by iam-py-test** [comment]
Thank you for reporting this. I have fixed it in https://github.com/DandelionSprout/adfilt/commit/67d6b17f05840abc5ae83eb3d3943af37cace141.

**Comment by hagezi** [comment]
Thanks @iam-py-test

**Comment by pidus** [comment]
Thanks @iam-py-test and @hagezi

**Comment by hagezi** [comment]
@iam-py-test I use https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt as a source, it's not fixed in there yet. Is the file generated or do you still have to modify it?

**Comment by hagezi** [comment]
@iam-py-test https://github.com/DandelionSprout/adfilt/pull/933

**Comment by iam-py-test** [comment]
I have no clue how those files are automatically generated (I think Imre runs a Python script on his computer & uploads the result), but I assume your changes will be overwritten next time it is updated.
Thanks

**Comment by iam-py-test** [comment]
Sorry, didn't see that comment
