### ISSUE TITLE
securescanmtde.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#1743]
### Which domain(s) should be blocked?

`securescanmtde.com` NRD

ex `https://securescanmtde.com/de-avira/?uclick=bzpm37i4&uclickhash=bzpm37i4-bz8wa7i4-4pvr-0-174p-hq17-hqgx-76fb6a#`

### Why should these domain(s) be blocked?

Malware spam site. "You have 7 viruses!"

cc: @iam-py-test

**Comment by iam-py-test** [comment]
Added. Thanks @yokoffing
