### ISSUE TITLE
Block Request - playerpreferences.riotgames.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#175]
Link : playerpreferences.riotgames.com

I don't see any problem when blocking this site while playing League of Legends Wild Rift. It's appear when im doing login. The behaviour seems like ekg.riotgames.com, only appears when doing login, but not break anything when it blocked.

Not sure it will break function in other games like Valorant or LOL PC.

**Comment by hagezi** [comment]
Thanks, but `playerpreferences.riotgames.com` is used to load or save the player settings. The API is used for example in this tool:
https://github.com/weedeej/ValorantCC

See source code:
https://github.com/weedeej/ValorantCC/blob/8c28dde791e41c9602ace1bfddc1ecf50a4c38a3/ValorantCC/src/Processor.cs#L151

By blocking, you also block the API.

See also:
https://github.com/aPinat/riot-documentation#player-preferences

Do not include the domain.

**Comment by MagicalAlchemist** [comment]
Thank you for clarifying, i will add to my personal blacklist since im not valorant player. This raises my suspicions because appear in a game that has nothing to do with Valorant gameplay.

**Comment by hagezi** [comment]
@MagicalAlchemist It is used in all Riot games for player settings.
