### ISSUE TITLE
Correios (Brazilian post) breaks with list Normal or Pro

### ISSUE THREAD

**Issue by ciro-mota** [hagezi/dns-blocklists#1754]
I use normal (or pro) lists with Rethinkdns on Android and I have recently noticed that access to the Correios app (Brazil post) has access problems. If I disable the use of private DNS with the lists, access occurs normally.

Unfortunately I don't have enough knowledge to debug the app and see which domain is being blocked.

Thank you.

**Comment by hagezi** [comment]
Thanks, I can't test the app in my region, if you can't tell me any blocked domains, we'll have to hope someone from the community can test it and find herUs which blocked domains are causing the behaviour.

Can you describe exactly when the problem occurs? Does the app not start?

Can someone here help?

**Comment by ciro-mota** [comment]
I downloaded the Rethinkdns app and was able to check these IPs and domains, but I don't see them in your list. I don't think these are the addresses that are blocked.

![Screenshot_20231025_175100_Rethink](https://github.com/hagezi/dns-blocklists/assets/57502603/b8acf9e0-ffbb-463e-a232-7d84cabbb77a)

About describing the problem, the app starts but prevents me from logging in.

![Screenshot_20231025_174701](https://github.com/hagezi/dns-blocklists/assets/57502603/5a737255-81f3-42e9-bb70-9ce8c723f504)

**Comment by hagezi** [comment]
The domains in your screenshot have an IP, so they are not blocked. You have to search for blocked domains in the log. See what is blocked when you click on the login button.

**Comment by hagezi** [comment]
@ciro-mota 

Someone from my Telegram community has tested the app, here is the result:

```
I tested here and I'm using ultimate. The app works normally, there are only two exclusively domains (both allowed):
proxyapp.correios.com.br
meucorreios.correios.com.br

Some domains are blocked while using the app, but they are generic domains, like "googleads.g.doubleclick.net" and "app-measurement.com".

I got the same error reported when trying to log in, but just retrying some times, it worked, without needing to disable ultimate list. 
And I tested disabling it also, and got the same log in error, and after retrying a few times it worked as well. 

So I think it's a problem of the app itself.
```

**Comment by ciro-mota** [comment]
Thank you very much to you and the other gentleman who helped in investigating this problem. I'll keep an eye out and if anything else comes up I'll post it again.

I think we can close this issue.
