### ISSUE TITLE
Fake shops

### ISSUE THREAD

**Issue by Axonym** [hagezi/dns-blocklists#1760]
### Which domain(s) should be blocked?

adidassuomi-fi.com
alohas-suomi.com
alohasfinland.com
alohassuomi.com
altrafi.com
altrafinland.com
altrahelsinki.com
altrasuomi.com
altrasuomifi.com
altrasuomioutlet.com
altrasuomishop.com
arcteryxfi.com
arcteryxfinland.com
arcteryxoutletsuomi.com
arcteryxsuomiale.com
asics-finland.com
asics-suomi.com
asicsale.com
asicsfi-suomi.com
asicsfi.com
asicsfinlandoutlets.com
asicshelsinki.com
asicshelsinki.net
asicsoutlet-suomi.com
asicsoutletsuomi.com
asicssuomi.com
asicssuomioutlet.com
balmain-suomi.com
balmainsuomi.com
balmainsuomishop.com
canada-gymshark.com
carhartt-suomi.com
carharttsuomi.com
caterpillar-finland.com
caterpillar-suomi.com
caterpillarfi.com
caterpillarinsuomi.com
caterpillarsuomi.com
caterpillarsuomiale.com
caterpillarsuomifi.com
champion-suomi.com
championhelsinki.com
championsuomi.com
columbia-suomi.com
columbiakengatsuomi.com
columbiasuomi-fi.com
columbiasuomifi.com
columbiasuomioutlet.com
columbiasuomis.com
comfitunderwear-suomi.com
converse-finland.com
converse-suomi.com
converseale.com
conversealesuomi.com
conversefi.com
conversehelsinki.com
converseinsuomi.com
converseoutlet-suomi.com
converseoutlethelsinki.com
converseoutletsuomi.com
conversesuomi.com
conversesuomi.net
conversesuomioutlet.com
conversexsuomi.com
crossfitsuomi.co
crossfitsuomi.com
demonia--suomi.com
demonia-finland.com
demoniafinland.com
demoniasuomi.com
demoniasuomi.net
demoniasuomioutlet.com
desigual-suomi.com
desigualsuomi.com
desigualsuomi.net
dope-suomi.com
dopeoutletsuomi.com
dopesnow-finland.com
dopesnow-suomi.com
dopesnowfinland.com
dopesnowsuomi-fi.com
dopesnowsuomi.com
dopesuomi-fi.com
dopesuomi.com
dopetakki-suomi.com
dopetakki.com
dopetakkisuomi.com
dubarrysuomi.com
ecco-suomi.com
eccooutlet-suomi.com
eccooutletsuomi.com
eccooutletsuomis.com
eccosuomi.com
eccosuomi.net
eccosuomioutlet.com
fjallraven-suomi.com
fjallravenoutletsuomi.com
fjallravensuomi.com
footjoy-finland.com
footjoy-suomi.com
footjoyfinland.com
footjoyssuomi.com
footjoysuomi.com
freedommoses-suomi.com
freedommosessuomi.com
gfore-suomi.com
gforefinland.com
gforesuomi.com
gforesuomi.net
groundies-finland.com
groundiesale.com
groundiesfinland.com
groundiesinsuomi.com
groundiesoutletsuomi.com
groundiessuomioutlet.com
gym-shark-canada.com
gym-shark-danmark.com
gym-shark-egypt.com
gym-shark-hungary.com
gym-shark-india.com
gym-shark-italia.com
gym-shark-philippines.com
gym-shark-romania.com
gym-shark-schweiz.com
gym-shark-suomi.com
gym-shark-turkiye.com
gym-shark.co.za
gym-sharkgreece.com
gym-sharkmexico.com.mx
gym-sharknorge.com
gym-sharksingapore.com
gym-sharksuomi.com
gym-sharkuaestore.com
gymshark-cz-shop.com
gymshark-españa.com.es
gymshark-fi.com
gymshark-finland.com
gymshark-italia.com
gymshark-no.com
gymshark-osterreich.at
gymshark-sk.sk
gymshark-suomi-fi.com
gymshark-suomi.com
gymshark-suomiale.com
gymshark-sweden.com.se
gymshark-turkiye-tayt.com
gymshark-uk-sale.com
gymshark-uk.com
gymshark.com.hr
gymsharkale.com
gymsharkalesuomi.com
gymsharkar.com
gymsharkauckland.com
gymsharkaustralia-au.com
gymsharkaustraliastores.com
gymsharkbutikkoslo.com
gymsharkcanadafactoryoutlet.com
gymsharkcanadastore.com
gymsharkcolombia-co.com
gymsharkcz.cz
gymsharkczsale.com
gymsharkczshop.cz
gymsharkdanmark.com
gymsharkdublin.com
gymsharkespaña.com
gymsharkespañaoutlet.com
gymsharkeufinland.com
gymsharkfi.com
gymsharkfinland.com
gymsharkhungarystore.com
gymsharkieonline.com
gymsharkindiashops.com
gymsharkinsingapore.com
gymsharkinsouthafrica.co.za
gymsharkinus.com
gymsharkmexicostore.com
gymsharkmexicotiendas.com.mx
gymsharknewzealand.co.nz
gymsharknzsale.com
gymsharkostereichs.com
gymsharkosterreichshop.com
gymsharkoutletsuomi.com
gymsharkoutletsverige.com.se
gymsharkoutletwebsite.com
gymsharkperu.com
gymsharkportugalstore.com
gymsharkpt.com
gymsharksbelgie.com
gymsharksbudapest.com
gymsharkshop.cz
gymsharksingaporeshop.com
gymsharkslovenijaeu.com
gymsharkslovensko.sk
gymsharksnorge.com
gymsharksouthafrica.com
gymsharkspainstore.com
gymsharkssuomi.com
gymsharkssverige.com
gymsharkstore.com.au
gymsharkstoreindia.com
gymsharkstorenyc.com
gymsharksuomi-fi.com
gymsharksuomi.com
gymsharksuomiale.com
gymsharksuomifi.com
gymsharksuomioutlet.com
gymsharksuomishop.com
gymsharkukoutlet.com
gymsharkwinkel.com
gymsharkzagreb.com
gymsharkzurich.com
gymsharkösterreich.com
haglofsoutlethelsinki.com
haglofsoutletsuomi.com
haglofssuomifi.com
hanwag-suomi.com
hanwagsuomi.com
hanwagsuomi.net
hellyhansen-fi.com
hellyhansen-suomi.com
hellyhansenfi.com
hellyhansenfinland.com
hellyhansenoutletsuomi.com
hellyhansensuomi.com
hellyhansensuomi.net
hoka-finland.com
hokaale.com
hokasuomi.com
hokasuomifi.com
icebugfinland.com
icebugfioutlet.com
icebugsfioutlet.com
icebugsuomi.com
icebugsuomi.net
ilsejacobsen-suomi.com
ilsejacobsensuomi.com
inov-8-suomi.com
inov-8suomi.com
joma-suomi.com
jomafinland.com
jomasuomi.com
kamik-suomi.com
kamikfinland.com
kamiksuomi.com
kamiksuomi.net
kappa-suomi.com
kappafi.com
kappasuomi.com
karhulenkkaritale.com
karhulenkkarithelsinki.com
keds-suomi.com
kedsoutletsuomi.com
kedssuomi.com
kedssuomishop.com
kickers-suomi.com
kickersfinland.com
kickerssuomi.com
legoale.com
legosuomi.com
loake-suomi.com
loakesuomi.com
loakesuomioutlet.com
lojagymsharkportugal.com
lornajane-suomi.com
lornajanesuomi.com
lornajanesuomi.net
louboutin-finland.com
louboutin-suomi.com
mizuno-finland.com
mizuno-suomi.com
mizuno-suomis.com
mizunofi.com
mizunofinland.com
mizunossuomi.com
mizunosuomishop.com
moonboot-suomi.com
moonbootfi.com
moonbootfinland.com
moonboothelsinki.com
moonbootssuomi.com
moonbootsuomi.com
moonbootsuomi.net
muckboot-suomi.com
muckbootale.com
muckbootinsuomi.com
muckboots-suomi.com
muckbootssuomi.com
muckbootsuomi.com
nautica-suomi.com
nauticasuomi.com
nikealesuomi.com
nikefinland.com
nikeinsuomi.com
nikeoutletsuomi.com
nikesuomi-fi.com
nikesuomi.com
nikesuomi.net
nikesuomioutlet.com
nikesuomishop.com
olukai-suomi.com
olukaifi.com
olukaisuomi.com
osirisfi.com
osirissuomi.com
osprey-suomi.com
ospreyfinland.com
ospreysuomi.com
ospreysuomi.net
outletadidas.com
outletadidasfi.com
outletarcteryx.com
outletcarhartt.com
outletconverse.com
outletdopesnow.com
outlethellyhansen.com
outletjoma.com
outletlego.com
outletmizuno.com
outletmuckboot.com
outletosprey.com
outletregatta.com
outletsalomon.com
outletveja.com
outletversace.com
palladium-finland.com
palladium-suomi.com
palladiumfi.com
palladiumfinland.com
palladiumhelsinki.com
palladiumoutletsuomi.com
palladiumsuomi.com
palladiumsuomishop.com
persol-suomi.com
pleaserssuomi.com
pleasersuomi.com
puma-fi.com
puma-finland.com
puma-suomi.com
pumafi-suomi.com
pumafi.com
pumafinland.com
pumainsuomi.com
pumaoutlet-suomi.com
pumasuomi.com
pumasuomi.net
pumasuomiale.com
pumasuomioutlet.com
pumasuomis.com
redwing-suomi.com
redwingsuomi.com
regatta-suomi.com
regattasuomi.com
restockssuomi.com
rvca-suomi.com
rvcasuomi.com
salmingale.com
salmingsuomi.com
salomon--suomi.com
salomon-finland.com
salomon-suomi.com
salomon-suomiale.com
salomonalesuomi.com
salomonfinland.com
salomonhelsinki.com
salomonoutletfi.com
salomonoutlethelsinki.com
salomonssuomi.com
salomonsuomi-fi.com
salomonsuomi.com
salomonsuomihuijaus.com
salomonsuomioutlet.com
salomonsuomishop.com
samsonite-suomi.com
samsonitesuomi.com
samsonitesuomi.net
sanuk-suomi.com
sanukale.com
sanukfinland.com
sanuksuomi.com
sanuksuomi.net
sendra-suomi.com
sendrasuomi.com
sendrasuomi.net
sendrasuomioutlet.com
sendrasuomis.com
skims-suomi.com
skimsale.com
skimssuomi.com
skimssuomi.net
skimssuomiale.com
superga-finland.com
superga-suomi.com
supergafi.com
supergasuomi.com
tedbaker-suomi.com
tedbakerale.com
tedbakerfinland.com
tedbakeroutletsuomi.com
tedbakersuomi.net
teva-finland.com
tevafi.com
tevafinland.com
tevahelsinki.com
tevaoutletsuomi.com
tevassuomi.com
tevasuomi.com
timberland--suomi.com
timberland-finland.com
timberland-suomi.com
timberlandfi-suomi.com
timberlandfi.com
timberlandhelsinki.com
timberlandoutletfi.com
timberlandoutlethelsinki.com
timberlandsuomi.com
timberlandsuomi.net
timberlandsuomifi.com
timberlandxsuomi.com
timbsuomi.com
uniqlo-finland.com
uniqlo-suomi.com
uniqloale.com
uniqlofinland.com
uniqlohelsinki.com
uniqlosuomi.com
uniqlosuomi.net
uniqlosuomioutlet.com
vans-finland.com
vansale.net
vansfi.com
vansfioutlet.com
vanshelsinki.net
vansoutlet-suomi.com
vansssuomi.com
vanssuomi.net
vanssuomioutlet.com
veja-fi.com
veja-finland.com
veja-suomi.com
veja-suomiale.com
vejafioutlet.com
vejahelsinki.com
vejassuomi.com
vejasuomi.net
vejasuomiale.com
vejasuomioutlet.com
versaceinsuomi.com
versacesuomi.net
vessi-suomi.com
vessiale.com
vessisuomi.com
vitaelight-suomi.com
vivobarefoot-fi.com
vivobarefoot-finland.com
vivobarefoot-suomi.com
vivobarefootale.com
vivobarefootalesuomi.com
vivobarefootfi.com
vivobarefootsuomi.com
vivobarefootsuomiale.com
youngla-suomi.com
younglasuomi.com
younglasuomi.net

### Why should these domain(s) be blocked?

Fake shops

**Comment by iam-py-test** [comment]
I have a few questions (I am NOT affiliated with @hagezi):
- a few of these domains appear to be dead (ie `alohassuomi.com`, `vejasuomiale.com`)
- Would you mind providing more information?
Thanks

**Comment by Axonym** [comment]
Yeah sure! 
So I initially noticed some of these fake shops in Google Search when searching for some brand + country name. And I noticed a certain pattern with the domain names after looking through the fake shops which targeted Finnish people.

I then created a long list of these possible domain names and started to look if and where (through what domain registrar) they are registered through some bulk tool I found (Thus the list might have dead domains). 
I assume this is just tip of the iceberg since I was able to find something like 83 domains for fake Gymshark shops alone.

**Comment by iam-py-test** [comment]
> Thus the list might have dead domains

Only 7/456 (not that bad)
Living ones:
[list.txt](https://github.com/hagezi/dns-blocklists/files/13184005/list.txt)
Thanks

**Comment by hagezi** [comment]
Thanks @Axonym @iam-py-test
