### ISSUE TITLE
Gaming Bible

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#1768]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

micro.rubiconproject.com

### Why should the domain(s) be unblocked?

Some videos won't display unless this domain is unblocked. Example listed below. While this domain is affiliated with tracking, I didn't know if you wanted to allow the domain on less aggressive lists.

Example
https://www.gamingbible.com/news/unreal-engine-5-horror-most-realistic-game-ever-546174-20231018

**Comment by hagezi** [comment]
The videos require the following unblocked domains:

```
micro.rubiconproject.com
c.amazon-adsystem.com

```
Will not be unblocked in Ultimate.
