### ISSUE TITLE
4fstore.com

### ISSUE THREAD

**Issue by darkfence** [hagezi/dns-blocklists#1769]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

4fstore.com

### Why should the domain(s) be unblocked?

It’s just a sport wear store. Nothing to block here.

**Comment by hagezi** [comment]
ping @jarelllama
