### ISSUE TITLE
nintendo

### ISSUE THREAD

**Issue by Slipi089** [hagezi/dns-blocklists#1774]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Anti Piracy

### Which domain(s) should be unblocked?

www.nintendo.de

### Why should the domain(s) be unblocked?

Is there a specific reason why nintendo.de is listed under Anti Piracy? It would be nice if it would be excluded here, then you can also use the eshop. Thank you very much.

**Comment by hagezi** [comment]
Blocked by CNAME. `*.llnwd.net` will be removed.
