### ISSUE TITLE
appmetrica.yandex.ru not blocked | Multi PRO Adblock | PiHole

### ISSUE THREAD

**Issue by SeimusS** [hagezi/dns-blocklists#1775]
### Which domain(s) should be blocked?

appmetrica.yandex.ru

### Why should these domain(s) be blocked?

Yandex has probably a new domain for metrics "appmetrica.yandex.ru" which is not blocked. Checking the list filter on your GitHu repo this domain is missing in the list.

**Comment by iam-py-test** [comment]
I am curious where you noticed this domain in use?
Thanks

**Comment by SeimusS** [comment]
I found it during audit of my network. Specifically during checking of blocking capabilities of my Pihole.

I am using Eds test tool for this:
https://d3ward.github.io/toolz/adblock.html

When running the test without any browser ad-blockers (uBlock Origin is turned off) then I can see lower score and this specific domain is not blocked. When I turn on browser ad-blocker (uBlock Origin is turned on) then I can see higher score and this specific domain is blocked. So it looks like in one of the uBlock origin filters this domains is included.

Also when checking on Hagezi's filter list he has a similar domain with with a **k** instead of **c**
appmetri**k**a.yandex.ru

**Comment by iam-py-test** [comment]
Ok, thanks.
Be aware: That "test" took is highly inaccurate ([not all the servers it tests are even ads/trackers](https://github.com/d3ward/toolz/issues/31))

**Comment by SeimusS** [comment]
I am aware of it. It tests I would say the "most causal actors" or well known "spy domains" that looks like its aim. This is fine if you keep that in mind - and its only for confirmation, when I am doing on Pihole specific per group filtering so I verify I didn't by mistake permit something from that "most casual actors".

Regards,
S.
