### ISSUE TITLE
Gamepass domain

### ISSUE THREAD

**Issue by rkolja76** [hagezi/dns-blocklists#1785]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Ultimate

### Which domain(s) should be unblocked?

catalog.gamepass.com

### Why should the domain(s) be unblocked?

xbox app with gamepass is not usable. No content will be shown.

**Comment by hagezi** [comment]
Fixed, sorry ...
