### ISSUE TITLE
Controld contains Hagezi's DNS - TIF

### ISSUE THREAD

**Issue by iamaugustinthomas** [hagezi/dns-blocklists#1788]
Controls contains : Hagezi's DNS - TIF
Does it block ads and trackers.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists#tif

TIF is an blocklist for blocking malware, cryptojacking, scam, spam and phishing. Blocks domains known to spread malware, launch phishing attacks and host command-and-control servers
