### ISSUE TITLE
DNS Service - ControlD

### ISSUE THREAD

**Issue by chr-lei** [hagezi/dns-blocklists#179]
Hello!

I asked the folks at ControlD to add some of your more popular lists to their service. They are now added and available for both paid and free users. The free DNS URLs are below. Just letting you know in case you wanted to add ControlD to the README.md list of online services using your list. Thank you for providing these blocklists!

Normal DoH: https://freedns.controld.com/x-hagezi-normal
Normal DoT: x-hagezi-normal.freedns.controld.com

Pro DoH: https://freedns.controld.com/x-hagezi-pro
Pro DoT: x-hagezi-pro.freedns.controld.com

Pro+ DoH: https://freedns.controld.com/x-hagezi-proplus
Pro+ DoT: x-hagezi-proplus.freedns.controld.com

Cheers,
Chris

**Comment by yegors** [comment]
There are Ipv4 and Ipv6 resolvers also available: https://kb.controld.com/en/3rd-party-filters

**Comment by hagezi** [comment]
Thanks @chr-lei @yegors 
DoH/DoT added: https://github.com/hagezi/dns-blocklists#controld

The online DNS section is to be revised, then I will also add the IP resolvers.

**Comment by yegors** [comment]
Thanks :)
