### ISSUE TITLE
`www.iobit.com` false positive

### ISSUE THREAD

**Issue by ghost** [hagezi/dns-blocklists#1794]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

www.iobit.com

### Why should the domain(s) be unblocked?

Website of a fairly well-known software developer company IObit

**Comment by iam-py-test** [comment]
With all due respect, IOBit is legitimately blocked:
- they have been caught stealing the intellectual property of other companies and selling it as part of their products<sup>[[1]](https://forums.malwarebytes.com/topic/29681-iobit-steals-malwarebytes-intellectual-property/)</sup>
- the IOBit Malware Fighter installer is detected as a PUP by GData and Dr Web<sup>[[2]](https://www.virustotal.com/gui/file/3409d450cf61270c8a43608fa7e98182aeed7a970741a659a9080dd772468c81/detection)</sup>
- their "Malware fighter" installed four other PUPs, three of which without my consent (two via these deceptive checkboxes, the third was installed without any notice)<sup>[[3]](https://tria.ge/231105-nq2lcsee2v/behavioral1)</sup>:
![image](https://github.com/hagezi/dns-blocklists/assets/84232764/8f3bc2c1-f3bc-4eeb-9e2e-5b08c49efed0)
- iTop is detected as a PUP by DrWeb<sup>[[4]](https://www.virustotal.com/gui/file/514fdd985236aa75a63b8240ec16d1d20aae3bfaef68e573f44af3347160043c/detection)[[5]](https://www.virustotal.com/gui/file/b92e4d3ccd3e62d98c190f03211bdff91916d49cfbc2d4ac6009b5a8e07c6368/detection)[[6]](https://www.virustotal.com/gui/file/55ea17a44d7a9882236b5cda25fa844e62cb1a4fe8d5cdc17b3591f4f98aa802/detection)[[7]](https://www.virustotal.com/gui/file/e6b2acd0738623318f2a5a0af0318b069623fc3455339643da45b67a148c7c96/detection)</sup>
- IOBit sells a "driver updater". Third-party driver updaters are snake oil
- Like IOBit Malware Fighter, it installs the iTop PUPs<sup>[[7]](https://tria.ge/231105-n83alsef7s/behavioral1)</sup>. 
![image](https://github.com/hagezi/dns-blocklists/assets/84232764/2493b70e-bab6-4273-902b-c2035f444f42)
- At least this one it asks for consent before installing it
![image](https://github.com/hagezi/dns-blocklists/assets/84232764/a14366c0-bff9-4746-9a44-5c7a0fac5899)
- My VM crashed before I could finish installing IOBit. It is unclear if IOBit caused the crash
- IOBit System Care is the worst: complete snake oil
- Firstly, like all of IOBit's software, it installs iTop<sup>[[8]](https://tria.ge/231105-pchrrsgf42/behavioral1)</sup>
![image](https://github.com/hagezi/dns-blocklists/assets/84232764/b2962a9f-3190-41d7-a0b0-619ebd5216b8)
- IOBit System Care identifies fake problems
![image](https://github.com/hagezi/dns-blocklists/assets/84232764/bcadb49a-fc1b-4bf6-a82e-95a22b97ebcd)
![image](https://github.com/hagezi/dns-blocklists/assets/84232764/aab7bb2d-ebc5-4f0e-9706-a08cde869967)
- I am not the only person who has raised these concerns: [Don't trust PC Optimizers](https://yewtu.be/watch?v=bIpYJoE7CxA)

Thank you.

**Comment by hagezi** [comment]
Thank you for the detailed information @iam-py-test
