### ISSUE TITLE
Australia Post

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#180]
I keep getting an error in the Australia Post tracking app on Android. The error I get is `Connection issues, try again later. (Error 500)`

I checked AdGuard Home and your list I use seems to be blocking `ssl.o.auspost.com.au` but I couldn't find out why.

Hoping you can look into it as it might be a false positive?

**Comment by hagezi** [comment]
Thank you, it will be removed during the current update. I'll check what the source is later.

**Comment by gothic-bum** [comment]
`ssl.o.auspost.com.au` is an alias for the CNAME `o.auspost.com.au.ssl.d2.sc.omtrdc.net` which is a disguised tracker.

**Comment by hagezi** [comment]
Thanks @gothic-bum, yes, blocking `*.sc.omtrdc.com` breaks some things.

Sources: @AdguardTeam (CNAME-Trackers/Spyware Filter) @bongochong @hectorm @notracking @stevenblack @uniartisan

whitelisted: `ssl.o.auspost.com.au` and `o.auspost.com.au.ssl.d2.sc.omtrdc.net`

**Comment by uniartisan** [comment]
> ssl.o.auspost.com.au

I found that `ssl.o.auspost.com.au` is blocked by uniartisan's privacy list.
This phenomenon is because the upstream privacy list contains such rules. I will push a patch and add a whitelist to my repository, but it is still recommended that affected users directly report problems to the upstream list.

**Comment by bongochong** [comment]
As this application looks to be fairly useful for Aussies, I'm reminding myself to explore this and consider whitelisting these domains, if they aren't used in too many other user tracking contexts. Thank you @hagezi for the heads up. Always appreciated.

**Comment by hagezi** [comment]
@gyCfjSnO fixed.

**Comment by notracking** [comment]
Fixed, thanks!

**Comment by bongochong** [comment]
Whitelisted on this end too. Doesn't seem to be involved in anything outside of Australia Post mobile applications.
