### ISSUE TITLE
community.norton.com

### ISSUE THREAD

**Issue by Slipi089** [hagezi/dns-blocklists#1800]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

DoH/VPN/TOR/Proxy Bypass

### Which domain(s) should be unblocked?

community.norton.com

### Why should the domain(s) be unblocked?

Community forum this has nothing directly to do with vpn or similar.

**Comment by hagezi** [comment]
norton.com is blocked because you can bypass your DNS with Norton VPN.

**Comment by Slipi089** [comment]
I can understand, but norton also offers other services than just vpn and therefore all services are blocked. The family service is also useful. And has nothing to do with vpn. So I think blocking the whole norton.com is too much. Don't you know which subdomain is used for vpn?

**Comment by hagezi** [comment]
No, I don't know which subdomains are used. I'll try to find out.

**Comment by Slipi089** [comment]
Thank you
