### ISSUE TITLE
atsholz.com fake shop

### ISSUE THREAD

**Issue by SIRSteiner** [hagezi/dns-blocklists#1803]
### Which domain(s) should be blocked?

atsholz.com

### Why should these domain(s) be blocked?

This is a fake shop like expressholz.com

**Comment by iam-py-test** [comment]
Would you mind providing more information?
Thank you.

**Comment by SIRSteiner** [comment]
You can find more informations about this fake shop at
https://www.trustedshops.de/fake-shops/
https://www.verbraucherzentrale.de/fakeshopfinder-71560

At https://atsholz.com/datenschutz/ you will find the mail address info@expressholz.com wich domain is already blacklisted.

**Comment by iam-py-test** [comment]
Thanks
