### ISSUE TITLE
Add "SS" website mirror

### ISSUE THREAD

**Issue by ymhcanada** [hagezi/dns-blocklists#1804]
### Which domain(s) should be blocked?

sanctionedsuicide[.]site

### Why should these domain(s) be blocked?

This is a follow-up request re #1592. 

Please refer to the edit history of the first post within that issue: https://github.com/hagezi/dns-blocklists/issues/1592#issue-1903531651

Thank you!

![image](https://github.com/hagezi/dns-blocklists/assets/110322955/b5a37e39-328e-4041-8bba-1e692546494d)

**Comment by iam-py-test** [comment]
Also onion mirror: `suicidabvrputryeg3mxdwwtwnv3eqj2koztuaiko5zn5rzodtencnad.onion`
Thanks

**Comment by iam-py-test** [comment]
I have sent an abuse report to CloudFlare and told them to share it with the hosting provider (and site owner).
