### ISSUE TITLE
lg webom blocklist false positive 

### ISSUE THREAD

**Issue by candybars2021** [hagezi/dns-blocklists#1807]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Native Tracker

### Which domain(s) should be unblocked?

native tracker lg web oś native blocker, includes a domains, that when trying to access the LG appstore, does not allow it, showing "not connected to network". I also run Pro++, which partly includes this native tracker, the problem is not there but only in the full native blocker for lg-web os

### Why should the domain(s) be unblocked?

eic.service.lgtvcommon.com

**Comment by hagezi** [comment]
![image](https://github.com/hagezi/dns-blocklists/assets/104343908/53786e3e-79bc-4638-b7b7-6c43a888f174)

The domain is on all lists, can you please check again which domain is causing the problem?

**Comment by hagezi** [comment]
@markangus2b Can you provide assistance here and test it? Thanks!

**Comment by markangus2b** [comment]
> Mark @markangus2b, Can you provide assistance here and test it? Thanks!

I quickly tested it this morning and didn't have any problems accessing the LG store app or downloading/updating content.

I will play around with it more this afternoon.

**Comment by markangus2b** [comment]
After looking into it more, it appears I have no request for `eic.service.lgtvcommon.com` in my NextDNS logs. I have a DNAT rule redirecting all port 53 DNS traffic to the router, along with blocking ports 853 and 8853 (DoT) so there shouldn't be any leakage.

Maybe it's model or region specific?

**Comment by hagezi** [comment]
@markangus2b Thanks for the support, it may be region or model dependent. Do any of the following domains appear in your log?
```
kic.service.lgtvcommon.com
ruc.service.lgtvcommon.com
```
@candybars2021 Have you been able to check again?

**Comment by markangus2b** [comment]
Both are not in my logs, the closest domain I have to any of these is `aic.service.lgtvcommon.com`. When I block it my guide data doesn't load for my local channels. I presume any `*.service.lgtvcommon.com` domains are required for the same function, just different regions.

**Comment by hagezi** [comment]
Many thanks @markangus2b for the clarification and help.

**Comment by hagezi** [comment]
Fixed on next update.
