### ISSUE TITLE
analytics.google.com

### ISSUE THREAD

**Issue by rcsaquino** [hagezi/dns-blocklists#1809]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### Other

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO, Multi PRO++

### Which domain(s) should be unblocked?

analytics.google.com

### Why should the domain(s) be unblocked?

It's not used as a tracker domain. [Here's a similar issue created in AdGuard DNS Filter](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/724)

**Comment by hagezi** [comment]
This is not correct, I find calls in DNS logs without accessing the Google Analytics page, sometimes even with subdomains, e.g. `region1.analytics.google.com`

It remains blocked in my lists.

**Comment by rcsaquino** [comment]
> This is not correct, I find calls in DNS logs without accessing the Google Analytics page, sometimes even with subdomains, e.g. `region1.analytics.google.com`
> 
> It remains blocked in my lists.

fair enough. I'll just whitelist it on my end. Thanks!
