### ISSUE TITLE
BlockListProject Lists for TIF

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#181]
I did not see these in your used or known sources: https://github.com/blocklistproject/Lists#details

Note: I tried using their lists for ads and trackers and they were way too aggressive with no allowlisting. However, I would think that would be great when it comes to security threats! All that to say: You may want to vet these more thoroughly.

I'm also getting some errors when testing a few links, so there's probably some dead domains (which your script removes anyway).

1. Abuse: https://blocklistproject.github.io/Lists/adguard/abuse-ags.txt
2. Fraud: https://blocklistproject.github.io/Lists/adguard/fraud-ags.txt
3. Malware: https://blocklistproject.github.io/Lists/adguard/malware-ags.txt
4. Phishing: https://blocklistproject.github.io/Lists/adguard/phishing-ags.txt
5. Ransomeware: https://blocklistproject.github.io/Lists/adguard/ransomware-ags.txt
6. Redirects (possibly opt out of this one; may be too aggressive): https://blocklistproject.github.io/Lists/adguard/redirect-ags.txt
7. Scam: https://blocklistproject.github.io/Lists/adguard/scam-ags.txt

**Comment by hagezi** [comment]
I had looked at the lists at the time and had not used them due to any amount of false positives and dead domains.

I will have another look at it.

**Comment by yokoffing** [comment]
> false positives and dead domains.

I hear you. No biggie if you don't. We can at least add them to "known sources".

**Comment by hagezi** [comment]
I'll take another look at them, maybe they'll provide some added value.

**Comment by hagezi** [comment]
@yokoffing Result after a quick check of the lists without the redirect list via my Buld system: 

`814903 unique domains` were checked.

After whitelisting, removing known dead domains and removing domains that are already on the TIF list. `616762 domains` remain for further checking for possible dead domains.

That would be a lot of domains that are "missing", so I assume there are a lot of dead domains in there. With all the sources I use for the TIF, I can't imagine that many are missing.

That would make the TIF and Ultimate list "explode".

**Comment by yokoffing** [comment]
That's fair.

Are there any systems/scripts that check for dead domains? Like, ping the domains on the list and see if there's a response. If not, they're considered dead and removed from the blocklist?

**Comment by hagezi** [comment]
Yes, I check them against an uncensored DNS, if the result is NXDOMAIN then they are considered dead. With 600000+ domains this runs for a few days.
I check all domains from all sources once a month, that's about 6,500,000 domains, that takes about 10 days.

**Comment by yokoffing** [comment]
> With 600000+ domains this runs for a few days.

> I check all domains from all sources once a month, that's about 6,500,000 domains, that takes about 10 days.

😨 😨 😨

**Comment by hagezi** [comment]
The monthly check is currently running, but it will take time to complete. After that I check the 600,000 ...

![grafik](https://user-images.githubusercontent.com/104343908/211653997-a7bcb802-dab1-4f1e-872b-3b5f3c23868b.png)

**Comment by hagezi** [comment]
@yokoffing 
The result of the check for dead domains: `616762/616762 DOMAINS | 310155 DEAD | 306607 OK`

Now I have to see what I do with it, this inflates the tif and ultimate list properly. I have to check again more precisely what it is actually about the 300,000 missing domains.

**Comment by hagezi** [comment]
@yokoffing 

Top 100 FLD:
<details>

```
   9244 000webhostapp.com
   6306 blogspot.com
   3010 2o7.net
   2206 cz.cc
   2176 duckdns.org
   1794 comcast.net
   1548 ono.com
   1179 tpnet.pl
   1107 wordpress.com
    833 usa.cc
    627 weebly.com
    576 narod.ru
    572 ourtoolbar.com
    566 godaddysites.com
    512 yi.org
    493 wixsite.com
    448 charter.com
    418 cloudfront.net
    405 inetia.pl
    390 ddns.net
    375 corbina.ru
    355 amazonaws.com
    349 rr.com
    339 netcabo.pt
    305 digikabel.hu
    300 tumblr.com
    298 vtr.net
    291 t-online.hu
    281 hitbox.com
    268 telekom.hu
    253 nut.cc
    248 fastsize.ru
    247 usercash.com
    236 webnode.com
    226 ne.jp
    225 centde.com
    224 comhem.se
    221 webcindario.com
    220 invitel.hu
    206 bezeqint.net
    204 meegmfio.in
    203 hispeed.ch
    201 tripod.com
    186 notentop.com
    186 beget.tech
    184 xorg.pl
    183 at.ua
    177 telecable.es
    176 broadband.hu
    174 xt.pl
    171 free.fr
    170 gb.net
    166 savetubevideo.com
    165 swbell.net
    162 msdwnld.com
    161 us.com
    161 myradiotoolbar.com
    157 ac.id
    149 cjt1.net
    148 sapo.pt
    145 publicvm.com
    145 igg.biz
    144 rima-tde.net
    141 7wkw.com
    140 webs.com
    139 guidegoods.net
    135 levitrawelloch.in
    133 certified-toolbar.com
    130 yolasite.com
    130 tie.cl
    125 016272.com
    124 flu.cc
    122 brandcollections.ru
    119 ltdomains.com
    113 ddns.name
    113 chello.nl
    111 starman.ee
    109 blogspot.ru
    105 musicfrost.com
    104 kjukenhi.in
    102 pacbell.net
    102 24x7help.org
     98 strefa.pl
     95 herokuapp.com
     94 ucgalleries.com
     92 mystoretoolbar.com
     91 hopto.org
     91 dnset.com
     90 fibernet.hu
     88 xsph.ru
     88 netbynet.ru
     85 no-ip.biz
     85 ngrok.io
     82 gov.br
     80 blogspot.in
     77 tre.se
     76 rr.nu
     76 appspot.com
     73 microticket.xyz
     73 16mb.com
```

</details>

Top 100 SLD.FLD:
<details>

```
   1731 112.2o7.net
   1548 user.ono.com
   1278 122.2o7.net
   1169 adsl.tpnet.pl
   1148 underpains.duckdns.org
    628 telesp.net.br
    405 adsl.inetia.pl
    375 broadband.corbina.ru
    346 res.rr.com
    339 cpe.netcabo.pt
    307 fl.comcast.net
    304 pool.digikabel.hu
    298 cm.vtr.net
    288 pool.t-online.hu
    268 pool.telekom.hu
    243 cableonline.com.mx
    224 bredband.comhem.se
    221 s3-website-us-west-2.amazonaws.com
    220 pool.invitel.hu
    203 dclient.hispeed.ch
    199 bigpond.net.au
    194 ca.comcast.net
    177 bookonline.com.cn
    176 catv.broadband.hu
    169 iam.net.ma
    156 red.bezeqint.net
    143 staticip.rima-tde.net
    141 url.7wkw.com
    125 url.016272.com
    122 wa.comcast.net
    122 adsl.tie.cl
    119 reverse.ltdomains.com
    119 ga.comcast.net
    119 brands.brandcollections.ru
    114 tx.comcast.net
    111 watchdogdns.duckdns.org
    111 cable.starman.ee
    106 threembb.co.uk
    105 pa.comcast.net
    103 zzz.com.ua
    100 il.comcast.net
     99 three.co.uk
     98 ma.comcast.net
     91 mi.comcast.net
     88 bb.netbynet.ru
     87 epm.net.co
     85 com.sapo.pt
     82 blogspot.co.uk
     77 bredband.tre.se
     75 tn.comcast.net
     75 home.ne.jp
     70 ca.charter.com
     67 homepage.t-online.de
     66 url.tudown.com
     64 stats.esomniture.com
     64 maherstcottage.com.au
     64 dsl.telepac.pt
     63 rev.stofanet.dk
     63 netspace.net.au
     63 gekub.yi.org
     61 nosu.yi.org
     58 tn.charter.com
     58 madpendesign.com.au
     58 co.comcast.net
     56 us.intellitxt.com
     55 ga.charter.com
     54 qufewec.yi.org
     53 mesh.ad.jp
     53 kl.com.ua
     52 vs.speednames.com
     52 highway.telekom.at
     52 cust.tele2.se
     51 sc.omtrdc.net
     50 72.1dial.com
     49 goqavat.yi.org
     49 cp.regruhosting.ru
     48 pool.hdsnet.hu
     47 sc.charter.com
     47 mo.charter.com
     47 gumohib.yi.org
     47 cablep.bezeqint.net
     46 dyn.centurytel.net
     45 pltn13.pacbell.net
     45 kefifi.yi.org
     45 client.mchsi.com
     44 md.comcast.net
     44 inter.net.il
     43 monradsl.monornet.hu
     42 paperswriting.publicvm.com
     42 or.comcast.net
     42 in.comcast.net
     42 hpg.com.br
     41 va.comcast.net
     41 hop.clickbank.net
     40 s3.amazonaws.com
     39 net.t-com.hr
     38 plesk05.zap-webspace.com
     38 nj.comcast.net
     38 hinet-ip.hinet.net
     38 fgppchg.fgpp.com
```

</details>

There are some FLDs on it like 2o7.net and omtrdc.net which in my opinion have no place on TIF lists. The list definitely needs further cleanup. I don't know if I will do that, I have to check it again. This looks like a lot of work. This looks partly wildly thrown together.

**Comment by hagezi** [comment]
@yokoffing 
One thing I forgot to mention, out of the `814903 unique domains`, `11,456 domains` were marked as false positives for a TIF list and removed ...

**Comment by hagezi** [comment]
Top 100 FLDs after "cleanup":
<details>

```
   5686 000webhostapp.com
   3722 blogspot.com
   2203 cz.cc
   1794 comcast.net
   1548 ono.com
   1181 duckdns.org
   1179 tpnet.pl
    722 usa.cc
    599 wordpress.com
    571 ourtoolbar.com
    499 godaddysites.com
    480 yi.org
    448 charter.com
    418 cloudfront.net
    413 weebly.com
    405 inetia.pl
    387 ddns.net
    375 corbina.ru
    349 rr.com
    339 netcabo.pt
    305 narod.ru
    305 digikabel.hu
    298 vtr.net
    290 t-online.hu
    281 hitbox.com
    273 wixsite.com
    268 telekom.hu
    248 fastsize.ru
    247 usercash.com
    232 amazonaws.com
    224 comhem.se
    223 centde.com
    220 invitel.hu
    218 nut.cc
    217 ne.jp
    206 bezeqint.net
    204 meegmfio.in
    203 hispeed.ch
    201 tumblr.com
    186 notentop.com
    177 telecable.es
    176 broadband.hu
    174 webcindario.com
    168 free.fr
    165 swbell.net
    161 myradiotoolbar.com
    157 webnode.com
    151 beget.tech
    146 sapo.pt
    144 rima-tde.net
    139 guidegoods.net
    138 at.ua
    135 levitrawelloch.in
    130 tie.cl
    124 tripod.com
    120 savetubevideo.com
    120 ac.id
    119 ltdomains.com
    113 ddns.name
    113 chello.nl
    112 igg.biz
    111 starman.ee
    111 gb.net
    104 kjukenhi.in
    102 pacbell.net
     96 strefa.pl
     93 webs.com
     92 mystoretoolbar.com
     91 hopto.org
     91 dnset.com
     90 fibernet.hu
     89 us.com
     88 netbynet.ru
     85 no-ip.biz
     84 flu.cc
     81 yolasite.com
     77 tre.se
     76 7wkw.com
     74 rr.nu
     71 myforumtoolbar.com
     68 ngrok.io
     67 publicvm.com
     67 certified-toolbar.com
     65 telepac.pt
     65 016272.com
     64 xsph.ru
     64 multimo.pl
     64 downyouxi.com
     63 stofanet.dk
     63 ojolink.fr
     63 byinter.net
     62 appspot.com
     61 gcion.com
     60 go.th
     59 jlxnesex.in
     59 herokuapp.com
     59 16mb.com
     56 intellitxt.com
     55 hdsnet.hu
     55 blogspot.ru

```
</details>

**Comment by yokoffing** [comment]
> `310155 DEAD`

Half of the list is dead. Good gracious.

> If I compress the `303172 domains` to AdBlock format, `193859 rules` remain:

Do we want to risk adding them since so many rules were garbage / not security risks?

**Comment by hagezi** [comment]
> Do we want to risk adding them since so many rules were garbage / not security risks?

I wouldn't like to use it as a source, I would have to put more work into it and it probably doesn't add too much value.

**Comment by yokoffing** [comment]
> I wouldn't like to use it as a source, I would have to put more work into it and it probably doesn't add too much value.

That's my thoughts as well. At least we now have this thread as a reference.

**Comment by hagezi** [comment]
Yes, I agree with that.

**Comment by jarelllama** [comment]
@hagezi for future reference, I've generated updated reports for the various blocklists mentioned: https://github.com/jarelllama/Blocklist-Checker/issues?q=is%3Aissue+label%3A%22report+generated%22+%22The+Block+List+Project%22
