### ISSUE TITLE
Lock the entire domain, not its sub domains

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#1810]
### Which domain(s) should be blocked?

googleadservices.com
googletagmanager.com
urbanairship.com

### Why should these domain(s) be blocked?

Lock the entire domain, not its sub domains (third level). 

Example
In Pro AdBlock list:
afs.googleadservices.com
pagead2.googleadservices.com
partner.googleadservices.com
partner46.googleadservices.com
partnerssl.googleadservices.com
privacysandbox.googleadservices.com
Why not block the entire domain at once, rather than list the third level? Like Ultimate list.

Same with the other two.

**Comment by hagezi** [comment]
`googleadservices.com` is [referral domain](https://github.com/hagezi/dns-blocklists#referral), not used for ads, only blocked in Ultimate.

`googletagmanager.com` breaks some sites and video playback, only blocked in aggressive lists (Pro++ and Ultimate)

some subdomains of `urbanairship.com` breaks some apps, e.g.
- push notificaties app fotmob 
- add boarding pass to apple wallet
- The Southwest Airlines app on iPhones (and other apps) use this service to generate Apple Wallet entries for plane tickets or other wallet-like items.
- push notifications settings screen inside the ZEIT ONLINE mobile app, which is a german newspaper
- ...
