### ISSUE TITLE
Website not loading due to “disable adblocker to continue”

### ISSUE THREAD

**Issue by cblinq** [hagezi/dns-blocklists#1813]
https://gamerant.com/

**Comment by hagezi** [comment]
@cblinq can't reproduce using ultimate.

**Comment by cblinq** [comment]
Hmm, I’m seeing these blocked in my logs (but I’m using several other lists) my.getadmiral.com

live.primis.tech

mbid.marfeelrev.com

cdnral.com

d15kdpgjg3unno.cloudfront.net

seg.ad.gt

c.amazon-adsystem.com

succeedscene.com

cdn.adsninja.ca

tru.am

imasdk.googleapis.com

www.googletagservices.com

a.ad.gt

cdn.optmn.cloud

launchpad-wrapper.privacymanager.io

pagead2.googlesyndication.com

delicatecascade.com

www.google-analytics.com

With multi normal

**Comment by hagezi** [comment]
It is not caused by my lists. But my guess is that you need to allow succeedscene.com.
