### ISSUE TITLE
No playback due to "Ad Block Detected".

### ISSUE THREAD

**Issue by rcsaquino** [hagezi/dns-blocklists#1814]
Can't play any videos from [iwanttfc](https://www.iwanttfc.com/ ) because of this error. Issue is present from Light - Ultimate. Currenly using ControlD Free DNS so no logs, sorry.

**Comment by hagezi** [comment]
You need a subscription to test it, which I don't have. However, I can play the video preview with Ultimate.

Do you possibly still have a browser content blocker active that is causing this?

Otherwise we need someone who can test this and has access to logs.

**Comment by rcsaquino** [comment]
I made a new profile in my NextDNS to further test this and doing so, I found out that putting `*.googlesyndication.com` in the allowlist fixed the issue.

**Comment by rcsaquino** [comment]
This is shown on my console when `pagead2.googlesyndication.com` is not in allowlist.
![image](https://github.com/hagezi/dns-blocklists/assets/64822775/7643a44e-66cc-45f0-87a2-45c27e8c2495)

**Comment by hagezi** [comment]
The domain will not be unblocked in my lists. If this is the problem, you won't find another list that works.

You can also try a content blocker. Maybe the script for detection will then be blocked.

**Comment by rcsaquino** [comment]
> You can also try a content blocker. Maybe the script for detection will then be blocked.

Problem is I'm running the Light version on my home router so I cant do this.

**Comment by hagezi** [comment]
As I said, this is an elementary ad domain that is also blocked in every other list. Unblocking leads to ads being displayed elsewhere.

This is something for the personal allowlist.

**Comment by rcsaquino** [comment]
Okay. Thank you!

**Comment by hagezi** [comment]
@sjhgvr This might be something for your FAQ.
