### ISSUE TITLE
aurorastore.pro

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#1817]
### Which domain(s) should be blocked?

aurorastore.pro

### Why should these domain(s) be blocked?

This is not the official site Aurora Store and is probably distributing a virus version.
The official site of the Aurora Store - https://auroraoss.com
The official repository of the Aurora Store - https://gitlab.com/AuroraOSS/AuroraStore

**Comment by iam-py-test** [comment]
FYI, the APK on that website is identical to version 3.2.1 from the legitimate website.
Thanks

**Comment by iam-py-test** [comment]
I'm aware. I'm not saying the site isn't sketchy, but the app download isn't malware, it's just outdated.
