### ISSUE TITLE
dc.railgun.works is false positive

### ISSUE THREAD

**Issue by salad612** [hagezi/dns-blocklists#1820]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

dc.railgun.works

### Why should the domain(s) be unblocked?

It's a harmless domain, just says "Move along, nothing to see here"

There are other URL in this domain but they just redirect to discord servers: https://dc.railgun.works/electroshack
https://dc.railgun.works/starbreak
https://dc.railgun.works/r6jm5rhorx
https://dc.railgun.works/lostlegacy

So I don't think it's malicious

**Comment by hagezi** [comment]
@bongochong Do you know why this is blocked?

**Comment by hagezi** [comment]
https://rethinkdns.com/search?q=dc.railgun.works

Quite widely blocked, but I can't find a reason why. I will unblock it.

**Comment by bongochong** [comment]
No idea @hagezi and sorry for the considerable delay! Life stuff. Will look into this over the week though, because it is widely blocked as you noted.
