### ISSUE TITLE
Playstation 5 telemetry baked into the console

### ISSUE THREAD

**Issue by damianir750** [hagezi/dns-blocklists#1821]
### Which domain(s) should be blocked?

telemetry-console.api.playstation.com

### Why should these domain(s) be blocked?

I put nextdns on my ps5 and i saw this not getting blocked even if it is 99% telemetry it has telemetry in the name

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/blob/e8e51e83fffdeee49e6cda55b073ae94c6b440c7/whitelist.txt#L3323C25-L3323C25

**Comment by damianir750** [comment]
Im really sorry next time i will check
