### ISSUE TITLE
False Block: different Domains from Securepoint!

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#183]
Hi,

looks like you have a few quite important blocks within your Pro Lists, which shouldn't be blocked:

https://www.spdyn.de is the service:

actually blocked:
spdns.de 
spdns.org
spdns.eu
firewall-gateway.de
firewall-gateway.com
firewall-gateway.net
myfirewall.org
my-firewall.org
my-router.de
my-gateway.de

Shouldn't be blocked.

**Comment by hagezi** [comment]
They come from malware sources, will check and remove them.

**Comment by hagezi** [comment]
Fixed.
