### ISSUE TITLE
Android.Spy.SpinOk (Virus)

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#1831]
### Which domain(s) should be blocked?

s.hisp.in

### Additional links:
d3hdbjtb1686tn.cloudfront.net/gpsdk.html

d3hdbjtb1686tn.cloudfront.net - In actual use, I haven't seen this domain in the logs, but locking can cause breakdowns.

Android.Spy.SpinOk
https://github.com/DoctorWebLtd/malware-iocs/tree/master/Android.Spy.SpinOk

# Do not open links!

**Comment by hagezi** [comment]
Is already blocked in all list versions.

**Comment by hagezi** [comment]
Please check in future whether the domains are already included. Thank you ...
