### ISSUE TITLE
Android.Spy.Lydia (Virus)

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#1832]
### Which domain(s) should be blocked?

httpiamaloneqs.xyz
teuoi.com
biuy.are-eg.com
sahmanl.4dq.com
fusagov.xyz
biguxcse.xyz

### Why should these domain(s) be blocked?

Additional links:
my-edalatsaham.sbs/fa/app.php
sahamt.qpoe.com/app.php
my-edalat-sahamse.ol?lang=fa
viiirubre.store/Dargah
date-manager.com/sham/app.php
dolati.host/%F0%9D%90%9C%E2%80%8C%E2%80%8C/app.php
ydilat.host/%F0%9D%90%9C%E2%80%8C%E2%80%8C/app.php

I think all of the above can be blocked together with domains, not just links

Android.Spy.Lydia
https://github.com/DoctorWebLtd/malware-iocs/tree/master/Android.Spy.Lydia

# Do not open links!

**Comment by hagezi** [comment]
Already included, partially dead domains.

**Comment by hagezi** [comment]
Please check in future whether the domains are already included. Thank you ...
