### ISSUE TITLE
Android.Joker (Virus)

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#1833]
### Which domain(s) should be blocked?

novasdk.oss-cn-beijing.aliyuncs.com
superkeyboard.oss-ap-southeast-1.aliyuncs.com
happycolor.oss-ap-northeast-1.aliyuncs.com
funcolortoucheffects.oss-ap-southeast-2.aliyuncs.com
new2021keyboard.oss-ap-south-1.aliyuncs.com
cameramx-photovideocamera.oss-cn-wulanchabu.aliyuncs.com
beautypluscamera.oss-ap-northeast-1.aliyuncs.com
colorrollingicon.oss-cn-huhehaote.aliyuncs.com
funneymemeemoji.oss-ap-southeast-5.aliyuncs.com
happytapping.oss-cn-qingdao.aliyuncs.com
allinonemessenger.oss-cn-shenzhen.aliyuncs.com
api.lemonmanga.com
gp.fortunnecat.com
deepkeyboardpro.oss-cn-hongkong.aliyuncs.com
router.cutebubblegame.com
welcome.baltergames.com
ad.mobnv.com

### Why should these domain(s) be blocked?

Android.Joker
https://github.com/DoctorWebLtd/malware-iocs/tree/master/Android.Joker

# Do not open links!

**Comment by hagezi** [comment]
Already included, partly dead domains.

**Comment by hagezi** [comment]
Please check in future whether the domains are already included. Thank you ...
