### ISSUE TITLE
breaks naver pay

### ISSUE THREAD

**Issue by aesof01** [hagezi/dns-blocklists#1838]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

```
img.pay.naver.net.nheos.com
```
### Why should the domain(s) be unblocked?

breaks naver pay, naver pay ui, naver pay address selection menu, naver pay address selection menu ui
`img.pay.naver.net.nheos.com` is a CNAME of `img.pay.naver.net`

**Comment by hagezi** [comment]
Thanks, flagged by Google Safebrowsing, will be removed asap.
