### ISSUE TITLE
schroederdennis.de

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#1840]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

schroederdennis.de

### Why should the domain(s) be unblocked?

because it's just a normal website from a well known Youtuber within germany.

**Comment by hagezi** [comment]
Not blocked in my lists.

**Comment by Fqwe1** [comment]
Blocked by NextDNS Threat Intelligence Feeds, not hagezi blocklists
![Screenshot](https://github.com/hagezi/dns-blocklists/assets/139431054/a7fb3706-fcad-4ff3-98ca-4253ed37185e)

**Comment by iam-py-test** [comment]
Seems to have been listed due to https://urlhaus.abuse.ch/url/2723008/, which has been taken down.
Thanks
