### ISSUE TITLE
Potential domains for tracking 

### ISSUE THREAD

**Issue by amit-bh** [hagezi/dns-blocklists#1843]
### Which domain(s) should be blocked?

telemetry.goodlifefitness.com

Not sure if these 2 should be considered tracking, leave to discretion:
amp.analytics-debugger.com
firebase-settings.crashlytics.com

### Why should these domain(s) be blocked?

Seem to be telemetry domains

**Comment by hagezi** [comment]
@amit-bh already blocked in all list versions.

**Comment by Yuki2718** [comment]
If any of your source lists other than EP blocks `analytics-debugger.com`, looks it's better to exclude https://github.com/easylist/easylist/issues/22031

**Comment by thyngster** [comment]
Hi,

Just to give some context: I used to host a JSON file at amp.analytics-debugger.com/ga4.json. This file doesn’t perform any tracking; it simply serves as a configuration file for AMP pages.

It doesn’t set cookies, it doesn't collect any data, it doesn't get any payloads ( there's no server-side tracking involed at any level ) or do anything else—it’s just a plain JSON file.

So, if still want to prevent this file to be loaded please either fully match https://amp.analytics-debugger.com/ga4.json or at least adjust it to only to cover .*amp\.analytics-debugger\.com.*  so it doesn’t impact my corporate sites.

I fail to understand how domains can be added to the list so readily, without thorough investigation or meaningful discussion. A user with a newly created account submits a domain for consideration—in this case being his first message or issue to the repository—and those domains are subsequently added without sufficient review. This approach is concerning :/

In any case thanks for replying and helping on this.
