### ISSUE TITLE
drivereasy.com

### ISSUE THREAD

**Issue by green1052** [hagezi/dns-blocklists#1844]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

drivereasy.com

### Why should the domain(s) be unblocked?

https://www.drivereasy.com/

**Comment by iam-py-test** [comment]
[Third party driver updaters are snake oil](https://www.malwarebytes.com/blog/news/2015/06/driver-updaters-digital-snake-oil-part-2), and DriverEasy is a third party driver updater. In my opinion, this should not be unblocked.
Thanks

**Comment by hagezi** [comment]
@iam-py-test Yes.
