### ISSUE TITLE
Suggestion: Domains that report bugs should not be blocked, at least in the Light list

### ISSUE THREAD

**Issue by jakecharlie** [hagezi/dns-blocklists#1845]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT

### Which domain(s) should be unblocked?

firebase-settings.crashlytics.com

### Why should the domain(s) be unblocked?

This is a suggestion for Hagezi. I noticed that from the simplest Hagezi's DNS Light to the more advanced Hagezi's DNS Ultimate, all dns lists block the domain "firebase-settings.crashlytics.com", for example.

Which is a different practice from the Adguard Public DNS list, for example, which blocks trackers and ads, but they do not block bug-tracking services that are used to report bugs and crashes to application developers.
Source: 
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1226#issuecomment-1437220784

And there are many users, like me, who would like to block invasive ads and trackers, but still would like to allow bugs to be reported to developers (this is how bugs are fixed many times). I believe that at least the Light version, as today it is the least restricted of all Hagezi lists, could allow bug-tracking services domains.

Like I said, it's just a suggestion. Please think about it. Thank you very much.

**Comment by hagezi** [comment]
I know that blocking errortracking is debatable. I have also had these discussions several times. It's a blessing and a curse.

But as long as error tracking does not comply with data protection regulations and is misused in some apps by transmitting parameters that are not absolutely necessary for troubleshooting and tracking user behaviour, they will remain blocked in my lists. Theoretically, all sorts of things can be transmitted.

The user is free to add these domains to their personal allowlist or to use a blocklist that allows these domains.

**Comment by hagezi** [comment]
@jakecharlie 

I have received several requests on this topic and the resulting discussions have led me to adapt the light and normal versions of the lists as follows:

*Light and Normal does not block error trackers such as Bugsnag, Crashlytics, Firebase, Instabug, Sentry, ... and other app-specific crash trackers. These are only blocked from the Pro version onwards.*

This change will be made with the next update.

**Comment by hagezi** [comment]
Your comments are pretty much the result of the discussions I had with the community. I finally realized that. Of course, there will now be users who have been using Normal and want to have Bugtracker blocked. They will then have to switch to Pro. Even with so many levels, you can't please everyone anyway. But I think the solution is fair.
