### ISSUE TITLE
Whitelist compatible Blocky format

### ISSUE THREAD

**Issue by buroa** [hagezi/dns-blocklists#1858]
Hey there @hagezi 

Great blocklists! Would just like to request a simple feature: can we create compatible Domains / Subdomains formatted whitelists based on what is in these whitelists:

https://github.com/hagezi/dns-blocklists/blob/main/whitelist.txt
https://github.com/hagezi/dns-blocklists/blob/main/whitelist-referral.txt

Many thanks in advance!

**Comment by hagezi** [comment]
The whitelist contains wildcards (asterisks) and is only used to document what is removed and why.

I will not create a list that contains all removed domains and subdomains.

**Comment by buroa** [comment]
> The whitelist contains wildcards (asterisk) and is only used to document what is removed and why.
> 
> I will not create a list that contains all removed domains and subdomains.

Cool. Thanks.

**Comment by hagezi** [comment]
@buroa 

Yes, nothing, that's what I do best ;)

What do you want to do with the list?

The lists are already available in the following formats:

Adguard/Adblock:

https://github.com/hagezi/dns-blocklists/blob/main/adblock/whitelist.txt
https://github.com/hagezi/dns-blocklists/blob/main/adblock/whitelist-referral.txt

RegEx (Pihole):

https://github.com/hagezi/dns-blocklists/blob/main/regex/whitelist-referral-pihole.txt

**Comment by buroa** [comment]
@hagezi I'm trying to get these into a format that blocky can understand. It has a lot of parse errors with the current lists, so I'm just trying to cut that down.

If it's not possible, that's okay. But this is Github, so please be open to discussions instead of giving hard definite lines. It comes off as rude.

**Comment by hagezi** [comment]
The list contains wildcard domains (*) and is used by my build system to remove the corresponding domains from my lists. Due to the wildcards, the list cannot be used if only domains are supported.

If you want to use it, you must first remove all entries with a *.

I am open for discussions. I have only made it clear that I will not convert the list into a pure domain list because the wildcard entries cannot be converted so easily.

**Comment by hagezi** [comment]
@buroa 

Found out that Blocky can process regex lists, see here: https://0xerr0r.github.io/blocky/v0.22/configuration/

Try the Referral Allowlist: https://github.com/hagezi/dns-blocklists/blob/main/regex/whitelist-referral-pihole.txt

If that works, I could also convert the allowlist and make it available.

**Comment by ben-auo** [comment]
For those who find this, note Blocky now supports the wildcard format: https://0xerr0r.github.io/blocky/latest/configuration/

Also, mentions this warning:

```
Regexes use more a lot more memory and are much slower than wildcards, you should use them as a last resort.
```
