### ISSUE TITLE
https://c.webengage.com/ blocked

### ISSUE THREAD

**Issue by iamaugustinthomas** [hagezi/dns-blocklists#1859]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

https://c.webengage.com/

### Why should the domain(s) be unblocked?

otherwise mail links won't open properly

**Comment by iamaugustinthomas** [comment]
I wanted to bring to your attention that I have previously requested assistance with the ongoing issue of my (https://c.webengage.com/) being added to the blocklist. While the matter was successfully resolved on previous occasions, it appears that the issue resurfaces after some time.

I kindly request your prompt attention to address this matter once again and take the necessary steps to ensure a lasting resolution. Your assistance in this regard is greatly appreciated.

Thank you for your understanding and cooperation.

**Comment by iamaugustinthomas** [comment]
issue was with adguard

**Comment by hagezi** [comment]
c.webengage.com is on my referral allowlist and has been removed from my lists.
