### ISSUE TITLE
Blocking non-child-safe search engines

### ISSUE THREAD

**Issue by rhodin** [hagezi/dns-blocklists#1863]
### Which domain(s) should be blocked?

There could be a list for blocking all search engine domains except child-safe ones (see 5 examples of child-safe search engines here: https://en.wikipedia.org/wiki/List_of_search_engines ).

### Why should these domain(s) be blocked?

Even with "Safesearch not supported" blocklist, a couple of clicks disables the safesearch on search engines that do support safesearch. I would like to be able to block inappropriate content strictly, that's the reason for this request.

**Comment by hagezi** [comment]
Hi, thanks for the idea, I'll see what I can do. You are very welcome to contribute to the list.

**Comment by hagezi** [comment]
One of the main problems is that by blocking *.google.com, for example, you are not only blocking the search engine, but it feels like you are blocking half the Internet because this also blocks various services, APIs and other things.

**Comment by hagezi** [comment]
It is therefore more effective to use parental controls such as those in AdGuardDNS:

![image](https://github.com/hagezi/dns-blocklists/assets/104343908/579aed1b-097d-4a33-ae68-662130925f74)

**Comment by rhodin** [comment]
What about using an add-on such as "Enforce Safe Search" instead? Are there some big differences in terms of privacy or security?

**Comment by rhodin** [comment]
> One of the main problems is that by blocking *.google.com, for example, you are not only blocking the search engine, but it feels like you are blocking half the Internet because this also blocks various services, APIs and other things.

Would there be a way to block *.google.com while at the same time whitelisting those APIs and the like?

**Comment by iam-py-test** [comment]
I think the problem is that the APIs are also hosted on google.com, and there is no way to unblock part of Google.com at the DNS level. You might be better off with something like uBlock Origin, or a dedicated parental control program.
Thanks

**Comment by rhodin** [comment]
I understand. By the way, I am currently using Ultimate with 1Hosts Xtra along with all other filters from uBlock Origin. I may be a bit crazy, but it's fun to be a minimalist on the Internet. B-) I also use a Pi-hole DNS, Enforce Safe Search, ClearURLs and Privacy Badger. Couldn't open the website of DNS0 to set it on my Firefox, though; probably need to whitelist it.

**Comment by darkmyregaming** [comment]
You can use something like this on your PiHole to enforce safe-search on supported search engines: https://cloudtechtips.com/linux/ubuntu/force-safesearch-using-pi-hole/396/
This removes the ability to turn safe search off for any device using the PiHole.

**Comment by rhodin** [comment]
Hi, darkmyregaming! Thanks! However, it seems a bit short of what I was looking for. This is because one must configure one search engine at a time. There are several dozens at least. Oh! This just popped an idea: perhaps the list I was talking about in the beginning of this thread could be created, after all, with one or two exceptions including Google, that can could be addressed with the tutorial you just presented me! :-D

**Comment by rhodin** [comment]
The ideal would be a one-step command or script to block all search engines on the Pi-hole, except the child-safe ones, and then if one cannot live with some Google APIs or the like (and perhaps one can, by the way), one click on the Pi-hole settings to disable this search engine alone. (´^-^`)

**Comment by hagezi** [comment]
To avoid the problem that blocking google.com also blocks all subdomains, you would have to use a host list that only contains the domains with subdomains, i.e:

```
0.0.0.0 google.com
0.0.0.0 www.google.com
0.0.0.0 search.google.com
0.0.0.0 google.com
0.0.0.0 www.google.de
...
```

That's a lot of work to find all the domains/subdomains of all search engines for all regions. It's not really worth the effort.
Furthermore, there is always a way around the DNS blocker, even if you use a bypass list that blocks DoH domains and block the use of native DNS port 53 and DoT 853 in the router.
The simplest bypass is to use the IP instead of the domain for DNS-over-HTTPS: `https://8.8.8.8/dns-query` instead of `https://dns.google/dns-query`

And then there are all kinds of proxies, VPNs and ...

The better way is certainly a parental control software, blocking search engines without Safesearch and forcing Safsearch.

**Comment by Dynamic5912** [comment]
You need to either use AGH and use the option to enforce safe search or if using a pihole there's a list that handles redirects to the safe search version of search engines. 

Are you running AGH or pihole?

**Comment by rhodin** [comment]
pihole

**Comment by Dynamic5912** [comment]
> pi-hole

There's various ways to try and enforce safe search on pihole. But I can't account for their reliability.
