### ISSUE TITLE
Services of A1.rs mobile network operator inaccessible 

### ISSUE THREAD

**Issue by Bejoneta** [hagezi/dns-blocklists#1867]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Other

+ yokoffing recommended (non-interfering) setup

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

https://a1.rs/

### Why should the domain(s) be unblocked?

A1 is a legitimate source (https://a1.rs/)... well, as legitimate as a network provider can be; regardless, they're still a necessary evil in terms of accessing the internet. Please consider unblocking them.

**Comment by hagezi** [comment]
@Bejoneta not blocked in my lists

**Comment by Bejoneta** [comment]
I can't access their services through the dedicated app, unless I turn off the private dns or switch to mobile data instead :(
