### ISSUE TITLE
Unblock Google Drive URL

### ISSUE THREAD

**Issue by realgauravmehta** [hagezi/dns-blocklists#1871]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

doc-10-3c-docs.googleusercontent.com

### Why should the domain(s) be unblocked?

This is used to download files from Google Drive.

**Comment by hagezi** [comment]
Via URLhaus malware list, will be removed.
