### ISSUE TITLE
adult , porn & malware list

### ISSUE THREAD

**Issue by alsyundawy** [hagezi/dns-blocklists#1872]
### Which domain(s) should be blocked?

https://github.com/ShadowWhisperer/BlockLists/blob/master/RAW/Adult
https://github.com/ShadowWhisperer/BlockLists/blob/master/RAW/Malware
https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-rpz.conf
https://malware-filter.gitlab.io/malware-filter/vn-badsite-filter-rpz.conf
https://malware-filter.gitlab.io/malware-filter/pup-filter-rpz.conf
https://malware-filter.gitlab.io/malware-filter/phishing-filter-rpz.conf
https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/malware.list[
https://github.com/StevenBlack/hosts/blob/master/alternates/porn/hosts
https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/porn.txt
https://raw.githubusercontent.com/blocklistproject/Lists/master/porn.txt
https://raw.githubusercontent.com/Bon-Appetit/porn-domains/master/bl-custom.txt
https://raw.githubusercontent.com/brijrajparmar27/host-sources/master/Porn/hosts
https://raw.githubusercontent.com/Castle67/CastleAds/main/extensions/porn/sinfonietta/hosts
https://raw.githubusercontent.com/Castle67/CastleAds/main/NakedSite
https://raw.githubusercontent.com/EdmondN1/MyPiHoleLists/main/PiPornList.txt
https://raw.githubusercontent.com/elbkr/bad-websites/main/separated/nsfw.json
https://raw.githubusercontent.com/emiliodallatorre/adult-hosts-list/main/list.txt
https://raw.githubusercontent.com/go2engineering/pihole-blocklists/main/pihole_blocklist_adult.list
https://raw.githubusercontent.com/LittleCordines/pfsense-hosts-file/master/PornBlocklists
https://raw.githubusercontent.com/moose84/list/master/listaPI.txt
https://raw.githubusercontent.com/mullvad/dns-blocklists/main/lists/relay/adult/pornography-hosts
https://raw.githubusercontent.com/nizekun/adguardhome-blocklist/main/alexsannikov-pornlist.txt
https://raw.githubusercontent.com/nizekun/adguardhome-blocklist/main/chadmayfieldporn_all1.txt
https://raw.githubusercontent.com/nizekun/adguardhome-blocklist/main/chadmayfieldporn_all2.txt
https://raw.githubusercontent.com/nizekun/adguardhome-blocklist/main/chadmayfieldporn_all3.txt
https://raw.githubusercontent.com/nizekun/adguardhome-blocklist/main/chadmayfieldtop1mlist.txt
https://raw.githubusercontent.com/nizekun/adguardhome-blocklist/main/mhhakimpornlist.txt
https://raw.githubusercontent.com/nizekun/adguardhome-blocklist/main/porn-list.txt
https://raw.githubusercontent.com/pq6p41fgt6k/potential-octo-parakeet/master/porn.txt
https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
https://raw.githubusercontent.com/sjhgvr/oisd/main/abp_nsfw.txt
https://raw.githubusercontent.com/tiuxo/hosts/master/porn
https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-porn
https://github.com/mrvivacious/PorNo-_Porn_Blocker/tree/master/lists/Urls

### Why should these domain(s) be blocked?

For Better Internet

**Comment by hagezi** [comment]
Hi @alsyundawy,

I don't offer an adult blocklist, I can recommend the [OISD NSFW}(https://oisd.nl/) from @sjhgvr. Maybe there are also some sources here that Stephan can include if they are missing.

The listed malware sources are already in use.

Gerd
