### ISSUE TITLE
Computerbase - Ads coming up since yesterday

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#1881]
### Which domain(s) should be blocked?

Hi, 
actually I don't know how they're doing it. But at https://www.computerbase.de you can see Ads now (from today on). Since yesterday everything was fine while using HaGeZi Pro++ Blocklist

Hope this category is ok for reporting?

### Why should these domain(s) be blocked?

Annoying Ads at their website

**Comment by hagezi** [comment]
The ads are loaded from the main domain itself, this cannot be blocked with DNS without blocking half the page, you need a browser content blocker like uBlock.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/aa0f0030-73b9-4884-ae87-442ab8088214)

**Comment by hagezi** [comment]
without uBlock:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/c9ba6318-855c-495e-af2b-86c0a04094e4)

With uBlock:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/48c7cdee-ce9c-4277-89ce-ae31f1bc015e)
