### ISSUE TITLE
Caser.es

### ISSUE THREAD

**Issue by molgar** [hagezi/dns-blocklists#1882]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT, Multi NORMAL

### Which domain(s) should be unblocked?

caser.es should be as it is the website of a popular insurer in Spain, providing health, home, car insurance.
Browsing the caser.es website also required the whitelisting of kampyle.com and of tiqcdn.com, otherwise website functionality was broken.

### Why should the domain(s) be unblocked?

Caser.es is a legitimate website providing insurer services in Spain

**Comment by hagezi** [comment]
Hi @molgar, `caser.es` ist not blocked in my lists, Have I overlooked something?

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/916566cb-d672-40c6-9254-92787bd92db8)

**Comment by molgar** [comment]
Sorry. What I see blocked is l.cliente.caser.es on Multi Pro++ and smetrics.caser.es on Normal, as well as the other domains in the report text field.

**Comment by hagezi** [comment]
@molgar 

`l.cliente.caser.e`s is blocked by CNAME `rts.ccmp.eu ` 
`smetrics.caser.es` are analytics

Which functions are restricted as a result?

**Comment by molgar** [comment]
The end result is that the incident report function is broken, with missing font, javascript elements not loading, and stalling during the upload of files.

**Comment by hagezi** [comment]
OK, and which blocked domains exactly lead to this behaviour? I think smetrics should not cause any problems. You also listed other domains: `kampyle.com` and `tiqcdn.com`

Please list the exact subdomains that are causing this behaviour.

Do you have a link where I can test this?

**Comment by molgar** [comment]
I did some more testing, and it seems blocking tiqcdn.com is what prevents the funcionality javascript from working.

One way to test is to load https://www.caser.es/seguros-autonomos. Then click the Contactar link on the top right, and then click "Te llamamos gratis". If tiqcdn.com is blocked, nothing will happen.

**Comment by molgar** [comment]
Nevermind, upon further inspecting it was not blocked by Hazegi, but by NextDNS' default list
