### ISSUE TITLE
mobile spyware

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#1883]
### Which domain(s) should be blocked?

luis-dubuque.in
haroldramsey.icu
danny-cartwright.firm.in
conner-margie.com
junius-cassin.com
junius-cassin.com
orin-weimann.com
jack-keys.site
elizabeth-steiner.tech
orin-weimann.com

### Why should these domain(s) be blocked?

https://github.com/Cisco-Talos/IOCs/blob/main/2023/10/arid-viper-mobile-spyware.txt

**Comment by hagezi** [comment]
All Domains are dead ...
