### ISSUE TITLE
allow 2ip.me

### ISSUE THREAD

**Issue by robin98** [hagezi/dns-blocklists#1886]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

2ip.me

### Why should the domain(s) be unblocked?

this is an online source for checking web services, IP lists  etc.

**Comment by hagezi** [comment]
@robin98 Can't find `2ip.me` in my lists ...
