### ISSUE TITLE
s.deepl.com is blocked - translation not working

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#189]
Hi,

when blocking s.deepl.com - website translation is broken.

**Comment by hagezi** [comment]
It works for me with `s.deepl.com` blocked. 

![grafik](https://user-images.githubusercontent.com/104343908/211823955-07a28cea-3649-44f5-91ad-eb52f19a8ee5.png)

![grafik](https://user-images.githubusercontent.com/104343908/211824097-3d1a3096-616b-4086-b5cb-5e34cb6a0470.png)

**Comment by hagezi** [comment]
@pictosun 

I have now looked at it again and performed several translations. It seems that the translation sometimes does not work, then a red error message appears at the top. After unblocking s.deepl.com the error no longer occurs.

I take the domain on the whitelist ...

**Comment by hagezi** [comment]
fixed.
