### ISSUE TITLE
TikTok partially broken as captcha challenge cannot be loaded

### ISSUE THREAD

**Issue by StrangePeanut** [hagezi/dns-blocklists#1890]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

pfBlockerNG

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

lf-cdn-tos.bytescm.com

### Why should the domain(s) be unblocked?

Captcha challenge cannot be loaded which prevents parts of TikTok from working

**Comment by hagezi** [comment]
Thanks, will be removed.
