### ISSUE TITLE
RedeCanais

### ISSUE THREAD

**Issue by MatadorProBr** [hagezi/dns-blocklists#1891]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Personal, Multi NORMAL, Multi PRO, Most Abused TLDs

### Which domain(s) should be unblocked?

redecanais.zip
redecanaistv.zip
xn--90afacat5dwa6a2e.xn--p1ai
xn--90afacaz8cml9ac9f.xn--p1ai

### Why should the domain(s) be unblocked?

It uses a abused TLD but it's not used for anything bad besides distributing movies, series and TV channels with some little ads (which is already blocked with the blocklist).

**Comment by hagezi** [comment]
zip: ping @yokoffing
