### ISSUE TITLE
jsdelivr CDN mirror

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#1895]
Add jsdelivr CDN as a mirror for hagezi

GitHub convertor: https://www.jsdelivr.com/github
example: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@main/adblock/ultimate.txt

**Comment by hagezi** [comment]
I wanted to include the links, but at the moment there are size problems with different file formats, see:
https://github.com/hagezi/dns-blocklists/discussions/1852#discussioncomment-7828522

**Comment by hagezi** [comment]
There is a size limit of 20 MB for single files and therefore unusable for some of my lists.
https://github.com/jsdelivr/jsdelivr/tree/master#restrictions

**Comment by piquark6046** [comment]
Please continue at https://github.com/hagezi/dns-blocklists/issues/2097.
