### ISSUE TITLE
Annoying ads

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#1896]
### Which domain(s) should be blocked?

www.adbosgame.com
api.mythad.com
apse-cr-svr-algorix.com
mediaservingcd.com
dsp.nexabids.com

### Why should these domain(s) be blocked?

f, this is ads.

**Comment by MagicalAlchemist** [comment]
want to edit
**apse-cr.svr-algorix.com** is the correct one
_apse-cr-svr-algorix.com_ is incorrect

**Comment by hagezi** [comment]
another one: `use-cr.svr-algorix.com`
