### ISSUE TITLE
False Positive [uplynk.com]

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#190]
Blocking the following domain doesn't allow videos to play on this website. See example below.

Example
https://fox11online.com/news/local/fox-cities/tiktok-ban-on-government-devices-in-wisconsin-could-impact-advertising-within-the-state-mike-gallagher-republican-tony-evers-phone-computer-social-media-facebook-bytedance-twitter-instagram#

**Comment by hagezi** [comment]
Thanks, removed.
