### ISSUE TITLE
pro plus list blocks Eventbrite support chat

### ISSUE THREAD

**Issue by eharris** [hagezi/dns-blocklists#1906]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

bind9 rpz

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

api.amplitude.com
api.mypurecloud.com

### Why should the domain(s) be unblocked?

These two domains seem to be required for Eventbrite online support chat to work.

**Comment by hagezi** [comment]
@eharris Is there a link where I can test this? `api.amplitude.com` is a well-known tracker, if unblocking is really needed, then this is something for the personal Allowlist.

Please check whether unblocking `api.mypurecloud.com` is enough.

**Comment by eharris** [comment]
www.eventbrite.com/help/en-us/contact-us/

**Comment by hagezi** [comment]
Could it be that you need an account for this? I don't have one and I can't find a support chat without a login.

**Comment by hagezi** [comment]
I have created an account and tested the chat, I can't see any limitations with Ultimate

![image](https://github.com/hagezi/dns-blocklists/assets/104343908/b5113c26-4630-424e-b4c7-96793f06425f)

**Comment by eharris** [comment]
I was testing on a computer, not a phone.  But further testing shows that it seems to work now without any changes.  Perhaps they had an outage that coincided and just seemed like unblocking made it work.  Closing.
