### ISSUE TITLE
AdGuard for iOS list crashing wifi on iOS (it's not the threat intelligence list)

### ISSUE THREAD

**Issue by jaypatrick** [hagezi/dns-blocklists#1907]
I'm not sure which list it is, but it's not the one you noted as crashes wifi on ios (not the threat intelligence list). I do not know which list it is, but it's one of these:

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/popupads.txt

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/hoster.txt

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/anti.piracy.txt

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/gambling.txt

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/fake.txt

**Comment by hagezi** [comment]
See: https://github.com/hagezi/dns-blocklists/issues/1623

This is due to a limitation in ios, more than about 500000 rules lead to this behaviour.
