### ISSUE TITLE
False positive: speedcheck.org

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#191]
Pro Plus list. Also false positive in @notracking.

![Screenshot 2023-01-11 at 19-26-51 (4) Discord #🔗｜domain-reports Control D](https://user-images.githubusercontent.com/11689349/211947061-67a3d4f1-6ec1-4f26-826b-4fbb3cf362a7.png)

**Comment by hagezi** [comment]
Thanks, removed.

**Comment by hagezi** [comment]
Thanks, i think *.etrality.com is safe to remove:
https://slayterdev.github.io/tracker-radar-wiki/domains/etrality.com.html

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
