### ISSUE TITLE
linkt-help.top

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#193]
Can you kindly please block this site engaging in phishing activities?

The website in question is `linkt-help.top`, and it is targeting a legitimate website/business `linkt.com.au`.

Website was reported to the web host & domain registrar, the site may be offline by the time you see this so I have [archived the webpage](https://web.archive.org/web/20230111140114/http://www.linkt-help.top/linkt1.php) for your convenience.

I've also [flagged with a number of security vendors](https://www.virustotal.com/gui/url/8f89f1d423845780f1edd5031e0b44ead1e3914802172a499b2bda22bbdfa9d7?nocache=1)

**Comment by hagezi** [comment]
Thanks, added.
