### ISSUE TITLE
exlibris.ch not working correctly

### ISSUE THREAD

**Issue by akr-18** [hagezi/dns-blocklists#1936]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

exlibris.ch is not working properly with the activated blocklist (I only use this blocklist). The website is not blocked but the searchbox on the website (to look for specific books, authors etc.) is not working. 
When I set https://dns.quad9.net/dns-query as custom dns in the browser, it is working. 

### Why should the domain(s) be unblocked?

It is a shopping website for books and audio in Switzerland and is owned by one of the biggest retailers (Migros).

**Comment by hagezi** [comment]
Thanks, will be fixed on next update.

**Comment by hagezi** [comment]
@akr-18 The list should be updated in NextDNS in the next half hour, can you test it again and give feedback?

**Comment by akr-18** [comment]
It is now working like a charm. Thank you very much for the super-fast support.
