### ISSUE TITLE
Whitelist: tigress.wtf in Most Abused TLD filter list

### ISSUE THREAD

**Issue by snsmac** [hagezi/dns-blocklists#1938]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL, Most Abused TLDs

### Which domain(s) should be unblocked?

tigress.wtf

### Why should the domain(s) be unblocked?

It hosts the tigress C obfuscator from the University of Arizona

**Comment by hagezi** [comment]
@snsmac fixed.
