### ISSUE TITLE
Phone soft reboot - Infinix hot 9 play

### ISSUE THREAD

**Issue by thealidev** [hagezi/dns-blocklists#1939]
I am using Infinix hot 9 play
After i add your Blocklist in my next dns my phone started soft rebooting after five minutes of turn on
After analyzing problem with my everything i got know the issue
My phone took whole processor logs and send it to mediatek servers after every five minutes
But this Blocklist blocks thats logs to uploaded on server
So my phone do a soft reboot automatic to uploaded log again
Well just can you unblock the domains of mediatek and other services like that is used for logging processor info
Thanks btw

**Comment by thealidev** [comment]
Sorry to say
I reanalyzed it
It was not Blocklist issue

**Comment by hagezi** [comment]
Hi @thealidev,

Which list version are you using? And can you provide details of the domains concerned?

**Comment by hagezi** [comment]
@thealidev It's crazy that a smartphone reboots because it can't get rid of the logs. Some manufacturers are really cheeky. I think it largely affects all smartphones with a Mediatek chip (EPO.DAT).

I have removed the domains that I think could lead to the problem, the lists are updated in NextDNS. Can you please test and then give feedback?

**Comment by thealidev** [comment]
Are you sure
My software got crazy
I reflashed my stock rom to solve the issue

**Comment by hagezi** [comment]
@thealidev 

Then why don't you give me details of which blocked domains are supposedly causing your problem?

Which listen version are you using?

Currently no domains are blocked that prevent the uploading of logs.

Unfortunately, that's all I can do with my crystal ball ;)

**Comment by thealidev** [comment]
![Screenshot_20231215-112741](https://github.com/hagezi/dns-blocklists/assets/84855696/12281e52-5b6d-4fa5-bd31-df45d1bfeba1)
![Screenshot_20231215-112746](https://github.com/hagezi/dns-blocklists/assets/84855696/3672a421-6f50-4ca4-a0a0-f54ffe6c328c)
![Screenshot_20231215-112752](https://github.com/hagezi/dns-blocklists/assets/84855696/153ec6d9-6d4a-4f62-aa5e-c6b915e2d5d2)
![Screenshot_20231215-112757](https://github.com/hagezi/dns-blocklists/assets/84855696/eb5ed9b0-2284-4d89-ada9-69a711587790)

Here are log screenshots

**Comment by thealidev** [comment]
I don't know so much but mist of them are blocked by your Blocklist

**Comment by hagezi** [comment]
@thealidev 

What should I do with it? 

What time are the logs from, before the reboot?

Furthermore, the following domains are not on my lists:
```
*.mobsurl.com
*.yksdks.com
```

We can't make any progress like this, especially since you seem to be using other lists/functions that could be causing your problems. I asked about this, but did not receive an answer.

Deactivate all other lists, only use the Ultimate. If the problem still occurs, we'll take it from there.

**Comment by thealidev** [comment]
It is overall logs from start to finish
I mean full logs till phone on and soft reboot

**Comment by thealidev** [comment]
Well i prefer people if they have android (xos , hios or itelos) device
Kindly don't use this list for now
It is little buggy
Am i correct admins

**Comment by hagezi** [comment]
You claim that it's because of the list, I claim the opposite. I think we can close here.

If you can provide more reliable details, I'll be happy to take another look.

**Comment by thealidev** [comment]
Then what do you think I should do?

**Comment by hagezi** [comment]
@thealidev 

1. deactivate ALL blocklists, deactivate ALL functions under Security, Parental Controls and make sure that nothing is blocked via the denylist.
Deactivate the block page and CNAME flattening under Settings.

Test whether the problem still occurs. If the problem does not occur, continue with 2.

2. activate ONLY the OISD blocklist under Privacy.

Test whether the problem occurs, if so, search the log for the blocked domains and try to find out which of the domains are causing the problem. If the problem does not occur, continue with 3.

3. activate ONLY the HaGeZi PRO blocklist under Privacy.

Test whether the problem occurs, if so, search the log for the blocked domains and try to find out which of the domains are causing the problem. If the problem does not occur, then continue with 4.

4. activate ONLY the HaGeZi PRO++ blocklist under Privacy.

Test whether the problem occurs, if so, search the log for the blocked domains and try to find out which of the domains are causing the problem. If the problem does not occur, continue with 5.

5. activate ONLY the HaGeZi ULTIMATE blocklist under Privacy.

Test whether the problem occurs, if so, search the log for the blocked domains and try to find out which of the domains are causing the problem. If the problem does not occur ...

**Comment by thealidev** [comment]
I think issue is in these domains :

dcpxf.hs.gslb.mob.com
api-d.dutils.com

And i already reset my device and removed your all blocklists to solve
the problem

**Comment by hagezi** [comment]
The domains are not blocked in my lists, but they are blocked in OISD:

![image](https://github.com/hagezi/dns-blocklists/assets/104343908/2fc91d3f-31f8-4dbc-975b-62c0230ba42c)

![image](https://github.com/hagezi/dns-blocklists/assets/104343908/ec7bd423-3392-4259-a509-ef458f62d976)

So they can't be my lists.

**Comment by thealidev** [comment]
Well idk the issue main thing but it happened after adding your list
That's why i am blaming this list

**Comment by thealidev** [comment]
Ok
Just ignore and close the issue
Thanks
Bye
