### ISSUE TITLE
linkt-transport.top

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#194]
Can you kindly please block this site engaging in phishing activities?

The website in question is `linkt-transport.top`, and it is targeting a legitimate website/business `linkt.com.au`.

I have reported the site to the web host & domain registrar, the site may be offline by the time you see this, I'm unable to archive the webpage for your convenience as it will only show you the phishing website if you are accessing it from a mobile device otherwise it redirects you to the legitimate business website.

I've also flagged this domain with a number of security vendors as [evident on VirusTotal](https://www.virustotal.com/gui/url/7cfd4f9138107d120588d662c1989c1a35f742b264de78f63806e6bddc463826?nocache=1)

![image](https://user-images.githubusercontent.com/49738152/211978574-d3b6a5d4-9f84-471c-81f9-992818762e05.png)

**Comment by hagezi** [comment]
Thanks, added.

**Comment by gyCfjSnO** [comment]
Can you help me get this added to the AdGuard list? They've closed my issue trying to say the legitimate owners must be running the phishing website... I'm dumfounded... Kind of puts me off from wanting to use AdGuard Home anymore. 

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1185

**Comment by hagezi** [comment]
@gyCfjSnO I commented on that once.
