### ISSUE TITLE
https://www.totaaltv.nl/

### ISSUE THREAD

**Issue by Glassertje** [hagezi/dns-blocklists#1941]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL, Native Tracker

### Which domain(s) should be unblocked?

Can't acces website https://www.totaaltv.nl sins a few days.

In the log of Adguard Home i see that the domain that is blocked is: api.cooladata.com

And the filter is; ||cooladata.com^

### Why should the domain(s) be unblocked?

It is a information website for providers and streaming services.

**Comment by Glassertje** [comment]
In the log of adguard home i see that the domain that is blocked is: api.cooladata.com

**Comment by hagezi** [comment]
@Glassertje Hi, I cannot reproduce this, the page opens normally for me using the Ultimate list.

**Comment by Glassertje** [comment]
Ppff... i apologize. I use uBlock in Firefox and AdGuard/uBO – Cookie Notices is causing the problem. 

Thank you for the fast reply. Sorry for contacting you.
