### ISSUE TITLE
uk.trapstarlondon.com

### ISSUE THREAD

**Issue by aesof01** [hagezi/dns-blocklists#1943]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

uk.trapstarlondon.com

### Why should the domain(s) be unblocked?

legit fashion website

**Comment by hagezi** [comment]
@aesof01 
Not exactly a fake store, but a very poor rating: https://www.trustpilot.com/review/uk.trapstarlondon.com

Customers are being scammed here. Sometimes no delivery, no refund, ...

**Comment by hagezi** [comment]
Will be removed from the TIF with the next update, but will remain blocked in the aggressive lists.
