### ISSUE TITLE
Chaturbate.com stream

### ISSUE THREAD

**Issue by Morku** [hagezi/dns-blocklists#1944]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

live.mmcdn.com

### Why should the domain(s) be unblocked?

Enter the page and select a stream. The stream will not load or is choppy. Cause is the rule `||mmcdn.com^`
The workaround is `@@||live.mmcdn.com^` and the stream loads fine and other Subdomain of mmcdn remain blocked.

**Comment by iam-py-test** [comment]
> `live.mmcdn.com`

Does not resolve for me.
Thanks

**Comment by hagezi** [comment]
Thanks for your support, incorrectly detected as popup ad domain, will be removed.
