### ISSUE TITLE
alert-bendigobank.com

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#195]
This website should be added on the block list, the website in question is `alert-bendigobank.com`, and it is targeting a legitimate website/business https://www.bendigobank.com.au/.

A copy of the archived phishing website can be found here https://web.archive.org/web/20230112065834/https://alert-bendigobank.com/ and attached is a screenshot of the website accessed today.

16 security vendors flagged this URL as malicious on VirusTotal https://www.virustotal.com/gui/url/08bc9ad10c0cf23f827c9554cb680239949861773df6ff6ece65dc2f2b7e6688?nocache=1

![image](https://user-images.githubusercontent.com/49738152/212000286-2688cf33-f82e-4d19-baa1-8462a093b2ce.png)

**Comment by hagezi** [comment]
Thanks, added.
