### ISSUE TITLE
u.pcloud.com

### ISSUE THREAD

**Issue by braboobssiere** [hagezi/dns-blocklists#1952]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

u.pcloud.com

### Why should the domain(s) be unblocked?

it is authorization page of pcloud (i have seen it when try to link 3rd party app to pcloud)

**Comment by hagezi** [comment]
Thanks, via URLhaus malware list, will be removed.

**Comment by hagezi** [comment]
@braboobssiere fixed.
