### ISSUE TITLE
ISP mobile pinging domains

### ISSUE THREAD

**Issue by th3m** [hagezi/dns-blocklists#1953]
### Which domain(s) should be blocked?

`pvdynatracegw01.cosmote.gr`
`gcpsmapi.vodafone.com`

### Why should these domain(s) be blocked?

The first is a very aggressive pinging domain from the ISP Cosmote that it is very frequently happening in the background while their app is installed. Dynatrace in general is a cloud service for monitor and app analytics. I have manually blocked the domain for testing the last 2 months and nothing breaks, all functionality remains the same on the phone and on the app.
So i would suggest to be added to the aggressive lists PRO++ and Ultimate for the time being, but the pinging is very aggressive maybe it should be considered to be added in the normal lists after further testing.

The second domain is some kind of GPS mapping(?) from Vodafone that also happens in the background, not so aggressive or frequent like the first domain but still worth to mention and block. After blocking it for 2 months, all functionality remains the same, nothing breaks. My suggestion is to be added to the aggressive list (Ultimate).

Just have to add for both domains the official apps for both ISP were installed, the domain pinging is happening in the background while the apps are not running, notifications for the apps are disabled and 0 permissions are given.

**Comment by Ry3nlNaToR** [comment]
The 2nd domain doesn't look like a it's map related based on the output if you load it in a web browser.

```

{"links":{"report-attachment-submission":{"method":"POST","href":"https://gcpsmapi.vodafone.com/customerChannel/report/{id}/attachments","title":"Link for submitting attachment for report","type":"application/json"},"rate-submission":{"method":"POST","href":"https://gcpsmapi.vodafone.com/customerChannel/submit-rating","title":"Link for submitting user app rating ","type":"application/json"},"http://a42.vodafone.com/rels/sec/submit-events":{"method":"POST","href":"https://gcpsmapi.vodafone.com/submit-events","title":"Link for event submission","type":"application/json"},"http://a42.vodafone.com/rels/sec/submit-crash":{"method":"POST","href":"https://gcpsmapi.vodafone.com/submit-crash","title":"Link for crash submission","type":"application/json"},"report-submission":{"method":"POST","href":"https://gcpsmapi.vodafone.com/customerChannel/submit-report","title":"Link for Report and feedback submission","type":"application/json"}}}
```

Seem to be more of a tracking and feedback domain.

**Comment by hagezi** [comment]
Thanks everyone, will add `pvdynatracegw01.cosmote.gr` to the aggressive lists.
