### ISSUE TITLE
Blocklist is blocking Nike SNKRS website

### ISSUE THREAD

**Issue by ECHLN** [hagezi/dns-blocklists#1954]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

https://www.nike.com/za/launch?s=upcoming

### Why should the domain(s) be unblocked?

I can't shop Nike as a result

**Comment by ECHLN** [comment]
Same issue on the Ultimate Blocklist

**Comment by hagezi** [comment]
@ECHLN Thanks, fix is online. Wait until the list in AGDNS is updated or add the rule `@@||cdn.optimizely.com^` to your personal list.

**Comment by ECHLN** [comment]
Issue has been resolved, thank you!

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2006

**Comment by hagezi** [comment]
`optimizely.com` will be re-added to ultimate on next release. 

It is a popular tracker and there are only a few limitations. If you use the Ultimate, this is something for your personal allowlist.

https://duckduckgo.github.io/tracker-radar-wiki/domains/optimizely.com.html
