### ISSUE TITLE
ncc.avast.com

### ISSUE THREAD

**Issue by SeriousHoax** [hagezi/dns-blocklists#1957]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

`ncc.avast.com`

### Why should the domain(s) be unblocked?

According to Avast officials, "It is used for network connectivity testing only. ncc (Network Connectivity Check)".
So, looks like it's safe to unblock it and blocking it could possibly hamper the product in some way.
Source: https://forum.avast.com/index.php?topic=325661.0

**Comment by eliegoudout** [comment]
Hello,

I noticed that www.github.com/StevenBlack/hosts blacklists it [on purpose](https://github.com/StevenBlack/hosts/issues/2739). Is there a counter-argument to theirs for allowing it here?

**Comment by SeriousHoax** [comment]
> Hello,
> 
> I noticed that [www.github.com/StevenBlack/hosts](http://www.github.com/StevenBlack/hosts) blacklists it [on purpose](https://github.com/StevenBlack/hosts/issues/2739). Is there a counter-argument to theirs for allowing it here?

@eliegoudout IMO, his counter-argument is not good. Avast had a bad case in the past and it's fine to have some doubts about them but since the incident, Avast has changed many things regarding privacy. They abandoned those bad practices.
With that said, this particular domain was never related to user data collection anyway. It seems that they simply use this domain to verify whether the user has active internet or not. Similar to, NCSI (Network Connectivity Status Indicator) of Windows. 
Since Gen Digital products (Avast, AVG, Norton, Ccleaner) are used by millions of users, I think blocking something like this that breaks certain app functionality is not ideal.
Mr. Hagezi can decide if it's eligible to be blocked in the Ultimate list, but IMO it shouldn't go into any other filter lists.
BTW, I don't directly use any Avast products, excluding my Android phone's built-in scanner uses Avast database to scan apps. I didn't turn it off since I use modded apps and a scan by Avast doesn't cause any harm. The phone doesn't contact this domain.

**Comment by eliegoudout** [comment]
Thank you *very much* for your thorough answer. It helps me, from a simple user perspective, to enlighten whatever choice I will make.
