### ISSUE TITLE
Brazilian website Terra.com.br has a graphical interface blocking elements by Hagezi's DNS Pro Plus

### ISSUE THREAD

**Issue by jakecharlie** [hagezi/dns-blocklists#1959]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

https://www.terra.com.br/

https://www.terra.com.br/byte/terra-tem-data-centers-em-sp-rs-e-eua-veja-outros-pelo-mundo,90192feb711ea310VgnCLD200000bbcceb0aRCRD.html

### Why should the domain(s) be unblocked?

I am using Hagezi's DNS Pro Plus from ControlD Free DNS service. I noticed that the Brazilian website Terra.com.br, as well as its subdomains, have some element blocked by this list, which prevents the correct visualization of the website's graphical interface.

**Comment by hagezi** [comment]
Thanks for your support @jakecharlie, fix is online, wait for the update of the lists in ControlD or unblock `s1.trrsf.com`.
