### ISSUE TITLE
anz-shield-secure.com

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#196]
This website should be added on the block list, the website in question is `anz-shield-secure.com`, and it is targeting a legitimate website/business https://www.anz.com.au/.

I was unable to create an archived copy of the phishing website using the Wayback Machine as it has reCAPTCHA enabled, I have however attached a screenshot for your convenience.

7 security vendors flagged this URL as malicious on VirusTotal https://www.virustotal.com/gui/url/6d796f85b757fd04a1cb6a03a613fb0dd543a003551f146e4ccef529f7c6fb8f?nocache=1

![image](https://user-images.githubusercontent.com/49738152/212010091-cd682c04-2641-4690-a318-e99dd25751eb.png)

**Comment by hagezi** [comment]
Thanks, added.
