### ISSUE TITLE
richmedia.channeladvisor.com from Costco offer email is blocked

### ISSUE THREAD

**Issue by dominick-han** [hagezi/dns-blocklists#1960]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

richmedia.channeladvisor.com

### Why should the domain(s) be unblocked?

[My costco offer email](https://data.digital.costco.ca/ee/v1/webview?configId=a06f1d39-fdc3-41fe-85bf-08066f298482&level=channel&landingParams=eyJ1cmwiOiIifQ%3D%3D&pid=v1.4CHYl9FUyi8eeYfmqWAkJ5mccGSemhrkcQkQvh345dTR-aW47R_FCnmVa9KWCuejHhoia-bfIvu9C35ijeintyyQ3rVhGSmFtDdprZaAEFoAi937Is7KP9Seoqp61tHTYyp7rOgTatPcKIpL3DKfY2kLrb5n_GPG8mtIud9lJTf1LKRwo3Ii1HkNLHcJsRN_Rx2EOxYjMZZteYs&params=v1.D3FT4dsosgEfil7iRL2oTJ0NLcEgtgHsMXn5Up9oF2OYGqqHGsMQHRZxf5fmsguwMJLwTW2tA0D_xNwZzJ7-D66OHJII2W5VgVF2CQWHXNl0i-4413w98hkXU3JNMncRxHGZcORAdtwTbor2b3FwJ8CuQJ3pO9QWy2kV5zmdnf-Tx9gtJGQ46ti5yiQNn7ry4XFPoU0rNFveIhLJhsayPjb8gYMg70l9kj3JXuW4GxW3Ua7EwL2v-yc7EXWRwP22JiwYr9OLmbNzutWdZaReiVTwT-9j7NYBSVlb-c_a9b-zFtVmv101t0rMhA&p=v1.OGO8amDEXS6YjT9PO2gC8vK3Ms2rnu4v1QErxSiCpiJfzhDoe-HGeQBF3b8r2EZD-rTlV3OM0hbUVz-X8ZP0z3XYvfHNZLgT96WimWF9gj3Rub7wL2kNjVHz7sdb3wiVFPdYEVhm7zrPEZvz5Dtz4SZMQnZJ8m8srfYaofi5czTU2VoRLkWAKpHqNEn52vMU6eacxddmkgozhVsZ_Aa9Tzy0NQkN-CMWjrV6Zfzyh-kf8nf8Ns2cYvSyHEcMrpknsjy_CrZUohj31tNLeRkTdPsNq5td_ndVQhXUG3qB7rS04FVftIpv-xzk0gIy4oQaWKiazvwMJvfrrjJrI-Y8O6xqm-9OGJr6pFG3EBa1CMjKCAKc5Cvk07xI1Uux5n-qy7r2ek50ybd14xnEGjtVEYpwO2JZOxdJ9Bm8ByJRPnpBEqX2cWmDFcnA7kl2UWLzvDjvksx0U35lTh7sULc5LKwRQ22ZHrhjMvqQmrNFQCKNccTxP9mTKEENWNUDBh2YAlZ6-4SGXyVgUlvSxaznO4yrUGfIIrjbQL48G2nGhe2rnezcuvYSVLoGVs3mF7FL3XP1EUidQQaGhUyWzpQOQIfGFpUzr8OXeQzUr1dtCsthB-PnKH2f94Y1rc9I4vx_sOIKSVpJGq2pK4mxEEoRdjVEMsY3Ynz8uRr_G-CslZRPtQXc9hhBD0DhZRX33judGfRGQYNHWNw5&t=1703180344338&correlationId=79e71cee-fcc6-49dd-9c68-ec6221dc3c97-0)

Item images under "Our Top Offers Selected for you" are blocked because of "richmedia.channeladvisor.com" domain is blocked in Pro/Pro++ (didn't test normal)

**Comment by hagezi** [comment]
Thanks @dominick-han, will be fixed in next update.
