### ISSUE TITLE
tek.no

### ISSUE THREAD

**Issue by Schanzation** [hagezi/dns-blocklists#1961]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT, Multi NORMAL

### Which domain(s) should be unblocked?

tek.no

### Why should the domain(s) be unblocked?

When I have Multi light or Multi normal filter list enabled I can not see this comment section on this website. Is it possible to fix that?
https://www.tek.no/nyheter/nyhet/i/xgqbW8/tesla-skyldte-paa-kunder-for-feil-som-skyldtes-oedelagte-deler

![image](https://github.com/hagezi/dns-blocklists/assets/19490515/76ed0076-c59f-4efe-a4bb-efcf76bd27a0)

**Comment by hagezi** [comment]
Thanks @Schanzation for the support, will be fixed in the next update. The following domain will be removed: `cmmnts.i.bt.no`
