### ISSUE TITLE
can access site but can not search anything

### ISSUE THREAD

**Issue by Teddy0095** [hagezi/dns-blocklists#1964]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

https://www.kmart.com.au/

### Why should the domain(s) be unblocked?

i can access this site but when i try to search it is not doing anything (as below picture) and i am unable to find exact domain that is causing this. can you please help me. Thank you
![kmart](https://github.com/hagezi/dns-blocklists/assets/144679358/bc3885f1-2ea9-4c93-832f-5f267c674292)

**Comment by Teddy0095** [comment]
i was looking for domains to allow so that it works and allowing this works but i am not sure is it safe or not to allow ???

*.ac.cnstrc.com

**Comment by hagezi** [comment]
Thanks, will be removed.
