### ISSUE TITLE
Podcast Issues [podscribe.com]

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#1966]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

podscribe.com

### Why should the domain(s) be unblocked?

Blocking `podscribe.com` causes any podcast using this service to not play. They specifically require `verifi.podscribe.com` to play properly.

This domain does appear to be associated with advertising and podcast analytics, so maybe leave blocked on the ultimate list.

Examples
https://www.iheart.com/podcast/8-the-clark-howard-podcast-28200731/
https://www.iheart.com/podcast/1069-the-ben-shapiro-show-28178102/
https://www.iheart.com/podcast/1069-the-dan-bongino-show-28888454/

**Comment by hagezi** [comment]
Thanks, fixed.
