### ISSUE TITLE
Missing some UK TV domains

### ISSUE THREAD

**Issue by mvevitsis** [hagezi/dns-blocklists#1967]
### Which domain(s) should be blocked?

ITV:
recommendations.prd.user.itv.com
ar.prd.content.itv.com
toots-a.akamaihd.net

Channel 5:
c5adds.ott.skymedia.co.uk

Channel 4:
ads-pres.channel4.com

### Why should these domain(s) be blocked?

They are used for serving ads, and as far as I can tell there is no adverse effect from blocking them (I watch all of these channels)

**Comment by hagezi** [comment]
Thank you, the domains will be added with the next update, but the following domains are dead/no longer exist (NXDOMAIN):
```
c5adds.ott.skymedia.co.uk
ads-pres.channel4.com
```

**Comment by hagezi** [comment]
I found these as blockable domains:
```
c5ads.ott.skymedia.co.uk
skyads.ott.skymedia.co.uk
```
Did you mean these?

**Comment by mvevitsis** [comment]
Yes, that's correct.

**Comment by mvevitsis** [comment]
I tested the latest version and most were blocked (excluding ads-pres.channel4.com as you said this domain no longer exists).

However, toots-a.akamaihd.net is still going through, at least on pro++.

**Comment by hagezi** [comment]
My build system was of the opinion that the domain did not belong on the list. Now I have to investigate where the build system's own behaviour comes from.

I'll get back to you.

**Comment by hagezi** [comment]
@Reason, my domain database says:
Supposedly domain is required for streaming to work in the ITV Hub app. Can you please check this again for the app?

**Comment by mvevitsis** [comment]
> @Reason, my domain database says:
> Supposedly domain is required for streaming to work in the ITV Hub app. Can you please check this again for the app?
> 

I tried both live TV and on demand with this domain blocked, and both seemed to work without issue.

**Comment by hagezi** [comment]
Anyone here who can test this on AppleTV?

**Comment by mvevitsis** [comment]
@hagezi 

I had my mom test it on Apple TV.
Both live TV and on demand seem to work fine with this domain blocked.

**Comment by hagezi** [comment]
@mvevitsis Thanks, will be added.
