### ISSUE TITLE
Missing an Apple tracking domain

### ISSUE THREAD

**Issue by mvevitsis** [hagezi/dns-blocklists#1968]
### Which domain(s) should be blocked?

feedbackws.fe.apple-dns.net

### Why should these domain(s) be blocked?

This is included in the guide found here:
https://github.com/yokoffing/NextDNS-Config

The other recommended domains are already in Hagezi.
I can't seem to find any reason why this shouldn't be blocked (doesn't seem to break anything)

**Comment by hagezi** [comment]
This is the CNAME of `feedbackws.icloud.com` which is blocked in my lists.

```
dig feedbackws.icloud.com

; <<>> DiG 9.16.44-Debian <<>> feedbackws.icloud.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14021
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;feedbackws.icloud.com.         IN      A

;; ANSWER SECTION:
feedbackws.icloud.com.  43200   IN      CNAME   feedbackws.fe.apple-dns.net.
feedbackws.fe.apple-dns.net. 120 IN     A       17.248.209.68
```
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/31bb69d8-b423-4cf5-b1b8-3ea5d93a237a)

But I will include the CNAME.

**Comment by mvevitsis** [comment]
Strangely, this one is still going through for me using pro++ on nextDNS

![Screenshot 2023-12-24 at 20.26.15.png](https://github.com/hagezi/dns-blocklists/assets/12841042/6b38fca3-add8-4f12-be29-9a5d0a904a9d)

**Comment by hagezi** [comment]
My build system was of the opinion that the domain did not belong on the list. Now I have to investigate where the build system's own behaviour comes from.

I'll get back to you.

**Comment by hagezi** [comment]
Fix is online, wait for the next update in NextDNS,
