### ISSUE TITLE
Twitter domains

### ISSUE THREAD

**Issue by mvevitsis** [hagezi/dns-blocklists#1969]
### Which domain(s) should be blocked?

syndication.twitter.com

### Why should these domain(s) be blocked?

This domain is listed in the guide featured here:
https://github.com/yokoffing/NextDNS-Config

Unlike blocking graph.facebook.com, blocking this doesn't seem to break anything important, so I'm wondering why it isn't included in any blocklist (I am using pro++)

**Comment by hagezi** [comment]
The domain is only blocked in Ultimate, I seem to remember that on some pages embedded Twitter posts were not displayed when the domain was blocked. I'm not sure though, I'll have to check again.
