### ISSUE TITLE
TI-feed removed from ReThinkDNS?

### ISSUE THREAD

**Issue by iJorgen** [hagezi/dns-blocklists#197]
Hi!

When I follow your links I only see the Pro/ProPlus lists selected and can't find the TI-feed any more. Is it removed?!

https://sky.rethinkdns.com/1:AAoACBAA
https://sky.rethinkdns.com/1:AAoACAgA

**Comment by hagezi** [comment]
This is a bug in RethinkDNS, will be fixed in the next update in RethinkDNS. But I don't know exactly when that will be. Ping @ignoramous

**Comment by hagezi** [comment]
@ignoramous Thanks for your feedback.

**Comment by hagezi** [comment]
@ignoramous TIF not yet online, update already done?

**Comment by ignoramous** [comment]
The latest runs failed because... The size of compiled lists has blown up from 50M to 120M 

I'm looking to see which ones have grown dramatically and what I can do about those. I'm guessing the new lists we added as a replacement for Energized might be too big to chew (as in 120M is fine, but there isn't enough RAM on Cloudlare Workers to handle that).

**Comment by hagezi** [comment]
@ignoramous Thanls!

**Comment by ignoramous** [comment]
These lists have increased by 100k domains (and there are 20+ others with more than 10K+ new domains), I am looking to see how we can mitigate this short of not bundling these lists:

```
# recovered lists
Adult (ShadowWhisperer) 0 	| Adult (ShadowWhisperer) 231078 		| diff: 231,078
Threats (Hagezi) 0        	| Threat Intelligence Feeds (Hagezi) 674200 	| diff: 674,200
Child Protection (RPi) 0 	| Child Protection (RPi) 417479 		| diff: 417,479
Scamware (TBPL) 1269 		| Typosquatting Protection 150328 		| diff: 149,059
Ads (The Block List Project) 0 	| Ads (The Block List Project) 154573 		| diff: 154,573
---
# energized replacements
Energized Xtreme Extension 0 	| The Quantum Blocklist (AI) 1824219 		| diff: 1,824,219
Energized Unified 0 		| Blocklists (cbuijs) 3902648 			| diff: 3,902,648
Energized Basic 0 		| Normal (Hagezi) 373698 			| diff: 373,698
Energized Blu Go 0 		| Light (Hagezi) 151790 			| diff: 151,790
---
# new lists
Malware Ekans (rescure.me) 0 	| Malicious domains (cbuijs) 288381 		| diff: 288,381
Adult (Mahadi Xion) 31178	| Adult (cbuijs) 796188 			| diff: 765,010
```

**Comment by hagezi** [comment]
My lists also contain more dead Domains than should be on it. The last check for dead domains crashed and I had to use a backup of the dead list from December.
Currently a deadcheck is running but it will run for another 2-3 days.

**Comment by ignoramous** [comment]
Hi there, 

I removed *The Quantum Blocklist* and *Blocklists by Cbuijs* (around 5.7M entries), and the trie size was down to acceptable levels (70M).

I've deployed the new version to Fly (`max.rethinkdns.com`) which has the Threats (Hagezi) lists. I'll deploy this change to Cloudflare (`sky.rethinkdns.com`) after 12h of monitoring Fly (`max`).

**Comment by ignoramous** [comment]
Threats (Hagezi) should be back up on both `sky` and `max`. I've also improved retries and increased timeouts to make sure *existing* (bigger) lists don't drop off from builds: https://github.com/serverless-dns/blocklists/commit/50c4c9930491354d91b45390d3a024f8592de155

Sorry for the trouble, everyone (:

**Comment by hagezi** [comment]
@ignoramous Thanks for your work and the great support! It's time for a paid version of RethinkDNS ... ;)
