### ISSUE TITLE
PiHole-compatible regex whitelist

### ISSUE THREAD

**Issue by ColonelPanic-42** [hagezi/dns-blocklists#1970]
I see there is a `whitelist.txt` and `whitelist-referral.txt` in the `regex` folder, and there is a PiHole equivalent for the referral one (`whitelist-referral-pihole.txt`) which I presume only differs with the added info in the header and removal of the forward slashes surrounding the regex values. Would it be possible to get the same treatment for the base whitelist as well?

**Comment by hagezi** [comment]
I can do that, it's no problem.

**Comment by hagezi** [comment]
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/regex/whitelist-pihole.txt
