### ISSUE TITLE
Missing Brave Browser Telemetry

### ISSUE THREAD

**Issue by HoVeRzzz** [hagezi/dns-blocklists#1973]
### Which domain(s) should be blocked?

First of all this needs to be tested by me and more people to ensure this is safe to add.
From the reddit post I linked:

[static.brave.com](https://static.brave.com/)

[crlsets.brave.com](https://crlsets.brave.com/) about this domain idk but for me works fine but I don't use brave rewards

[brave-core-ext.s3.brave.com](https://brave-core-ext.s3.brave.com/) for this do it after you have waited a bit after the install as this domain probably has all the https upgrader type extensions but I have it disabled as I think its gonna get a lot of crpto stuff as well but if it causes problem with using crypto or brave rewards don't use it

[safebrowsing.brave.com](https://safebrowsing.brave.com/) (optional not recommended if you don't have configurable dns or dns that uses google safebrowsing)

[static1.brave.com](https://static1.brave.com/)

[laptop-updates.brave.com](https://laptop-updates.brave.com/) this is byfar the most pinged domain as you are using the browser as this is the one which catalogues all the ad types and their ad messages but seeing that this is pinged so often shows that even when rewards is turned off they still locally in the browser still run algorithms through whatever you do on the browser so in future brave rewards shows more relevant ads.

[variations.brave.com](https://variations.brave.com/) this is the second most pinged domain

[grant.rewards.brave.com](https://grant.rewards.brave.com/) optional only if you have disabled brave rewards

[api.rewards.brave.com](https://api.rewards.brave.com/) optional only if you have disabled brave rewards

[rewards.brave.com](https://rewards.brave.com/) optional only if you have disabled brave rewards

[p3a.brave.com](https://p3a.brave.com/) this isn't pinged when you have disabled 'automatically product analytics' but just did it just in case.

### Why should these domain(s) be blocked?

It should be added to improve privacy of Brave Browser users.

Source:  https://www.reddit.com/r/brave_browser/comments/n71we0/just_helping_everybody_out_how_to_disable_all/?rdt=47341

**Comment by hagezi** [comment]
I don't see any trackers here at a glance. At first glance, this looks more like try and error blocking to me. You should definitely take a closer look at this.

When I have more time, I'll take a closer look.

**Comment by HoVeRzzz** [comment]
@hagezi Alright. The thing is I never made any requests to that subdomains, only those I linked (very occasionaly).
Sometimes my browser pings p3a, static, static1 even though all GUI telemetry switches are OFF and safebrowsing is OFF.

**Comment by yokoffing** [comment]
* If `p3a.brave.com` is linked to analytics and nothing else, then sure.
* Generally wouldn't touch `static` requests.
* `Safebrowsing` hasn't been an issue with Brave for years now.
* Everything else is Brave Rewards, which is subjective. A non-issue if you disable their crypto stuff.

**Comment by HoVeRzzz** [comment]
> * If `p3a.brave.com` is linked to analytics and nothing else, then sure.
> * Generally wouldn't touch `static` requests.
> * `Safebrowsing` hasn't been an issue with Brave for years now.
> * Everything else is Brave Rewards, which is subjective.

Everything else is not Brave Rewards only related.
https://spyware.neocities.org/articles/brave
It is outdated but lists some of requests' content using curl.

**Comment by hagezi** [comment]
I have added `p3a.brave.com`. I don't think blocking rewards is a good idea. Everyone should decide for themselves whether they want to use it or not.

**Comment by HoVeRzzz** [comment]
Ok. Great decision thank you. I think we still should analyze it further to see if we can block more uncessary requests

**Comment by nightznero** [comment]
i m using Brave since first relase, i have blocked _Analytics_ and _Variations_ and didn't noticed ever any issue with it,every update,notification always comes in. Maybe (if) can be issue with **Rewards** cuz I use em but they are depended from location,campains and others so if they are not linked to rewards as for they can be easily blocked

**Comment by hagezi** [comment]
After further analysis, the following is now blocked:

```
light.txt         ||analytics.brave.com^
light.txt         ||matomo.brave.com^
light.txt         ||metrics.brave.com^
light.txt         ||p3a.brave.com^
light.txt         ||stats.brave.com^
light.txt         ||variations.brave.com^

multi.txt         ||analytics.brave.com^
multi.txt         ||matomo.brave.com^
multi.txt         ||metrics.brave.com^
multi.txt         ||p3a.brave.com^
multi.txt         ||stats.brave.com^
multi.txt         ||variations.brave.com^

pro.txt           ||analytics.brave.com^
pro.txt           ||matomo.brave.com^
pro.txt           ||metrics.brave.com^
pro.txt           ||p3a.brave.com^
pro.txt           ||stats.brave.com^
pro.txt           ||variations.brave.com^

pro.plus.txt      ||analytics.brave.com^
pro.plus.txt      ||matomo.brave.com^
pro.plus.txt      ||metrics.brave.com^
pro.plus.txt      ||p3a.brave.com^
pro.plus.txt      ||stats.brave.com^
pro.plus.txt      ||variations.brave.com^

ultimate.txt      ||ads.brave.com^
ultimate.txt      ||ads-static.brave.com^
ultimate.txt      ||analytics.brave.com^
ultimate.txt      ||matomo.brave.com^
ultimate.txt      ||metric-proxy.brave.com^
ultimate.txt      ||metrics.brave.com^
ultimate.txt      ||p3a.brave.com^
ultimate.txt      ||rewards.brave.com^
ultimate.txt      ||stats.brave.com^
ultimate.txt      ||variations.brave.com^
```

**Comment by nightznero** [comment]
> After further analysis, the following is now blocked:
> 
> ```
> light.txt         ||stats.brave.com^
> 
> ```
Do You know for whats is _stats.brave_ HaGi? Bcs i have added them in my cosmetic filter list to unblock necessary staffs from Brave `@@||stats.brave.com^$ghide
@@||stats.brave.com^$first-party`
But i also noticed that ADM(Advanced Download Manager) list also blocks it and i m a lil confused does its not that really ness as i was thinking? o.O

**Comment by hagezi** [comment]
@nightznero Unfortunately not, it's been on the lists for ages and comes in via QuidsUp Notrack. If it is triggered, you could take a look at the payload.

**Comment by ShivanKaul** [comment]
Blocking [variations.brave.com](https://variations.brave.com/) breaks the ability for users to get the latest Brave features, including privacy ones. We noticed this recently when we rolled out [Shred on Android](https://brave.com/privacy-updates/37-shred-button-android/) for Brave users. Users of this blocklist are placed in the unfortunate position of not getting the latest privacy features or turning off their blocklist. ([See thread on X](https://x.com/Techman_Z01/status/2047097026664423720)).

For what it's worth, `variations.brave.com` is not used for telemetry. Brave users can disable telemetry by disabling [P3A](https://support.brave.app/hc/en-us/articles/9140465918093-What-is-P3A-in-Brave) and [usage pings](https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Capture-of-Usage-Data). I think you have those network requests covered here. We also maintain https://github.com/brave/brave-browser/wiki/Network-requests-in-Brave for a list of network requests that are made by default, and explain why they're made. Let me know if you're seeing any network requests not mentioned there. Brave Rewards wouldn't be there (for example) because it requires the user to opt-into Rewards.

**Comment by ph00lt0** [comment]
@ShivanKaul very interesting did you patch this manually then because I have shred and block this domain?

**Comment by ShivanKaul** [comment]
The feature is now enabled by default in Nightly, but on Brave Beta and Release it's still only enabled via [variations.brave.com](https://variations.brave.com/) on Android. You can check if it's enabled by going to brave://flags/#brave-shred

**Comment by ph00lt0** [comment]
I don't use nightly or beta software. I am on release? And yes it is enabled

**Comment by ShivanKaul** [comment]
Hmm if variations.brave.com is always blocked for you then Shred on Android shouldn't be available since that's how we ship the seed file necessary to turn the feature on. Shred on iOS is however enabled by default in code.

**Comment by ph00lt0** [comment]
Very strange I honestly have no explanation for it as I am sure it is blocked (and logs proof so) anyway I probably should remove this from my blocklist too

**Comment by nightznero** [comment]
> Very strange I honestly have no explanation for it as I am sure it is blocked (and logs proof so) anyway I probably should remove this from my blocklist too

Well.. im in the same case. (I already unblocked it but..) Before i had blocked it and i m on Relase (Android) version and i have Shred option for like 2weeks or 3 already(variations.brave.com was blocked in this time)
