### ISSUE TITLE
Apphud API Unblock request

### ISSUE THREAD

**Issue by realgauravmehta** [hagezi/dns-blocklists#1974]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

api.apphud.com

### Why should the domain(s) be unblocked?

Used for in app purchases. Without allowing this URL an in app purchase didn't work and it was stuck in the loading screen. (App referenced: Replica on iOS)

**Comment by hagezi** [comment]
Thanks, will be removed.
