### ISSUE TITLE
Potentially abused TLDs

### ISSUE THREAD

**Issue by mvevitsis** [hagezi/dns-blocklists#1976]
### Which domain(s) should be blocked?

.pw
.nexus

### Why should these domain(s) be blocked?

I was comparing with yokoffing's recommended TLDs (in the guide here: https://github.com/yokoffing/NextDNS-Config)
as well as the Spamhaus recommended TLDs in NextDNS. I understand not including .cn, .ru, and .info since these might adversely affect users in those countries and have far too many legitimate uses for a whitelist to be effective.
However I noticed .pw and .nexus
Do these have any known legitimate uses?

**Comment by hagezi** [comment]
nexus:

https://github.com/hagezi/dns-blocklists/issues/1602

**Comment by hagezi** [comment]
pw, to many exclusions:

||pw^~libgen.pw|petridish.pw|palaugov.pw|dpc.pw|buttercup.pw|rezka.pw|darkcrystal.pw|xor.pw|fullhdfilmizlesene.pw|gopass.pw|vost.pw|core.pw|bittor.pw|plutonium.pw|nitter.pw|kge.pw ...
