### ISSUE TITLE
Block OneTrust Privacy Annoyances

### ISSUE THREAD

**Issue by riei2922jww** [hagezi/dns-blocklists#1979]
### Which domain(s) should be blocked?

my.onetrust.com
geolocation.onetrust.com
mobile-data.onetrust.io

### Why should these domain(s) be blocked?

Please add the following domains to
![IMG_8877](https://github.com/hagezi/dns-blocklists/assets/154846714/162994b9-85da-4914-9e70-376e62b471fb)
 the blocklist to prevent these annoying cookie pop-ups on 70% of applications.

**Comment by hagezi** [comment]
I can't block this for the masses in DNS lists.

In Europe, blocking at domain level means that many apps and websites do not work properly. Blocking should therefore be done via filter lists in browser content blockers. These can be used to decide what is blocked for which page and what is not. This is not possible in DNS, blocking is blocking, for every site and app.

**Comment by hagezi** [comment]
That is why they are not blocked in any known DNS list:

```
Domain:
 - mobile-data.onetrust.io OK

Malware/Phishing/Scam:

 - Threat?
   HaGeZi.TIF.RAW  NO
   DNS0.eu         NO
   DNS0.eu ZERO    NO
   Quad9           NO
   Umbrella        NO
   ThreatFox       NO
   URLhaus         NO
   ThreatView      NO
   CERT.PL         NO

 - Phishing?
   Phishing.Army   NO
   PT/OP/PH        NO

Top 1M:
 - Umbrella:       YES
 - Cloudflare:     NO
 - Tranco:         NO
 - Majestic:       NO
 - BuiltWith:      NO
 - Chrome:         NO

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - NRD.DGA.IDN     OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Umbrella        OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - DevDansHosts    OK
 - EasyList        OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.TIF      OK
 - HaGeZi.ULTIMATE OK
 - hBlock          OK
 - NextDNS         OK
 - OISD.Big        OK
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

```

**Comment by hagezi** [comment]
https://rethinkdns.com/search?q=mobile-data.onetrust.io

**Comment by hagezi** [comment]
@rowboatz Thanks for that, that's exactly what I can agree with. That's why I don't block CCM/CMP in the DNS lists, not even in Ultimate.
