### ISSUE TITLE
Calendar to book tickets doesn’t show up in Pro++

### ISSUE THREAD

**Issue by dikrek** [hagezi/dns-blocklists#1980]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

Not sure what’s blocked but the calendar selector when trying to buy tickets here is blocked:

https://winterwonderland.seetickets.com/winterwonderland

### Why should the domain(s) be unblocked?

Seems like it blocks normal site function - buying tickets is impossible

**Comment by hagezi** [comment]
@dikrek Thanks, fix is online, wait for the update in ControlD or unblock `c.ststat.net` temporarily.
