### ISSUE TITLE
Cannot play videos at https://www.express.co.uk/ - cookie notice is blocked

### ISSUE THREAD

**Issue by arturstat** [hagezi/dns-blocklists#1981]
### Which AdBlocker/DNS cloud service do you use?

AdGuard, NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

I am not sure!
The issue occurs at -> https://www.express.co.uk/news/world/1848866/countries-where-english-is-spoken-spt
To reproduce, you may need to clear browser data first.

### Why should the domain(s) be unblocked?

Cookie notice is blocked. Without accepting cookies, videos cannot be played.
My investigation leads to the conclusion that "HaGeZi - Multi NORMAL" is blocking the cookie popup.
The cookie notice only pops up when I disable "HaGeZi - Multi NORMAL" from within NextDNS.

**Comment by hagezi** [comment]
Thanks, `*.cmp.inmobi.com` must be unblocked. Will be removed.

**Comment by hagezi** [comment]
fixed.
https://github.com/AdguardTeam/AdguardFilters/issues/169293

**Comment by arturstat** [comment]
@hagezi 
Thanks for dealing with the issue so quickly!
Happy New Year!
