### ISSUE TITLE
Does using the whitelist overwrite some of the blocked entries, particularly the ones in the Encrypted DNS Server list?

### ISSUE THREAD

**Issue by tjamieg** [hagezi/dns-blocklists#1982]
I am currently using AdGuard Home with Multi Pro, Threat Intelligence Feeds, Most Abused TLDs, Encrypted DNS Servers only, and Native lists, along with the whitelist and referral whitelist.

My question, as the title suggests, is will the whitelist take precedence over the Encrypted DNS Server list, and accidentally allow certain DOH requests through?

**Comment by hagezi** [comment]
There is no reason to use the whitelist. It is actually only used to document what has been removed.
If necessary, you can use the referral whitelist, but this is not necessary as long as you do not use any other lists that block referral domains.

**Comment by hagezi** [comment]
Since there is always confusion with the AdBlock version of the whitelist and people simply use it without it even being linked and mentioned in the README, I will remove it.

**Comment by tjamieg** [comment]
Ahh okay, my apologies. Thank you for clearing up any confusion.

**Comment by xRuffKez** [comment]
If you only use Hagezis list, you dont need any of his allowlists exept when using Ultimate, there you can use meta tracker allowlist.

**Comment by alfky12** [comment]
So this is the cause of my adguard home blocked things more. Hagezi please don't remove this whitelist. This list is best used with your ultimate in combination with 1host pro. Please consider to release it again.

**Comment by xRuffKez** [comment]
> So this is the cause of my adguard home blocked things more. Hagezi please don't remove this whitelist. This list is best used with your ultimate in combination with 1host pro. Please consider to release it again.

https://github.com/hagezi/dns-blocklists/issues/1987#issuecomment-1870999331
