### ISSUE TITLE
cdu.de is blocked in TIF

### ISSUE THREAD

**Issue by 5c41a** [hagezi/dns-blocklists#1983]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

www.cdu.de

### Why should the domain(s) be unblocked?

german political party (a strange one, but that‘s another problem 😂 )

**Comment by hagezi** [comment]
Thanks, via usom.gov.tr Malwarelist. Will be removed asap.

**Comment by hagezi** [comment]
fixed.

**Comment by xRuffKez** [comment]
Ich sehe kein Problem die Domain in der TIF zu haben 😅
