### ISSUE TITLE
How do you add the list to Adguard? 

### ISSUE THREAD

**Issue by iamaugustinthomas** [hagezi/dns-blocklists#1985]
Its for filter subscription in adguard

**Comment by iamaugustinthomas** [comment]
Its for filter subscription in adguard

**Comment by hagezi** [comment]
@iamaugustinthomas 

These are DNS lists, which you can of course add to the filter lists, but they actually belong under DNS filters.

Which AdGuard products are we talking about? With the mobile versions, you need a Premium subscription to add more lists.

You should use the AdBlock version as the format.

**Comment by iamaugustinthomas** [comment]
<img width="964" alt="Screenshot 2023-12-28 at 08 11 45" src="https://github.com/hagezi/dns-blocklists/assets/141567905/d2f176c4-32ea-423e-8610-b438636ce3a7">
How do you add to this?
Thank you!

**Comment by hagezi** [comment]
You take the link (AdBLock format) of the list you want to add, e.g. for the Pro:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt
