### ISSUE TITLE
Whitelist gone ?

### ISSUE THREAD

**Issue by whyisthisbroken** [hagezi/dns-blocklists#1987]
Hey – I would just like to know why the whitelist is gone? Are there alternatives or is it over? :(

**Comment by hagezi** [comment]
Do you mean the AdBlock version? This will no longer exist in its current form. It was simply generated from my allowlist from the build system. In this form, it can only be used to a limited extent as a positive list in AdGuard, too much has been unblocked.

**Comment by whyisthisbroken** [comment]
yes, i mean the:
```
https://github.com/hagezi/dns-blocklists/blob/main/whitelist.txt
https://github.com/hagezi/dns-blocklists/blob/main/whitelist-referral.txt
```

Okay - thanks for the Info.

**Comment by hagezi** [comment]
I'm thinking about how I can divide it up differently so that I end up with a usable list. But that requires a lot of effort on the build system.

For the use of my lists, an additional use of the Allowlist is not necessary, the domains have already been removed.

**Comment by hagezi** [comment]
@whyisthisbroken 

The referral allowlist is still available in a suitable form:

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt

**Comment by brokoler** [comment]
> @whyisthisbroken
> 
> The referral allowlist is still available in a suitable form:
> 
> https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt

Hello @hagezi 
this whitelist seems not to be compatible with Technitium DNS, I get 0 whitelist entries when adding it.
Earlier I was using the referral whitelist that was published in a different format, which was working fine.
Could you probably make a version compatible with Technitium?

**Comment by hagezi** [comment]
@brokoler I don't know if Technitium can process DNS wildcard domain lists as allowlists, but here is what I can provide:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/whitelist-referral.txt
