### ISSUE TITLE
Foreign TLDs?

### ISSUE THREAD

**Issue by mvevitsis** [hagezi/dns-blocklists#1988]
I noticed that the DNS (PiHole) versions of the Most Abused TLDs blocklist don't have foreign domains in them, even though the ublock/adguard extension versions don't seem to have any exclusions for these domains.

Is this intentional, and if so, why?

**Comment by hagezi** [comment]
Pihole cannot process this type of rules.

**Comment by mvevitsis** [comment]
@hagezi I also noticed .zip in the no-exception list even though it has exceptions.

Is that a mistake?

**Comment by hagezi** [comment]
Yes, I explicitly included it because it is one of the most "dangerous" TLDs and has hardly any exceptions.
