### ISSUE TITLE
Unblock gruppenpraxis-woedlinger-schulz.at

### ISSUE THREAD

**Issue by flowsworld** [hagezi/dns-blocklists#1989]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Personal, Multi PRO, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

gruppenpraxis-woedlinger-schulz.at

### Why should the domain(s) be unblocked?

Group medical practice in Linz, Austria.

**Comment by hagezi** [comment]
Thanks @flowsworld, blocked in TIF via webnode.at.

Fixed.

**Comment by hagezi** [comment]
@flowsworld FYI: You do not need Personal if you use Pro. It is included in all lists.
