### ISSUE TITLE
Brightdata

### ISSUE THREAD

**Issue by r2fo** [hagezi/dns-blocklists#1990]
### Which domain(s) should be blocked?

brightdata.com
brightdata.de
bright-sdk.com
clientsdk.bright-sdk.com
perr.bright-sdk.com

### Why should these domain(s) be blocked?

Brightdata offers SDK’s for developers to put into their apps. These SDK’s abuse the user’s internet connection and turn it into a proxy. The developer earns money from it.

https://web.archive.org/web/20230601022816/https://old.reddit.com/r/privacy/comments/13wyc0c/bightdatacom_attempting_to_trick_child_into/

**Comment by hagezi** [comment]
ref: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1580

**Comment by hagezi** [comment]
Thanks @r2fo, added.

**Comment by sanjayen** [comment]
Two Bright Data SDK tracking domains which are missing in  HaGeZi's Pro mini DNS/Browser Blocklist

proxyjs.luminatinet.com
*.luminatinet.com

See https://blog.includesecurity.com/2026/06/the-smart-tv-in-your-livingroom-is-a-node-in-the-aiscraping-economy/ for details.

**Comment by hagezi** [comment]
```
ADBLOCK  light.txt                 ||clientsdk.luminatinet.com^
ADBLOCK  light.txt                 ||proxyjs.luminatinet.com^
ADBLOCK  multi.txt                 ||clientsdk.luminatinet.com^
ADBLOCK  multi.txt                 ||proxyjs.luminatinet.com^
ADBLOCK  pro.mini.txt              ||clientsdk.luminatinet.com^
ADBLOCK  pro.mini.txt              ||proxyjs.luminatinet.com^
ADBLOCK  pro.plus.mini.txt         ||clientsdk.luminatinet.com^
ADBLOCK  pro.plus.mini.txt         ||proxyjs.luminatinet.com^
ADBLOCK  pro.plus.txt              ||clientsdk.luminatinet.com^
ADBLOCK  pro.plus.txt              ||proxyjs.luminatinet.com^
ADBLOCK  pro.txt                   ||clientsdk.luminatinet.com^
ADBLOCK  pro.txt                   ||proxyjs.luminatinet.com^
ADBLOCK  ultimate.mini.txt         ||luminatinet.com^
ADBLOCK  ultimate.txt              ||luminatinet.com^
```
