### ISSUE TITLE
Allowlist union.fit

### ISSUE THREAD

**Issue by adworacz** [hagezi/dns-blocklists#1991]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home, uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

www.union.fit

### Why should the domain(s) be unblocked?

This is a legitimate domain used by yoga studios for event scheduling.

**Comment by hagezi** [comment]
https://github.com/yokoffing/filterlists/issues/127
