### ISSUE TITLE
Allowlist shayujizhang.com

### ISSUE THREAD

**Issue by wengkitttt** [hagezi/dns-blocklists#1995]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi NORMAL

### Which domain(s) should be unblocked?

shayujizhang.com
api.shayujizhang.com
cmt.shayujizhang.com
itg.shayujizhang.com
pms.shayujizhang.com
www.shayujizhang.com

### Why should the domain(s) be unblocked?

This website is a mobile application called "Shayujizhang" designed for tracking spending habits. The app provides features such as budgeting, expenses tracking and bill alert.

**Comment by hagezi** [comment]
Thanks, fixed.
