### ISSUE TITLE
OP.GG Desktop app 

### ISSUE THREAD

**Issue by Ghadeem** [hagezi/dns-blocklists#1997]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

not sure 

### Why should the domain(s) be unblocked?

OP.GG is a comprehensive website that offers valuable information, detailed statistics, and helpful resources for players across a wide range of popular games such as League of Legends, Teamfight Tactics, Valorant, and PUBG. 
I am currently experiencing a problem with the OP.GG desktop app. While the website (https://op.gg) functions properly, the app fails to load when I enable the Hagezi multi pro ++ filter. If you're interested in accessing the app, you can download it from this link: https://op.gg/desktop/. 
Unfortunately, I'm unsure which specific domain or URL needs to be unblocked to resolve this issue.

**Comment by hagezi** [comment]
Hi, @Ghadeem, happy new year,
which domains are blocked at app startup?

**Comment by hagezi** [comment]
@Ghadeem 

I have installed the app on Windows 11 and cannot reproduce the problem, the app starts. I tested with the Ultimate version of my lists, which contains everything from the Pro++ version.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/e569ed40-882e-4a47-97c1-e21140fa57d2)

**Comment by Ghadeem** [comment]
Thank you for your effort and assistance in trying to resolve the issue I've been facing with the op.gg. It appears that the issue might be related to NextDns rather than the filter itself. Interestingly, when I disable NextDns, the app works fine from the first attempt. 
I was wondering if you have any insights on how to debug further and identify the root cause of the issue. Are there any specific troubleshooting steps or logs that I could provide to help investigate the problem
Thank you again for your assistance, and I look forward to your response.

here is a YouTube video showing the issue: https://youtu.be/ECz2bi_UOCw

Do you think the embedded ad from NordVPN is causing this issue?

**Comment by Ghadeem** [comment]
Thank you for your effort and assistance in trying to resolve the issue I've been facing with the op.gg. It appears that the issue might be related to NextDns rather than the filter itself. Interestingly, when I disable NextDns, the app works fine from the first attempt. 
I was wondering if you have any insights on how to debug further and identify the root cause of the issue. Are there any specific troubleshooting steps or logs that I could provide to help investigate the problem
Thank you again for your assistance, and I look forward to your response.
Here is a video illustrating the issue: https://www.youtube.com/watch?v=ECz2bi_UOCw
Do you think the embedded ad from NordVPN is causing this issue?

**Comment by hagezi** [comment]
@Ghadeem I had tested with local Adguard Home, which uses DNS0.eu as upstream DNS.

To make sure it's NextDNS, I would create a profile, deactivate all blocklists, security features etc. and test the app with this profile.
If the problem occurs with this, then try an unfiltered DNS such as Cloudflare to see if the problem also occurs with this.

Gerd

**Comment by hagezi** [comment]
@Ghadeem I have tested the app against a NextDNS profile with the Ultimate and all security features, works perfectly.

Have you activated the block page in the NextDNS settings? It often causes problems where there are none. This feature is the plague and should be banned from NextDNS.

**Comment by hagezi** [comment]
Maybe the NextDNS Windows app is causing these problems ...
