### ISSUE TITLE
Shrink pro version

### ISSUE THREAD

**Issue by Domsicols** [hagezi/dns-blocklists#20]
Is it possible to shrink the pro version because I am using Adguard pro on ios and its only limitation is that greater than 500k domains it will not work? Thanks in advance

**Comment by hagezi** [comment]
Please use the multi list. Currently I can not reduce the list. It will rather grow. The blocking performance with the multilist will be the same with AdBlock iOS. I have made a few adjustments in the multilist.
If you miss something just let me know.

**Comment by Domsicols** [comment]
Thanks, I'll try the multi list but please make additions with the multi list not exceeding 500k, 450k  would be great since the pro has jumped with significant number of added list to 650k,

**Comment by hagezi** [comment]
@Domsicols I have optimized the pro version and additionally limited the size to a maximum of 500000 entries.

**Comment by Domsicols** [comment]
Thank you! Really appreciate it.
