### ISSUE TITLE
[Add] Meta Fallback Domains

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#200]
Meta graph fallback domains. Block in ultimate.

Details:
```
graph-fallback.instagram.com
graph-fallback.facebook.com
star.fallback.c10r.facebook.com
star.fallback.c10r.instagram.com
```

**Comment by hagezi** [comment]
Thanks, added. Will be included on next full update.

**Comment by devipasigner** [comment]
@hagezi is there a reason this was reverted?

**Comment by hagezi** [comment]
No, will check ...

**Comment by hagezi** [comment]
@devipasigner Should be fixed with the next update. Excluding *star* from whitelisting was missing.

**Comment by devipasigner** [comment]
> 

Thank you 😁

**Comment by hagezi** [comment]
fixed.

**Comment by devipasigner** [comment]
> fixed.

reverted again.

**Comment by hagezi** [comment]
Yes, because CNAME `star.fallback.c10r.facebook.com` breaks also Facebook-Messenger.

**Comment by devipasigner** [comment]
> Yes, because CNAME `star.fallback.c10r.facebook.com` breaks also Facebook-Messenger.

yes, so shouldn’t it be kept on ultimate since it’s a cname?
