### ISSUE TITLE
Shopee track domain

### ISSUE THREAD

**Issue by jakecharlie** [hagezi/dns-blocklists#2002]
### Which domain(s) should be blocked?

seller-log-collector.shopee.com.br

### Why should these domain(s) be blocked?

It is a tracking domain for Shopee shopping platform. You are already blocking log-collector.shopee.com.br but still not blocking seller-log-collector.shopee.com.br

I am using hagezi normal dns list from controld. Adguard dns list already blocks it. Thank you.

~ $ dig @76.76.2.40 log-collector.shopee.com.br

; <<>> DiG 9.16.41 <<>> @76.76.2.40 log-collector.shopee.com.br
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23706
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;log-collector.shopee.com.br.   IN      A

;; ANSWER SECTION:
log-collector.shopee.com.br. 60 IN      A       0.0.0.0

;; Query time: 40 msec
;; SERVER: 76.76.2.40#53(76.76.2.40)
;; WHEN: Mon Jan 01 22:48:56 -03 2024
;; MSG SIZE  rcvd: 61

~ $ dig @76.76.2.40 seller-log-collector.shopee.com.br

; <<>> DiG 9.16.41 <<>> @76.76.2.40 seller-log-collector.shopee.com.br
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 21291
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;seller-log-collector.shopee.com.br. IN A

;; AUTHORITY SECTION:
shopee.com.br.          900     IN      SOA     ns-125.awsdns-15.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 40 msec
;; SERVER: 76.76.2.40#53(76.76.2.40)
;; WHEN: Mon Jan 01 22:49:35 -03 2024
;; MSG SIZE  rcvd: 144

~ $

**Comment by hagezi** [comment]
Thanks @jakecharlie,

`seller-log-collector.shopee.com.br` will be added

`c-api-bit.shopeemobile.com` is not blocked, because: https://github.com/hagezi/dns-blocklists/issues/1428

Gerd
