### ISSUE TITLE
Microsoft Copilot app telemetry

### ISSUE THREAD

**Issue by th3m** [hagezi/dns-blocklists#2003]
### Which domain(s) should be blocked?

`location.microsoft.com`
`gateway.bingviz.microsoftapp.net`

`app.adjust.com`
`self.events.data.microsoft.com`

### Why should these domain(s) be blocked?

source: https://www.kuketz-blog.de/datenschutzverstoesse-bei-der-app-microsoft-copilot/

Tested the app with blocking all the above domains and still works perfectly.

**Comment by hagezi** [comment]
Hi @th3m,

thanks, but that needs further analysis:

`app.adjust.com` - [referral domain](https://github.com/hagezi/dns-blocklists#referral), only plocked in Pro++ and Ultimate. That won't change either.

`self.events.data.microsoft.com` - breaks Office 365 Admincenter and online collaboration on documents, only blocked in Ultimate. That won't change either.

`location.microsoft.com` - I am almost certain that this will break the Microsoft location service. I'll take a closer look at this.

`gateway.bingviz.microsoftapp.net` - This is an general Bing [Azure Application Gateway](https://learn.microsoft.com/en-us/azure/application-gateway/overview), blocking it probably has side effects. This definitely needs further analysis.

Gerd

**Comment by hagezi** [comment]
I will block the following domains in the Ultimate and then we'll see:

```
location.microsoft.com
gateway.bingviz.microsoftapp.net
```

**Comment by th3m** [comment]
Yes i understand,

as you see in the source link above every domain send device identifiers or post the google advertisingId.

All of them are super aggressive on pinging, and `location.microsoft.com` pings even with location services off and no app location permissions given.

**Comment by hagezi** [comment]
Yes, but I can't block this for the masses in non-aggressive lists if, for example, the "Windows find my device" no longer works and you can no longer find your stolen device as a result. This is more for a very strict list like the Ultimate or the personal denylist.

With the Azure Gateway, I'm not sure whether blocking will lead to further functional restrictions. That's why it's only blocked in the Ultimate for now.

**Comment by hagezi** [comment]
After further analysis, now blocked:

Pro++ and Ultimate:  `gateway.bingviz.microsoftapp.net` `app.adjust.*`
Ultimate: `location.microsoft.com` `self.events.data.microsoft.com` `in.appcenter.ms`

**Comment by hagezi** [comment]
FYI: after a few tests, I also blocked `location.microsoft.com` in Pro++.
