### ISSUE TITLE
Streaming/Torrent sites blocked

### ISSUE THREAD

**Issue by ECHLN** [hagezi/dns-blocklists#2004]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

https://fmoviesz.to/
https://www.13377x.tw/

### Why should the domain(s) be unblocked?

I’m unable to watch shows that aren’t available in my country

**Comment by hagezi** [comment]
@ECHLN both domains are not blocked in my lists, except in the anti piracy list.

**Comment by ECHLN** [comment]
Thank you Gerd. It must be my ISP then

On 02 Jan 2024, at 11:46 AM, Gerd ***@***.***> wrote:

﻿

@ECHLN<https://github.com/ECHLN> both domains are not blocked in my lists, except in the anti piracy list.
