### ISSUE TITLE
s.orbis.zone - ED Ship Builder 

### ISSUE THREAD

**Issue by Slipi089** [hagezi/dns-blocklists#2005]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Most Abused TLDs

### Which domain(s) should be unblocked?

s.orbis.zone

### Why should the domain(s) be unblocked?

s.orbis.zone is a link shorter for coriolis.io on this page you can create and edit ship configurations for the game Elite Dangerous
An example link would be: https://s.orbis.zone/nfwj

**Comment by hagezi** [comment]
Thanks @Slipi089, fixed in https://github.com/hagezi/dns-blocklists/commit/103f69afbf2b7435f058d3520b906b71ab9c6ab8#diff-378e604202344489bbf76519f6fcbc0aa20d930586d529e7cf91953b650f3c82
