### ISSUE TITLE
Nike SNKRS not working again

### ISSUE THREAD

**Issue by ECHLN** [hagezi/dns-blocklists#2006]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

https://www.nike.com/za/launch

### Why should the domain(s) be unblocked?

I can’t shop on Nike SNKRS. A fix was issue a month ago but it seems the site is blocked again

**Comment by hagezi** [comment]
WTF ...

**Comment by hagezi** [comment]
@ECHLN Sorry, my mistake, will be fixed with the next update. But I'll remove the domain temporarily.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/1954

**Comment by hagezi** [comment]
@ECHLN Thanks, fix is online. Wait until the list in AGDNS is updated or add the rule @@||cdn.optimizely.com^ to your personal list.

**Comment by hagezi** [comment]
@ECHLN The domain was on the ultimate protected list, on it are domains that are excluded for unblocking for the ultimate. I had overlooked this, but it has now been fixed.

**Comment by ECHLN** [comment]
Thank you !

**Comment by hagezi** [comment]
`optimizely.com` will be re-added to ultimate on next release. 

It is a popular tracker and there are only a few limitations. If you use the Ultimate, this is something for your personal allowlist.

https://duckduckgo.github.io/tracker-radar-wiki/domains/optimizely.com.html
