### ISSUE TITLE
000webhost.com was blocked

### ISSUE THREAD

**Issue by Iz-zzzzz** [hagezi/dns-blocklists#2008]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi LIGHT, Multi NORMAL, Multi PRO

### Which domain(s) should be unblocked?

```
000webhost.com
files.000webhost.com
panel.000webhost.com
```
maybe more

### Why should the domain(s) be unblocked?

These domains are not Ads, Affiliate, Phishing, Malware, Scam, Fake, Coins. 000webhost.com is just a free web hosting.

**Comment by hagezi** [comment]
95% of the subdomains are malware domains, which is why the main domain is and remains blocked.

**Comment by hagezi** [comment]
@Iz-zzzzz Sorry, I was mistaken, the main domain with the malware subdomains is `000webhostapp.com` not `000webhost.com`. But it also belongs to the "association". I will unblock `000webhostapp.com`, but I definitely cannot recommend using this free hoster.

**Comment by Iz-zzzzz** [comment]
I using this hoster to host my filter. I wonder why you not recommend using this free hoster?

**Comment by hagezi** [comment]
On the TIF 46781 malware subdomains of `000webhostapp.com` are blocked ...

Fixed in https://github.com/hagezi/dns-blocklists/commit/e61fc7946419168f44539ba904a09212b8bab296
