### ISSUE TITLE
Stone Island website broken

### ISSUE THREAD

**Issue by ECHLN** [hagezi/dns-blocklists#2009]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

https://www.stoneisland.com/

### Why should the domain(s) be unblocked?

I’m unable to shop on the Stone Island website because elements are missing from the website 
![IMG_5459](https://github.com/hagezi/dns-blocklists/assets/16183174/95273dac-ef6b-4fba-9589-87987795dffb)

**Comment by hagezi** [comment]
Thanks @ECHLN, `media.yoox.biz` unblocked.
