### ISSUE TITLE
reviewmygov.tuquy.com

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#201]
I believe the website `http://reviewmygov.tuquy.com/MyGov/index.html` to be a phishing website and targets https://my.gov.au/, can this be added on to the blocklist please?

I have reported to both the web host and domain registrar.

[VirusTotal](https://www.virustotal.com/gui/url/120d77be52cfd73768ba8cecd7cf9762cb2e13a8d66dec80f145b4856aa224bd?nocache=1)
[Wayback Machine](https://web.archive.org/web/20230113052519/http://reviewmygov.tuquy.com/MyGov/index.html)

![reviewmygov tuquy com](https://user-images.githubusercontent.com/49738152/212255124-e8149647-2e34-4426-b18b-c3ad089d11e2.png)

**Comment by hagezi** [comment]
Thanks, added.
