### ISSUE TITLE
Feature request: A principally anti-crapware, anti-snookering list

### ISSUE THREAD

**Issue by jadenekotenshi** [hagezi/dns-blocklists#2011]
I'd like to request a list somewhere between Normal and Pro that has a focus on excluding malware, badware, fake stuff and otherwise gullible-people-bait while taking a fairly light touch on everything else. This would be invaluable for keeping kids, the elderly, etc who are prone to clicking on anything that looks cool from getting their devices rooted, even for those users who aren't likely to have an admin around to unblock things.

**Comment by hagezi** [comment]
Light/Multi + Fake + TIF should fulfil your wish.

**Comment by hagezi** [comment]
@jadenekotenshi Is that sufficient for you?

**Comment by jadenekotenshi** [comment]
Oops, missed the initial reply. Yes, it is, thank you.
