### ISSUE TITLE
iobit.com blocked

### ISSUE THREAD

**Issue by kaiden87** [hagezi/dns-blocklists#2014]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

iobit.com

### Why should the domain(s) be unblocked?

This site is blocked in the multi pro++ and ultimate list, but not the other lists (lite, normal, pro). Is there a reason why it's blocked or is it just a mistake?

**Comment by hagezi** [comment]
Yes, see:

https://github.com/hagezi/dns-blocklists/issues/1794
