### ISSUE TITLE
URL duchessefit.com not blocked yet

### ISSUE THREAD

**Issue by Alex67693** [hagezi/dns-blocklists#2017]
### Which domain(s) should be blocked?

duchessefit.com

### Why should these domain(s) be blocked?

This site pops up fake phone cleaner warnings. Can be found on Google spam results.

**Comment by hagezi** [comment]
ref:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/64dfcfa5-f47c-4b14-81d0-33fbacf43a14)
