### ISSUE TITLE
Zalo app CDN blocked

### ISSUE THREAD

**Issue by hlqviet** [hagezi/dns-blocklists#2018]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

```
zpsocial-f35-org.zadn.vn
zpsocial-f40-org.zadn.vn
zpsocial-f41-org.zadn.vn
zpsocial-f42-org.zadn.vn
zpsocial-f43-org.zadn.vn
zpsocial-f44-org.zadn.vn
zpsocial-f45-org.zadn.vn
zpsocial-f46-org.zadn.vn
zpsocial-f47-org.zadn.vn
zpsocial-f48-org.zadn.vn
zpsocial-f49-org.zadn.vn
zpsocial-f50-org.zadn.vn
zpsocial-f51-org.zadn.vn
zpsocial-f52-org.zadn.vn
zpsocial-f53-org.zadn.vn
zpsocial-f54-org.zadn.vn
zpsocial-f55-org.zadn.vn
zpsocial-f56-org.zadn.vn
zpsocial-f57-org.zadn.vn
```

### Why should the domain(s) be unblocked?

Blocking these domains prevented the content in the feeds from being loaded.

I tried allowing `zpsocial-f56-org.zadn.vn` and got one of the images loaded.

![image](https://github.com/hagezi/dns-blocklists/assets/5486625/0500da64-7312-491d-aefa-7c6460bc30fc)

Android: https://play.google.com/store/apps/details?id=com.zing.zalo
iOS: https://apps.apple.com/vn/app/zalo/id579523206

**Comment by bigdargon** [comment]
From here https://github.com/hagezi/dns-blocklists/issues/2007

**Comment by hlqviet** [comment]
Ping @antiadvs

**Comment by hagezi** [comment]
Thanks and sorry, fixed.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/commit/d93c1efedb3ee077c815879f848430ada0243f5c
