### ISSUE TITLE
False Positive - mindvalley.com?

### ISSUE THREAD

**Issue by kallumrich** [hagezi/dns-blocklists#202]
I am not sure if this is intentional (and apologies if it is!) but mindvalley.com, which is an online learning platform for courses etc. seems to be blocked in all the lists.

Thanks!

**Comment by hagezi** [comment]
Thanks, yes it is a false positive domain, will remove.

ping upstream sources: @badmojr @notracking @stevenblack @FiltersHeroes

**Comment by kallumrich** [comment]
Thanks for the super fast response! Much appreciated.

**Comment by hagezi** [comment]
Removed.

**Comment by notracking** [comment]
KADhosts was also the source for me, fixed. Thanks!
