### ISSUE TITLE
Fox Nation App

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#2022]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

atp.fox

### Why should the domain(s) be unblocked?

The Fox Nation app requires `prod.xid.atp.fox` to initialize properly. Blocking this domain results in the app crashing immediately after landing on the Getting Started page. These results occur on the Amazon Fire TV Stick 4k.

**Comment by hagezi** [comment]
Thanks @markangus2b, fixed.
