### ISSUE TITLE
Portainer Docs

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#2023]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

cta-service-cms2.hubspot.com

### Why should the domain(s) be unblocked?

This domain is required to navigate to the Portainer Documentation. Clicking, "**Install Portainer CE Now**" will not properly redirect to Portainer Docs.

Example
https://www.portainer.io/install

**Comment by hagezi** [comment]
Thanks @markangus2b, fixed.
