### ISSUE TITLE
portalinmobiliario.com

### ISSUE THREAD

**Issue by sebalvaro** [hagezi/dns-blocklists#2026]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole, NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

```txt
portalinmobiliario.com
www.portalinmobiliario.com
```

### Why should the domain(s) be unblocked?

Portal Inmobiliario is a Latam/Chilean real estate platform that provides services for buying, selling, and renting properties. Blocking these domains causes the website to not function properly.

![imagen](https://github.com/hagezi/dns-blocklists/assets/9834151/39c830cb-9b74-4895-b7a4-26da2e8349b7)

**Comment by hagezi** [comment]
Thanks, fixed.
