### ISSUE TITLE
Allow safetwitch.drgns.space

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#2028]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

https://safetwitch.drgns.space/

### Why should the domain(s) be unblocked?

safetwitch.drgns.space is official [instance](https://codeberg.org/SafeTwitch/safetwitch#clearnet) SafeTwitch.

**Comment by hagezi** [comment]
Thans fixed.
