### ISSUE TITLE
Unblock peakperks.ca

### ISSUE THREAD

**Issue by AdamLMark** [hagezi/dns-blocklists#2029]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

peakperks.ca

### Why should the domain(s) be unblocked?

Legitimate program

**Comment by hagezi** [comment]
Thanks, fixed in https://github.com/hagezi/dns-blocklists/commit/51ccf7b77a9a6209527796c2276c7f7a2615c4bd
