### ISSUE TITLE
Potential threat

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#203]
See `https://www.reddit.com/r/firefox/comments/10ahdkf/fake_developer_mozilla_website`

URL: `https://developer.mozzila.org/` (two Z's)

When I run it [here](https://www.browserling.com) it takes me to `best.aliexpress.com`

![Screenshot 2023-01-13 151055](https://user-images.githubusercontent.com/11689349/212410808-5eb4a604-877c-42ae-8f5b-22f55e64ccdf.png)

I've also submitted to [Google Safe Browsing](https://safebrowsing.google.com/safebrowsing/report_general/).

**Comment by devipasigner** [comment]
> See `https://www.reddit.com/r/firefox/comments/10ahdkf/fake_developer_mozilla_website`
> 
> URL: `https://developer.mozzila.org/` (two Z's)
> 
> When I run it [here](https://www.browserling.com) it takes me to `best.aliexpress.com`
> 
> ![Screenshot 2023-01-13 151055](https://user-images.githubusercontent.com/11689349/212410808-5eb4a604-877c-42ae-8f5b-22f55e64ccdf.png)
> 
> I've also submitted to [Google Safe Browsing](https://safebrowsing.google.com/safebrowsing/report_general/).

Yep, probably a threat. It is already blocked in ultimate

**Comment by yokoffing** [comment]
> Yep, probably a threat. It is already blocked in ultimate

@devipasigner I should've checked his lists before reporting. But in the moment I thought I'd drop it here while I was reporting lol.

**Comment by devipasigner** [comment]
Wait, this domain is not a threat. It is a legit aliexpress domain. I think the reason it redirected you to this domain is because it is a referral link

**Comment by devipasigner** [comment]
See here: https://www.reddit.com/r/Aliexpress/comments/al5cme/please_fix_this_aliexpress_scamissue/

**Comment by yokoffing** [comment]
![Screenshot 2023-01-13 at 15-38-29 Fake Developer Mozilla Website firefox](https://user-images.githubusercontent.com/11689349/212414894-7773cda6-4234-4bab-af62-a548c333103f.png)

Everybody's getting a different experience lmao

**Comment by devipasigner** [comment]
Did some more research, it is a real aliexpress domain, however you can be hit with a malware unrelated to the domain that will redirect all sorts of online shopping links to referral links

**Comment by devipasigner** [comment]
So the link is not malicious but attackers use it to earn a profit from all your online shopping

**Comment by devipasigner** [comment]
Apparently clearing cookies and cache will fix it

**Comment by hagezi** [comment]
I added the subdomain incl. FLD and called domains to the lists. Anyway, pretty suspicious behaviour. It also seems to make a difference whether you use a mobile or desktop browser. Perhaps the humidity also plays a role, probably a climate crisis domain. ;)
