### ISSUE TITLE
i.imgur.com

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#2030]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

i.imgur.com

### Why should the domain(s) be unblocked?

This shows the actual images on imgur

**Comment by hagezi** [comment]
Thanks, via CERTPL and KADhosts, will be removed.
