### ISSUE TITLE
component-ota-eu.allawnos.com

### ISSUE THREAD

**Issue by Fqwe1** [hagezi/dns-blocklists#2031]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

component-ota-eu.allawnos.com

### Why should the domain(s) be unblocked?

Blocks system updates on Oppo phones

**Comment by hagezi** [comment]
Thanks @Fqwe1. Fixed.
