### ISSUE TITLE
feedback.questdiagnostics.com

### ISSUE THREAD

**Issue by FookunKlez** [hagezi/dns-blocklists#2035]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

feedback.questdiagnostics.com

### Why should the domain(s) be unblocked?

survey link for quest lab visit experience

**Comment by hagezi** [comment]
Thanks @FookunKlez, blocked by CNAME `akamaisecure8.qualtrics.com.edgekey.net` will be removed.

**Comment by hagezi** [comment]
Fixed in https://github.com/hagezi/dns-blocklists/commit/9f7ed9689468e922c97e691c5b1c22263d7a50ac
