### ISSUE TITLE
[FP] payments-redirector.ext.prd.jspaas.uk

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#2037]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Blocky

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

payments-redirector.ext.prd.jspaas.uk

### Why should the domain(s) be unblocked?

Greetings Gerd / @hagezi,

I hope you're well? 

Online card payments at a large national (UK) store fail due to this domain being blocked. Please can you add to the whitelist? Thank you for all your hard work!

Lee

**Comment by hagezi** [comment]
@RainmakerRaw 
Thanks Lee, will be removed in the current build.

**Comment by hagezi** [comment]
Fixed in https://github.com/hagezi/dns-blocklists/commit/ab1af75413e32bf79918fc356bc2e55bbe95dd64
