### ISSUE TITLE
Remove search.zzls.xyz and librex.zzls.xyz from wildcard/nosafesearch.txt

### ISSUE THREAD

**Issue by Fijxu** [hagezi/dns-blocklists#2038]
search.zzls.xyz is now non functional (and it will be for some days).
librex.zzls.xyz has been deprecated for months.
Oh, if you are asking, I am the owner of zzls.xyz and I will **replace all zzls.xyz domains by nadeko.net ones**. But at the moment, search and librex domains do not serve any search engines.

librex.zzls.xyz just displays a text telling what happened to the search engine. The same goes for search.zzls.xyz.

If I host SearxNG again in the future. I will notify you via trough a issue if you don't mind.

**Comment by hagezi** [comment]
Thanks @Fijxu, will be removed.
