### ISSUE TITLE
false positive domain in multi pro++

### ISSUE THREAD

**Issue by looser71** [hagezi/dns-blocklists#2039]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

tracker.nofap.com

### Why should the domain(s) be unblocked?

This blocked by default in multi pro++ . This website creates a flair in reddit sub r/Nofap which tells how many days have passed without relapsing. This is not a scam or other type of website.

**Comment by hagezi** [comment]
Thanks @looser71, will be removed.

**Comment by looser71** [comment]
Thanks brother haegzi for your services to the AdBlock community. Stay blessed. I am not a techy person so i don't know if I put the pull request proper but u got the point. ♥️

**Comment by hagezi** [comment]
Fixed.

**Comment by hagezi** [comment]
> Thanks brother haegzi for your services to the AdBlock community. Stay blessed. I am not a techy person so i don't know if I put the pull request proper but u got the point. ♥️

Thanks, I remove the domains via my build system and push the changes to the repository.  Pull requests would be far too time-consuming due to the many formats that need to be adapted.
