### ISSUE TITLE
Possible fake store

### ISSUE THREAD

**Issue by Slipi089** [hagezi/dns-blocklists#2041]
### Which domain(s) should be blocked?

http://east-trading.shop

### Why should these domain(s) be blocked?

![Screenshot_20240116-180601](https://github.com/hagezi/dns-blocklists/assets/59597268/c649eb1f-c69f-4c80-af73-b93c84392caa)

**Comment by Slipi089** [comment]
@hagezi could you please take another look at this? Somehow I believe bitdefender is a false positive. sorry for the circumstances.

**Comment by hagezi** [comment]
@Slipi089 Another company from the agricultural sector is registered at the address given in the legal notice and the VAT ID given there is invalid. The GMail contact address is also dubious. In short, the legal notice is fake.

**Comment by Slipi089** [comment]
@hagezi what surprises me is that under the address (Ludwig-Wucherer-Straße 33, 06108 Halle) there really is a store that also leads to instagram: https://www.instagram.com/luwu33_halle this website is also linked there again. that paypal is specified as a payment method is not usual for a fake store either, is it? so it looks quite "normal" to me again. i'm a bit confused in this case.

but thanks for your time and the great support
