### ISSUE TITLE
New Mexico Government website blocked on the Pro++ list

### ISSUE THREAD

**Issue by clemtech-nexus** [hagezi/dns-blocklists#2042]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

https://www.sos.nm.gov/

### Why should the domain(s) be unblocked?

It's an important Government website.

![Screenshot 2024-01-16 174100](https://github.com/hagezi/dns-blocklists/assets/143275628/3c63092a-73a7-47a5-8891-902aaa8953f0)

**Comment by hagezi** [comment]
Thanks @clemtech-nexus, but this domain is not blocked in my lists.

**Comment by clemtech-nexus** [comment]
I Apologize I accidentally type (or copy and paste) in the wrong domain, It's www.sos.state.nm.us (Which does Redirect to www.sos.nm.gov)

at least in my NextDNS logs, it shows it's blocked by Hagezi PRO ++

https://github.com/hagezi/dns-blocklists/assets/143275628/75ba9510-2a26-4c88-be74-2569b8a445a8

![Screenshot 2024-01-17 132100](https://github.com/hagezi/dns-blocklists/assets/143275628/daa85a31-6496-4bc1-95a1-18322ccd93f7)

**Comment by hagezi** [comment]
Thanks @clemtech-nexus, will be fixed asap.

**Comment by hagezi** [comment]
Fixed in https://github.com/hagezi/dns-blocklists/commit/bdb289cc6ac19d569f30afd13a66656d89f232b0
