### ISSUE TITLE
Multiple filterlists and their whitelists... could one whitelist cripple another filterlist?

### ISSUE THREAD

**Issue by Utini2000** [hagezi/dns-blocklists#2045]
Hi everyone,

so far I only had three filterlists in my setup:

- NextDNS
- Adguard DNS
- oisd.nl

I am now thinking about adding a more strict filterlist e.g. from HaGeZi.
The HaGeZi list will probably block something which might be whitelisted by oisd.

So what happens in the end?
Does oisd make HaGeZi less effective because it will whitelist something?
Or does the blocklist of HaGeZi trump the whitelist of oisd?
What is the best practice in such a case?

This will be configured in NextDNS, uBlock and AdGuard for Android.

Thanks!

**Comment by hagezi** [comment]
These are blocklists, not whitelists. The domains on these lists are blocked, regardless of which list they are on. The principle:

A domain is called up, then it is checked whether it is on one of the block lists used and if so, the domain is blocked.

With one exception, the AdGuard lists can also contain whitelist entries, which can unblock domains in AdGuard and uBlock that are blocked on other lists. However, this does not apply to NextDNS, ControlD and Co.

**Comment by Utini2000** [comment]
@hagezi oohhhh okay, I thought a filterlist (such as oisd, hagezi pro, easylist,..) would always contain domains that are being blocked but also some which are being whitelisted to prevent any errors/problems.

In that case I can just throw together all filterlists and not worry about much, except breaking something due to too strict filtering.

**Comment by hagezi** [comment]
Yes ;)
