### ISSUE TITLE
allow driveteslacanada.ca

### ISSUE THREAD

**Issue by abidjauhar17** [hagezi/dns-blocklists#2046]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

https://driveteslacanada.ca/

### Why should the domain(s) be unblocked?

When I enable the PRO filter, the site doesn't display the images on the website
but when I disable the filter, the images appear again

**Comment by hagezi** [comment]
@abidjauhar17 Thanks, I fixed it quickly, I'll take a closer look at it in a moment. You can update the list in AdGuard and test it.

**Comment by hagezi** [comment]
Fixed.
