### ISSUE TITLE
iot-dns.com

### ISSUE THREAD

**Issue by pduchnovsky** [hagezi/dns-blocklists#2047]
### Which domain(s) should be blocked?

*.iot-dns.com

### Why should these domain(s) be blocked?

I am assuming based on my short research that this is used by tuya devices for DNS queries
I blocked this manually and it seems there is no adverse effects (yet?)

**Comment by hagezi** [comment]
Thanks @pduchnovsky, I'll just block this in the aggressive and bypass lists for now.

**Comment by dennisvandehoef** [comment]
For everyone coming across this in the future.

This caused my sweeper to be unable to pair in the tuya app, and also removes functionality if this host can't be reached upon boot. Allowing *.tuyaus.com did not help. Based on [this comment on redit](https://www.reddit.com/r/homeassistant/comments/10b2384/comment/j4btora/) Also [localTuya for Home Assistant](https://github.com/rospogrigio/localtuya) might be affected.

_I still think that this is a valid entry for the list it has been added to. It's up to the person who encounters issues to decides if they want to allow the domain or not._
