### ISSUE TITLE
Metactrl

### ISSUE THREAD

**Issue by nightznero** [hagezi/dns-blocklists#2048]
Helloz HaGi, i would like to ask why there is a rule to block whole `Metactrl.com` site? Its any issues with company,shady as _Avast_ or smthg ?
Regards, NIGHTZNERO.
![Screenshot_20240117_171216](https://github.com/hagezi/dns-blocklists/assets/61750641/8b1b26b2-4286-42f6-893b-2b2685335201)

**Comment by hagezi** [comment]
@nightznero 
Blocked via logroid adaway-hosts, why? I have no idea.
