### ISSUE TITLE
Technitium DNS Server does not support wildcard

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#205]
Technitium only supports hosts/domains format! Please correct in README!

**Comment by devipasigner** [comment]
Technitium's domains/hosts format by default blocks subdomains by default just like adblock syntax. If you install advanced blocking extension under "Apps" it also supports adblock syntax and regex.

**Comment by hagezi** [comment]
> Technitium only supports hosts/domains format! Please correct in README!

I have tested the wildcard format and it works as expected. FLDs and SLDs are blocked.

**Comment by devipasigner** [comment]
> > Technitium only supports hosts/domains format! Please correct in README!
> 
> I have tested the wildcard format and it works as expected. FLDs and SLDs are blocked.

I’m confused, what is a FLD? I tried the wildcard lists and they don’t block domains however the hosts, domain and Adblock do. I saw the developer say the same a couple months ago on the GitHub as well.

**Comment by devipasigner** [comment]
Now I saw another post from the developer a couple years ago saying it does… Im going to check again

**Comment by devipasigner** [comment]
I think the developer means it supports wildcard blocking not wildcard syntax. Meaning it does not need wildcard syntax to achieve wildcard blocking of subdomains

**Comment by devipasigner** [comment]
Anyways, I’m switching back to adguard home since they just added dark mode 🤣

**Comment by hagezi** [comment]
As I said, I have it running here with the wildcard list. The list is nothing more than a compressed domain list preceded by *. to tell the DNS to block the domains including subdomains.

**Comment by devipasigner** [comment]
> As I said, I have it running here with the wildcard list. The list is nothing more than a compressed domain list preceded by *. to tell the DNS to block the domains including subdomains.

Will try again, but that is strange. Can you show me where you added them?

**Comment by hagezi** [comment]
![grafik](https://user-images.githubusercontent.com/104343908/212468971-46683d80-14a4-4ec4-84ca-e4c2da69a0e6.png)

```
[2023-01-14 11:05:59 Local] [192.168.178.111:64767] [admin] Block list update was triggered.
[2023-01-14 11:05:59 Local] DNS Server successfully downloaded block list (16.89 MB): https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
[2023-01-14 11:05:59 Local] DNS Server is reading block list from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
[2023-01-14 11:06:02 Local] DNS Server read block list file (849157 domains) from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
[2023-01-14 11:06:04 Local] DNS Server block list zone was loaded successfully.
```

**Comment by devipasigner** [comment]
> ![grafik](https://user-images.githubusercontent.com/104343908/212468971-46683d80-14a4-4ec4-84ca-e4c2da69a0e6.png)
> 
> ```
> [2023-01-14 11:05:59 Local] [192.168.178.111:64767] [admin] Block list update was triggered.
> [2023-01-14 11:05:59 Local] DNS Server successfully downloaded block list (16.89 MB): https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
> [2023-01-14 11:05:59 Local] DNS Server is reading block list from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
> [2023-01-14 11:06:02 Local] DNS Server read block list file (849157 domains) from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
> [2023-01-14 11:06:04 Local] DNS Server block list zone was loaded successfully.
> ```

Mine parses the rules as well but did you try out the blocking? It doesn't block any domains for me. Also at the bottom of that page it saids it supports domain/hosts..

**Comment by hagezi** [comment]
Yes...

![image](https://user-images.githubusercontent.com/104343908/212495266-877cf8f9-6029-4cef-a4a0-e175ba123d39.jpeg)

**Comment by devipasigner** [comment]
> Yes...
> 
> ![image](https://user-images.githubusercontent.com/104343908/212495266-877cf8f9-6029-4cef-a4a0-e175ba123d39.jpeg)

That’s so strange! I’ll check again when I get home. Anyways, I have a blocklist request: can you make a spam tlds list regex for technitium? Maybe the pihole one works but it seems outdated

**Comment by devipasigner** [comment]
So weird! I’m trying and it’s still not blocking anything!

**Comment by devipasigner** [comment]
@hagezi i think it may be a bug with technitium. I also see blocked domains in the stats and query log but if I run dig I can access the domains, not responded with 0.0.0.0. Can you run dig and verify you don’t get a response?

**Comment by devipasigner** [comment]
Also the owner itself claims it supports wildcard blocking but not wildcard syntax. The domains and hosts files will be blocked using wildcard

**Comment by devipasigner** [comment]
Switched back to domains/hosts..  blocking domains again

**Comment by hagezi** [comment]
Ping @TechnitiumSoftware

**Comment by hagezi** [comment]
@devipasigner 

**Wildcard format is definitely supported.**

It works fine for me, it processes the rules and applies them correctly. Blocked is `cdn.optimizely.com` on the list is only `*.optimizely.com` included.

![grafik](https://user-images.githubusercontent.com/104343908/212526815-8fd12685-5670-43d2-b49e-aa3e4b776393.png)

![grafik](https://user-images.githubusercontent.com/104343908/212526699-bf5dcc00-382c-4293-9c00-9bac61e6c881.png)

![grafik](https://user-images.githubusercontent.com/104343908/212526716-e49d552e-bb78-4edc-ba0d-f45f27f896e1.png)

Have TechnitiumDNS running in a Docker container and using my Ultimate list as a wildcard:

![grafik](https://user-images.githubusercontent.com/104343908/212526936-6836baac-3086-4514-b6d5-f92a1c1fcf0c.png)

Blocklist: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt

![grafik](https://user-images.githubusercontent.com/104343908/212527073-5ddc6338-8f29-4ed7-822e-079a991f825d.png)

```
[2023-01-15 06:37:08 Local] [192.168.178.111:64069] [admin] Block list update was triggered.
[2023-01-15 06:37:11 Local] DNS Server successfully downloaded block list (16.87 MB): https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
[2023-01-15 06:37:11 Local] DNS Server is reading block list from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
[2023-01-15 06:37:13 Local] DNS Server read block list file (848879 domains) from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
[2023-01-15 06:37:15 Local] DNS Server block list zone was loaded successfully.
```

**Comment by devipasigner** [comment]
> @devipasigner
> 
> **Wildcard format is definitely supported.**
> 
> It works fine for me, it processes the rules and applies them correctly. Blocked is `cdn.optimizely.com` on the list is only `*.optimizely.com` included.
> 
> ![grafik](https://user-images.githubusercontent.com/104343908/212526815-8fd12685-5670-43d2-b49e-aa3e4b776393.png)
> 
> ![grafik](https://user-images.githubusercontent.com/104343908/212526699-bf5dcc00-382c-4293-9c00-9bac61e6c881.png)
> 
> ![grafik](https://user-images.githubusercontent.com/104343908/212526716-e49d552e-bb78-4edc-ba0d-f45f27f896e1.png)
> 
> Have TechnitiumDNS running in a Docker container and using my Ultimate list as a wildcard:
> 
> ![grafik](https://user-images.githubusercontent.com/104343908/212526936-6836baac-3086-4514-b6d5-f92a1c1fcf0c.png)
> 
> Blocklist: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
> 
> ![grafik](https://user-images.githubusercontent.com/104343908/212527073-5ddc6338-8f29-4ed7-822e-079a991f825d.png)
> 
> ```
> [2023-01-15 06:37:08 Local] [192.168.178.111:64069] [admin] Block list update was triggered.
> [2023-01-15 06:37:11 Local] DNS Server successfully downloaded block list (16.87 MB): https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
> [2023-01-15 06:37:11 Local] DNS Server is reading block list from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
> [2023-01-15 06:37:13 Local] DNS Server read block list file (848879 domains) from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
> [2023-01-15 06:37:15 Local] DNS Server block list zone was loaded successfully.
> ```

That’s so weird! It’s possible it’s a bug with technitium, wouldn’t be surprised I’ve seen some similar bugs with blocklists

**Comment by hagezi** [comment]
Please open an issue here: https://github.com/TechnitiumSoftware/DnsServer/issues

**Comment by ShreyasZare** [comment]
> Ping @TechnitiumSoftware @ShreyasZare for support

Thanks for the ping. Technitium DNS Server does not support wildcard block lists in the current version. Support for it is coming up in the next update. You can check out [this issue](https://github.com/TechnitiumSoftware/DnsServer/issues/514) regarding the same.

However, Technitium DNS Server currently supports wildcard domain names being allowed/blocked using the options in the web panel. In there, blocking `*.example.com` blocks all the subdomain names but not `example.com`.

I am not sure how its working for @hagezi. It could be some other reason that its working for sure. Try a test by querying the blocked domain with type as TXT and you should get a response that explains how the domain was blocked. It could be either blocked by the Blocked zone, via the Advanced Blocking app, or could be that there is a forwarder configured which is actually blocking the domain name.

**Comment by hagezi** [comment]
@ShreyasZare Thanks for the feedback, but it works for me in the current Docker version `*.optimizely.com` blocks `optimizely.com` and all subdomains. For whatever reason

![grafik](https://user-images.githubusercontent.com/104343908/212540974-9eea3e97-f58f-4d38-b612-64b60d0a0c4b.png)

**Comment by ShreyasZare** [comment]
> @ShreyasZare Thanks for the feedback, but it works for me in the current Docker version `*.optimizely.com` blocks `optimizely.com` and all subdomains. For whatever reason

Test by querying for TXT record instead of A record for `cdn.optimizely.com` and share the output. That should give some clue on how its being blocked.

**Comment by hagezi** [comment]
@ShreyasZare OK, the Steven Black list is used, but it is not configured at all:

![grafik](https://user-images.githubusercontent.com/104343908/212541371-3202183b-d127-438e-b2a9-8e722cb7a25f.png)

**Comment by ShreyasZare** [comment]
> @ShreyasZare OK, the Steven Black list is used, but it is not configured at all:
> 
> ![grafik](https://user-images.githubusercontent.com/104343908/212541371-3202183b-d127-438e-b2a9-8e722cb7a25f.png)

The TXT record has `source=advanced-blocking-app` which indicates that you have the Advanced Blocking app installed which is actually blocking the domain.

**Comment by hagezi** [comment]
@ShreyasZare OK, that explains the behavior. Thanks!

**Comment by ShreyasZare** [comment]
> @ShreyasZare OK, that explains the behavior. Thanks!

You're welcome! Also, you wont have to edit your readme since support for wildcard block lists is coming in couple of weeks.

**Comment by hagezi** [comment]
Readme updated.
