### ISSUE TITLE
allow some fediverse instances

### ISSUE THREAD

**Issue by Sam-Oak** [hagezi/dns-blocklists#2050]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

akko.wtf
blahaj.zone
botsin.space
diode.zone
dragonscave.space
freeradical.zone
tiny.tilde.website
yiff.life

### Why should the domain(s) be unblocked?

they're all fediverse instances, i don't know if it's worth it since there are so many of them.

**Comment by hagezi** [comment]
Thanks, the problem is that if the exclusions become too long, the rules are no longer processed at some point and are ignored by AdGuard, for example.

@yokoffing what do you mean? Personally, I don't want to include such exclusions.

**Comment by yokoffing** [comment]
Idk what sources underlay `.space` and `.zone`. I would just remove those TLDs from the list; they're usually fan-made sites or fediverses. That would only leave

```
akko.wtf
tiny.tilde.website
yiff.life
```

for you to add as exceptions.

**Comment by hagezi** [comment]
Via Spamhaus, will remove `space` and `zone` and add the other exclusions.
