### ISSUE TITLE
Regarding facebook's new link history feature

### ISSUE THREAD

**Issue by th3m** [hagezi/dns-blocklists#2051]
I see many reports online about this tracking-malware JS pushing domain introduced with the new rolling facebook feature :

`netseer-ipaddr-assoc.xy.fbcdn.net`

Posting this for further analysis so maybe can be added on the tiff list.

The supposed malware injecting urls are in the form of
`{random generated}-netseer-ipaddr-assoc.xy.fbcdn.net`
so the blocking needs to be in an Adblock syntax for `xy.fbcdn.net`

Not sure if that's possible though cause in general fbcdn.net is used for video and image processing.

sources:
[https://mastodon.social/@protonmail/111699323585240444](url)
[https://lemmy.ml/post/10121519](url)

**Comment by hagezi** [comment]
You probably can't block xy.fbcdn.net without breaking something.

These are possible subdomains:

```
a.ns.xy.fbcdn.net
netseer-ipaddr-assoc.xy.fbcdn.net
netseer.xy.fbcdn.net
ns.xy.fbcdn.net
sonar6.xy.fbcdn.net
```

**Comment by hagezi** [comment]
This cannot be prevented via DNS without breaking something. Best to avoid Facebook ;)
