### ISSUE TITLE
Lokal TV Portal

### ISSUE THREAD

**Issue by Morku** [hagezi/dns-blocklists#2052]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

`hbbtv-tracking.bmt-technik.de`

### Why should the domain(s) be unblocked?

I am using a Smart TV with HbbTV. There is a channel with Lokal TV Portal: https://www.lokal-tv-portal.de/

No Stream loads with that domain blocked even when it indicate to be "tracking".

<details><summary>Screenshot:</summary>

![IMG_4266](https://github.com/hagezi/dns-blocklists/assets/6276915/99571a9d-2c57-49e2-998a-374888ca51b6)

</details><br/>

When I allow the domain, it's working fine.

<details><summary>Screenshot:</summary>

![IMG_4265](https://github.com/hagezi/dns-blocklists/assets/6276915/383cec17-b3e0-488b-9e5b-28c7f177d622)

</details><br/>

During use of the App, _from name_ very suspiciously other domains load randomly and App still works even when blocked, like: `hbbtv-pixel.bmt-technik.de` , `stats.mytvscout.de` and `tvstats.telvi.de`
It might be worth to check since I don't know how to analyze DNS connections.

**Comment by hagezi** [comment]
Thanks for your support @Morku 

will be unblocked:
`hbbtv-tracking.bmt-technik.de`

will blocked on next update:
```
hbbtv-pixel.bmt-technik.de 
stats.mytvscout.de
tvstats.telvi.de
```

**Comment by hagezi** [comment]
@Morku removed/added.
