### ISSUE TITLE
samsung.attn.tv

### ISSUE THREAD

**Issue by FookunKlez** [hagezi/dns-blocklists#2053]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

samsung.attn.tv

### Why should the domain(s) be unblocked?

Legitimate Samsung link

**Comment by hagezi** [comment]
Thanks @FookunKlez, will be removed.
