### ISSUE TITLE
allow hitadsmedia.com

### ISSUE THREAD

**Issue by abidjauhar17** [hagezi/dns-blocklists#2054]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

hitadsmedia.com or https://publisher.hitadsmedia.com

### Why should the domain(s) be unblocked?

Enabling the PRO filter makes the website display damaged and disorganized
![image](https://github.com/hagezi/dns-blocklists/assets/37255346/d1d34a18-64b2-4865-b1dc-8463ca4229e1)
![image](https://github.com/hagezi/dns-blocklists/assets/37255346/99631405-f818-42de-bb34-4ec40139043e)

**Comment by hagezi** [comment]
Thanks @abidjauhar17, but this is an advertising network that you would expect to be blocked in ads & trackers blocklists.

**Comment by abidjauhar17** [comment]
> Thanks @abidjauhar17, but this is an advertising network that you would expect to be blocked in ads & trackers blocklists.
> 
> On which page does the problem with the layout occur?

This is a dashboard page for me to create an advertisement to place on my website
https://publisher.hitadsmedia.com/dashboard
![image](https://github.com/hagezi/dns-blocklists/assets/37255346/e305ef39-1d82-45ca-8944-a88f41397b64)

**Comment by hagezi** [comment]
@abidjauhar17 This is something for the personal Allowlist, add the following rule: `@@||hitadsmedia.com^`
