### ISSUE TITLE
Request to block worldssl.net and all of its subdomains

### ISSUE THREAD

**Issue by SeimusS** [hagezi/dns-blocklists#2056]
### Which domain(s) should be blocked?

worldssl.net
r.worldssl.net

### Why should these domain(s) be blocked?

My L7 FW identified this domain as harmful with classification of Malware/Virus. After inspecting the sessions it looks like this domain and all its subdomains are potential thread.

**Comment by hagezi** [comment]
@SeimusS https://github.com/easylist/easylist/issues/267

**Comment by hagezi** [comment]
Related to https://help.cdn.net/hc/en-us/search?utf8=✓&query=worldssl.net

Blocking will break a lot.

Not flagged, not blocked by any Secure DNS.

**Comment by SeimusS** [comment]
Hello,

You are right. I miss-interpreted the session from the FW. It was referencing to perfops.r.worldssl.net. However now when I tried to query for it either internal or external no IP is present.

**Comment by hagezi** [comment]
Related to https://perfops.net/

I can't find anything malicious about the domain.

**Comment by SeimusS** [comment]
Very interesting, 

Could be a false positive in the FWs DB. 

I will close the request as no Block is needed.

Thank you very much for double checking!

Regards,
S.
