### ISSUE TITLE
Secondary Sentry link 

### ISSUE THREAD

**Issue by Amateur-God** [hagezi/dns-blocklists#2057]
### Which domain(s) should be blocked?

browser.sentry-cdn.com

### Why should these domain(s) be blocked?

error tracker for sentry, ``app.getsentry.com`` is allready on a blocklist but ``browser.sentry-cdn.com`` isnt

**Comment by hagezi** [comment]
Blocked in Pro, Pro++ and Ultimate.

Light and Normal does not block error trackers such as Bugsnag, Crashlytics, Firebase, Instabug, Sentry, ... and other app-specific crash trackers.

**Comment by hagezi** [comment]
`Blocklists:
 - 1Hosts.Lite     BLOCKED
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD.AT     BLOCKED
 - DevDansHosts    BLOCKED
 - EasyList        OK
 - GoodbyeAds      BLOCKED
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.TIF      OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - NextDNS.AT      OK
 - OISD.Big        OK
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK`
