### ISSUE TITLE
Bukalapak

### ISSUE THREAD

**Issue by abidjauhar17** [hagezi/dns-blocklists#2058]
Can you check the tracker and analytics on this online shop site which can and is safe to block?
https://www.bukalapak.com/

![image](https://github.com/hagezi/dns-blocklists/assets/37255346/d67981cf-9fad-465a-8032-cf8b89533d0b)

**Comment by hagezi** [comment]
All trackers I have found are already blocked.

**Comment by abidjauhar17** [comment]
@hagezi what about these sites?
https://shopee.co.id/
https://www.lazada.co.id/
https://www.blibli.com/

**Comment by hagezi** [comment]
There are a few reports from the community, these should already be covered.

**Comment by abidjauhar17** [comment]
> There are a few reports from the community, these should already be covered.

ok

try looking at this site
https://pahe.me/

there are pop up ads that if a visitor clicks in any area, an ad will appear in a new tab
for now I found https://lovy.llykjmzqkzkbr.top/ that looks suspicious
