### ISSUE TITLE
pahe.me - Popup Ads

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#2061]
try looking at this site
https://pahe.me/

there are pop up ads that if a visitor clicks in any area, an ad will appear in a new tab
for now I found https://lovy.llykjmzqkzkbr.top/ that looks suspicious

_from @abidjauhar17 in https://github.com/hagezi/dns-blocklists/issues/2058#issuecomment-1902172311_

**Comment by hagezi** [comment]
Blocked in all lists via CNAME `feuageepitoke.com`

Found the following domains on the same IPs, will be added with the next update:
```
avatarsfief.digital
belikeelean.life
boxofwhisper.com
businessessities.com
callyourinformer.com
cantedshackly.space
copycatnews.com
daphnews.com
drystervernile.life
edition25.com
ednewsbd.com
globeofnews.com
itvalleynews.com
justonemorenews.com
lookslikenews.com
louxoxo.com
newsforyourmood.com
newsfrompluto.com
newsignites.com
newsjuices.com
newslikemeds.com
newstemptation.com
newswhose.com
ninetyninesec.com
opentecs.com
ourlittlenews.com
popetechs.com
rerunglor.life
techiteration.com
technotology.com
topwwnews.com
viewyentreat.guru
viralnewssystems.com
wantsomenews.com
webmaghome.com
whataboutnews.com
whirlwindofnews.com
aleassbun.site
bridelydishley.space
enchaseys.website
eucosiaepeiric.com
paulusacor.uno
budgedsnavvle.com
minningespeire.com
nesokiahld.com
niatapray.com
putainalen.com
sealerysuppler.com
smasheswamefou.com
taoyinbiacid.com
babssata.com
bichosdamiana.com
bromidsluluai.com
codmanbumming.com
cubbingrebbes.com
fratchyaeolist.com
fudginghoners.com
gracedschelly.com
intinepollist.com
intrinechymous.com
lecticashaptan.com
lepiotaspectry.com
machairbren.com
mattockpackall.com
paravaprese.com
piloteegazy.com
printsmull.com
ranselpugmark.com
reivereme.com
rosolicdalapon.com
rotondelibya.com
sacquebenzine.com
sanseislydite.com
sciaticbehelp.com
solemncringle.com
unairedcushite.com
untineanunder.com
waxingcesti.com
williednb.com
writshackman.com
amidoxypochard.com
canastagruff.com
grubbysplay.com
ropedsawwort.com
scarnvesuvin.com
speermoving.com
ananymkidsman.com
aviewrodlet.com
betissantos.com
caidanglify.com
conoidsltr.com
daukshewing.com
draystownet.com
earlapssmalm.com
fritzantenna.com
fudderhemagog.com
idreamed-like.app
idreamed-match.app
idreamed-message.app
idreamed-news.app
idreamed-register.app
idreamed-register.com
idreamed-reset.app
lurgleucin.com
malleinevinces.com
mintmanunmanly.com
nonenetwiner.com
ovantfaits.com
paulinaccus.com
rimdieties.com
rockerysulkily.com
roomierhisis.com
scaliersingpho.com
sutiletoroid.com
tankertoxymora.com
tintersloggish.com
tympanskoff.com
aftwardatavi.guru
alexicallowed.digital
alexisclou.top
amoebaejacktan.website
awswayful.space
bebravetuis.top
bibulustartane.guru
borghtigrina.uno
briochechorea.website
checkcriey.website
cudwortparve.top
feelesssqueezy.guru
firmsossa.guru
forbledpukras.top
jewisalgetic.guru
jicamasonde.website
kennethsibber.space
knurleddeblock.guru
lambedbarbal.website
lanatesourock.uno
limberkilnman.cam
mezzoitys.life
nailyhexones.uno
neatenmikra.life
nideganta.life
pinlocklocular.space
pithjones.guru
pluralsoc.uno
pyropuscrimson.life
rabatwongara.website
rageekellock.top
regiltfurbish.website
simianssidrach.life
sonraifishnet.website
speanunlarge.cfd
swatheslyssic.space
taxablemuran.cfd
unwelthwen.digital
watchedthorter.guru
wigletrheeboc.digital
awnyrightle.com
axledjuking.com
baiocsomma.com
baloneyunraked.com
beetcrenula.com
binoticprotea.com
borghgeog.com
canzonicassons.com
clairekabobs.com
clognukes.com
codeinagugal.com
comitalmows.com
durgenweesh.com
echinusandaste.com
encarpiar.com
eulogiafilial.com
fallalentered.com
foliumumu.com
glochisprp.com
gorgetmobiles.com
grubsnuchale.com
hoodoosdonsky.com
jatfugios.com
karpasbeamer.com
kenoscoulee.com
leesecobourg.com
leptidunhaunt.com
linhacitoyen.com
lustickmiasmic.com
lyssapebble.com
mucinyak.com
nanaimostarkle.com
notesrumba.com
petasusawber.com
plotafb.com
porailbond.com
pudencygletty.com
pulpybizarre.com
shoeingneurone.com
tetrylscullion.com
throngsarseno.com
tokofyttes.com
tsarkinds.com
tweezesmalanga.com
tylosischewer.com
udalmancozen.com
uppardjets.com
vampersyacal.com
vanirstub.com
wagepulsate.com
waymarkgentiin.com
woolenabled.com
zirkiterocklay.com
blanksuppoint.com
bronzerkevil.com
essedadhooras.top
fobbedkaver.website
goleeairable.com
highishhayride.life
kedgingdemob.uno
lamparajudice.guru
meniscigox.digital
putamenbares.uno
regivenrefract.guru
rewetgreeter.top
sawflyacoela.com
scraichchoroid.com
skipssokotri.digital
stormsamba.live
sylviapettah.com
tannahokerly.com
tippierelbowy.guru
dampwarabi.com
pigmydocent.com
rustyretails.com
texacosimkin.com
arbersunroof.com
astrandconifer.com
axillovely.com
cusecwhitten.com
darghinruskin.com
halachadivvers.com
weanyergravely.com
xenylclio.com
```

**Comment by abidjauhar17** [comment]
> Blocked in all lists via CNAME `feuageepitoke.com`
> 
> Found the following domains on the same IPs, will be added with the next update:
> 
> ```
> avatarsfief.digital
> belikeelean.life
> boxofwhisper.com
> businessessities.com
> callyourinformer.com
> cantedshackly.space
> copycatnews.com
> daphnews.com
> drystervernile.life
> edition25.com
> ednewsbd.com
> globeofnews.com
> itvalleynews.com
> justonemorenews.com
> lookslikenews.com
> louxoxo.com
> newsforyourmood.com
> newsfrompluto.com
> newsignites.com
> newsjuices.com
> newslikemeds.com
> newstemptation.com
> newswhose.com
> ninetyninesec.com
> opentecs.com
> ourlittlenews.com
> popetechs.com
> rerunglor.life
> techiteration.com
> technotology.com
> topwwnews.com
> viewyentreat.guru
> viralnewssystems.com
> wantsomenews.com
> webmaghome.com
> whataboutnews.com
> whirlwindofnews.com
> aleassbun.site
> bridelydishley.space
> enchaseys.website
> eucosiaepeiric.com
> paulusacor.uno
> budgedsnavvle.com
> minningespeire.com
> nesokiahld.com
> niatapray.com
> putainalen.com
> sealerysuppler.com
> smasheswamefou.com
> taoyinbiacid.com
> babssata.com
> bichosdamiana.com
> bromidsluluai.com
> codmanbumming.com
> cubbingrebbes.com
> fratchyaeolist.com
> fudginghoners.com
> gracedschelly.com
> intinepollist.com
> intrinechymous.com
> lecticashaptan.com
> lepiotaspectry.com
> machairbren.com
> mattockpackall.com
> paravaprese.com
> piloteegazy.com
> printsmull.com
> ranselpugmark.com
> reivereme.com
> rosolicdalapon.com
> rotondelibya.com
> sacquebenzine.com
> sanseislydite.com
> sciaticbehelp.com
> solemncringle.com
> unairedcushite.com
> untineanunder.com
> waxingcesti.com
> williednb.com
> writshackman.com
> amidoxypochard.com
> canastagruff.com
> grubbysplay.com
> ropedsawwort.com
> scarnvesuvin.com
> speermoving.com
> ananymkidsman.com
> aviewrodlet.com
> betissantos.com
> caidanglify.com
> conoidsltr.com
> daukshewing.com
> draystownet.com
> earlapssmalm.com
> fritzantenna.com
> fudderhemagog.com
> idreamed-like.app
> idreamed-match.app
> idreamed-message.app
> idreamed-news.app
> idreamed-register.app
> idreamed-register.com
> idreamed-reset.app
> lurgleucin.com
> malleinevinces.com
> mintmanunmanly.com
> nonenetwiner.com
> ovantfaits.com
> paulinaccus.com
> rimdieties.com
> rockerysulkily.com
> roomierhisis.com
> scaliersingpho.com
> sutiletoroid.com
> tankertoxymora.com
> tintersloggish.com
> tympanskoff.com
> aftwardatavi.guru
> alexicallowed.digital
> alexisclou.top
> amoebaejacktan.website
> awswayful.space
> bebravetuis.top
> bibulustartane.guru
> borghtigrina.uno
> briochechorea.website
> checkcriey.website
> cudwortparve.top
> feelesssqueezy.guru
> firmsossa.guru
> forbledpukras.top
> jewisalgetic.guru
> jicamasonde.website
> kennethsibber.space
> knurleddeblock.guru
> lambedbarbal.website
> lanatesourock.uno
> limberkilnman.cam
> mezzoitys.life
> nailyhexones.uno
> neatenmikra.life
> nideganta.life
> pinlocklocular.space
> pithjones.guru
> pluralsoc.uno
> pyropuscrimson.life
> rabatwongara.website
> rageekellock.top
> regiltfurbish.website
> simianssidrach.life
> sonraifishnet.website
> speanunlarge.cfd
> swatheslyssic.space
> taxablemuran.cfd
> unwelthwen.digital
> watchedthorter.guru
> wigletrheeboc.digital
> awnyrightle.com
> axledjuking.com
> baiocsomma.com
> baloneyunraked.com
> beetcrenula.com
> binoticprotea.com
> borghgeog.com
> canzonicassons.com
> clairekabobs.com
> clognukes.com
> codeinagugal.com
> comitalmows.com
> durgenweesh.com
> echinusandaste.com
> encarpiar.com
> eulogiafilial.com
> fallalentered.com
> foliumumu.com
> glochisprp.com
> gorgetmobiles.com
> grubsnuchale.com
> hoodoosdonsky.com
> jatfugios.com
> karpasbeamer.com
> kenoscoulee.com
> leesecobourg.com
> leptidunhaunt.com
> linhacitoyen.com
> lustickmiasmic.com
> lyssapebble.com
> mucinyak.com
> nanaimostarkle.com
> notesrumba.com
> petasusawber.com
> plotafb.com
> porailbond.com
> pudencygletty.com
> pulpybizarre.com
> shoeingneurone.com
> tetrylscullion.com
> throngsarseno.com
> tokofyttes.com
> tsarkinds.com
> tweezesmalanga.com
> tylosischewer.com
> udalmancozen.com
> uppardjets.com
> vampersyacal.com
> vanirstub.com
> wagepulsate.com
> waymarkgentiin.com
> woolenabled.com
> zirkiterocklay.com
> blanksuppoint.com
> bronzerkevil.com
> essedadhooras.top
> fobbedkaver.website
> goleeairable.com
> highishhayride.life
> kedgingdemob.uno
> lamparajudice.guru
> meniscigox.digital
> putamenbares.uno
> regivenrefract.guru
> rewetgreeter.top
> sawflyacoela.com
> scraichchoroid.com
> skipssokotri.digital
> stormsamba.live
> sylviapettah.com
> tannahokerly.com
> tippierelbowy.guru
> dampwarabi.com
> pigmydocent.com
> rustyretails.com
> texacosimkin.com
> arbersunroof.com
> astrandconifer.com
> axillovely.com
> cusecwhitten.com
> darghinruskin.com
> halachadivvers.com
> weanyergravely.com
> xenylclio.com
> ```

wow. I was quite surprised
why are there so many?

**Comment by abidjauhar17** [comment]
@hagezi I also found https://qzzj.qyromjlbjlqkz.top/ on the site https://pahe.me/

**Comment by hagezi** [comment]
> @hagezi I also found https://qzzj.qyromjlbjlqkz.top/ on the site https://pahe.me/

It is blocked via the CNAME and you will find new ones every day because these popup domains sprout up like mushrooms. It is impossible to update them all promptly or add them at all, as they are automatically generated domains.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/9fcf9952-0bec-4c2f-91e7-71930bcf33fe)

**Comment by abidjauhar17** [comment]
> > @hagezi I also found https://qzzj.qyromjlbjlqkz.top/ on the site https://pahe.me/
> 
> It is blocked via the CNAME and you will find new ones every day because these popup domains sprout up like mushrooms. It is impossible to update them all promptly or add them at all, as they are automatically generated domains.
> 
> ![grafik](https://private-user-images.githubusercontent.com/104343908/298363841-9fcf9952-0bec-4c2f-91e7-71930bcf33fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTgxNzgsIm5iZiI6MTcwNTgxNzg3OCwicGF0aCI6Ii8xMDQzNDM5MDgvMjk4MzYzODQxLTlmY2Y5OTUyLTBiZWMtNGMyZi05MWU3LTcxOTMwYmNmMzNmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwNjE3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDkzMzU3NGNiZjI1OGI0NTgyY2FkMDVjZTY5NmNlODA4N2VhYzg1YzhiY2MyZTVhZmZjNTEwNzQxZWE2NzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RPRRN1jbiFYqoue5UbgRwOYwNz3zWVRRC6MBmQUUevY)

omg this damn trash 🤦‍♂️
