### ISSUE TITLE
TWO TLDS to BLOCK

### ISSUE THREAD

**Issue by supspaceyt** [hagezi/dns-blocklists#2062]
### Which domain(s) should be blocked?

.cam
.cams

### Why should these domain(s) be blocked?

because they are being abused by twitter bots and can get you malicious poups and the cal subscritipon that you never signuped for.

**Comment by hagezi** [comment]
Thanks @supspaceyt, but
`cam`: 2313 domains on umbrella top 1 million list - too many exclusions
`cams`: does not exist.
