### ISSUE TITLE
Square Site

### ISSUE THREAD

**Issue by rodeodomino** [hagezi/dns-blocklists#2064]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [x ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

https://square.site

### Why should the domain(s) be unblocked?

This is the url for restaurant ordering pages. For example https://soul-cocina.square.site/

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2063
