### ISSUE TITLE
Ghostbusters Spirit Unleased

### ISSUE THREAD

**Issue by Slipi089** [hagezi/dns-blocklists#2065]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

eu-west-2.echo.spacefish.illfonic.com

### Why should the domain(s) be unblocked?

This domain is used to play the multiplayer of the game Ghostbusters Spirit Unleashed by the developer Illfonic.

**Comment by hagezi** [comment]
Thanks, fixed in https://github.com/hagezi/dns-blocklists/commit/bad2f7584f0e0482db2adb3519e06731615be819
