### ISSUE TITLE
https://myip.wtf/ a legitimate IP adress viewer website

### ISSUE THREAD

**Issue by Uneccessary** [hagezi/dns-blocklists#2068]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

https://myip.wtf/ (trigger warning, F-word)

### Why should the domain(s) be unblocked?

The website is a legitimate IP viewer website and not malicious in any way

**Comment by hagezi** [comment]
Thanks @Uneccessary, fixed in https://github.com/hagezi/dns-blocklists/commit/0595e5ea71759413d4140f83f295401472a14b4a#diff-378e604202344489bbf76519f6fcbc0aa20d930586d529e7cf91953b650f3c82

**Comment by Uneccessary** [comment]
No problem :)
