### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by CodeCruncher24** [hagezi/dns-blocklists#2069]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

aliexpress.com
daraz.pk

### Why should the domain(s) be unblocked?

These seem to be falsely blocked, as I have checked with AdGuard, OISD filters.

**Comment by hagezi** [comment]
@CodeCruncher24I can't find the domains on my lists.

**Comment by CodeCruncher24** [comment]
Strange. I changed by lists and they opened fine. With your lists, they partially open and then there is white space on the page.

**Comment by hagezi** [comment]
I cannot reproduce this in my region.
