### ISSUE TITLE
Block Request for DoH/VPN/TOR/Proxy Bypass List

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#207]
Hello.

Can you add this website to your bypass blocklist? They website provide SSH, V2Ray, Vmess, Trojan Vpn, Wireguard, OpenVPN, Softether account for free. Which is can bypass network firewall.

https://www.fastssh.com
https://howdy.id
https://www.sshkit.com/
https://vpngame.com/
https://www.tcpvpn.com/
https://hax.co.id/ <- Free VPS but also provide free VMESS VPN server

**Comment by hagezi** [comment]
Thank you very much, I will add them.

**Comment by hagezi** [comment]
Added.

**Comment by MagicalAlchemist** [comment]
I added the list again if you don't mind. Mostly all lists below provide free SSH and VPN.

https://vpnudp.com/
https://ssh-free.com/
https://hidessh.com/
https://sshssl.com/
https://androvpn.com/
https://cyberssh.com/
https://freevpn.us/
https://greenssh.com/
https://www.jagoanssh.com/
https://sshagan.net/
https://lionssh.com/
https://globalssh.net/
https://cloudssh.net/
https://flyssh.com/
https://serverssh.net/
https://sshocean.com/
https://skyssh.co/
https://speedssh.com/
https://mytunneling.com/
https://jetssh.com/
https://portssh.com/
https://sshdropbear.net/
https://goodssh.com/
https://createssh.com/
https://bestvpnssh.com/
https://akashiro.co.id/
https://cloudssh.us/
https://ciscossh.com/
http://criarssh.com/
https://interssh.com/
https://mainssh.com/
https://sshstores.net/

**Comment by hagezi** [comment]
Thanks, added.
