### ISSUE TITLE
Include data from the DNS4EU project in TIF

### ISSUE THREAD

**Issue by MadSpindel** [hagezi/dns-blocklists#2071]
Hi Hagezi,

I am a user of your DNS blocklists and I appreciate your work. I would like to suggest that you check out the DNS4EU project, which is an EU-funded initiative to provide a public EU DNS resolver similar to Quad9. They are setting up a Threat Intelligence exchange that you might be able to join:
https://www.joindns4.eu/for-certs

If the data from the DNS4EU project could be included in your TIF in the future, that would be really good.

**Comment by hagezi** [comment]
Thanks, I'll have a look. However, I don't think they will make their entire source available, other services don't do that either.
Furthermore, it will probably be a censored DNS, well ...

**Comment by hagezi** [comment]
I have been in contact and the lists will not be public, as with other Sec DNS.
