### ISSUE TITLE
Tester wanted: Vivo's smartphone tracking domains

### ISSUE THREAD

**Issue by vhpcdpgl** [hagezi/dns-blocklists#2072]
### Which domain(s) should be blocked?

```
asia-commonitor-stsdk.vivoglobal.com
asia-compnrt-stsdk.vivoglobal.com
```
CNAME: `cname-sin01-stsdk09.vivoglobal.com`
[ the same CNAME with blocked domains:
```
asia-analyzer-appstore.vivoglobal.com
asia-comonrt-stsdk.vivoglobal.com
asia-comort-stsdk.vivoglobal.com
asia-ex-adlog.vivoglobal.com
asia-exstsdk.vivoglobal.com
asia-monitor-stsdk.vivoglobal.com
asia-onrt-stsdk.vivoglobal.com
asia-ort-stsdk.vivoglobal.com
asia-pnrt-stsdk.vivoglobal.com
asia-prt-stsdk.vivoglobal.com
asia-stsdk.vivoglobal.com
...
```
]

### Why should these domain(s) be blocked?

tracking domains

**Comment by hagezi** [comment]
@vhpcdpgl I have added an experimental Vivo native tracker list, more testers welcome:

Domains: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.vivo.txt
AdBlock: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.vivo.txt

Other formats are also available as usual.

**Comment by RicoHeat** [comment]
I'm currently working with a Vivo.. I can attest that *.vivoglobal. is very aggressive.. Just constantly feeding data to CN.. So far completely blocking *vivoglobal* has not created any issues.. Unless user is under warranty and still has android critical updates capabilities.. But for the most part it's related to Vivo system apps like their own app store, cloud storage etc.. Unfortunately they cannot be disabled or uninstalled unless user has Root access.

**Comment by hagezi** [comment]
Thanks @RicoHeat, the system apps should continue to work by blocking, anything else would cause too many screams ;)

**Comment by hagezi** [comment]
Added:

```
asia-err-up.vivoglobal.com
asia-vpushonrt-stsdk.vivoglobal.com
asia-vpushort-stsdk.vivoglobal.com
err-up.vivoglobal.com
eu-errup.vivoglobal.com
in-errup.vivoglobal.com
kz-err-up.vivoglobal.com
onrt-stsdk.vivoglobal.com
ort-stsdk.vivoglobal.com
pnrt-stsdk.vivoglobal.com
ru-err-up.vivoglobal.com
stsdk.vivoglobal.com
onrt.stsdk.vivoglobal.com
pnrt.stsdk.vivoglobal.com
err.up.vivoglobal.com
```

**Comment by hagezi** [comment]
Added:

```
cname-ali-asia-stsdk.vivoglobal.com
cname-asia-stsdk09.vivoglobal.com
in-adreq.vivoglobal.com
in-adsjssdk.vivoglobal.com
monitor-stsdk.vivoglobal.com
ort.stsdk.vivoglobal.com
prt-stsdk.vivoglobal.com
prt.stsdk.vivoglobal.com
ro-up.vivoglobal.com
```

**Comment by vhpcdpgl** [comment]
`https://www.netify.ai/resources/applications/vivo`
