### ISSUE TITLE
amazon.com.au

### ISSUE THREAD

**Issue by m0dded** [hagezi/dns-blocklists#2073]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

When trying to access amazon.com.au

Following domains are getting blocked - preventing the website from loading completely.

tp.04f01a85e-frontier.amazon.com.au
c.amazon-adsystem.com
d10yke8mddzjba.cloudfront.net

### Why should the domain(s) be unblocked?

Try to access www.amazon.com.au - website won't load.
amazon.com loads fine.

**Comment by hagezi** [comment]
Thanks @m0dded cloudfront CNAME is blocked by Malware Filter Phishing list, WTF!

Will be fixed asap.

**Comment by hagezi** [comment]
Fixed, Wait for the update in NextDNS (every half hour).
