### ISSUE TITLE
filedn.com

### ISSUE THREAD

**Issue by timothy890511** [hagezi/dns-blocklists#2074]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

filedn.com

### Why should the domain(s) be unblocked?

There is a cloud storage provider called pCloud.
pCloud has a "public folder" feature that makes the files in it available to the public.
This domain is used to access files in the pCloud public folder.

**Comment by hagezi** [comment]
Thanks @timothy890511, will be removed.

**Comment by hagezi** [comment]
@timothy890511 Fixed.
