### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by TIBCSI66** [hagezi/dns-blocklists#2076]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

vilagunk.hu

### Why should the domain(s) be unblocked?

I think it's a wrong ban

**Comment by hagezi** [comment]
Thanks @TIBCSI66, it is widely blocked, but I don't see why:

```
Blocklists:
 - 1Hosts.Lite     BLOCKED
 - 1Hosts.Mini     BLOCKED
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD.AT     BLOCKED
 - DevDansHosts    OK
 - EasyList        OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.TIF      OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - NextDNS.AT      BLOCKED
 - OISD.Big        BLOCKED
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED

```

**Comment by hagezi** [comment]
Will be removed.

**Comment by TIBCSI66** [comment]
Hi,

I have one more question.
**Does Hagezi Pro++ need this list?
Hagezi Threat Intelligence Feeds**
Unfortunately, this can only be achieved with AdguardDNS, not with NextDNS.
Adguard DNS does not have a server in Budapest, it connects to Frankfurt.
I used NextDNS because of the distance.
But if this filter is also important, then I may switch to Adguard.

REgards

**Comment by hagezi** [comment]
@TIBCSI66 Use their own TIF+AI in NextDNS. My TIF list is not available there.

**Comment by TIBCSI66** [comment]
Hi,

On the next page, if they would like to watch a video, the filters block it.
I think it is too: Hagezi Pro++
[https://www.mafab.hu/filmek/filmek/](url)
[https://www.mafab.hu/movies/a-keresztapa-2551.html](url)
You would look at it?

Regards,
