### ISSUE TITLE
apple-analyser.com  (MacOS BackDoor Crypto Stealer)

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#2077]
### Which domain(s) should be blocked?

apple-analyser.com
22.imohub.workers.dev
imohub.net
apple-health.org

### Why should these domain(s) be blocked?

apple-analyser.com  (MacOS Virus)

https://securelist.ru/new-macos-backdoor-crypto-stealer/108815/

**Comment by hagezi** [comment]
Already blocked in TIF.

**Comment by dikrek** [comment]
What would the reasoning be to allow this to be added to the normal lists? Some services can’t add TIF (like the free controlD, you can only pick 1 list)

**Comment by hagezi** [comment]
I have split the lists so that they are acceptable in terms of size. How do I draw the line between what is added where?
