### ISSUE TITLE
Philips Hue systems should be on Blocklists

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#208]
Hi,

don't know if you're aware of the extensive tracking of Philips Hue systems from Philips. But these are sending a 'lot' of data via DNS and I think that a lot of stuff can be blocked.

**Comment by hagezi** [comment]
I have no way to test this, so would need to know which domains are blockable without them limiting functionality and crippling the whole system.

**Comment by pictosun** [comment]
I will investigate and give you feedback.

**Comment by hagezi** [comment]
@pictosun 

During my web research I found the following domains which are supposed to be related to Analytics and Metrics:

`diagnostics.meethue.com` - Needed for "out of home" control and software update check.
`dc1.philips.com ` - `dp.dc1.philips.com` CNAME for `www.ecdinterface.philips.com` - Needed for Hue Bridge
`ws.meethue.com` - Central Service?

![grafik](https://user-images.githubusercontent.com/104343908/213552304-e1c3acf1-6633-42be-a19c-cb2e8e618034.png)
Source: https://www.sidnlabs.nl/en/news-and-blogs/looking-at-internet-traffic-using-spin-a-philips-hue-case-study

They seem to restrict functions, in short, I have not found anything that can be safely blocked. Unless you want to take them offline completely, that would be something for your personal block list, see:
https://community.home-assistant.io/t/how-to-silence-your-philips-hue-bridge/31816

I think we can close here, or do you see it differently?

**Comment by pictosun** [comment]
Hi. Sorry for the delay.

Do have a „lot“ of requests to:
- diagnostics.meethue.com
- ntp1.aliyun.com (and ntp2, ntp3, ntp4)
- www.baidu.com
- time4.google.com (maybe if others are not reachable as backup)
- www.signify.com
- www.philips-hue.com
- time.meethue.com
- www.edcinterface.philips.com

Looks like they‘re sending every button press on the light switches and much much more
