### ISSUE TITLE
Unblock IPFS gateways

### ISSUE THREAD

**Issue by AppleMayExist** [hagezi/dns-blocklists#2085]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

ipfs.runfission.com
ipfs.eth.aragon.network
ipfs.fleek.co
ipfs.scalaproject.io
cf-ipfs.com
4everland.io
dweb.link
w3s.link
gw3.io
nftstorage.link

### Why should the domain(s) be unblocked?

More public IPFS gateways

**Comment by hagezi** [comment]
This would add thousands of dangerous subdomains to the lists, which would make the lists extremely bloated. This is why the main domains are blocked, as in many other lists.

**Comment by AppleMayExist** [comment]
Okay, that makes sense. I do believe the official gateways block malicious content (citation needed) which these other ones might not, and you have unblocked one previously (#1687). However it would be nice if at least dweb.link could also be unblocked, as it is another official gateway and I would assume blocks malicious content as well.

**Comment by hagezi** [comment]
Yes @AppleMayExist, dweb.link will be removed.

**Comment by AppleMayExist** [comment]
Thank you.
