### ISSUE TITLE
Why are some domains of b-ite.com blocked in aggressive blockslists?

### ISSUE THREAD

**Issue by PythonGermany** [hagezi/dns-blocklists#2086]
In the [Ultimate](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/ultimate.txt) blocklist those three subdomains are blocked:
cs-assets.b-ite.com
jobs.b-ite.com
static.b-ite.com

In some other very strict like [1Hosts (Xtra)](https://o0.pages.dev/Xtra/domains.txt)  even more subdomains of it are blocked. What is the reason to block such a domain?

**Comment by hagezi** [comment]
@PythonGermany Source is 1Hosts. I don't see any real point in blocking either.

I will remove the domains.

**Comment by hagezi** [comment]
@PythonGermany removed.
