### ISSUE TITLE
app.hubspot.com

### ISSUE THREAD

**Issue by AidanGee7** [hagezi/dns-blocklists#2087]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

app.hubspot.com

### Why should the domain(s) be unblocked?

I know that HubSpot is a marketing/analytics company, but I'm pretty sure that the app.hubspot.com domain is just used for logging in/accessing the back-end of the platform and doesn't actually get used for any analytics or tracking.

E.g. Visiting https://app.hubspot.com/ will take you to the login page and once you login and use the back end it's all still under "app.hubspot.com".

When checking my DNS history, after 1+ month of browsing online, this domain only appeared today when I tried to login to HubSpot.

Completely up to you if you want to keep it blocked or not and I'll personally whitelist it - Just thought I'd raise it as someone who came across this blockage when trying to use HubSpot and using Multi PRO++.

Thank you!

**Comment by hagezi** [comment]
@AidanGee7 fixed.
