### ISSUE TITLE
Allowlist vsdb.top

### ISSUE THREAD

**Issue by adworacz** [hagezi/dns-blocklists#2088]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

vsdb.top

### Why should the domain(s) be unblocked?

https://vsdb.top/ is a useful reference site for video filters in the Vapoursynth video processing framework.

**Comment by hagezi** [comment]
@adworacz fixed.

**Comment by adworacz** [comment]
Thank you!
