### ISSUE TITLE
ARD images incorrectly blocked

### ISSUE THREAD

**Issue by hduelme** [hagezi/dns-blocklists#2089]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi LIGHT

### Which domain(s) should be unblocked?

image.ard.de

### Why should the domain(s) be unblocked?

The domain is used by the German public-service broadcaster ARD to provide images for there website and streaming services. Without the domain some images are not loading on their website.

**Comment by hagezi** [comment]
@hduelme This domain is not used to display images, it is a masked tracker.

Please post the link under which the images are not displayed.

**Comment by hduelme** [comment]
I agree. 
The requests look like site analytics (report information of the browser version, host system, etc)
Thanks for your work on this project.
