### ISSUE TITLE
*.netweather.accuweather.com

### ISSUE THREAD

**Issue by garfieldairlines** [hagezi/dns-blocklists#2090]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

blocky

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

*.netweather.accuweather.com

### Why should the domain(s) be unblocked?

Blocks the weather stats of Accuweather in the Android Nova Launcher. This is the only domain blocked in pro plus and not in pro.
Since switching lists solved the issue, I think this is the culprit.

**Comment by hagezi** [comment]
@garfieldairlines fixed.
