### ISSUE TITLE
house-fastly-signed-eu-west-1-prod.brightcovecdn.com

### ISSUE THREAD

**Issue by zmni** [hagezi/dns-blocklists#2091]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

house-fastly-signed-eu-west-1-prod.brightcovecdn.com

### Why should the domain(s) be unblocked?

Serve video streaming cdn for brightcove.

URL: https://www.mancity.com/citytv/mens/tottenham-hotspur-v-manchester-city-extended-highlights-63841895

I watched it from Indonesia. There is a possibility of being served from a different cdn domain if the video is watched from another country.

**Comment by hagezi** [comment]
@zmni fixed.
