### ISSUE TITLE
identity.mparticle.com [USA Networks]

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#2092]
This should probably not be allowed, but for those who might have issues with USA Network app, you need to allow this domain or else it will crash out at least on a Google TV device.

`identity.mparticle.com`

**Comment by hagezi** [comment]
Thanks, will be allowed for non-aggressive lists.

**Comment by jo2dan94** [comment]
@hagezi sorry to bother. i came across mparticle issue on amcplus.com today. should the whole domain be blocked in pro++? if yes sorry for bothering. the issue stems from identity.mparticle.com if you need to know.

**Comment by hagezi** [comment]
Only blocked in ultimate.
