### ISSUE TITLE
jsDelivr CDN mirror

### ISSUE THREAD

**Issue by piquark6046** [hagezi/dns-blocklists#2097]
I think that you can use the jsDelivr CDN by submitting a request about increasing file size limit in https://github.com/jsdelivr/jsdelivr/issues.
Also, I think that you don't have to clear GitHub commit history because you can set a GitHub workflow file and GitHub upgraded their free runner for a public repo:
 - https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
 - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Comment by piquark6046** [comment]
GitHub uses AMD EPYC 7763 64-Core Processor as a vCPU of the free runner.

**Comment by hagezi** [comment]
Thanks @piquark6046, I'll take a look when I have time.

**Comment by piquark6046** [comment]
Please note that you need https://github.com/List-KR/semver-release.

**Comment by hagezi** [comment]
added jsDelivr mirror

**Comment by piquark6046** [comment]
I don't think that you use main branch. When you request a cached file with the main branch, you may receive a file that is not purged if you use https://github.com/List-KR/jsdelivr-purge.

**Comment by piquark6046** [comment]
I recommend that you use https://github.com/List-KR/jsdelivr-purge and https://github.com/List-KR/semver-release.

**Comment by hagezi** [comment]
added jsdelivr-purge in  https://github.com/hagezi/dns-blocklists/commit/f4bbddfd99aabb53add1530b72b70a07d8faa8c5

**Comment by piquark6046** [comment]
Opened a PR.

**Comment by hagezi** [comment]
Merged.

**Comment by piquark6046** [comment]
Also, please replace `@main` with `@latest` in README.md.

**Comment by piquark6046** [comment]
Hmm... There is an issue in the List-KR/jsdelivr-purge@5.3.0.
I will investigate it. Please disable the workflow until there is an update.

**Comment by hagezi** [comment]
> Also, please replace `@main` with `@latest` in README.md.

Fixed.

**Comment by hagezi** [comment]
Thanks, workflow is disabled.

**Comment by piquark6046** [comment]
@hagezi Can you delete the successful workflow run at https://github.com/hagezi/dns-blocklists/actions/workflows/purge.yml

**Comment by hagezi** [comment]
deleted an enabled.

**Comment by hagezi** [comment]
Thank you @piquark6046, works now.

**Comment by hagezi** [comment]
@piquark6046 The jsDelivr links do not seem to provide the current version, see:

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.plus.txt
`# Last modified: 01 Feb 2024 02:01 UTC`

https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/pro.plus.txt
`# Last modified: 31 Jan 2024 02:30 UTC`

Can this be related to the Purge?
After the build there was a big push with all the changes.

**Comment by piquark6046** [comment]
Please upgrade semver-release from 3.1.0 to 3.1.1.

**Comment by hagezi** [comment]
@piquark6046 done

A question about the release via semver, is it possible to add a comment to a release?

It would be great to have a "Chaneglog" that contains all closed issues since the last release.

Thanks, "Workflow Noob" Gerd

**Comment by piquark6046** [comment]
> A question about the release via semver, is it possible to add a comment to a release?

Yes. If you can create manually.
But, it is impossible to add comments via semver-release because there are no features there.

**Comment by hagezi** [comment]
@piquark6046 https://github.com/hagezi/dns-blocklists/actions/runs/8075190771/job/22062357315

Can you please take a look at the error of the last release.

**Comment by piquark6046** [comment]
It seems that your commit ( https://github.com/hagezi/dns-blocklists/commit/5e6eea5082413a448fb0ac62a1287d5855d1bb89 ) causes the issue because the workflow run had not finished.

**Comment by hagezi** [comment]
@piquark6046 Yes, thanks, I had overlooked that I had merged a PR during the release, sorry.

**Comment by hagezi** [comment]
@piquark6046 https://github.com/hagezi/dns-blocklists/actions/runs/8106236083/job/22155875060
purge crashed in the last two runs ...

**Comment by hagezi** [comment]
> Did you delete a file?

Yes, some files.

**Comment by piquark6046** [comment]
@hagezi Please upgrade version of jsdelivr-purge to 5.6.0.

**Comment by hagezi** [comment]
Thanks ...

**Comment by piquark6046** [comment]
Did you want to run `workflowcleanup` job after `jsdelivrpurge` job in `.github/workflows/purge.yml`?

**Comment by hagezi** [comment]
Yes, is that a problem?

**Comment by hagezi** [comment]
Done, thanks.
