### ISSUE TITLE
api.teslacoilapps.com

### ISSUE THREAD

**Issue by garfieldairlines** [hagezi/dns-blocklists#2098]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

blocky

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

api.teslacoilapps.com

### Why should the domain(s) be unblocked?

After discussion with the Nova Launcher dev, it turns out the API call for the weather uses api.teslacoilapps.com, could you please allow it ?

Which means I was wrong on netweather.accuweather.com, it can be blocked again, my sincere apologies.

**Comment by hagezi** [comment]
Thanks @garfieldairlines, removed.
