### ISSUE TITLE
dnsmasq ultimate syntax fails

### ISSUE THREAD

**Issue by h1771t** [hagezi/dns-blocklists#2104]
Using this file:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/ultimate.txt

Putting it into /etc/dnsmasq.d/
restart dnsmasq fails.
" error at line 46477 of /etc/dnsmasq.d/ultimate.txt"

Seems dnsmasq does not like the line entries where there are double dashes? "--"
First line that it has an issue with looks like this:
> address=/d1--p1--cn-gotcha04.bilivideo.com/#

Files for pro.plus and pro also fail syntax, but multi works fine
dnsmasq version 2.85

**Comment by h1771t** [comment]
weirdly, at the top of the file I see entries like:
> address=/0--4.com/#
> address=/0--d.com/#

but dnsmasq doesn't flag those as an issue?

**Comment by h1771t** [comment]
multi loads fine and also has "--" entries in it, maybe something else dnsmasq does not like that I am missing.

**Comment by hagezi** [comment]
not allowed: `d1--p1--cn-gotcha04.bilivideo.com`
allowed: d--p--cn-gotcha04.bilivideo.com or d11--p1--cn-gotcha04.bilivideo.com

WTF?

**Comment by h1771t** [comment]
somehow d--p--cn-gotcha04.bilivideo.com is a valid IDNA2008 name it seems.

```
x:/tmp$ dig +short d--p--cn-gotcha04.bilivideo.com
x:/tmp$ dig +short d1--p1--cn-gotcha04.bilivideo.com
dig: 'd1--p1--cn-gotcha04.bilivideo.com' is not a legal IDNA2008 name (string contains forbidden two hyphens pattern), use +noidnin
```

**Comment by hagezi** [comment]
```
ultimate '^[a-z]{1}[0-9]{1}\-\-.*\-\-'

d1--p1--cn-gotcha04.bilivideo.com
d1--p2--cn-gotcha04.bilivideo.com
```

**Comment by h1771t** [comment]
Weird:
```

> x:~$ dig 'd1--p2--cn-gotcha04.bilivideo.com'
> dig: 'd1--p2--cn-gotcha04.bilivideo.com' is not a legal IDNA2008 name (string contains forbidden two hyphens pattern), use +noidnin
> x:~$ dig 'd1--p2--cn-gotcha04.bilivideo.com'
> dig: 'd1--p2--cn-gotcha04.bilivideo.com' is not a legal IDNA2008 name (string contains forbidden two hyphens pattern), use +noidnin
> x:~$ dig 'd1--p--cn-gotcha04.bilivideo.com'
> dig: 'd1--p--cn-gotcha04.bilivideo.com' is not a legal IDNA2008 name (string contains forbidden two hyphens pattern), use +noidnin
> x:~$ dig 'd--p2--cn-gotcha04.bilivideo.com'
> x:~$ dig +short 'd--p2--cn-gotcha04.bilivideo.com'
> x:~$ dig +short 'd11--p2--cn-gotcha04.bilivideo.com'

```

maybe the library that dnsmasq and dig uses to verify IDNA2008 is buggy?

**Comment by hagezi** [comment]
The pattern that does not work is a letter followed by a one-digit number and two hyphens, i.e. `d1--*` (regex: `^[a-z]{1}[0-9]{1}\-\-`)

**Comment by h1771t** [comment]
dig and probably dnsmasq too seems to be using this library for me at least:
https://gitlab.com/libidn/libidn2/-/blob/master/lib/idna.c?ref_type=heads#L159

**Comment by hagezi** [comment]
Entries from the Ultimate that cause problems:

```
cat </media/nas/git/dns-blocklists/domains/ultimate.txt | grep -Pv '^xn\-\-' | grep -P '^[a-z0-9]{2}[\-]{2}[a-z0-9]'

d1--p1--cn-gotcha04.bilivideo.com
d1--p2--cn-gotcha04.bilivideo.com
26--crwic.ifa.adx.com.ru
26--cyqal.ifa.adx.com.ru
ci--metrics.elifesciences.org
cs--33129-view-mail-ups.firebaseapp.com
hm--test2.vergic.com
cs--33129-view-mail-ups.web.app
```

**Comment by h1771t** [comment]
I guess the issue is then whatever generates the Ultimate dnsmasq file? If so, it also affects pro.plus and also pro too.

**Comment by hagezi** [comment]
@h1771t 

Maybe you should report this, it looks like a bug to me, doesn't it?

For compatibility reasons, I will remove the domains for now.

**Comment by h1771t** [comment]
A bug in the libidn library? Sorry I am not familiar with IDNA2008 at all. If so I will open a bug report there too.

**Comment by hagezi** [comment]
Wait, I'll check if I'm not talking garbage ;)

**Comment by hagezi** [comment]
@lynxthecat Can you say anything more about this?

**Comment by hagezi** [comment]
Example domain from Pro list:

cs--33129-view-mail-ups.web.app is valid!

```
dig cs--33129-view-mail-ups.web.app
dig: 'cs--33129-view-mail-ups.web.app' is not a legal IDNA2008 name (string contains forbidden two hyphens pattern), use +noidnin
```

```
dig cs--33129-view-mail-ups.web.app @8.8.8.8 +noidnin +noidnout

; <<>> DiG 9.16.44-Debian <<>> cs--33129-view-mail-ups.web.app @8.8.8.8 +noidnin +noidnout
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55962
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;cs--33129-view-mail-ups.web.app. IN    A

;; ANSWER SECTION:
cs--33129-view-mail-ups.web.app. 21600 IN A     199.36.158.100

;; Query time: 27 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jan 30 13:21:12 CET 2024
;; MSG SIZE  rcvd: 76
```

https://urlscan.io/result/e4f56107-7e5a-4a01-8da8-cec5770e3d54/

**Comment by hagezi** [comment]
@h1771t Have you tried the latest DNSmasq version?

**Comment by lynxthecat** [comment]
Nobody has reported any issues with PRO nor have I seen any issues. 

adblock-lean handles the latest ULTIMATE DNSmasq version just fine:

```
root@OpenWrt-1:~/adblock-lean# service adblock-lean start
Started adblock-lean.
No local blocklist identified.
Downloading new blocklist file part(s).
Downloading new blocklist file part from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/ultimate.txt.
Download of new blocklist file part from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/ultimate.txt suceeded (downloaded file size: 10967 KB).
Cleaning whitespace and formatting blocklist file part as local=/.../.
Successfully generated preprocessed blocklist file with 372058 line(s).
Processing and checking new blocklist file.
Preprocessed blocklist file size: 9877 KB.
Skippping removal of duplicates (only one blocklist URL specified).
No local allowlist identified.
Checking for any rogue elements.
Processed blocklist file size: 9877 KB.
Performing dnsmasq --test on the processed blocklist.
dnsmasq --test output: dnsmasq: syntax check OK.
The dnsmasq --test on the processed blocklist passed.
New blocklist file check passed.
Restarting dnsmasq.
Restart of dnsmasq completed.
Checking dnsmasq instance.
The dnsmasq check passed with new blocklist file.
New blocklist installed with good line count: 372058.
```

**Comment by lynxthecat** [comment]
```
root@OpenWrt-1:~# dnsmasq --version
Dnsmasq version 2.89  Copyright (c) 2000-2022 Simon Kelley
Compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack no-ipset nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
```

> Also there is a new list for DNSMasq v2.86 or newer. Starting with v2.86, using the format server=/example.com/ or address=/example.com/ will only block A queries and send other queries upstream. The format for v2.86 and newer should be local=/example.com/ which blocks all the queries for the domain.
> 
> More info: [https://thekelleys.org.uk/dnsmasq/CHANGELOG 4](https://thekelleys.org.uk/dnsmasq/CHANGELOG) and [https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html 2](https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) (-A, --address)

https://forum.openwrt.org/t/adblock-oisd-22-03-allows-you-to-use-huge-blocklists-with-dnsmasq/136413/221

**Comment by h1771t** [comment]
> @h1771t Have you tried the latest DNSmasq version?

no I did not, my setup is running on a rasp pi 2 with raspberry pi OS based off debian 10. My OS does not provide a newer dnsmasq for me unfortunately. I do plan to update that rasp pi to the newer raspberry pi OS at some point, maybe it has a newer dnsmasq.

**Comment by h1771t** [comment]
@lynxthecat what version of libidn does your setup run? And does dig <domain> using domains from earlier in this ticket, work? Dig showed me errors for a few domains, if those work for you, I probably need a newer libidn I think.

**Comment by h1771t** [comment]
Ah I see @lynxthecat dnsmasq version output is:
Compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack no-ipset nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile

and mine is:
Compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC loop-detect inotify dumpfile

So his has no-IDN but mine does not.

**Comment by hagezi** [comment]
@h1771t 

Yes, that explains the behavior. What I'm going to do now:

The current lists will be converted to the new format for v2.86+ (`local=`)

I will prepare lists in the old format (`server=`) for versions <=v2.85 and remove the corresponding IDN2 domains so that they are compatible.

This will take a moment as I have to customize the build system and do a full build.

**Comment by h1771t** [comment]
no problem thanks, I think I will open a ticket with libidn2 to ask them to comment too, thanks again.

**Comment by hagezi** [comment]
@h1771t 

Can you please test the following list and provide feedback:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/ultimate-old.txt

**Comment by h1771t** [comment]
> @h1771t
> 
> Can you please test the following list and provide feedback: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/ultimate-old.txt
> 
> And then please test this one, it contains `xn--` domains. https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/anti.piracy-old.txt

Both these pass syntax check with no problems.

**Comment by hagezi** [comment]
@h1771t 

Thanks, the other list versions will be delivered with the next full build, the readme will be adapted accordingly.

You can already use the Ultimate, the link above remains.

**Comment by hagezi** [comment]
The other list versions are now also available in the new IDN2 compatible format. The readme has been adapted.

**Comment by Wizballs** [comment]
Hey, I'm late to this party.  But that's great @hagezi formatting everything as local=/.../
This should save a small amount of processing time.  Thanks :)

**Comment by h1771t** [comment]
just as a comment, libidn2 was fine (not a bug in the lib)
https://gitlab.com/libidn/libidn2/-/issues/127
So adjusting the block list syntax for idn was the right thing here.
thank you.
