### ISSUE TITLE
store.nvidia.com

### ISSUE THREAD

**Issue by Silent-Remux** [hagezi/dns-blocklists#2108]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

I don't know but something is causing "access denied". Could be any of these:

smetrics.nvidia.com
munchkin.marketo.net
t.contentsquare.net
adobetarget.data.adobedc.net
nvidia.tt.omtrdc.net
156-ofn-742.mktoresp.com

You can browse the store for a bit but it kicks you out with access denied after a bit.

### Why should the domain(s) be unblocked?

Unable to shop on store.

**Comment by hagezi** [comment]
You mean store.nvidia.com? In which region? Please post the full link with region to the store.

Where is the problem occurring? Mobile or desktop website?

**Comment by Silent-Remux** [comment]
> You mean store.nvidia.com? In which region? Please post the full link with region to the store.
> 
> Where is the problem occurring? Mobile or desktop website?

store.nvidia.com, any region it seems, desktop site

**Comment by hagezi** [comment]
I clicked through the store for 15 minutes and cannot reproduce the problem.

**Comment by hagezi** [comment]
FYI: `adobetarget.data.adobedc.net` is not blocked in my lists.
