### ISSUE TITLE
Android Malware

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#2116]
### Which domain(s) should be blocked?

hello-chat-c47ad-default-rtdb.firebaseio.com
chit-chat-e9053-default-rtdb.firebaseio.com
meetme-abc03-default-rtdb.firebaseio.com
chatapp-6b96e-default-rtdb.firebaseio.com
tiktalk-2fc98-default-rtdb.firebaseio.com
wave-chat-e52fe-default-rtdb.firebaseio.com
privchat-6cc58-default-rtdb.firebaseio.com
glowchat-33103-default-rtdb.firebaseio.com
letschat-5d5e3-default-rtdb.firebaseio.com
quick-chat-1d242-default-rtdb.firebaseio.com
yooho-c3345-default-rtdb.firebaseio.com
rafaqat-d131f-default-rtdb.asia-southeast1.firebasedatabase.app

### Why should these domain(s) be blocked?

https://github.com/eset/malware-ioc/tree/master/vajraspy
and
https://www.welivesecurity.com/en/eset-research/vajraspy-patchwork-espionage-apps

**Comment by hagezi** [comment]
Already blocked in TIF.

**Comment by hagezi** [comment]
No Problem.
