### ISSUE TITLE
Major consent managers are blocked

### ISSUE THREAD

**Issue by rowboatz** [hagezi/dns-blocklists#2123]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

api.axept.io
cdn-cookieyes.com
consent.cookiebot.com
cookiehub.com
cookiehub.eu
cookiehub.net
cookieyes.com
consentframework.com
fastcmp.com
gatekeeperconsent.com
uniconsent.com

### Why should the domain(s) be unblocked?

In my view it is important to be able to express consent and make conscious choices. These entries in your lists belong to major consent managers used across many websites and blocking them prevents consent dialogs from appearing. Some of these entries are present all the way down to Light. Some of their subdomains could possibly remain blocked, but more research is needed in order to know which ones. See also this related issue and comment about the risks of blocking CMPs: https://github.com/hagezi/dns-blocklists/issues/1979#issuecomment-1870498567

Thank you for your dedication to this project!

**Comment by hagezi** [comment]
@rowboatz Yes, I agree, those are probably the ones I overlooked. Thanks for that, will be removed in the next update.

**Comment by hagezi** [comment]
@rowboatz Will be removed:

```
api.axept.io
cdn-cookieyes.com
consentframework.com
api.consentframework.com
cache.consentframework.com
cdn.consentframework.com
choices.consentframework.com
ui.consentframework.com
consent.cookiebot.com
cookiehub.com
cookiehub.eu
cookiehub.net
cdn.cookiehub.eu
cdn-kcu2.cookiehub.eu
consent.cookiehub.eu
consent.cookiehub.net
consent-eu.cookiehub.net
ds.cookiehub.net
geo.cookiehub.net
region-eu.cookiehub.net
static.cookiehub.com
cookieyes.com
app.cookieyes.com
directory.cookieyes.com
geoip.cookieyes.com
ptr6221.cookieyes.com
fastcmp.com
eu.fastcmp.com
static.fastcmp.com
gatekeeperconsent.com
gvl.gatekeeperconsent.com
privacy.gatekeeperconsent.com
the.gatekeeperconsent.com
uniconsent.com
api.uniconsent.com
app.uniconsent.com
cmp.uniconsent.com
connect.uniconsent.com
edge.uniconsent.com
```

If you find more, simply open an issue.
