### ISSUE TITLE
Why is userlocation.googleapis.com not blocked?

### ISSUE THREAD

**Issue by Alex67693** [hagezi/dns-blocklists#2125]
### Which domain(s) should be blocked?

userlocation.googleapis.com

### Why should these domain(s) be blocked?

It sends your location to Google but doesn't break Google Maps.

**Comment by hagezi** [comment]
Hi @Alex67693, it didn't take long for the first person to get in touch. The domain was blocked in the Ultimate, so there were discussions in my Telegram group. One of the things that came out of the discussion was that this domain needs to be unblocked to determine a more precise position, e.g. if you make an emergency call and transmit your position in the process. This was the main reason for me to unblock the domain again.

**Comment by Alex67693** [comment]
Ok, thanks
