### ISSUE TITLE
Cookiehost not blocked 

### ISSUE THREAD

**Issue by Alex67693** [hagezi/dns-blocklists#2126]
### Which domain(s) should be blocked?

Hi, can cdn.cookielaw.org be blocked? 

### Why should these domain(s) be blocked?

It's a cookie request.

**Comment by hagezi** [comment]
@Alex67693, blocking CMPs via DNS (network wide) breaks a lot of things and takes away the user's freedom to decide what he wants to allow and what not. Blocking is reserved for content blockers with corresponding filter lists. These can be used to decide which sites are excluded from CMP domains and which are not. You only have to look at the exclusions in the cookie filter lists to see why blocking with DNS is not a good idea.

See: https://github.com/hagezi/dns-blocklists/issues/1979#issuecomment-1870498567 from @rowboatz

If you want to block this via DNS, then use your personal denylist or use a list that blocks CMPs, such as 1Hosts Pro.
