### ISSUE TITLE
tr.apsis.one Whitelist refferal addition

### ISSUE THREAD

**Issue by BourbonCrow** [hagezi/dns-blocklists#2127]
tr.apsis.one this domain is used to unsubscribe to emails i dont know if its used for anything else but looking at their site apsis.one it loosk like they just have this where they send out emails / sms on companys behalf for advertising. you can look into it yourself, but it might be an addition to your whitelist refferal list

**Comment by BourbonCrow** [comment]
I'm sorry but there seems to be 1 more step to it all once i allowed tr.apsis.one and clicking the unsub link it redirected me from tr.apsis.one/unsub/ to uns.apsis.one/usub/ for unsubbing so i guess they both need to be allowed idk why they would do that, but i guess the tr tracks the click and the uns usubs you, weird to not have both in same but it is what it is

**Comment by hagezi** [comment]
Thanks @BourbonCrow, will be fixed.
