### ISSUE TITLE
Blocklist additions? 

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#2128]
### Which domain(s) should be blocked?

better-replay.com
replayapp.io

### Why should these domain(s) be blocked?

Hello, Gerd!

I hope you're well. I've been tidying up my personal black/white lists while migrating some of my systems to Blocky from AGH, and came across these two domains that don't seem to be on your lists. They are screen recording / replay companies who transmit user activity (what you touch, links you click, how long you look at items etc) in apps and on websites. I have had them blocked for a long time, with no ill effect. Perhaps consider them for addition to your lists? 

Best wishes, 

Lee

**Comment by hagezi** [comment]
Thanks Lee, will be added.

**Comment by RainmakerRaw** [comment]
Thanks Gerd / @hagezi ! Just one more, sorry - it slipped my net when I posted the issue. Pointless opening a whole new issue for a single domain (unless you prefer?). 

`covatic.com`

is not currently blocked, but `covatic.io` is. It's just two domains for the same company. Can we please add the `.com` also, or perhaps just change to something like `*covatic.*`? Thank you as always!

**Comment by hagezi** [comment]
No problem Lee, will be added.
