### ISSUE TITLE
Robux gambling websites

### ISSUE THREAD

**Issue by shayrbx** [hagezi/dns-blocklists#2131]
### Which domain(s) should be blocked?

bloxflip.com
rblxwild.com
bloxmoon.com
rbxgold.com
bloxempire.com
rblxroll.com

### Why should these domain(s) be blocked?

These websites are all gambling websites focused around a children's game.
Note some of these were bought out by bloxmoon, but the domains still exist.

**Comment by shayrbx** [comment]
While we're at it, here's even more domains
```
tf2easy.com
tf2cases.com
tf2hunt.com
tf2.bet
runestake.com
500.casino
xcsgofast.com
plgrubet.com
csgost.run
hellstore.me
cs.fail
wtfskins.com
godota2.com
csgopositive.com
skin.fans
d2exp.net
dotaclash.com
d2ggdrop.net
rustcasino.com
rustchance.com
rustyrocket.gg
```

**Comment by hagezi** [comment]
Thanks @shayrbx, will be added.
