### ISSUE TITLE
RedCurl

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#2134]
### Which domain(s) should be blocked?

app-l07.servicehost.click
clever.forcloudnetworks.online
app-l07.servicehost.click
app-l07.servicehost.click
fiona.forcloudnetworks.online

### Why should these domain(s) be blocked?

https://www.facct.ru/blog/redcurl-2024/

https://www.virustotal.com/gui/url/d4933863faec71b7093d42f3d7b56a890e79c25306865dae1ecad3d4c98914f0?nocache=1
https://www.virustotal.com/gui/url/90e5f314e6973a53dcbe8dfcc44e18432ad8fff735052576db05c981f9d0e4e3?nocache=1

**Comment by hagezi** [comment]
`forcloudnetworks.online` NXDOMAIN
`servicehost.click` NXDOMAIN
