### ISSUE TITLE
alidns doh/dot

### ISSUE THREAD

**Issue by alsyundawy** [hagezi/dns-blocklists#2137]
### Which domain(s) should be blocked?

*.alidns.com
public2.alidns.com
public.alidns.com
doh.alidns.com
alidns.com
public2.alidns.com
public99.alidns.com
public254.alidns.com
doh.alidns.com
doh1.alidns.com

### Why should these domain(s) be blocked?

wildcard domain

they have ip 223.6.6.0/24 & 223.5.5.0/24 with random sub domain

**Comment by alsyundawy** [comment]
not solve, i mean all subdomain of alidns can be add to list

like whatever.alidns.com & all subdomain.alidns.com

they have ip 223.6.6.0/24 & 223.5.5.0/24 with random sub domain

**Comment by hagezi** [comment]
What should I add, see:

https://bgp.he.net/net/223.6.6.0/24#_dnsrecords
https://bgp.he.net/net/223.5.5.0/24#_dnsrecords

**Comment by hagezi** [comment]
https://www.alibabacloud.com/help/en/alibaba-cloud-public-dns/latest/dns-over-https

It is impossible to block all possible UserIDs, use an adblocker that supports wildcard blocking.
