### ISSUE TITLE
False positive: trezor.io

### ISSUE THREAD

**Issue by Krizzii** [hagezi/dns-blocklists#214]
Why would this get blocked? Please unblock.

**Comment by hagezi** [comment]
Thanks, removed. Was marked as Cryptoscam.

ping sources: @notracking @kevinthomas0 @laniksj @shadowwhisperer @adguardteam (french filter) @easylist (listefr)

**Comment by ShadowWhisperer** [comment]
My Cryptocurrency list is just a list of cryptocurrency sites. Not to be used as a malware list.

`Cryptocurrency   Bitcoin, Ethereum, Mining, etc. (Not malware, but could be used by it) `

**Comment by hagezi** [comment]
@ShadowWhisperer Thank you, I already thought of something like that.

**Comment by notracking** [comment]
Thanks!. It's on easylist and adguards list, fixed!

**Comment by LanikSJ** [comment]
Removed.

CC: @smed79 for ListeFR
