### ISSUE TITLE
www.beliefnet.com

### ISSUE THREAD

**Issue by onmyouji** [hagezi/dns-blocklists#2143]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

beliefnet.com

### Why should the domain(s) be unblocked?

According to wikipedia (https://en.wikipedia.org/wiki/Beliefnet), it is some kind of a Christian spiritual website.

I am not Christian and I understand that some people might not agree with some of their views (including myself), but I think this blocklist should not engage in censorship.

**Comment by hagezi** [comment]
Via Stopforumspam list.
