### ISSUE TITLE
ettoday api

### ISSUE THREAD

**Issue by Arden-Cho** [hagezi/dns-blocklists#2145]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

api.ettoday.net

### Why should the domain(s) be unblocked?

It breaks the ettoday mobile app.

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by Arden-Cho** [comment]
Excellent, thanks.
