### ISSUE TITLE
Unblock pegelinux.top

### ISSUE THREAD

**Issue by rezhajulio** [hagezi/dns-blocklists#2146]
### Which AdBlocker/DNS cloud service do you use?

AdGuard, AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

*.pegelinux.top
pegelinux.top

### Why should the domain(s) be unblocked?

This is the domain of our Mastodon instance. We are just a small Linux community and self-host several services.

**Comment by rezhajulio** [comment]
Thank you!

**Comment by hagezi** [comment]
@rezhajulio Fix was not in the last update, my mistake, will be fixed in the next update, sorry.

**Comment by rezhajulio** [comment]
@hagezi No worries, thanks for letting me know.

**Comment by hagezi** [comment]
@rezhajulio fixed. ;)

**Comment by xRuffKez** [comment]
Still blocked in TIF @hagezi

**Comment by hagezi** [comment]
Thanks for the tip, I hadn't even looked at the TIF. It will be removed with the next update.

**Comment by iam-py-test** [comment]
>  I think from Dandelion Malware List.

I have allowlisted your website in https://github.com/DandelionSprout/adfilt/commit/487d1fb10459184579d1a3897a19283bfe4616ed.
Thank you.
