### ISSUE TITLE
torrent trackers

### ISSUE THREAD

**Issue by rugabunda** [hagezi/dns-blocklists#2148]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

dnsmasq new

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

9.rarbg.com
10.rarbg.com
11.rarbg.com
tracker.pomf.se
tracker.tallpenguin.org

### Why should the domain(s) be unblocked?

These are all torrent trackers

**Comment by rugabunda** [comment]
Ok, seems diversion ad blocker is blocking all kinds of stuff it shouldn't; may be an isolated issue with my device, but no harm done, these are all legit torrent trackers

**Comment by hagezi** [comment]
@rugabunda Thanks anyway, I found some on the Ultimate.
