### ISSUE TITLE
a7.org is connected to news site israelnationalnews.com

### ISSUE THREAD

**Issue by katchy3132** [hagezi/dns-blocklists#2149]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

www.a7.org
a7.org

### Why should the domain(s) be unblocked?

its an associated domain for the news site israelnationalnews.com
blocking the domain breaks the images for the news articles. 

![image](https://github.com/hagezi/dns-blocklists/assets/3707138/e184a0b3-f676-4012-a5c1-9f8d91b38daf)
![image](https://github.com/hagezi/dns-blocklists/assets/3707138/10204fc7-8c75-4a48-becc-d583d99470e2)

**Comment by hagezi** [comment]
Thanks @katchy3132, will be removed on next update. I am currently making a few adjustments to the aggressive lists and will then also remove the domain from all lists.

**Comment by hagezi** [comment]
@katchy3132 fixed.
