### ISSUE TITLE
Torrent Tracker

### ISSUE THREAD

**Issue by rugabunda** [hagezi/dns-blocklists#2150]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Dnsmasq NEW

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

tracker.zond.org

### Why should the domain(s) be unblocked?

its a torrent tracker

**Comment by hagezi** [comment]
Thanks, will be removed.
