### ISSUE TITLE
Blocked cwwk.net

### ISSUE THREAD

**Issue by JGeek00** [hagezi/dns-blocklists#2152]
I just wanted to ask why cwwk.net is blocked on the following blocklist. It seems to be the legit store from the cwwk mini PCs brand.

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/fake.txt

**Comment by hagezi** [comment]
Thanks @JGeek00m the domain was categorised as a fake shop by Watchlist Internet, and after a check under https://www.verbraucherzentrale.nrw/fakeshopfinder-71560 is also identified as a fake shop.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/fae02ae2-2ae9-414b-beb7-43ddfe1d201e)

I'll check this in more detail.

**Comment by hagezi** [comment]
https://www.watchlist-internet.at/liste-betruegerischer-shops/shop/cwwknet/

**Comment by hagezi** [comment]
However, it appears to be the manufacturer's website. I will unblock the domain.
