### ISSUE TITLE
Add konspiratori.sk block list to fake news

### ISSUE THREAD

**Issue by pduchnovsky** [hagezi/dns-blocklists#2153]
### Which domain(s) should be blocked?

https://github.com/pduchnovsky/konspiratori-sk-blocklist/blob/main/konspiratori-sk-filter.txt

### Why should these domain(s) be blocked?

I've created this repo https://github.com/pduchnovsky/konspiratori-sk-blocklist  
that provides updated filter list from the site  
https://konspiratori.sk/dovod-vzniku/en - which explains what's behind this intiative

Would appreciate if it would be possible to include this in your fake news domains list.

**Comment by hagezi** [comment]
Thanks @pduchnovsky, but the fake list does not contain any "fake news" domains. The description of the list is still incorrect. I will adjust this. I removed such domains at the time after receiving various notices, because this is mostly censorship.

**Comment by pduchnovsky** [comment]
I understand and it is up to you to decide however, one could argue that any blocklist could be then considered censorship, since it fits the description.

People wrongly assume that any censorship is wrong or bad, which is plain wrong assumption. We all use these blocklists to protect family and friends from false information, which in this age is very important and governments do close to nothing to address this situation unfortunately. 

If any censorship is bad then there is an argument that the same can be said about trying to protect children and not allowing them to watch certain movies or tv series, because they are not old enough.

**Comment by hagezi** [comment]
@pduchnovsky Yes, I understand your point of view and see it similarly.

I'll add your list to the aggressive lists (Pro++, Ultimate) and then we'll see.

**Comment by pduchnovsky** [comment]
@hagezi just want to follow up, was it already included ? Because I don't see the domains in Pro++ list which I use as well :)

**Comment by hagezi** [comment]
@pduchnovsky 

Yes, I have added them to the Fake++, this list is included in the Pro++ and Ultimate. The Fake and TIF lists are checked against the Umbrella/Chrome Top 1 million list. Domains that are on this list are very popular and not malicious, so the domains are removed.

The following domains have been removed from my build system:

**_Reason:_ The domains are on the top 1 million list**
```
ac24.cz
aeronet.news
armadnymagazin.sk
autoforum.cz
babickinerady.sk
badatel.net
breitbart.com
bystricoviny.sk
casopisargument.cz
cestyksobe.cz
christianitas.sk
cz24.news
czechfreepress.cz
domacaliecba.sk
dracik.cz
dracik.sk
ereport.sk
extraplus.sk
gloria.tv
hlavnespravy.sk
hlavnydennik.sk
infokuryr.cz
infovojna.bz
knihya.cz
naturalnews.com
necenzurovanapravda.cz
noveslovo.eu
otevrisvoumysl.cz
paralelne.cz
plenum.sk
pokec24.cz
pravdive.eu
protiproud.info
prvnizpravy.cz
radiouniversum.cz
sk.news-front.su
slobodnyvysielac.sk
slovanskenoviny.sk
slovenskydohovorzarodinu.sk
southfront.org
standard.sk
svobodny-vysilac.cz
tadesco.org
theepochtimes.com
veci-verejne.sk
vigilantcitizen.com
vitazstvosvetla.org
zemavek.sk
zenskerady.sk
zvedavec.news
```

**_Reason:_ Domain does not resolve, dead (`NXDOMAIN`/`SERVFAIL`)**
```
archa21.sk
desitka.org
euportal.cz
euronoviny.eu
ezopress.sk
faktyadokazy.cc
freepub.cz
legalizuj.to
nadlani.org
nejhorsi.cz
obcansky-tydenik.cz
onlineslecna.sk
ozonyx.cz
parlamentne-volby-2016.sk
planetajednoduchost.sk
prekladyodlesa.sk
qanon.sk
radyzdravie.sk
rozhladna.org
rtps.sk
sk.news-front.info
sknews.sk
slovinfos.sk
stopislam.eu
stratenaeuropa.sk
svobodnymonitor.cz
trendweb.sk
venuska.cz
voxpopuliblog.cz
weeks.cz
withform.cz
zahadnysvet.sk
zlapanda.cz
```

**Comment by pduchnovsky** [comment]
@hagezi they could be on top 1 million but they just spread misinformation.
There is exhausting evidence near each of those blocked sites on konspiratori.sk

But I understand none of your lists are specifically designated to block misinformation so I take it.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2204
