### ISSUE TITLE
Images are not displayed on dcinside due to dcinside.co.kr blocking.

### ISSUE THREAD

**Issue by Githubmaniak** [hagezi/dns-blocklists#2155]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

dcinside.co.kr

### Why should the domain(s) be unblocked?

![Screenshot_20240214-002647](https://github.com/hagezi/dns-blocklists/assets/103377449/30bb4b3d-74ae-4748-9e38-7d3aca844080)
![Screenshot_20240214-002702](https://github.com/hagezi/dns-blocklists/assets/103377449/8984fa7f-5283-4dd6-9f6c-25f4d3f7a85f)

If you block dcinside.co.kr, the images will not display on dcinside, but if you unblock them, the images will display normally.

**Comment by hagezi** [comment]
Thanks @Githubmaniak, but I can't find `dcinside.co.kr` on the current list version.

**Comment by hagezi** [comment]
@Githubmaniak I think you mean `dccdn11.dcinside.co.kr` (blocked by CNAME `dccdn11.dcinside.co.kr.bplslb.com`)?

**Comment by hagezi** [comment]
Will be removed.
