### ISSUE TITLE
VPN PROXY TOR SITES

### ISSUE THREAD

**Issue by supspaceyt** [hagezi/dns-blocklists#2159]
### Which domain(s) should be blocked?

https://gointerstellar.app/ 
https://ios.4webhelp.ca/
https://environmental.laws.tibetjustice.org/
https://mystic.xyz.moochurch.com/
https://database.development.sanluix.org/
https://tysonsbackagain.capnorthshore.org/
https://quantum.xyz.moochurch.com/
https://store.hkordermedicine.hk/
https://stats.volkszaehler.org/
https://h2o.lakeballs.fi/
https://sunset.sun.2of1.org/
https://e.t.texasmath.org/
https://xp.x14n.org/
https://lambda.y.glenwaverleychurches.org/
https://photography.backriverphotography.com/
https://support.cloud.rigaprecast.com/
https://x.j0.icom.org.np/
https://mystic.xyz.moochurch.com/
https://snapshot.photography.backriverphotography.com/
https://stats.volkszaehler.org/
https://forum.cloud.rigaprecast.com/
https://sunrise.sun.2of1.org/
https://skillset.photography.backriverphotography.com/
https://snap.photography.backriverphotography.com/
https://pixels.photography.backriverphotography.com/
https://creativity.photography.backriverphotography.com/
https://o.h4xxel.org/
https://j.kayru.org/
https://delta.y.glenwaverleychurches.org/
https://a.virg0.org/
https://x.n.dnsmirror.org/
https://x.a.ubiq.org/
https://angle.photography.backriverphotography.com/
https://capturelife.photography.backriverphotography.com/
https://i.a.ubiq.org/
https://s.j0.icom.org.np/
https://x.o.h4xxel.org/
https://k.c.gracemp.org/
https://test.sun.2of1.org/
https://frontend.development.sanluix.org/
https://w.q.sagesinst.org/
https://sundown.sun.mountofoliveschurch.com/
https://sunflower.sun.mountofoliveschurch.com/
https://alpha.y.glenwaverleychurches.org/
https://w.n.dnsmirror.org/
https://r.j0.icom.org.np/
https://vp.c.gracemp.org/
https://experiment.photography.backriverphotography.com/
https://n.c.gracemp.org/
https://vision.photography.backriverphotography.com/
https://sunrays.sun.mountofoliveschurch.com/
https://luminous.xyz.moochurch.com/
https://focus.photography.backriverphotography.com/
https://demo.cloud.rigaprecast.com/
https://techniques.photography.backriverphotography.com/
https://visuals.photography.backriverphotography.com/
https://backend.development.sanluix.org/
https://c.gracemp.org/
https://docs.cloud.rigaprecast.com/
https://mobile.development.sanluix.org/
https://x4.o.h4xxel.org/
https://lighting.photography.backriverphotography.com/
https://pose.photography.backriverphotography.com/
https://w.t.texasmath.org/
https://shop.twinslist.org/
https://sunflower.sun.2of1.org/
https://b.j0.icom.org.np/
https://innovation.photography.backriverphotography.com/
https://e.adamandandrea.org/
https://farms.stentwood.com.au/
https://database.development.sanluix.org/
https://aurora.xyz.moochurch.com/
https://environmental.laws.tibetjustice.org/
https://shutter.photography.backriverphotography.com/
https://j.o.h4xxel.org/
https://lol.sanluix.org/
https://1.belizebuilders.com/
https://x.a.virg0.org/
https://edu.photography.backriverphotography.com/
https://learn.photography.backriverphotography.com/
https://jubilee.xyz.moochurch.com/
https://app.cloud.rigaprecast.com/
https://beta.y.glenwaverleychurches.org/
https://tutorial.photography.backriverphotography.com/
https://blog.cloud.rigaprecast.com/
https://insight.photography.backriverphotography.com/
https://storytelling.photography.backriverphotography.com/
https://tools.development.sanluix.org/
https://n.dnsmirror.org/
https://kappa.y.glenwaverleychurches.org/
https://epsilon.y.glenwaverleychurches.org/
https://perspective.photography.backriverphotography.com/
https://z.d.2of1.org/
https://exposure.photography.backriverphotography.com/
https://craft.photography.backriverphotography.com/
https://sundown.sun.2of1.org/
https://professional.photography.backriverphotography.com/
https://dove.soapagent.com/
https://dove.soapclient.com/
https://frysprinters.com/
https://us1.cambrianscientific.com/
https://s1.hancockcountyfoodpantry.com/
https://ocean.lakeballs.fi/
https://api.cloud.rigaprecast.com/
https://forum.cloud.rigaprecast.com/
https://alpha.y.glenwaverleychurches.org/
https://beta.y.glenwaverleychurches.org/
https://gravity.omniscien.cl/
https://youth.prosports.cl/
https://meteor.newsofmaricopa.com/
https://spacial-awareness.potomacriversafetycommittee.org/
https://workshop.precisewarehousing.com/
https://cultures.linexedu.eu/
https://t.lifestylethailand.com/
https://acetaminophen.deleesportsmedicine.com/
https://einstein.lawson-engineers.co.uk/
https://schoolmath.hop.sh/
https://antihistamines.medscience.cl/
https://gravity.sciencevictory.org/
https://edpuzzle.videospeed.cl/
https://login.thegalleryofart.info/
https://roundrockisd.online/
https://nationalgeographic.wiki/
https://adsadkjsadjksakldjxx.math-solver.online/

https://ixl.plus/  
https://mangoai.artclass.site/ 
https://buythe.cybertruck.design/  
https://sutausfjsajfas.englishpapers.online/ 
https://edit.commanders.design/  
https://sail.msg.boats/  
https://thiscopyofartclassisnotgenuine.rare1k.space/  
https://parrotballs.worksheetsforteachers.xyz/  
https://mathnotes.icu/  
https://123.mathlearning.tech/   
https://chat.mathhelpnow.site/  
https://hejustfarted.artclass.lol/  
https://ihavekidsinmybasement.mathlearning.tech/  
https://smellyal.isreally.pro/  
https://testing.sciencesimplified.pro/  
https://purchase-some.hotglue.click/  
https://todo.mathnotes.help/  
https://edpuzzle-lol.vercel.app/  
https://school-ilove.vercel.app/  
https://asdsasd.vercel.app/ 
https://art-class-omg.vercel.app/  
https://clase-de-arte.vercel.app/  
https://vercel-is-cool.vercel.app/   
https://shop-books-school.vercel.app/ 
https://parrotballs.worksheetsforteachers.xyz/ 
https://ilovemrmorris-ggnewo.vercel.app/ 
https://ifyoublockthisurgay-ggnewo.vercel.app/ 
https://learn.mathnotes.help/  
https://mathnotes.help/  
https://monkeytype.sciencesimplified.pro/  
https://wildcardsareepic.mathlearning.tech/  
https://stufy.englishpapers.online/  
https://stuffyschicken.isreallycool.lol/  
https://smellypay.isreally.pro/  
https://math.isreally.pro/  
https://study.englishpapers.online/  
https://artclass.site/  
https://subscribe.artclass.site/  
https://artclass.lol/  
https://www.sciencesimplified.pro/  
https://www.mathhelpnow.site/  
https://www.mathlearning.tech/  
https://my.worksheetsforteachers.org/  
https://tethers.wiki/  
https://presidentalhistory.wiki/  
https://my.englishpapers.online/  
https://login.readinghelper.online/  
https://cranking90s.fortnitebuilder.pro/

### Why should these domain(s) be blocked?

School Proxy Sites use to bypass.

**Comment by hagezi** [comment]
Thanks @supspaceyt, what is the source?

**Comment by supspaceyt** [comment]
https://docs.google.com/document/d/1nK6tJb-sxfrrQJM9bSWcAV-Fo7jHasd_dWpj4VEVg5E/edit Google Document
