### ISSUE TITLE
Block Request for DoH/VPN/TOR/Proxy Bypass List (Part #2)

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#216]
Hello.

Want to add this to your blocklist. Many of them are of the same category as before.

https://masterssh.com/
https://sshcdn.com/
https://sharevpn.org/
https://www.sshprotocol.net/
https://starssh.com/
https://dewassh.net/
https://indo-ssh.com/
https://www.portalssh.com/
https://contassh.com/
https://herbalserver.me/
https://akunssh.net/
https://www.racevpn.com/
https://vpnhack.com/
https://opentunnel.net/
https://www.freevmess.com/
https://sshmax.net
https://openvpn-ssh.com/
https://turbossh.com/
https://monthlyssh.net/
https://bestssh.net/
https://jupitervpn.ninja/
https://createssh.net/
https://serverhoya.com/
https://getoutline.org/
https://gamingssh.com/
https://bebasid.com/
https://premiumproxy.net/
https://spys.one/
https://squidproxyserver.com/
https://gatcha.org/ <- affiliate with fastssh.com, provide illegal internet access and bypassing internet firewall tutorials.

**Comment by hagezi** [comment]
Thanks for your support! Added.
