### ISSUE TITLE
Content incorrectly blocked at www.femmeactuelle.fr

### ISSUE THREAD

**Issue by arturstat** [hagezi/dns-blocklists#2161]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

Unable to determine.

### Why should the domain(s) be unblocked?

Content is incorrectly blocked at:

https://www.femmeactuelle.fr/sante/news-sante/longevite-cette-boisson-a-prendre-au-petit-dejeuner-reduirait-le-vieillissement-biologique-2169759

The content is visible when Multi NORMAL is removed from NextDNS.
Also see: https://github.com/AdguardTeam/AdguardFilters/issues/171637

Thank you!

**Comment by hagezi** [comment]
The site is pure ads and tracking hell. I did not manage to display the podcast player. It looks like you have to unblock all ads for the podcast player to load. With every unblock new blocked domains appear in the log. The absolute plague.

**Comment by hagezi** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/171637#issuecomment-1949151850

**Comment by xRuffKez** [comment]
You should unblock
```
securepubads.g.doubleclick.net
```
to make the Podcast load.

The Podcast Scripts are hidden behind an element of securepubads domain.

You might allow only for specific clients to load the domain, if you don't want to see Google ads on your entire network.

**Comment by hagezi** [comment]
Many thanks for your support. Unblocking is definitely something for the personal allow list.
