### ISSUE TITLE
Allowlist - pam.mail.orange.fr

### ISSUE THREAD

**Issue by MaximeSharp** [hagezi/dns-blocklists#2162]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

pam.mail.orange.fr

### Why should the domain(s) be unblocked?

Orange Mail can't sync new mails and report a network error if this domain is blocked.
Adding it to the allowlist fix the issue.

**Comment by hagezi** [comment]
Thanks @MaximeSharp, blocked by CNAME `pamela.gslb.fti.net`. Will be removed on next update.
