### ISSUE TITLE
freedomofinformationlibrary.com

### ISSUE THREAD

**Issue by rugabunda** [hagezi/dns-blocklists#2163]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Dnsmasq New

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO, Multi PRO++

### Which domain(s) should be unblocked?

freedomofinformationlibrary.com

### Why should the domain(s) be unblocked?

Legit, Freedom of information library of Canada.

**Comment by rugabunda** [comment]
its also on the adblock pro/plus list as well

**Comment by hagezi** [comment]
Thanks, will be removed on next update.
