### ISSUE TITLE
YouTube blocked in IPS-list

### ISSUE THREAD

**Issue by iJorgen** [hagezi/dns-blocklists#2164]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

142.250.74.14
142.250.74.78

### Why should the domain(s) be unblocked?

Youtube don't work for me and noticed these blocked IP's in the firewall.

When doing a "dig" I get this, so guess YouTube uses the whole 142.250.74.0/24 subnet.
youtube.com.		295	IN	A	142.250.74.174

**Comment by hagezi** [comment]
Had added an IP source yesterday, it doesn't seem to be clean, will remove it again.

**Comment by hagezi** [comment]
fixed.
