### ISSUE TITLE
Unblock jx3hwhk-homeland

### ISSUE THREAD

**Issue by a77841s** [hagezi/dns-blocklists#2168]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL, Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

jx3hwhk-homeland.obs.ap-southeast-1.myhuaweicloud.com

### Why should the domain(s) be unblocked?

game url

**Comment by hagezi** [comment]
Thanks, will be removed on next update.
