### ISSUE TITLE
Adding threat-list.com in TIF Blocklist

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#217]
Hello.

Could you consider adding this blocklist to your TIF blocklist? I didn't find this list in your TIF blocklist source, or i missed it?

Link : https://threat-list.com

**Comment by hagezi** [comment]
Hi,

I had already looked at this list, where various lists are consolidated.
The list contained a lot of dead domains, domains that have no business on a TIF list and many positive domains.

The result of the analysis was the following:
https://github.com/hagezi/dns-blocklists/issues/181

Probably these lists are used as sources.

**Comment by hagezi** [comment]
@MagicalAlchemist 
I ran the list through my build system again, it still looks the same as it did back then and needs some work to make it fit. From my point of view it does not add any value to the TIF.

The result actually reflects the result of the analysis of the Blocklist Project lists.

**Comment by MagicalAlchemist** [comment]
I have no idea about his blocklist contains false positive or dead domains because I don't have a tool to check the domain is dead or false positive. 

But thanks for double checking again and keep bringing high quality Blocklist.
