### ISSUE TITLE
Add guidesite.info

### ISSUE THREAD

**Issue by robingroppe** [hagezi/dns-blocklists#2178]
### Which domain(s) should be blocked?

guidesite.info

### Why should these domain(s) be blocked?

Apple iPhone lookalike phishing

![WhatsApp Bild 2024-02-18 um 15 11 53_78396a23](https://github.com/hagezi/dns-blocklists/assets/11094654/853de9f4-1294-43b3-8aaf-a133039288b7)

**Comment by hagezi** [comment]
Thanks @robingroppe, will be added to light-ultimate and tif on the next update.

**Comment by xRuffKez** [comment]
Damn! Even your battery got infected :o

**Comment by xRuffKez** [comment]
ustrack[.]online
