### ISSUE TITLE
DSTV Blocked

### ISSUE THREAD

**Issue by ECHLN** [hagezi/dns-blocklists#2195]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

dstv.stream 

### Why should the domain(s) be unblocked?

This is a streaming website/app/satellite service in South Africa. Similar to cable

**Comment by hagezi** [comment]
dstv.stream not blocked in my lists.

**Comment by iam-py-test** [comment]
It is blocklisted by 1Hosts Xtra and Google Safe Browsing, and also is currently broken.
Maybe one of those are the cause for the OP's issue.
Thanks

**Comment by hagezi** [comment]
Thanks @iam-py-test
