### ISSUE TITLE
hyperfollow.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#2200]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

hyperfollow.com

### Why should the domain(s) be unblocked?

HyperFollow is promotional page for influencer/creator/producer

**Comment by hagezi** [comment]
Thanks @MagicalAlchemist, via Phishing Army.

Flags:
https://phishtank.org/phish_detail.php?phish_id=8434606
https://www.virustotal.com/gui/domain/hyperfollow.com/detection

FYI: @drego85
