### ISSUE TITLE
naturalnews.com

### ISSUE THREAD

**Issue by rugabunda** [hagezi/dns-blocklists#2204]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Dnsmasq new; adlbock

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

naturalnews.com

### Why should the domain(s) be unblocked?

a legit new website

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2153

**Comment by xRuffKez** [comment]
https://en.m.wikipedia.org/wiki/Natural_News
https://mediabiasfactcheck.com/natural-news/
https://grist.org/food/heres-why-natural-news-is-neither/
https://www.welt.de/wirtschaft/webwelt/article162355451/Google-zeigt-US-Verschwoerungsseite-nicht-mehr-an.html

**Comment by rugabunda** [comment]
> You're all right, even if it's better to read the site with an aluminium hat on, blocking is censorship. If it were up to conspiracy theories and the like, I would also have to block `bild.de` and co. 

And CNN, and Whitehouse.Gov for that matter. 

> Where do you draw the line? Everyone has their own views.

Zuckerbergs facebook won't even allow a link to naturalnews, which probably means you should check it out TBH, not a wise move to even contemplate following Facebooks footsteps.

**Comment by xRuffKez** [comment]
> You're all right, even if it's better to read the site with an aluminium hat on, blocking is censorship. If it were up to conspiracy theories and the like, I would also have to block `bild.de` and co. Where do you draw the line? Everyone has their own views.

Im not into blocking those, i don't have the right to decide for others. (It's not Ad/Tracking/Scam/Malware). But i gave you some sources, because you have a Fakenews list.

**Comment by xRuffKez** [comment]
> Zuckerbergs facebook won't even allow a link to naturalnews

This... Is censorship 😆
