### ISSUE TITLE
TikTok (Fingerprinting) in all lists?

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#221]
Is there a reason this list is not included all the way down to the Light list instead of only in the Pro++ list?  I would think all native lists would be added across the board, especially for how intrusive TikTok can be on tracking.

**Comment by hagezi** [comment]
Thanks @travisboss, the fingerprinting list is pretty aggressive and can limit features, so it's only in the Pro++ and Ultimate. I'll see about putting a stripped down version in the other lists.

**Comment by hagezi** [comment]
Leave the issue open until I get it done, otherwise I'll forget it. I'm getting old ... ;)

**Comment by hagezi** [comment]
I have taken a closer look and have come to the conclusion that I will only leave them in the aggressive lists for the time being.
