### ISSUE TITLE
Italian operator Iliad

### ISSUE THREAD

**Issue by Damia91** [hagezi/dns-blocklists#2210]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

iliad.it

### Why should the domain(s) be unblocked?

Until a few days ago he had never been blocked, from today yes. The site is simply the official website of the Italian mobile operator Iliad.

**Comment by hagezi** [comment]
Thanks @Damia91, but iliad.it is not blocked in the current version of my lists.

**Comment by Damia91** [comment]
Ops, thank you for your reply!
