### ISSUE TITLE
www.indexexchange.com

### ISSUE THREAD

**Issue by tatchiuleung** [hagezi/dns-blocklists#2218]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

www.indexexchange.com

### Why should the domain(s) be unblocked?

I recognize Index Exchange is an ads company, similar to Google Ads etc. But I think the corporate site www.indexexchange.com should be allowed for legitimate use like looking for careers, contact info, or general info.

For example, just because Google Ads provides ads, we don't block ads.google.com for searching general info.

**Comment by hagezi** [comment]
@tatchiuleung Thanks, but this is something for the personal allowlist.

Possible subdomains are used for ads and tracking. It is impossible to add all generic or new tracking subdomains, so the main domain remains blocked.

**Comment by tatchiuleung** [comment]
Understood. Thanks!
