### ISSUE TITLE
Allow objection.lol

### ISSUE THREAD

**Issue by TestNintendo** [hagezi/dns-blocklists#2219]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

objection.lol

### Why should the domain(s) be unblocked?

It's a popular Ace Attorney scene and case maker. Also has a multiplayer courtroom mode.

**Comment by hagezi** [comment]
Thanks @TestNintendo, will be removed

**Comment by hagezi** [comment]
fixed.
