### ISSUE TITLE
Hagezi VPN DOR PROXY BYPASS

### ISSUE THREAD

**Issue by christophergarcia-KS** [hagezi/dns-blocklists#2220]
### Which domain(s) should be blocked?

The Domains are 6000 and are at the limit here is a txt with the URLS. https://raw.githubusercontent.com/supspaceyt/school-proxys/main/proxys-from-school.txt

### Why should these domain(s) be blocked?

School Proxys

**Comment by hagezi** [comment]
Thank you @supspaceyt, extracting valid domains from URLs is not a problem. However, lines that are not to be transferred should be labelled as comments, i.e. starting with #.

Is the list intended for a one-time transfer or is it updated cyclically?

If you want to extract valid domains from a continuous text, you can use the following online tool:

https://de.rakko.tools/tools/62/

You would then have to sort out the domains that are not proxies from the result.

**Comment by supspaceyt** [comment]
Uptoia Proxy
add.tutor.hydraulik-handpumpen.com
area.brain.cravat-club.com
area.state.wspaperbag.com
atom.class.aviornstein.com
atom.class.chowpatty.com
base.arts.dirty-thought.com
books.bio.eapwws.org
books.excel.tantalizing-nutmeg.com
info.angle.twlab.org
study.add.poshdcentaplus.com
sci.clever.thompent.com
smart.task.maurwind.com
task.words.starlordbob.com
read.study.escfks.com
study.recap.laidigs.com
teach.bio.lamagdeleine.com
rizz.orbit.abdatabase.com
school.data.guance-paffute.com
state.arts.commonwealthparksuites.com
skills.excel.ramomichelle.com
state.data.tatahasa.com
recap.area.biddingtraveller.com
plant.graph.thesqueakandoilchart.com
school.craft.barajasmexico.com
real.edu.sardar.org
rizz.skills.gatnas.com
math.prep.safe-transfer.com
read.mass.wichidnixin.com
read.smart.sternentor.org
prep.data.drzubairkhan.com
prep.logic.longjinglihua.com
orbit.lab.hitformule.com
mass.theme.iswellhung.com
books.gyat.smile-backk.com
login.tutor.fununit.com
login.notes.4sillysausages.com
brain.state.vntp.com
logic.edu.centromedicopaz.com
orbit.vocab.takkat.com
how.state.cumbrevirtualdecoaching.org
info.focus.sunrisefarmireland.org
cells.data.qualitely.com
how.smart.verheij-group.com
cells.tech.arbnepal.com
how.focus.rimbardmanor.com
chart.state.wilgaskin.com
church.facts.hkrenoman.com
church.math.resco-research.com
class.course.acslincoln.com
class.rizz.ibnbola.com
clever.teach.nekclan.com
core.area.lantzranch.com
core.info.port0.org
course.books.ceramicsclay.com
data.idea.islamicnetwork.org
ela.guide.dietpc.org
ela.school.desprivacy.com
goal.excel.didi-construction.com
gov.idea.ubidrhzos.com
gov.learn.hitchhiker-linux.org
graph.edu.dahmongah.org
history.church.tantalizing-chick.com
history.think.dimlocogr.com
how.add.axiomb.com
teach.history.locosxelfutbol.org
tech.idea.jsnerd.com
theme.data.darlaengland.com
theme.gyat.rebro.org
theme.real.chadpools.com
theme.rizz.unix-admins.com
train.mind.hotunix.com
train.rizz.cosmosis.org
train.sci.aygenerji.com
work.gov.urbanarboretum.com
work.undefined.xn--bq4b03i.com
write.know.electricidadesport.com
write.mind.croftmail.com
lab.sci.jackdawmc.com
study.mass.g-lang.com
info.tutor.refillmaker.com
books.know.duncanmctavish.com
read.task.3am-eternal.org
guide.angle.worldcreate.org
clever.read.vadamus.com
course.rizz.soulspark.org
focus.words.lanceglenn.com
theme.goal.burningbarrelbrewery.com
clever.sci.scaldeddog.com
books.mind.wafranks.com
prep.vocab.purnimafernando.com
learn.clever.notesninjas.com
tutorcenter.quest
theme.focus.99kpe.com
cellscience.top
khanacademy.buzz
vastknowledge.quest
ancienthistory.website
acutemath.quest
howtomath.org
studyinghive.com
schoolguide.buzz
utopiaunblocker.com
studyingmath.org
learningprep.xyz
learnbiology.quest
academichelp.xyz
cleverutopia.com
science-facts-molkify.koyeb.app
smartacademy.buzz
www.smartowls.tk
historypractice.org
eduverse.wiki
tutorsharp.com
solve.topic.the-dawn.com
utopia.mass.tozsugianto.com
cells.study.gorichev.com
gyat.grid.volkswagenrescue.com
angle.books.allanon.org

**Comment by supspaceyt** [comment]
UltraViolet

69.eightgrade.com
violet.u46-war-education.xyz
noko.fishoho.com
developmentbuild.herokuapp.com
guardian-ultraviolet.vercel.app
ultraviolet.segso.net
clearview.sushiprosi.com
coca.colaclass.com
icon.sashimimi.com
badbad.promathclass.com
wolf.fishoho.com
scpwolf.fishoho.com
zc.promathclass.com
zc.colaclass.com
laptop.promathclass.com
icon.colaclass.com
icon.promathclass.com
wolfunblock.sashimimi.com
icon.fishoho.com
wolf.colaclass.com
scpwolf.promathclass.com
badbad.sashimimi.com
scpwolf.topicademy.com
zc.fishoho.com
adevertisment.topicademy.com
icon.topicademy.com
wolf.sashimimi.com
noodss.topicademy.com
wolfunblock.promathclass.com
research.topicademy.com
motor.sashimimi.com
foot.topicademy.com
mossnews.mathtutoringwithlove.info
stopblokingplease.promathclass.com
securly.com.foxmoss.com
badbad.colaclass.com
fishme.me
maths.23azorun.com
classes.23azoshooting.com
classswork.23azosports.com
wolfunblock1.sashimimi.com

**Comment by supspaceyt** [comment]
kumasushi.g2g.asia
ilovelagtrain.hs.vc
nebulur.synchole.net
learnjapanese.dob.jp
typhoon.lol
twistedmath.ignorelist.com
crystalnetwork.me

**Comment by supspaceyt** [comment]
https://letslearn-math.xyz/ 
https://cosmicgeometry.xyz/ 
https://math-orbit.com/ 
https://cosmicgateway.xyz/ 
https://schoolgeometry.xyz/

**Comment by supspaceyt** [comment]
letslearn-math.xyz
cosmicgeometry.xyz
math-orbit.com
cosmicgateway.xyz
schoolgeometry.xyz
algebra.prototipservisi.com
math.fullstackelectron.com
science.kdense.com
geometry.ruskow.com
pro.minoa.cat
servers.h-o-s-t.name
math.apsago.com
algebra.customintegrator.org
tutor.phyorealty.com
counting.jweststudio.com
art.ontariobsd.net
geometry.rpcthai.com
geometry.precisewarehousing.com
science.pyramidish.com
math.faverybishop.com
math.supplysolutionsmx.com
algebra.sembiring.com
math.firerehab.org
algebra.hyrisoft.com
algebra.videla.net
geometry.hacknperl.com
algebra.idcmsc.com
algebra.morrisis.net
algebra.sjtech.org
geometry.artidoksan.com
khanacademy.hopto.org
math.velkat.org
geometry.fernhamconsulting.net
math.ajatar.org
algebra.melissaanddougcoop.com
geometry.triutama.com
algebra.stickyricecakes.com
science.paulmccune.com
space.banquick.com
math.lamela-trans.com
algebra.candcinsurancebrokers.com
algebra.bransw.com
science.chris-kelley.com
algebra.mciahh.org
algebra.hitekrecruiting.net
edu.projectsioux.com
math.polonisgroup.com
math.smelle.net
band.kuztsudio.com
math.abasma.com
math.sociedadecirugialp.org
math.lexvoip.net
link.embedding.mov
atutor.tien-shan.org
math.jimayre.com
science.jrybb.com
algebra.feezor.net
search.uwuugle.com
schooltech-joelwkwssd.koyeb.app
nooo-the.chubsinfestation.design
literature.tscng.org
findmytutor.info
webapplication.design
codingwizard.org
sciencemaster.co
eduhelper.co
teachersearcher.co
mathhelper.co
physicprofession.org
exploreshuttle.xyz
spanishlearnolgy.co
tutors4u.net
artmastery.guru
learn.autismawareness.design
tutors4u.co
learnsmartly.org
shuttle.cf
edu.primemath.lol
shuttleproxy.com
edurelief.co
tutors4cheap.co
tristanschools.co
learn2invest.info
creativeclassroom.co
cheapclass.co
homework.226vitech.com
algebra.ruiz-tagle.com
math.rulfer.com
jmtforever.cfd
youarethereasonforthedivorce.cfd
typeist.lat
walterwhitexjessepinkman.gay
isleptwithyour.mom
jonesgymtutors.website
867-5309.website
gearcalculator.lat
287kx5.csb.app
science-work.us.to
english-reading-games.uk.to
math.work.fr.to
social-studies-work.fr.to
polished-pinto-bean.glitch.me
funny-grandiose-kitty.glitch.me
equal-frill-gravity.glitch.me
knotty-rambunctious-snowman.glitch.me
dawn-tiny-hour.glitch.me
alert-band-cobbler.glitch.me
blog1201.mathcalculators.site
blog1201.mathsblog.site
blog1201.mathematicstopvaz.online
blog1201.mathematicstopvaz.site
blog1201.geometrytopvaz.site
blog1201.geometrytopvaz.online
blog1201.topvazgeometry.site
blog1201.topvazgeometry.online
blog1201.tvazgeometry.online
blog1201.mathsblog.online
blog1201.topvazgeo.online
blog1201.tvazgeo.site
calc1208.topvzmath.online
calc1208.topvazmathblog.site
calc1208.topvz.site
calc1208.topvz.online
calc1208.topvazmath.site
calc1208.topvazg1.online
calc1208.topvazg1.site
calc1208.tvaz.online
calc1208.tvazmathblog.site
calc1208.tvazmath.online
calc1208.tvazmath.site
calc1208.greatmathblogs.site
calc1208.greatmathblogs.online
calc1208.mathematicsblogs.online
calc1208.topvaz1.online
calc1208.topvazmathblogs.online
calc1208.mathematicsblogs.site
calc1208.topvzmath.site
blog1201.tvazgeo.online

**Comment by supspaceyt** [comment]
They are adding More Links every two weeks here is Google Docs Source https://docs.google.com/document/d/1nK6tJb-sxfrrQJM9bSWcAV-Fo7jHasd_dWpj4VEVg5E/view

**Comment by supspaceyt** [comment]
rocks.sciencesimplified.pro
free.englishpapers.online
theclimate.sciencesimplified.pro
earlybirdbonus.earlyriserscoffeeshop.com
discount.zoneitshop.com
cool.tribalgod.com
e.pentafon.net
iam.pastrypowered.com
areu.zombiehitmen.com
free.unibutton.com
peace.computersforpeace.net
free.hitremixes.com

**Comment by supspaceyt** [comment]
https://kazwire.com/apps/google This is using Proxy

**Comment by hagezi** [comment]
@supspaceyt It makes no sense to post bulk posts with domains here, either you create a list that we can parse, or I take it from the source document.

Please stop ...

**Comment by supspaceyt** [comment]
Use this Document https://docs.google.com/document/d/1nK6tJb-sxfrrQJM9bSWcAV-Fo7jHasd_dWpj4VEVg5E/view has all links proxies

**Comment by hagezi** [comment]
@supspaceyt I would prefer it if you would host and maintain a clean list on Github. We can then import it. Maintaining all the lists already requires more than enough effort, so I don't need to manually maintain and update a proxy list.

**Comment by supspaceyt** [comment]
@hagezi Here is a Gamilbing Site presale.hypeloot.com

**Comment by xRuffKez** [comment]
There might be more, but im not a school Web administrator... I don't get paid for tearing apart a google doc with hidden links and lists.
Although thanks for your contribution.

**Comment by hagezi** [comment]
It makes absolutely no sense to inflate the bypass list with 100s of thousands of domains, especially since the simplest bypass is to use the IP instead of the domain name.

**Comment by hagezi** [comment]
@supspaceyt Are you able to provide a slimmed-down list of top proxies that does not contain thousands of domains? Otherwise I will close this. I will not inflate the bypass list unnecessarily.

**Comment by xRuffKez** [comment]
> It makes absolutely no sense to inflate the bypass list with 100s of thousands of domains, especially since the simplest bypass is to use the IP instead of the domain name.

https://github.com/hagezi/dns-blocklists/issues/4555
https://github.com/hagezi/dns-blocklists/issues/4556
https://github.com/hagezi/dns-blocklists/issues/4557
https://github.com/hagezi/dns-blocklists/issues/4558
https://github.com/hagezi/dns-blocklists/issues/4559

**Comment by xRuffKez** [comment]
> > > It makes absolutely no sense to inflate the bypass list with 100s of thousands of domains, especially since the simplest bypass is to use the IP instead of the domain name.
> > 
> > 
> > #4555 #4556 #4557 #4558 #4559
> 
> Is this basically saying these domains won’t be added?

@hagezi added them to the list 😉
