### ISSUE TITLE
Allow tr.strumentimusicali.net

### ISSUE THREAD

**Issue by irondave** [hagezi/dns-blocklists#2222]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

tr.strumentimusicali.net
a2x6h7.trk.musvccustom.net

### Why should the domain(s) be unblocked?

It's a legit site

**Comment by hagezi** [comment]
Thanks @irondave, but which function is restricted by blocking, what does not work?

The subdomains are trackers, are they referral trackers that are called up by clicking on a link?

**Comment by irondave** [comment]
Thank you,
the problem occurs when I try to open a link that I get by email with notices of what products are being offered for sale at https://www.mercatinomusicale.com/
Also, the problem occurs only on smartphones since on computers I can open the links without problems, on smartphones the blocking occurs.
On both pc and smartphone I use nextdns with the same settings.
