### ISSUE TITLE
False positive: dripdepot.com

### ISSUE THREAD

**Issue by justfalter** [hagezi/dns-blocklists#2231]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

dripdepot.com

### Why should the domain(s) be unblocked?

This is an online store for buying drip-irrigation equipment. It's unclear to me why it would have been blocked.

**Comment by hagezi** [comment]
Thanks, fixed with last release.
