### ISSUE TITLE
add allow list: auction.co.kr

### ISSUE THREAD

**Issue by nanggo** [hagezi/dns-blocklists#2234]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

auction.co.kr

### Why should the domain(s) be unblocked?

This site is a legitimate and widely used e-commerce platform in South Korea.

Maybe some sub domains tracking users, but if blocking auction.co.kr can't access e-commerce service.

Thank you for your attention to this matter and for your ongoing efforts to improve internet safety and accessibility.

**Comment by hagezi** [comment]
Thanks @nanggo, will be removed asap.
