### ISSUE TITLE
fapnado.xxx (NSFW)

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#2237]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

`fapnado.xxx`

### Why should the domain(s) be unblocked?

Legitimate adult site

**Comment by yokoffing** [comment]
@hagezi We need to also allowlist  `fapnado.com` as well.
example: `cdnca6b.fapnado.com`

We continue to block `ok.fapnado.xxx`, but the site works with it blocked. So that request can stay blocked.

**Comment by hagezi** [comment]
Thanks, will be removed in the current running build.
