### ISSUE TITLE
Brazzers.com (NSFW)

### ISSUE THREAD

**Issue by AncientVamp** [hagezi/dns-blocklists#2239]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

brazzers.com, www.brazzers.com

### Why should the domain(s) be unblocked?

Legitimate Adult Site

**Comment by hagezi** [comment]
Thanks @AncientVamp, fixed in release https://github.com/hagezi/dns-blocklists/commit/8031d5f421a707ed1259f0d11d58060eb151e13e
