### ISSUE TITLE
Unblock 87.230.98.74

### ISSUE THREAD

**Issue by ShiGhost** [hagezi/dns-blocklists#2242]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

87.230.98.74

### Why should the domain(s) be unblocked?

The situation is similar with #949, you deleted the domain from the list, but forgot about the IP address.

![Screenshot_14](https://github.com/hagezi/dns-blocklists/assets/104279498/3e8d9eaa-68d0-4bc5-8aea-e45500cfa810)

**Comment by hagezi** [comment]
fixed

**Comment by hagezi** [comment]
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/f68b32e6-f2cf-4243-9045-d3aa25d2f5d4)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/c79a174a-8096-412d-8aa9-56fa969be9c3)

**Comment by hagezi** [comment]
@iam-py-test

**Comment by iam-py-test** [comment]
I am sorry, but I do not believe this IP address is blocklisted in my filterlist.
Am I missing something?
Thank you
