### ISSUE TITLE
Pastebin.com blocked in TIF-feed

### ISSUE THREAD

**Issue by iJorgen** [hagezi/dns-blocklists#2245]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

104.20.68.143

### Why should the domain(s) be unblocked?

A legit IP pointing to pastebin.com

```
;; ANSWER SECTION:
pastebin.com.		340	IN	A	104.20.68.143
pastebin.com.		340	IN	A	172.67.34.170
pastebin.com.		340	IN	A	104.20.67.143
```

**Comment by hagezi** [comment]
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/a12655b1-420f-413d-aace-5ce53d8af07c)

@iam-py-test

**Comment by hagezi** [comment]
Thanks @iJorgen, fixed.

**Comment by iam-py-test** [comment]
I am confused; this IP address does not appear to be listed in my blocklist.
Thank you
