### ISSUE TITLE
mix type of blocked website I don't understand it clearly 

### ISSUE THREAD

**Issue by looser71** [hagezi/dns-blocklists#2248]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

tiktok.com

### Why should the domain(s) be unblocked?

Sir I have disabled all settings in the security tab in nextdns to test this . The only setting on is multi pro++ (the only blocklist I use) and po*n in parental control. When someone send me a TikTok video link and I open it in chrome or Firefox it doesn't. I checked my nextdns log and it shows it normally (doesn't show that it's blocked). I disabled all settings in security tab to test it and still no luck . I checked it with multi normal still no luck . I checked it with multi light still no luck. When I disable private dns in my Android settings and use my default dns set by my ISP then the links open flawlessly. So I don't understand that if it was because of dns why didn't it showed in nextdns log.

**Comment by looser71** [comment]
If u could look into this or guide me to diagnose this issue that will be very kind of you. Thank u so much .

**Comment by hagezi** [comment]
Please send a link for testing.

**Comment by looser71** [comment]
https://www.tiktok.com/@wasimfedayi91/video/7321258599798541574?_t=8kCl6ORLo9K&_r=1

Or even simple tiktok.com also don't opens.

**Comment by hagezi** [comment]
I have tested it with NextDNS and Ultimate, works perfectly. This is not a blocklist problem. Please contact the NextDNS support.

**Comment by looser71** [comment]
Ok sir no problem. I am sorry for the inconvenience. Have a good day.
