### ISSUE TITLE
Coin locally blocked

### ISSUE THREAD

**Issue by amirhosseinds** [hagezi/dns-blocklists#2252]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

coinlocally.com

### Why should the domain(s) be unblocked?

coin locally is a legit crypto exchange and its ok please unblock it thanks

**Comment by hagezi** [comment]
Thanks, will be fixed on current running release.

**Comment by hagezi** [comment]
fixed.
