### ISSUE TITLE
NextDNS admin-pages blocked (my.nextdns.io)

### ISSUE THREAD

**Issue by iJorgen** [hagezi/dns-blocklists#2259]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds IPs

### Which domain(s) should be unblocked?

76.76.21.9  (but could be more in the 76.76.21.x subnet)

### Why should the domain(s) be unblocked?

Couldn't reach my.nextdns.io and noticed 76.76.21.9 was blocked in my firewall. 

Seems it's owned by Vercel (hosting) with loads of applications in this subnet.
https://otx.alienvault.com/indicator/ip/76.76.21.9

```
;my.nextdns.io.			IN	A

;; ANSWER SECTION:
my.nextdns.io.		29	IN	CNAME	cname.vercel-dns.com.
cname.vercel-dns.com.	29	IN	A	76.76.21.123
cname.vercel-dns.com.	29	IN	A	76.76.21.9
```

Cleared my DNS-cache and got a new working IP-address after a few tries that's not blocked.

```
QUESTION SECTION:
;cname.vercel-dns.com.		IN	A

;; ANSWER SECTION:
cname.vercel-dns.com.	300	IN	A	76.76.21.61
cname.vercel-dns.com.	300	IN	A	76.76.21.241
```

**Comment by hagezi** [comment]
WTF ...

**Comment by hagezi** [comment]
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/ef4d7ca2-4029-4d12-8a8e-81aa035ca2c5)

**Comment by iam-py-test** [comment]
Out of curiosity, what tool are you using in the above screenshot?
Your tool shows 76.76.21.9 being listed in my list (among others), but as with prior issues, that does not seem to be the case.
Thank you.

**Comment by hagezi** [comment]
Then there is probably an error in my query against my build system. I'll have a look at that later.

**Comment by iam-py-test** [comment]
No worries.

**Comment by hagezi** [comment]
Yes, there was a mistake in my query. If you query correctly, you'll get the right result ;)
Sorry ...

**Comment by iam-py-test** [comment]
It's fine
