### ISSUE TITLE
webhook.logentries.com

### ISSUE THREAD

**Issue by darkfence** [hagezi/dns-blocklists#2260]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

webhook.logentries.com

### Why should the domain(s) be unblocked?

This domain is required for proper work of IKEA Tradfri + Homekit system.

**Comment by hagezi** [comment]
@darkfence What exactly is wrong with the domain blocking? I also operate an IKEA gateway and have never had any problems with the blocked domain. Neither software updates nor anything else is restricted.

There are reports about it, but this concerns old firmware versions.

**Comment by darkfence** [comment]
With the domain blocked, all accessories become unreachable. I just checked in the IKEA app and I have the latest software version installed.

**Comment by hagezi** [comment]
I've never had any problems with it and the app is used here. However, I will unblock the domain in the Pro, it remains blocked in the aggressive lists.
