### ISSUE TITLE
Whitelist these domains 

### ISSUE THREAD

**Issue by nextDNSconfig** [hagezi/dns-blocklists#227]
Hi, could you maybe whitelist these? 
it see domains I had to allow for everything to work properly on my phone, it's a lot of dutch websites and apps. also school websites I had to allow for learning, and the hockey website. 

-----------------------------------------------------------------

.cdn.nos.nl

.api.nos.nl

.api2.scoupy.nl

*.game.brawlstarsgame.com

*.xp.apple.com

*.tracking.hockeydirect.nl

*.mobile-api.coolblue-production.eu

*.datadog-gateway.eu-west-1.coolblue-production.eu

*.sf-api-token-service.itunes.apple.com

*.api-edge.apps.apple.com

*.api.apps.apple.com

*.amp-api-edge.apps.apple.com

*.api.me2-prd.gmal.app

*.api.me1-prd.gmal.app

*.dif.gmal.app

*.api.bosch-wdw.com

*.flitsmeister.app

*.cdn.flitsmeister.app

*.account.flitsmeister.app

*.alerts.flitsmeister.app

*.data-ios.flitsmeister.app

*.4411.flitsmeister.app

*.appservice.flitsmeister.app

*.charting.vwdservices.com

*.solutions.vwdservices.com

￼*.beurs.fd.nl

*.api.fdmg.org

*.getbux.com

*.api.rudderlabs.com

*.api.leanplum.com

*.stocks.prod.getbux.com

*.api-partner.spotify.com

*.mp.images.icas.io

*.cdn.ebayclassifieds.net

*.accountbar.toegang.nu

*.noordhoff.nl

*.kennisnet.nl

*.thiememeulenhoff.nl

*.aselect.entree.kennisnet.nl

*.engine.entree.kennisnet.nl

*.toegang.thiememeulenhoff.nl

*.www.lessonup.com

*.team.lisa-is.nl

*.hockey.nl

*.graph.talparad.io

*.content.talparad.io

*.www.lttstore.com

*.api.wordfeud.com

*.talpatvcdn.nl

*.cldnr.talpa.network

*.api.prd.video.talpa.network

*.amp-api-search-edge.apps.apple.com

**Comment by hagezi** [comment]
I did a random check of the domains listed, none of the ones I checked were on my lists.

Is this your personal NextDNS whitelist that you have created over time?

**Comment by nextDNSconfig** [comment]
Yes, this is my personal blocklist from NextDNS, much are from 1Hosts Xtra

**Comment by hagezi** [comment]
@nextDNSconfig 

Checked your list against the Ultimate, found:

```
api.leanplum.com
api.rudderlabs.com
```
Are blocked in all my lists and are present on many sources. They are trackers.

Can you tell me why these had to go on your whitelist so I can check?

**Comment by DevKoen** [comment]
the app [bux zero](https://getbux.com/nl/) use them, if they are blocked i can't open the app

**Comment by hagezi** [comment]
@DevKoen 

I can open and operate the iOS app:

![grafik](https://user-images.githubusercontent.com/104343908/213875094-82a16611-2ced-4398-9b15-345c8a9757f9.png)

**Comment by DevKoen** [comment]
@hagezi 
Yep, i blocked it and the app still works! you can keep blocking them!

**Comment by hagezi** [comment]
@DevKoen Thank you for the confirmation.
