### ISSUE TITLE
Analyse and integrate TIF from @rodanmaharjan

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#2270]
Analyse and integrate TIF from @rodanmaharjan

https://github.com/rodanmaharjan/ThreatIntelligence

Hint from @xRuffKez

**Comment by hagezi** [comment]
Many false positive domains:

```
https://raw.githubusercontent.com/rodanmaharjan/ThreatIntelligence/main/CobaltStrike.txt
https://raw.githubusercontent.com/rodanmaharjan/ThreatIntelligence/main/Phishing_Domains.txt
```

**Comment by hagezi** [comment]
Far too many false positives.

**Comment by rodanmaharjan** [comment]
Can you give me the list of false positive so that I can remove it from the list?

**Comment by rodanmaharjan** [comment]
And also the dead domain list. Thank you.

**Comment by hagezi** [comment]
Hi @rodanmaharjan, I'll put it together later.

**Comment by rodanmaharjan** [comment]
Sure, thanks. And, you can send me the list in my mail it will be easier to remove the false positive.

**Comment by hagezi** [comment]
@rodanmaharjan I'll send you the files by e-mail later.

What I did in addition to the first analysis:

- Checked the missing domains for dead domains (NXDOMAIN/SERVFAIL).
- Removed dead domains from the original allowlist.
- Checked the adjusted Allowlist against SecureDNS (DNS0.eu, Quad9.net, CloudflareSec, Umbrella) and removed the blocked domains from the Allowlist.

The allowlist should now be relatively "clean".

**Comment by rodanmaharjan** [comment]
@hagezi Thank you. Hoping to get the file soon.

**Comment by hagezi** [comment]
@rodanmaharjan I have already sent them, have a look.

**Comment by rodanmaharjan** [comment]
@hagezi Thankyou, I will remove all the dead links from the list.
