### ISSUE TITLE
Whitelist this domain

### ISSUE THREAD

**Issue by Quorum75** [hagezi/dns-blocklists#228]
Ultimate list blocks swile.co
It is an application / restaurants card sponsored by companies for their employees. Totally legit. 
Blocking the domain prevents employees to use the application to pay for their meals. 

https://apps.apple.com/app/id1190612035

**Comment by DevKoen** [comment]
Can you add the log?

**Comment by hagezi** [comment]
Thanks, will check ...

**Comment by hagezi** [comment]
Removed `swile.co`, blocked is `do.swile.co` (CNAME `go.pardot.com`). Do you have a subdomain for the log? Haven't found anything suitable.

**Comment by DevKoen** [comment]
@hagezi i will have a look...

**Comment by nextDNSconfig** [comment]
![image](https://user-images.githubusercontent.com/86489640/213875044-097977c4-da56-40c7-85a9-1a8057f64031.png)



![image](https://user-images.githubusercontent.com/86489640/213875048-ca0f354f-ee12-416d-ac85-aff0609dedf1.png)

**Comment by DevKoen** [comment]
[affiliates-api.swile.co](https://affiliates-api.swile.co/)
[affiliate-api-staging.swile.co](https://affiliate-api-staging.swile.co/)
[in-app-notifications-api.swile.co](https://in-app-notifications-api.swile.co/)
[affiliate-api.swile.co](https://affiliate-api.swile.co/) 


block these

**Comment by hagezi** [comment]
Thanks @DevKoen, added to ultimate.

**Comment by hagezi** [comment]
Is there something else or can I close?

**Comment by nextDNSconfig** [comment]
@hagezi if i find more domains I will send them to you! 

Your support is amazing btw, very fast and good help!

**Comment by Quorum75** [comment]
Thank you very much. Case closed.
