### ISSUE TITLE
api.hf.space

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#2283]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

`api.hf.space`

I'm testing:
https://github.com/hagezi/dns-blocklists/blob/main/controld/spam-tlds-folder.json
https://github.com/hagezi/dns-blocklists/blob/main/controld/spam-tlds-allow-folder.json

### Why should the domain(s) be unblocked?

`https://huggingface.co/spaces/lmsys/chatbot-arena-leaderboard`

**Comment by hagezi** [comment]
@yokoffing The TLD is no longer included in the spam TLD list.

I have not updated the ControlD JSONs for a while, they were created manually, could you correct this in your folder and update via PR here?

Thank you ...

**Comment by hagezi** [comment]
Thanks!
