### ISSUE TITLE
Generate ControlD folder JSONs from TLD/CMP/Referral source list

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#2285]
#2283 
https://github.com/hagezi/dns-blocklists/tree/main/controld

**Comment by xRuffKez** [comment]
Need help?

**Comment by hagezi** [comment]
Referral: https://github.com/hagezi/dns-blocklists/commit/48d214c41389409bee311d675013507098d085ba

**Comment by xRuffKez** [comment]
Do you need Action, Python or straight converting?

**Comment by hagezi** [comment]
Thanks for the offer, but I do this locally in my build system process.

**Comment by hagezi** [comment]
Spam TLDs: https://github.com/hagezi/dns-blocklists/commit/f00e4a418292da0a5b14b4494ee440951fd02e22
