### ISSUE TITLE
constantcontact

### ISSUE THREAD

**Issue by FookunKlez** [hagezi/dns-blocklists#2292]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

constantcontact.com

### Why should the domain(s) be unblocked?

Legitimate survey domain

**Comment by hagezi** [comment]
@FookunKlez Thank you, the main domain is not blocked, tracking subdomains are blocked. Where do these lead to restrictions, please provide more details.

**Comment by FookunKlez** [comment]
https://lp.constantcontactpages.com/


That was the page which was blocked. Thank you

**Comment by hagezi** [comment]
@FookunKlez 

From where is the domain accessed? What did not work due to the blocking?
