### ISSUE TITLE
Bypass Androeed.store

### ISSUE THREAD

**Issue by mocduong2307** [hagezi/dns-blocklists#2296]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

androeed.store

### Why should the domain(s) be unblocked?

Because is normal , why blocked

**Comment by hagezi** [comment]
Thanks @mocduong2307, blocked because spyware in ABKs, see:
https://github.com/hagezi/dns-blocklists/blob/ca0345027f99ae02902919e070f54071894677ba/submit_pullrequest_here/deny_tif.txt#L17

@xRuffKez Can you please take over and check that?

**Comment by xRuffKez** [comment]
Yes one sec

**Comment by xRuffKez** [comment]
https://any.run/report/7da63d58afcb888bdf9c7184f5c9353bc72cffcc8e2fa291e931c6823fea9ca9/313c7bef-ed67-4921-8abf-326b9a097b9b
https://tria.ge/230928-zpaxssed6v

There are many Apps, (which you can scan yourself via Virustotal) Container at least Spyware and worst Ransomware.
A week ago, I analyzed `Merge Dragons` where data from the phone gets transfered to `googlesavedata.ru`. 
In my opinion, im not for unblocking it.

**Comment by xRuffKez** [comment]
> Tks for comment , i think i need charge the website for android app . If not have your commant , maybe i dont know is dangerous and have spyware + ransowmare

You're welcome, unfurtunately i cannot publicly recommend an alternative in this Repository.
