### ISSUE TITLE
launchgiftcards.com

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#2298]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

launchgiftcards.com
www.launchgiftcards.com

### Why should the domain(s) be unblocked?

Legitimate gift card network/site, eg. used by Uber for gift cards: https://www.uber.com/ca/en/gift-cards/
- "Buy Now" button => https://uberca.launchgiftcards.com/

Thank you!

**Comment by hagezi** [comment]
Thanks @durablenapkin, via @shadowwhisperer Scam list, will be removed.
