### ISSUE TITLE
Battlefield 2042 doesnt load into a match as it cannot connect

### ISSUE THREAD

**Issue by smcmackin20** [hagezi/dns-blocklists#2299]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

I am not sure the domains but related to EA

### Why should the domain(s) be unblocked?

I was using free Control D and Battlefield 2042 doesn't load into a match

**Comment by hagezi** [comment]
Thank you @smcmackin20, unfortunately I can't test this myself. Please test the following?

- Does it work with normal?
- Does it work with OISD big?

**Comment by smcmackin20** [comment]
I will test when possible for OISD big. I know normal also doesn't work. I switched lists to Adguard DNS filters and it works now

**Comment by hagezi** [comment]
@smcmackin20 please test the light as well as OISD.

**Comment by hagezi** [comment]
@smcmackin20 I have searched the lists for EA specific domains and can't find anything. On which platform does the problem occur?

**Comment by slawa-dev** [comment]
> I will test when possible for OISD big. I know normal also doesn't work. I switched lists to Adguard DNS filters and it works now

Go to controld website to the logging page. Then start the game and post which domains are being blocked.

**Comment by hagezi** [comment]
> Go to controld website to the logging page. Then start the game and post which domains are being blocked.

Thanks, but he uses ControlD free and has no access to logs.

**Comment by hagezi** [comment]
@smcmackin20 I had a feedback from the community via Discord, on Playstation using the Ultimate it works fine. Then it also works with the lists below the Ultimate, at least on Playstation.
Maybe you should check again, not that it was due to the servers.

**Comment by bezibaerchen** [comment]
Just tested with NextDNS utilizing The Ultimate-List. I was able to connect without issues.

**Comment by BourbonCrow** [comment]
@smcmackin20 i tested this using controlD (payed account) with ultimate list and joining 3 servers was totally fine no issue

**Comment by smcmackin20** [comment]
I am so sorry for the delayed response, I just tested on Adguard DNS with your lists and it worked. My platform is Xbox, however the free control d version doesn't connect into a match. OISD doesn't have the problem and neither does light for your list. I have chalked it up to Control D not working right

**Comment by hagezi** [comment]
Thanks, closing ...
