### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Domsicols** [hagezi/dns-blocklists#23]
I am seeing ads in this particular site. Can you check? https://animals.howstuffworks.com/arachnids/pelican-spiders.htm

![image](https://user-images.githubusercontent.com/104392824/182771104-3683061f-0c8d-4bcb-b0ec-d7bfa76e73d3.png)

**Comment by Domsicols** [comment]
Im using pro btw

**Comment by hagezi** [comment]
Hi,

I cannot reproduce this via the link provided. I do not see any ads.

![grafik](https://user-images.githubusercontent.com/104343908/182814849-de757720-0afa-45b6-b4f0-910a8eb2466a.png)


Test environment:
AdGuard Home, Pro Blocklist (latest build), Browser: Safari on iOS

Please check again.

Cheers,
Gerd

**Comment by Domsicols** [comment]
Thanks. No problem on safari, this appears on the flipboard app itself.
