### ISSUE TITLE
Can whitelist-referral include URL shorteners too?

### ISSUE THREAD

**Issue by timkgh** [hagezi/dns-blocklists#230]
I use https://github.com/hagezi/dns-blocklists/blob/main/adblock/whitelist-referral.txt in AGH which I understand is generated from https://github.com/nextdns/click-tracking-domains

But now the nextdns affiliate & tracking links feature also includes this list of URL shorteners that don't appear directly in the nextdns/click-tracking-domains list, per https://github.com/nextdns/click-tracking-domains/issues/1:
https://github.com/PeterDaveHello/url-shorteners/blob/master/list

Could your whitelist-referral list also include it or have a separate AGH format for URL shorteners? Thank you.

**Comment by hagezi** [comment]
Thanks @timkgh, check https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-urlshortener.txt

**Comment by hagezi** [comment]
@timkgh Header added.
