### ISSUE TITLE
block tracker.testbook.com

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2300]
### Which domain(s) should be blocked?

tracker.testbook.com
jarvis.testbook.com

### Why should these domain(s) be blocked?

This domain are for tracking purpose only i have blocked them and there was no effect using this service app but having this unblocked you can't use that app simultaneously on 2 or more devices.

**Comment by hagezi** [comment]
Thanks, I will only block the domains in the aggressive lists for now.

**Comment by userforsource** [comment]
> Thanks, I will only block the domains in the aggressive lists for now.

I am using multi pro++ kindly include it in this thanks for your prompt action.

**Comment by hagezi** [comment]
Thanks @userforsource, will be added to pro++ and ultimate on next release.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2368
