### ISSUE TITLE
false positive?? 

### ISSUE THREAD

**Issue by looser71** [hagezi/dns-blocklists#2302]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

androeed.store

### Why should the domain(s) be unblocked?

Sir @hagezi this is a reputable website and trusted . I think it may have been blocked mistakenly if not can u provide the reason for its block. Thank u so much.

**Comment by hagezi** [comment]
See: https://github.com/hagezi/dns-blocklists/issues/2296

**Comment by looser71** [comment]
Also androeed.ru. both are same but .store is the English version. Plz look into it .

**Comment by looser71** [comment]
Thanks I read the other thread. U blocked it for spyware. Thanks sir.

**Comment by hagezi** [comment]
ping @xRuffKez

**Comment by xRuffKez** [comment]
I will check random 20 apps and will decide. Modyolo.com had also some malicious apps. 
I think someone who Downloads apks and is able to disable the Androids safety  setting to install the apk, they might be aware of some risks.

Checking, brb...
@hagezi

**Comment by xRuffKez** [comment]
I've checked some APKs. Most were clean and some got flagged with `Android.Riskware.TestKey.rA` which is a developer signing keys, used by modded apks. Harmless.
I would unblock androeed[.ru|.store|.de|.cn] and it is up to the user to check for APKs which contain spyware and which not.
i've also checked Merge Dragon APK and is clean this time. I think they removed the malicious APK?
@hagezi @looser71

**Comment by xRuffKez** [comment]
https://github.com/hagezi/dns-blocklists/issues/2296

**Comment by hagezi** [comment]
Thanks @xRuffKez

**Comment by looser71** [comment]
Thanks alot to both @xRuffKez  and @hagezi . ♥️
