### ISSUE TITLE
block fb tracker

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2305]
### Which domain(s) should be blocked?

mqtt-mini.facebook.com

### Why should these domain(s) be blocked?

This is a domain i think is for tracking purpose only i find this on mi and xiaomi devices and it constantly ping on that even when you don't have any facebook app installed.

**Comment by nightznero** [comment]
You can block it manually and check if its not collide with mess on other devices but according to my list i would say its ness if some1 uses Mess Lite
![Uploading Screenshot_20240309_192850_Brave.png…]()

**Comment by nightznero** [comment]
You can block it manually and check if its not collide with mess on other devices but according to my list i would say its ness if some1 uses Mess Lite
![Screenshot_20240309_192850_Brave](https://github.com/hagezi/dns-blocklists/assets/61750641/590fd283-315a-43d2-aad3-dc51ff473a5a)

**Comment by userforsource** [comment]
It does not because. I have tried by installing fb lite and used that for a while.

**Comment by hagezi** [comment]
Breaks the Facebook registration and therefore no longer included in the Ultimate.

@xRuffKez

**Comment by xRuffKez** [comment]
> Breaks the Facebook registration and therefore no longer included in the Ultimate.
> 
> @xRuffKez 

Confirmed breakage!

**Comment by xRuffKez** [comment]
> It does not because. I have tried by installing fb lite and used that for a while.

When you need to verify your Phonenumber on registration, you cannot proceed until mqtt-mini is unblocked.

**Comment by userforsource** [comment]
Ok i have not registered on fb so i did not face this issue. I think we can close this.
