### ISSUE TITLE
Multi + TIF lists

### ISSUE THREAD

**Issue by nightznero** [hagezi/dns-blocklists#2307]
Helloz HaGi,

I would like to ask, TIF list(s) is partially added in all of Multi lists,from light to ulti.

If using Pro++,adding TIF Medium does job or Pro++ covers 80/90% medium list and only full tif is way to go?

Best Regards,NIGHTZNERO.

**Comment by hagezi** [comment]
If your AdBlocker allows it, then combine the TIF with all lists, if this is too large, then with the TIF medium.

| List | Entries | from TIF included | from TIF medium included | 
|:---|:---|:---|:---|
| Light | 68936 | 14705 | 6663 |
| Normal | 135958 | 24766 | 14238 |
| Pro | 214684 | 41474 | 16811 |
| Pro++ | 249259 | 54832 | 20347 |
| Ultimate | 304949 | 90237 | 46267 |
