### ISSUE TITLE
Personal List found in RPZ folder

### ISSUE THREAD

**Issue by JonMurphy** [hagezi/dns-blocklists#2309]
Over the past week or two I've been experimenting with the various hagezi RPZ lists.  And I started to gather some very simple metrics.  On my local network the most used RPZ seems the be hagezi `personal.txt`.

I looked at the https://github.com/hagezi/dns-blocklists README and did not find a section for **Personal**.  And I was going to ask for a small paragraph describing this list.  

But I found a mention in the hagezi GitHub Issues area under Issue #2203.  Is this really disappearing?  

It definitely works VERY well for me and I'd hate to see it go!  Is there something that will replace it?

Here are my metrics over the past week:
```
[root@ipfire ~] # grep "info: rpz: applied" /var/log/messages |
  awk ' { print $10 }' | sort | uniq --count | sort --numeric-sort --reverse
  13571 [zzPersonalHZ]
   1893 [AppleTrkrHZ]
   1253 [AmazonTrkrHZ]
    442 [PopUpAdsHZ]
    139 [ProxyBypassHZ]
     74 [HosterHZ]
     58 [GamblingHZ]
     32 [TIFmedHZ]
     12 [tldHZ]
      5 [NotSafeSearchHZ]
```

**EDIT**:  I did see your post "I integrated the wildcard rules into my build system some time ago." but I don't know what that means.  Where did those URLs end up??

**Comment by hagezi** [comment]
The personal list has been obsolete for several months. The light is the new personal. You should switch to light.

**Comment by hagezi** [comment]
I will remove the personal list with the next release.

**Comment by hagezi** [comment]
personal list removed.

**Comment by JonMurphy** [comment]
Newbie question here...

I am just starting to experiment with the various lists.  Is Light (and thus the old Personal list) included in all of the various Normal / Pro / Pro++ / Ultimate lists?

**Comment by hagezi** [comment]
Yes ...

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/38e0c129-cdb8-45d0-a72f-8a77269eb9a5)

https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#overview

**Comment by JonMurphy** [comment]
Got it!  I saw the graphic but I did not put two and two together.  Thank you!
