### ISSUE TITLE
starwank.com (NSFW)

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#2311]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

`starwank.com`

### Why should the domain(s) be unblocked?

false positive

**Comment by hagezi** [comment]
Fixed
