### ISSUE TITLE
False positive: www.userlike.com

### ISSUE THREAD

**Issue by sefinek24** [hagezi/dns-blocklists#2312]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?
```
Match found in https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/hagezi/pro.fork.txt:
  userlike.com
  api.userlike.com
  umd.userlike.com
  userlike-cdn-operators.userlike.com
  www.userlike.com
```

![image](https://github.com/hagezi/dns-blocklists/assets/92880265/4b64050c-fc25-4c16-bc21-c43b2bb1d5ac)
![image](https://github.com/hagezi/dns-blocklists/assets/92880265/6db43787-9b29-4f6b-a0c9-85f27a77c6d5)

### Why should the domain(s) be unblocked?

Userlike functions as a live chat service and is a safe website.
https://www.userlike.com/en/

**Comment by hagezi** [comment]
Thanks @sefinek24, will be removed.

**Comment by hagezi** [comment]
fixed.
