### ISSUE TITLE
pla.fwdcdn.com

### ISSUE THREAD

**Issue by Fqwe1** [hagezi/dns-blocklists#2318]
### Which domain(s) should be blocked?

pla.fwdcdn.com

### Why should these domain(s) be blocked?

Event tracking

**Comment by hagezi** [comment]
**ref:** https://slayterdev.github.io/tracker-radar-wiki/domains/fwdcdn.com.html

`pla.fwdcdn.com/api/event`

Sites:
```
sinoptik.ua
ua.sinoptik.ua
www.ukr.net
ukrinform.net
www.ukrinform.net
```
