### ISSUE TITLE
Is phishtank.org part of the HaGeZi blocklist?

### ISSUE THREAD

**Issue by Alex67693** [hagezi/dns-blocklists#2319]

**Comment by hagezi** [comment]
Yes, covered via https://phishing.army/ and Co in TIF and TIF medium:
```
phishfort-hot
https://phishing-filter.pages.dev/phishing-filter-hosts.txt
https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/hosts.txt
https://phishing.army/download/phishing_army_blocklist.txt
https://phishing.army/download/phishing_army_blocklist_extended.txt
https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/phishing/domains
```
See, also:
https://github.com/hagezi/dns-blocklists/blob/main/sources.md
https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources

**Comment by hagezi** [comment]
@Alex67693 The TIF is of course not a real-time feed, it is updated every 24 hours. Phishing domains are sometimes dead faster than they end up on the list.

**Comment by hagezi** [comment]
@Alex67693 So if you find them in PT and Co they will be on the TIF at the next update, unless they are false positive domains. So you don't have to open an issue if you find them on one of these phishing lists ;)
