### ISSUE TITLE
False Positive: mobile.pipe.aria.microsoft.com

### ISSUE THREAD

**Issue by Rage-X** [hagezi/dns-blocklists#233]
Blocks my Outlook email from sending via Outlook app. Multi Pro++.

![Screenshot_20230122_204511_Chrome](https://user-images.githubusercontent.com/16078559/213916523-e50e0d47-2524-462b-8d3d-b1931b180fd7.jpg)

**Comment by hagezi** [comment]
Thanks, checked and fixed in all lists. I had checked this before, there were no restrictions, but currently I could reproduce it. This seems to be mandatory in newer app versions.

**Comment by hagezi** [comment]
Updated lists are live in NextDNS.
