### ISSUE TITLE
cf.aliyun.com

### ISSUE THREAD

**Issue by nichgit** [hagezi/dns-blocklists#2330]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Diversion

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

cf.aliyun.com

### Why should the domain(s) be unblocked?

https://www.visaforchina.cn/#/nav/applications/applicationFormSection0?visacenterCode=MUC2&request_locale=en_US&site_alias=MUC2_EN
It prevents the "Please slide to verify" widget from working on the Chinese visa application landing page. Cannot progress any further without this slider working.

**Comment by hagezi** [comment]
Fixed
