### ISSUE TITLE
Sources for each blocklist

### ISSUE THREAD

**Issue by MadSpindel** [hagezi/dns-blocklists#2333]
Would it be possible to split up sources.md into one sources.md for each blocklist? For example, I would like to see which sources are used in TIF Medium.

**Comment by hagezi** [comment]
No, see: https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources

**Comment by MadSpindel** [comment]
Thanks! Could you also post the sources for TIF Full?

**Comment by hagezi** [comment]
@MadSpindel The TIF lists are now also displayed in the build statistics again, they should have appeared there, but I had a bug in the build system. I have now fixed it.

https://github.com/hagezi/dns-blocklists/blob/main/statistics.md#tifmedium
https://github.com/hagezi/dns-blocklists/blob/main/statistics.md#tif
