### ISSUE TITLE
unblock collect.media.jio.com

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2334]
### Which AdBlocker/DNS cloud service do you use?

NextDNS, RethinkDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

collect.media.jio.com

### Why should the domain(s) be unblocked?

Without that domain allowed you can't play anything on that app i have checked manually.
https://play.google.com/store/apps/details?id=com.jio.jioplay.tv

**Comment by hagezi** [comment]
@Alex-302 fyi, also blocked in Adguard DNS.

**Comment by hagezi** [comment]
@userforsource Fixed in https://github.com/hagezi/dns-blocklists/commit/0244103a354974d8d671c01f0e2dda4c845915a3

**Comment by userforsource** [comment]
Have you unblocked that domain.

**Comment by hagezi** [comment]
> Have you unblocked that domain.

Yes

**Comment by userforsource** [comment]
I find after the newest update you can play videos
New domain added https://tv.media.jio.com
And blocking that domain https://collect.media.jio.com still plays videos.

**Comment by hagezi** [comment]
`tv.media.jio.com` is not blocked. Should I block `collect.media.jio.com` again?

**Comment by userforsource** [comment]
Yes you can actually.

**Comment by hagezi** [comment]
@Alex-302: false alarm, domain can apparently remain blocked. Sorry ...
