### ISSUE TITLE
Paypal 2FA does not work with Hagezi Pro++(caused by the NextDNS block page)

### ISSUE THREAD

**Issue by skariko** [hagezi/dns-blocklists#2335]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

*.browser-intake-datadoghq.com
*.qualtrics.com

### Why should the domain(s) be unblocked?

The PayPal **app** on Android will not allow you to enter the 2FA if these two domains are locked. If unlocked, however, everything works correctly.

**Comment by hagezi** [comment]
@xRuffKez Can you please check under Android whether and which domains exactly lead to this behaviour? Thank you!

I can't reproduce the problem on iOS.

**Comment by hagezi** [comment]
@skariko Can you please test whether it works with unblocking `*.siteintercept.qualtrics.com` alone.

**_It is important that you clear the DNS cache of the smartphone after unblocking and before the test. Also switch flight mode on and off.
Even if you have ticked the box, make sure that the block page in NextDNS is not activated._**

**Comment by skariko** [comment]
> @skariko Can you please test whether it works with unblocking `*.siteintercept.qualtrics.com` alone.
> 
> **Please make sure beforehand that the problem occurs without unblocking.**
> 
> **_It is important that you clear the DNS cache of the smartphone after unblocking and before the test. To do this switch flight mode on and off. Even if you have ticked the box, make sure that the block page in NextDNS is not activated._**

I just checked again and I was looking in the wrong profile, actually in this profile NextDNS "block page" is enabled, sorry.
By removing the flag it works even without unlocking those domains it works even without unlocking anything.

If it is of interest though, I tried it with the flag "block page" enabled and putting only `*.siteintercept.qualtrics.com` in the allowlist seems to work.

**Comment by hagezi** [comment]
And once again caused by the NextDNS block page.

@yokoffing @rs @romaincointepas

**Comment by rs** [comment]
Would you be able to provide some actual URLs on those domains that causes problem with the blockpage so we can investigate?

**Comment by hagezi** [comment]
Thanks @rs, of course this case if `siteintercept.qualtrics.com` is blocked and @yokoffing has also collected some here_
https://github.com/yokoffing/NextDNS-Config#block-page

I also had a case recently, I'll have to see if I can reproduce it again.

**Comment by hagezi** [comment]
@rs 

1. block `fundingchoicesmessages.google.com`
2. activate the block page
3. go to `https://stadt-bremerhaven.de/` in the mobile browser
4. an AdBlock detection banner is displayed at the bottom of the page
5. deactivate the block page
6. delete the DNS cache of the mobile device
7. call up the page again
8.. The adblock detection banner is no longer displayed and the page can be used normally with the blocked domain `fundingchoicesmessages.google.com`

**Comment by hagezi** [comment]
> Cannot reproduce on several Android Devices.

Thanks, it's the NextDNS block page ...

**Comment by hagezi** [comment]
The same problems also occur in ControlD if the block response is set to Custom or Branded.

**Comment by pictosun** [comment]
What browser is this you're using here?

> ![image](https://private-user-images.githubusercontent.com/104343908/312576641-926a160b-eaab-44b5-bbad-f851c7b4b4c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDEwODcsIm5iZiI6MTcxMzIwMDc4NywicGF0aCI6Ii8xMDQzNDM5MDgvMzEyNTc2NjQxLTkyNmExNjBiLWVhYWItNDRiNS1iYmFkLWY4NTFjN2I0YjRjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNzA2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzNhMThhYTE2MGM0MDYwNzdkNTM3YmE0ZjFhZDlkNzQyNGJjMjVlZTc2N2VhYWE3ZmU2YTQ0NTIzZWQzMGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.59F4NRbfYmnW6FgZojJ4EHicxvWUoE16SEorvTKgIBQ)

**Comment by hagezi** [comment]
DuckDuckGo Private Browser

**Comment by hagezi** [comment]
FYI:

Furthermore, there is a problem with PayPal 2FA under iOS with Safari if you have activated the extended tracking protection (`Settings > Safari > Advanced > Extended Tracking and Identification Protection`)
