### ISSUE TITLE
api.mumuglobal.com

### ISSUE THREAD

**Issue by Uranite** [hagezi/dns-blocklists#2336]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

api.mumuglobal.com

### Why should the domain(s) be unblocked?

Can't install android emulator mumu player with it blocked
![nemu-downloader_NVZzAeHunw](https://github.com/hagezi/dns-blocklists/assets/62639703/b12753a7-61ae-47e2-aee2-ee1d632a3f57)

**Comment by hagezi** [comment]
Thanks @Uranite, will be removed.
