### ISSUE TITLE
theCut: Find Barbers Anywhere

### ISSUE THREAD

**Issue by AlmightyHeretic** [hagezi/dns-blocklists#2337]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

api.thecut.co

### Why should the domain(s) be unblocked?

While the domain is blocked you can't login or use the service at all. The service is for finding and scheduling appointments with barbers.

![thecutfail](https://github.com/hagezi/dns-blocklists/assets/62065336/97f88e12-d3fa-4129-8d38-ede6d773e20c)

[https://www.thecut.co/](url)

**Comment by hagezi** [comment]
Thanks, will be removed.
