### ISSUE TITLE
Linux Malware

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#2339]
### Which domain(s) should be blocked?

b.9-9-8.com

### Why should these domain(s) be blocked?

[CadoSecurity](https://www.cadosecurity.com/spinning-yarn-a-new-linux-malware-campaign-targets-docker-apache-hadoop-redis-and-confluence/)

**Comment by hagezi** [comment]
@topminipie already blocked in TIF and TIF medium.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/d87f59e6-9f20-47f1-92cb-e0a670b744da)
