### ISSUE TITLE
1984 Hosting infrastructure in TIF

### ISSUE THREAD

**Issue by hawk7000** [hagezi/dns-blocklists#2347]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

RPZ

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

mx1.1984.is
mx2.1984.is
ns1.1984.is
ns2.1984.is
ns1.1984hosting.com
ns2.1984hosting.com

### Why should the domain(s) be unblocked?

While I am not familiar with the background of why these names were recently added to TIF, considering this is just infrastructure (dns, smtp) of a hosting provider it seems unlikely that these names themselves belong in TIF.
It is of course entirely possible that they have/had customers that belong in one list or another, but that really ought to be based on the domain names used by said customers.

**Comment by hagezi** [comment]
Thanks @hawk7000, via `rodanmaharjan_threatintelligence_threatgroups_darkcaracal.txt` 
ping @rodanmaharjan

Will be removed ...

**Comment by rodanmaharjan** [comment]
@hawk7000  When extracting the IOC for the feed from various sources, there are often numerous false positives, including DNS and SMTP entries, which can complicate the list. Sanitizing the list can be time-consuming. Nevertheless, thank you for acknowledging the issue. I have now removed the domains from the list.
