### ISSUE TITLE
res.wx.qq.com

### ISSUE THREAD

**Issue by YZRW** [hagezi/dns-blocklists#2348]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Gambling

### Which domain(s) should be unblocked?

res.wx.qq.com

### Why should the domain(s) be unblocked?

This is not a gambling website, it is used to load the pictures attached to the Weixin Official Accounts Platform.
Blocking it will prevent images from loading, for example: https://mp.weixin.qq.com/s/P_EYQxOEupqdU0BJMRqWsw

**Comment by hagezi** [comment]
Thanks @YZRW, will be removed, via `alsyundawy_trustpositif_gambling_indonesia.txt` @alsyundawy

**Comment by alsyundawy** [comment]
noted
