### ISSUE TITLE
Some Samsung apps don't work as intended

### ISSUE THREAD

**Issue by ottoosworth** [hagezi/dns-blocklists#2349]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

sspapi-prd.samsungrs.com

### Why should the domain(s) be unblocked?

When this domain is blocked:
1. Samsung Galaxy store doesn't save new privacy policy options when it starts and hence restarts giving you the option to accept the new terms again and keeps repeating in a cycle until this domain is added to white list.
2. Samsung Galaxy Game Launcher also fails to display list of apps to customise their performance profiles when this domain is being blocked.
3. There may be other Samsung related services that are also not working working but as these two were the ones I use I can only comment on them

**Comment by ottoosworth** [comment]
It's blocked by every other list too tbf, maybe i haven't seen any ads but maybe it's better to leave it blocked, I guess I'll close this for now

**Comment by hagezi** [comment]
@ottoosworth Blockpage in NextDNS enabled?
