### ISSUE TITLE
Blocks Shark Robot Vacuum

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#235]
Using Pro Plus on ControlD, thanks for all your hard work!

Noticed my Shark robot vacuum didn't run as scheduled for the last couple days since I switched to the Pro Plus list.

Did some debugging and looks like it's related to the *.aylanetworks.com domain:

![2023-01-22_20-01-35](https://user-images.githubusercontent.com/57188837/213950681-3f2dcdff-dde6-400f-a941-c31a74d328dd.png)

Sample URL: rv1100aa-xyz-device.aylanetworks.com

Did a grep on the Pro++ List and found these entries:
```
0.0.0.0 ads-apiv1-sharkue1.aylanetworks.com
0.0.0.0 ads-field.aylanetworks.com
0.0.0.0 ads-field-1a2039d9.aylanetworks.com
0.0.0.0 ads-field-39a9391a.aylanetworks.com
0.0.0.0 ads-owlue1.aylanetworks.com
0.0.0.0 ads-sharkue1.aylanetworks.com
0.0.0.0 ads-throttle-sharkue1.aylanetworks.com
```

The Pro List does not contain any *.aylanetworks.com entry.

Did a search and found that at least `ads-field-39a9391a.aylanetworks.com` is a valid domain: https://github.com/DoctorMcKay/HSPI_SharkRobot/blob/master/HSPI_SharkRobot/AylaClient.cs#L16

There's a high chance that all of the *.aylanetworks.com entries are harmless and essential to vacuum <=> Internet integration (https://www.businesswire.com/news/home/20200714005134/en/Ayla-Networks-Partners-with-SharkNinja%C2%AE-to-Provide-Exceptional-Consumer-Experience) and I'd like to see if *.aylanetworks.com can be whitelisted entirely. If not no big deal, I can always downgrade to the Pro list :)

Thanks very much for reading and for your time!

EDIT: found more info on some of the other entries -

`ads-field.aylanetworks.com`

"If the integration frequently disconnects and you have an ad blocker runner like [Pi-hole](https://pi-hole.net/) or [AdGuard](https://adguard.com/) add `ads-field.aylanetworks.com` to the Allow list . This domain is needed for the connection and can be part of the automatic blocking because of ads being part of the subdomain."

https://www.home-assistant.io/integrations/sharkiq/

https://www.reddit.com/r/homeassistant/comments/si3oq7/shark_iq_robot_vacuum_integration_stopped_working/

`ads-field-1a2039d9.aylanetworks.com`

https://github.com/mbevand/owlet_monitor/blob/master/owlet_monitor#L24

**Comment by durablenapkin** [comment]
Went through my ControlD logs and only the `rv1100aa-xyz-device.aylanetworks.com` domain is appearing as being blocked, which is strange because the *.aylanetworks.com isn't being blocked by your Pro++ list.

Perhaps this is an issue on ControlD's end on how they parse your lists...

**Comment by hagezi** [comment]
Hi,

Thank you for this excellent analysis and documentation. Accordingly, I am of the opinion that whitelisting *.aylanetworks.com is the right thing to do to prevent possible effects on other functions.

Thanks for your support,
Gerd

**Comment by hagezi** [comment]
Removed.

ping @badmojr

**Comment by durablenapkin** [comment]
Scheduled run ran successfully this morning, thank you!
