### ISSUE TITLE
Suggestion, New list (FR financial fraud websites)

### ISSUE THREAD

**Issue by raphaelp-github** [hagezi/dns-blocklists#2351]
### Which domain(s) should be blocked?

https://www.data.gouv.fr/fr/datasets/r/d2d9df6d-1cd2-41a8-96f5-684cb3057ecb (CSV based)

### Why should these domain(s) be blocked?

Hello,

Could you please add the sites blacklisted by the FR FMA https://www.data.gouv.fr/fr/datasets/listes-noires-des-entites-non-autorisees-a-proposer-des-produits-ou-services-financiers-en-france/? Data.gouv.fr regularly updates the list in CSV format.

Thank you for your help!

**Comment by hagezi** [comment]
Thanks @raphaelp-github, but 1863 valid domains, 1169 dead domains ...

Such domains are sometimes dead faster than they are on the list. It might make sense to include them in a realtime feed, but not for a list that is updated every 24 hours.

I'll have another look at the list in a few days to see if there are any domains that survive longer ...

**Comment by hagezi** [comment]
I swapped the links.

**Comment by hagezi** [comment]
I have added the list to the fakelist (included in Pro++, Ultimate, TIF and TIF medium). Let's see how long the Domains live.

https://github.com/hagezi/dns-blocklists#fake

**Comment by raphaelp-github** [comment]
@hagezi Yes, this list contains dead domain names. The list is special. It is fed by a financial authority that is only interested in adding new domain names. Its role ends there. That's why there are so many dead domains (normal, since scammers drop their domains as soon as they're spotted by the authorities...). Unfortunately, we can't expect much more from the authority that updates the list (it's already a good thing to add domain names to this list).

The site indicates a daily update of the CSV and I don't know what's technically best to integrate it into your lists (24hrs or real time). You'd have to find something to do on that to link to the CSV.

I'm waiting the update for https://github.com/hagezi/dns-blocklists#fake.

Thanks!
