### ISSUE TITLE
Remove GitHub Raw and GitLab Raw used as subscription URL

### ISSUE THREAD

**Issue by piquark6046** [hagezi/dns-blocklists#2353]
To start reducing load and bandwidth usage about requesting your hostlists, please consider removing GitHub Raw and GitLab Raw used as subscription URL in README.md.
Of course, the above action does not help the purpose directly.
However, new user and user who re-installs your hostlist will use the subscription URL using jsDelivr CDN instead of them.

**Comment by hagezi** [comment]
Thanks @piquark6046, but I like to offer an alternative, the user can decide from where he wants to load the list. What I can do is swap the links so that Github and Gitlab are displayed as mirrors.

**Comment by hagezi** [comment]
I swapped the links.

**Comment by piquark6046** [comment]
Hmm... It is reverted. Please take a look.

**Comment by hagezi** [comment]
Yes, I turned it back because the jsDelivr links don't always provide the current version, I have no idea if something is cached sometimes. I had this with @latest, but I also noticed it with @main.

**Comment by piquark6046** [comment]
Please report it to jsDelivr even if you use `@latest`.
