### ISSUE TITLE
Block unidentifiedanalytics.web.app

### ISSUE THREAD

**Issue by twisty-thrifty205729** [hagezi/dns-blocklists#2359]
### Which domain(s) should be blocked?

`unidentifiedanalytics.web.app`

### Why should these domain(s) be blocked?

Analytics (should likely be blocked in pro and onwards)

**Comment by yokoffing** [comment]
What’s the context of the URL? Where does it appear?

**Comment by hagezi** [comment]
Privacy friendly user statistics: https://unidentifiedanalytics.web.app/#/stats/unidentified-analytics-website-data

**Comment by hagezi** [comment]
Since other "privacy friendly analytics" are also blocked, I will include domain.
