### ISSUE TITLE
False Positive [embed.tagboard.com]

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#236]
embed.tagboard.com is required to interact with the question of the day on the following website. "embed.tagboard.com.herokudns.com" is the CNAME on the blocklist.

Example
https://fox11online.com/question/vote-should-the-federal-government-ban-gas-stoves-homes-us-consumer-product-safety-commission-hidden-hazard-climate-impacts-emissions-health-risks-cooking

**Comment by hagezi** [comment]
Thanks, removed.
