### ISSUE TITLE
#2194 blocks many innocent personal websites

### ISSUE THREAD

**Issue by linyinfeng** [hagezi/dns-blocklists#2360]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi LIGHT

### Which domain(s) should be unblocked?

```
# D0G3 and his i-soon ctf friends
0akarma.com
0day.design
anandalue.com
aslower.github.io
bak6ry.cn
branchzero.com
c10udlnk.top
cheverjohn.xyz
clean99.github.io
d-veda.top
d0g3.cn	
dao.ge
demochen.com
diygod.me
dna049.com
elitedj.me
fdrag0n.github.io
flyhigher.top
goushi.me
haipz.com
hicasper.com
hokori.online
hpdoger.cn
hu3sky.github.io
i-meto.com
idealclover.top
ikirby.me
ilcl.cc
imhan.com
ipixeloldc.github.io
jarvisoj.com
jarvisoj.com # i-soon / d0g3	
ku3n.github.io
l1n.wang
lakejason0.wordpress.com
luojia.me
mapan.tech/
mayuko.cn
micblo.com
miigon.net
mikusa.cn
p2hm1n.com
patrilic.top
peter1303.github.io
redtiger.labs.overthewire.org
rm-rf.moe
sendya.me
servernotfound.net
srin.top
thiscute.world
threezh1.com
tianheg.co
tover.xyz
txisfine.cn
usslab.org # university
viosey.com
vircloud.net
waitalone.cn # i-soon / d0g3	
wczf.net
wlvmoo.com
wonz.wang
xctf.org.cn
xlesun.com
xun9er.com
y1nhui.com
zgq.ink
zhangxiaoyao.cn
zuotian.org
```

### Why should the domain(s) be unblocked?

I am not a user of this repository. I open this issue due to <https://discourse.nixos.org/t/an-unofficial-nixos-flakes-book-for-beginners/29561/12>, in which a NixOS user complains that [nixos-and-flakes.thiscute.world](https://nixos-and-flakes.thiscute.world/) is blocked in this block list.

@xRuffKez <https://github.com/hagezi/dns-blocklists/pull/2194> blocks many personal websites. I support part of this PR to block iSoon's website, since it is a spyware vendor. But, "i-soon ctf friends" are just some personal websites of innocent students. As an example, [thiscute.world](https://thiscute.world/) is the domain of personal website of @ryan4yin.

I'd like to say that <https://github.com/D0g3-Lab> and all related websites should not be blocked.
The GitHub organization holds some materials and software for the CTF competition that they co-organized with iSoon, does not mean the members of the organization are participate in any business of iSoon.
D0g3-Lab (道格实验室) is just a student club about network security research in Chengdu University of Information Technology. Unfortunately, their website already dead for two years, here is the [web archive](https://web.archive.org/web/20221004123556/https://www.d0g3.cn/) of their home page.

**Comment by ryan4yin** [comment]
Thanks to @linyinfeng, I'm the author of https://github.com/ryan4yin/nixos-and-flakes-book, which uses the domain https://nixos-and-flakes.thiscute.world/.

https://nixos-and-flakes.thiscute.world/, and my blog https://thiscute.world/en/, and all my friends like https://diygod.me (@DIYgod), https://zgq.ink (@zgq354), https://blog.miigon.net/ (@Miigon), tianheg.co(@tianheg), and many others, are all just ordinary technical bloggers.
We write all kinds of technical and personal articles and documents, which have nothing to do with any Fake, Coins, etc.

It is very unreasonable to add our domain name to the blacklist so rudely. This does not make the Internet safer and cleaner, but turns DNS Block List into a personal cyber attack tool!

**Comment by hagezi** [comment]
Thanks @linyinfeng I'll take care of it right away.

**Comment by zgq354** [comment]
Thanks @linyinfeng, I am the owner of [zgq.ink](https://zgq.ink), is my personal website, and all my friends' domains below is not under iSoon, please remove them from the block list. @hagezi 

```
0day.design
aslower.github.io
branchzero.com
c10udlnk.top
clean99.github.io
d-veda.top
demochen.com
diygod.me
dna049.com
elitedj.me
flyhigher.top
goushi.me
haipz.com
hokori.online
i-meto.com
ikirby.me
ilcl.cc
ipixeloldc.github.io
l1n.wang
lakejason0.wordpress.com
luojia.me
mikusa.cn
peter1303.github.io
rm-rf.moe
sendya.me
servernotfound.net
srin.top
thiscute.world
tianheg.co
tover.xyz
viosey.com
xlesun.com
zhangxiaoyao.cn
zuotian.org
```

**Comment by DIYgod** [comment]
I believe the maintainer should take responsibility for project users and carefully review added domains.

**Comment by Chever-John** [comment]
Same to my website(cheverjohn.xyz) which should not be blocked by this closed issues #2193 

Please reconsider my website (cheverjohn.xyz) which has been mistakenly blocked, as per closed issue #2193. Although this site is outdated and I haven't updated it with new content recently, I believe it's essential to thoroughly review it again, especially considering the responsibilities of DNS blocklists project maintainers:)

**Comment by Elitedj** [comment]
same to my website([elitedj.me](https://elitedj.me/))

**Comment by hagezi** [comment]
I have analyzed the domains.

Fixed in https://github.com/hagezi/dns-blocklists/commit/d05f36ce8a89ebaefd7496d846fefae8f542ec8d

**Comment by xRuffKez** [comment]
https://github.com/hagezi/dns-blocklists/issues/2193#issuecomment-2003883010
