### ISSUE TITLE
BBC scam

### ISSUE THREAD

**Issue by jul059** [hagezi/dns-blocklists#2365]
### Which domain(s) should be blocked?

new-s24.click

### Why should these domain(s) be blocked?

Hosts the same scam as reported with https://github.com/hagezi/dns-blocklists/issues/2341 (passing as BBC instead of La Presse). Has been unblocked for at least a few days.

**Comment by yokoffing** [comment]
FWIW, in USA for me, the site takes so long to load that the connection times out.

**Comment by hagezi** [comment]
> Has been unblocked for at least a few days.

`uk-news.pro` is still blocked in the TIF and TIF medium. Combine the normal lists with a TIF version.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/da297a53-f835-4574-8afb-a7e39471b245)

**Comment by iam-py-test** [comment]
Added to my list, thanks
