### ISSUE TITLE
allow jarvis.testbook.com

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2368]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

jarvis.testbook.com

### Why should the domain(s) be unblocked?

This domain used for analytics.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2300

Thanks, will be removed.

**Comment by hagezi** [comment]
Fixed
