### ISSUE TITLE
Justtrack

### ISSUE THREAD

**Issue by trackerct** [hagezi/dns-blocklists#2370]
### Which domain(s) should be blocked?

justtrack-logs.justtrack.io
sdk-api.justtrack.io
prod.adjoe-programmatic.com

### Why should these domain(s) be blocked?

Ads and Tracker.

**Comment by hagezi** [comment]
Thanks @trackerct, `justtrack.io` is only blocked in the aggressive lists so far. I will block it in the non-aggressive lists as well.

`adjoe-programmatic.com` will also be added to all lists.
