### ISSUE TITLE
Request missed lists

### ISSUE THREAD

**Issue by nightznero** [hagezi/dns-blocklists#2373]
Helloz HaGi,
from Your sources
![Screenshot_20240320_083211](https://github.com/hagezi/dns-blocklists/assets/61750641/cf040bb0-4e6a-4f71-9658-a59d96b094ee)

 i noticed You use Ultimate Adblock lists from AdAvoid so here is one more list created by them
**AdBlock Ultimate - Ultimate Security Filter**
`https://filters.adavoid.org/ultimate-security-filter.txt`

and also, _CERT.pl_ lists has been changed to version v2 so here is souces:
**ADB-Syntax**:`https://hole.cert.pl/domains/v2/domains_adblock.txt`
**Domains**:`https://hole.cert.pl/domains/v2/domains.txt`
**Hosts**:`https://hole.cert.pl/domains/v2/domains_hosts.txt`
**RPZ**:`https://hole.cert.pl/domains/v2/domains_rpz.db`
Would be awesome if You could add em. Best Regards, NIGHTZNERO.

**Comment by hagezi** [comment]
Thanks @nightznero, will be added.

**Comment by hagezi** [comment]
Added in https://github.com/hagezi/dns-blocklists/commit/5204e621bf112be200d564da70299bf9028e0d5f

**Comment by iam-py-test** [comment]
> AdBlock Ultimate - Ultimate Security Filter

This filter is an almost exact copy of uBlock Origin's badware filter (I can not recall who first informed me of this so can not credit them, but I can easily confirm it by opening the two side-by-side). The only difference is they replaced shorthand filters ($doc, $3p) with longer versions ($document, $third-party), and a couple other minor things.
Thank you

**Comment by hagezi** [comment]
Thanks @iam-py-test I was wondering why all domains were already on the TIF.
