### ISSUE TITLE
Ads on spiegel.de

### ISSUE THREAD

**Issue by ybenme** [hagezi/dns-blocklists#2374]
### Which domain(s) should be blocked?

I am new to this so not really sure what domains need to be blocked, but there are ads on spiegel.de 
<img width="1217" alt="Screenshot 2024-03-20 at 16 06 42" src="https://github.com/hagezi/dns-blocklists/assets/49727126/4723bc97-cf9b-4bf1-b521-436f56e47470">

### Why should these domain(s) be blocked?

Advertising

**Comment by hagezi** [comment]
Thanks @ybenme ,but I don't see any ads, tested with `Light`. Something is wrong with your DNS configuration.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/7c6e1319-085d-404d-9d54-620ca8abede6)

**Comment by ybenme** [comment]
Thanks, that might be. 
However those ads on the side and top of the picture I posted are the only ads I see on any web page. 
What might I have configured incorrectly. Or is that better asked in a pihole forum?

Thanks again!

**Comment by hagezi** [comment]
@ybenme A frequent source of errors is an IPv6 bypass, IPv6 DNS queries then bypass the Pi-hole. If you have configured the Pi-hole as DNS in the router, then both the local IPv4 address and the local IPv6 address of the Pi-hole must be specified.

Please give me some details about your setup.
