### ISSUE TITLE
False Positive: binarypiano.com

### ISSUE THREAD

**Issue by Algorithm5838** [hagezi/dns-blocklists#238]
binarypiano.com is blocked in Pro, it's not phishing nor malicious.

**Comment by hagezi** [comment]
Thanks, its flagged:

https://www.virustotal.com/gui/url/d4cec495b41cf39d6f6db6587ac39c31fe0772ebfbf41e453f2a10d4a5b1e2d5

Blocked by Cloudflare and Quad9 SecureDNS. Found on different phishing lists.

**Comment by hagezi** [comment]
Thanks, i will check.

**Comment by drego85** [comment]
The domain is on the phishing lists as a result of this report: https://www.phishtank.com/phish_detail.php?phish_id=7949729

I requested Phishtank to review the report, it's obviously a false positive!

**Comment by tholman** [comment]
Weird, I have the 3rd party unpkg script on there for tone.js, but I can't imagine that'd be it. I guess there's minimal visual content, but 🤷‍♂️ no data collection/ads/spam or anything.

**Comment by drego85** [comment]
@tholman I think it's just a mistake!

**Comment by hagezi** [comment]
Fixed in my lists.

@tholman I have also requested removal from Virustotal.

Thanks to all who were involved.

**Comment by drego85** [comment]
Once removed from PhishTank, it will consequently be removed from all other sources!

**Comment by hectorm** [comment]
I confirm that once it is removed from Phishing Army, it will also be automatically removed from hBlock.

**Comment by drego85** [comment]
Ok, PhishTank removed the false positive! 😉

**Comment by notracking** [comment]
> Ok, PhishTank removed the false positive! 😉

Then it will also be removed from our list, added it to the whitelist anyways.
