### ISSUE TITLE
Fitbit App Gallery & Spotify views unusable 

### ISSUE THREAD

**Issue by thoughtfuldata** [hagezi/dns-blocklists#2386]
I use nextDNS with PRO and PRO++( issue effects both. I am using an Android 

When attempting to use those Fitbit app features, I get a "looks like there is no internet connection." Turning off Nextdns makes it work again. I do not have block page enable

**Comment by hagezi** [comment]
The log is your friend. What is being blocked? Which domain is causing the problem?

**Comment by thoughtfuldata** [comment]
I found a possible solution[here](https://help.nextdns.io/t/m1hltgn/impaired-in-app-fitbit-functionality)  Seems like I have to whitelist  `www.google-analytics.com` but wouldn't that reenable like 40% of tracking? Is there anything else I can do?

**Comment by hagezi** [comment]
Yes, number 1 tracker, that is definitely something for the personal allowlist.
