### ISSUE TITLE
Most Abused TLD's Whitelist

### ISSUE THREAD

**Issue by SpidaXS** [hagezi/dns-blocklists#2387]
Hello HaGeZi, hope all has been well.

I was wondering, for the Abused TLD's Blocklist, why cant you just offer a seperate whitelist containing all the entries from the Adguard List for all the software/syntax's that don't support it?  Thanks.

**Comment by hagezi** [comment]
Thanks @SpidaXS, an AdBlock allowlist will be added with the next release. However, if you take a look at the exclusions, very few users need them. Most users only unblock what they really need. I'll let you know when the allowlist is online.

**Comment by SpidaXS** [comment]
Thanks for your work HaGeZi, much appreciated. Yes true, its just a shame that Pi-hole and Technitium don't support AdBlock whitelist and blacklist rules in the same file.

**Comment by hagezi** [comment]
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-adblock-allow.txt
