### ISSUE TITLE
TIF and Dandelion Sprout's Anti-Malware List

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2391]
If I'm using the Full TIF list, do I still need to use Dandelion Sprout's Anti-Malware List as per the recommendations section?

I'm running AGH on a RPi.

**Comment by hagezi** [comment]
Yes, that's my recommendation. The list contains special rules in AdGuard syntax that cannot be mapped in simple AdBlock syntax.

**Comment by Dynamic5912** [comment]
Is his list not included already in the TIF list then?

**Comment by hagezi** [comment]
Yes, but my list is compatible with all AdBlockers, so only the rules that can be converted to simple AdBlock have been adopted. As mentioned, the list contains rules in AdGuard format that have not been adopted. Hence the recommendation to also use the list in AdGuard.

**Comment by Dynamic5912** [comment]
Thank you sir! Your hard work is appreciated as always!

Can the new Aggressive TLD list also be used with AGH? It only lists PiHole and some others currently.

**Comment by hagezi** [comment]
In AGH use the AdGuard spam TLD list. It contains everything.

**Comment by Dynamic5912** [comment]
Does that list also include allowed/whitelisted sites though?

**Comment by hagezi** [comment]
Yes

**Comment by Dynamic5912** [comment]
OK. Could I use the other list if I don't want the white listing?

**Comment by hagezi** [comment]
Yes
