### ISSUE TITLE
block argo.svcmot.com

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2394]
### Which domain(s) should be blocked?

argo.svcmot.com

### Why should these domain(s) be blocked?

This is a motorola domain for which reason is totally unknown to me i have blocked it from the beginning of my purchase i have 3devices from that brand. Blocking it does not have any issues with updates or anything. I assume it is for tracking. I have tested for it 2years. I have blocked it manually.

**Comment by hagezi** [comment]
Ref: https://forums.lenovo.com/t5/motorola-one-fusion/what-to-know-about-this-url/m-p/5118436

**Comment by hagezi** [comment]
Thanks, I will only block this in the aggressive lists (Pro++ and Ultimate) for the time being.

**Comment by userforsource** [comment]
> Ref: https://forums.lenovo.com/t5/motorola-one-fusion/what-to-know-about-this-url/m-p/5118436

This was me.
