### ISSUE TITLE
block sgepodownload.mediatek.com

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2396]
### Which domain(s) should be blocked?

sgepodownload.mediatek.com

### Why should these domain(s) be blocked?

I find it in a device with mediatek chipset i find no issues if i block this domain or allow this. So this domain is most likely used for some form of tracking reasons.

**Comment by hagezi** [comment]
Currently only blocked in Ultimate, will also block the domain in Pro++.

**Comment by xRuffKez** [comment]
This Domain supplies GPS data updates.
