### ISSUE TITLE
block spam website

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2397]
### Which domain(s) should be blocked?

ggogle.de
iosvpndefender.com

### Why should these domain(s) be blocked?

Spam
And typo

**Comment by iam-py-test** [comment]
>  `iosvpndefender.com`

I am sorry, but this domain does not appear to resolve. Is there a specific subdomain which is used, or has it just been taken down since you initially discovered it?
Thank you

**Comment by hagezi** [comment]
Yes, the domain has no A-Record but delivers `NOERROR`. There will probably be some subdomains that have an A-Record. Not uncommon with "such" domains.

**Comment by userforsource** [comment]
> > `iosvpndefender.com`
> 
> I am sorry, but this domain does not appear to resolve. Is there a specific subdomain which is used, or has it just been taken down since you initially discovered it/opened this issue? Thank you

Probably because it shows virus pop up in a iphone.

**Comment by userforsource** [comment]
> > > `iosvpndefender.com`
> > 
> > 
> > I am sorry, but this domain does not appear to resolve. Is there a specific subdomain which is used, or has it just been taken down since you initially discovered it/opened this issue? Thank you
> 
> Probably because it shows virus pop up in a iphone.

But it was opened randomly while clicking on a news article and 3website opened just becuase i have dns i checked the domains.
