### ISSUE TITLE
TIF IP list use case

### ISSUE THREAD

**Issue by HellboyPI** [hagezi/dns-blocklists#2398]
DNS blockers block domains. I presume your IP blocklist is for a firewall and content blockers, not for DNS blockers. Or am I missing something? 😄

**Comment by hagezi** [comment]
@HellboyPI This is correct, but the AGuard Home version can be used in AdGuard Home. All domains that resolve to the IP are then blocked. A practical thing ...

**Comment by hagezi** [comment]
I have adapted the readme.

**Comment by xRuffKez** [comment]
But disable Ipv6 resolving in AGH.
