### ISSUE TITLE
block api.howlapm.com

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2399]
### Which domain(s) should be blocked?

api.howlapm.com

### Why should these domain(s) be blocked?

I could not find anything it does i have blocked and no issues occurred.

**Comment by hagezi** [comment]
I can't categorise the domain at all, what kind of API does it provide, where is it triggered from?

Related to LAPM (Lean Agile Portfolio Management)? ;)

**Comment by hagezi** [comment]
It is some "china domain", do you have more details. I have not found any.

**Comment by hagezi** [comment]
A few modded APKs seem to be phoning it in ...

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/9e1d9ef9-b1f0-4ac5-bb26-b890a83b520c)

**Comment by hagezi** [comment]
I block the domain in the aggressive lists, since it is relatively high up in the umbrella top list, we should soon see if this try and error blocking has any restrictions.
