### ISSUE TITLE
Suggestion, New list (FR gambling websites)

### ISSUE THREAD

**Issue by raphaelp-github** [hagezi/dns-blocklists#2400]
### Which domain(s) should be blocked?

https://ressources.anj.fr/blocage_sites_illegaux/blocage_sites_illegaux.csv

### Why should these domain(s) be blocked?

Hello,

Could you please add the sites blacklisted by the French online gambling regulatory authority (ANJ) https://ressources.anj.fr/blocage_sites_illegaux/blocage_sites_illegaux.csv? The authority seems to update its db several times a month (latest: December 2023, but still current).

Thanks for your help!

**Comment by hagezi** [comment]
Will be added on next release.
