### ISSUE TITLE
Allowlist - block URL

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2406]
Hi,

If I enable your Allowlist for referral URL's, it enables access to ad.doubleclick.net, for example. 

Is there a way I can block ad.doubleclick.net even though it's in the Allowlist?

Running AGH on a RPi4.

**Comment by jarelllama** [comment]
See `5. Block and unblock individual sites` in https://www.smarthomebeginner.com/adguard-home-configuration-tips/ to block individual domains.

**Comment by hagezi** [comment]
||ad.doubleclick.net^$important

**Comment by hagezi** [comment]
Why are you using the referral allowlist and then blocking one of the most frequently used referral domains?

**Comment by Dynamic5912** [comment]
> `||ad.doubleclick.net^$important`

That doesn't seem to work - when checking the domain it still sees it in the allow list and it is still resolvable.

**Comment by xRuffKez** [comment]
> > `||ad.doubleclick.net^$important`
> 
> That doesn't seem to work - when checking the domain it still sees it in the allow list and it is still resolvable.

Rewrite it with nxdomain
