### ISSUE TITLE
block c.webengage.com

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2409]
### Which domain(s) should be blocked?

`c.webengage.com`
`wsdk-files.webengage.com`
`decide.mixpanel.com`

### Why should these domain(s) be blocked?

This is used for tracking.

**Comment by hagezi** [comment]
`c.webengage.com` - referral domain - https://github.com/hagezi/dns-blocklists/wiki/FAQ#referral

`wsdk-files.webengage.com` - already blocked in all lists
`decide.mixpanel.com` - already blocked in all lists
