### ISSUE TITLE
False Positive [www.yasir252.com]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#241]
Link : www.yasir252.com

I think it makes more sense to go into a piracy blocklist than into a malware / ads and tracker blocklist.

**Comment by hagezi** [comment]
Yes. ;)

**Comment by hagezi** [comment]
Fixed.

**Comment by MagicalAlchemist** [comment]
nice, thank you.

**Comment by iam-py-test** [comment]
This appears to come from my blocklist, I'll look into unblocking

**Comment by iam-py-test** [comment]
Short answer: I'm hesitant to unblock it, but so far I don't see any evidence the site it's self is malicious. However, it does host quite a few malicious ads.
Long answer:
The site's a complete adwall and I spent half my time clicking fake download buttons before I found the real one<sup>[[1]](https://tria.ge/230714-tf54paga3y/behavioral1)</sup>.
The file I downloaded claimed to be Glasswire (which was what I tried to download). However, while I did get a Glasswire setup window, I did not ever end up with it installed. Instead, I ended up with what acted like malware <sup>[[1]](https://tria.ge/230714-tf54paga3y/behavioral1)</sup>. Oddly, that executable does appear to be the legitimate Glasswire <sup>[[2]](https://www.virustotal.com/gui/file/cc6174aa776a0b1bc29c8a466de095e281cc9a238dee7363196dbbdbb7bb2873/details)</sup>. In fact, it is identical to version 2.3.449 from the legitimate Glasswire website. The "crack" DLL included gets 0 detection on VT<sup>[[3]](https://www.virustotal.com/gui/file/4c1fa83e0e7b67537cc6fbf2d6ff652c63d3121e12564f97ad5f242527b08492/details)</sup>, and without any evidence to the contrary (and I lack the skills to reverse engineer it), I must assume it too is safe. Both with and without that DLL, it seems to install a legitimate (but broken) version of Glasswire<sup>[[4]](https://tria.ge/230714-t2bf7sgb7z)</sup>. It seems that the Glasswire installer tries to fingerprint the machine it's running on, which is sketchy, however, given that this occurs with just the plain exe installed - which is signed and identical to the one from the website for that version - I guess this is just Glasswire.
This website is blocked by the notracking list (though I am unsure why, and given it is currently unmaintained[[5]](https://github.com/notracking/hosts-blocklists/issues/900), I wouldn't decide based on that factor alone) and detected by 8 engines on VT <sup>[[6]](https://www.virustotal.com/gui/url/deff0e95cdc5cf4b23178d7747ec721836cde91cc0c2ea4eb35b2d56fa4c2c6d/detection)</sup>.
In my opinion, it's not a site I would personally trust (even with a content blocker installed). However, I have commented out the entries blocking it in https://github.com/iam-py-test/my_filters_001/commit/f0dcafa221ebea5886ad7a1139e1758585b16302. If someone can provide more evidence either way, then I will either remove it completely or reblock it.
