### ISSUE TITLE
what is the usage of this domains

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2411]
i find this domains i have blocked but did not faced yet
Can anyone provide information about this domains.
*.footprints-pa.googleapis.com
*.mdh-pa.googleapis.com
*.federatedml-pa.googleapis.com
*.xgapromomanager-pa.googleapis.com
*.signaler-pa.googleapis.com
*.growth-pa.googleapis.com
*.regioninfo-pa.googleapis.com
*.discover-pa.googleapis.com

**Comment by hagezi** [comment]
These are Google APIs, by blocking them you restrict or paralyse one or more functions on your Android phone. You can probably find more information on this in the Google Developer documentation.

**Comment by userforsource** [comment]
I have blocked them but i have not faced any issues hence i can claim that this are not required in day to day task maybe for some kind of tracking or data retaining

**Comment by hagezi** [comment]
That can be good and may suit you, but it's not something to block for everyone.
