### ISSUE TITLE
adserv.ai

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#2412]
### Which domain(s) should be blocked?

adserv.ai

### Why should these domain(s) be blocked?

[VirusTotal](https://www.virustotal.com/gui/ip-address/84.252.143.174/relations)
The domain service [otm-r.ru](https://otm-r.ru/)?

otm-r.ru:
"We have been successfully implementing projects in the field of mobile advertising and marketing in Russia and abroad since 2010."

**Comment by hagezi** [comment]
Already blocked in Pro++ and Ultimate, will be added to the other lists as well.
