### ISSUE TITLE
Idea for tiny optimization of Pro+ Mini list

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#2414]
Seeing how most browsers implement Google's Safe Browsing API, an idea could be to remove domains already flagged by Safe Browsing from the Pro+ Mini list since it's intended for browsers.

I used Elliotwutingfeng's [Inversion DNSBL Blocklist](https://github.com/elliotwutingfeng/Inversion-DNSBL-Blocklists) as a reference for domains flagged by Safe Browsing here:

![image](https://github.com/hagezi/dns-blocklists/assets/91372088/49e9eab1-dc5d-4e46-a714-98808178573d)

The matching entries are few, but this is just an idea.

**Comment by hagezi** [comment]
Thanks @jarelllama, good idea, will implement that in the next release.
