### ISSUE TITLE
Add Yokoffing ControlD Setupup guide

### ISSUE THREAD

**Issue by BourbonCrow** [hagezi/dns-blocklists#2417]
Maybe add this to the readme just like you have a link for his setup guide for NextDNS, he makes relly nice well written guides!
https://github.com/yokoffing/Control-D-Config/

**Comment by hagezi** [comment]
Thanks @BourbonCrow, I hadn't realised that yet, of course I'll add the recommendation. Great work @yokoffing.

**Comment by hagezi** [comment]
added
