### ISSUE TITLE
Deny https://fling-trainer.com

### ISSUE THREAD

**Issue by tkien931** [hagezi/dns-blocklists#2425]
### Which domain(s) should be blocked?

I requested this website to be block last week but it's still working. Is there a reason it wasn't added to denylist? :/
https://fling-trainer.com

https://github.com/hagezi/dns-blocklists/issues/2389

### Why should these domain(s) be blocked?

Virus in downloads
Impersonating real website: https://flingtrainer.com

**Comment by hagezi** [comment]
The domain is on both malware lists. TIF medium and TIF.
