### ISSUE TITLE
Block fstatic.nl , marktplaats.com

### ISSUE THREAD

**Issue by AleIlMagno** [hagezi/dns-blocklists#2428]
### Which domain(s) should be blocked?

fstatic.nl
(or only assets.fstatic.nl)

marktplaats.com
(or only s.marktplaats.com)
(I also found marktplaats.nl)

### Why should these domain(s) be blocked?

These two domains seem to be automatically called when opening Brave on mobile in the Netherlands. I'm not sure about what is the first domain, the second one seems to be an advertising company.
I blocked the entire domains and everything works, but the ones that are actually called are the subdomains specified above.

**Comment by hagezi** [comment]
`fstatic.nl `- Breaks site layout on some sites, e.g. https://www.funda.nl/
`s.marktplaats.com` - DEAD (NXDOMAIN)

https://www.marktplaats.nl/ - online market place
