### ISSUE TITLE
Identifying Edge Browser Requests

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#2429]
### `config.edge.skype.com`
We block `variations.brave.com` (Brave) but not `config.edge.skype.com` (Edge). Both of these dictate Controlled Feature Rollout (A/B testing) for their respective browsers.

`config.edge.skype.com` is _not_ blocked, but `variations.brave.com` is blocked.

I was going to argue that we should block the Edge request, but it looks like it may be used for other things besides A/B testing:
* Controlled Feature Rollout `https://learn.microsoft.com/en-us/deployedge/edge-configuration-and-experiments`
* User agents `https://www.bleepingcomputer.com/news/microsoft/the-new-microsoft-edge-sometimes-impersonates-other-browsers-user-agents/`

### **Other requests**
Other requests that aren't blocked and that I'm trying to identify:
* `api.edgeoffer.microsoft.com` may be `edge://settings/privacy` > Services > "Save time and money with Shopping in Microsoft Edge" (possibly?)
* `business.bing.com`
* `edge-mobile-static.azureedge.net`

Lmk if you have any info on these.

 Thanks

**Comment by hagezi** [comment]
Thanks @yokoffing, I can't say anything about it straight away, I'll have to do some research first.

**Comment by hagezi** [comment]
I have not found anything concrete about `api.edgeoffer.microsoft.com`. I think it loads the overview page after an Edge update, but I'm not sure. It can be found on some blocklists and is labelled as "Edge tracking". The domain is blocked in Ultimate, I will block it in Pro++ as well.

**Comment by hagezi** [comment]
https://learn.microsoft.com/en-us/windows/privacy/windows-11-endpoints-non-enterprise-editions

`config.edge.skype.com`
-  used to retrieve Skype configuration values

`business.bing.com`
- Cortana and Live Tiles
- Used by Microsoft Search in Bing enabling users to search across files, SharePoint sites, OneDrive content, Teams and Viva Engage conversations, and other shared data sources in an organization, as well as the web.

`edge-mobile-static.azureedge.net`

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/e0563020-1190-4bfa-b54d-4a502bee0ac7)

Seems to be related to https://learn.microsoft.com/en-us/azure/frontdoor/
