### ISSUE TITLE
Photo comments do not open in the Trendyol application

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#243]
I understand, thank you for your interest. Then I would like to specify another address.

Photo comments do not open in the Trendyol application. When you add this address to the whitelist, the problem improves.

Hagezi multi pro++ blocks.

![D35EE9CB-97D7-48C3-91D5-BFE7C610A124](https://user-images.githubusercontent.com/30311445/214381981-824e5269-aea5-4d26-a657-2a3fee91ea27.png)
![A0DC41A1-0184-4C5C-A001-F00962395C14](https://user-images.githubusercontent.com/30311445/214382019-106db8b3-4ba5-4a5e-8613-4907164d49df.jpeg)

_Originally posted by @azafrak in https://github.com/hagezi/dns-blocklists/issues/242#issuecomment-1402431063_

**Comment by hagezi** [comment]
@azafrak Thanks, removed.

ping @badmojr @symbuzzer

**Comment by symbuzzer** [comment]
> @azafrak Thanks, removed.
> 
> ping @badmojr @symbuzzer

removed, thanks for report
