### ISSUE TITLE
HSL app breaks

### ISSUE THREAD

**Issue by dragani** [hagezi/dns-blocklists#2448]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi LIGHT

### Which domain(s) should be unblocked?

*.app.cookieinformation.com

### Why should the domain(s) be unblocked?

Blocking the domain breaks  HSL mobile app (HSL is public transport  provider in Helsinki, Finland).

**Comment by hagezi** [comment]
Thanks, will be removed,
