### ISSUE TITLE
Add services.chipotle.com to allowlist

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#245]
Trying to order some Chipotle and this is blocked in Pro++ `services.chipotle.com`, once allowed the site seems to work fine.

**Comment by hagezi** [comment]
Blocked by CNAME serviceschipotlecom.trafficmanager.net

**Comment by hagezi** [comment]
Thanks, fixed.

**Comment by hagezi** [comment]
ping @badmojr
