### ISSUE TITLE
Question on AdGuard DNS lists

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#2452]
Asking here to benefit the community.

I just learned AdGuard now has their own configurable web interface for DNS, and users don't have to used AdGuard Home. `https://adguard-dns.io`

I see they list your Badware Hoster list and DynDNS list. Are those rules included in TIF, even if the lists themselves aren't listed as [sources](https://github.com/hagezi/dns-blocklists/blob/main/statistics.md#tif)?

And is the Allowlist Referral list needed or is that for Ultimate users only?

**Comment by hagezi** [comment]
No, Badware Hoster and DynDNS are not included as a source in the TIF. The referral allowlist is not absolutely necessary, but with Pro++ and Ultimate it unblocks referral domains that are also used as normal trackers. E.g. app.adjust.*

**Comment by yokoffing** [comment]
Thanks for clarifying!
