### ISSUE TITLE
https://browser.lol/

### ISSUE THREAD

**Issue by Nzzyme** [hagezi/dns-blocklists#2471]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS, Other

### Other

HaGeZi's Threat Intelligence Feeds DNS Blocklist 

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

https://browser.lol/

### Why should the domain(s) be unblocked?

I don't see a reason why it should be blocked.

**Comment by hagezi** [comment]
Via Phishing Army.

Flagged:
https://www.virustotal.com/gui/domain/browser.lol/detection
https://www.urlvoid.com/scan/browser.lol/

```
Secure DNS:
 - 360Secure       OK
 - AliDNS          OK
 - CFIEC           OK
 - CleanBrowsing   BLOCKED
 - Cloudflare      BLOCKED
 - ComodoSecure    OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - DNSWatchGO      OK
 - HaGeZi.TIF      BLOCKED
 - Neustar         BLOCKED
 - NextDNS.TIF_AI  OK
 - NortonCS        OK
 - NRD.DGA.IDN     OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        BLOCKED
 - Umbrella        OK
 - YandexSafe      OK
```

**Comment by Nzzyme** [comment]
> Via Phishing Army.
> 
> Flagged: https://www.virustotal.com/gui/domain/browser.lol/detection https://www.urlvoid.com/scan/browser.lol/
> 
> ```
> Secure DNS:
>  - 360Secure       OK
>  - AliDNS          OK
>  - CFIEC           OK
>  - CleanBrowsing   BLOCKED
>  - Cloudflare      BLOCKED
>  - ComodoSecure    OK
>  - CONTROLD.TIF    BLOCKED
>  - DNS0.eu         BLOCKED
>  - DNS0.eu.ZERO    BLOCKED
>  - DNSWatchGO      OK
>  - HaGeZi.TIF      BLOCKED
>  - Neustar         BLOCKED
>  - NextDNS.TIF_AI  OK
>  - NortonCS        OK
>  - NRD.DGA.IDN     OK
>  - Quad9           OK
>  - SafeDNS         OK
>  - UltraDNS        BLOCKED
>  - Umbrella        OK
>  - YandexSafe      OK
> ```

Thanks! May I know which service have you used to generate the tabular status of 'Secure DNS' above? I mean, how do I scan a URL via multiple DNS service providers at once? Thanks!

**Comment by hagezi** [comment]
This is my own shell script from my build system. Simplifies a dig of the domain against different IPs of the Secure DNS.

https://github.com/PeterDaveHello/chkdomain does something similar

**Comment by Nzzyme** [comment]
> This is my own shell script from my build system. Simplifies a dig of the domain against different IPs of the Secure DNS.
> 
> https://github.com/PeterDaveHello/chkdomain does something similar

Thanks!
