### ISSUE TITLE
Anthropologie App on iOS not working 

### ISSUE THREAD

**Issue by Justforreporting** [hagezi/dns-blocklists#2473]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

http://captcha.px-cdn.net/
http://captcha.px-cloud.net/

### Why should the domain(s) be unblocked?

Can’t pass thought captcha on Anthropologie app on IOS

**Comment by hagezi** [comment]
See my comments: https://github.com/hagezi/dns-blocklists/issues/2043
