### ISSUE TITLE
Two domains breaks the refresh location of Maps and FamilyLink

### ISSUE THREAD

**Issue by XRzero** [hagezi/dns-blocklists#2477]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Cloudflare Gateway

### NextDNS users only

- [ ] IMPORTANT - I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

firebaselogging-pa.googleapis.com
firebaselogging.googleapis.com

### Why should the domain(s) be unblocked?

When these two domains are blocked it breaks the refresh location functionality of the Google Maps and Family Link app after 24 to 48hrs from time they are blocked.

When trying to refresh the location of the device we're locating, sometimes it says "Something went wrong" but most of the time it not show an error but will just shows that the device we're trying to locate is "Offline" even if it is not. The only way to locate the device is to wait for the device to automatically report its exact location which sometimes takes an hour before it happens.  I had this problem for more that 2 years starting with other known blocklists that I've used in the past (because they also blocked these domains) and I had to whitelist these two domains in order to locate my lil sister's phone because my mom keeps complaining that she cannot locate my little sister in real-time and after investigating, it turns out that these two domains has something to do with Google Maps and Family Link location functionality.

Please check if it is worth removing the domains from your list because to be honest, I don't know what other Google services are using these two domains.

**Comment by hagezi** [comment]
Thank you, but from Pro upwards the domains remain blocked. Bug trackers are not blocked in Light and Normal, you could downgrade to Normal or unblock these domains yourself.
