### ISSUE TITLE
Apple DOH CDN domain

### ISSUE THREAD

**Issue by BirdInFire** [hagezi/dns-blocklists#2478]
### Which domain(s) should be blocked?

doh.dns.apple.com.v.aaplimg.com

### Why should these domain(s) be blocked?

if my memory is right it's the CDN version of doh.dns.apple.com who is already in the "HaGeZi's Encrypted DNS/VPN/TOR/Proxy Bypass" list

**Comment by hagezi** [comment]
Thanks, but already blocked in the DoH and Bypass list.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/675a94f4-ef60-4847-b936-69377c85d559)

**Comment by BirdInFire** [comment]
> Thanks, but already blocked in the DoH and Bypass list.
> 
> ![grafik](https://private-user-images.githubusercontent.com/104343908/320300805-675a94f4-ef60-4847-b936-69377c85d559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzM0MDUsIm5iZiI6MTcxMjUzMzEwNSwicGF0aCI6Ii8xMDQzNDM5MDgvMzIwMzAwODA1LTY3NWE5NGY0LWVmNjAtNDg0Ny1iOTM2LTY5Mzc3Yzg1ZDU1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QyMzM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGVmMmM3MTU4NjliY2EwNDFkMDBhY2EwNjlhMWFkYWQ0ZjgzMmVhMGQ3YWE2N2ZlNGMxMjQxNGVjMmIwOTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w620UYCAxMxTQ5SACt-NVEA2f1k6mMQi4gGmSpGCbs4)

Thanks I will linvestiguate why my Adblock with the list don't block it so :/ (sorry for the false report)
