### ISSUE TITLE
Allow qsurvey.mozilla.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#248]
Pro++

`qsurvey.mozilla.com` links to a feedback form for [Firefox Translations](https://blog.mozilla.org/en/mozilla/local-translation-add-on-project-bergamot/).

`https://qsurvey.mozilla.com/s3/Firefox-Translations`

**Comment by hagezi** [comment]
Blocked by CNAME privatedomain.sgizmo.com

ping @badmojr

**Comment by hagezi** [comment]
Thanks, removed.
