### ISSUE TITLE
Pop-Up Ads List Inclusion

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2484]
Hey,

I see that the Pop-Up Ads is now only partially included in Ultimate and TIF - I thought these were fully included on Ultimate?

What has been removed to only make them partially included now?

Is it worth adding the list as its own blocklist in addition?

**Comment by hagezi** [comment]
It has been split, if you are using Pro or higher and TiF, there is no reason to use the PopupAds list additionally.
