### ISSUE TITLE
Blocked domain prevents filling out forms

### ISSUE THREAD

**Issue by petergithubuser** [hagezi/dns-blocklists#2499]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

https://www.abras.com.br/superhiper/ultima-edicao

https://www.abras.com.br/superhiper/edicoes-anteriores

### Why should the domain(s) be unblocked?

I am using Hagezi's DNS Normal from ControlD free DNS service. I don't know if the other Hagezi's DNS versions of are also impacted or just the Normal one.

The two links below are to a free Brazilian digital monthly magazine. To access the download option, we must fill out an online form that always appears in the link to download the latest edition (current edition) and in the link to download previous editions. If the form is blocked, it is not possible to download the magazine.

As can be seen the difference between using Hagezi's DNS normal and Cloudflare 1.1.1.1:
![photo_4956474306800495857_y](https://github.com/hagezi/dns-blocklists/assets/159736884/5cfff2da-67d3-476e-a79a-76108d8a69cd)

![photo_4956474306800495856_y](https://github.com/hagezi/dns-blocklists/assets/159736884/1af415f3-9210-462a-b89c-9a2226a603df)

Thank you very much.

**Comment by hagezi** [comment]
Thanks, will be fixed on next release.
