### ISSUE TITLE
go.e2language.com

### ISSUE THREAD

**Issue by Domsicols** [hagezi/dns-blocklists#25]
It is blocked on pro and it its unable to load links from yahoo mail. Its a english language reviewing website. Thanks

**Comment by hagezi** [comment]
removed on next update.

**Comment by Domsicols** [comment]
Sorry i have already reported this and i did not remember. Thank you

**Comment by hagezi** [comment]
ping @notracking

**Comment by notracking** [comment]
Fixed!
