### ISSUE TITLE
.bond TLD consideration

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#2507]
Would you consider adding .bond to the Most Abused TLDs list?

It's currently ranked 2 in my scam blocklist:
``` console
$ awk -F . '{print $NF}' raw.txt | sort | uniq -c | sort -nr | head -n 10
  26564 com
   1601 bond
   1339 shop
   1069 de
    958 xyz
    938 net
    773 top
    720 online
    644 org
    410 za
```

![https://ntldstats.com/tld/bond](https://github.com/hagezi/dns-blocklists/assets/91372088/b29520b4-41cd-4ac3-bc28-1eada4f69e8a)
https://ntldstats.com/tld/bond

**Comment by jarelllama** [comment]
Sample of NRDs with .bond:
![Screenshot_20240415-135506~2](https://github.com/hagezi/dns-blocklists/assets/91372088/62dd7b06-6c67-4866-ba6d-7376df6e79b2)

It's dozens of the same domain with a random number string behind them.

**Comment by hagezi** [comment]
Thanks, I'll add it to the list.
