### ISSUE TITLE
edge.microsoft.com (Telemetry)

### ISSUE THREAD

**Issue by ChaseKnowlden** [hagezi/dns-blocklists#2509]
### Which domain(s) should be blocked?

edge.microsoft.com

### Why should these domain(s) be blocked?

Server that Sends Telemetry to Microsoft

**Comment by hagezi** [comment]
This is the Microsoft Edge Sync Endpoint: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-endpoints#sync
