### ISSUE TITLE
Request Block - Survey Scam

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#251]
Link : 
fundanemt.org
claimcoderz.live

Sample : 
https://fundanemt.org/space-marshals-3/
https://fundanemt.org/dragonscapes-adventure/
https://fundanemt.org/league-of-legends-wild-rift/

https://claimcoderz.live/8b0fc0a
https://claimcoderz.live/472d147
https://claimcoderz.live/5aafafd

Typical survey scam, which redirects to a spammy website.

**Comment by hagezi** [comment]
Many thanks, added.

**Comment by hagezi** [comment]
@durablenapkin
Something for your scam blocklist?

**Comment by durablenapkin** [comment]
Thank you @hagezi! I've added these two domains and it'll be included in the next nightly update.

**Comment by hagezi** [comment]
Thanks @durablenapkin, so far, I have only used your scam list in the tif and thus in the ultimate. But I will also use the list as a source for the other lists, and it will then be included in light to ultimate.

**Comment by durablenapkin** [comment]
What an honor, thank you @hagezi!

**Comment by MagicalAlchemist** [comment]
Another site worth to block (same category as before)
modmobile24.com
knightmods.com
gamingtoolz.club
gamingbuffs.com
levelbash.com
nxtgenerator.top
hotmod.eu
www.resources4gaming.com

sample : 
warpath-hack-gold.modmobile24.com
knightmods.com/lol-wild-rift
gamingtoolz.club/?d26633f
gamingbuffs.com/gen/club-vegas-slots
levelbash.com/injectors
nxtgenerator.top/global-strike-counter-action
deer-hunter-world-the-hunt-hack-mod.hotmod.eu - (phising detected by bitdefender)
www.resources4gaming.com/generator

**Comment by hagezi** [comment]
Ping @durablenapkin

**Comment by durablenapkin** [comment]
Thank you! Domains will be included in next nightly update.
