### ISSUE TITLE
feeds.nobaraproject.org

### ISSUE THREAD

**Issue by johnblaze00** [hagezi/dns-blocklists#2516]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

https://feed.nobaraproject.org

### Why should the domain(s) be unblocked?

A feed page of issues and fixes for the Nobara Operating System

**Comment by hagezi** [comment]
Thanks @johnblaze00, blocked by CNAME `custom.getbeamer.com`. Will be removed on next release.

**Comment by johnblaze00** [comment]
Thank you!

**Comment by hagezi** [comment]
I have to thank you. The lists only get "better" with the support of the community.

**Comment by johnblaze00** [comment]
best list(s) out there!
