### ISSUE TITLE
Incorrect blocked Domain.

### ISSUE THREAD

**Issue by NeikiDev** [hagezi/dns-blocklists#2519]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

"analyze.neiki.dev" / "*.neiki.dev"

### Why should the domain(s) be unblocked?

Hey,

I am the owner of the Domain "neiki.dev". 

Recently i found out that my domain "analyze.neiki.dev" is blocked in this list
> https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt

Please remove this domain from the blocklist.

As you can see i use this domain for virustotal analysis and more, its a domain that stores information about files (Malware reports and more) to keep the community safe.

You can see here on virustotal https://www.virustotal.com/gui/user/NeikiAnalytics that i have a good record and reputation and my domain is in no way malicious or related to ads.

Please let me also know why it got blocked in the first place.

Thanks, Neiki

**Comment by hagezi** [comment]
Thanks @NeikiDev, source is:

https://raw.githubusercontent.com/ttc-cert/TTC-CERT_blocklist_recommended/master/domain_blocklist_recommended.txt
@ttc-cert

The domain will be removed from my TIF list with the next release.
