### ISSUE TITLE
Allow detectportal.firefox.com

### ISSUE THREAD

**Issue by gnadgnaoh** [hagezi/dns-blocklists#252]
Pro ++

detectportal.firefox.com is used to check Captive Portal in Public Network

https://support.mozilla.org/en-US/kb/captive-portal

**Comment by hagezi** [comment]
Ping @cipherops

**Comment by hagezi** [comment]
Thanks, removed.

**Comment by nezlobnyj** [comment]
For anyone curious in the future:
this behaviour can be disabled - https://support.mozilla.org/en-US/questions/1157121
Did this on my machine - no requests since. That said - call seems completely harmless to end-user.

**Comment by hagezi** [comment]
Thanks @nezlobnyj
