### ISSUE TITLE
Trackers on etiko.com.au

### ISSUE THREAD

**Issue by brodyhoskins** [hagezi/dns-blocklists#2520]
### Which domain(s) should be blocked?

```
a.klaviyo.com
cnd.refersion.com
upsells.boldapps.net
whale.camera
```

### Why should these domain(s) be blocked?

- a.klaviyo.com loads endless tracking events
- cnd.refersion.com loads tracking pixel
- upsells.boldapps.net loads tracking script
- whale.camera loads tracking pixel

**Comment by hagezi** [comment]
Blocking `*.a.klaviyo.com` prevents registration on rungne.com - should be checked again. There may be further restrictions.
