### ISSUE TITLE
ertflix.gr: Videos and Live TV are being blocked because of npaw.com domain

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2524]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

`lma.npaw.com`
`interceptor.npaw.com`

### Why should the domain(s) be unblocked?

"Due to them being blocked, Greek users are unable to view any live TV from the Hellenic National Television on the website ertflix.gr. This causes the following error, and video playback stops:"
<img width="1529" alt="image" src="https://github.com/hagezi/dns-blocklists/assets/123986260/b55840ed-c178-4cb1-bd83-78a650a080dc">

You can test it here: `https://www.ertflix.gr/en/epg/channel/ept1-live`

**Comment by hagezi** [comment]
I have added the domains to the allowlist. It will be removed from all lists on release.
