### ISSUE TITLE
Missing domains

### ISSUE THREAD

**Issue by 0yLpSD5DbwiXq** [hagezi/dns-blocklists#2526]
### Which domain(s) should be blocked?

* firebaseremoteconfig.googleapis.com: Tracking (Google Firebase)
* settings.data.microsoft.com: Tracking
* firebaseinstallations.googleapis.com: Tracking (Google Firebase)
* nel.cloudflare.com (subdomains: a.nel.cloudflare.com, gcp.nel.cloudflare.com): Cloudflare Network Error Logging
* stats.ivpn.net: Analytics
* firebaseio.com: Tracking (Google Firebase)
* logs.pangolin.apelabs.net: Analytics
* logs-v3.pangolin.apelabs.net: Analytics
* reports.proton.me: Analytics/Crash reporting
* telemetry-cii.api.playstation.com: Analytics
* metric.gstatic.com: Android Private DNS analytics
* ad.youtube.com: Advertising
* adservice.google: Advertising
* adforms.net: Advertising

### Why should these domain(s) be blocked?

See above

**Comment by hagezi** [comment]
Thanks, please search the existing issues for the domains, then you will find some reasons why some are not blocked.

I'll have a look at the rest.

**Comment by hagezi** [comment]
Added:
```
stats.ivpn.net
reports.proton.me
```

Dead (`NXDOMAIN`/no A-Record):
```
logs.pangolin.apelabs.net
logs-v3.pangolin.apelabs.net
ad.youtube.com
adservice.google
adforms.net
```
