### ISSUE TITLE
Some Affiliate/Referral Domains To Whitelist

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#253]
Shark Vacuum person here!

Came across some domains for your consideration to add to https://github.com/hagezi/dns-blocklists/blob/main/whitelist-referral.txt

```
www.dpbolvw.net
www.kqzyfj.com
cj.mplxtms.com
```

The first two already exist in the whitelist but without "www."

**More Details:**

I browse RedFlagDeals quite often and clicking on the "Deal Link" in some posts loads a series of affiliate/referral domains before loading the actual product page. If one of these domains are blocked then the product page doesn't load.

I used https://www.expandurl.net/ to see what domains were being loaded. To save you time I analyzed the domain loading chains and extracted the 3 blocked domains above.

As always, thank you!

**My Testing:**

**https://forums.redflagdeals.com/dell-nintendo-switch-price-error-new-horizons-edition-79-99-2597337/**

The "Deal Link" link points to: http://www.dpbolvw.net/click-749547-12105225?url=https%3A%2F%2Fwww.dell.com%2Fen-ca%2Fshop%2Fnintendo-switch-with-pastel-green-and-blue-joy-con-new-horizons-edition-game-console-blue-pastel-green%2Fapd%2Fac434094%2Fgaming-gaming-accessories&sid=rfdcb

Using https://www.expandurl.net/ I tracked the urls being loaded:
    
* https://cj.dotomi.com/4877iqzyG/qx1/FGFEJGGJ/LINJIL/E/E/E?l=byoj%3Dxljih%260xr%3Dnzzvy%259G%258L%258L222.jkrr.ius%258Lkt-ig%258Lynuv%258Ltotzktju-y2ozin-2ozn-vgyzkr-mxkkt-gtj-hr0k-pu4-iut-tk2-nuxo5uty-kjozout-mgsk-iutyurk-hr0k-vgyzkr-mxkkt%258Lgvj%258LgiA9A6FA%258Lmgsotm-mgsotm-giikyyuxoky%3c%3cnzzv%3A%2F%2F222.jvhur12.tkz%2Firoiq-DAFBAD-7876B88B%3c%3cM%3cnzzv%3A%2F%2Frutm0xr.uxm%3c%3c7%3c7%3c6%3c6%3c6%3c
* https://www.emjcd.com/b766vpyxH/pw0/EFEDIFFI/KHMIHK/D/LDDDDIDGIJDJKFDGII:cQ8T1xWNUF71/sopJLpGLMqrpEErqLEpLGJEoDnLFoLGJ?u=gB1w%3DAywvu%26DA4%3D0CC8B%25MT%25LY%25LYFFF.wx44.v75%25LYx6-vt%25LYB078%25LY616Cx6w7-BF1Cv0-F1C0-8tBCx4-zAxx6-t6w-u4Dx-27H-v76-6xF-07A1I76B-xw1C176-zt5x-v76B74x-u4Dx-8tBCx4-zAxx6%25LYt8w%25LYtvNMNJSN%25LYzt516z-zt516z-tvvxBB7A1xB%3cv27!FC62-40vRxF0%3c0CC8%3A%2F%2FFFF.w8u74EF.6xC%2Fv41v3-QNSONQ-KLKJOLLO%3c%3cZ%3c0CC8%3A%2F%2F476zDA4.7Az%3cMuLtyyRQ-yuOO-NOMw-uKPv-xwyyNRSuRwRO%3cK%3cK%3cJ%3cJ%3cJ%3c
* https://ad.doubleclick.net/ddm/trackclk/N1153793.3448954CJAFFILIATE/B28465123.345578820;dc_trk_aid=537223123;dc_trk_cid=177484298;VEN1=12105225-749547-rfdcb;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;ltd=?https://www.dell.com/en-ca/shop/nintendo-switch-with-pastel-green-and-blue-joy-con-new-horizons-edition-game-console-blue-pastel-green/apd/ac434094/gaming-gaming-accessories?cjevent=fbc68c389dec11ed81c8361b0a82b836&dgc=CJ&publisherid=718969&publisher=&aff=RedFlagDeals.com&affid=718969&aff_webid=749547&aff_user_id=rfdcb&cjdata=MXxOfDB8WXww
* https://www.dell.com/en-ca/shop/nintendo-switch-with-pastel-green-and-blue-joy-con-new-horizons-edition-game-console-blue-pastel-green/apd/ac434094/gaming-gaming-accessories?cjevent=fbc68c389dec11ed81c8361b0a82b836&dgc=CJ&publisherid=718969&publisher=&aff=RedFlagDeals.com&affid=718969&aff_webid=749547&aff_user_id=rfdcb&cjdata=MXxOfDB8WXww&gacd=9683519-28465123-5750457-345578820-177484298&dgc=af&VEN1=12105225-749547-rfdcb&dclid=CLihpqDe5vwCFa7JGAId0HYOnw
* https://www.dell.com/en-ca/shop/accessories?showMessage=1

**https://forums.redflagdeals.com/reno-depot-rona-lowes-clearance-ego-snowblowers-899-ymmv-2595029/**

The "Deal Link" link points to: http://go.redirectingat.com/?id=130832X1694315&xs=1&url=https%3A%2F%2Fwww.rona.ca%2Fen%2Fproduct%2Fego-power-56v-21-in-single-stage-auger-propelled-snow-blower-kit-2-75ah-batteries-560w-dual-port-charger-included-snt2125ap-32165222

* https://go.redirectingat.com/?id=130832X1694315&xs=1&url=https%3A%2F%2Fwww.rona.ca%2Fen%2Fproduct%2Fego-power-56v-21-in-single-stage-auger-propelled-snow-blower-kit-2-75ah-batteries-560w-dual-port-charger-included-snt2125ap-32165222
* https://www.kqzyfj.com/click-100047067-12719258?sid=130832X1694315X18b9ba98a36f65b3bb56c16fcc993bee&url=https%3A%2F%2Fwww.rona.ca%2Fen%2Fproduct%2Fego-power-56v-21-in-single-stage-auger-propelled-snow-blower-kit-2-75ah-batteries-560w-dual-port-charger-included-snt2125ap-32165222
* https://cj.dotomi.com/fa100lnwvD/nuz/CDICKDGJ/CBBBFIBHI/B/B/B?w=qwmh%3D574C76b5AD8759b5CfDfeDCe7AjA9f7ff9Ag5AjggDD7fii%26yvp%3Dlxxtw%257E%256J%256J000.vsre.ge%256Jir%256Jtvshygx%256Jiks-ts0iv-9Az-65-mr-wmrkpi-wxeki-eykiv-tvstippih-wrs0-fps0iv-omx-6-B9el-fexxivmiw-9A40-hyep-tsvx-glevkiv-mrgpyhih-wrx6569et-765A9666%3c%3clxxtw%3A%2F%2F000.ou32jn.gsq%2Fgpmgo-54448B4AB-56B5D69C%3c%3cK%3clxxt%3A%2F%2Fpsrkyvp.svk%3c%3c5%3c5%3c4%3c4%3c4%3c
* https://www.emjcd.com/p670kjsrB/jqv/89E8G9CF/8777BE7DE/7/F77F7C7ACCG8EBACFG:YA2RwrQPOC_K/h8jjAi8DGklk88lkF7lBiBlm7hF9iFA9?d=d1rm%3DAC9HCBgAFIDCAEgAHkIkjIHjCFoFEkCkkEFlAFollIICknn%2630u%3Dq22y1%25CJ%25BO%25BO555.0xwj.lj%25BOnw%25BOy0xm3l2%25BOnpx-yx5n0-EF4-BA-rw-1rwpun-12jpn-j3pn0-y0xynuunm-1wx5-kux5n0-tr2-B-GEjq-kj22n0rn1-EF95-m3ju-yx02-lqj0pn0-rwlu3mnm-1w2BABEjy-CBAFEBBB%3clsx!58FG-jGulx0I%3cq22y1%3A%2F%2F555.tz87os.lxv%2Flurlt-A999DG9FG-ABGAIBEH%3c%3cP%3cq22y%3A%2F%2Fuxwp30u.x0p%3cDFk9kGCj-EICD-DnHm-Imno-DmllEGCIEIEI%3cA%3cA%3c9%3c9%3c9%3c
* https://www.rona.ca/en/product/ego-power-56v-21-in-single-stage-auger-propelled-snow-blower-kit-2-75ah-batteries-560w-dual-port-charger-included-snt2125ap-32165222?cm_mmc=affiliate-_-cj-_-wpo_Skimlinks-_-5370367_100047067&utm_medium=affiliate&utm_source=cj&utm_campaign=wpo_Skimlinks&utm_content=5370367-100047067&cjevent=a1cc3b169ded11ed80e4b4ef0a82b832&cjdata=MXxOfDB8WXww

**https://forums.redflagdeals.com/lowes-remington-24-208cc-2-stage-self-propelled-gas-snow-blower-electric-start-509-reg-849-also-sale-rona-2595203/**

The "Deal Link" link points to: http://go.redirectingat.com/?id=130832X1694315&xs=1&url=https%3A%2F%2Fwww.lowes.ca%2Fproduct%2Fgas-snow-blowers%2Fremington-24-in-208cc-2-stage-self-propelled-gas-snow-blower-with-electric-start-1058822

* https://go.redirectingat.com/?id=130832X1694315&xs=1&url=https%3A%2F%2Fwww.lowes.ca%2Fproduct%2Fgas-snow-blowers%2Fremington-24-in-208cc-2-stage-self-propelled-gas-snow-blower-with-electric-start-1058822
* https://www.kqzyfj.com/click-100047067-12082851?sid=130832X1694315Xe379dd31143d80e115bc8c837410a563&url=https%3A%2F%2Fwww.lowes.ca%2Fproduct%2Fgas-snow-blowers%2Fremington-24-in-208cc-2-stage-self-propelled-gas-snow-blower-with-electric-start-1058822
* https://cj.dotomi.com/c2111y1A9S/18D/RSQYSYVR/RQQQUXQWX/Q/Q/Q?k=oD3y%3DMOLTONsMRUPOMQszOSUyyOMMPOyTLzMMQwxTxTOSPMLvQRO%26FC6%3D2EEAD%25OV%25Na%25NaHHH.69HzD.xv%25NaAC9yFxE%25Na1vD-D89H-w69HzCD%25NaCz7381E98-NP-38-NLTxx-N-DEv1z-Dz60-AC9Az66zy-1vD-D89H-w69HzC-H3E2-z6zxEC3x-DEvCE-MLQTTNN%3c%3c2EEAD%3A%2F%2FHHH.5BKJ04.x97%2Fx63x5-MLLLPSLRS-MNLTNTQM%3c%3cb%3c2EEA%3A%2F%2F6981FC6.9C1%3c%3cM%3cM%3cL%3cL%3cL%3c
* https://cj.mplxtms.com/e466r098T/07C/QRPXRXUQ/QPPPTWPVW/P/XPPQPUPSUVRXVVSXXV:0ITwD8iag.Bu/z3PW0-SXY123QQ21XR3WTSY0PzXR-XSX?s=i6wr%3DFHEMHGlFKNIHFJlsHLNrrHFFIHrMEsFFJpqMqMHLIFEoJKH%2685z%3Dv7736%25HO%25GT%25GTAAA.z2As6.qo%25GT352r8q7%25GTuo6-612A-pz2As56%25GT5s0w1u721-GI-w1-GEMqq-G-67ous-6szt-3523szzsr-uo6-612A-pz2As5-Aw7v-szsq75wq-67o57-FEJMMGG%3cqx2!A3s5-7zE5toJo%3cv7736%3A%2F%2FAAA.y4DCtx.q20%2Fqzwqy-FEEEILEKL-FGEMGMJF%3c%3cU%3cv773%3A%2F%2Fz21u85z.25u%3cqJNELpIH-KLMN-ItoN-oJHG-FqoHsJqNGHEq%3cF%3cF%3cE%3cE%3cE%3c
* https://www.lowes.ca/product/gas-snow-blowers/remington-24-in-208cc-2-stage-self-propelled-gas-snow-blower-with-electric-start-1058822?cm_mmc=affiliate-_-cj-_-wpo_Skimlinks-_-5370367_100047067&utm_medium=affiliate&utm_source=cj&utm_campaign=wpo_Skimlinks&utm_content=5370367-100047067&cjevent=af07cb389def11ed82f7439c0a82b838&cjdata=MXxOfDB8WXww

**Comment by hagezi** [comment]
Thanks, will check.

**Comment by hagezi** [comment]
Thanks for the details and your support. Fixed.
