### ISSUE TITLE
Source Suggestions

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#2537]
https://github.com/infinitytec/blocklists
http://phishing.mailscanner.info/phishing.bad.sites.conf

I have yet to check them for dead domains and false positives. I'll do so in a few hours if you've yet to.

**Comment by hagezi** [comment]
Thanks, I'll have a look at it in a few days.

**Comment by jarelllama** [comment]
https://raw.githubusercontent.com/infinitytec/blocklists/master/scams-and-phishing.txt (I have yet to look at the other blocklists in the repo): 
``` console
# Total entries
$ wc -l scams-and-phishing.txt 
22779 scams-and-phishing.txt

# Unique entries
$ comm -23 scams-and-phishing.txt tif.txt | wc -l
22395
```

http://phishing.mailscanner.info/phishing.bad.sites.conf:
```console
# Total entries
$ wc -l mailscanner.txt
36632 mailscanner.txt

# Unique entries
$ comm -23 mailscanner.txt tif.txt | wc -l
19339
```

Will run dead check in a bit.

**Comment by hagezi** [comment]
Thank you, can you make the dead domains available? Then I don't have to check again. Thank you!

**Comment by jarelllama** [comment]
Will do, just waiting for dead domains linter to finish.

**Comment by jarelllama** [comment]
I haven't ran the dead check on the mailscanner list yet but look at some of these false positives from both sources (in the edit). I see some false positives in there like yandex.ru. What do you think?

**Comment by hagezi** [comment]
So if such domains end up on the list, I won't add them.

**Comment by jarelllama** [comment]
I'll take a deeper look at https://github.com/infinitytec/blocklists when I have the time later.

**Comment by jarelllama** [comment]
Hi again, here are the various reports generated for the blocklists in question:
[https://github.com/infinitytec/blocklists/raw/master/ads-and-trackers.txt](https://github.com/jarelllama/Blocklist-Checker/issues/8#issuecomment-2069735235): compressed from 53043 to 342, 23% invalid, 19% dead
[https://github.com/infinitytec/blocklists/raw/master/scams-and-phishing.txt](https://github.com/jarelllama/Blocklist-Checker/issues/9#issuecomment-2069737916): compressed from 22767 to 3893, 52% dead
[https://github.com/infinitytec/blocklists/raw/master/mlm.txt](https://github.com/jarelllama/Blocklist-Checker/issues/20#issuecomment-2069993400): compressed from 143351 to 823, 75% invalid (most contain underscores)
[http://phishing.mailscanner.info/phishing.bad.sites.conf](https://github.com/jarelllama/Blocklist-Checker/issues/10): 219 in Tranco, probably needs a deeper dive

**Comment by hagezi** [comment]
Thanks for the effort, I think we should leave it at that.

My conclusion, not worth it.

**Comment by jarelllama** [comment]
Agreed.

**Comment by infinitytec** [comment]
Hi,
Just wanted to pop in and say that any advice for how I can make my blocklists better is appreciated!
