### ISSUE TITLE
Rakuten Cashback Whitelist

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#254]
Semi-related to #253 (allowing affiliate/referral domains), Rakuten is a cashback site that uses affiliate/referral domains to track purchases and give cashback to users:

https://www.rakuten.ca/static/cashback-shopping-whitelist
(note: some domains contain uppercases and need to be converted to lowercase, eg. Aramark.evyy.net)

Feel free to skim through the domains, I wasn't sure if this counts as affiliate/referral links re: https://github.com/hagezi/dns-blocklists#referral but just wanted to bring this to your attention for consideration.

(They also have a US whitelist (https://www.rakuten.com/whitelist/ebates-cash-back-shopping.txt) but it seems to be **very liberal** in allowing domains, eg. `analytics.yahoo.com` and others so I only linked to the Canadian whitelist above. It also isn't linked anywhere so it may be outdated, whereas the Canadian one is mentioned on https://www.rakuten.ca/help/trouble-shooting#ensurecashbackshopping)

Thanks as always!

**Comment by hagezi** [comment]
Thanks, I will take a closer look.

One note, when using the referral whitelist not only the main domains need to be removed but also their subdomains, so for example 7eer.net removes *.7eer.net.

This is how I apply this to my lists as well.

**Comment by hagezi** [comment]
Thanks, checked.

**Comment by durablenapkin** [comment]
Thank you, have a wonderful weekend!

**Comment by hagezi** [comment]
Thanks, you too.
