### ISSUE TITLE
Block graph.microsoft.com

### ISSUE THREAD

**Issue by 4d62ext** [hagezi/dns-blocklists#2540]
### Which domain(s) should be blocked?

graph.microsoft.com

### Why should these domain(s) be blocked?

Data collection thingy? I assume it does the same thing as graph.facebook.com which is blocked here iirc

**Comment by hagezi** [comment]
This breaks a lot …

**Comment by hagezi** [comment]
https://learn.microsoft.com/en-us/graph/overview#what-can-you-do-with-microsoft-graph
