### ISSUE TITLE
Just the News, Article Videos Clips

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#2541]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

live.primis.tech
video.primis.tech

### Why should the domain(s) be unblocked?

Blocking these two domains prevents video clips from loading within articles.

Example Below
https://justthenews.com/government/courts-law/tiktok-says-it-will-sue-if-bill-forces-owner-sell-or-be-banned-passes

**Comment by markangus2b** [comment]
@hagezi My apologies for the false, false positive report. While these domains were used 24 hours ago, it would appear that today this is not the case. You can reinstate both domains if you wish.

**Comment by hagezi** [comment]
fixed
