### ISSUE TITLE
bstgms4y.com

### ISSUE THREAD

**Issue by miansopi** [hagezi/dns-blocklists#2550]
### Which domain(s) should be blocked?

bstgms4y.com

### Why should these domain(s) be blocked?

Started showing up in the AdGuard DNS logs. Looking at VirusTotal it seems to be distributing pirated/modded Android apks, possible malicious? According to a Google search the domain is included in the 1Hosts blocklist.

https://www.virustotal.com/gui/domain/bstgms4y.com/relations

**Comment by hagezi** [comment]
@xRuffKez

**Comment by xRuffKez** [comment]
> @xRuffKez 

Investigation

**Comment by xRuffKez** [comment]
@hagezi Site is masked. Virustotal Vendors are flagging for developer keys, which is common to repack an apk and is not a malicious behaviour.
But i cannot decide, since i cannot access the site.

**Comment by hagezi** [comment]
Thanks, I can't access either, will add the domain to the anti piracy list.

It is not flagged by any Security DNS.
