### ISSUE TITLE
yts.mx

### ISSUE THREAD

**Issue by SeriousHoax** [hagezi/dns-blocklists#2559]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

`yts.mx`

### Why should the domain(s) be unblocked?

It's a website to download pirated movies. It's not related to any malicious/advert related contents.

**Comment by hagezi** [comment]
FYI: @MIOGMIOG
