### ISSUE TITLE
trivialextrovertedarrangement.pro

### ISSUE THREAD

**Issue by tkien931** [hagezi/dns-blocklists#2566]
### Which domain(s) should be blocked?

trivialextrovertedarrangement.pro

### Why should these domain(s) be blocked?

I blocked it on my computer for 2 days and haven't seen any issues.
I looked up domain whois, it's from AdGuard. I have AdGuard VPN installed, but never run it and AdGuard VPN addons

About ~50 queries. I think it came from AdGuard VPN addon (using Chrome).
![image](https://github.com/hagezi/dns-blocklists/assets/141718751/2eea88c2-f7bd-4506-9852-b45daa8ca9e9)

**Comment by hagezi** [comment]
These are required AdGuard VPN domains that are used, for example, to test whether your provider is blocking the VPN.
