### ISSUE TITLE
Pluto TV App on Windows 11

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#2569]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

tags.tiqcdn.com
a-fds.youborafds01.com

### Why should the domain(s) be unblocked?

The Pluto TV app on Windows will start but doesn't play videos/channels when `tags.tiqcdn.com` is blocked. When `a-fds.youborafds01.com` is blocked videos/channels will start playing, but after about 30 seconds and error message appears and the video freezes completely.

**Comment by hagezi** [comment]
Hi @markangus2b,

the two domains are in good hands in the Ultimate. I will not unblock them there. I was able to reproduce that `tags.tiqcdn.com` is required to start the video. This domain is currently only blocked in Ultimate because it also leads to restrictions in other places. It is a popular tracker. I could not reproduce the freeze caused by the other domain.

https://duckduckgo.github.io/tracker-radar-wiki/domains/tiqcdn.com.html

**Comment by 3h50** [comment]
I can't get Pluto TV to work on an Apple TV in light.  I managed to white list a few items now it starts video for 30 seconds and dies.

**Comment by hagezi** [comment]
@3h50 In which region do you use PlutoTV?

**Comment by hagezi** [comment]
@jo2dan94 Can you check that?

**Comment by jo2dan94** [comment]
Yes I will check

**Comment by 3h50** [comment]
> [@3h50](https://github.com/3h50) In which region do you use PlutoTV?

US Central.

This is what I started unblocking to get here.  I think the AppleTV PlutoTV app has different trackers than the web based version.  I'm not asking for these to be whitelisted, this is just what I started whitelisting with no concern to privacy in vain to get it to work.  Using Technitium if there is anything I can do to help. 

[tiqcdn.com](http://192.168.22.3:5380/#)
[youborafds01.com](http://192.168.22.3:5380/#)
*.pluto.tv

**Comment by hagezi** [comment]
@3h50 Did you test using the Light version? Neither `tiqcdn.com` nor `youborafds01.com` are blocked in the Light version.

`tiqcdn.com` is only blocked in the Ultimate version, and `youborafds01.com` is blocked from the Pro version onwards.

**Comment by jo2dan94** [comment]
Looks like youborafds01.com needs to be unblocked otherwise I get this.


![Image](https://github.com/user-attachments/assets/ac0c6e8a-63ee-4c71-9ff1-441cfdd7a1b3)

**Comment by jo2dan94** [comment]
And for tiqcdn.com it doesn't play at all if it's blocked.

**Comment by 3h50** [comment]
> [@3h50](https://github.com/3h50) Did you test using the Light version? Neither `tiqcdn.com` nor `youborafds01.com` are blocked in the Light version.
> 
> `tiqcdn.com` is only blocked in the Ultimate version, and `youborafds01.com` is blocked from the Pro version onwards.

I think so but I've made dumber mistakes...  This is the *only*  list I have in technitium, and I only additionally block .cn and .ru

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt

**Comment by hagezi** [comment]
@3h50 Based on tests conducted by @jo2dan94 it should currently work with Light and Normal. Pro and Pro++ require `a-fds.youborafds01.com` to be unblocked. For Ultimate, `tags.tiqcdn.com` must also be unblocked.

I will also unblock `a-fds.youborafds01.com` in Pro and Pro++ in the next release.

**Comment by 3h50** [comment]
> [@3h50](https://github.com/3h50) Based on tests conducted by [@jo2dan94](https://github.com/jo2dan94) it should currently work with Light and Normal. Pro and Pro++ require `a-fds.youborafds01.com` to be unblocked. For Ultimate, `tags.tiqcdn.com` must also be unblocked.
> 
> I will also unblock `a-fds.youborafds01.com` in Pro and Pro++ in the next release.

Great thanks!  

I'm going to whitelist these and see if it fixes it.  I think there is an extra tracker in the AppleTV version of the PlutoTV app and think there may be one missing.  I can get videos to play for 30 seconds then all streams quit and the app closes.  If I stop blocking this issue goes away.

**Comment by 3h50** [comment]
UPDATE: whitelisting these did not stop the issue of the app closing.  I recorded the application if it would help but it closes after closer to 15 seconds.  This does not happen if the blocking is turned off.  It feels like the TVOS version of this app has an additional domain that tells the app their isn't being blocked

**Comment by jo2dan94** [comment]
Is there anyway you can get a full list of the domains? Can you sign up for nextdns and send the domains.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by hagezi** [comment]
I don’t think it’s a blocklist issue. Disable the blocking and test if the problem still occurs.

**Comment by 3h50** [comment]
> I don’t think it’s a blocklist issue. Disable the blocking and test if the problem still occurs.

Turning blocking off was the first thing I tried before opening this ticket and it resolves the issue.  

@jo2dan94 I will get nextdns on the unit so I can see only it's traffic.  thanks for the good idea.

**Comment by 3h50** [comment]
Switched to NextDNS with only the light list on and it worked, making me think that even tho I only see the blocklist in my local dns something else is going on when I turn on the blocklists, so I'm blaming my DNS server.  

I will be switching to pro with the update, thanks @hagezi and @jo2dan94 !  Making the web a better place.
