### ISSUE TITLE
api.telegram.org blocked on threat intel feed

### ISSUE THREAD

**Issue by alexframe** [hagezi/dns-blocklists#2575]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] ~IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.~

### NextDNS users

- [ ] ~IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.~

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

api.telegram.org

### Why should the domain(s) be unblocked?

This is the telegram api used to interact with telegram bots. Documentation can be found here: https://core.telegram.org/bots/api#making-requests

**Comment by hagezi** [comment]
Fixed.
