### ISSUE TITLE
May I ask if these are safe be added to Ultimate separately

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#258]
Thank you for prompt reply, noted.

May I ask if these are safe be added to Ultimate separately:
- hg-statsd.setapp.com (personal, SetApp tracking)
- stats.setapp.com (personal, SetApp tracking)
- gooqle.internalportal.net (Xtra, typo squatting)
- js.monitor.azure.com (Xtra, https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript)
- cdn-xp-ingest.edge.apple (Xtra, https://domain.glass/cdn-xp-ingest.edge.apple - not sure what to make of it and other sub-domains)
- cdn.9to5terminal.com (Xtra, potentially malware, but no concrete proof)
- q1.gb-gmt.gh-g.v1.akaquill.net (Xtra)
- assets.adobedtm.com (Xtra, was discussed at https://github.com/StevenBlack/hosts/issues/709, feels like it belongs to Ultimate as we whitelist domains anyway with this list)

_Originally posted by @nezlobnyj in https://github.com/hagezi/dns-blocklists/discussions/256#discussioncomment-4797742_

**Comment by yokoffing** [comment]
`assets.adobedtm.com` will break shit if blocking at the browser level (uBO/AdGuard) and is blocked by EasyPrivacy with rule`adobedtm.com^$3p,domain=~adobe.com` but has a lot of exceptions.

For DNS level, see https://github.com/badmojr/1Hosts/issues/604.

**Comment by hagezi** [comment]
Thanks @yokoffing 
@nezlobnyj Added except assets.adobedtm.com
