### ISSUE TITLE
MAX (old HBO MAX)

### ISSUE THREAD

**Issue by marcelloinfoweb** [hagezi/dns-blocklists#2580]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO mini

### Which domain(s) should be unblocked?

I can't identify which url is blocking the MAX app from listing the content, but when I remove the list the app opens normally.

### Why should the domain(s) be unblocked?

I can't identify which url is blocking the MAX app from listing the content, but when I remove the list the app opens normally.

**Comment by hagezi** [comment]
Please post a link to the app. Which platform?

**Comment by marcelloinfoweb** [comment]
> Please post a link to the app. Which platform?

https://play.google.com/store/apps/details?id=com.wbd.stream&pli=1

**Comment by hagezi** [comment]
@xRuffKez Can you provide support here?

**Comment by marcelloinfoweb** [comment]
> ```
> events.prd.api.max.com
> telegraph.prd.api.max.com
> matomo.max.nl
> tracking.max.co.il
> ```

whitelist?

**Comment by xRuffKez** [comment]
> > Please post a link to the app. Which platform?
> 
> Android

Which App? HBO Max? I need more details, please.

**Comment by xRuffKez** [comment]
> > ```
> > events.prd.api.max.com
> > telegraph.prd.api.max.com
> > matomo.max.nl
> > tracking.max.co.il
> > ```
> 
> whitelist?

We are investigating, since it is service specific, we might remove the domains.

**Comment by marcelloinfoweb** [comment]
> > > Please post a link to the app. Which platform?
> > 
> > 
> > Android
> 
> Which App? HBO Max? I need more details, please.

MAX (old HBO MAX) in Redmi K50 PRO With HyperOS

**Comment by marcelloinfoweb** [comment]
I discovered that this url below blocks some connections, this is the case with the MAX app, I did several tests and it really is the problem.

`connect.rom.miui.com`

**Comment by hagezi** [comment]
Thanks, connect.rom.miui.com will be removed on next release.

**Comment by hagezi** [comment]
Thanks to everyone for the help. Do any other domains need to be unblocked? 
So far I have not had any reports on the Max app.

**Comment by marcelloinfoweb** [comment]
> Thanks to everyone for the help. Do any other domains need to be unblocked? So far I have not had any reports on the Max app.

Now everything is ok, obrigado!

**Comment by hagezi** [comment]
Thanks @marcelloinfoweb
