### ISSUE TITLE
blogger.com

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#2581]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster Blocklist

### Which domain(s) should be unblocked?

blogger.com

### Why should the domain(s) be unblocked?

Google Play site  required login to install app on device. After enter password redirect to 
`https://accounts.blogger.com/accounts/SetSID?ssdc=1&sidt=<LONG HASH>&continue=https://play.google.com/web/store/apps/details?id%3Dcom.bitwarden.authenticator%26raii%3Dcom.bitwarden.authenticator%26raboi%3DCAE%253D%26rasi%3D-<LONG HASH>=1&dbus=PL`

After unblock domain all went fine
![20240501-1714581922](https://github.com/hagezi/dns-blocklists/assets/9846948/27dc9793-3d27-43b1-8ef9-b72b751b1da1)

**Comment by hagezi** [comment]
The domain is not blocked in the normal lists. It is only blocked in the Badware Hoster list.

**Comment by FadeMind** [comment]
@hagezi I read again logs and saw this too. Closing. 
Regards
