### ISSUE TITLE
eSound Pangle Ads

### ISSUE THREAD

**Issue by RAiNYRENJi** [hagezi/dns-blocklists#2584]
### Which domain(s) should be blocked?

p16-ttam-va.ibyteimg.com
p16-sign-sg.tiktokcdn.com
pangleglobal.com (just in case)
mediation.unity3d.com

### Why should these domain(s) be blocked?

Even though the Pangle ad domains are blocked by the Hagezi filters, without these domains blocked this would keep showing up and try to load:

![Screenshot_20240411_182311.jpg](https://github.com/ragibkl/adblock-dns-server/assets/161404404/1d6abf8b-6cb9-4e14-a59b-ddba2ccbeaa3)

**Comment by hagezi** [comment]
p16-ttam-va.ibyteimg.com and
p16-sign-sg.tiktokcdn.com 
cannot be blocked for the masses as normal content is also delivered via these domains.

**Comment by hagezi** [comment]
I tested this in the Tiktok app, couldn't find any restrictions at first, but since I'm not sure, I'll only block the domains in Ultimate for now.

**Comment by hagezi** [comment]
@RAiNYRENJi Thanks, I will implement it like this.
