### ISSUE TITLE
"La Presse" impersonating news website

### ISSUE THREAD

**Issue by jul059** [hagezi/dns-blocklists#2588]
### Which domain(s) should be blocked?

https://news-rebit.com/

### Why should these domain(s) be blocked?

Scam, impersonating a legitimate news website. (example: [Scam page](https://news-rebit.com/gr5xF9f6))

Not picked-up by other lists after a few days.

**Comment by jarelllama** [comment]
Can't seem to access: `404 Not Found`. Appears to be down. Will add in case it comes back up.

**Comment by iam-py-test** [comment]
The example page still works for me: https://tria.ge/240505-sdnaesgd96/behavioral1
Thanks
