### ISSUE TITLE
cdn.elev.io blocked in light.txt

### ISSUE THREAD

**Issue by rainforest1155** [hagezi/dns-blocklists#26]
Could you add cdn.elev.io to the whitelist? It's a service used as a knowledge base by different companies and with this blocked, the knowledge base / support pages and in product help of companies using the service no longer work.

For example SmugMug is using it for its knowledge base on www.smugmughelp.com .

Thanks!

**Comment by hagezi** [comment]
Thanks, removed.

ping @badmojr: blocked in 1Hosts lite/pro
