### ISSUE TITLE
jbzd.com.pl required google-analytics.com for solve RECAPTCHA

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#2602]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

google-analytics.com

### Why should the domain(s) be unblocked?

Site https://jbzd.com.pl  for login/create account/reset password using RECAPCHA from Google. 
After  enter data prompt to solve RECAPTCHA popup and without unlocked `google-analytics.com` site does not finish properly proccess. 
Custom rule solve issue:
```
||google-analytics.com^$denyallow=jbzd.com.pl
```

![20240504-1714843253](https://github.com/hagezi/dns-blocklists/assets/9846948/cbe482fa-ead0-4c5a-8434-3bb65a615058)

For resolving RECAPTCHA I used:
https://chromewebstore.google.com/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl
Without unlocked  `google-analytics.com` does not work.

**Comment by hagezi** [comment]
Thank you, but that's something for the personal allowlist. The number 1 tracker is not unblocked in any of my lists.

**Comment by hagezi** [comment]
@FadeMind `||google-analytics.com^$denyallow=jbzd.com.pl` I'm surprised that this rule works, it contradicts the way denyallow works:

`||google-analytics.com^$denyallow=region1.google-analytics.com|www.google-analytics.com`

https://adguard-dns.io/kb/general/dns-filtering-syntax/#denyallow-modifier

**Comment by FadeMind** [comment]
@hagezi My bad. 
In the first opt I added 
||google-analytics.com^
Next I followed by denyallow from TLDs, but You have right. My suggestion is wrong.

**Comment by FadeMind** [comment]
@hagezi so how to handle exception in right way?

**Comment by hagezi** [comment]
You can unblock them for one client or for all, but not for a specific domain.
`@@||google-analytics.com^$client=MyPhone`

**Comment by FadeMind** [comment]
@hagezi I found source of the issues, my ISP using CG-NAT. One public IPv4 address is shared between many AP routers. Google does not like this and sometimes freak out. 
```
@@||analytics.google.com^
@@||google-analytics.com^
```
workaround this mess and reCAPTCHA can be solved. 
Regards
