### ISSUE TITLE
igg-games.com

### ISSUE THREAD

**Issue by GitGitu79** [hagezi/dns-blocklists#2606]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

||igg-games.com^

### Why should the domain(s) be unblocked?

I don't know why this one get blocked but other game piracy site work normally, this is the only game pirating site that have almost every game up to date in a week upon request, if it's popular game it get updated in 3 day.

**Comment by hagezi** [comment]
It was marked as unsafe because it spreads malware in the downloads. I will unblock it, but be careful with the downloads.

See, also: https://github.com/hagezi/dns-blocklists/issues/2561

FYI: @MIOGMIOG
