### ISSUE TITLE
Block Fake Shopping Website - 93mobiles

### ISSUE THREAD

**Issue by auditmn** [hagezi/dns-blocklists#2607]
### Which domain(s) should be blocked?

93mobiles.com

### Why should these domain(s) be blocked?

This report indicates potential scamming on the website.

The website's contact page lists an address that a business at the location claims is fake in their Google Maps reviews.

Additional Info:
Contact Page: https://93mobiles.com/contact/
Google Maps Location: https://maps.app.goo.gl/g7HDTkyH4YynpTe38
Google Maps Review: https://maps.app.goo.gl/7K61Wn6XPrG8jVJw9

**Comment by jarelllama** [comment]
Common scam search term in the About page: https://www.google.com/search?q=%22our+goal+is+to+make+shopping+easier,+faster,+and+more+convenient+than+ever+before+for+our+customers.%22&sca_upv=1&cs=0&filter=0#ip=1
