### ISSUE TITLE
Request: Filter Lists

### ISSUE THREAD

**Issue by nightznero** [hagezi/dns-blocklists#2616]
Helloz HaGi,

After checking sources i have noticed that You using `Gambling` and `Piracy` lists from `TheBlockListProject` in ur extensions. How about adding lists that blocking most sh1t without interrupting user like;
`Abuse` `Ads` `Fraud` `Malware` `Phishing` `Ransomeware` `Scam` to all Your lists and to Ultimate maybe `Tracking` (cuz Tracking sometimes crash some sites like Ali I guess) ? [Link to all lists mentioned above](https://github.com/blocklistproject/Lists?tab=readme-ov-file#main-lists)
And also list that I think should be necessary in all lists or at least in `TIF`
https://github.com/cbuijs/accomplist/raw/master/typosquat/plain.black.domain.list
Best Regards, NIGHTZNERO.

**Comment by hagezi** [comment]
See: https://github.com/hagezi/dns-blocklists/issues/181

**Comment by hagezi** [comment]
I don't use Typosqatting lists because they make the TIF list explode in size. It is already huge. My lists also only contain domains that resolve, with Typosqatting lists most domains are dead.
That would be something for a separate list, but there are already enough of them.

**Comment by jarelllama** [comment]
@nightznero, heads up that my [Scam Blocklist](https://github.com/jarelllama/Scam-Blocklist) includes typosquatting NRDs that resolve. These domains are already included in both TIF medium and full.

Example domains recently retrieved:
```
10:04:51 06-05-24,saved,airbb.info,dnstwist
10:04:51 06-05-24,saved,airbnbh.shop,dnstwist
10:04:51 06-05-24,saved,airbnbj.bond,dnstwist
10:04:51 06-05-24,saved,alibab.site,dnstwist
10:04:51 06-05-24,saved,aliexperss.net,dnstwist
10:04:51 06-05-24,saved,amazol.store,dnstwist
10:04:51 06-05-24,saved,banance.site,dnstwist
10:04:51 06-05-24,saved,binanve.shop,dnstwist
10:04:51 06-05-24,saved,bitc0in.online,dnstwist
10:04:51 06-05-24,saved,bitcoinm.org,dnstwist
10:04:51 06-05-24,saved,bitcooin.site,dnstwist
10:04:51 06-05-24,saved,bltcoin.shop,dnstwist
10:04:51 06-05-24,saved,bnance.online,dnstwist
10:04:51 06-05-24,saved,chatgpt5.org,dnstwist
10:04:51 06-05-24,saved,chatgptj.com,dnstwist
10:04:51 06-05-24,saved,chatgptq.com,dnstwist
10:04:51 06-05-24,saved,coinbased.shop,dnstwist
10:04:51 06-05-24,saved,coinbose.net,dnstwist
10:04:51 06-05-24,saved,cry-pto.shop,dnstwist
10:04:51 06-05-24,saved,crypte.shop,dnstwist
10:04:51 06-05-24,saved,crypto2.shop,dnstwist
10:04:51 06-05-24,saved,dchatgpt.com,dnstwist
10:04:51 06-05-24,saved,disaord.com,dnstwist
10:04:51 06-05-24,saved,discard.store,dnstwist
10:04:51 06-05-24,saved,disord.info,dnstwist
10:04:51 06-05-24,saved,faebook.cn,dnstwist
10:04:51 06-05-24,saved,fansy.shop,dnstwist
10:04:51 06-05-24,saved,foogle.store,dnstwist
10:04:51 06-05-24,saved,hitcoin.shop,dnstwist
10:04:51 06-05-24,saved,homedep0t.com,dnstwist
10:04:51 06-05-24,saved,ilibili.com,dnstwist
10:04:51 06-05-24,saved,itcoin.shop,dnstwist
10:04:51 06-05-24,saved,megamask.shop,dnstwist
10:04:51 06-05-24,saved,netflix0.com,dnstwist
10:04:51 06-05-24,saved,netfliz.site,dnstwist
10:04:51 06-05-24,saved,onlyfan.shop,dnstwist
10:04:51 06-05-24,saved,openci.shop,dnstwist
10:04:51 06-05-24,saved,spotif.org,dnstwist
10:04:51 06-05-24,saved,steamcommuniy.com,dnstwist
10:04:51 06-05-24,saved,steamcomnnunity.store,dnstwist
10:04:51 06-05-24,saved,telegramb.org,dnstwist
10:04:51 06-05-24,saved,telegramr.org,dnstwist
```
