### ISSUE TITLE
Fix: Facebook on iPad loads incorrectly

### ISSUE THREAD

**Issue by Byteintosh** [hagezi/dns-blocklists#2617]
### Which AdBlocker/DNS cloud service do you use?

ControlD, NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

graph.facebook.com

### Why should the domain(s) be unblocked?

Facebook on iPad loads incorrectly when using **Ultimate** blocklist so I check what domain has been blocking when application tried to load and found `graph.facebook.com`

I try to unblock it and it works again.

Here are screenshots sorry for the language:

![2024_05_06_18_29_IMG_0001](https://github.com/hagezi/dns-blocklists/assets/158021536/0b690bb3-5bdb-4580-af71-087f2be5bd16)
![2024_05_06_18_30_IMG_0006](https://github.com/hagezi/dns-blocklists/assets/158021536/1af66dee-8379-4e32-a095-a18e88139db5)
![2024_05_06_18_30_IMG_0005](https://github.com/hagezi/dns-blocklists/assets/158021536/63a7f5c5-3f69-42c0-b7d4-c6944fe5bae0)
![2024_05_06_18_30_IMG_0004](https://github.com/hagezi/dns-blocklists/assets/158021536/04cb6def-a0f9-4db3-9e65-0e6f3a1583d8)
![2024_05_06_18_30_IMG_0003](https://github.com/hagezi/dns-blocklists/assets/158021536/9aea3d4e-aae7-4542-abbb-ea10a0569fc2)
![2024_05_06_18_30_IMG_0002](https://github.com/hagezi/dns-blocklists/assets/158021536/d7c3bc91-a6a6-4b4b-9928-3f092d6fdaa0)

**Comment by hagezi** [comment]
Yes, see: https://github.com/hagezi/dns-blocklists#ultimate

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/83df887b-65c7-4beb-97fd-fed89625e1c8)

For ypur personal allowlist: https://github.com/hagezi/dns-blocklists/blob/main/share/facebook.txt
