### ISSUE TITLE
block this domains asap

### ISSUE THREAD

**Issue by userforsource** [hagezi/dns-blocklists#2624]
### Which domain(s) should be blocked?

tracker.istole.it
bttracker.crunchbanglinux.org
tracker.leechers-paradise.org

### Why should these domain(s) be blocked?

Malicious activity this domain doing dns-rebinding.
And other shaddy stuff.

**Comment by hagezi** [comment]
For tracker.leechers-paradise.org I don't see any DNS rebinding, seems to be a normal torrent tracker or am I missing something?

https://otx.alienvault.com/indicator/domain/tracker.leechers-paradise.org

**Comment by hagezi** [comment]
tracker.istole.it
bttracker.crunchbanglinux.org

Resolve to localhost.

Will be added (TIF) on next release.

**Comment by userforsource** [comment]
![Screenshot_20240508-093556~2](https://github.com/hagezi/dns-blocklists/assets/162728301/d7df5471-1a21-4889-87ef-bc789fc16aaa)
