### ISSUE TITLE
mediafire.com

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [hagezi/dns-blocklists#2625]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Anti Piracy

### Which domain(s) should be unblocked?

mediafire.com

### Why should the domain(s) be unblocked?

Legit website

**Comment by hagezi** [comment]
That's exactly how it is and that's why the domain is blocked in anti-piracy.
