### ISSUE TITLE
More additions to the windows tracker blocker

### ISSUE THREAD

**Issue by GiddyGoatGaming** [hagezi/dns-blocklists#263]
https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Cyber-Sicherheit/SiSyPHus/Telemetrie-Endpunkte_Windows10_Build_Build_21H2.xlsx?__blob=publicationFile&v=3

There are some domains missing in the windows tracker blocker blocklist that should be included I feel. I’m not sure how many domains on this list I’m suggesting taking from are already included in your blocklist 

the domains i see missing on first glance that should be included include:
au-v10.events.data.microsoft.com
au-v20.events.data.microsoft.com
v10.events.data.microsoft.com
v10.vortex-win.data.microsoft.com

**Comment by hagezi** [comment]
They are in the source but have been whitelisted, breaks Windows/XBox Gaming Achievements.
Could possibly include them in the Ultimate anyway.

**Comment by GiddyGoatGaming** [comment]
> They are in the source but have been whitelisted, breaks Windows/XBox Gaming Achievements.
> Could possibly include them in the Ultimate anyway.

Oh I see👍
