### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by moonstrawberrysweetpotato** [hagezi/dns-blocklists#2641]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

booktoki337.com
booktoki336.com
manatoki336.net

### Why should the domain(s) be unblocked?

they are all normal websites but seems to be flagged as phishing due to the recently increased usage

**Comment by jarelllama** [comment]
Added from my Scam Blocklist. Virustotal's vendors deem it as phishing: https://www.virustotal.com/gui/domain/booktoki337.com

I'll check manually in a bit.

**Comment by jarelllama** [comment]
Appears to be book/comic hosting site where booktoki337.com and manatoki337.net appears to be the main site. booktoki336.com and manatoki336.net redirect to their '337' domain. According to users, their domain changes often with the number of the back incrementing each time.

Seems to be genuinely used by people:
https://www.reddit.com/r/ProgressionFantasy/comments/1cmaano/webnovel_i_recommend_that_i_have_been_waiting_for/
https://www.reddit.com/r/DamnReincarnation/comments/ztodzp/comment/l26yl1z/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
https://www.reddit.com/r/DamnReincarnation/comments/1122sg3/comment/l0mvn1f/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I will unblock on my end. @iam-py-test @xRuffKez do you want to do a malware analysis?

**Comment by hagezi** [comment]
Thanks @jarelllama
