### ISSUE TITLE
Unblock embed.ly

### ISSUE THREAD

**Issue by bbhtt** [hagezi/dns-blocklists#265]
List: Ultimate

It's used to provide embedded content in various websites, most notably Reddit https://embed.ly/stories/reddit in the form of image/video.

For example try browsing https://www.reddit.com/r/gifs/

See also https://github.com/EnergizedProtection/block/issues/74, https://github.com/EFForg/privacybadger/issues/991, https://github.com/EFForg/privacybadger/issues/863

**Comment by hagezi** [comment]
Thanks, removed.
