### ISSUE TITLE
Block spyware domains based on the report from Amnesty International

### ISSUE THREAD

**Issue by onmyouji** [hagezi/dns-blocklists#2652]
### Which domain(s) should be blocked?

The full list of the domains can be found here:
https://github.com/AmnestyTech/investigations/tree/master/2024-05-02_wintego_helios

https://www.amnesty.org/en/documents/asa21/7974/2024/en/  (the domains are listed on Table 3, Table 4, and Table 6)

### Why should these domain(s) be blocked?

Amnesty International recently published a report about the sales of [spyware and surveillance products to Indonesia](https://securitylab.amnesty.org/latest/2024/05/global-a-web-of-surveillance-unravelling-a-murky-network-of-spyware-exports-to-indonesia/). 

They also published a list of spyware domains, these domains are not only linked to Indonesia, other suspect domains also cloned media websites from Europe and multiple news websites based in Senegal or other sub-Saharan African based websites.

The list of domains can be found on their github: https://github.com/AmnestyTech/investigations/tree/master/2024-05-02_wintego_helios

There are also some domains not included on the github, which can be found on the full PDF report: https://www.amnesty.org/en/documents/asa21/7974/2024/en/ (the domains are listed on Table 3, Table 4, and Table 6)

**Comment by eviltracker** [comment]
Bloquer complètement Amnesty International 🤣
