### ISSUE TITLE
search.yahoo.com

### ISSUE THREAD

**Issue by ChaseKnowlden** [hagezi/dns-blocklists#2653]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Safesearch not supported

### Which domain(s) should be unblocked?

search.yahoo.com

### Why should the domain(s) be unblocked?

This search engine is used by McAfee WebAdvisor. It's a legit search engine.

**Comment by iam-py-test** [comment]
> A blocklist for blocking search engines that do not support Safesearch.

I think it is the former. See https://github.com/hagezi/dns-blocklists/issues/2649 as precedent.
Thanks

**Comment by hagezi** [comment]
a)

**Comment by hagezi** [comment]
"A blocklist for blocking search engines that do not support Safesearch."

I don't know what is misleading about this description. People just don't read ...

**Comment by xRuffKez** [comment]
@HellboyPI to prevent minors from accidently seeing noodles and the other hidden two eyes a woman brings with
