### ISSUE TITLE
Merging Threat Intelligence Feeds into the Ultimate filter?

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2662]
Would it be a good idea to incorporate the full Threat Intelligence Feeds into Hagezi's Ultimate DNS filter? It appears that NextDNS has not taken steps to integrate the Threat Intelligence Feed into their system, so adding the full TIF list to the Ultimate filter might be a viable solution.

Additionally, we could consider shifting all the contents of the current Ultimate to Pro++, moving Pro++ to regular Pro, and then upgrading Ultimate to include Threat Intelligence Feeds. These might seem like unconventional or stupid suggestions, but I thought it was worth mentioning. Thank you so much for your contributions.

**Comment by iam-py-test** [comment]
If my memory serves me correctly, doing this would make the Ultimate filter too big, causing problems with GitHub.
I might be wrong, through.
Thanks

**Comment by xRuffKez** [comment]
If Ultimates gets TIF included, the size gets too latge for Github, thereby it stays seperated unfurtunately.

**Comment by hagezi** [comment]
That's it, too big for Github and some adblockers.

**Comment by hagezi** [comment]
@PhoenixFossGR See,also: https://github.com/hagezi/dns-blocklists/issues/2466#issuecomment-2039984664
