### ISSUE TITLE
Hagezi Ultimate Mini 

### ISSUE THREAD

**Issue by Poochy1130** [hagezi/dns-blocklists#2666]
I'm currently using hagezi ultimate with 1 host pro in my dns filter I also have the control D server for tif full as my dns upstream with me using that server would it benefit to use hagezi ultimate mini (under the impression that the mini doesn't have the medium tif included and I don't need it since I'm using the server) or I would be missing out on stuff

**Comment by hagezi** [comment]
If you use a mobile adblocker such as AdGuard Pro, it makes sense to use the smaller mini version. If you use a network-wide DNS blocker such as AdGuard Home, then use the larger full version.

**Comment by Poochy1130** [comment]
Thank you for the insight however does mini use any tif at all like the ultimate regular

**Comment by hagezi** [comment]
The mini makes sense for AdGuard for iOS because iOS only has limited RAM available for apps. AdGuard Pro causes problems from approx. 500000 DNS rules in total.

**Comment by hagezi** [comment]
Yes, the Ultimate contains domains from the 1Hosts Pro, but my lists are not 1:1 copies of sources, see: https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources
