### ISSUE TITLE
Various Firefox/Mozilla Domains

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#2676]
### Which domain(s) should be blocked?

contile.services.mozilla.com
contile-images.services.mozilla.com
coverage.mozilla.org
crash-stats.mozilla.com
crash-stats.mozilla.org
firefox-android-home-recommendations.getpocket.com
spocs.getpocket.com
topsites.services.mozilla.com

### Why should these domain(s) be blocked?

Figured these domains would be of interest.

contile.services.mozilla.com - Responsible for sponsored top sites, promotions, and other sponsored content on Firefox, more info on Contile [here](https://github.com/mozilla-services/contile).
contile-images.services.mozilla.com - Same as above.
coverage.mozilla.org - [Firefox Coverage Telemetry](https://blog.mozilla.org/data/2018/08/20/effectively-measuring-search-in-firefox/).
crash-stats.mozilla.com - Used for Firefox crash reporting.
crash-stats.mozilla.org - Same as above.
firefox-android-home-recommendations.getpocket.com - Responsible for promotions and sponsored content on Firefox on Android.
spocs.getpocket.com - Spocs is short for sponsored content, displays on Firefox's home page.
topsites.services.mozilla.com - Another domain responsible for Firefox's sponsored "top sites".

**Comment by hagezi** [comment]
The domains mentioned were not added because they are dead (NXDOMAIN) and are therefore sorted out by my build system anyway.

**Comment by hagezi** [comment]
Thanks @Retold3202, added.
