### ISSUE TITLE
Unblock *.pdcdn1.top

### ISSUE THREAD

**Issue by bbhtt** [hagezi/dns-blocklists#268]
List: Ultimate

Hosts books on PDFDrive

Eg. https://www.pdfdrive.com/living-in-the-light-a-guide-to-personal-transformation-d10172273.html

https://fxcg9wx15m.pdcdn1.top/dl2.php?id=10172273&h=84f0f3490acb0a861ce0cf97be914eed&u=cache&ext=pdf&n=Living%20in%20the%20light%20a%20guide%20to%20personal%20transformation

The first part of the url is randomised.

**Comment by hagezi** [comment]
Thanks, removed.
