### ISSUE TITLE
Mini Variants 

### ISSUE THREAD

**Issue by Poochy1130** [hagezi/dns-blocklists#2681]
Hagezi do the mini Variants include titf medium or it's the regular Variants that include tiff medium as the github doesn't specify this, if not does the mini include any tif period

**Comment by hagezi** [comment]
No and No.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/b8b1ccb2-0832-451a-b94b-4ce8e248aa96)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/7dbf9352-a4b2-4dfc-a3cc-d37535fa58f7)
