### ISSUE TITLE
hassampc.com

### ISSUE THREAD

**Issue by SeriousHoax** [hagezi/dns-blocklists#2684]
### Which domain(s) should be blocked?

`https://hassampc.com/`

### Why should these domain(s) be blocked?

It's site where many fake cracks can be found. 
One example: `https://hassampc.com/norton-360-crack/`
This leads to download malware, mostly data stealer malware. Many of which are initially not detected by the default AV, Microsoft Defender. 
So, it should be blocked IMO.
It's currently blacklisted by Kaspersky, Norton/Symantec, Malwarebytes and probably some others.

Along with TIF, add it to Pro++ list if possible since that's the one I mainly use.

**Comment by hagezi** [comment]
![image](https://github.com/hagezi/dns-blocklists/assets/104343908/516e15c6-b506-449f-9f41-d635d1a1ab73)
