### ISSUE TITLE
Chatbase.co blocked by Hagezi DNS Pro

### ISSUE THREAD

**Issue by XBadFellaX** [hagezi/dns-blocklists#2687]
### Which AdBlocker/DNS cloud service do you use?

AdGuard, ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

https://www.chatbase.co/

### Why should the domain(s) be unblocked?

Chatbase is an AI service that provides the ability to chat with documents or create your own chatbots. Not sure why it is blocked.

**Comment by hagezi** [comment]
Via AdGuard Annoyances Filter
