### ISSUE TITLE
TIF-list has grown really big...

### ISSUE THREAD

**Issue by iJorgen** [hagezi/dns-blocklists#2690]
Hi!

My firewall seems to have a limit of 524288 items in an ipset and noticed the TIF-list has grown to 598858 items. Not sure how the firewall handles it, because it shows 523599 items imported in the IP-set and I see over 100 MB extra RAM used so getting a bit too much for a home-router to handle.

I can see this in the firewall code:
`ipset create "$setname" hash:net maxelem 524288`

Any thoughts or plans to create a TIF-light list where the size always is below 250K items as before?!

**Comment by hagezi** [comment]
Fixed in the next release, the build is currently running and will be finished in about 1.5 hours.
