### ISSUE TITLE
config2.mparticle.com

### ISSUE THREAD

**Issue by Foothill2135** [hagezi/dns-blocklists#2693]
### Which domain(s) should be blocked?

config2.mparticle.com

### Why should these domain(s) be blocked?

This tracking domain is found when ads play on Peacock. It is included in AdGuards DNS filter lists, but for some reason is not included in OISD big or Hagezi Pro++. I have noticed no ill-effects of blocking this domain while streaming and I did not see a previous issue opened about this domain.

**Comment by Foothill2135** [comment]
Thanks for the info. It not being blocked in OISD makes sense due to the lists intention of not having any breakage. I wonder if it makes sense to block it in Pro++, but leave it unblocked in Lite & Normal?

This seems like a very niche use case where it could cause breakage, whereas blocking it in the more aggressive lists would prevent a known tracking domain. Just a thought.

**Comment by xRuffKez** [comment]
I'm very sure that this domains will be added on Pro++ and Ultimate.

@hagezi please doublecheck for breakage and add my PR if applicable.
