### ISSUE TITLE
||js.sentry-cdn.com^

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#27]
When ```||js.sentry-cdn.com^``` is blocked it breaks ```https://www.pizzahut.com.au/``` can't put store information or address in etc.

Unblocking ```||js.sentry-cdn.com^``` allows for postcode/address to be put in to set delivery or pickup of pizza.

**Comment by hagezi** [comment]
Are you sure that blocking `js.sentry-cdn.com` will cause this? I can't really imagine that. `sentry-cdn` is tracking. Can you provide more details and what blocker are you using?

I can't test it myself, wrong region.

**Comment by hagezi** [comment]
I was able to test it after all, you're right. I'll put `js.sentry-cdn.com` on the whitelist. Thanks!

![grafik](https://user-images.githubusercontent.com/104343908/186153441-1989b6b9-4b42-4bc2-8426-56492032cdeb.png)
