### ISSUE TITLE
Cloudflare 

### ISSUE THREAD

**Issue by Poochy1130** [hagezi/dns-blocklists#2703]
h3://1.1.1.1/dns-query

h3://cloudflare-dns.com/dns-query

What are the difference between this 2 cloudflare servers and between both of them which is the better one to use hagezi if I was choosing between these 2 h3 cloudflare servers for adguard pro

**Comment by hagezi** [comment]
None, the lower one contains the domain, the upper one contains the IP of the domain.

Please only blocklist topics in future. There are other places for such questions.
