### ISSUE TITLE
Remove hsbc.co.uk from NRD Lists

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2712]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

hsbc.co.uk

### Why should the domain(s) be unblocked?

**Can’t select NRD blocklist.** 

Please remove hsbc.co.uk from the NRD lists. 

This is a legitimate website for HSBC Bank in the UK and has been registered for over 25+ years. 

It would be interesting to know how this ended up on the NRD list.

**Comment by hagezi** [comment]
The NRD lists are as they are. They normally only contain new domains from the last N days, which can also include false positives. I have noticed a few domains in the last few days that are older and have no place there. However, these were also found in the NRD services of AdGuard and ControlD.

I do not maintain an allowlist for the NRD lists, they are taken over unchanged by the services.

The domain comes from the 10-day feed from whoisds.com

Unblocking must be done in the personal allowlist.

**Comment by Dynamic5912** [comment]
Understood. 

I've added **@@||hsbc.co.uk^$important** to my AGH Custom Filtering Rules and all is working again. 

Cheers!

**Comment by hagezi** [comment]
I'll see if I can quickly implement something that sorts out such domains. I also wonder how something like this can end up on an NRD feed.

**Comment by hagezi** [comment]
> I've added **@@||hsbc.co.uk^$important** to my AGH Custom Filtering Rules and all is working again.

Better use `||hsbc.co.uk^$badfilter`, see: https://adguard-dns.io/kb/general/dns-filtering-syntax/#badfilter-modifier

**Comment by Dynamic5912** [comment]
Thanks.

Maybe some sort of separately maintained whitelist to add reported FP's?

I'm not sure how you would implement it :)

**Comment by hagezi** [comment]
Yes, I create the Allowlist. It would be nice if I could eliminate them "automatically". One possibility would be to use the Umbrella Top 1M list as the allowlist. I'll see what gets removed.

**Comment by Dynamic5912** [comment]
Thanks as always!

Happy to test any lists before making them GA.

**Comment by xRuffKez** [comment]
> I'll see if I can quickly implement something that sorts out such domains. I also wonder how something like this can end up on an NRD feed.

I tried to develop an nrd script, which tool too much power to generate... but i can answear your question. NRDs might also come as changed state. E.g. registrant change

**Comment by hagezi** [comment]
@xRuffKez Thanks, I noticed that too. I currently use the Umbrella 1M Toplist to filter out popular domains.
