### ISSUE TITLE
blindsclassactionsettlement.com

### ISSUE THREAD

**Issue by Tomadock** [hagezi/dns-blocklists#2716]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

blindsclassactionsettlement.com

### Why should the domain(s) be unblocked?

Class action lawsuit claim site for blinds.com.

**Comment by hagezi** [comment]
@Tomadock Can't find the domain in my lists.
