### ISSUE TITLE
Adblocking Setup 

### ISSUE THREAD

**Issue by Poochy1130** [hagezi/dns-blocklists#2717]
Is this a good setup for my iPhone Hagezi? (Blocking method NXdomain, ipv6 blocked and ttl set to 24 hours white list meta blockers and 2 personal things)
![IMG_1290](https://github.com/hagezi/dns-blocklists/assets/167346032/31db834d-7861-4d58-a21e-6c353138c777)
![Image](https://github.com/hagezi/dns-blocklists/assets/167346032/6d86af33-1bf4-4c08-a086-565187aaf3a7)

**Comment by hagezi** [comment]
I would also use the TIF medium list.

**Comment by Poochy1130** [comment]
Why if im running the control D tif server (isn't the server tif full)

**Comment by hagezi** [comment]
Looks good, if you don't use an upstream with TIF, I would also use the TIF medium list.

**Comment by Poochy1130** [comment]
Alright so since I have the tif upstream medium tif not needed for dns filter, thank you

**Comment by hagezi** [comment]
Theoretically, you could still add the PopupAds list, as the mini only contains one part.

**Comment by Poochy1130** [comment]
So only the full ultimate with full tiff gives you the complete pop up list and the mini even with full tif doesn't give it to you all did I understand that correctly

**Comment by hagezi** [comment]
Yes

**Comment by Poochy1130** [comment]
Thank you hagezi for making the internet safer for everyone
