### ISSUE TITLE
strpst.com doppiocdn.net

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#2721]
### Which domain(s) should be blocked?

strpst.com
doppiocdn.net

### Why should these domain(s) be blocked?

Sample URL `https://www.yeptube.com/pl/video/1341801/hot-amateur-teen-girl-with-big-boobs-toying-pussy-on-cam`

Porn cam img hosting and CDN for m3u8 files. 
https://urlscan.io/domain/doppiocdn.net
https://urlscan.io/domain/img.strpst.com

Link domain from cam thumbnails `go.strpjmp.com` is already blocked by PRO

![20240518-1716057284](https://github.com/hagezi/dns-blocklists/assets/9846948/0070ba16-2c59-4c5a-bd46-d953499a05af)
![20240518-1716057199](https://github.com/hagezi/dns-blocklists/assets/9846948/985cdede-1079-4a04-a661-faad5e47ae1c)

**Comment by hagezi** [comment]
@FadeMind the domains have been unblocked: https://github.com/hagezi/dns-blocklists/issues/668

What is your recommendation?

**Comment by FadeMind** [comment]
@hagezi `omg.adult` is web cam porn site. If You block other common cam domains. Links from thumbnails does not work (`go.strpjmp.com`). Adguard Team will probably cut off these sections  after report  (pending). 
Compromise: block all and note for users: You use unpopular cam sites - unblock at your place CDNs and img hostings for that. 
Mostly domains are advertainment/scam purpose. 
You already blocked  xhamsterlive for example. 
But works  well good known chaturbate domains. For example.
`camd.com` or `chaturbate.com`
LiveJasmin is  blocked from google via adguard at  all (agressive ads scam).

IMHO add these and notice for users. 
If links does not work, for what they are active? hupuza dot com is already blocked - iframe.

**Comment by hagezi** [comment]
Yes, that makes sense. Thanks for the support.
