### ISSUE TITLE
vortex.hulu.com

### ISSUE THREAD

**Issue by Foothill2135** [hagezi/dns-blocklists#2722]
### Which domain(s) should be blocked?

vortex.hulu.com

### Why should these domain(s) be blocked?

The vortex.hulu.com domain is included in AdGuard's DNS filter list. It is whitelisted in OISD (Big) and appears to be also whitelisted in Pro++ as it has previously been lumped in with a list of domains possibly causing issues with Hulu. I have been testing blocking this domain over the last month while using NextDNS and have not run into any playback or functionality issues during this testing period on either tvOS or Android TV. 

As this does appear (to the best I can find) a first-party tracking domain from Hulu and I have not encountered any issues blocking it while running AdGuard's DNS filter list alongside Pro++ I might suggest adding vortex.hulu.com to the Pro++ and Ultimate block list while keeping it whitelisted in the less aggressive Light/Normal & Pro lists.

**Comment by hagezi** [comment]
Thanks, I'll block the domain in the aggressive lists. I'll take another look at it and possibly add it to the Pro.
