### ISSUE TITLE
Can we have a pfblocker list for DoH/VPN/TOR/Proxy Bypass?

### ISSUE THREAD

**Issue by moapu** [hagezi/dns-blocklists#2723]
can we please have a pfblocker list for DoH/VPN/TOR/Proxy Bypass?

**Comment by hagezi** [comment]
The list only makes sense if wildcard blocking is supported. It is impossible to include all the required subdomains, some of which are generic.

**Comment by hagezi** [comment]
For further explanation, see:

https://oisd.nl/faq#legacysyntaxes
