### ISSUE TITLE
SmartThings False link

### ISSUE THREAD

**Issue by azafrak** [hagezi/dns-blocklists#273]
Merhaba,

SmartThing uygulamasını kullanabilmek için asagida ki linklerin listeden kaldırılması gerekiyor. Bu konuda yardımcı olabilir misin.  

Teşekkürler. 

Hagezi MultiPro ++

*.api.st-av.net
*.uimetadata.samsungiotcloud.com
*.us-api.mcsvc.samsung.com

![3DA92A40-567D-426E-98B6-30A3C3D3F1A8](https://user-images.githubusercontent.com/30311445/215354615-13fb5c75-056b-480a-aede-3c5a66fe19bc.png)

**Comment by hagezi** [comment]
Thanks for your support, I'll check and remove the domains.

Desteğiniz için teşekkürler, alan adlarını kontrol edip kaldıracağım.

**Comment by hagezi** [comment]
Thanks, removed.

ping source: @badmojr
