### ISSUE TITLE
lf-cdn-tos.bytescm.com

### ISSUE THREAD

**Issue by tsm55555** [hagezi/dns-blocklists#2730]
### Which domain(s) should be blocked?

lf-cdn-tos.bytescm.com

### Why should these domain(s) be blocked?

Collect information 
The following is on their website 
———————————
“we may collect information such as IP address and operation log when you use Ocean Engine official website; and we may collect information such as your device model, device serial, operating system version, device identity information (Android ID for Android、 OAID，SIM card information such as ICCID, hardware serial number (SN); IDFV, IDFA for iOS)”

**Comment by hagezi** [comment]
@tsm55555 Do you have details that show that this domain is used for tracking? Payload? From where is the domain triggered?

**Comment by hagezi** [comment]
https://urlscan.io/search/#page.domain%3Alf-cdn-tos.bytescm.com

**Comment by tsm55555** [comment]
> @tsm55555 Do you have details that show that this domain is used for tracking? Payload? From where is the domain triggered?

The domain was triggered when I opened novel reading app （https://apps.apple.com/tw/app/summit-reader/id1307517930?l=en-GB）.

This domain is used by company oceanengine (https://www.oceanengine.io), which is a digital marketing platform.

I do not currently have proof that it is used for tracking or advertisements; I just find it peculiar that a novel reading app needs to connect to this domain. Maybe a further investigation is needed.

**Comment by hagezi** [comment]
@tsm55555 I couldn't find out any details quickly, except that it is also used for content delivery, which probably leads to restrictions somewhere. If I block it, then only in Ultimate for now.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/commit/fbcf804e7c0d93ff5c19526138ca2ca9e5641fd2

**Comment by tsm55555** [comment]
Sounds reasonable
