### ISSUE TITLE
strpst.com (NSFW)

### ISSUE THREAD

**Issue by backlogbacklog** [hagezi/dns-blocklists#2732]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### Other

AdGuard Desktop

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

`strpst.com`

### Why should the domain(s) be unblocked?

Breaks `https://stripchat.com/` (NSFW) 

NSFW site. Not ad or malware

</details> 

<details><summary>Screenshot:</summary>

![image](https://github.com/hagezi/dns-blocklists/assets/170260710/8ddf2b7b-81ed-456f-9a0f-34a79c34c21a)

**Comment by hagezi** [comment]
ping @fademind - https://github.com/hagezi/dns-blocklists/issues/2721

**Comment by FadeMind** [comment]
@backlogbacklog  if you need it add to whitelist. 
Many cam porn sites with adware are blocked in hagezi's lists. `strpst.com` is major tracking and content delivery  domain for them.
