### ISSUE TITLE
stripchat.com

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#2733]
### Which domain(s) should be blocked?

stripchat.com

### Why should these domain(s) be blocked?

After block root domain `strpst.com`- simple does not work. 
BTW https://github.com/search?q=repo%3AAdguardTeam%2FAdguardFilters%20stripchat.com&type=code
They tracking and have agressive ads.

**Comment by xRuffKez** [comment]
```
stripchat.global
stripchat.red
strip.chat
```

@hagezi

**Comment by FadeMind** [comment]
@hagezi root domain is not blocked only some subs.

**Comment by hagezi** [comment]
@FadeMind Thanks, the root domain should actually be blocked as of pro, but is only blocked as of pro++. I'll have a look at this in a moment.

**Comment by hagezi** [comment]
Fixed on next build.
