### ISSUE TITLE
Denylist: Include FMHY Filterlist in Hagezi lists

### ISSUE THREAD

**Issue by Xandar-YT** [hagezi/dns-blocklists#2734]
Link to list: https://windowsaurora.github.io/FMHYFilterlist/site/index.html#

This list consists of a lot of malicious sites/sites for malicious apps, which should not be visited/used by anyone.

Hagezi lists users would benefit a lot from this being included.

Reasoning for each blocked site can be found here: https://fmhy.pages.dev/unsafesites

If you feel that this list is too harsh or something, at least add it to the Ultimate list, please.

Thanks for this, and also thanks for maintaining the best blocklist ever.

**Comment by Xandar-YT** [comment]
Sorry about the wrong tag, I meant to put the denylist one.

**Comment by jarelllama** [comment]
Blocklist report generated: https://github.com/jarelllama/Blocklist-Checker/issues/113#issuecomment-2119564363

@hagezi the domains in Tranco contain many non-malicious domains

**Comment by hagezi** [comment]
https://raw.githubusercontent.com/WindowsAurora/FMHYFilterlist/main/filterlist.txt

Valid domains: 202

Covered by Ultimate + TIF: 47
```
1377x.to
allpcworld.com
app-valley.vip
blackboxrepacke.com
cracked-games.org
ezcrack.info
fitgirl.cc
fitgirl-repack.com
fitgirlrepack.games
fitgirlrepacks.co
fitgirlrepacksite.com
fitgirl-repacks.vip
fitgirl-repacks.website
fitgirlrepackz.com
ftuapps.dev
gamefabrique.com
haxnode.net
help.totalav.com
oceansofgamess.com
pcprotect.com
portable4pc.com
sadeempc.com
store.app-valley.vip
totalav.com
tutubox.io
wifi4games.com
www.pcprotect.com
www.sadeempc.com
www.totalav.com
www.wifi4games.com
z-lib.ee
z-lib.id
z-lib.io
zlib.is
z-lib.lol
zlib-official.com
zlibrary-global.com
zlibrary.is
z-library.live
zlibrary.lol
z-library-proxy.com
zlibrary.to
z-library.wiki
z-lib.tf
zlib.to
z-lib.wf
z-lib.yt
```

Popular domains (Umbrella Top 1M): 58
```
avast.com
avg.com
www.avg.com
avira.com
my.avira.com
www.avira.com
bitcomet.com
www.bitcomet.com
bittorrent.com
www.bittorrent.com
bluesmods.com
ccleaner.com
www.ccleaner.com
ccleanercloud.com
www.ccleanercloud.com
cnet.com
www.cnet.com
cyberghostvpn.com
www.cyberghostvpn.com
downloadly.ir
expressvpn.com
www.expressvpn.com
filecr.com
getintopc.com
igetintopc.com
igg-games.com
kik.com
limewire.com
mcafeemobilesecurity.com
www.mcafeemobilesecurity.com
norton.com
login.norton.com
us.norton.com
nortonlifelock.com
www.nortonlifelock.com
oceanofgames.com
opera.com
www.opera.com
pirate-bays.net
pirateproxy-bay.com
www.pirateproxy-bay.com
privateinternetaccess.com
www.privateinternetaccess.com
softonic.com
en.softonic.com
steamunlocked.net
thepiratebay.org
thepiratebay.party
thepiratebay0.org
thepiratebay10.org
thepiratebay10.xyz
tlauncher.org
tpb.party
utorrent.com
www.utorrent.com
zdnet.com
www.zdnet.com
zenmate.com
```

Remaining domains:
```
allpcworld.co
allpcworlds.com
appvalley-apk.com
crackshash.com.atlaq.com
bitlord.com
www.bitlord.com
bitlorddl.com
bluekik.pro
tlauncher.co.com
crackingpatching.com
crackingpatching.org
www.crackingpatching.org
crackshash.org
download.com
downloadly.net
downloadlyir.com
downloadlynet.ir
fitgirl-repack.net
fitgirl-repack.org
fitgirl-repack.site
fitgirl-repacks.cc
fitgirl-repacks.to
fitgirl-repacks.xyz
ww9.fitgirl-repacks.xyz
fitgirlpack.site
fitgirlrepacks.in
fitgirlrepacks.org
fitgirlrepacks.pro
fitgirltorrent.com
frostwire.com
www.frostwire.com
ftuapps.io
ftuapps.me
www.ftuapps.me
gamefabrique.ru
gendigital.com
www.gendigital.com
getinmac.com
getintomac.net
www.getintomac.net
getintopc.cc
getitintopc.com
gshade.org
www.gshade.org
igg-games.cc
kape.com
www.kape.com
karanpc.com
kickass-official.blue
kms-pc.com
kmsmatrix.com
mainrepo.org
mcafee.com
www.mcafee.com
mrepo.org
oceanofapks.com
oceanofgame.cc
oceanofgamesu.com
oceantogames.com
piratebay.live
piratebay.party
piratebayproxy.live
piratebayproxy.net
pirateproxy.live
pirateproxylive.org
polymc.org
rsload.net
s0ft4pc.com
sadeemapk.com
soft4pc.net
thehiddenbay.com
thekickasstorrents.com
thepiratebay.rocks
thepiratebay.vet
thepiratebay.zone
thepiratebay1.info
thepiratebay1.live
thepiratebay1.top
thepiratebay10.info
thepiratebay3.co
thepiratebay7.com
thepiratebays.info
thepiratebays.live
fitgirl-repacks.theproxy.vip
vstorrent.org
wifi4games.net
yasdl.com
z-lib.ai
z-lib.club
z-lib.dev
z-lib.ink
z-lib.li
z-lib.nl
z-lib.wiki
z-lib.ws
z-library.help
zlibis.com
```

**Comment by hagezi** [comment]
Will add the list to the TIF / TIF medium and let the build system sort out the "false positives" .

**Comment by MIOGMIOG** [comment]
> https://raw.githubusercontent.com/WindowsAurora/FMHYFilterlist/main/filterlist.txt
> 
> Valid domains: 202
> 
> Covered by Ultimate + TIF: 47
> 
> ```
> 1377x.to
> allpcworld.com
> app-valley.vip
> blackboxrepacke.com
> cracked-games.org
> ezcrack.info
> fitgirl.cc
> fitgirl-repack.com
> fitgirlrepack.games
> fitgirlrepacks.co
> fitgirlrepacksite.com
> fitgirl-repacks.vip
> fitgirl-repacks.website
> fitgirlrepackz.com
> ftuapps.dev
> gamefabrique.com
> haxnode.net
> help.totalav.com
> oceansofgamess.com
> pcprotect.com
> portable4pc.com
> sadeempc.com
> store.app-valley.vip
> totalav.com
> tutubox.io
> wifi4games.com
> www.pcprotect.com
> www.sadeempc.com
> www.totalav.com
> www.wifi4games.com
> z-lib.ee
> z-lib.id
> z-lib.io
> zlib.is
> z-lib.lol
> zlib-official.com
> zlibrary-global.com
> zlibrary.is
> z-library.live
> zlibrary.lol
> z-library-proxy.com
> zlibrary.to
> z-library.wiki
> z-lib.tf
> zlib.to
> z-lib.wf
> z-lib.yt
> ```
> 
> Popular domains (Umbrella Top 1M): 58
> 
> ```
> avast.com
> avg.com
> www.avg.com
> avira.com
> my.avira.com
> www.avira.com
> bitcomet.com
> www.bitcomet.com
> bittorrent.com
> www.bittorrent.com
> bluesmods.com
> ccleaner.com
> www.ccleaner.com
> ccleanercloud.com
> www.ccleanercloud.com
> cnet.com
> www.cnet.com
> cyberghostvpn.com
> www.cyberghostvpn.com
> downloadly.ir
> expressvpn.com
> www.expressvpn.com
> filecr.com
> getintopc.com
> igetintopc.com
> igg-games.com
> kik.com
> limewire.com
> mcafeemobilesecurity.com
> www.mcafeemobilesecurity.com
> norton.com
> login.norton.com
> us.norton.com
> nortonlifelock.com
> www.nortonlifelock.com
> oceanofgames.com
> opera.com
> www.opera.com
> pirate-bays.net
> pirateproxy-bay.com
> www.pirateproxy-bay.com
> privateinternetaccess.com
> www.privateinternetaccess.com
> softonic.com
> en.softonic.com
> steamunlocked.net
> thepiratebay.org
> thepiratebay.party
> thepiratebay0.org
> thepiratebay10.org
> thepiratebay10.xyz
> tlauncher.org
> tpb.party
> utorrent.com
> www.utorrent.com
> zdnet.com
> www.zdnet.com
> zenmate.com
> ```
> 
> Remaining domains:
> 
> ```
> allpcworld.co
> allpcworlds.com
> appvalley-apk.com
> crackshash.com.atlaq.com
> bitlord.com
> www.bitlord.com
> bitlorddl.com
> bluekik.pro
> tlauncher.co.com
> crackingpatching.com
> crackingpatching.org
> www.crackingpatching.org
> crackshash.org
> download.com
> downloadly.net
> downloadlyir.com
> downloadlynet.ir
> fitgirl-repack.net
> fitgirl-repack.org
> fitgirl-repack.site
> fitgirl-repacks.cc
> fitgirl-repacks.to
> fitgirl-repacks.xyz
> ww9.fitgirl-repacks.xyz
> fitgirlpack.site
> fitgirlrepacks.in
> fitgirlrepacks.org
> fitgirlrepacks.pro
> fitgirltorrent.com
> frostwire.com
> www.frostwire.com
> ftuapps.io
> ftuapps.me
> www.ftuapps.me
> gamefabrique.ru
> gendigital.com
> www.gendigital.com
> getinmac.com
> getintomac.net
> www.getintomac.net
> getintopc.cc
> getitintopc.com
> gshade.org
> www.gshade.org
> igg-games.cc
> kape.com
> www.kape.com
> karanpc.com
> kickass-official.blue
> kms-pc.com
> kmsmatrix.com
> mainrepo.org
> mcafee.com
> www.mcafee.com
> mrepo.org
> oceanofapks.com
> oceanofgame.cc
> oceanofgamesu.com
> oceantogames.com
> piratebay.live
> piratebay.party
> piratebayproxy.live
> piratebayproxy.net
> pirateproxy.live
> pirateproxylive.org
> polymc.org
> rsload.net
> s0ft4pc.com
> sadeemapk.com
> soft4pc.net
> thehiddenbay.com
> thekickasstorrents.com
> thepiratebay.rocks
> thepiratebay.vet
> thepiratebay.zone
> thepiratebay1.info
> thepiratebay1.live
> thepiratebay1.top
> thepiratebay10.info
> thepiratebay3.co
> thepiratebay7.com
> thepiratebays.info
> thepiratebays.live
> fitgirl-repacks.theproxy.vip
> vstorrent.org
> wifi4games.net
> yasdl.com
> z-lib.ai
> z-lib.club
> z-lib.dev
> z-lib.ink
> z-lib.li
> z-lib.nl
> z-lib.wiki
> z-lib.ws
> z-library.help
> zlibis.com
> ```

I noticed that you were checking the filterlist intended for use with uBlock Origin/forks, not DNS filtering, this blocklist is also available in ABP syntax for DNS filtering
https://raw.githubusercontent.com/WindowsAurora/FMHYFilterlist/main/filterlist-abp.txt

**Comment by FadeMind** [comment]
@hagezi 
Avira, Avast and Norton software is well known crap apps. If you block their root domains in TIF, users will start report that (app name) does not work.
Fake/warez domains blocking is good idea.
For example: McAffe sh!tty app is added to many OEM preinstalled devices, also included on Samsung Smartphones (part of device care). 

Just sayin.

**Comment by Xandar-YT** [comment]
Users of those crap "AVs" should stop using them entirely and not complain they are blocked. Those "AVs" are mostly spyware.

-------- Original Message --------
