### ISSUE TITLE
Startpage's presumably fingerprinting domain

### ISSUE THREAD

**Issue by v1s7** [hagezi/dns-blocklists#2752]
### Which domain(s) should be blocked?

vf.startpage.com

### Why should these domain(s) be blocked?

In my NextDNS logs (where the Ultimate list is used) the first ever mention of this domain was at `May 17, 2024`. Startpage is my main search engine, so this fingerprinting stuff is pretty fresh (and pretty sad).

Source: https://discuss.privacyguides.net/t/startpage-has-apparently-started-to-fingerprint-users/

> UPDATE: The URL parameters of the vf.startpage.com/ct network request (F12 > Network) from startpage.com contain a fingerprint. Taking the contents of the di URL parameter of this request and pasting it into your base64 decoder will give an output that contains among other things: browser plugin info, canvas data, User Agent, your Do Not Track setting, and some other data points.

> I have suddenly been getting JShelter (browser extension) fingerprint detection warnings about Startpage. It appears that Startpage is accessing WebGL data (JShelter Fingerprint Detector Report), Canvas data (JShelter Fingerprint Detector Report), and Speech Synthesis (from a Firefox banner saying Speech Synth. is not supported).

> The script that is collecting this data is on the subdomain vf.startpage.com. Disabling the script (along with the entire subdomain) via uBlock Origin does not appear to affect Startpage's ability to provide search results. The subdomain did not exist before the suspected fingerprinting started.

> In the Network tab in Firefox's debugger, POST requests appear to be sent to vf.startpage.com, containing at minimum my window size (ws: "1290x296", changes on window resize).

> I have a screen recording of this phenomenon from a fresh virtual machine: https://drive.proton.me/urls/RNZ4NQJHAW#faKIDqFIvqa9

**Comment by xRuffKez** [comment]
@hagezi fyi.
https://github.com/easylist/easylist/issues/19193

**Comment by xRuffKez** [comment]
> @hagezi fyi.
> https://github.com/easylist/easylist/issues/19193
> https://www.reddit.com/r/privacy/comments/1culldp/sudden_jshelter_fingerprint_warnings_about/
> 
> Startpage is also a product of the Ad Company System1
> https://www.reddit.com/r/privacy/comments/f3gqoc/privacy_browser_waterfox_appears_to_be_sold_to/

Always think about how it makes money. 
Nothing is free.
