### ISSUE TITLE
Unblock *.banuba.*

### ISSUE THREAD

**Issue by sdk-banuba** [hagezi/dns-blocklists#2754]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### Other

Avast Antivirus

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO mini, Multi PRO++, Multi PRO++ mini, Multi ULTIMATE, Multi ULTIMATE mini

### Which domain(s) should be unblocked?

`telemetry.banuba.cloud`
`stats.sdk.banuba.net`

### Why should the domain(s) be unblocked?

We assure you that we do not collect any personal information for tracking or advertising purposes and always act in strict accordance with the applicable data protection laws. The only purpose of the domain names `telemetry.banuba.cloud` and `stats.sdk.banuba.net` is to collect information relating to the performance and maintenance of our SDK. All our clients agree to collection of this information by signing license agreements for the usage of SDK and Data Protection Addendum attached to the license agreements which specifies the list of collected information.

**Comment by hagezi** [comment]
What data is transmitted in detail?
What triggers the transmission of the data?

**Comment by sdk-banuba** [comment]
Please, find https://www.banuba.com/faq/data-collection-processing -- to get detailed description about data collection, analytics processing, etc... For example, data description at -- https://www.banuba.com/faq/what-data-do-software-usage-analytics-include

Data processing -- https://www.banuba.com/faq/how-does-face-ar-sdk-process-data-on-the-web

Also, privacy policy -- https://www.banuba.com/privacy-policy

**Comment by hagezi** [comment]
@xRuffKez What do you think about that?

**Comment by sdk-banuba** [comment]
Hi again,

Please, pay attention to the https://www.banuba.com/faq/do-banuba-sdks-collect-any-personal-data
We do not collect, store or access any user personal data.

Parameters, mentioned above - device name, model, OS version, etc… are not used for any fingerprinting and are really useful for performance analysis and measurement. They allow to determine, for example, bottle-necks for neural networks execution, when one OS version performs faster than other, or if there are quality drawdowns for some particular mobile devices.

Application crashes, render FPS diagnostics, and all other things - that finally helps to deliver high-quality product to our clients.

Our SDK never uses MAC address directly, please, pay attention to the following information: https://www.banuba.com/faq/how-does-face-ar-sdk-process-data-on-the-web Based on OS platform, the most «horrible» is to build a combined hash string, used for UserID generation. Of course, the resulting hash couldn't be decoded back.
Relating to UserID - please, pay attention to the following information: https://www.banuba.com/faq/what-data-do-software-usage-analytics-include
This is unique identifier, that couldn't be matched with any other ID's, like IDFA, IDFV, and definitely couldn't be used for tracking or fingerprinting.

Please, note that we adhere to the high standards of privacy in our company and do not collect any of these parameters without our client's consent. Only if our clients consent to the collection of these parameters, we collect them. And, even then, the parameters collected can never be used for any fingerprinting, tracking or advertising purposes as mentioned above. The only reason of collection is to improve the SDK and experience of our clients with SDK. Our clients are aware of that and none of our clients have ever submitted any complaint concerning the SDK's collection of these parameters.

**As you have mentioned: "As long the blockage do not interrupt user experience in any ways, we do not remove matching domains". But by including our domain in the blocklist user experience of our clients is heavily interrupted making their user experience lower than ever and making it impossible for us to track any parameters and improve that user experience. Such interruption significantly affects our company which is acting only in accordance with client's consent.**

We do understand the important purpose that you are following but, please, note that we are not the company that shall be included into this blocklist as fingerprinting, tracking or advertising has never been and will never be our purpose.
