### ISSUE TITLE
Blocking social media users account

### ISSUE THREAD

**Issue by renatoyamane** [hagezi/dns-blocklists#2756]
We have amazing block lists, like blocking trackers, advertisement, gambling, etc.

Is missing just an important list to be blocked: social media accounts spreading misinformation, conspiracy theory, politicians.

People are now using their huge number of followers, posting **disinformation** to engage their followers, just to make money with the "monetization".

Please, help to make the internet a better place :-)

- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8853081/
- https://phys.org/news/2023-06-controversy-facebook-linked-users.html
- https://studyfinds.org/controversial-social-media-posts/
- https://www.logicallyfacts.com/en/analysis/social-media-engagement-misinformation-anger-and-algorithms
- https://today.usc.edu/usc-study-reveals-the-key-reason-why-fake-news-spreads-on-social-media/

Social media companies will not stop this, because disinformation is part and parcel of social media’s business model:

- https://theconversation.com/disinformation-is-part-and-parcel-of-social-medias-business-model-new-research-shows-217842

**Comment by hagezi** [comment]
I block domains in my lists, not URLs. These are DNS lists, not lists for content blockers.
