### ISSUE TITLE
Allow www.czuni.com

### ISSUE THREAD

**Issue by superduke1010** [hagezi/dns-blocklists#2759]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Unbound/DoT Cloudflare on OPNSense

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

https://www.czuni.com

### Why should the domain(s) be unblocked?

A benign website whose function is to support entrance into Czech unis.

**Comment by hagezi** [comment]
Not blocked in the normal lists. Only blocked in Badware Hoster via `webnode.cz`.
