### ISSUE TITLE
[False Positive] lalpathlabs.com

### ISSUE THREAD

**Issue by duaraghav** [hagezi/dns-blocklists#276]
Dr. Lal Path Labs(lalpathlabs.com) is one of the top medical lab tests provider, here in India. It seems that the Multi ULTIMATE lists is blocking this domain.

FYI I am using the list in a NextDNS config

**Comment by hagezi** [comment]
Thanks. Removed.

Blocked by CNAME indusprodcustomer3996.pc.cdn.bitgravity.com

Ping source: @migueldemoura

**Comment by duaraghav** [comment]
Thanks a lot
