### ISSUE TITLE
Pictures blocked at https://www.sagrosso.com

### ISSUE THREAD

**Issue by arturstat** [hagezi/dns-blocklists#2762]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

I am not sure.

### Why should the domain(s) be unblocked?

Several pictures are incorrectly blocked at
https://www.sagrosso.com/trending/2024/05/22/el-unico-color-de-zapatos-que-carolina-herrera-recomienda-para-las-mujeres-de-mas-de-40-anos/

**Comment by arturstat** [comment]
The following screenshot was taken with AdGuard DNS. There are empty spaces in place of the big pictures when NextDNS is used instead. The pictures are referred in the text and are supposed to be seen.

![Screenshot_20240523_000426_Chrome](https://github.com/hagezi/dns-blocklists/assets/57625194/07e86f34-ccbe-4299-a22d-a39570b514a5)

**Comment by FadeMind** [comment]
@hagezi 
![20240523-1716445479](https://github.com/hagezi/dns-blocklists/assets/9846948/5919925b-6184-45eb-876e-bc95953971d1)
![20240523-1716445465](https://github.com/hagezi/dns-blocklists/assets/9846948/cfe3db9d-c947-4258-b42f-8659321a274b)
![20240523-1716445413](https://github.com/hagezi/dns-blocklists/assets/9846948/942fbcec-7d31-4f5f-a27f-b6dac137c8dc)

**Comment by FadeMind** [comment]
@hagezi 
![20240523-1716445789](https://github.com/hagezi/dns-blocklists/assets/9846948/2d70f3a4-ad28-415c-a662-daabe61c3631)

**Comment by hagezi** [comment]
Thanks @FadeMind
