### ISSUE TITLE
Remove resultify.com and resultify.se domains

### ISSUE THREAD

**Issue by dmh** [hagezi/dns-blocklists#2765]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Little Snitch

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO mini, Multi PRO++, Multi PRO++ mini, Multi ULTIMATE, Multi ULTIMATE mini

### Which domain(s) should be unblocked?

resultify.com
resultify.se
blog.resultify.se
www.resultify.com
www.resultify.se

### Why should the domain(s) be unblocked?

This is a regular Marketing Agency site, there is no reason to have it in block list.

**Comment by sjhgvr** [comment]
Sources;

https://raw.githubusercontent.com/mullvad/dns-blocklists/main/lists/doh/adblock/frellwits-swedish-hosts-file
https://repo.or.cz/Adblock-list-backups-Frellwits-filter-lists.git/blob_plain/refs/heads/master:/Frellwits-Swedish-Hosts-File.txt

**Comment by hagezi** [comment]
Widely blocked, also by AdGuard DNS:

```
Blocklists:
 - 1Hosts.Lite     BLOCKED
 - 1Hosts.Mini     BLOCKED
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      BLOCKED
 - CONTROLD.AT     BLOCKED
 - DevDansHosts    OK
 - EasyList        OK
 - GoodbyeAds      BLOCKED
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.TIF      OK
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - NextDNS.AT      OK
 - OISD.Big        BLOCKED
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK
```

**Comment by hagezi** [comment]
@Alex-302, what is your opinion on this?

**Comment by hagezi** [comment]
I have not found anything that would prove that tracking or ad distribution takes place via the main domain. For me a pure business domain. I don't know why it is blocked in the SE lists.

**Comment by DandelionSprout** [comment]
Swedish sites are purely Frellwit's field (except for Adblock Plus), and he's been known to block all sorts of sites due to going far to block trackers and cookies.

**Comment by Alex-302** [comment]
@hagezi 

> @Alex-302, what is your opinion on this?

I think these domains should not be blocked, as not used for ads/tracking directly.
