### ISSUE TITLE
moventus.com

### ISSUE THREAD

**Issue by sthom1595** [hagezi/dns-blocklists#2774]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

*.moventus.com

### Why should the domain(s) be unblocked?

I use this for work as a Project Portfolio Management tool.

**Comment by hagezi** [comment]
@sthom1595 Only the clarity (Microsoft tracking) domains are blocked. Where do these lead to restrictions?

```
clarity.cummins-cps.moventus.com
clarity.cummins-dbu.moventus.com
clarity.cummins-it.moventus.com
clarity.cummins-vpc.moventus.com
clarity.cummins-vpi.moventus.com
clarity.cvshealth.moventus.com
clarity.expedia.moventus.com
clarity.insulet.moventus.com
clarity.pepsicoit.moventus.com
clarity.questdiag.moventus.com
clarity.wabtec.moventus.com
```

**Comment by sthom1595** [comment]
![Screenshot 2024-05-24 at 2 12 36 AM](https://github.com/hagezi/dns-blocklists/assets/7688970/c0c7c0af-16e3-41cc-a7ec-5dd84e95b626)
clarity.expedia.moventus.com leads me to my work login page.
