### ISSUE TITLE
in.pinterest.com is currently being blocked.

### ISSUE THREAD

**Issue by shreya-jariwala** [hagezi/dns-blocklists#2785]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

in.pinterest.com

### Why should the domain(s) be unblocked?

The domain is the official domain of Pinterest in India.

**Comment by hagezi** [comment]
@jarelllama
