### ISSUE TITLE
Exophase Forums

### ISSUE THREAD

**Issue by denis-g** [hagezi/dns-blocklists#2788]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

forums.exophase.com

### Why should the domain(s) be unblocked?

Gaming community that specializes in trophy and achievement tracking.

**Comment by hagezi** [comment]
@jarelllama
