### ISSUE TITLE
Various Roblox Domains

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#2795]
### Which domain(s) should be blocked?

abtesting.roblox.com
gold.roblox.com
robloxlabs.com
c0ak.rbxcdn.com
c0aws.rbxcdn.com
c0cfly.rbxcdn.com
ecsv2.roblox.com 
metrics.roblox.com

### Why should these domain(s) be blocked?

`abtesting.roblox.com` - As the name suggests, used for A/B testing. Info [here](https://github.com/NoTwistedHere/Roblox-Apis/blob/main/Documentations/abtesting.roblox.com.md). Looks like it's a CNAME to `gold.roblox.com`.
`gold.roblox.com` - Explained above.
`robloxlabs.com` - Same as above, looks to be related to more A/B testing. More info [here](https://github.com/NoTwistedHere/Roblox-Apis/blob/main/Other/robloxlabs.com.md).
`c0ak.rbxcdn.com` - Used for analytics/telemetry. Confirmed through taking a look at [Roblox's FFlag list](https://clientsettings.roblox.com/v2/settings/application/PCDesktopClient), can be seen under `DFStringAnalyticsNS1BeaconConfig`.
`c0aws.rbxcdn.com` - Same as above.
`c0cfly.rbxcdn.com` - Same as above.
`ecsv2.roblox.com` - Used for analytics/telemetry, can be confirmed through looking at the [FFlag list](https://clientsettings.roblox.com/v2/settings/application/PCDesktopClient), can be seen various times. (i.e. under `DFStringRobloxAnalyticsURL` & `DFStringTelemetryV2Url`), also blocked by various other blocklists. It looks like this domain was blocked here at one point (Issue #1643), but I can't seem to find info on when/why it was removed. It doesn't seem to be known to cause any breakage.
`metrics.roblox.com` - Same as above, clearly used for analytics/telemetry, but looks like was also blocked at one point in time from the same issue. Not sure when or why it was removed. Info [here](https://github.com/NoTwistedHere/Roblox-Apis/blob/main/Documentations/metrics.roblox.com.md).

**Comment by hagezi** [comment]
@Retold3202 
```
ecsv2.roblox.com
metrics.roblox.com
```
These domains are supposedly required for the avatar editor and are therefore not on the lists. Do you have the possibility to test this? Thank you ...

**Comment by hagezi** [comment]
Thanks @Retold3202
