### ISSUE TITLE
Roblox domains

### ISSUE THREAD

**Issue by pimeja7** [hagezi/dns-blocklists#2797]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

abtesting.roblox.com
gold.roblox.com
robloxlabs.com
c0ak.rbxcdn.com
c0aws.rbxcdn.com
c0cfly.rbxcdn.com
ecsv2.roblox.com
metrics.roblox.com

im not sure which one is causing the problem but these domains were added to the block list recently

### Why should the domain(s) be unblocked?

i started having problems with animations, sounds, and avatars not loading in game
i opened the logs and it said it had to do with the DNS so i tried without it and it loaded normally
could u maybe look into it?
![RobloxPlayerBeta_imEKguWZlb](https://github.com/hagezi/dns-blocklists/assets/158540717/fc7f6e0b-9912-4ce2-8b21-427ae8d0a49a)

**Comment by pimeja7** [comment]
im using the free tier so i cant whitelist stuff

**Comment by hagezi** [comment]
@pimeja7 For testing: `https://dns.controld.com/1n9146pdqsl`
Pro++, allowed `c0ak.rbxcdn.com`

**Comment by pimeja7** [comment]
i tried it and it fixed it, thanks

**Comment by hagezi** [comment]
@pimeja7 will now deactivate the test account.
