### ISSUE TITLE
False Positive: domaintechnik.at

### ISSUE THREAD

**Issue by AlexHuebi** [hagezi/dns-blocklists#28]
In der Liste "Fake DNS Blocklist" steht "domaintechnik.at".

https://www.trustedshops.at/shops/?q=domaintechnik.at

Auch in der Quelle kann die Domain nicht gefunden werden: 
https://www.watchlist-internet.at/search/?id=153&tx_kesearch_pi1%5Bsword%5D=domaintechnik.at&tx_kesearch_pi1%5Bpage%5D=1&tx_kesearch_pi1%5BresetFilters%5D=0&tx_kesearch_pi1%5BsortByField%5D=&tx_kesearch_pi1%5BsortByDir%5D=

**Comment by hagezi** [comment]
Danke für den Hinweis, Doman wurde entfernt. Gruß, Gerd
