### ISSUE TITLE
[False Positive] Proofpoint Partner Program website

### ISSUE THREAD

**Issue by sam1310** [hagezi/dns-blocklists#280]
For the Proofpoint Partner Program [website](https://partners.proofpoint.com) to correctly load the menu bar, and allow login, I had to allowlist the URL `prod.impartner.live`

**Menu bar broken**

![image](https://user-images.githubusercontent.com/13442895/215633426-1a0a3bf1-b0cc-4436-84a1-9dc271a427a8.png)

**Menu bar working (post allowlisting)**

![image](https://user-images.githubusercontent.com/13442895/215633564-07396ba0-4edc-42a6-b6dd-4f1f42d325fb.png)

**Comment by hagezi** [comment]
Thanks, blocked by CNAME rv.treehousei.com

ping @badmojr

**Comment by hagezi** [comment]
Removed.
