### ISSUE TITLE
ephemeralcounters.api.roblox.com

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#2800]
### Which domain(s) should be blocked?

ephemeralcounters.api.roblox.com

### Why should these domain(s) be blocked?

This domain is used for telemetry in Roblox, it's another variant of `ecsv2.roblox.com`. I didn't include it in #2795, as it seemed to cause breakage in #891, but I've gone ahead and tested it (In-game, from Microsoft Store/Windows just like the person who encountered the issue), and it doesn't seem to cause this breakage anymore. Looks safe to block.

**Comment by Dynamic5912** [comment]
This domain stops Roblox from loading/opening and checking for updates when installed via the Microsoft Store. 

I've had to whitelist it to get Roblox to open and function. 

Can this be removed from the blocklist/s?

**Comment by Dynamic5912** [comment]
> > This domain stops Roblox from loading/opening and checking for updates when installed via the Microsoft Store.
> 
> > 
> 
> > I've had to whitelist it to get Roblox to open and function.
> 
> > 
> 
> > Can this be removed from the blocklist/s?
> 
> 
> 
> Apologies, this did not occur in my testing, sounds like it may be localized. I'm sorry for the trouble, we will need to remove for sure then.

All good - my daughter was in a bit of a mood with me yesterday saying it was all my fault it wasn't working. 

I told her to blame the internet... :)
