### ISSUE TITLE
Badware Hoster: unblock accounts.blogger.com

### ISSUE THREAD

**Issue by timkgh** [hagezi/dns-blocklists#2808]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster

### Which domain(s) should be unblocked?

accounts.blogger.com

### Why should the domain(s) be unblocked?

Google login re-verification when making account changes does some redirects to accounts.blogger.com (SSO-like) that fail resulting in re-verification to fail completely.

**Comment by timkgh** [comment]
Also `blogger.l.google.com` needs to be unblocked which is a CNAME for accounts.blogger.com

**Comment by hagezi** [comment]
blogger.com hosts a lot of badware sites and is therefore on the list.

**Comment by timkgh** [comment]
Breaking the Google account login flow is bad. What choice do people who use Google have? To allow list it.

**Comment by timkgh** [comment]
FWIW, in general these lists should allow the sites themselves to manage accounts, see what the sites are about (if they don't host badware themselves) and only block SUBDOMAINS that MAY host badware.

Applicable to DynDNS sites that I reported here:
https://github.com/hagezi/dns-blocklists/issues/2558

e.g. there is no harm in allowing just:
```
@@|www.duckdns.org^
@@|duckdns.org^
```
it will still block all subdomains.
