### ISSUE TITLE
Roblox Domains

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2812]
I'm trying to understand the logic that's been applied recently to the recent Roblox domain blocking. 

For example, **c0aws.rbxcdn.com** is blocked, which also has CNAME address **c0ns1.rbxcdn.com** and which are both part of DNS name **c0.rbxcdn.com**

![image](https://github.com/hagezi/dns-blocklists/assets/134324737/f05ade80-b7a7-4540-80fe-93f6114e8bab)

However there is also **c1/2/3/4/5/6/7.rbxcdn.com** which are not blocked, and also **t0/1/2/3/4/5/6/7.rbxcdn.com** which is not blocked and also has similar DNS and CNAME's (**aws** and the like).

Also **ephemeralcounters.api.roblox.com** prevents the app from opening now - I've already made a separate issue about this and commented on the original post where it was requested to be blocked.

**Comment by hagezi** [comment]
I can't contribute anything at the moment, I'm relying on @Retold3202 who has investigated this. These domains are therefore currently only blocked in the aggressive list.

**Comment by hagezi** [comment]
Thanks @Retold3202, will be fixed on next release.

**Comment by Dynamic5912** [comment]
So what has been decided to be whitelisted and blocked here going forwards?

**Comment by hagezi** [comment]
@Dynamic5912 : https://github.com/hagezi/dns-blocklists/commit/890f3389ba5977abd91f03a77eec0841ed61816d
