### ISSUE TITLE
Domains needed for Microsoft Quick Assist

### ISSUE THREAD

**Issue by lynxthecat** [hagezi/dns-blocklists#2815]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

adblock-lean

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO, Native Tracker

### Which domain(s) should be unblocked?

I believe one or more of the following domains might be needed for Quick Assist to function properly:

events.data.microsoft.com
s.go-mpulse.net
js.monitor.azure.com

### Why should the domain(s) be unblocked?

The blocking of these domains prevents Microsoft's "Quick Assist" utility (used for remote desktop viewing/assistance):

![image](https://github.com/hagezi/dns-blocklists/assets/10721999/1de81286-ef90-4b50-83e2-bb4230d7d77a)

 from functioning. I think this is particularly significant because it is used by Microsoft Support to help Windows and Office 365 users with any problems they are facing.

However, if there are other good reasons for blocking these domains then I would understand and adblock-lean users can always just whitelist these domains instead.

**Comment by hagezi** [comment]
`js.monitor.azure.com` and `events.data.microsoft.com` only blocked in aggressive lists (pro++ and ultimate) and native tracker list. If you use an aggressive list or the native tracker list, you must unblock it in your personal allowlist.

I will unblock `s.go-mpulse.net` for the non-aggressive lists (light, normal and pro). The domain will remain blocked in the aggressive lists.

**Comment by lynxthecat** [comment]
Thanks. I'm also just testing further to ensure all three need to be unblocked for Quick Assist to work.

**Comment by hagezi** [comment]
@lynxthecat I think only `js.monitor.azure.com` is needed. Try it with just the Pro and it should work. If unblocking s.go-mpulse.net is not necessary, let me know.

**Comment by lynxthecat** [comment]
Did you just update the Pro list already? Because now with:

```
# One or more dnsmasq blocklist urls separated by spaces
blocklist_urls="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/pro.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.winoffice.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.apple.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.amazon.txt"
```

it is working. But I could be facing a DNS caching issue? I tried "ipconfig /flushdns", but am struggling to see the issue manifest altogether now!

**Comment by lynxthecat** [comment]
Ah crap. Any thoughts on how I can avoid any kind of DNS caching? Maybe reboot?

**Comment by hagezi** [comment]
`ipconfig /flushdns` should be enough.

**Comment by hagezi** [comment]
@lynxthecat I have tested this under Windows 11 with Ultimate, only `js.monitor.azure.com` must be allowed. In other words, either you use the Pro without the native tracker list or you add `js.monitor.azure.com` to the allowlist.

**Comment by lynxthecat** [comment]
Ah were you able to reproduce the issue too? I just can't reproduce now even with Pro and native tracker list. Presumably there is some kind of caching issue going on here.

**Comment by hagezi** [comment]
Yes, I was able to reproduce this.

**Comment by lynxthecat** [comment]
Ah yes, I just got it too. I'll now add only "js.monitor.azure.com" to verify it is working again.

**Comment by lynxthecat** [comment]
By the way is js.monitor.azure.com used for other undesirable stuff?

**Comment by lynxthecat** [comment]
**Confirmed** - js.monitor.azure.com is the culprit. Having added **only** js.monitor.azure.com to allowlist "Quick Assist" starting working again.

**Comment by hagezi** [comment]
Yes, it is also used for tracking.

**Comment by lynxthecat** [comment]
Would it be worth just adding a note for the README on the native tracker list?

**Comment by Levander0** [comment]
Can confirm only js.monitor.azure.com is needed
