### ISSUE TITLE
Beacons.ai being blocked?

### ISSUE THREAD

**Issue by FeeninForMore** [hagezi/dns-blocklists#2820]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

Beacons.ai

### Why should the domain(s) be unblocked?

As far as I know isn't it just a website where creators can add links to their social media accounts?

**Comment by hagezi** [comment]
ping @iam-py-test

Flagged as crypto scam.

**Comment by hagezi** [comment]
I have not found anything malicious, will be removed.

**Comment by iam-py-test** [comment]
Fixed in my list as well.
