### ISSUE TITLE
Blocklist cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [hagezi/dns-blocklists#2839]
[i] Target: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/ips/tif.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 182469 exact domains and 0 ABP-style domains (ignored 7294 non-domain entries)
      Sample of non-domain entries:
        - "100.166.114.2"
        - "100.20.96.2"
        - "100.25.156.1"
        - "100.4.185.8"
        - "100.6.8.7"

 [i] Target: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/ips/doh.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 1841 exact domains and 0 ABP-style domains (ignored 200 non-domain entries)
      Sample of non-domain entries:
        - "1.0.0.1"
        - "1.0.0.2"
        - "1.0.0.3"
        - "101.6.6.6"
        - "102.113.175.2"

**Comment by hagezi** [comment]
This is an IP and not a domain list, you cannot use it in Pi-hole.
