### ISSUE TITLE
Can't sign in on playstation.com

### ISSUE THREAD

**Issue by FeeninForMore** [hagezi/dns-blocklists#2849]
I'm using TIF and pro blocklist on adguard DNS and I can't sign in for some reason, I disabled the DNS and it works

**Comment by FeeninForMore** [comment]
I found the domain what was causing it "r.3gl.net" once I unblocked this domain everything started working correctly.

**Comment by FeeninForMore** [comment]
"sonynetworkentertain.tt.omtrdc.net" also messes up signing in aswell

**Comment by hagezi** [comment]
@FeeninForMore I cannot reproduce the problem, I can log in normally. Tested with Ultimate.

Are you using NextDNS or ControlD and have you activated the block page?

Could someone else test again?

**Comment by FeeninForMore** [comment]
I'm using adguard DNS, and I have all the settings default

**Comment by hagezi** [comment]
@FeeninForMore Yes, sorry, I'm not quite awake yet and had overlooked that.

You mean the login on playstation.com in the browser?

**Comment by FeeninForMore** [comment]
I apologise, it now seems to be working. I don't know what happened before i turned off my DNS and it started working again

**Comment by FeeninForMore** [comment]
Sorry for wasting your time

**Comment by hagezi** [comment]
@FeeninForMore No problem, the internet must have had a hiccup.
