### ISSUE TITLE
fundingchoices.google.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#2853]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

fundingchoices.google.com

### Why should the domain(s) be unblocked?

I got weird youtube notification blocker even though it wasn't using adblock at the time
![youtube-starting-warns-for-adblocker-user-in-indonesian-v0-bwiz3txsvyrb1](https://github.com/hagezi/dns-blocklists/assets/69599160/96266cf3-ca2c-474f-a154-12230d98b224)

**Comment by hagezi** [comment]
@MagicalAlchemist Are you sure it's because of fundingchoices.google.com? I can't reproduce this.

**Comment by MagicalAlchemist** [comment]
Positive. 

This domain rarely called.
![Screenshot 2024-06-07 021059](https://github.com/hagezi/dns-blocklists/assets/69599160/4dc357f7-e35c-492d-a8bb-08371308597b)


I forgot to screenshot when I click "Allow youtube ads" then fundingchoices.google.com get notif "This site can't be reached"
