### ISSUE TITLE
joathath.com: Malware

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2854]
### Which domain(s) should be blocked?

https://joathath.com/4/7184818
https://joathath.com/
https://v5.mp3y.info/en (this is the website that shows the fake buttons that link to the malicious website after you enter a YouTube link)
https://v5.mp3y.info/en?q=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ (example with fake buttons)

### Why should these domain(s) be blocked?

They are malware/phishing and the links are distributed via fake download buttons like this one, where I found them:

<img width="584" alt="image" src="https://github.com/hagezi/dns-blocklists/assets/123986260/9a0c872c-190c-4eb5-84e2-5fdf09c818f4">

I suggest it would be beneficial to block them not only on TIF but also through DNS filters, so that NextDNS users can be protected as well.

**Comment by iam-py-test** [comment]
Added `mp3y.info` to my list.
Thanks

**Comment by iam-py-test** [comment]
Also, FYI, I am unaffiliated with @hagezi, though they do use my list as a source for TIF
