### ISSUE TITLE
Various Apple Domains

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#2855]
### Which domain(s) should be blocked?

applemediaservices.com
marketing.services.apple
autolinkmaker.itunes.apple.com
linkmaker.itunes.apple.com.edgekey.net
cstat.apple.com
cstat.apple.com.edgesuite.net
cstat.cdn-apple.com
cstat.g.aaplimg.com
odin-signals.apple.com
datacollection.apple.com
msc-dct-prod.msc.apple.com
databeacon.apple.com
experiments.apple.com
experiments.apple.com.edgekey.net
ab.apple.com.akadns.net
iad-apple.com.akadns.net
iadcontent-lb.apple.com.akadns.net
iadsdk.apple.com.akadns.net
iadsdk.apple.com.edgekey.net
iadmoo.apple.com
launch.apple.com
prd-usw2-requestattribution-iad.apple.com
searchads.lb-apple.com.akadns.net
searchads.apple.com.edgesuite.net
feedbackws.fe2.apple-dns.net
idiagnostics.apple.com
idiagnostics.apple.com.akadns.net
idiagnostics-mdn1.apple.com
diagnostics.apple.com
diagnostics.apple.com.akadns.net
diagassets.apple.com
diagassets.g.aaplimg.com
diagassets-lb.apple.com.akadns.net
iphonesubmissions.apple.com
iphonesubmissions.apple.com.akadns.net
iphonesubmissions.v.aaplimg.com
iphonesubmissions-old.apple.com
internalcheck.apple.com
me.apple-dns.net
prod-event-relay-books-api.v.aaplimg.com
prod-event-relay-notes-api.v.aaplimg.com
prod-event-relay-stocks-api.v.aaplimg.com
prod-event-relay-weather-api.v.aaplimg.com
radarsubmissions.apple.com
radarsubmissions.apple.com.akadns.net
securemetrics.v.aaplimg.com
securemvt.v.aaplimg.com
supportmetrics.v.aaplimg.com
smoot-feedback.v.aaplimg.com
xp.apple.com.edgekey.net
xp.itunes-apple.com.akadns.net
xp-cdn.apple.com
cdn-xp-ingest.edge.apple
cdn-xp-ingest-ab.v.aaplimg.com

### Why should these domain(s) be blocked?

`applemediaservices.com` - Provides marketing tools & services, see [here](https://tools.applemediaservices.com/).

`marketing.services.apple` - Same as above.

`performance-partners.apple.com` - Same as above.

`autolinkmaker.itunes.apple.com` - Same as above, related to Apple Media Services.

`linkmaker.itunes.apple.com.edgekey.net` - Same as above.

`cstat.apple.com` - This is extremely difficult to find info on, but my best guess based off my research and analysis is that this is used for metrics and crash reporting. Other lists have this blocked, I've had it blocked for a while now and haven't had any issues. 

`cstat.apple.com.edgesuite.net` - Same as above.

`cstat.cdn-apple.com` - Same as above.

`cstat.g.aaplimg.com` - Same as above.

`odin-signals.apple.com` - Same as above, appears to be related to `cstat.apple.com` & `cstat.cdn-apple.com`.

`idv-signals-pommery-prod.v.aaplimg.com` - Same as above.

`datacollection.apple.com` - This is an interesting domain I came across while researching, it appears to be used for telemetry and analytics (as the name suggests), as navigating to the domain asks for a log-in to "Product Ops-Data Collection". 

`msc-dct-prod.msc.apple.com` - Same as above.

`databeacon.apple.com` - This is another interesting one, seems very hard to find info on, but it appears to be active, my best guess is it's related to above.

`experiments.apple.com` - Noticed Apple devices on my network connecting to this, my first instinct was to guess this was used for A/B testing & telemetry of some kind, which I imagine is correct, as it appears to be directing traffic through `ab.apple.com.akadns.net` (which should be blocked as well). I did more research, and it looks like I was correct, as from [this](https://apple.stackexchange.com/questions/422847/amsengagmentd-is-causing-a-jetsamevent-due-to-per-process-limit) Stack Exchange comment, it looks like it's tied to a process Apple uses for telemetry/data collection. I've had these domains blocked for a couple weeks now and haven't noticed any issues.

`experiments.apple.com.edgekey.net` - Same as above.

`iad-apple.com.akadns.net` - Domain used for advertising from Apple's iAd Network, related to `iadsdk.apple.com`, which we already block, so makes sense to block this too.

`iadcontent-lb.apple.com.akadns.net` - Same as above, also iAd related, we already block `iadcontent.apple.com`, so makes sense to block this too.

`iadsdk.apple.com.akadns.net` Same as above, another iAd domain.

`iadsdk.apple.com.edgekey.net` - Same as above.

`iadmoo.apple.com` - Same as above, another iAd domain, appears to be active.

`launch.apple.com` - Another iAd domain, appears to be direct traffic to other iAd domains, seems to be active.

`prd-usw2-requestattribution-iad.apple.com` - Same as above, another iAd domain.

`searchads.lb-apple.com.akadns.net` - Another advertising domains, seems to be used for search ads in ex. App Store. We're blocking `searchads.apple.com`, so makes sense to cover this too.

`searchads.apple.com.edgesuite.net` - Same as above.

`feedbackws.fe2.apple-dns.net` - Seems to be used for iCloud telemetry, related to `acfeedbackws.icloud.com`, which we do block.

`idiagnostics.apple.com` - This is another domain that appears to be used for analytics & sending diagnostic data, I noticed my Apple TV making connections to it, so I've been blocking it, and haven't had any issues. More interesting info on Page 10 of [here](https://www.scss.tcd.ie/doug.leith/pubs/apple_google2.pdf) on it.

`idiagnostics.apple.com.akadns.net` - Same as above.

`idiagnostics-mdn1.apple.com` - Same as above, another domain used for these diagnostics.

`diagnostics.apple.com` - Appears to be related to domains above, more diagnostics.

`diagnostics.apple.com.akadns.net` - Same as above.

`diagassets.apple.com` - Another domain used by Apple for diagnostics, ["Used by Apple devices to help detect possible hardware issues"](https://support.apple.com/101555).

`diagassets.g.aaplimg.com` - Same as above.

`diagassets-lb.apple.com.akadns.net` - Same as above.

`iphonesubmissions.apple.com` - Appears to be used for telemetry & crash reporting, source [here](https://www.flickr.com/photos/factoryjoe/1973755571) & [here](https://discussions.apple.com/thread/2471894?sortBy=best)

`iphonesubmissions.apple.com.akadns.net` - Same as above.

`iphonesubmissions.v.aaplimg.com` - Same as above.

`iphonesubmissions-old.apple.com` - Same as above.

`internalcheck.apple.com` - Another domain I noticed some Apple devices in my network connecting to that I thought was interesting. Was difficult to find info on, but after some research, and a [~10 year old forum thread](https://web.archive.org/web/20141112150601/http://hintsforums.macworld.com/showthread.php?t=139495), it [appears](https://web.archive.org/web/20141113123711/http://www.flickr.com/photos/factoryjoe/1879014188) to be used for crash reporting & metrics. I haven't had any issues with it blocked.

`me.apple-dns.net` - Appears to be used for iCloud telemetry, related to `metrics.icloud.com`.

`prod-event-relay-books-api.v.aaplimg.com` - Analytics from Apple Books, related to `books-analytics-events.apple.com`, we block that so makes sense to cover this too.

`prod-event-relay-notes-api.v.aaplimg.com` - Analytics from Apple Notes, related to `notes-analytics-events.apple.com`, we block that so makes sense to cover this too.

`prod-event-relay-stocks-api.v.aaplimg.com` - Analytics from Apple Stocks, related to `stocks-analytics-events.apple.com`, we block that so makes sense to cover this too.

`prod-event-relay-weather-api.v.aaplimg.com` - Analytics from Apple Weather, related to `weather-analytics-events.apple.com`, we block that so makes sense to cover this too.

`radarsubmissions.apple.com` - Appears to be used for general telemetry, sending diagnostic and usage data. Sources [here](https://apple.stackexchange.com/questions/66119/disable-submitdiaginfo) & [here](https://discussions.apple.com/thread/2141147?sortBy=best).

`radarsubmissions.apple.com.akadns.net` - Same as above.

`securemetrics.v.aaplimg.com` - Appears to be used for metrics on some of Apple's websites & services. Similar to `securemetrics.apple.com`, we already block that domain, so makes sense to block this too.

`securemvt.v.aaplimg.com` - Same as above, related to `securemvt.apple.com`.

`supportmetrics.v.aaplimg.com` - Same as above, related to `supportmetrics.apple.com`.

`xp.apple.com.edgekey.net` - Related to the infamous `xp.apple.com`, makes sense to block on more aggressive lists alongside it.

`xp.itunes-apple.com.akadns.net` - Same as above.

`xp-cdn.apple.com` - Now this is interesting. It seems related to `xp.apple.com`, except Apple officially admits it's used for "reporting" [here](https://support.apple.com/101555). It also doesn't have any relation to updates like `xp.apple.com` does that I can see, so I think this will be safe to block regardless of list, unlike `xp.apple.com` which we have to be more careful with.

`cdn-xp-ingest.edge.apple` - Same as above, related to `xp-cdn.apple.com`.

`cdn-xp-ingest-ab.v.aaplimg.com` - Same as above, related to `xp-cdn.apple.com`.

**Comment by hagezi** [comment]
You have to be careful when blocking CNAMES such as me.apple-dns.net. As they have multiple uses for different functions.

I'll have a look when I have more time.

**Comment by hagezi** [comment]
I know that blocking `me.apple-dns.net` caused problems with the iCloud Gateway. This no longer seems to be the case.

As I said, it only makes sense to block the CNAMES if they are also called or can be assigned to several blockable domains. Who knows what Apple will do with the API on `me.apple-dns.net` in the next iOS update.

Blocking `me.apple-dns.net` currently makes no sense to me, `metrics.icloud.com` is blocked.

**Comment by thomasmerz** [comment]
If this is helpful(?) - I checked the list above with my setup and my different blocklists in use, so you can see if others and for what reason/category block some of these domains:
```
  [i] No results found for applemediaservices.com within the adlists
  [i] No results found for marketing.services.apple within the adlists
  [i] No results found for autolinkmaker.itunes.apple.com within the adlists
  [i] No results found for linkmaker.itunes.apple.com.edgekey.net within the adlists
 Match found in https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt:
   cstat.apple.com
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   cstat.apple.com
   cstat.apple.com.edgesuite.net
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   cstat.apple.com.edgesuite.net
 Match found in https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt:
   cstat.cdn-apple.com
  [i] No results found for cstat.g.aaplimg.com within the adlists
  [i] No results found for odin-signals.apple.com within the adlists
  [i] No results found for datacollection.apple.com within the adlists
  [i] No results found for msc-dct-prod.msc.apple.com within the adlists
  [i] No results found for databeacon.apple.com within the adlists
  [i] No results found for experiments.apple.com within the adlists
  [i] No results found for experiments.apple.com.edgekey.net within the adlists
  [i] No results found for ab.apple.com.akadns.net within the adlists
 Match found in https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt:
   iad-apple.com.akadns.net
   failover-journey-pcms.iad-apple.com.akadns.net
   hk-journey-pcms.iad-apple.com.akadns.net
   iadsdk.iad-apple.com.akadns.net
   journey-pcms.iad-apple.com.akadns.net
   lnarswc5ox6hzr.iad-apple.com.akadns.net
   lnarswc5ox6hzr-east.iad-apple.com.akadns.net
   lnarswc5ox6hzr-europe.iad-apple.com.akadns.net
   lnarswc5ox6hzr-west.iad-apple.com.akadns.net
   news.iad-apple.com.akadns.net
   searchads.iad-apple.com.akadns.net
   sk-journey-pcms.iad-apple.com.akadns.net
   skadnetwork.iad-apple.com.akadns.net
   tr.iad-apple.com.akadns.net
   vast-asia.iad-apple.com.akadns.net
   vast-australia.iad-apple.com.akadns.net
   vast-east.iad-apple.com.akadns.net
   vast-europe.iad-apple.com.akadns.net
   vast-west.iad-apple.com.akadns.net
   webproxy-advp.iad-apple.com.akadns.net
  [i] No results found for iadcontent-lb.apple.com.akadns.net within the adlists
 Match found in https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt:
   iadsdk.apple.com.akadns.net
 Match found in https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt:
   iadsdk.apple.com.edgekey.net
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   iadsdk.apple.com.edgekey.net
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   ||iadmoo.apple.com^
  [i] No results found for launch.apple.com within the adlists
  [i] No results found for prd-usw2-requestattribution-iad.apple.com within the adlists
  [i] No results found for searchads.lb-apple.com.akadns.net within the adlists
  [i] No results found for searchads.apple.com.edgesuite.net within the adlists
  [i] No results found for feedbackws.fe2.apple-dns.net within the adlists
 Match found in https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/MobileAppAds/appadsblocklist.txt:
   idiagnostics.apple.com
   idiagnostics.apple.com.akadns.net
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   ||idiagnostics.apple.com.akadns.net^
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   idiagnostics.apple.com.akadns.net
   idiagnostics.apple.com
 Match found in https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/MobileAppAds/appadsblocklist.txt:
   idiagnostics.apple.com.akadns.net
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   ||idiagnostics.apple.com.akadns.net^
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   idiagnostics.apple.com.akadns.net
  [i] No results found for idiagnostics-mdn1.apple.com within the adlists
 Match found in https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/MobileAppAds/appadsblocklist.txt:
   idiagnostics.apple.com
   idiagnostics.apple.com.akadns.net
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   ||idiagnostics.apple.com.akadns.net^
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   idiagnostics.apple.com.akadns.net
   idiagnostics.apple.com
 Match found in https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/MobileAppAds/appadsblocklist.txt:
   idiagnostics.apple.com.akadns.net
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   ||idiagnostics.apple.com.akadns.net^
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   idiagnostics.apple.com.akadns.net
  [i] No results found for diagassets.apple.com within the adlists
  [i] No results found for diagassets.g.aaplimg.com within the adlists
  [i] No results found for diagassets-lb.apple.com.akadns.net within the adlists
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   iphonesubmissions.apple.com.akadns.net
   iphonesubmissions.apple.com
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   iphonesubmissions.apple.com.akadns.net
  [i] No results found for iphonesubmissions.v.aaplimg.com within the adlists
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   iphonesubmissions-old.apple.com
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   internalcheck.apple.com
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   me.apple-dns.net
  [i] No results found for prod-event-relay-books-api.v.aaplimg.com within the adlists
  [i] No results found for prod-event-relay-notes-api.v.aaplimg.com within the adlists
  [i] No results found for prod-event-relay-stocks-api.v.aaplimg.com within the adlists
  [i] No results found for prod-event-relay-weather-api.v.aaplimg.com within the adlists
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   radarsubmissions.apple.com.akadns.net
   radarsubmissions.apple.com
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   radarsubmissions.apple.com.akadns.net
  [i] No results found for securemetrics.v.aaplimg.com within the adlists
  [i] No results found for securemvt.v.aaplimg.com within the adlists
  [i] No results found for supportmetrics.v.aaplimg.com within the adlists
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   smoot-feedback.v.aaplimg.com
  [i] No results found for xp.apple.com.edgekey.net within the adlists
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   xp.itunes-apple.com.akadns.net
   daf.xp.itunes-apple.com.akadns.net
  [i] No results found for xp-cdn.apple.com within the adlists
  [i] No results found for cdn-xp-ingest.edge.apple within the adlists
  [i] No results found for cdn-xp-ingest-ab.v.aaplimg.com within the adlists
```

**Comment by hagezi** [comment]
As I don't have time at the moment to look at this in detail and add it to the native tracker list if necessary, I'm only blocking the domains in Ultimate for testing in the next release.

**Comment by celenityy** [comment]
@hagezi We should consider unblocking `autolinkmaker.itunes.apple.com` & `linkmaker.itunes.apple.com.edgekey.net`.

I haven't seen either of these called on their own, rather they appear to act as referral domains.

I noticed this with Brave. Attempting to download the iOS app from their website (`https://brave.com/ios`) redirects to `https://geo.itunes.apple.com/app/brave-web-browser/id1052879175`, which is blocked, as it is a CNAME of `linkmaker.itunes.apple.com.edgekey.net`.

I'd also propose adding `autolinkmaker.itunes.apple.com`, `geo.itunes.apple.com`, & `linkmaker.itunes.apple.com.edgekey.net` to the referral allowlist.

**Comment by hagezi** [comment]
Thanks @celenityy, will be removed and added to the referral allowlist.
