### ISSUE TITLE
Attack on GitHub users

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#2858]
### Which domain(s) should be blocked?

githubtalentcommunity.online
githubcareers.online

### Why should these domain(s) be blocked?

[GitHub Community 1](https://github.com/orgs/community/discussions/109644)
[GitHub Community 2](https://github.com/orgs/community/discussions/109171)
[Bleeping Computer](https://www.bleepingcomputer.com/news/security/new-gitloker-attacks-wipe-github-repos-in-extortion-scheme/)
[X.com](https://x.com/1ZRR4H/status/1798412587484496068)
[VirusTotal 1](https://www.virustotal.com/gui/domain/auth.githubtalentcommunity.online/detection)
[VirusTotal 2](https://www.virustotal.com/gui/domain/githubcareers.online)

**Comment by hagezi** [comment]
Dead and Parked
