### ISSUE TITLE
Web Advertising Scam

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#286]
#### Which domain(s) should be blocked?

https://check-update-today.me
https://fraeuleinemma.fun/?u
https://path2zillion.com
https://new.bestageoffers22.com

#### Why should the domain(s) be blocked?

Web Advertising Scam and Spam

**Comment by hagezi** [comment]
Thanks, added.

ping @durablenapkin

**Comment by durablenapkin** [comment]
Thank you! Domains will be added in next nightly update.
