### ISSUE TITLE
Not blocking ads on Chinese sites

### ISSUE THREAD

**Issue by OshekharO** [hagezi/dns-blocklists#2864]
Ads and tracking are not being blocked on Chinese sites

Example: https://m.xs777.org/shu/269380/231867072.html

**Comment by xRuffKez** [comment]
```udkc7.com```

**Comment by xRuffKez** [comment]
I need more Infos, which Domains are Tracker and Ads? @OshekharO

**Comment by OshekharO** [comment]
> I need more Infos, which Domains are Tracker and Ads? @OshekharO

Wait let me check 

Also ads are being displayed on this site 

https://m.shuhaige.net/103397/63593794.html

Almost all Chinese sites ads are not being blocked

**Comment by hagezi** [comment]
@OshekharO I don't see any ads with Ultimate, which list are you using?

**Comment by OshekharO** [comment]
ta20k.xyz
anbkzt.xyz

Also I think this list includes almost all

https://cdn.jsdelivr.net/gh/geekdada/surge-list/domain-set/chinese-filter.txt

**Comment by hagezi** [comment]
Except mjxvnl.xyz all domans are already blocked in all list versions. There seems to be a problem on your side.

**Comment by OshekharO** [comment]
> Except `mjxvnl.xyz` all domans are already blocked in all list versions. There seems to be a problem on your side.

Hmm

**Comment by OshekharO** [comment]
Yes it's working but some are still being bypassed such as 

yt-twrp161.xyz

Will update more

**Comment by hagezi** [comment]
Seems to be partly NRDs (Newly Registered Domains), I will add the list you recommended and the missing domains you post here.

**Comment by OshekharO** [comment]
udkc7.com

**Comment by hagezi** [comment]
Everything will be added with the next release.

**Comment by hagezi** [comment]
Sources and missing domains have been added in https://github.com/hagezi/dns-blocklists/commit/084c37a7cd96b457b7f527f0356ba91ad41a74f3
