### ISSUE TITLE
diagnostic.networking.aws.dev

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#2867]
### Which domain(s) should be blocked?

diagnostic.networking.aws.dev

### Why should these domain(s) be blocked?

I noticed Amazon devices on my network constantly phoning home to this domain (`web.diagnostic.networking.aws.dev`, which also CNAMEs to `ec2.web.eu-central-1.prod.diagnostic.networking.aws.dev`). I tried to research it but couldn't find much info, but this seems to be related to sending diagnostic data & telemetry. I've had it blocked for a few weeks now and haven't had any issues.

**Comment by hagezi** [comment]
Yes, I blocked it a long time ago, but I couldn't find any details about it. I think there were some ‘no internet connection’ problems with Amazon Eero. But I'm not sure anymore. Block it in the aggressive lists.

**Comment by xRuffKez** [comment]
Please DO NOT block this domain. It is checking for network connectivity on Alexa devices. Blocking this will make Alexa devices cease working.

**Comment by hagezi** [comment]
@xRuffKez I haven't had any problems with connectivity so far. I've had them in my personal denylist for ages. acsechocaptiveportal.com and fireoscaptiveportal.com are used to check internet connectivity.

**Comment by xRuffKez** [comment]
> I also have an Alexa in my household and can confirm it still works without issue with this blocked. @xRuffKez Are you sure there's nothing else at play here?

Keep on hold. I had issues, with that domain. Maybe i remember false but if i find it, i will open an new issue. So keep blocked for now.

**Comment by hagezi** [comment]
There are problems with some FiretTVs. Domain will be removed again.

**Comment by xRuffKez** [comment]
Someone is having a FireTV Stick and can double check if the domain causes issues?
Also test network connection on FireTV please.

**Comment by hagezi** [comment]
@xRuffKez I can confirm that the network test with the blocked domain does not work.

**Comment by hagezi** [comment]
Yes ...
