### ISSUE TITLE
app.extremereach.com

### ISSUE THREAD

**Issue by nezlobnyj** [hagezi/dns-blocklists#287]
#### What adblocker/DNS cloud service are you using?

NextDNS via Adguard MacOS app

#### Which blocklists are used?

HaGeZi Ultimate

#### Which domain(s) should be unblocked?

app.extremereach.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

It's a corporate SaaS. Confusing is that extremereach.com is already whitelisted per # https://github.com/hagezi/dns-blocklists/issues/257, so technically if whitelist takes precedence app.extremereach.com rule should have no effect.

**Comment by nezlobnyj** [comment]
To add clarity - Adguard does not block this domain according to logs. Also tested with Apple Configuration Profile from NextDNS - same result (blocked).

**Comment by hagezi** [comment]
Thanks extremereach.com not *.extremereach.com was whitelisted in #257.

Blocked at the moment:

![grafik](https://user-images.githubusercontent.com/104343908/216095508-1fb741e6-ecb9-45ce-bbf3-9434ebcb10fd.png)

**Comment by hagezi** [comment]
Technical: If I whitelist extremereach.com the subdoamins are not removed.
If I whitelist app.extremereach.com, then extremereach.com and app.extremereach.com will be removed.

removed *.extremereach.com, except marketing.extremereach.com because it is a disguised CNAME tracker.
