### ISSUE TITLE
`no.run.place` domain

### ISSUE THREAD

**Issue by DarkCat09** [hagezi/dns-blocklists#2885]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Unbound

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

`no.run.place.`

### Why should the domain(s) be unblocked?

A snac2 (alternative to mastodon) instance is hosted there. Nothing ads- or tracking-related.

**Comment by hagezi** [comment]
ping @jarelllama
