### ISSUE TITLE
Sellpass.io

### ISSUE THREAD

**Issue by FeeninForMore** [hagezi/dns-blocklists#2886]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

Sellpass.io

### Why should the domain(s) be unblocked?

Is there any reason why this website is blocked, it's just a website where you can buy stuff from

**Comment by hagezi** [comment]
Flagged as malicious, false positive from my point of view, will be removed.
https://www.virustotal.com/gui/domain/sellpass.io/detection
