### ISSUE TITLE
Cannot access reolink.com and m.reolink.com

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2888]
Something in one of the Hagezi lists is blocking these sites from loading.

I'm using **Ultimate** as the primary Blocklist. 

If I go onto mobile data or disable AGH Protection the site loads with no issue.

Otherwise it either fails to load and/or displays a certificate error. 

Nothing in the Query Log stands out - the Reolink domains themselves are not blocked - it's something else that's causing it.

Any idea!?

**Comment by hagezi** [comment]
@Dynamic5912 I cannot reproduce this, the page loads normally for me.

**Comment by hagezi** [comment]
@Dynamic5912 

Perhaps it is being ‘blocked’ by your upstream DNS. Unfortunately you cannot see this directly in the log, you would have to look at the response code of the respective domain in the log:

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/50a1116f-a212-42ac-8567-71ab49431990)

**Comment by hagezi** [comment]
@Dynamic5912 The domain is also not blocked in other SecureDNS/lists:

```
Secure DNS:
 - 360Secure       OK
 - AliDNS          OK
 - CFIEC           OK
 - CleanBrowsing   OK
 - Cloudflare      OK
 - ComodoSecure    OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - DNSWatchGO      OK
 - HaGeZi.TIF      OK
 - Neustar         OK
 - NextDNS.TIF_AI  OK
 - NortonCS        OK
 - NRD.DGA.IDN     OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Umbrella        OK
 - YandexSafe      OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - CONTROLD.AT     OK
 - DevDansHosts    OK
 - EasyList        OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.TIF      OK
 - HaGeZi.ULTIMATE OK
 - hBlock          OK
 - NextDNS.AT      OK
 - OISD.Big        OK
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     OK

```

**Comment by Dynamic5912** [comment]
Seems to be working now. Strange. Maybe stale DNS.
