### ISSUE TITLE
m1.com

### ISSUE THREAD

**Issue by agireud** [hagezi/dns-blocklists#289]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?
Multi ULTIMATE - Aggressive protection

#### Which domain(s) should be unblocked?
m1.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
M1 Finance LLC, a financial services company based out of the USA, recently acquired the m1.com domain and it is used for legitimate access to their website and mobile applications.

Website: https://m1.com/
FINRA BrokerCheck: https://brokercheck.finra.org/firm/summary/281242

**Comment by hagezi** [comment]
Thanks, removed.
