### ISSUE TITLE
scam / raffle page - redirect sites

### ISSUE THREAD

**Issue by ruaq** [hagezi/dns-blocklists#290]
#### Which domain(s) should be blocked?

ironpawtiny.live
tecappcloud.com
gonedewcopy.live
suitaptcope.live

#### Why should the domain(s) be blocked?

`ironpawtiny.live`, `gonedewcopy.live`, and `tecappcloud.com` redirect if you enter the correct URL / Attributes. 
`suitaptcope.live` is a scam/raffle page, with the right URL.

The root domains are empty / *under construction*.

But `https://tecappcloud.com/away.php?url=I4WHKFughjL%2FMn4uEeImvbmcPCATDTlPk6EbswX%2FpoFkyTBbzAR7zQwAehbX5mryYPfbSLNpvk4YAvhZh3ILV3AwVBiej3knW4HUZWnPBkynaMZLPS0gQ1y411gUifr60oUgD3MiyOsByeDjg6ibyg%3D%3D` redirects to `https://next-pops.top/pop?id=pUDXrZrnZkywHW1RPUuKlQ&cid=72b705bc-6428-49bb-93d4-aa73dcb7b257&sub_id=l143904`. (`next-pops.top` is already blocked)

`https://ironpawtiny.live/?utm_campaign=INccHxHRWrew3TQsLBbfNnbGFYUZobMqxXT9Zrw5FhI1&t=main9` is redirecting to `https://212.suitaptcope.live/lrbrcits/?utm_campaign=INccHxHRWrew3TQsLBbfNnbGFYUZobMqxXT9Zrw5FhI1&t=main9&f=1&sid=t3~gzdla1lxpb0v2sksp2b3htni&fp=elN9Ss1yLITfUgD%2FvMYp%2B11am%2B235WzJEhhp23C%2B%2B%2B2uxQ%2B3%2BzDaYjNbDyIWa5SKgziJ8u6KXa0XabR1rq3oEiWxKQYaoTjFittNm5T5FPSUIC75wc%2FEVlgXLNlkNzRIN2is0xVTp0oVAIapZoS9gaY%2BhBnyKL37OMXy0GGS5VcsHD7br7jw%2FoSdJHOk3xnTA5Q13jh1yQWkZdDMD4Gi7%2F5bsBer1TO8OD3uKqJ6GOH9Dhl0DVaAalBfTRkfKZhzOKes6yg3u%2FiBGjEGZJXYUGLbPX49A00XpcYOaLAltuHKTjn5pXmsYQtqodQUHHlqr5TUNRQTg7oGOzIrSbk2CJzsjD3h7K8GcfUZrc41ubUqaKFN61pwSA%2Bh8xEuM3eTArjjxN4JFcg4%2FhFrzu4oRfIUfiwJ4%2FsI%2BPPZY3Sf72vj0c416B5hm2V0g0dmLDkNNz97pQwMwpQTRUsb7mc7TbWVuf9fl5VpE1K4%2B6y1ucCmWxpwz4fVj1xHLw3%2FzeAY2hqOkEhCS%2BBQbXPYJddtbbkeS96%2BsWAw6vxMHXTQNOXJbEyuXXndxhxgyjHB98ewmcvwkk593OnMkxHWhv0CHgqoGlBXt%2BqR9wCZo4nl7DTJ%2FuG6ldZGIzP2Mv2Cst%2FWLm%2BAd6wUXBd80smq3ZzJkpXd7fLzrOhWyoubK%2FIFRVYjCk7u8YZOqKqiFqn7QfgSouqIkNLyX8iaQHbT2MVu6Bm7kGInVFfpAHOzu6nC%2B81R1alROSiokqUVj0zP%2BEVvxUXkGExLB5MGIPTgwSdE0T6%2F71K9GGMZThG4b3FFMOteqM%2BCYH7aqIYAqrxK0bH8INoHFUorNKcpBMyqaO47LI4T%2BznJ1%2Fhq2NNCOVbsuOb2WVJ9183fkMnhAVOdSCUmUPOLQe2J6dO4RVX9JFdFDV5rfqroz%2FZpRA%2B785iNmhmmVVtqlaxk8xOe3stEBbspmBlBkmeC%2BvWioc5tPfyGcPNbcISGgii2T5Zz0oZHNwRadNiObnC6HIIamImb2MKl2%2BC5MKpvNt0iLmqJGVWvIdloW4PwYOnWIYluW4PL8OLz8IFtJP5AuWc4aZ%2Bnxmlvom7%2BhK2edxPolDLwA%2BUua%2B9xsDDWa8c%2F4KXdtR5wxjCkOlI7IuOw5LYtc4o7RVjeqLbiojzKkStBINZX6HUxlzA1IBumelmFSA9jhnxypkO%2BHJSeQ9bwXP2Ao6gHKLqlKjfZtFeNfvW5tBQJD2%2BaYE4EDpIkEDuK8k2ywI8frrReI1Vk3y2UQJj3FGJApjxq7nRSoj9YkeUo1Ih%2BsJgY3Rr%2FUwjeLZvOK4DAB8St4SIgjQn6Tea8I53nHjBjkcLLdmAhSooof9Gl3gbW51Q1TGBR%2FOCcRYdsSA2jwgLpxDrIa5%2FWNJVmWv3Q9GKuJ2P%2FzCGXQnTnzNp2VBs5oD4op4FzNiNw1n0qxSyduQcL5AV1nuXhYImmXuBcM84MwWYK7t6gNQ8vqAZ6yu7%2B4UbtJCeg2eFTjITYxXNmCwDKJdaqaHSdjVUmcyeeblpsFx4F1I%2BTfTX1rzElLXCz%2FZe3KtqksUcKOKXIMVaaR4pxV8ktSGN%2BtKmzrtnvdQGe3g6f65YHh3HI7bnKdpN0JY6Va7Zzp6aqhiAkLvT0icOEtwKkjUW5HSsoDXA8HGCS8mgw4LtMQBd9Kk%2Bkgil6ImxAPQf5Wmf%2BAWaYMdQtuo%2BIstW07wm1i1tJTuixeQen4A8kaM94K%2Fdyv3pqsCETbceesqBi6CEzovS28Gd9FXRap71VNIQ2XaePNMc3XQo8kV3pr5iJ7z3POeX81dhPa66f4QWvsF%2BF7tmpeIvawv%2BgBy7HdTLgAJqe2SEz9Iib30MzNDB8dZULp%2BBbtVL1y3SB%2F3h3My3AT%2BucymfEV7koi0VF70r1X3gmJdTVNJpZJL%2FYWKuGGkZnq%2BD2%2Bq7hXxVWY3gZ4oiKJaE%2B1%2BtryHi5SsU%3D` (`suitaptcope.live` isn’t blocked at the moment)

`https://211.gonedewcopy.live/web/?sid=t3~gzdla1lxpb0v2sksp2b3htni` redirects me to `teappcloud.com` and then to `https://trk.adtrk18.com/aff_c?offer_id=15506&aff_id=1850&url_id=14568&aff_sub=4fbe452d-17bb-4c54-ae0c-0076415e4c39&aff_sub5=cm3l143904`. (`trk.adtrk18.com` is also blocked already.)

**Comment by hagezi** [comment]
ping @durablenapkin

**Comment by hagezi** [comment]
Many thanks, added.

**Comment by durablenapkin** [comment]
Added, will be included in next nightly update, thanks!
