### ISSUE TITLE
More crypto scam domains 

### ISSUE THREAD

**Issue by xmaniq** [hagezi/dns-blocklists#291]
#### Which domain(s) should be blocked?
teslaking.io
teslas2023.com
fix-live.tech
teslalnc.net
tsladouble23.com
spacexpump23.com

#### Why should the domain(s) be blocked?
Crypto giveaway scams.

**Comment by hagezi** [comment]
ping @durablenapkin

**Comment by hagezi** [comment]
Many thanks, added.

**Comment by durablenapkin** [comment]
Added, will be included in next nightly update, thanks!
