### ISSUE TITLE
Question about blocking id.google.*

### ISSUE THREAD

**Issue by PedroHome18207** [hagezi/dns-blocklists#2916]
Is it safe to block `id.google.*`?

In EasyPrivacy the filter is different: `||id.google.*/verify/` instead of `||id.google.*^` reference: `https://github.com/easylist/easylist/blob/9fa53c0cd737341a9835b420801d98d7842f2e7e/easyprivacy/easyprivacy_thirdparty.txt#L1098C1-L1098C22`

Your response would be very helpful.

**Comment by hagezi** [comment]
So far, I have not noticed any restrictions due to the blocking of `id.google.*`

**Comment by hagezi** [comment]
@Retold3202 Do you have any further information on this?

**Comment by PedroHome18207** [comment]
Whatever the answer, here are some missing TLDs:
`||id.google.com.bo^`
`||id.google.com.py^`
`||id.google.com.uy^`

**Comment by hagezi** [comment]
Thanks @PedroHome18207, will be added on next release.

**Comment by hagezi** [comment]
Thank you @Retold3202. Does that answer your question @PedroHome18207?

**Comment by PedroHome18207** [comment]
Yes, thank you very much @hagezi and @Retold3202 for answering my question.
