### ISSUE TITLE
searx.work

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#2920]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

searx.work

### Why should the domain(s) be unblocked?

Legitimate & widely used [SearXNG](https://github.com/searxng/searxng) instance

**Comment by bphd** [comment]
It's not owned anymore :(

**Comment by hagezi** [comment]
Thanks @bphd, will be removed from the exclusions.
