### ISSUE TITLE
Denylist Request - HaGeZi - Multi NORMAL

### ISSUE THREAD

**Issue by Mile-Lile** [hagezi/dns-blocklists#2927]
### Which domain(s) should be blocked?

notify.bugsnag.com
sessions.bugsnag.com
api.bugsnag.com
app.bugsnag.com
browser.sentry-cdn.com
app.getsentry.com
ad.doubleclick.net
adservice.google.com

### Why should these domain(s) be blocked?

HaGeZi - Multi NORMAL

these are known ad hostnames

**Comment by hagezi** [comment]
Bug trackers are intentionally not blocked in light and normal, see:

I recommend that you switch to Pro.

![image](https://github.com/hagezi/dns-blocklists/assets/104343908/05170516-b519-446a-8aba-5974e8dec331)

ad.doubleclick.net and adservice.google.com are referral domains, only blocked in Pro++ and Ultimate, see:

https://github.com/hagezi/dns-blocklists/wiki/FAQ#referral

**Comment by Mile-Lile** [comment]
I apologize... thx
