### ISSUE TITLE
Life 360

### ISSUE THREAD

**Issue by azafrak** [hagezi/dns-blocklists#293]
#### Which domain(s) should be unblocked?

<!- api-cloudfront.life360.com -->

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

![348D3026-AF93-47DA-A10B-F89187951180](https://user-images.githubusercontent.com/30311445/216693503-6b637788-e0a5-4053-b156-7b9a88cccc50.jpeg)
![31CBF9BD-034F-45B3-8202-46D9C06171E7]

**Comment by azafrak** [comment]
![F9A39E0E-81F6-4664-B538-FEAC5B8084A7](https://user-images.githubusercontent.com/30311445/216694269-2188e9aa-9092-4e7a-813a-29b52038a934.jpeg)

**Comment by hagezi** [comment]
Thanks, removed.

Ping source: @assoechap

**Comment by devipasigner** [comment]
What app is this? Life360 is used to spy on phones

**Comment by azafrak** [comment]
> What app is this? Life360 is used to spy on phones

Life360 is not a spy app. It is a system created to follow family members, friends and people you love and communicate with them. You can find more information at the internet address.

**Comment by hagezi** [comment]
It is a Family Safety Service. You have to use the app consciously and decide whether to share your location or not. For me, it has nothing to do with spying.

**Comment by devipasigner** [comment]
> 

I guess you can see a lot of these services that way. Anyways, the whole point of the stalkerware blocklist is to block things like this.

**Comment by devipasigner** [comment]
And DONT forget. They sell your data. https://isharingsoft.com/why-life360-is-bad-for-privacy/?amp=1

**Comment by hagezi** [comment]
Thanks, then I didn't look closely enough when I included the source. Will only use it in the Ultimate.

**Comment by azafrak** [comment]
I think this is news that contains advertising. He also said he stopped selling Life360 data.

In addition, he recommended his own application on the site that made this news. I think this is advertising news.

It's up to you whether to use these tour applications or not. Blocking this address blocks the app entry, it's not a spying app. It is not secretly loaded into the system. I think you are wrong about this.

![1853AA8B-A407-42B7-8406-C6A21C90C27F](https://user-images.githubusercontent.com/30311445/216750404-0634ad93-017e-46d3-956e-e57d4754041e.jpeg)

**Comment by devipasigner** [comment]
> I think this is news that contains advertising. He also said he stopped selling Life360 data.
> 
> In addition, he recommended his own application on the site that made this news. I think this is advertising news.
> 
> It's up to you whether to use these tour applications or not. Blocking this address blocks the app entry, it's not a spying app. It is not secretly loaded into the system. I think you are wrong about this.
> 
> ![1853AA8B-A407-42B7-8406-C6A21C90C27F](https://user-images.githubusercontent.com/30311445/216750404-0634ad93-017e-46d3-956e-e57d4754041e.jpeg)

Are you really willing to just trust them based off that statement after staying quiet for 4 whole years? They’ve lied once, they’ll do it again. You know there are good open source alternatives right? Regarding the source, there are others, check all you want. Maybe I didn’t post the best one.

**Comment by devipasigner** [comment]
Hagezi has removed it from the pro plus list and below. I think it must remain on the ultimate list. Personally I added the stalkerware list to my collection.

**Comment by AAraonWPaul** [comment]
I despise any parent who forces their kid to use this app. Its stalking, not safety.

**Comment by azafrak** [comment]
> I despise any parent who forces their kid to use this app. Its stalking, not safety. Kids need to grow, live their life, explore, experiment, succeed, fail. Not be put in a jail cell. That isn't how we develop as humans, we never have. Reading all these reddit posts about how it completely ruined their life and relationships.. its truly heartbreaking.

My friend, I agree with you, but we no longer live in the old world order. Look around, nobody's life matters anymore. Do you want something to happen to your child? Personally, I don't want to and I would like to take some precautions in this regard. Just because I'm following him doesn't mean I'm restricting his personal life. I think it should be used purely for emergencies.

Love, peace, brotherhood and respect have decreased in the world and it is decreasing day by day. Although I agree with what you say, unfortunately things don't work like that in the new world order. People are so bad now!

**Comment by hagezi** [comment]
Everyone will have their own views on this, and that's a good thing. The fact is, everyone should decide for themselves whether to block "stalkerware indicators" or not.
I misjudged the source when I added it, it is definitely not a blocklist, for the masses.
That's why I removed the source from all lists except the Ultimate.

**Comment by azafrak** [comment]
> > I think this is news that contains advertising. He also said he stopped selling Life360 data.
> > In addition, he recommended his own application on the site that made this news. I think this is advertising news.
> > It's up to you whether to use these tour applications or not. Blocking this address blocks the app entry, it's not a spying app. It is not secretly loaded into the system. I think you are wrong about this.
> > ![1853AA8B-A407-42B7-8406-C6A21C90C27F](https://user-images.githubusercontent.com/30311445/216750404-0634ad93-017e-46d3-956e-e57d4754041e.jpeg)
> 
> Are you really willing to just trust them based off that statement after staying quiet for 4 whole years? They’ve lied once, they’ll do it again. Also, they are literally exposing children’s PRECISE location. They clearly lack any kind of morals, do you think someone like that is trustworthy? You know there are plenty of good open source alternatives right? Regarding the source, there are others, check all you want. Maybe I didn’t post the best one.

Man, all apps actually do this. It's not just life360. If a product is free, money has to be spent to cover its costs. How can someone who does not receive any money from a product keep it? Either you have to be very rich, to benefit humanity or you have to make a deal.

There is a saying you know; " if you don't pay for the product you are the product "

From the moment you use the Internet, you are not actually private and all your information is now known. If you really want to stay private, turn off your smartphone, turn off your computer and unplug your internet. And not only that, turning off the internet will not make you incognito. You know too.

So not using this application will not make you or our children private. There are many applications such as social media applications, photo editing, video making, playing games, they buy and sell this information. Do you have any suggestions for this? How long can we keep our children away from them? How far can we forbid their freedom?

We can only give advice, the decision maker will still be themselves.

**Comment by azafrak** [comment]
> Everyone will have their own views on this, and that's a good thing. The fact is, everyone should decide for themselves whether to block "stalkerware indicators" or not. Just as someone decides for himself whether to use such apps or not.
> I misjudged the source when I added it, it is definitely not a blocklist, for the masses.
> That's why I removed the source from all lists except the Ultimate.

Thank you.

Anyway, my purpose is not to discuss with friends, but to express our thoughts. I understand their reservations and agree with them. But I also stated where I joined in my comments.

**Comment by hagezi** [comment]
Thanks,, will add ...
