### ISSUE TITLE
youtube videos not playing

### ISSUE THREAD

**Issue by redcat42** [hagezi/dns-blocklists#2935]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

youtube

### Why should the domain(s) be unblocked?

videos are not playing when [https://freedns.controld.com/x-hagezi-ultimate](https://freedns.controld.com/x-hagezi-ultimate) is added to firefox, DNS settings (max protection) 

disabling dns protection in firefox allows youtube videos to start playing

**Comment by hagezi** [comment]
@redcat42 

Is not reproducible for me.

Checked with ControlD free DNS Ultimate:
- Firefox as DoH
- iOS Youtube App
- iOS Youtube via Safari

This is not a blocklist problem, seems to be a problem on your end.

**Comment by redcat42** [comment]
> @redcat42
> 
> Is not reproducible for me.
> 
> Checked with ControlD free DNS Ultimate:
> 
>     * Firefox as DoH
> 
>     * iOS Youtube App
> 
>     * iOS Youtube via Safari
> 
> 
> This is not a blocklist problem, seems to be a problem on your end.

thank you for replying, I'll check other settings in Firefox ... probably an extension acting up, sorry for the trouble ...
