### ISSUE TITLE
midjourney.co: Malware

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2936]
### Which domain(s) should be blocked?

http://midjourney.co/

### Why should these domain(s) be blocked?

This website is pretending to be the official Midjourney AI website and has been flagged as malicious by multiple engines on VirusTotal and by independent security researchers. It is also being blocked by NextDNS's AI Threat Detection.

`https://www.virustotal.com/gui/url/c23eaafde97e2703c0756e8e5fa4c47212718191fffe5fee551d68a34d977e72`
`https://www.joesandbox.com/analysis/1422226/0/html`

**Comment by hagezi** [comment]
@iam-py-test

**Comment by iam-py-test** [comment]
Added, thanks
