### ISSUE TITLE
tracker.scenetime.com

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#294]
#### What adblocker/DNS cloud service are you using?

Nextdns

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
tracker.scenetime.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is the domain for a private torrent tracker not an actual tracking link, services like jackett and prowlarr use this to pull torrents from this site.

**Comment by hagezi** [comment]
Thanks, removed.
