### ISSUE TITLE
Scam site not blocked

### ISSUE THREAD

**Issue by Levander0** [hagezi/dns-blocklists#2946]
### Which domain(s) should be blocked?

www.gym-sharkfinland.com

### Why should these domain(s) be blocked?

It is a scam site posing as Gymshark. The official finnish Gymshark website is https://fi.gymshark.com/

**Comment by iam-py-test** [comment]
[This domain is listed in my filterlist (albeit not the www. subdomain)](https://iam-py-test.github.io/lookup.html?q=gym-sharkfinland.com), but not TIF (the Threat Intelligence Feeds blocklist).
However, it is dead, and has been for at least a few months.
Thanks

**Comment by Levander0** [comment]
If it's dead then no need to add it. I encountered it a while back. It came up in google search results. 
Thanks for the info. Have a great day!
