### ISSUE TITLE
[False Positive] Best of the Bay Community Awards

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#295]
#### What adblocker/DNS cloud service are you using?
Ublock Origin, Firefox, Cloudflare DNS 

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
secondstreetapp.com
localiq.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking secondstreetapp.com prevents, Best of the Bay from loading. Best of the Bay is a community-based award system for local businesses.

localiq.com is needed when trying to click “Business Owners Click Here” (Blue Button) for businesses to claim their prizes.

Example
https://greenbaypressgazette.gannettcontests.com/Best-of-the-Bay-2023/?fbclid=IwAR3Gz9YY8fgaWf4wzKu-rXNqc9Iur18qnoWeWDZnUhAyj5sQEko7fukbpWE

**Comment by hagezi** [comment]
Thanks, fixed.
