### ISSUE TITLE
Xbox achievements blocked

### ISSUE THREAD

**Issue by Levander0** [hagezi/dns-blocklists#2950]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

v10.events.data.microsoft.com
v20.events.data.microsoft.com

### Why should the domain(s) be unblocked?

These domains are used for xbox achievements

**Comment by hagezi** [comment]
Yes, serve as a tracker, only blocked in Ultimate, you can switch to Pro++ or add it to your personal allowlist.
