### ISSUE TITLE
How can you just allow a site to be unblocked because one person requested it? How do you know that they are not the owner of the site and Mal-intended?

### ISSUE THREAD

**Issue by Rubyruby7** [hagezi/dns-blocklists#2952]
### Which domain(s) should be blocked?

aa.online-metrix.net

### Why should these domain(s) be blocked?

This domain is from a group of sub domains belonging to ThreatMetrix. The site is known for implementing an intrusive port scanning protocol called "WEBSOCKETS" to all of their visitors. Their actions are deplorable and they were blocked for a valid reason. They should not be unblocked based off of one user because that user may be affiliated with the site. That user may be pretending to be an honest Github user. The link was blocked for a valid reason in the first place. Therefore, should be blocked again and remained blocked. If a used would like to unblock this domain, they can do so on an individual basis. It is important that this domain blocked for the safety of the users. You can find out more information about the site at the link https://www.bleepingcomputer.com/news/security/list-of-well-known-web-sites-that-port-scan-their-visitors

**Comment by hagezi** [comment]
The domain is known to be required for logins to various banking apps, for example, and is therefore only blocked in the aggressive lists.
In the other lists, however, the key subdomains are blocked:

`a-sac.aa.online-metrix.net
d.aa.online-metrix.net
e.aa.online-metrix.net
eu-aa.online-metrix.net`
