### ISSUE TITLE
getkmspico.com and the multiple domains it connects to

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2953]
### Which domain(s) should be blocked?

```
download.artificusbrowser.com
poperblocker.com
ak.itponytaa.com
rnofor4ht.top
ad.install-adblockers.com
veepteero.com
ads.download-adblockers.com
file.fan
file.fan/38131da0f904a05
baldappetizingun.com
tracking.trackingrouter.com
app-rush.com
ak.oneegrou.net
```

### Why should these domain(s) be blocked?

`getkmspico.com` is a total nightmare. It is filled with malicious and phishing ads and pop-ups. Clicking anywhere results in a random malicious website appearing. I am aware that HaGeZi is blocking this domain entirely, but there are multiple associated malicious domains that are not being blocked. These domains could be potentially reached from other sources, other than `getkmspico.com`.

**Comment by hagezi** [comment]
I'll take a closer look when I get back.
