### ISSUE TITLE
Fake KMS Activation websites

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2954]
### Which domain(s) should be blocked?

```
href.li
kmsauto.uno
```

### Why should these domain(s) be blocked?

These websites deceives users into downloading malware by making them believe they are installing a legitimate Windows activator.

**Comment by iam-py-test** [comment]
`href.li` is not malicious; it is just a URL redirector. For example, `https://href.li/?https://iam-py-test.github.io/lookup.html?q=href.li` redirects to https://iam-py-test.github.io/lookup.html?q=href.li.
> href.li: hide your referrer

I have added the other domain.
Thank you.
