### ISSUE TITLE
Unblock centricabritishgas.sc.omtrdc.net

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2956]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

centricabritishgas.sc.omtrdc.net

### Why should the domain(s) be unblocked?

Required by Hive - a Home Automation/Smart Heating product/system by British Gas/Centrica

**Comment by hagezi** [comment]
The omtrdc.net tracker remains blocked in the aggressive lists. If I remove the main domain, 1000s of subdomains end up on the lists. You can unblock the domain yourself or switch to Pro.

**Comment by Dynamic5912** [comment]
Understood. Thanks!

**Comment by hagezi** [comment]
FYI: There have been several apps in the last few days that do not work properly due to the blocking of the `omtrdc.net` tracker, so I have decided to unblock the domains in Pro++ as well. In the Ultimate `*.omtrdc.net` remains blocked. The changes will be made with the next release.

**Comment by Dynamic5912** [comment]
> FYI: There have been several apps in the last few days that do not work properly due to the blocking of the `omtrdc.net` tracker, so I have decided to unblock the domains in Pro++ as well. In the Ultimate `*.omtrdc.net` remains blocked. The changes will be made with the next release.

Are you unlocking certain subdomains in the lists or omtrdc.net as a whole domain?

**Comment by hagezi** [comment]
Only "breaking" Subdomains.

**Comment by Dynamic5912** [comment]
> Only "breaking" Subdomains.

Thanks. But they're staying blocked in Ultimate?

**Comment by hagezi** [comment]
Yes
