### ISSUE TITLE
Potential tracker?

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2957]
### Which domain(s) should be blocked?

`fr-resolver-msg-global-xiaomi-n-(9 random numbers).eu-central-1.elb.amazonaws.com`

With 9 random numbers example: `fr-resolver-msg-global-xiaomi-n-123456789.eu-central-1.elb.amazonaws.com`

~~So maybe `elb.amazonaws.com`?~~

### Why should these domain(s) be blocked?

According to Perplexity and Google, this is a tracker on Xiaomi phones. However, I cannot confirm whether it's an actual tracker or not. It is being contacted very frequently on Xiaomi phones. Any ideas?

Here is what Perplexity says about it:
> The domain fr-resolver-msg-global-xiaomi is associated with Xiaomi's messaging services. It is part of the tracking system used by Xiaomi, which collects data on user activity and sends it to their servers. This domain is used for DNS requests and is connected to Amazon AWS servers in Singapore.

**Comment by hagezi** [comment]
Blocking all Amazon web services endpoints via elb.amazonaws.com (Elastic Load Balancing) is definitely a bad idea and definitely not an option.

I'll have a look at the specific domains when I get back.

**Comment by Retold3202** [comment]
This looks similar to `resolver.msg.xiaomi.net`, which looks like it's just used for Xiaomi Push. (Ex. Can be seen [here](https://www.tencentcloud.com/ko/document/product/1024/32624)):

`1. Mi Push SDK: http://new.api.ad.xiaomi.com/logNotificationAdActions, http://resolver.msg.xiaomi.net/psc/?t=a`.

It looks like blocking that domain was also shown to break Push: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1456

I can't find any evidence that this is actually used for telemetry, just looks like hearsay to me, so I think it's probably not worth blocking this, unless you don't use any Xiaomi Push functionality, in which case, it probably wouldn't hurt to block.

**Comment by hagezi** [comment]
Thank you @Retold3202 yes it is. They are needed for push and are therefore not blocked.
