### ISSUE TITLE
Some false positives

### ISSUE THREAD

**Issue by tsweet64** [hagezi/dns-blocklists#2959]
### Which AdBlocker/DNS butt service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

swadleys.com
txxx.com

### Why should the domain(s) be unblocked?

swadleys.com - appears to be a legitimate restaurant. Report submitted to oisd too.
txxx.com - appears to be a normal nsfw site

**Comment by hagezi** [comment]
@jarelllama
