### ISSUE TITLE
[False Positive] Home Depot Careers

### ISSUE THREAD

**Issue by 956ross** [hagezi/dns-blocklists#296]
#### What adblocker/DNS cloud service are you using?
Ublock Origin, Firefox, NextDNS

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
careers.homedepot.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking careers.homedepot.com prevents Home Depot Careers site from loading. This site list openings for Home Depot.

**Comment by hagezi** [comment]
Thanks, blocked by CNAME homedepot.cdn.findly.com

ping source: @badmojr

**Comment by hagezi** [comment]
Removed.
