### ISSUE TITLE
Lots & Lots of Google Advertising Domains

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#2968]
### Which domain(s) should be blocked?

acceleratewithgoogle.com
adexchange.googleapis.com
adexchangebuyer.googleapis.com
adexchangebuyer-json.googleapis.com
adexchangeseller.googleapis.com
adgoogle.net
admob.co.in
admob.co.za
admob.com.br
admob.com.es
admob.com.fr
admob.com.mx
admob.com.pt
admob.google.ac
admob.google.ad
admob.google.ae
admob.google.al
admob.google.am
admob.google.as
admob.google.at
admob.google.az
admob.google.ba
admob.google.be
admob.google.bf
admob.google.bg
admob.google.bi
admob.google.bj
admob.google.bs
admob.google.bt
admob.google.by
admob.google.ca
admob.google.cat
admob.google.cc
admob.google.cd
admob.google.cf
admob.google.cg
admob.google.ch
admob.google.ci
admob.google.cl
admob.google.cm
admob.google.cn
admob.google.co.jp
admob.google.co.uk
admob.google.cv
admob.google.cz
admob.google.de
admob.google.dj
admob.google.dk
admob.google.dm
admob.google.dz
admob.google.ee
admob.google.es
admob.google.eu
admob.google.fi
admob.google.fm
admob.google.fr
admob.google.ga
admob.google.ge
admob.google.gg
admob.google.gl
admob.google.gm
admob.google.gp
admob.google.gr
admob.google.gy
admob.google.hk
admob.google.hn
admob.google.hr
admob.google.ht
admob.google.hu
admob.google.ie
admob.google.im
admob.google.info
admob.google.io
admob.google.iq
admob.google.is
admob.google.it
admob.google.je
admob.google.jo
admob.google.jp
admob.google.kg
admob.google.ki
admob.google.kz
admob.google.la
admob.google.li
admob.google.lk
admob.google.lt
admob.google.lu
admob.google.lv
admob.google.md
admob.google.me
admob.google.mg
admob.google.mk
admob.google.ml
admob.google.mn
admob.google.ms
admob.google.mu
admob.google.mv
admob.google.mw
admob.google.ne
admob.google.nl
admob.google.no
admob.google.nr
admob.google.nu
admob.google.pl
admob.google.pn
admob.google.ps
admob.google.pt
admob.google.ro
admob.google.rs
admob.google.ru
admob.google.rw
admob.google.sc
admob.google.se
admob.google.sh
admob.google.si
admob.google.sk
admob.google.sm
admob.google.sn
admob.google.so
admob.google.sr
admob.google.st
admob.google.td
admob.google.tg
admob.google.tl
admob.google.tm
admob.google.tn
admob.google.to
admob.google.tt
admob.google.us
admob.google.vg
admob.google.vn
admob.google.vu
admob.google.ws
admob.googleapis.com
admob.hk
admob.ie
admob.in
admob.ph
admob.us
admobapplicationnetwork.com
adsense.cv
adsense.fr
adsense.google.ac
adsense.google.ad
adsense.google.ae
adsense.google.al
adsense.google.am
adsense.google.as
adsense.google.at
adsense.google.az
adsense.google.ba
adsense.google.be
adsense.google.bf
adsense.google.bg
adsense.google.bi
adsense.google.bj
adsense.google.bs
adsense.google.bt
adsense.google.by
adsense.google.ca
adsense.google.cat
adsense.google.cc
adsense.google.cd
adsense.google.cf
adsense.google.cg
adsense.google.ch
adsense.google.ci
adsense.google.cl
adsense.google.cm
adsense.google.cn
adsense.google.co.jp
adsense.google.co.uk
adsense.google.com.au
adsense.google.cv
adsense.google.cz
adsense.google.de
adsense.google.dj
adsense.google.dk
adsense.google.dm
adsense.google.dz
adsense.google.ee
adsense.google.es
adsense.google.eu
adsense.google.fi
adsense.google.fm
adsense.google.fr
adsense.google.ga
adsense.google.ge
adsense.google.gg
adsense.google.gl
adsense.google.gm
adsense.google.gp
adsense.google.gr
adsense.google.gy
adsense.google.hk
adsense.google.hn
adsense.google.hr
adsense.google.ht
adsense.google.hu
adsense.google.ie
adsense.google.im
adsense.google.info
adsense.google.io
adsense.google.iq
adsense.google.is
adsense.google.it
adsense.google.je
adsense.google.jo
adsense.google.jp
adsense.google.kg
adsense.google.ki
adsense.google.kz
adsense.google.la
adsense.google.li
adsense.google.lk
adsense.google.lt
adsense.google.lu
adsense.google.lv
adsense.google.md
adsense.google.me
adsense.google.mg
adsense.google.mk
adsense.google.ml
adsense.google.mn
adsense.google.ms
adsense.google.mu
adsense.google.mv
adsense.google.mw
adsense.google.ne
adsense.google.nl
adsense.google.no
adsense.google.nr
adsense.google.nu
adsense.google.pl
adsense.google.pn
adsense.google.ps
adsense.google.pt
adsense.google.ro
adsense.google.rs
adsense.google.ru
adsense.google.rw
adsense.google.sc
adsense.google.se
adsense.google.sh
adsense.google.si
adsense.google.sk
adsense.google.sm
adsense.google.sn
adsense.google.so
adsense.google.sr
adsense.google.st
adsense.google.td
adsense.google.tg
adsense.google.tl
adsense.google.tm
adsense.google.tn
adsense.google.to
adsense.google.tt
adsense.google.us
adsense.google.vg
adsense.google.vn
adsense.google.vu
adsense.google.ws
adsense.googleapis.com
adsensehost.googleapis.com
adsense.ie
adsense.ru
adsense.si
adservice.google.eu
adservice.google.hk
adservice.google.info
adservice.google.jp
adservice.google.us
adservice.google.vn
adsgoogle.com
adsmarketingfrontend-pa.clients6.google.com
adsonair.withgoogle.com
adwords.ae
adwords.at
adwords.be
adwords.ch
adwords.cl
adwords.cn
adwords.co.uk
adwords.corp.google.com
adwords.dk
adwords.fi
adwords.fr
adwords.google.ac
adwords.google.ad
adwords.google.ae
adwords.google.al
adwords.google.am
adwords.google.as
adwords.google.at
adwords.google.az
adwords.google.ba
adwords.google.be
adwords.google.bf
adwords.google.bg
adwords.google.bi
adwords.google.bj
adwords.google.bs
adwords.google.bt
adwords.google.by
adwords.google.ca
adwords.google.cat
adwords.google.cc
adwords.google.cd
adwords.google.cf
adwords.google.cg
adwords.google.ch
adwords.google.ci
adwords.google.cl
adwords.google.cm
adwords.google.cn
adwords.google.co.jp
adwords.google.co.uk
adwords.google.com.au
adwords.google.cv
adwords.google.cz
adwords.google.de
adwords.google.dj
adwords.google.dk
adwords.google.dm
adwords.google.dz
adwords.google.ee
adwords.google.es
adwords.google.eu
adwords.google.fi
adwords.google.fm
adwords.google.fr
adwords.google.ga
adwords.google.ge
adwords.google.gg
adwords.google.gl
adwords.google.gm
adwords.google.gp
adwords.google.gr
adwords.google.gy
adwords.google.hk
adwords.google.hn
adwords.google.hr
adwords.google.ht
adwords.google.hu
adwords.google.ie
adwords.google.im
adwords.google.info
adwords.google.io
adwords.google.iq
adwords.google.is
adwords.google.it
adwords.google.je
adwords.google.jo
adwords.google.jp
adwords.google.kg
adwords.google.ki
adwords.google.kz
adwords.google.la
adwords.google.li
adwords.google.lk
adwords.google.lt
adwords.google.lu
adwords.google.lv
adwords.google.md
adwords.google.me
adwords.google.mg
adwords.google.mk
adwords.google.ml
adwords.google.mn
adwords.google.ms
adwords.google.mu
adwords.google.mv
adwords.google.mw
adwords.google.ne
adwords.google.no
adwords.google.nr
adwords.google.nu
adwords.google.pl
adwords.google.pn
adwords.google.ps
adwords.google.pt
adwords.google.ro
adwords.google.rs
adwords.google.ru
adwords.google.rw
adwords.google.sc
adwords.google.se
adwords.google.sh
adwords.google.si
adwords.google.sm
adwords.google.sn
adwords.google.so
adwords.google.sr
adwords.google.st
adwords.google.td
adwords.google.tg
adwords.google.tl
adwords.google.tm
adwords.google.tn
adwords.google.to
adwords.google.tt
adwords.google.us
adwords.google.vg
adwords.google.vn
adwords.google.vu
adwords.google.ws
adwords.ie
adwords.it
adwords.jp
adwords.nl
adwords.no
adwords.pl
adwords.ro
adwords.se
adwords.si
adwords-select.com
adwordsexample.com
adwordsgoogle.com
dartmotif.com
pageadgooglesyndication.com

### Why should these domain(s) be blocked?

Most of these are self-explanatory, but I'll elaborate for the few that aren't as obvious:

`acceleratewithgoogle.com` - Part of Google Ads, redirects to a page titled "Google Ads AI Essentials".

`adexchange.googleapis.com` - Part of ["Doubleclick Ad Exchange"](https://developers.google.com/authorized-buyers) - "Authorized Buyers (formerly DoubleClick Ad Exchange) connects ad networks, agencies, and demand-side platforms with real-time inventory".

`adexchangebuyer.googleapis.com` - Same as above.

`adexchangebuyer-json.googleapis.com` - Same as above.

`adexchangeseller.googleapis.com` - Same as above.

`adsmarketingfrontend-pa.clients6.google.com` - Used for Google Ads Marketing, can be seen ex. [here](https://ads.google.com/home/).

`adsonair.withgoogle.com` - Part of Google Ads, Google "Ads on Air" Campaign/"Ad Experts".

`dartmotif.com` - Doubleclick "Rich Media", [Reference](https://adage.com/article/btob/doubleclick-signs-publishers-dart-motif/257853).

Let me know if you have any questions for any other domains, there will be more to come...

**Comment by hagezi** [comment]
I've added them to the aggressive lists for now. I'll take a closer look later.

**Comment by hagezi** [comment]
I think I'll leave the domains in the aggressive lists for the time being and continue to monitor them. If the domains are also used for the distribution of advertising or tracking, I will move them up in the tier.
