### ISSUE TITLE
Videos blocked at globo.com and subdomains

### ISSUE THREAD

**Issue by xxAlex7** [hagezi/dns-blocklists#2970]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

I am not sure.

### Why should the domain(s) be unblocked?

Videos on some subdomains are blocked as shown in the screenshot. Subdomains like ge.globo.com and gshow.globo.com. It's from the biggest TV station in my country.
![image](https://github.com/hagezi/dns-blocklists/assets/173583268/31f1af2b-36c4-4984-8d82-96453031493e)

**Comment by hagezi** [comment]
Geo restricted in my regiom. Can't check. Can anyone help?

**Comment by hagezi** [comment]
@xxAlex7 try unblocking www.googletagmanager.com

**Comment by xxAlex7** [comment]
> @xxAlex7 try unblocking [www.googletagmanager.com](http://www.googletagmanager.com)

I tested it with Pro++ and Ultimate and it apparently worked, thank you very much for your help.
