### ISSUE TITLE
Various ring.com domains blocked by Abused TLD list

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#2984]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

Various ring.com domains

### Why should the domain(s) be unblocked?

These are getting blocked by the Abused TLD List due to the rule **||*.gw**

This is affecting functionality of Ring devices, namely showing Notification Thumbnails/Previews for alerts on mobile devices.

**Comment by hagezi** [comment]
@Dynamic5912 And which domains are they exactly?

**Comment by Dynamic5912** [comment]
![image](https://github.com/hagezi/dns-blocklists/assets/134324737/f31d69d3-a776-4db6-a2e1-e644169f7321)

![image](https://github.com/hagezi/dns-blocklists/assets/134324737/ddd8cb94-687f-4442-9a15-f6b837797a4f)

**Comment by hagezi** [comment]
fixed.

**Comment by Dynamic5912** [comment]
Thanks. Will this come in a next filter update/change?

**Comment by hagezi** [comment]
As soon as the lists are updated by AdGuard, or if you have added them manually, the fix is already online:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds.txt

**Comment by Dynamic5912** [comment]
I've updated my lists - still being blocked though.

**Comment by Dynamic5912** [comment]
Ah - it's not updated here - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/spam-tlds.txt

The Github link is updated though

**Comment by hagezi** [comment]
Yes, it sometimes takes time until the files are updated there, at the latest with the next release.

**Comment by Dynamic5912** [comment]
Great - thanks.

I've changed my links to point to GitHub now :)
