### ISSUE TITLE
Malware, adware, PUPs & scams

### ISSUE THREAD

**Issue by PhoenixFossGR** [hagezi/dns-blocklists#2985]
### Which domain(s) should be blocked?

```
acdcdn.com
chromnius.com
retdaz.fun
mfcewkrob.com
myfood.ltd
mendress.icu
2download.online
downloadfilearea.com
mybetterck.com
havanese.top
agabreloomr.com
youradexchange.com
torrent-protection.com
week-tale.xyz
ourhotposts.com
winluckychance.com
fallstring.website
esinenmer.ml
crystal-blocker.com
shield-ads.net
watchadsfree.com
adz-skip.net
download-portal.net
rh3msg.online
adblocker-app.info
filehostpro.xyz
ezadblocker.com
eloypatrick.pro
chinnica.net
simplestar.com
realtime-bid.com
antivirus-update.shop
unik-redirect.com
unik-redirect.site
infopicked.com
get-express-vpn.online
track4ref.com
mybuzz.fun
spazdiet.com
directredirection.com
newtab.page
popblockplus.com
```

### Why should these domain(s) be blocked?

Some of these links redirect to malware and phishing sites, others install potentially malicious PUPs, and others are simply adware. Almost all of these domains have subdomains, so I recommend blocking the entire domains.

**Comment by iam-py-test** [comment]
@PhoenixFossGR where/how did you find these domains?
[chromnius.com](https://iam-py-test.github.io/lookup.html?q=chromnius.com), [downloadfilearea.com](https://iam-py-test.github.io/lookup.html?q=downloadfilearea.com), and [torrent-protection.com](https://iam-py-test.github.io/lookup.html?q=torrent-protection.com) are all listed in both my filterlist and hagezi's threat intelligence list.
youradexchange.com has been around for years, and seems to be just a sketchy advertising service.
I am looking into the rest, but it may take a while, as I am busy with other things.
Thank you

**Comment by iam-py-test** [comment]
> I'm sorry if I'm doing something wrong or if I'm wasting your time, I'm not a professional and I do this as a hobby.

No, it's fine. **You are not wasting my time**. I'm not a professional either; I do this in my spare time too.
> I am examining databases of malicious domains and software, and I watch malware analysis videos where malicious or suspicious domains are shown.

Ok, makes sense.
Some of these domains are quite old (i.e. directredirection.com [has been doing malicious stuff since 2021](https://xangis.com/adsterra-didnt-work-for-me/), but the malicious subdomain still exists, so it's hard to know if it still in use), so I was just wondering if you were seeing these domains in active use.
Please don't take my rejection of certain domains as meaning your methods are "wrong".
Thanks

**Comment by iam-py-test** [comment]
I have reviewed all the domains in this issue report, and have blocklisted those I believe are alive.
Thank you @PhoenixFossGR
