### ISSUE TITLE
Stats, ads, metrics, analytics 

### ISSUE THREAD

**Issue by rugabunda** [hagezi/dns-blocklists#2986]
### Which domain(s) should be blocked?

stats.iobit.com (stats analytics for iobit apps)
ad.ldplayer.net (ads for ldplayer app, an android emulator)
ads.brave.com (ads for brave) 
cdn.prod.metrics.imdb.a2z.com (imdb metrics)
dsol-analytics-ingress-285988153.us-east-1.elb.amazonaws.com	*lytic* (alias for [launcher2.robertsspaceindustries.com]) (analytics for online PC game "star citizen", well tested, game functions while blocked.)

geo.ads.brave.com is one of the advertising-related domains contacted by the Brave browser, even when Brave Ads are turned off.
The domain is used to determine the user's geographic location for ad targeting purposes. It returns information about the user's country and region.
For users who want to use Brave's rewards program while using network-level ad blocking (like Pi-Hole), this domain is one that needs to be whitelisted to ensure proper functionality.

### Why should these domain(s) be blocked?

To reduce online tracking

**Comment by hagezi** [comment]
Thanks @rugabunda.

`ad.ldplayer.net` - blocked in Pro++ and Ultimate, will be blocked in Light, Normal and Pro
`stats.iobit.com` - blocked in Pro++ and Ultimate, will be blocked in Light, Normal and Pro
`ads.brave.com` - blocked in Ultimate, will be blocked in Pro++
`metrics.imdb.a2z.com` - blocked in Ultimate, will be blocked in Light, Normal and Pro
`dsol-analytics-ingress-285988153.us-east-1.elb.amazonaws.com `- already blocked in all list versions

**Comment by rugabunda** [comment]
Thank you for your wonderful works!
