### ISSUE TITLE
c.msn.com

### ISSUE THREAD

**Issue by endocrine7132** [hagezi/dns-blocklists#2989]
### Which domain(s) should be blocked?

c.msn.com

### Why should these domain(s) be blocked?

This domain is included in the AdGuard DNS List and appears to be called when Microsoft Edge is launched.

**Comment by hagezi** [comment]
This is the CNAME of c.office.com and will break Office Forms, see:

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1047

c.office.com is allowed in AdGuardDNS.
