### ISSUE TITLE
International version of Xiaomi tracker is missing.

### ISSUE THREAD

**Issue by rfxcll** [hagezi/dns-blocklists#299]
#### Which domain(s) should be blocked?
data.mistat.intl.xiaomi.com

#### Why should the domain(s) be blocked?
International version of Xiaomi tracking or analytic.

**Comment by hagezi** [comment]
@rfxcll

Thanks, Xiaomi provides updates for own apps via special section in Settings. This domain is needed.
See: https://github.com/badmojr/1Hosts/issues/392

Currently, the domain is only blocked in the ultimate. I don't have a device to test, can you check?

**Comment by rfxcll** [comment]
I've a Redmi 7A, let me check tomorrow when i got the phone.
Looks like i know which app update refers to.

No, theres none of that domain in the Ultimate or this repo, i've tried searching for it before making this issue.
There's only two variant of them in the Ultimate.
```
||data.mistat.rus.xiaomi.com^
||data.mistat.india.xiaomi.com^
```
That's why i though it's missing in the first place.

**Comment by hagezi** [comment]
@rfxcll `||mistat.intl.xiaomi.com^` is blocked in Ultimate-

**Comment by rfxcll** [comment]
I've tried updating the Apps on my Redmi 7A and it's working. But this is the System App updates under the settings.
Theres another App Store by Xiaomi, called **GetApps**. But i've revoked that from my system so it can't be used.

Nevertheless, let's close this issue and i'll make it a personal blocklist only.

**Comment by hagezi** [comment]
Thanks for testing.
