### ISSUE TITLE
caitlinjohnst.one

### ISSUE THREAD

**Issue by StrangePeanut** [hagezi/dns-blocklists#2990]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

pfBlockerNG

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

caitlinjohnst.one

### Why should the domain(s) be unblocked?

It looks like the domain was listed by accident. Someone shared an article on caitlinjohnst.one which was not accessible for me due to being listed on TIF.

**Comment by hagezi** [comment]
ping @scafroglia93 - Blocklist META
