### ISSUE TITLE
ttwmed.com

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#2994]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

ttwmed.com

### Why should the domain(s) be unblocked?

LOG
![20240626-1719421240](https://github.com/hagezi/dns-blocklists/assets/9846948/4172a317-e35d-46b8-987e-6ceb270aaba3)

NSFW `camhub.cc` without access to `ttwmed.com` shows anti adblock warning instead of content on random sub sites with content video. 

![20240626-1719418269](https://github.com/hagezi/dns-blocklists/assets/9846948/c5cf4bcb-4efe-4416-afc7-1bc7fc62501b)
After unblock `ttwmed.com` video load just fine. Some blocking is handled directly via Adguard Extension.

![20240626-1719420676](https://github.com/hagezi/dns-blocklists/assets/9846948/c1b39d34-066c-4f62-8556-707dd92a14d1)

**Comment by hagezi** [comment]
Thanks @FadeMind, will be fixed in next release.
