### ISSUE TITLE
books-edge.apple.com

### ISSUE THREAD

**Issue by 4d62** [hagezi/dns-blocklists#2998]
### Which domain(s) should be blocked?

~~cds.apple.com~~
books-edge.apple.com
### Why should these domain(s) be blocked?

~~* Looks like it sends some telemetry data as showcased in https://www.youtube.com/watch?v=TJiOv2sLVxY @ 6:20
![image](<https://github.com/hagezi/dns-blocklists/assets/157558804/a7416f4f-2e9a-4c11-a11c-5b574317299d>)~~
* Hit when opening apple books ( @ 8:28)
![image](https://github.com/hagezi/dns-blocklists/assets/157558804/605d63a5-52c0-44b3-be5f-5395ae70b429)

**Comment by Retold3202** [comment]
> The video also mentions urls like oscp2.apple.com which is requested when an unknown application gets opened. Someone with a mac would have to check if blocking it doesn't cause issues . (same vid @ 5:20)

`ocsp2.apple.com` should not be blocked, it's a legitimate domain part of App Notarization & Certificate Validation, used to help prevent malicious software & domains. ([Reference](https://support.apple.com/101555))

**Comment by Retold3202** [comment]
As far as `cds.apple.com` goes, this is an interesting one and caught my eye. I actually noticed this domain myself on my network yesterday. It appears to be used as part of Apple's Help Documentation. [Reference](https://readmedium.com/apple-macintosh-network-traffic-2b172d084fd):

`direction: outgoing priority: regular process: /System/Library/PrivateFrameworks/HelpData.framework/Versions/A/Resources/helpd owner: me destination: cds.apple.com ports: 443 protocol: 6`

I just tested this on macOS and was also able to confirm this:

![image](https://github.com/hagezi/dns-blocklists/assets/132830388/481e7493-4081-4666-a36a-ca381067631f)

I'm personally not convinced this is actually being used for telemetry, I can't seem to find any evidence or data backing that up. (The video you linked only shows the connection being made, not that data is actually being sent to it).

**Comment by Retold3202** [comment]
> Is there any issues with the books-edge tho?

After some testing & experimentation, I think I understand what this is now:

It seems to be some sort of first-time set-up/initialization for the app. On macOS, I only saw the domain called once on the first launch of the Books app - After that, it has not been called again that I can see. This would also make sense based off what we can see in the video you linked:

![image](https://github.com/hagezi/dns-blocklists/assets/132830388/b37ca9a6-9296-48f0-ad16-82c30f3e778d)

So, I'm currently under the impression that this probably isn't worth blocking, unless we can see the domain being called on a consistent basis for ex. telemetry/analytics.

**Comment by hagezi** [comment]
Thank you for your support. I don't see anything "blockable" here either and agree with @Retold3202.
