### ISSUE TITLE
[False positive] stat.gov.pl

### ISSUE THREAD

**Issue by pmaliszewski** [hagezi/dns-blocklists#300]
#### What adblocker/DNS cloud service are you using?
PiHole with Google DNS upstream.

#### Which blocklists are used?

Pro+ and TIF.

#### Which domain(s) should be unblocked?

   stat.gov.pl
   workspace.stat.gov.pl
   wyszukiwarkaregon.stat.gov.pl
   wyszukiwarkaregontest.stat.gov.pl

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Those domains belong to Polish government's [Central Statistical Office](https://en.wikipedia.org/wiki/Statistics_Poland) (Główny Urząd Statystyczny) which performs a similar role to United States Census Bureau. I don't know of any services that ping stat.gov.pl in the background, so I think it's pretty safe to whitelist.

**Comment by hagezi** [comment]
Thanks, removed.

ping source: @badmojr
