### ISSUE TITLE
chatgpt.com

### ISSUE THREAD

**Issue by levinberg** [hagezi/dns-blocklists#3000]
### Which domain(s) should be blocked?

ab.chatgpt.com

### Why should these domain(s) be blocked?

privacy

**Comment by hagezi** [comment]
@brunoais Do you have more details about the domain?

**Comment by hagezi** [comment]
@retold3202 Can you provide support here?

**Comment by levinberg** [comment]
@hagezi used for A/B testing by [Statsig](https://www.statsig.com/)

it continuously makes request sending browser information. chatgpt works flawlessly even without this domain.
