### ISSUE TITLE
Some image search engines with safe search mode insecure

### ISSUE THREAD

**Issue by DonPiotr** [hagezi/dns-blocklists#3002]
### Which domain(s) should be blocked?

yandex.com
ecosia.org
images.search.yahoo.com
privacia.org

### Why should these domain(s) be blocked?

As in title. As my DNS I use 1.1.1.3 and 1.0.0.3 so in google, duckduckgo, bing I can't switch off safe search mode. In those search engines it can be done with a click.

**Comment by hagezi** [comment]
The list only blocks search engines that do not offer Safesearch. If I want to bypass Safesearch, I would have to block all search engines, so pure DNS lists with domains cannot help.

**Comment by DonPiotr** [comment]
Not sure if I can call safesearch as existing if I can disable it with literally one-two clicks. But ok, those I can block by myself.
