### ISSUE TITLE
device-api.urbanairship.com

### ISSUE THREAD

**Issue by rafalfr** [hagezi/dns-blocklists#3006]
### Which domain(s) should be blocked?

device-api.urbanairship.com

### Why should these domain(s) be blocked?

Please consider blocking this domain in the ultimate list because some applications on my phone send tracking data to this domain.

**Comment by hagezi** [comment]
@rafalfr Thanks for the hint, the domain should actually be blocked in the Ultimate, I'll see why this is not the case and add it again.

**Comment by hagezi** [comment]
@rafalfr The release will be online in about 1 hour.

**Comment by hagezi** [comment]
Still unblocked in the Pro++ and lower ref: https://github.com/hagezi/dns-blocklists/issues/2024
