### ISSUE TITLE
wingify.com

### ISSUE THREAD

**Issue by maheshrijal** [hagezi/dns-blocklists#3007]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL, Multi PRO, Multi PRO++

### Which domain(s) should be unblocked?

wingify.com

### Why should the domain(s) be unblocked?

wingify is a startup.

**Comment by hagezi** [comment]
@maheshrijal Startup for what?

Analytics, insights, tracking, ...

**Comment by maheshrijal** [comment]
vwo.com is a product by wingify.com and it does all three(Analytics, insights, tracking). But wingify.com does not do analytics, insights etc.
