### ISSUE TITLE
ChatGPT Login

### ISSUE THREAD

**Issue by cmirza** [hagezi/dns-blocklists#3009]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

ab.chatgpt.com

### Why should the domain(s) be unblocked?

This domain is required to login into the ChatGPT desktop app

**Comment by hagezi** [comment]
@levinberg https://github.com/hagezi/dns-blocklists/issues/3000

**Comment by hagezi** [comment]
I can confirm that logging in to the iOS app also does not work if the domain is blocked.

**Comment by hagezi** [comment]
@cmirza fixed.
