### ISSUE TITLE
monitoring.*.amazonaws.com needed for CloudWatch alarms to work

### ISSUE THREAD

**Issue by neitsab** [hagezi/dns-blocklists#3014]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

`monitoring.*.amazonaws.com`

### Why should the domain(s) be unblocked?

I am doing a training on AWS and I was the only one in the group not seeing the Auto Scaling alarms in CloudWatch. I had an error pop-up saying something like "An unexpected error prevents retrieving the charts" (approximate translation from memory).

I had already disabled uBlock origin for the whole AWS Console, but when I checked my NextDNS logs I saw this `monitoring.us-east-1.amazonaws.com` being blocked by HaGeZi - Multi PRO++.

After  whitelisting `*.amazonaws.com` (I know, dirty) and waiting a few minutes, I finally could see the Alarms and monitoring appear as expected. So it seems this domain is required for the AWS Console monitoring functionalities to work.

**Comment by hagezi** [comment]
Yes, and it is used for tracking, which is why it is blocked in the aggressive lists from Pro++ onwards. You can add it to your personal allowlist or downgrade to Pro.

**Comment by neitsab** [comment]
After checking the repo I thought it was blocked across all lists, hence the bug report. I have downloaded to Pro, thanks for your work and quick reply 🙏🏻

**Comment by hagezi** [comment]
@neitsab allow:

```
monitoring.af-south-1.amazonaws.com
monitoring.ap-east-1.amazonaws.com
monitoring.ap-northeast-1.amazonaws.com
monitoring.ap-northeast-2.amazonaws.com
monitoring.ap-northeast-3.amazonaws.com
monitoring.ap-south-1.amazonaws.com
monitoring.ap-south-2.amazonaws.com
monitoring.ap-southeast-1.amazonaws.com
monitoring.ap-southeast-2.amazonaws.com
monitoring.ap-southeast-3.amazonaws.com
monitoring.ap-southeast-4.amazonaws.com
monitoring.ca-central-1.amazonaws.com
monitoring.ca-west-1.amazonaws.com
monitoring.eu-central-1.amazonaws.com
monitoring.eu-central-2.amazonaws.com
monitoring.eu-north-1.amazonaws.com
monitoring.eu-south-1.amazonaws.com
monitoring.eu-south-2.amazonaws.com
monitoring.eu-west-1.amazonaws.com
monitoring.eu-west-2.amazonaws.com
monitoring.eu-west-3.amazonaws.com
monitoring.il-central-1.amazonaws.com
monitoring.me-central-1.amazonaws.com
monitoring.me-south-1.amazonaws.com
monitoring.prod.cloudwatch.amazonaws.com
monitoring.sa-east-1.amazonaws.com
monitoring.us-east-1.amazonaws.com
monitoring.us-east-2.amazonaws.com
monitoring.us-gov-east-1.amazonaws.com
monitoring.us-gov-west-1.amazonaws.com
monitoring.us-west-1.amazonaws.com
monitoring.us-west-2.amazonaws.com
```

Or only the domain(s) that apply to your region.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/6611
