### ISSUE TITLE
temu.com

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#3015]
### Which domain(s) should be blocked?

temu.com

### Why should these domain(s) be blocked?

TEMU App works like malware/spyware. This site is mostly advertised on META portals/apps (FB/Insta)
References:
 - https://grizzlyreports.com/we-believe-pdd-is-a-dying-fraudulent-company-and-its-shopping-app-temu-is-cleverly-hidden-spyware-that-poses-an-urgent-security-threat-to-u-s-national-interests/
 - https://arstechnica.com/tech-policy/2024/06/shopping-app-temu-is-dangerous-malware-spying-on-your-texts-lawsuit-claims/
 - https://urlscan.io/result/fab6789a-b0a1-4aac-bf95-a363eb4f1139/
 
 I can't find any others domains used by app for blocking.

**Comment by hagezi** [comment]
@FadeMind Yes, but this ist the "official" TEMU domain. A bit hard to block out for the masses. I have blocked TEMU in my network via AdGuard DNS Services.

I think everyone should decide for themselves whether they want to use such crap.

**Comment by hagezi** [comment]
@FadeMind https://github.com/AdguardTeam/HostlistsRegistry/blob/main/services/temu.yml

**Comment by hagezi** [comment]
What does the rest of the community think?

**Comment by super-lurker** [comment]
> What does the rest of the community think?

block em all >:(

**Comment by Dynamic5912** [comment]
> What does the rest of the community think?

Maybe make and maintain a separate "Insecure/Red Flag app/domain" list like the Tracker ones and only include them in Ultimate or the more aggressive lists?

Or just make them an optional list for people to add manually and then whitelist as needed.

**Comment by hagezi** [comment]
Very few users would understand that and very few read it anyway. The same questions always come up, even though they are answered in the readme.

The lists are already enough work.
