### ISSUE TITLE
[False Positive] Phishing Quiz

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#302]
#### What adblocker/DNS cloud service are you using?

Ublock Origin, Firefox, Cloudflare DNS

#### Which blocklists are used?
Threat Intelligence Feeds
Ultimate

#### Which domain(s) should be unblocked?
phishingquiz.withgoogle.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is a phishing quiz to test a person's knowledge when it comes spotting phishing emails.

**Comment by hagezi** [comment]
Thanks, removed.

Ping source: @mitchellkrogza
