### ISSUE TITLE
Lloyds bank app not working 

### ISSUE THREAD

**Issue by FeeninForMore** [hagezi/dns-blocklists#3020]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

zn3wyma4xs4oqh2ct-lloydsbankinggroup.siteintercept.qualtrics.com

lloydsbankinggroup.d3.sc.omtrdc.net

lloydsbankinggroup.tt.omtrdc.net

### Why should the domain(s) be unblocked?

My app was stuck on the authenticator screen, and wouldn't get past it so I disabled my DNS and it suddenly worked. I digged deeper and found unblocking these domains fixed the problem

**Comment by hagezi** [comment]
Please check again whether all domains really need to be unblocked. I can imagine that one of the omtrdc trackers is necessary, but not for the qualtrics tracker.

The Pro is quite popular and the banking app is not unpopular either, the domains have been on the list forever and so far there have been no reports of the problem.

I don't want to unblock trackers if it's not necessary.

Proceed as follows to avoid getting a false result from the DNS cache.

- Remove domains from the Allowlist.
- Wait 1 min, clear DNS cache (flight mode on/off)
- Test whether the problem still occurs, then: unblock a domain, wait 1 min, delete DNS cache, test. If this is not successful, remove the domain again and then continue with the next domain.

**Comment by hagezi** [comment]
Can anyone else here who uses the app provide support?

**Comment by FeeninForMore** [comment]
I literally don't know what's happening, it works fine now  the app wasn't working for like a day I switch off DNS and turn it back on and it works

**Comment by FeeninForMore** [comment]
Sorry for the false alarm
