### ISSUE TITLE
seat.sc.omtrdc.net

### ISSUE THREAD

**Issue by ericafterdark** [hagezi/dns-blocklists#3023]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

seat.sc.omtrdc.net

### Why should the domain(s) be unblocked?

The _My CUPRA_ app on iOS does not seem to function when this domain is blocked.

The app is used to remotely control certain CUPRA car functionality.

More info: https://www.cupraofficial.com/owners/cupra-connect

**Comment by hagezi** [comment]
See: https://github.com/hagezi/dns-blocklists/issues/2956#issuecomment-2180999931

Will be unblocked in Light to Pro.

**Comment by hagezi** [comment]
FYI: There have been several apps in the last few days that do not work properly due to the blocking of the `omtrdc.net` tracker, so I have decided to unblock the domains in Pro++ as well. In the Ultimate `*.omtrdc.net` remains blocked. The changes will be made with the next release.

**Comment by ericafterdark** [comment]
Thank you!
