### ISSUE TITLE
Lloyds bank not working 

### ISSUE THREAD

**Issue by FeeninForMore** [hagezi/dns-blocklists#3025]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

lloydsbankinggroup.tt.omtrdc.net

### Why should the domain(s) be unblocked?

Yea it's definitely this domain, It wouldn't work again I unblocked this one and it worked

**Comment by hagezi** [comment]
Will be unblocked in light to pro. Remain blocked in aggressive lists.

**Comment by hagezi** [comment]
FYI: There have been several apps in the last few days that do not work properly due to the blocking of the `omtrdc.net` tracker, so I have decided to unblock the domains in Pro++ as well. In the Ultimate `*.omtrdc.net` remains blocked. The changes will be made with the next release.
