### ISSUE TITLE
[False Positive] Unmineable

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#303]
#### What adblocker/DNS cloud service are you using?

Ublock Origin, Firefox, Cloudflare DNS

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
unmineable.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Unmineable is a crypto currency mining website that allows people to mine for otherwise unmineable tokens.

**Comment by hagezi** [comment]
Thanks,removed.

Ping @bongochong

**Comment by bongochong** [comment]
Seems to be [a bit sketchy](https://old.reddit.com/r/dogecoin/comments/livdda/is_unmineable_a_legit_miner_or_a_scam_in_disguise/?sort=confidence) but not malware or a scam, so I'll whitelist it and it should be gone from all my blacklists after the next full update in a day or two. It's in a few of the sources I pull from that block malicious crypto-miners. Thank you once again @hagezi! I'll relay this info to other relevant list maintainers.

**Comment by bongochong** [comment]
Turned out to be just one source, so I'm pinging @hoshsadiq. Hope he sees this.

**Comment by hoshsadiq** [comment]
It doesn't seem to be blocked for me with my normal block lists, which also includes the nocoin list. Do you know which filter causes the issue?

**Comment by bongochong** [comment]
@hoshsadiq apologies. You're correct. It's the suspicious crypto mining maltrail list from @stamparm. For anyone interested, the basis for including `unmineable.com` seems due to activity from a rootkit: https://blog.talosintelligence.com/necro-python-bot-adds-new-tricks/ though it appears that it's only `rx.unmineable.com` which is worthy of inclusion.

**Comment by hagezi** [comment]
Thanks @bongochong

**Comment by bongochong** [comment]
No problemo. My plan is to whitelist unmineable.com in my less aggressive Mini lists, while still keeping rx.unmineable.com in all of my blacklists, for now at least. I want to try and dig up more info about the rootkit which was communicating with that subdomain, though it looks as if it was a third party simply taking advantage of that entity's infrastructure.

**Comment by hagezi** [comment]
I will block the subdomain rx again as well.

**Comment by bongochong** [comment]
From what I've read, the subdomain is associated with a number of their mining pools, but - at least according to that Talos post - it was being used by a malicious program for skimming funds into a Tezos wallet. I'll update you here if / when I find out anything more substantial. It may just have been a one-off case of a botnet misusing Unmineable's network.

**Comment by hagezi** [comment]
> It may just have been a one-off case of a botnet misusing Unmineable's network.

Yes, that's what I think, but I haven't found anything else about it yet.

**Comment by bongochong** [comment]
I guess great minds do think alike! That does appear to be the case. After a little more digging, I found that Quad9 also used to block `rx.unmineable.com` [1](https://old.reddit.com/r/Unmineable/comments/sitpwl/rxunmineablecom3333_dns_error_unknown_node_or/), but after querying several `unmineable.com`  subdomains via Quad9, they no longer appear to be blocked. I'm tentatively going to whitelist the two domains in question for my MiniLists, while deferring to the upstream source for my standard lists.

**Comment by hagezi** [comment]
dig `rx.unmineable.com` via secure DNS

![grafik](https://user-images.githubusercontent.com/104343908/217090960-b2330584-9cc4-42c8-997a-3b2f48292515.png)

**Comment by bongochong** [comment]
Whoa. Unblocked on a wide array of resolvers. Already removed from my less aggressive lists, and it looks like I'll be pruning it from my standard lists next. Thanks again. Didn't mean to complicate your decision making process by the way.

**Comment by stamparm** [comment]
I would not suggest blocking of anything based only on entries from Maltrail's [suspicious](https://github.com/stamparm/maltrail/tree/master/trails/static/suspicious) folder. those were not meant for blocking, but for detection of potentially "suspicious" DNS traffic
