### ISSUE TITLE
Windows 10 Defender Removes events.data.microsoft.com From Hosts File

### ISSUE THREAD

**Issue by taufikp** [hagezi/dns-blocklists#3030]
Hi,

Not really an issue but just to let you know that Microsoft Windows Defender managed to remove events.data.microsoft.com from hosts file and tagged it as this virus: SettingsModifier:Win32/PossibleHostsFileHijack, few days after I put the anti tracker list in hosts file.

Thank you

**Comment by hagezi** [comment]
As long as he does not delete the subdomains such as self.events.* and co, this is not a problem, the telemetry is blocked. Or does he remove them too?

Bravo Microsoft ....

**Comment by hagezi** [comment]
This seems to be a general host file protection, see:

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=SettingsModifier%3AWin32%2FPossibleHostsFileHijack&threatid=14994

"_If you have changed the Hosts file yourself, you need to exclude it from detection by your antivirus software._"

https://support.microsoft.com/de-de/topic/hosts-file-is-detected-as-malware-in-windows-defender-4320fa8b-0d54-1129-db85-61f095144521

**Comment by taufikp** [comment]
Thank you, good to know we can exclude hosts file from AV. And when I compared the tampered hosts file with your list here, only events.data.microsoft.com removed by Windows Defender. Interesting.
