### ISSUE TITLE
ControlD Folder limitations

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#3032]
[BUG/LIMITATION]
Folders for ControlD stops importing once 267 entries reached!

**Comment by hagezi** [comment]
@xRuffKez Which folder?

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/b0a2a511-c7fd-46bb-a915-793cae2f7a60)

**Comment by hagezi** [comment]
I can't find any problems with the folders.

**Comment by xRuffKez** [comment]
Referral, but wow, why does it work for you? I think it stops importing once it encounters my rule as dublicate.

**Comment by hagezi** [comment]
Yes, duplicates are not allowed. However, this is also displayed in a message during import.
