### ISSUE TITLE
host.secureserver.net

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#304]
#### What adblocker/DNS cloud service are you using?
ControlD

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
`host.secureserver.net`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
For your consideration: the CNAME of `lp.acanac.com` is `59.44.167.72.host.secureserver.net`: https://mxtoolbox.com/SuperTool.aspx?action=cname%3alp.acanac.com&run=toolpage

This means this page is inaccessible: https://lp.acanac.com/on-en-in-alst/ (source: https://forums.redflagdeals.com/acanac-altima-start-ca-subscribers-switch-acanac-get-free-service-6-months-quebec-ontario-2599242/)

`host.secureserver.net` exists in the Pro++ list but not the Pro list.

```
pro.plus.txt:host.secureserver.net
pro.plus.txt:104.129.205.92.host.secureserver.net
pro.txt:104.129.205.92.host.secureserver.net
```

Thank you as always!

**Comment by durablenapkin** [comment]
Changed from Pro++ to Pro in ControlD and I am confirming I am able to access the above page. I'm thinking that the issue has more to do with ControlD's wildcard domain blocking and perhaps I should stick with a less aggressive list variant.

**Comment by hagezi** [comment]
Thanks, this is not a ControlD problem, *.host.secureserver.net was fully blocked in my wildcard list. I have fixed it.

**Comment by durablenapkin** [comment]
Thank you, good to know! Switched back to Pro++ :)
