### ISSUE TITLE
cloudns.net

### ISSUE THREAD

**Issue by assid2** [hagezi/dns-blocklists#3041]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

opnsense

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

DoH/VPN/TOR/Proxy Bypass

### Which domain(s) should be unblocked?

cloudns.net

### Why should the domain(s) be unblocked?

cloudns.net requested previously as well. just found it in this list too. cloudns is a DNS provider similar to cloudflare for authoritive servers

**Comment by hagezi** [comment]
Yes, it is a DNS provider and therefore blocked in the bypass list.

**Comment by hagezi** [comment]
@assid2 
Yes, it is a DNS provider and therefore blocked in the bypass list. Are no usable DNS instances hosted via the main domain?

**Comment by assid2** [comment]
Actually it's not a DNS resolver for the public internet like 8.8.8.8 for example, it's for authoritive servers, that means it you have a domain and you want to have a hosted DNS so you work with companies like this to host your DNS for your domain. 
There is a difference between DNS authoritive servers and resolvers and should be treated differently, and I don't think I see that they provide public resolvers
Nextdns , quad9, etc on the other hand are public resolvers not authoritative servers they don't host domains
