### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by archon-valec** [hagezi/dns-blocklists#305]
#### What adblocker/DNS cloud service are you using?

Adguard Home

#### Which blocklists are used?

HaGeZi Personal Black & White

#### Which domain(s) should be unblocked?

ship.sephora.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Shipment tracking for sephora orders

**Comment by hagezi** [comment]
Thankes, fixed.
