### ISSUE TITLE
Crypto scam domains

### ISSUE THREAD

**Issue by ghost** [hagezi/dns-blocklists#306]
#### Which domain(s) should be blocked?
tsla-win.com
bytesla.net
cryptolnvest.com
2xtsla.io
teslafuture.io
teslatime.net
ark-invests.net
23elon.pro
x2-promo.net
tslax2.io
teslamotors2x.com
familybakery.xyz
teslaev.d1v854kgghhsze.amplifyapp.com
teslapull.io
teslainc2023.net
tesla2xdrop.com
cryptogiveaway.host
teslacars.space
teslapull.com
x2droptesla.com

#### Why should the domain(s) be blocked?
All of these are Elon Musk/Crypto related scams/fake giveaways.

**Comment by durablenapkin** [comment]
Thanks! All added.
