### ISSUE TITLE
Polyfill.io and subdomains

### ISSUE THREAD

**Issue by BulldozerPete** [hagezi/dns-blocklists#3062]
### Which domain(s) should be blocked?

See linked article.

### Why should these domain(s) be blocked?

https://www.golem.de/news/grossteil-aus-deutschland-fast-400-000-webhosts-verbreiten-malware-via-polyfill-io-2407-186716.html

**Comment by hagezi** [comment]
Already blocked in all lists

https://github.com/hagezi/dns-blocklists/blob/0020e13a53d144aa7b3da2ada9ef7f8ba1e04918/submit_pullrequest_here/deny_light-ultimate.txt#L60

https://github.com/hagezi/dns-blocklists/blob/0020e13a53d144aa7b3da2ada9ef7f8ba1e04918/submit_pullrequest_here/deny_tif.txt#L47

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/8df94aac-1543-4d29-8696-04d3439e7b2e)

**Comment by BulldozerPete** [comment]
„Dazu gehören bei vielen Webdiensten eingebundene Domains wie bootcdn.net, bootcss.com, staticfile.net und staticfile.org. Laut Censys gibt es zumindest im Falle von bootcss.com Hinweise darauf, dass die Domain für bösartige Aktivitäten eingesetzt wurde – und das mindestens seit Juni 2023.“

**Comment by hagezi** [comment]
bootcss.com, staticfile.net and staticfile.org blocked in all lists, bootcdn.net only blocked in aggressive lists. Wil check ...

**Comment by alswl** [comment]
@hagezi Why should staticfile.org be blocked? There is no apparent connection between polyfill.io and staticfile.org.

**Comment by iam-py-test** [comment]
Please see this article: [Polyfill.io, BootCDN, Bootcss, Staticfile attack traced to 1 operator](https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/).
Thank you

**Comment by alswl** [comment]
@iam-py-test thank you for your prompt response; I've received it.
