### ISSUE TITLE
this is for analytics purpose 

### ISSUE THREAD

**Issue by botollama** [hagezi/dns-blocklists#3063]
### Which domain(s) should be blocked?

sdk.split.io
I find this on terminus app

### Why should these domain(s) be blocked?

Tracking stuufff
![Screenshot_20240705-000917~2](https://github.com/hagezi/dns-blocklists/assets/162728301/1cec09c4-d830-4314-8a67-ce7a2169a04c)

**Comment by hagezi** [comment]
```
# EA Desktop App - Properties/Download unavailable / Affects various apps
auth.split.io
cdn.split.io
sdk.split.io
```

`events.split.io` (tracking) is blocked in all list versions.

**Comment by botollama** [comment]
I have blocked but don't effect any function of that app.

**Comment by hagezi** [comment]
Affects various apps, e.g.:
https://github.com/AdAway/adaway.github.io/issues/377

The tracking via `events.split.io` is blocked.

**Comment by botollama** [comment]
Ok thanks for that i will remove the cdn from my deny list but this has to be noted that it does not effect the app.
Anyways thanks for your great work i highly appreciate.
