### ISSUE TITLE
cdn.glitch.global

### ISSUE THREAD

**Issue by Suyooo** [hagezi/dns-blocklists#3064]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

cdn.glitch.global

### Why should the domain(s) be unblocked?

Block added in 4fbe5d. The domain is the CDN for https://glitch.com/, a browser code editor and hosting service, and projects built on it.

**Comment by hagezi** [comment]
ping @bongochong

**Comment by bongochong** [comment]
Thank you for the ping @hagezi Will be remedying this on my end today as well.
