### ISSUE TITLE
Tracklutions Subdomains (to be Investigated)

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#3065]
Hey contributors and those who want to participate.
Does someone know which subdomains of Tracklutions are used for Tracking?
Once blocked, is there breakage of services?

Please share your work about Tracklutions, e.g. More (Sub)Domains of the Service.

Following Subdomains of Tracklution are under investigation:

```
api.bhg.tracklution.com
api.karkkainen.tracklution.com
api.mediashake.tracklution.com
api.tagomo.tracklution.com
bhg.tracklution.com
karkkainen.tracklution.com 
mediashake.tracklution.com
my.bhg.tracklution.com 
my.tagomo.tracklution.com
tagomo.tracklution.com
tralut.tracklution.com
```

Sincerely,
xRuffKez

**Comment by hagezi** [comment]
Tracklution is a data quality software designed to help businesses improve tracking for their digital advertising efforts. The platform facilitates the use of server-side tracking, first-party cookies, and conversion APIs across multiple ad platforms, all within a unified interface. This setup aims to provide better tracking and data management for marketing campaigns.

Block it in the aggressive lists ...

**Comment by xRuffKez** [comment]
@hagezi Affirmative. Once it is done, will push to ULTIMATE.

**Comment by hagezi** [comment]
@xRuffKez I already have them in my DB for Pro++ and Ultimate, they will become active in the current release.

**Comment by xRuffKez** [comment]
Thanks for the Information, therefore i will cease my work on this service.
