### ISSUE TITLE
Unblock url.rw

### ISSUE THREAD

**Issue by nishaddesilva** [hagezi/dns-blocklists#308]
#### What adblocker/DNS cloud service are you using?

NextDNS 

#### Which blocklists are used?
HaGeZi - Multi PRO++

#### Which domain(s) should be unblocked?
url.rw

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is a URL referral blocking platform. Please check again. Thanks!

**Comment by hagezi** [comment]
Thanks, removed.

ping @notracking @smed79

**Comment by notracking** [comment]
Thanks!

**Comment by smed79** [comment]
Removed ...

Thank you for the report and the ping.
