### ISSUE TITLE
source list

### ISSUE THREAD

**Issue by alsyundawy** [hagezi/dns-blocklists#3086]
### Which domain(s) should be blocked?

https://blocklist.sefinek.net/generated/v1/0.0.0.0/abuse/blocklistproject/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/abuse/urlhaus.abuse.ch/hostfile.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/0Zinc/easylist.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/DandelionSprout.GameConsoleAdblockList.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/FadeMind/UncheckyAds.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/MajkiIT/SmartTV-ads.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/ShadowWhisperer/Ads.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/adaway/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/anudeepND/adservers.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/blocklistproject/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/blocklistproject/youtube.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/craiu/mobiletrackers.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/crazy-max/spy.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/disconnectme/simple-ad.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/AdguardDNS.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/Admiral.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/Easylist.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/Prigent-Ads.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/jerryn70/GoodbyeAds.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/r-a-y/AdguardMobileAds.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/sefinek.hosts.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ads/yoyo/ads-trackers-etc.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/amp/developerdan/amp-hosts-extended.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/amp/ente-dev/google-amp-hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/anime/myanimelist.net.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/anime/shinden.pl.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/apps/discord.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/apps/skype.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/apps/spotify.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/apps/whatsapp.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/cryptojacking/Snota418/Crypto-streams.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/cryptojacking/firebog/Prigent/Crypto.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/cryptojacking/hoshsadiq/adblock-nocoin-list.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/cryptojacking/zerodot1/CoinBlockerLists-hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/crypto/sites/sefinek.hosts.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/dating-services/developerdan/extended.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/dating-services/sefinek.hosts.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/dead-domains/jarelllama/dead-domains.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/drugs/blocklistproject/drugs.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/FadeMind/add-2o7Net.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/MajkiIT/adguard-host.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/MajkiIT/easy-privacy-host.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/deathbybandaid/CountryCodesLists-France.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/deathbybandaid/ParsedBlacklists-EasyList-Liste-FR.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/deathbybandaid/ParsedBlacklists-EasyList.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/hagezi/pro.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/justdomains/adguarddns-justdomains.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/oisd/big.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/r-a-y/AdguardApps.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/extensions/r-a-y/AdguardMobileSpyware.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/fakenews/StevenBlack/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/fakenews/marktron/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/fraud/blocklistproject/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/gambling/MajkiIT/gambling-hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/gambling/StevenBlack/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/gambling/TrustPositif/gambling-indonesia.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/gambling/blocklistproject/hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/gambling/sefinek.hosts.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/games/league-of-legends.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/games/valorant.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/hate-and-junk/developerdan/extended.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/AssoEchap/stalkerware-indicators.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/DandelionSprout-AntiMalwareHosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/RPiList/Malware.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/Spam404/main-blacklist.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/bigdargon/hostsVN.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/blocklistproject/malware.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/digitalside/latestdomains.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/disconnectme/simple-malvertising.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/malware-filter/urlhaus-filter-hosts-online.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/phishing.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/quidsup/notrack-malware.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/reported-by-norton.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/sefinek.hosts1.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/sefinek.hosts2.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/suspicious.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/web-attacks.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/other/StevenBlack/fakenews-gambling-porn.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/Dogino/Discord-Phishing-URLs-phishing.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/RPiList/Phishing-Angriffe.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/blocklistproject/phishing.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/phishing.army/blocklist-extended.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/piracy/blocklistproject/piracy.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/ransomware/blocklistproject/ransomware.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/redirect/blocklistproject/redirect.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/Dogino/Discord-Phishing-URLs-scam.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/blocklistproject/scam.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/durablenapkin/scamblocklist.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/jarelllama/scam.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/scam/sefinek.hosts.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/booth.pm.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/gamebanana.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/omegle.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/patreon.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/pinterest.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/pixiv.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/riotgames.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/sites/youtube.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/social/facebook.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/social/instagram.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/social/snapchat.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/social/tiktok.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/social/twitter.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/spam/FadeMind/add-Spam.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/spam/RPiList/spam-mails.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/spam/stopforumspam/toxic-domains-whole.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/suspicious/FadeMind/add-Risk.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/suspicious/firebog/w3kbl.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/test.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/0Zinc/easyprivacy.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/MajkiIT/adguard-mobile-host.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/ente-dev/tv.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/frogeye/firstparty-trackers-hosts.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/mitchellkrogza/INACTIVE.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/neodevpro/host.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/quidsup/trackers-hosts.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/useless-websites/jarelllama/parked-domains.fork.txt
https://blocklist.sefinek.net/generated/v1/0.0.0.0/useless-websites/sefinek.hosts.txt

### Why should these domain(s) be blocked?

all in one list

**Comment by xRuffKez** [comment]
Do me a favor @alsyundawy and add every single list you mentioned to your dns filter instance. I pay you 100€ if you have no FP within 24h!
