### ISSUE TITLE
LG WebOS domains found on reddit and personally tested

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#309]
#### Which domain(s) should be blocked?

```
aic.recommend.lgtvcommon.com
images.redbox.com
aic.sports.lgtviot.co
images.pluto.tv
discovery.meethue.com
aic.wiseconfig.lgtvcommon.com
aic.homeprv.lgtvcommon.comaic-gfts.lge.com
aic-op-lss.lgthinq.com
aic.api.lgtviot.com
aic.lgtviot.com
ngfts.lge.com
us.emp.lgsmartplatform.com
us.lgeapi.com
aic.nudge.lgtvcommon.com
us.lgtvsdp.com
www.ueiwsp.com
api.us-east-1.aiv-delivery.net
d184dfn36gombl.cloudfront.net
aic-gfts.lge.com
aic-op-lss.lgthinq.com
lss.lgthinq.com
aic.api.lgtviot.com
common.lgthinq.com
canvas.tubitv.com
qt2-ngfts.lge.com
img.nvidiagrid.net
cdn77.utomik.com
i.ibb.co
aic.wiseconfig.lgtvcommon.com
images.redbox.com
aic-ngfts.lge.com
ngfts.lge.com
cdpbeacon.lgtvcommon.com
cdpsvc.lgtvcommon.com
homeprv.lgtvcommon.com
nudge.lgtvcommon.com
rdl.lgtvcommon.com
recommend.lgtvcommon.com
lgsmartad.com
service.lgtvcommon.com
alphonso.tv
```

#### Why should the domain(s) be blocked?

They are samsung telemetry/sponsor domains.

#### Why are there so many?

Samsung switched their tv ad providers and it seems not many people took notice.

**Comment by hagezi** [comment]
Hi, thanks, my results so far after checking the domains:

On Pro++/Ultimate - not looked at the lists below:
```
api.us-east-1.aiv-delivery.net - blocked by CNAME global.telemetry.insights.video.a2z.com
aic-ngfts.lge.com
alphonso.tv
lgsmartad.com
```

Dead (NXDOMAIN) - possible that subdomains resolve (see missing), not checked against the whitelist:
```
aic.sports.lgtviot.co
aic.homeprv.lgtvcommon.comaic-gfts.lge.com
cdpbeacon.lgtvcommon.com
cdpsvc.lgtvcommon.com
homeprv.lgtvcommon.com
nudge.lgtvcommon.com
rdl.lgtvcommon.com
recommend.lgtvcommon.com
service.lgtvcommon.com
```

Whitelisted:
```
ngfts.lge.com - NPO Start app on lg webOS televisions / blocks thumbnails from loading in the LG Content Store
us.lgtvsdp.com - https://github.com/Perflyst/PiHoleBlocklist/issues/117

discovery.meethue.com - Hue bridge - https://github.com/hagezi/dns-blocklists/issues/208

canvas.tubitv.com - Tubi (Movie Covers) - https://github.com/ShadowWhisperer/BlockLists/blob/master/Whitelists/Whitelist

cdn77.utomik.com - CDN for utomik.com Gaming on various platforms

Image "hosting":
i.ibb.co - Images on upload site
images.pluto.tv
images.redbox.com - http://images.redbox.com/Images/EPC/boxartlarge/8421.jpg
img.nvidiagrid.net
```

Missing / to check - more datat needed:
```
aic.api.lgtviot.com
aic-gfts.lge.com
aic.lgtviot.com
aic.nudge.lgtvcommon.com
aic-op-lss.lgthinq.com
aic.recommend.lgtvcommon.com
aic.wiseconfig.lgtvcommon.com
common.lgthinq.com
d184dfn36gombl.cloudfront.net
lss.lgthinq.com
qt2-ngfts.lge.com
us.emp.lgsmartplatform.com
us.lgeapi.com
www.ueiwsp.com
```

**Comment by hagezi** [comment]
Checked the "dead" SOA domains on possible subdoamins:

```
cdpbeacon.lgtvcommon.com
aic.cdpbeacon.lgtvcommon.com - on my lists
eic.cdpbeacon.lgtvcommon.com - will be added
```
```
cdpsvc.lgtvcommon.com - more data needed, what this is for?
aic.cdpsvc.lgtvcommon.com
eic.cdpsvc.lgtvcommon.com
```
```
homeprv.lgtvcommon.com - more data needed, what this is for?
aic.homeprv.lgtvcommon.com
eic.homeprv.lgtvcommon.com
kic.homeprv.lgtvcommon.com
ruc.homeprv.lgtvcommon.com
```
```
nudge.lgtvcommon.com - more data needed, what this is for?
aic.nudge.lgtvcommon.com
eic.nudge.lgtvcommon.com
kic.nudge.lgtvcommon.com
ruc.nudge.lgtvcommon.com
```
```
rdl.lgtvcommon.com - more data needed, what this is for?
aic.rdl.lgtvcommon.com
eic.rdl.lgtvcommon.com
kic.rdl.lgtvcommon.com
ruc.rdl.lgtvcommon.com
```
```
recommend.lgtvcommon.com - more data needed, what this is for?
aic.recommend.lgtvcommon.com
eic.recommend.lgtvcommon.com
kic.recommend.lgtvcommon.com
ruc.recommend.lgtvcommon.com
```
```
service.lgtvcommon.com  - more data needed, what this is for?
aic.service.lgtvcommon.com
eic.service.lgtvcommon.com
kic.service.lgtvcommon.com
ruc.service.lgtvcommon.com
```

**Comment by hagezi** [comment]
Finally ...

Could be that it makes LG ThinQ unusable? - https://www.lg.com/us/discover/thinq/app:
```
aic-op-lss.lgthinq.com 
common.lgthinq.com
lss.lgthinq.com
```

Missing / to check - more data needed:
```
aic-gfts.lge.com
aic.api.lgtviot.com
aic.cdpsvc.lgtvcommon.com
aic.homeprv.lgtvcommon.com
aic.lgtviot.com
aic.nudge.lgtvcommon.com
aic.rdl.lgtvcommon.com
aic.recommend.lgtvcommon.com
aic.service.lgtvcommon.com
aic.sports.lgtviot.com
aic.wiseconfig.lgtvcommon.com
d184dfn36gombl.cloudfront.net
eic.cdpsvc.lgtvcommon.com
eic.homeprv.lgtvcommon.com
eic.nudge.lgtvcommon.com
eic.rdl.lgtvcommon.com
eic.recommend.lgtvcommon.com
eic.service.lgtvcommon.com
kic.homeprv.lgtvcommon.com
kic.nudge.lgtvcommon.com
kic.rdl.lgtvcommon.com
kic.recommend.lgtvcommon.com
kic.service.lgtvcommon.com
qt2-ngfts.lge.com
ruc.homeprv.lgtvcommon.com
ruc.nudge.lgtvcommon.com
ruc.rdl.lgtvcommon.com
ruc.recommend.lgtvcommon.com
ruc.service.lgtvcommon.com
us.emp.lgsmartplatform.com
us.lgeapi.com
www.ueiwsp.com
```

Anyone reading along who can help with the analysis?

**Comment by markangus2b** [comment]
I have an older LG OLED55C7P-U Web OS TV. I have added all the domains in your last post to my NextDNS Denylist. I can confirm that `aic-ngfts.lge.com` does prevent some cover art from displaying properly. I haven't found anything else broken in the LG content store on the TV.

**Comment by hagezi** [comment]
Many thanks for testing and your support.

**Comment by markangus2b** [comment]
### Final LG Web OS TV Basic Operation Whitelist
What I specifically checked was:
- Time and Date Synchronization.
- LG Content Store, including downloading apps.
- Setting TV location, presumably for guide data.
- Functionality of Guide App, for both local channels and Internet channels.

I used NextDNS with the block page disabled when preforming these tests. Here are all the domains I found, that are required to operate my LG Web OS TV.

```
us.lgeapi.com
us.emp.lgsmartplatform.com
us.rdx2.lgtvsdp.com
ngfts.lge.com
aic-ngfts.lge.com
us.lgtvsdp.com
us.ibs.lgappstv.com
aic.cdpsvc.lgtvcommon.com
aic.service.lgtvcommon.com
```

us.lgeapi.com - _Causes error message on LG ThinQ App_
us.emp.lgsmartplatform.com - _Causes error message on LG ThinQ App_
us.rdx2.lgtvsdp.com - _Required for LG Cover Art_
ngfts.lge.com - _Required for LG Cover Art_
aic-ngfts.lge.com - _Required for LG Cover Art_
us.lgtvsdp.com - _Prevents LG Content Store from loading_
us.ibs.lgappstv.com - _Needed for Service Location Area (Settings)_
aic.cdpsvc.lgtvcommon.com - _Prevents Internet Channel guide data from downloading_
aic.service.lgtvcommon.com - _Prevents local OTA Channel guide data from downloading_

The rest of the potential blacklisted domains should be okay to add to the blocklist, as I did not encounter any breakage. At least for LG Web OS TVs.

**Comment by hagezi** [comment]
Thanks for the great work @markangus2b.

**Comment by hagezi** [comment]
This leaves, potentially false positives:

Breaks IoT things?
```
aic.lgtviot.com
aic.api.lgtviot.com
aic.sports.lgtviot.com
ueiwsp.com - QuickSetAPI -  #https://rapidapi.com/blog/directory/quickset
```

Random Cloudflare, couldn't find anything on this:
`d184dfn36gombl.cloudfront.net`

Because aic.service.lgtvcommon.com is whitelisted?
```
eic.service.lgtvcommon.com
kic.service.lgtvcommon.com
ruc.service.lgtvcommon.com
```

Because aic.cdpsvc.lgtvcommon.com is on the whitelist?
`eic.cdpsvc.lgtvcommon.com`

To the blacklist I could add:
```
aic-gfts.lge.com
qt2-ngfts.lge.com
aic.homeprv.lgtvcommon.com
eic.homeprv.lgtvcommon.com
kic.homeprv.lgtvcommon.com
ruc.homeprv.lgtvcommon.com
aic.nudge.lgtvcommon.com
eic.nudge.lgtvcommon.com
kic.nudge.lgtvcommon.com
ruc.nudge.lgtvcommon.com
aic.rdl.lgtvcommon.com
eic.rdl.lgtvcommon.com
kic.rdl.lgtvcommon.com
ruc.rdl.lgtvcommon.com
aic.recommend.lgtvcommon.com
eic.recommend.lgtvcommon.com
kic.recommend.lgtvcommon.com
ruc.recommend.lgtvcommon.com
aic.wiseconfig.lgtvcommon.com
```

**Comment by hagezi** [comment]
I will add the following domains to the Pro++ and Ultimate, then we will see if there are any more false positives:

```
aic-gfts.lge.com
qt2-ngfts.lge.com
aic.homeprv.lgtvcommon.com
eic.homeprv.lgtvcommon.com
kic.homeprv.lgtvcommon.com
ruc.homeprv.lgtvcommon.com
aic.nudge.lgtvcommon.com
eic.nudge.lgtvcommon.com
kic.nudge.lgtvcommon.com
ruc.nudge.lgtvcommon.com
aic.rdl.lgtvcommon.com
eic.rdl.lgtvcommon.com
kic.rdl.lgtvcommon.com
ruc.rdl.lgtvcommon.com
aic.recommend.lgtvcommon.com
eic.recommend.lgtvcommon.com
kic.recommend.lgtvcommon.com
ruc.recommend.lgtvcommon.com
aic.wiseconfig.lgtvcommon.com
eic.service.lgtvcommon.com
kic.service.lgtvcommon.com
ruc.service.lgtvcommon.com
```

**Comment by hagezi** [comment]
The complete LG webOS Blacklist can be found here:
https://github.com/hagezi/dns-data-collection/blob/main/data/native/lg-webos.txt

Let me know if I missed something.

**Comment by hagezi** [comment]
allow `aic-gfts.lge.com` - https://github.com/hagezi/dns-blocklists/issues/995

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/1216

allow:
```
eic.cdpsvc.lgtvcommon.com
eic.recommend.lgtvcommon.com
```

**Comment by hagezi** [comment]
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.lgwebos.txt

**Comment by Glassertje** [comment]
@hagezi Thank you for your great work.

**Comment by boospy** [comment]
Very thanks, that helped me a lot too.

**Comment by jimmielk** [comment]
Anyone know which domains block LG webOS from checking to see if the firmware needs updating after powering TV on and popping up the annoying window telling me to update the firmware.  I need my LG TV to allow installed streaming apps to work properly but do not wish to ever update the firmware, since it's working perfectly.

**Comment by hagezi** [comment]
Try blocking snu.lge.com

**Comment by piratenpanda** [comment]
Not updating firmware and leaving known vulnerabilities unpatched is also not a great idea tbh

**Comment by ExtRIELICi** [comment]
I've noticed that `rdx2.lgtvsdp.com` is very active in my DNS logs and it not blocked by any filterlist. Other `lgtvsdp.com` subdomains are also very active, and according to some quick research, these seem to be aggressive trackers/loggers.

Could you please add them to the Ultimate filter? It's the most aggressive version of HaGeZi filters after all.

There also many other domains to list, but I will have to do some research about them before asking for a block.

@hagezi

**Comment by boospy** [comment]
I now have a whitelist. It's easier.

**Comment by hagezi** [comment]
@ExtRIELICi `rdx2.lgtvsdp.com` - required for LG Cover Art

**Comment by ExtRIELICi** [comment]
> [@ExtRIELICi](https://github.com/ExtRIELICi) `rdx2.lgtvsdp.com` - required for LG Cover Art

I’m not sure what that is, but I’m just interested in watching TV channels and possibly using Netflix. However, I understand if it causes problems. Since it’s the Ultimate filter, I thought it should be blocked. I will try to block most of them manually. Thanks!
