### ISSUE TITLE
events.split.io

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#3094]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

events.split.io

### Why should the domain(s) be unblocked?

Without `events.split.io` https://help.twilio.com/ does not work.

**Comment by hagezi** [comment]
@FadeMind What exactly is not working, how can I reproduce this? I couldn't find any problems during a quick test.
