### ISSUE TITLE
Potential Xiaomi tracker?

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3095]
### Which domain(s) should be blocked?

mqs-log.miui.com

### Why should these domain(s) be blocked?

It's showing up in the logs, but I'm not sure what it is.

**Comment by hagezi** [comment]
Thanks @cOnRiTCh, the domain seems related to logging and possibly telemetry data collection by the MIUI system. I haven't found any more details, but I think it's worth blocking.
