### ISSUE TITLE
Unblock platform.arkhamintelligence.com

### ISSUE THREAD

**Issue by nishaddesilva** [hagezi/dns-blocklists#3098]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

platform.arkhamintelligence.com

### Why should the domain(s) be unblocked?

This is the Arkham Intelligence's blockchain statistics domain.

**Comment by hagezi** [comment]
Thanks @nishaddesilva, the domain has already been removed with release https://github.com/hagezi/dns-blocklists/commit/6d1179ef36f7d41014826b9f3632c4bb86129902
