### ISSUE TITLE
c.tadst.com CDN for timeanddate.com

### ISSUE THREAD

**Issue by fn5** [hagezi/dns-blocklists#3102]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

c.tadst.com

### Why should the domain(s) be unblocked?

This is the CDN for the website https://www.timeanddate.com/

**Comment by hagezi** [comment]
Ping @reverendretro
