### ISSUE TITLE
blocked by mistake 

### ISSUE THREAD

**Issue by looser71** [hagezi/dns-blocklists#3109]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

rutracker.ru
rutracker.net
![IMG_20240709_185131](https://github.com/hagezi/dns-blocklists/assets/156733182/9f4caf6d-d6f3-4ea9-a8fe-225bd52b526e)

### Why should the domain(s) be unblocked?

It's incorrectly marked as porn. It may be present on that website but the whole website is generally trust Worthy for softwares etc.

**Comment by hagezi** [comment]
@looser71 I do not maintain the internal NextDNS lists, you are wrong here. Here would be the right place: https://help.nextdns.io/category/bugs

The domains are not blocked in my lists.

**Comment by looser71** [comment]
> @looser71 I do not maintain the internal NextDNS lists, you are wrong here. Here would be the right place: https://help.nextdns.io/category/bugs
> 
> The domains are not blocked in my lists.

I am so sorry. I didn't thought about that. My bad. Sorry for the inconvenience sir.
