### ISSUE TITLE
track.dhlparcel.co.uk

### ISSUE THREAD

**Issue by nezlobnyj** [hagezi/dns-blocklists#311]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?

Multi Ultimate

#### Which domain(s) should be unblocked?

track.dhlparcel.co.uk

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Legitimate delivery tracking URI for delivery company, used in e.g. eBay messages. Is probably a collateral due to the word "track".

**Comment by hagezi** [comment]
Thanks, removed. Yes, a collateral. ;)
