### ISSUE TITLE
geldmarie.at

### ISSUE THREAD

**Issue by n0w4y** [hagezi/dns-blocklists#3119]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL, Multi PRO

### Which domain(s) should be unblocked?

www.geldmarie.at

### Why should the domain(s) be unblocked?

financial blog

**Comment by hagezi** [comment]
Blocked by CNAME tal1.tripple.at
