### ISSUE TITLE
mijn.overheid.nl


### ISSUE THREAD

**Issue by royvou** [hagezi/dns-blocklists#312]
#### What adblocker/DNS cloud service are you using?
NextDNS

#### Which blocklists are used?
Ultimate 

#### Which domain(s) should be unblocked?
mijn.overheid.nl / overheid.nl

Please note the following should remain blocked. 
statistiek.rijksoverheid.nl

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

It is used by the Dutch government app 'DigId' / 'mijnOverheid' and is not a tracking domain.

**Comment by hagezi** [comment]
Thanks, removed. "statistiek" will be re-added on full update to the wildcard lists.
