### ISSUE TITLE
Mastodon/Fediverse Instances

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#3126]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

dragonscave.space

mstdn.party

shitposter.world

gamedev.place

oldbytes.space

### Why should the domain(s) be unblocked?

Harmless, just some Fediverse/Mastodon instances I came across

**Comment by Retold3202** [comment]
Couple more Mastodon/Fediverse instances I just came across as well:

`mstdn.party`

`shitposter.world`

**Comment by hagezi** [comment]
@Retold3202 If I exclude every Mastodon instance, at some point the `$denyallow` modifiers become too long and I have to remove the entire TLD. I think it is up to the user to allow the required instances.

**Comment by Retold3202** [comment]
@hagezi Ok, that makes sense. I think it may be worth at least allowing `mstdn.party` at least then, since it has ~2K users.

**Comment by Retold3202** [comment]
The others are smaller so I could understand excluding and leaving to the user.

**Comment by hagezi** [comment]
I'll take it as an exclusion as long as it fits, but I think it makes sense to look at the popularity.
