### ISSUE TITLE
Remove bleachernation

### ISSUE THREAD

**Issue by dotshe** [hagezi/dns-blocklists#3129]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Gambling

### Which domain(s) should be unblocked?

https://www.bleachernation.com/

### Why should the domain(s) be unblocked?

This is a sports information website.

Thank you

**Comment by hagezi** [comment]
ping @alsyundawy

**Comment by alsyundawy** [comment]
done
