### ISSUE TITLE
[False Positive] Tipico

### ISSUE THREAD

**Issue by bitstalker** [hagezi/dns-blocklists#313]
#### What adblocker/DNS cloud service are you using?
AdGuard Home

#### Which blocklists are used?

Ultimate

#### Which domain(s) should be unblocked?

sports.tipico.de

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

The site isn't malicious, it's just a sports bookie.

**Comment by hagezi** [comment]
Thanks, removed.
