### ISSUE TITLE
Online Scout Manager

### ISSUE THREAD

**Issue by Nuuki9** [hagezi/dns-blocklists#3131]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

oymcdn.co.uk

### Why should the domain(s) be unblocked?

[Online Scout Manager](https://www.onlinescoutmanager.co.uk/login.php) is a widely used tool in the UK for administering cub and scout groups. Login to the site is broken with the current blocklist. Here's the login page with the domain blocked:

![image](https://github.com/user-attachments/assets/6497751c-6d1c-4004-8a21-eace057ea514)

Here's the login page with the domain unblocked:

<img width="931" alt="image" src="https://github.com/user-attachments/assets/99ca3cbd-fb1e-4c56-845e-8753e6b4387c">

**Comment by hagezi** [comment]
@Nuuki9 oymcdn.co.uk is not blocked in my lists. The login screen looks completely normal to me.

![image](https://github.com/user-attachments/assets/3da9f6af-bc24-443b-9240-9a635db5144d)

Am I missing something?

**Comment by Nuuki9** [comment]
Apologies - I just moved from Light to Pro so I immediately assumed that was the issue. I've gone back and double checked the logs and I see its a newly registered domain and was blocked for that reason., Apologies for wasting your time and keep up the amazing work!
