### ISSUE TITLE
Alves bandeira gás station app ( Portugal )

### ISSUE THREAD

**Issue by maghuro** [hagezi/dns-blocklists#314]
#### What adblocker/DNS cloud service are you using?

Nextdns 

#### Which blocklists are used?
Hagezi pro+

#### Which domain(s) should be unblocked?
mobapi-qero-ab.e-goi.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It's a portyuguese gas station app, it breaks the app if blocked.

**Comment by hagezi** [comment]
Thanks, fixed.
