### ISSUE TITLE
remove  ||staticfile.org^

### ISSUE THREAD

**Issue by xiulou23** [hagezi/dns-blocklists#3144]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

||staticfile.org^

### Why should the domain(s) be unblocked?

When I watched a video on a video site, I couldn't play the video because of the ad filtering rules, and when I tried not to use the rules, the video could play, and I guessed that the rule with the problem was ||staticfile.org^   The Video Website: 
 https://vidhub.tv/vodplay/243158-1-1.html
![image](https://github.com/user-attachments/assets/b5a5c79e-aedb-42c7-8ec2-41def93e62ca)

**Comment by hagezi** [comment]
Related: https://github.com/hagezi/dns-blocklists/issues/3062

https://thehackernews.com/2024/06/over-110000-websites-affected-by.html

Will not be unblocked.
