### ISSUE TITLE
Potential trackers?

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3145]
### Which domain(s) should be blocked?

```
gcpsmapi.vodafone.com
netperform-lz.vodafone.com
api.eu-game-sdk.com
acr.amplreq.com
xboxab.com
consent.trustarc.com
cacerts.geotrust.com
privacy-center.org
a.nel.cloudflare.com
sonar.viously.com
jnn-pa.googleapis.com
logo.clearbit.com
cdn-images.mailchimp.com
gravatar.com
t.indeed.com
indeed.mktoweb.com
stun.services.mozilla.com
clientservices.googleapis.com
firebaseinstallations.googleapis.com
ultimedia.com
t.paypal.com
m.stripe.com
cdn.cookielaw.org
cmp.inmobi.com
```

### Why should these domain(s) be blocked?

They frequently appear in my DNS logs.

I'm not sure if all of them are trackers, if some of them are something else but still worth blocking, or if some of them serve an actual function. So I thought I'd ask you.

Some domains are worth blocking entirely, like `privacy-center.org` and maybe others on the list.

Any ideas?

**Comment by hagezi** [comment]
Just search in the issues and you'll find a few reasons why this and that is not blocked. I have to do that too ...

Reddit, Google, ChatGPT and the like are also a good source.

**Comment by hagezi** [comment]
privacy-center.org and other CMP domains are not blocked in my lists, see https://github.com/hagezi/dns-blocklists/wiki/FAQ#cmps

**Comment by hagezi** [comment]
I don't see anything blockable here.
