### ISSUE TITLE
Allow tl.foxnews.com for Fox News Live

### ISSUE THREAD

**Issue by Fail-Safe** [hagezi/dns-blocklists#3146]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

tl.foxnews.com

### Why should the domain(s) be unblocked?

This domain provides a video feed for Fox News Live. Without this domain unblocked, the Fox News Live page shows just a static video thumbnail.

**Comment by hagezi** [comment]
Please send me a link where I can check this. I have not noticed any problems with the livestream.

![grafik](https://github.com/user-attachments/assets/a8c893c2-aadf-4f60-8213-797309625838)

**Comment by Fail-Safe** [comment]
Hope this helps! I just reproduced the issue on my side.

URL: https://www.foxnews.com/video/5614615980001

```
❯ dig -4 +short tl.foxnews.com
0.0.0.0
```
<img width="266" alt="image" src="https://github.com/user-attachments/assets/3bcccdae-0ce9-49c6-8e45-9cce5d6a0511">

<img width="2168" alt="Screenshot 2024-07-14 at 8 21 33 AM" src="https://github.com/user-attachments/assets/776d6216-c95a-4bb3-8418-4a40463d3566">

After unblocking the domain:
```
❯ dig -4 +short tl.foxnews.com
104.18.174.46
104.17.21.44
```
<img width="2168" alt="Screenshot 2024-07-14 at 8 24 16 AM" src="https://github.com/user-attachments/assets/e90d2e5c-cbf3-404f-99d3-6cfa626839eb">

**Comment by hagezi** [comment]
@Fail-Safe I can't reproduce this, when I click on the play button at the bottom right of your link the video plays normally. Tested with Ultimate. The domain is a `taplytics.com` tracker (CNAME `v3.taplytics.com`).

**Comment by Fail-Safe** [comment]
Well I appreciate the humor, but I assure you it is not working the same way on my side. I can click any part of that image, including the "play button" but it doesn't play unless I go into NextDNS and unblock the domain I listed in this issue.

**Comment by hagezi** [comment]
Then it's something for your personal allowlist.

**Comment by Fail-Safe** [comment]
Could you help me understand how you came about the detail that the domain points to a CNAME record? It appears to be an A record with two IPs returned, both of which are hosted with Cloudflare:

```
; <<>> DiG 9.10.6 <<>> -4 tl.foxnews.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 627
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;tl.foxnews.com.			IN	A

;; ANSWER SECTION:
tl.foxnews.com.		5	IN	A	104.18.174.46
tl.foxnews.com.		5	IN	A	104.17.21.44

;; Query time: 20 msec
```

**Comment by hagezi** [comment]
If you only query IPs, you will not get a CNAME ...

```
dig tl.foxnews.com

; <<>> DiG 9.16.48-Debian <<>> tl.foxnews.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56921
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tl.foxnews.com.                        IN      A

;; ANSWER SECTION:
tl.foxnews.com.         4100    IN      CNAME   v3.taplytics.com.
v3.taplytics.com.       300     IN      A       104.18.174.46
v3.taplytics.com.       300     IN      A       104.17.21.44

;; Query time: 15 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Jul 14 15:09:08 CEST 2024
;; MSG SIZE  rcvd: 102
```

**Comment by hagezi** [comment]
Under Safari it wants me to choose a provider and log in - I can't test this because I don't have an account. I have probably used up the free time. But there is no static video thumbnail here either. When I click on play, it asks me to select the provider and to log in.

Are you logged in when the problem occurs?

And you are definitely not using the NextDNS block page?

**Comment by Fail-Safe** [comment]
> If you only query IPs, you will not get a CNAME ...

Got it--thanks for indulging my curiosity there. Apparently the version of dig I have on my Mac is pretty old (compared to your version) and it doesn't display the CNAME automatically. Though I can query for it explicitly, per your hint.

```
❯ dig -4 CNAME tl.foxnews.com

; <<>> DiG 9.10.6 <<>> -4 CNAME tl.foxnews.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6769
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; CLIENT-SUBNET: 2001:1890:199e::/48/0
;; QUESTION SECTION:
;tl.foxnews.com.			IN	CNAME

;; ANSWER SECTION:
tl.foxnews.com.		5	IN	CNAME	v3.taplytics.com.

;; Query time: 4 msec
```

Anyway, I work in an IT profession, so I really like to know why something isn't behaving as expected--hence my additional curiosities into this issue. This one has me scratching my head, but I will quit taking up your time. I suppose if others have issues, they'll raise them here as well.

> Are you logged in when the problem occurs?

No sir, I also do not have an account.

> And you are definitely not using the NextDNS block page?

Affirmative--I avoid it like the plague. Due to my IT background and curiosity, block pages confound troubleshooting and generally annoy me 😄.

<img width="174" alt="image" src="https://github.com/user-attachments/assets/1163e96b-52d3-4ca0-863c-a9d7d95e1ea6">

**Comment by hagezi** [comment]
@Fail-Safe Maybe you have the possibility to try another browser, of course it can only occur in Safari.

**Comment by Fail-Safe** [comment]
> Maybe you have the possibility to try another browser

I actually tried it in all of the following with the same behavior:
Brave, Safari, DuckDuckGo Browser, and Orion (another Webkit based browser)

However, there is yet another new and odd twist. I have returned `tl.foxnews.com` to its default blocked state within NextDNS and now (even after clearing DNS cache in both OS and browsers) when I visit Fox News Live the video begins to load, but I am now also prompted for choosing a TV provider. So I'm not sure if the video would continue to play even with tl.foxnews.com blocked, assuming I had a valid TV subscription.

I am not sure where to go with it now since I don't have an account (nor TV subscription). I completely understand if you'd like to just close out this issue since I won't be able to troubleshoot it any further without TV subscription credentials.

Either way, I really, really appreciate what you do with your lists, and for engaging with me on this endeavor today. ❤️ 👍🏻

**Comment by hagezi** [comment]
I'll leave the issue open, let's see. I was able to open the link under Safari and the problem doesn't occur for me. I'll surf through the site and see if it occurs at some point, the domain doesn't always seem to be contacted for me either.

**Comment by hagezi** [comment]
@Fail-Safe After wild clicking, I was able to reproduce the problem once, it seems to occur really "randomly". I will allow the domain.
