### ISSUE TITLE
Firefox killed, hosts file locked by DNSClient

### ISSUE THREAD

**Issue by GerryOnGithub** [hagezi/dns-blocklists#3148]
I installed this hosts file on Windows 11

https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/multi.txt

Firefox stopped being able to load any site I clicked. Chrome/Edge okay. I thought maybe it was a Firefox issue, so uninstalled it but could not reinstall. Firefox is not malware and should not be blocked.

DNSClient started using lots of CPU and the hosts file became locked by it. I had to reboot in safe mode to remove the hosts file. My system as 8 Gig of RAM

**Comment by hagezi** [comment]
The host file is too large for Windows.

**Comment by hagezi** [comment]
Or better, use a DNS online service if you don't want to run your own network-wide DNS blocker.

https://github.com/hagezi/dns-blocklists#dnsservices
