### ISSUE TITLE
Admitad - PopAds

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#3149]
### Which domain(s) should be blocked?

www.admitad.com
easypost14.com

### Why should these domain(s) be blocked?

First domain is PopAds Company. Second domain is the subject.

**Comment by hagezi** [comment]
Only subdomains of `admitad.com` are blocked because `ad.admitad.com` was allowed as a referral domain.

**Comment by hagezi** [comment]
ref: https://github.com/hagezi/dns-blocklists/issues/950
