### ISSUE TITLE
youtube live scam crypto

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#315]
#### Which domain(s) should be blocked?
teslahelp.io
tesladrop2x.com
tsla-23.com
x2bytesla.com
teslagive23.net

#### Why should the domain(s) be blocked?
YouTube live crypto scam

**Comment by cinatime** [comment]
see https://github.com/badmojr/1Hosts/issues for more info

**Comment by hagezi** [comment]
Many thanks, added.

ping @durablenapkin

**Comment by durablenapkin** [comment]
Thanks! Will be included in next nightly.
