### ISSUE TITLE
Two more domains

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#3152]
### Which domain(s) should be blocked?

||skan.singular.net^
||anonymised.io^ # In Pro++ but not Pro

### Why should these domain(s) be blocked?

Greetings Gerd / @hagezi, I hope you're well? It's been a while, which is testament to your lists' efficacy and efficiency these days! 

I notice that you block multiple subdomains of `singular.net`, but not the one above that is spamming my logs from various Apple devices lately. It's been blocked on my LAN for a week now, with no known resulting issues. Please consider adding it, or truncating all the existing entries to the root domain? 

Regarding `anonymised.io`: It is blocked in Pro++ but not in Pro. Is there a particular rationale for this? I had been running Pro as I have less time lately, and it 'just works'. However one particular site my wife enjoys spams many subdomains of this tracking/profiling domain. Again, it has now been blocked by custom filter rule to no detriment, but might you consider moving it into Pro also, so I can tidy up my rules and logs? 

Best wishes,

Lee

**Comment by hagezi** [comment]
Thanks Lee, will be adjusted.
