### ISSUE TITLE
FYI: Github Issue - RAW links do not provide the current list versions

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#316]
FYI: 
Currently there seems to be a GitHub problem, the RAW links over which the lists are retrieved do not provide the current list versions, but partly only a cached version from yesterday. 

More info about this at: https://github.com/orgs/community/discussions/46691

To get current list versions, use the GitLab Mirror link from the [README](https://github.com/hagezi/dns-blocklists/blob/main/README.md) or visit the [Mirror](https://hagezi.gitlab.io/mirror/dns-blocklists/)

**Comment by hagezi** [comment]
In the meantime, more lists as RAW links are up to date again, there are still a few lists missing in AdBlock format.

**Comment by hagezi** [comment]
The problems seem to be fixed.

**Comment by hagezi** [comment]
The Github RAW cache issues are back ... :(

**Comment by hagezi** [comment]
[Mirror](https://gitlab.com/hagezi/mirror/-/tree/main/dns-blocklists) - Mirrored files of the block lists on GitLab

**Comment by iam-py-test** [comment]
> [Mirror](https://gitlab.com/hagezi/mirror/-/tree/main/dns-blocklists) - Mirrored files of the block lists on GitLab

GitLab isn't a great option for mirroring lists
https://github.com/uBlockOrigin/uBlock-issues/issues/1285

**Comment by hagezi** [comment]
Thanks @iam-py-test, what do you recommend?

**Comment by hagezi** [comment]
@iam-py-test I have moved the mirror links to GitLab Pages, so the RAW download limit should no longer matter.
Example: https://hagezi.gitlab.io/mirror/dns-blocklists/domains/doh.txt

**Comment by hagezi** [comment]
Update: More and more repositories seem to be affected, the RAW cache is updated for them only every 24 hours instead of - as before - every 5 minutes. 
More info about this at: https://github.com/orgs/community/discussions/46691

**Comment by hagezi** [comment]
Update: Github is working on it: https://github.com/orgs/community/discussions/46691#discussioncomment-4948308

**Comment by hagezi** [comment]
The problems persist, I have now switched from Github RAW links to Github Pages links in the README. These links provide, like the GitLab links, the current version.

**Comment by hagezi** [comment]
Fixed.
