### ISSUE TITLE
Potential Amazon tracker

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3165]
### Which domain(s) should be blocked?

awstrack.me

### Why should these domain(s) be blocked?

This looks like a tracking domain by Amazon and is already blocked by multiple filter lists on NextDNS, including by extensions like uBO and AdGuard.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
This is a referral domain, will bot be blocked.

**Comment by xRuffKez** [comment]
Referral
