### ISSUE TITLE
Potential Tracker?

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3166]
### Which domain(s) should be blocked?

fscdn.eppo.cloud

### Why should these domain(s) be blocked?

It keeps appearing in my logs, even when I'm not doing anything. I searched a bit about it, and it says it's for collecting experimental data and performing A/B testing, etc. but I wanted to report it just to be sure.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
This is something for the aggressive lists, only block them in ultimate for now.
