### ISSUE TITLE
Block li.blogtrottr.com

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#317]
#### Which domain(s) should be blocked?
li.blogtrottr.com

#### Why should the domain(s) be blocked?
ads

li.blogtrottr.com redirect to p.liadm.com 

p.liadm.com is blocked by Peter Lowe’s Ad and tracking server list
 
EasyPrivacy
 
AdGuard Base
 
HaGeZi's Ultimate DNS Blocklist

**Comment by hagezi** [comment]
Many thanks, added.
