### ISSUE TITLE
firebase-auth.vsco.co Blocked by TIF

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3177]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

firebase-auth.vsco.co

### Why should the domain(s) be unblocked?

Not a malicious site

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked by CNAME `vsco-prod.web.app` via @jarelllama Scam list.
