### ISSUE TITLE
fake flipkart prize site

### ISSUE THREAD

**Issue by pokegamer5547** [hagezi/dns-blocklists#3179]
### Which domain(s) should be blocked?

https://tinyurl.com/FlipKart-2593
https://hyndtren25.pages.dev/
https://folkrbvi.pages.dev/
https://alindflepkaty14.pages.dev/

### Why should these domain(s) be blocked?

They are a fake site claiming to be flipkart as providing gifts as it's anniversary sale. They all get redirected to same end domain, but it's better to block all to be safe i guess incase they change the domain name except maybe tinyurl if it's going to be included in hosts entry.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hackpapa762-rgb** [comment]
/

**Comment by pokegamer5547** [comment]
Um, idk if i'm supposed to comment here but, why were these domains (except tinyurl and 4th one cuz i get it) are no longer in lists?
The 2nd and 3rd links are still working and doing fake flipkart gifts thingy.
