### ISSUE TITLE
Unblock twitchytides.io

### ISSUE THREAD

**Issue by TwitchyTides** [hagezi/dns-blocklists#3188]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Pop-Up Ads

### Which domain(s) should be unblocked?

https://www.twitchytides.io

### Why should the domain(s) be unblocked?

This is a website owned by our project, and does not involve any ads or spamware. Please remove from block list and update

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via @jarelllama Scam list, will be removed.
