### ISSUE TITLE
appocalypsis.com: Tracker?

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3201]
### Which domain(s) should be blocked?

appocalypsis.com

### Why should these domain(s) be blocked?

According to a quick search on Perplexity,

"Appocalypsis is a website optimization and conversion rate optimization (CRO) platform that offers various tools and features such as exit-intent popups, opt-ins, countdowns, forms, and inline elements to engage visitors, a large library of customizable templates for different industries and use cases, a workbench to easily customize widgets without any programming skills, the ability to manage multiple widgets across multiple websites, analytics to track widget performance, leads, referrals, countries, cities etc., and integrations with tools like Mailchimp, Slack, Zapier to manage leads."

However, it is unclear from the provided information if Appocalypsis itself acts as a tracker or collects user data. It loads in the background on a few sites, like `protothema.gr`.

Any ideas?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Belongs in the annoyance category. User behaviour is also tracked with the widgets. I have not yet found out which domains are used to receive the tracking data. Are they internal domains of the pages that use the widgets, or does the data end up directly with the widget provider without any detours? I can't find any subdomains for the main domain in top lists.

I'll have to take a closer look at that.

**Comment by hagezi** [comment]
I will block the domain in the aggressive lists, have not found any further details on tracking subdomains, but also do not see any restrictions by blocking the domain.

**Comment by hagezi** [comment]
https://www.appocalypsis.com/opt-out
