### ISSUE TITLE
Potential trackers and/or badware

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3202]
### Which domain(s) should be blocked?

x.grxchange.gr
pahtuo.tech
pahtzc.tech
pahtlf.tech
pahtqo.tech
pahtmb.tech
pahtkm.tech
pahtnf.tech
pahtdz.tech

### Why should these domain(s) be blocked?

The first one is probably a tracker. The others are strange and show up randomly in DNS logs. They might be trackers too, or something worse. HaGeZi's lists already block a few similar ones, such as `pahtpw.tech`, `htagpa.tech`, `paht.tech`, `palibzh.tech`, and more.

For some reason, there are a lot of six-letter domains that end with `.tech`, like the ones mentioned above. What even are these `paht` domains?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Do you have the possibility to find out where these calls come from?

**Comment by hagezi** [comment]
The pah domains seems related to Partner Tech, specializes in providing POS (Point of Sale) solutions.

https://www.partnertechcorp.com

**Comment by hagezi** [comment]
I still have to find out, just a quick look, maybe I'm wrong. I'll have to take a closer look.

Have you blocked the domains and checked whether this has any side effects?

**Comment by hagezi** [comment]
Found on Top1M lists:

pah3ots.tech
paham.tech
pahtag.tech
pahtbt.tech
pahtch.tech
pahtdz.tech
pahtef.tech
pahter.tech
pahtfi.tech
pahtgq.tech
pahthf.tech
pahtkm.tech
pahtky.tech
pahtlf.tech
pahtmb.tech
pahtnf.tech
pahtpw.tech
pahtqo.tech
paht.tech
pahtuo.tech
pahtuz.tech
pahtvs.tech
pahtwt.tech
pahtzc.tech
pahtzh.tech
