### ISSUE TITLE
*.health TLD

### ISSUE THREAD

**Issue by tatchiuleung** [hagezi/dns-blocklists#3203]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

https://sca.health/

### Why should the domain(s) be unblocked?

![image](https://github.com/user-attachments/assets/70616d4e-ae50-4408-a46e-21b27ee44407)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
sca.health will be excluded.
