### ISSUE TITLE
Malicious domains

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3206]
### Which domain(s) should be blocked?

```
185.196.9.251
85.28.47.31
203.232.37.151
inspirepk.org
185.172.128.116
srv019.amt-games.com
id-formulare-ag-login.myz.info
serviweb-ag-dkb.itsaol.com
m-ag-dkb-login-id.itsaol.com
77.91.77.81
se.elof7.za.com
185.196.8.12
https://bitbucket.org/holliwoodip/updater/downloads/BrowserUpdate.exe
176.123.2.229
77.91.77.80
77.91.77.82
77.105.132.27
45.139.198.242
34.72.148.88
57.180.253.244
```

### Why should these domain(s) be blocked?

All these domains serve malware.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The IPs are already blocked in my TIF IP list.

Already blocked in TIF:
```
inspirepk.org
srv019.amt-games.com
id-formulare-ag-login.myz.info
serviweb-ag-dkb.itsaol.com
m-ag-dkb-login-id.itsaol.com
se.elof7.za.com
```

So, nothing to do. Please check in future what is already blocked, it saves me unnecessary work, thank you.
