### ISSUE TITLE
rakuten.ca being blocked by TIF

### ISSUE THREAD

**Issue by sgobiraj** [hagezi/dns-blocklists#3208]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

rakuten.ca

### Why should the domain(s) be unblocked?

They are a deals and coupon platform that is legitimate with an office in Toronto.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Thanks, added to allowlist.

**Comment by iam-py-test** [comment]
This is not a false positive: [Rakuten has users install an overly broad allowlist under the false pretense that it is necessary for the extension to function](https://www.rakuten.ca/help/trouble-shooting#ensurecashbackshopping). This allowlist globally permits connections to many adservers; this behavior is not disclosed on their website, so users will be unaware.
In my opinion, this is deceptive behavior and as such warrants blocking.
That said, I understand that is a controversial opinion, so I understand you may wish to continue allowlisting this service.
Thank you

**Comment by sgobiraj** [comment]
Rakuten owns Viber and I've noticed some weird issues around it when it can't resolve rakuten.
