### ISSUE TITLE
Adblock-lean:  Recommended lists

### ISSUE THREAD

**Issue by Wizballs** [hagezi/dns-blocklists#3212]
Hi Hagezi, I can't tag you directly in the adblock-lean issues.  But wondering if you would be able to take a look at this one for any recommendations, advice etc?

https://github.com/lynxthecat/adblock-lean/issues/43

Thanks!

**Comment by hagezi** [comment]
https://github.com/lynxthecat/adblock-lean/issues/43#issuecomment-2238484696
