### ISSUE TITLE
taboola.com

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#322]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
taboola.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
I understanding blocking there tracking and other domains, but there actual website is just blocked.

**Comment by hagezi** [comment]
Taboola is an international advertising technology company, why shouldn't I block it? Where does it cause restrictions?
