### ISSUE TITLE
shop.espruino.com

### ISSUE THREAD

**Issue by SKBotNL** [hagezi/dns-blocklists#3224]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

shop.espruino.com

### Why should the domain(s) be unblocked?

It is a legitimate shop by the Espruino project that sells devices

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Falsely flagged as a fake shop by watchlist internet.
