### ISSUE TITLE
topcashback.co.uk

### ISSUE THREAD

**Issue by gh3597** [hagezi/dns-blocklists#3229]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

topcashback.co.uk

### Why should the domain(s) be unblocked?

Not sure why it's blocked as it's a legitimate referral site. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
via @iam-py-test anti malware list.

**Comment by hagezi** [comment]
I find no flags and no reason to block it, it is on all Top1M lists and seems to be legit:

https://uk.trustpilot.com/review/www.topcashback.co.uk

https://www.scamadviser.com/check-website/topcashback.co.uk

**Comment by iam-py-test** [comment]
See https://www.reddit.com/r/uBlockOrigin/comments/143k8lm/comment/jnbl4yg/
They used to convince their users to install [a highly invasive allowlist into their content filter](https://www.topcashback.com/Misc/AdBlockWhiteList.aspx), which includes a rule practically allowlisting *everything* (`@@||^*$xmlhttprequest,subdocument,document,script,object,image,stylesheet`). As such, it is a PUP and qualifies for my list.
That said, after installing their extension and looking through their website, it seems they are no longer promoting this list to users, though concerningly they continue to host the list.
I may remove this, but it is not a false positive.
Thank you

**Comment by iam-py-test** [comment]
As they are no longer promoting this list, I have unblocked them in https://github.com/iam-py-test/my_filters_001/commit/44cfddd0dd451dd1ec8306563715eb63ecf6ea4c.
Thanks

**Comment by gh3597** [comment]
> See https://www.reddit.com/r/uBlockOrigin/comments/143k8lm/comment/jnbl4yg/ They used to convince their users to install [a highly invasive allowlist into their content filter](https://www.topcashback.com/Misc/AdBlockWhiteList.aspx), which includes a rule practically allowlisting _everything_ (`@@||^*$xmlhttprequest,subdocument,document,script,object,image,stylesheet`). As such, it is a PUP and qualifies for my list. 

That makes sense. I remember the popup asking for the allowlist to be added but that went away a long time ago, a number of years to my recollection. Even if that was still the case would be useful to be able to still access the main website and the tracking is done via third parties so just block the script?

**Comment by iam-py-test** [comment]
It's hard to know if there was a way to block just the allowlist request, as it is no longer present.
That said, I prefer to take an agressive stance on companies who engage in deceptive practices. Understandably, that's a controversial stance, not everyone may agree with my position.
Thanks
