### ISSUE TITLE
Blocked payment method on lampgallerian.se

### ISSUE THREAD

**Issue by BourbonCrow** [hagezi/dns-blocklists#323]
#### Which blocklists are used?
HaGeZi - Multi PRO

#### Which domain(s) should be unblocked?
secure.adnxs.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
The website https://www.lampgallerian.se/ is using the domain above as a secure payment service or whatever you wanted to call it my mom tried to order a lamp but didnt work to pay so i checked the logs and this was the domain that blocked the payment and i can imagine other swedish sites could use it as well

**Comment by BourbonCrow** [comment]
i did whitelist it my self to confirm and it solved the payment issue, so she can have her lamp now :3

**Comment by BourbonCrow** [comment]
https://imgur.com/a/vD4FqEm

here is a image of the 2 domains that was blocked during the attempt to pay but i only unblocked the adnxs and it worked, after googling for that domain tho i dont find anything positive about it really so im a lil confused

**Comment by nezlobnyj** [comment]
More specifically - https://secure.adnxs.com/seg?add={INTEGER}&t={INTEGER}

This request isn't being sent neither from this website on mobile platform (i.e., iOS 16 and Android 13) nor from country-specific website versions (e.g., https://www.lightshop.com/pl) on desktop.

Also quick lazy search suggests it's used for tracking/fingerprinting as it deploys tracking pixel. VT and alienvault suggest it's clean though.

Not that anyone asked, but I'd keep it blocked globally and leave whitelisting to user.

**Comment by hagezi** [comment]
https://slayterdev.github.io/tracker-radar-wiki/domains/adnxs.com.html

Very wild to use a popular ad motivated tracker as an obligation for a payment process. A bit cheeky. I'm curious to see what the company says when you ask.

Until then, it's definitely something for the personal whitelist. If there are any other restrictions in the payment area, I'll have to bite the bullet and whitelist it for the masses.

**Comment by hagezi** [comment]
Thanks @nezlobnyj I agree with you completely. Let's see what the company responds to the request.

**Comment by BourbonCrow** [comment]
If they reply to me I will post it here gonna be interesting

**Comment by hagezi** [comment]
@BourbonCrow Have you received any feedback?

**Comment by BourbonCrow** [comment]
> @BourbonCrow Have you received any feedback?

oh i wish.. im gonna wait until friday since it was like weekend when i emailed em and most ppl dont work on weekends and if nothing they can .... off :D

**Comment by hagezi** [comment]
Since no one has contacted me, I will close here. If you get any more info, please let me know.
