### ISSUE TITLE
HaGeZi's Gambling Blocklist ||takeaway.com^

### ISSUE THREAD

**Issue by privacy-advo** [hagezi/dns-blocklists#3230]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### With which block list(s) does the problem occur?

Gambling

### Which domain(s) should be unblocked?

||takeaway.com^

### Why should the domain(s) be unblocked?

Required to use lieferando.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Thank you, the domain is already on the Allowlist and will be removed in the current build.
