### ISSUE TITLE
Urgent : Unblock Awit at Papuri Communications

### ISSUE THREAD

**Issue by thedoggybrad** [hagezi/dns-blocklists#3237]
Please unblock Awit at Papuri Comminunications (https://www.awitatpapuri.com/). It is a legitimate website that provides daily holy mass readings in the Filipino language.

Filter Concerned: Pop-up Ads Filter
Type: False Positive

**Comment by thedoggybrad** [comment]
@hagezi Can you give any justifications on blocking this site? or just a false positive?

**Comment by hagezi** [comment]
Flagged as popupads, false positive ...
