### ISSUE TITLE
muskusa.com: Scam

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3241]
### Which domain(s) should be blocked?

muskusa.com

### Why should these domain(s) be blocked?

This is a crypto scam domain that is being advertised by hacked account on various platforms like YouTube.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/3236
