### ISSUE TITLE
Edilnet whitelist

### ISSUE THREAD

**Issue by skariko** [hagezi/dns-blocklists#325]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?

HaGeZi Pro++

#### Which domain(s) should be unblocked?

edilnet.it

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

it's a legittimate website as you can see here: https://www.trustpilot.com/review/www.edilnet.it

**Comment by hagezi** [comment]
Thanks, removed.

ping sources: @marco-acorte @notracking

**Comment by marco-acorte** [comment]
Yeah I will investigate....

**Comment by marco-acorte** [comment]
@hagezi  yes edilnet.it is included in antispam.it dnsblocklist and notified to Abuse desk <abuse@sendinblue.com> (MTA vector)

reason: involved in a massive spam campaign that fall in one of our honeypot.

This spam campaign targeting business info@domain.it  Italian mailboxes.

![image](https://user-images.githubusercontent.com/6375935/218150476-a93454f0-644d-46f5-a3b9-a9e8a2e181fd.png)

**Comment by hagezi** [comment]
Thanks @marco-acorte

**Comment by notracking** [comment]
Thanks!
