### ISSUE TITLE
Some genius decided to blanket ban: *.blob.core.windows.net

### ISSUE THREAD

**Issue by Gyarbij** [hagezi/dns-blocklists#3254]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

*.blob.core.windows.net

### Why should the domain(s) be unblocked?

Because you're blocking every single blob storage container on Azure. You know the equivalent of s3.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@Gyarbij 

Not blocked in the normal lists.

`*.blob.core.windows.net` is only blocked in badware hoster, actually to catch all malicious subdomains. a lot of badware is distributed via this and a lot of phishing/scam via `*.web.core.windows.net`.

**Comment by Gyarbij** [comment]
Thank you @hagezi and apologies if I came off a bit rude, it was early in the morning of me trying to figure out what spectacular new way Azure had found to crap bed so it was a bit of relief mixed with frustration.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/3254
