### ISSUE TITLE
gsas.apple.com: Transmitting handset identifiers (IMEI, the SIM serial number etc.)

### ISSUE THREAD

**Issue by OrkoGrayskull** [hagezi/dns-blocklists#3255]
### Which domain(s) should be blocked?

gsas.apple.com

### Why should these domain(s) be blocked?

When the iPhone is left idle, roughly every 2-3 days it sends data to gsas.apple.com/grandslam:

```
POST https://gsas.apple.com/grandslam/GsService2/postdata
Headers
User-Agent: akd/1.0 CFNetwork/1128.0.1 Darwin/19.6.0
X-Apple-I-UrlSwitch-Info: MDAxMDI5LTA...GF0YQ== //
x-apple-adsid base64 encoded
X-Apple-HB-Token: MDAxMDI5LTA1LTk...5XN3dnPT0= //
x-apple-adsid base64 encoded
X-Mme-Device-Id: 7c2694081d...71412dc5bc5 //UDID
X-Apple-I-MD-RINFO: 17106176
X-Apple-I-SRL-NO: C8PVCB1HJC67 //Handset hardware serial
number
X-Apple-I-MD-M: 5ekJNohU...YjL2Z //Anisette machineID11
X-Apple-I-MD: AAAABQAA...AAAAw==
POST body
<...>
<key>iccid</key>
<string>8935311180135555145</string> // SIM
Integrated Circuit Card Identifier
<key>imei</key>
<string>356765081821496</string> //Handset IMEI
<...> <key>number</key>
<string>+35389...97590</string> //
Handset phone number
<...> <key>pn</key>
<string>+35389...97590</string>
<...> <key>ptkn</key>
<string>7534B939D....6E2750CB0FD0</string>
<...> <key>sn</key>
<string>C8PVCB1HJC67</string> //Handset hardware
serial number
<...>
```

It can be seen that this message sends (and links together) many handset identifiers including: the handset hardware serial number, the handset UDID, the IMEI, the SIM serial number, the handset phone number, the Apple advertising ID plus the X-Apple-I-MD-M security token/anisette machine identifier.

Source: https://www.scss.tcd.ie/doug.leith/apple_google.pdf (site 7).

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@Retold3202 Can you provide assistance here?

**Comment by OrkoGrayskull** [comment]
FYI: Maybe more domains can be blocked: https://www.kuketz-blog.de/ios-17-von-einem-iphone-kontaktierte-domains/

**Comment by hagezi** [comment]
Difficult to find out what the domain is actually used for and how it is triggered.

`gsas.apple.com` domain is associated with the [Apple ID](https://www.netify.ai/resources/applications/apple-id) application
https://www.netify.ai/resources/domains/gsas.apple.com

**Comment by hagezi** [comment]
This is what AI says:

The domain gsas.apple.com is used by Apple Inc. for services related to device activation and authentication. Specifically, GSAS stands for "Global Service Activation System." It is involved in processes such as:

- Device Activation: When you set up a new Apple device, gsas.apple.com helps to activate it by verifying the device's eligibility and configuration.
- Authentication: It handles authentication requests to ensure that devices are correctly associated with user accounts and Apple services.
- Verification: The system verifies the device's serial number, checks for any activation lock, and confirms that the device is not reported as lost or stolen.

This system is integral to ensuring that Apple devices are securely activated and authenticated, providing a seamless and secure experience for users.

**Comment by hagezi** [comment]
@OrkoGrayskull I asked an acquaintance who is responsible for managed Apple devices in a company and he more or less confirmed what the AI said. So it's not a good idea to block it.

**Comment by mattcheau** [comment]
@celenityy:
> So it's likely that `gsas.apple.com` provides similar functionality to `gsa.apple.com` & is related here. Probably not safe to block.

Then what reason would Apple have not to document it the same way? Forgot? Or`gsas.apple.com`, in fact, should not be accessible by devices connected to so-called 'enterprise networks'? 🤔

**Comment by celenityy** [comment]
@mattcheau 

> Then what reason would Apple have not to document it the same way? Forgot? Or`gsas.apple.com`, in fact, should not be accessible by devices connected to so-called 'enterprise networks'? 🤔

They probably just forgot. I just looked this up again though and I'm now even more certain than I was before that we shouldn't block this...

See [here](https://github.com/MathewYaldo/Apple-GSA-Protocol/). It looks like this is part of Apple's `GrandSlam Authentication` protocol. For reference, the specific endpoint referenced on that GitHub repo is `https://gsa.apple.com/grandslam/GsService2`, which is identical to the endpoint that @OrkoGrayskull reported *(`https://gsas.apple.com/grandslam/GsService2/postdata`)*, minus the `s`. It looks like GSA is just used for Apple ID activation, so I don't see a reason to block it.

**Comment by mattcheau** [comment]
@celenityy I appreciate your reply very much. Not only do I agree with your conclusion as to what type of service this URL likely points to—but also, further reading led me down a rabbit hole of Secure Remote Password ([SRP](http://srp.stanford.edu/)) and password-authenticated key agreement ([PAKE](https://en.wikipedia.org/wiki/Password-authenticated_key_agreement)) protocols.

It also jibes with anecdotal experience on my own Apple devices wherein, with the domain `gsas.apple.com` blocked, I'm constantly prompted to re-authenticate my Apple Account from within Settings.
