### ISSUE TITLE
Phishing domains

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3259]
### Which domain(s) should be blocked?

onenightchicko.com
singleflirt.com
casualdating1.com
info-flirt me.com
info-milfroom.com

### Why should these domain(s) be blocked?

These domains are phishing and scams.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by durablenapkin** [comment]
> info-flirt me.com

Could you please confirm this domain?
