### ISSUE TITLE
BestBuy.com Login Error

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#326]
#### What adblocker/DNS cloud service are you using?

NextDNS with Block Page and CNAME flattening disabled

#### Which blocklists are used?
HaGeZi's Pro DNS Blocklist
HaGeZi's Pro++ DNS Blocklist
HaGeZi's Ultimate DNS Blocklist

#### Which domain(s) should be unblocked?
tmx.bestbuy.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking this domain causes bestbuy.com to display and error message after entering account credentials stating credentials are incorrect. Best Buy would then force me to reset my password, my new password would display the same message. Only after unblocking `tmx.bestbuy.com` was I able to login without the issue.

**Comment by hagezi** [comment]
Thanks, removed.
