### ISSUE TITLE
Brave Domains

### ISSUE THREAD

**Issue by Retold3202** [hagezi/dns-blocklists#3261]
### Which domain(s) should be blocked?

metrics.brave.software
p2a.brave.software
p3a-creative.bravesoftware.com
rewards-stg.bravesoftware.com
star-randsrv.bsg.brave.com
star-randsrv.bsg.brave.software
star-randsrv.bsg.bravesoftware.com

### Why should these domain(s) be blocked?

`metrics.brave.software` - Similar to `metrics.brave.com` & `metrics.bravesoftware.com`, used for browser telemetry.

`p2a.brave.software` - Similar to `p2a.brave.com`, part of Brave's P3A Analytics/Telemetry.

`p3a-creative.bravesoftware.com` - Similar to `p3a-creative.brave.com`, part of Brave's P3A Analytics/Telemetry.

`rewards-stg.bravesoftware.com` - Similar to `rewards.brave.com` & `rewards.brave.software`, part of Brave Rewards.

`star-randsrv.bsg.brave.com` - Part of Brave's P3A Analytics/Telemetry, can be seen ex. [here](https://fossies.org/linux/www/brave-core-1.67.134.tar.gz:b/brave-core-1.67.134/browser/net/brave_network_audit_allowed_lists.h?m=b). Details from Brave also [here](https://brave.com/privacy-updates/19-star/).

`star-randsrv.bsg.brave.software` - Same as above.

`star-randsrv.bsg.bravesoftware.com` - Same as above.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Thanks @Retold3202
