### ISSUE TITLE
Allow steamcloudsaopaulo.blob.core.windows.net

### ISSUE THREAD

**Issue by gtollini** [hagezi/dns-blocklists#3265]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster

### Which domain(s) should be unblocked?

steamcloudsaopaulo.blob.core.windows.net

### Why should the domain(s) be unblocked?

It is the legitimate cloud storage for steam (or one of the ones available in LATAM). I couldn't sync my save files until I manually allow-listed this domain. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/3254
