### ISSUE TITLE
Zepp Analytics

### ISSUE THREAD

**Issue by Skrriply** [hagezi/dns-blocklists#3268]
### Which domain(s) should be blocked?

app-analytics.zepp.com
api-analytics.zepp.com
app-analytics-sg.zepp.com
api-analytics-cn.zepp.com
app-analytics-us.zepp.com
api-analytics-us.zepp.com
app-analytics-us3.zepp.com
api-analytics-us3.zepp.com
api-analytics-cn3.zepp.com
app-analytics-de.zepp.com
app-analytics-ru.zepp.com

### Why should these domain(s) be blocked?

Unfortunately, I didn't find specific information about these domains, but I think they are related to [this](https://www.zepp.com/data-analytics).

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked in Ultimate, will also block them in the other lists.
