### ISSUE TITLE
Whitelist ksn-stat-geo.kaspersky-labs.com

### ISSUE THREAD

**Issue by nishaddesilva** [hagezi/dns-blocklists#327]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
ksn-stat-geo.kaspersky-labs.com ( kaspersky-labs.com )

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Kaspersky domain

**Comment by hagezi** [comment]
Thanks, what are the functional limitations of blocking?

**Comment by nishaddesilva** [comment]
Not really sure, maybe related to Kaspersky Cloud connections or updates...

**Comment by hagezi** [comment]
If you find a traceable restriction, I will remove the domain. It seems to be a geo tracker.
