### ISSUE TITLE
Allow web.diagnostic.networking.aws.dev

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#3272]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

web.diagnostic.networking.aws.dev

### Why should the domain(s) be unblocked?

Echo Dot devices report in the Alexa App they aren’t connected to the internet, despite being online and having a working internet connection visible in the App.  

Occasionally it leads to devices responding with “device not connected to internet please reboot router etc etc” then immediately working after without being rebooted. 

This seems to be referenced here: https://github.com/hagezi/dns-blocklists/issues/2867#issuecomment-2156758173

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
I cannot reproduce or confirm this.

**Comment by Dynamic5912** [comment]
Update - the domain was being requested from the devices every 5 minutes (to the _exact_ second) for each affected device.

Allowing the domain to resolve then stopped the domain being queried further and the devices are no longer reporting as having no internet connection in the App. 

So it looks like this domain is definitely required to confirm device connectivity and therefore should not be blocked. 

I don't believe it to be doing any other telemetry as my other Amazon devices have not queried the domain for a **long time** and have had no reported connectivity issues like these other devices.

**Comment by Dynamic5912** [comment]
> I cannot reproduce or confirm this. 

I posted an update above. Allowing the domain fixed the issues.

**Comment by hagezi** [comment]
I'll unblock the domain and look at it again in detail when I have time.

**Comment by hagezi** [comment]
That's really weird, I've had it blocked on my network for ages and have never had any problems with Alexa or FireTV.

**Comment by Dynamic5912** [comment]
> That's really weird, I've had it blocked on my network for ages and have never had any problems with Alexa or FireTV.

Strange. It only seems to be doing on the "older" style Echo Dots (the flatter ones with the fabric material) - the newer "round" Echo Dots and normal Echo's don't seem to have the issue.

**Comment by hagezi** [comment]
I should still have one of the old ones, I'll test it in the days when I find it. :)

**Comment by Dynamic5912** [comment]
> I should still have one of the old ones, I'll test it in the days when I find it. :)

OK great. It's the 3rd Gen ones that seem to be problematic.

I have a 1st/2nd Gen one kicking around in a cupboard somewhere but I don't use it anymore.

4th Gen and onward seem to be OK as well as the normal "full-sized" Echo's.

**Comment by hagezi** [comment]
Blocked:

```
crash-analysis.mozilla.com
crash-reports-xpsp2.mozilla.com
crash-reports-xpsp2s.mozilla.com
crash-reports.allizom.org
crash-reports.build.mozilla.org
crash-reports.maven.mozilla.org
crash-reports.mozilla.com
crash-reports.nightly.mozilla.org
crash-reports.security.mozilla.org
crash-reports.stage.mozilla.com
crash-stacks.mozilla.com
crash-stats-dev.allizom.org
crash-stats-django.allizom.org
crash-stats-django.mozilla.org
crash-stats-new-dev.allizom.org
crash-stats.allizom.org
crash-stats.mozilla.com
crash-stats.mozilla.org
crash-stats.stage.mozilla.com
crash.addons.mozilla.org
crash.mozilla.com
crash.planet.mozilla.org
crash.reporting.build.mozilla.org
crash.reporting.mozilla.org
crash.reporting.planet.mozilla.org
crash.reporting.svn.mozilla.org
crash.services.mozilla.com
crash.svn.mozilla.org
crash.vpn.mozilla.org
crashplan.addons.mozilla.org
crashplan.planet.mozilla.org
crashplan.svn.mozilla.org
crashplan.vpn.mozilla.org
crashstats.mozilla.com
```

CNAMES:
```
socorro.nonprod.webservices.mozgcp.net
socorro.prod.webservices.mozgcp.net
```

**Comment by hagezi** [comment]
I have the old Echo in operation and can confirm the behavior.

**Comment by Dynamic5912** [comment]
> I have the old Echo in operation and can confirm the behavior.

You're getting the same "not connected to internet" in the app?

And the device red lighting and saying it can't connect?

**Comment by hagezi** [comment]
The red ring and the novel about what I should restart. I haven't looked at the app. However, the problem solved itself after a while because the Echo rebooted on its own. :)

**Comment by Dynamic5912** [comment]
> The red ring and the novel about what I should restart. I haven't looked at the app. However, the problem solved itself after a while because the Echo rebooted on its own. :)

Interesting. Could have been a software update that caused the self-reboot (especially if it's been shelved for a while) :)

**Comment by hagezi** [comment]
Yes, the Amazon devices are a miracle of technology, they can do a software update without the Internet. :)
The device has been running since the self-healing process. Let's see if and when I come across the red ring again. It is shown as online in the app.
