### ISSUE TITLE
I use your DNS after the video site can't play

### ISSUE THREAD

**Issue by xiulou23** [hagezi/dns-blocklists#3273]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

Then you can't play videos on Bilibili, which is a video site in China, similar to YouTube, not a dangerous site, and so on  .Bilibili's website address is:  https://www.bilibili.com/  Hope to fix it soon. I don't know if this problem will also occur with DNS that uses other filtering rules, I haven't tried other DNS, and if there is also this problem, it will be solved by the way, thank you very much.

### Why should the domain(s) be unblocked?

After entering the Bilibili website, you can choose a video at random, and you will find that it has been loading, so I think it was blocked by mistake
![image](https://github.com/user-attachments/assets/60bd520d-ce40-430b-9ba0-ea44d801e820)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Can't reproduce on mobile:

![image](https://github.com/user-attachments/assets/82c6226e-cb39-44ad-af93-f956aa5e96dc)

**Comment by xiulou23** [comment]
> Can't reproduce on mobile:
> 
> ![image](https://private-user-images.githubusercontent.com/104343908/352002098-82c6226e-cb39-44ad-af93-f956aa5e96dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTIyMTgsIm5iZiI6MTcyMTg5MTkxOCwicGF0aCI6Ii8xMDQzNDM5MDgvMzUyMDAyMDk4LTgyYzYyMjZlLWNiMzktNDRhZC1hZjkzLWY5NTZhYTVlOTZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNzE4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjNjZDg5MWU2MTI0Y2QwNThiMWJjY2Y4OWE1NDNlOWY3NTI4NDhhYWM4YzVlN2U0YWZkOTU4NzViNzVlMGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nae6TsxoHfkuu3HTE9pWu26ILvsR-SkcLEMCPvSmYCs)

Now there is no problem.,I guess the problem appears on the browser.,I use the librewolf browser.,It should be the browser's own settings that can't play.,I've been able to play videos after switching to the Firefox browser.
