### ISSUE TITLE
trust-provider.com

### ISSUE THREAD

**Issue by kzshantonu** [hagezi/dns-blocklists#328]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
trust-provider.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
needed to request certs from zerossl CA `acme.zerossl.com`

**Comment by hagezi** [comment]
Thanks, removed.

ping source: yokoffing
