### ISSUE TITLE
 incorrectly blocked

### ISSUE THREAD

**Issue by residentcode** [hagezi/dns-blocklists#3280]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

alexhost.com

### Why should the domain(s) be unblocked?

it is safe website, Im using it for years.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@scafroglia93
