### ISSUE TITLE
OPNsense support clarification

### ISSUE THREAD

**Issue by kasper93** [hagezi/dns-blocklists#3283]
"Should be used for" column include OPNsense for `Wildcard Asterisk`, but I don't think it works as you expect it does.

`*.0-02.net` will not match `0-02.net`, which is expected result.

**Comment by hagezi** [comment]
According to users who have tested this, it should work in OPNsense. I have not tested it myself.

**Comment by kasper93** [comment]
Ok, apparently it was PEBKAC.
