### ISSUE TITLE
Issue with "shopee" app

### ISSUE THREAD

**Issue by edwinlimkh** [hagezi/dns-blocklists#3287]
Hi, there seems to be "something" within all your list that is prevent the "shopee" app from loading properly. it was alright 2 days ago. 

Pls assist.

**Comment by hagezi** [comment]
Have you looked at the log?

I can't test it myself, I asked for help in the community. But you should provide more details, such as platform, region, link to the app ...

**Comment by hagezi** [comment]
@MagicalAlchemist

**Comment by MagicalAlchemist** [comment]
To be honest, if your shopee app doesnt work properly, than blame your isp most of the time.
![Screenshot_20240727_114555_Shopee](https://github.com/user-attachments/assets/051b3060-57c2-421d-94b6-a42b2213c121)

Recently checked, it's not hagezi fault.

**Comment by edwinlimkh** [comment]
> To be honest, if your shopee app doesnt work properly, than blame your isp most of the time. ![Screenshot_20240727_114555_Shopee](https://private-user-images.githubusercontent.com/69599160/352699030-051b3060-57c2-421d-94b6-a42b2213c121.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTk5ODAsIm5iZiI6MTcyMjA1OTY4MCwicGF0aCI6Ii82OTU5OTE2MC8zNTI2OTkwMzAtMDUxYjMwNjAtNTdjMi00MjFkLTk0YjYtYTQyYjIyMTNjMTIxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA1NTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMDViOWYyYzM3NzY5NGM0MTI3YTJkMzkxZTRjM2Q1MzhiNGIzNjRkZmQxYjcyYmY4ZjMxMzdjODlkOTI2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hr6i3blzi820BauDyo5V4mfFPtTx9rkyDi7a6qfHEVw)
> 
> Recently checked, it's not hagezi fault.

![Screenshot_20240727_135414_Shopee SG](https://github.com/user-attachments/assets/aee2dcab-27c8-4232-89ed-d1612069aafe)

it's not the ISP!!!

I toggled between wifi and 5G. Both same issue. When I disable my DNS or change to a different block list(adguard/easylist/oisd/easylist etc), it can LOAD. 

I have been using Hagezi for the past few months, no issue at all. Thus, this only occurred 2 days back.

**Comment by MagicalAlchemist** [comment]
Than share your log dns query related to shopee because is necessery, than we can solve and know what causes the problem. Without your dns query data, this will useless and you should provide more details, such as platform, region, link to the app like hagezi said.

**Comment by edwinlimkh** [comment]
I found it.... 

this caused the problem:

down-spe-sg.img.susercontent.com

when I allowed it.... the app load as per normal.

**Comment by edwinlimkh** [comment]
Before:

![Screenshot_20240727_142219_Chrome](https://github.com/user-attachments/assets/83647aca-0b5f-4854-8cdb-4de0fe74b5d8)


after allow the link:

![Screenshot_20240727_142142_Chrome](https://github.com/user-attachments/assets/09248271-bcc3-4d9a-83d0-b983794b2831)

**Comment by edwinlimkh** [comment]
![Screenshot_20240727_143122_Chrome](https://github.com/user-attachments/assets/6c70ccec-b37b-4894-b897-f738a98cc862)

**Comment by edwinlimkh** [comment]
it's that consider a false positive?!

**Comment by xRuffKez** [comment]
> it's that consider a false positive?!

Yes it is, it got removed.
