### ISSUE TITLE
Netflix household bypass

### ISSUE THREAD

**Issue by retta1** [hagezi/dns-blocklists#3288]
### Which domain(s) should be blocked?

android.prod.cloud.netflix.com
ios.prod.cloud.netflix.com
web.prod.cloud.netflix.com

### Why should these domain(s) be blocked?

to bypass household problem 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
This breaks Netflix ...

**Comment by retta1** [comment]
i tried them and it get rids of household thing

**Comment by retta1** [comment]
edited now works perfectly

**Comment by retta1** [comment]
@hagezi

**Comment by hagezi** [comment]
I fear that this will lead to restrictions elsewhere. I can't test this myself at the moment, so it would be good if others could test it.

**Comment by xRuffKez** [comment]
Contains sign in/up scripts. If you are signed into netflix, yes it can bypass household restriction.
If blocked and you want to sign in/up you won't be successful.

Check it out yourself.

**Comment by hagezi** [comment]
If it prevents login and registration, it's something for the personal denylist. It was somehow clear that more functionalities are attached to the domains - it makes sense.

**Comment by hagezi** [comment]
There are reports that the login is not affected. @retta1 @AleIlMagno can you test whether the logoff/login still works?

**Comment by hagezi** [comment]
I was just able to test this on an iPad, after logging out a login is not possible if `ios.prod.cloud.netflix.com` is blocked. Same on AppleTV if `tvos.prod.cloud.netflix.com` is blocked.

**Comment by djibe** [comment]
This definitely breaks Netflix.

**Comment by yashveerkc** [comment]
@retta1 

hmmmmm  

![Image](https://github.com/user-attachments/assets/0dac7a88-fd66-49b2-91b5-b61c86507bda)


Then this AMAZING thing happens  captured even with their NetflixId cookies too even if it says Incorrect password , but cookies editor Yay! 

![Image](https://github.com/user-attachments/assets/1b94e7aa-4539-4634-bef5-68f2e29fe0ba)

Anyway  this is for research purposes lmao
don't bother msg me . 

GG

**Comment by xRuffKez** [comment]
@yashveerkc are these your household members?

**Comment by YashvirGaming** [comment]
@hagezi  stop lying man 

> I was just able to test this on an iPad, after logging out a login is not possible if `ios.prod.cloud.netflix.com` is blocked. Same on AppleTV if `tvos.prod.cloud.netflix.com` is blocked. It therefore prevents you from logging in.

**Comment by YashvirGaming** [comment]
@hagezi if that API stopped then what is this 
can you explain how tf was i able to get over 63 hits here 

<img width="510" height="506" alt="Image" src="https://github.com/user-attachments/assets/5fe4d7bc-e20f-43f2-bc05-88e591064bd0" />

**Comment by TikaToka** [comment]
Hi everyone, does anyone know the dns for Android TV? It seems like `android.prod.cloud.netflix.com` is invalid for TV

**Comment by ghost** [comment]
@TikaToka 

```
{
  "Metadata": {
    "NameServer": "dnsbunker.org (152.53.144.65)",
    "Protocol": "Udp",
    "DatagramSize": "269 bytes",
    "RoundTripTime": "4,62 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "Identifier": 0,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 6,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "android.prod.cloud.netflix.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "android.prod.cloud.netflix.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "288 (4m48s)",
      "RDLENGTH": "22 bytes",
      "RDATA": {
        "Domain": "android.prod.dradis.netflix.com"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "android.prod.dradis.netflix.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "48 (48s)",
      "RDLENGTH": "34 bytes",
      "RDATA": {
        "Domain": "android.prod.eu-west-1.internal.dradis.netflix.com"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "android.prod.eu-west-1.internal.dradis.netflix.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "48 (48s)",
      "RDLENGTH": "70 bytes",
      "RDATA": {
        "Domain": "apiproxy-device-prod-nlb-4-f1dce6fa09ac5989.elb.eu-west-1.amazonaws.com"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "apiproxy-device-prod-nlb-4-f1dce6fa09ac5989.elb.eu-west-1.amazonaws.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "60 (1m)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "54.246.59.141"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "apiproxy-device-prod-nlb-4-f1dce6fa09ac5989.elb.eu-west-1.amazonaws.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "60 (1m)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "34.252.42.104"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "apiproxy-device-prod-nlb-4-f1dce6fa09ac5989.elb.eu-west-1.amazonaws.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "60 (1m)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "46.137.170.241"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "1232",
      "TTL": "0 (0s)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

**Comment by TikaToka** [comment]
@xRuffKez Thank you for the reply!
It seems like the results indicates `android.prod.cloud.netflix.com` is corrent. I should double check my setting..... Thanks

**Comment by YashvirGaming** [comment]
@TikaToka  rename the .cloud to http1 

example:  tvos.prod.cloud to tvos.prod.http1.netflix.com/graphql  for the POST Login API 
same applied for android.prod.cloud to android . prod . http1 /graphql

Also do you EVEN know there is **### itunes.prod.cloud**  too 

ios.
itunes.
tvos.
android.
playstation 
xbox 


There are many if you can find it or ask AI nowadays its all about asking premium GPT~5 etc etc LOL

_`Use Burp or Fiddler and you will be able to see the Request headers for iOS Netflix app (Sniff IOS APP Traffic) or from Android its called SSL Unpinning traffic bypasser .....  but you might need to DECODE  / DECRYPT  the PAYLOAD thats easy too`_

**Comment by TikaToka** [comment]
@YashvirGaming Thanks! I'll give it a try soon.

**Comment by Chirag-Jamariya** [comment]
I am getting an issue with the web.prod.cloud.netflix.com  it i now my search doesn't work and preview also doesn't work

**Comment by YashvirGaming** [comment]
@Chirag-Jamariya  its proof brother what more do you need ?
Live proof , well many of my telegram members approved my sh*t , they say it works the CONFIG android version TLS

<img width="499" height="627" alt="Image" src="https://github.com/user-attachments/assets/66fc8645-1598-44d6-80dd-a1c3743a0d6c" />

<img width="828" height="599" alt="Image" src="https://github.com/user-attachments/assets/9f47a1a1-49da-48c1-bbf9-15945478017e" />

**Well i did POST the config publicly on my Telegram group**
<img width="477" height="516" alt="Image" src="https://github.com/user-attachments/assets/15526918-dd98-4de3-a613-5a4715ee92d9" />


Well can't link the group here directly ,  im sure the AUTHOR will remove any outsider links especially telegram links LMAO

QR CODE is better than nothing i guess.... 

<img width="378" height="482" alt="Image" src="https://github.com/user-attachments/assets/d698004e-a84b-4091-ac34-b5606a74412e" />

**Comment by ShubuYeole** [comment]
> [@Chirag-Jamariya](https://github.com/Chirag-Jamariya) its proof brother what more do you need ? Live proof , well many of my telegram members approved my sh*t , they say it works the CONFIG android version TLS
> 
> <img alt="Image" width="499" height="627" src="https://private-user-images.githubusercontent.com/64865096/491296157-66fc8645-1598-44d6-80dd-a1c3743a0d6c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA5MzM5NTcsIm5iZiI6MTc2MDkzMzY1NywicGF0aCI6Ii82NDg2NTA5Ni80OTEyOTYxNTctNjZmYzg2NDUtMTU5OC00NGQ2LTgwZGQtYTFjMzc0M2EwZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIwVDA0MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NTYzN2QwODlhNTQxZGI1MWJhNmQ5YjdjZGJlMzdjZTc4Nzc2ZjU5ZTRhZDEzMDI2NWQ2ZjU5ODU5NTFjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.COQErouLGy2MQ4JTX5Cu3_HMyXZvkUi-Ei8maNeSkso"> <img alt="Image" width="828" height="599" src="https://private-user-images.githubusercontent.com/64865096/491296486-9f47a1a1-49da-48c1-bbf9-15945478017e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA5MzM5NTcsIm5iZiI6MTc2MDkzMzY1NywicGF0aCI6Ii82NDg2NTA5Ni80OTEyOTY0ODYtOWY0N2ExYTEtNDlkYS00OGMxLWJiZjktMTU5NDU0NzgwMTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIwVDA0MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNzhjNDU3OTU1MjhjMzkwZjViODg3OGQ2MjZlMjY4NWJhY2U5NDMzNWM2OWY2ZDVkOTAxMTNhOGFhNzQzNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u2ttfoQ2Ttd5eN8obzrh2D5A1hx2DsAmsBTDiJ-7dRc">
> **Well i did POST the config publicly on my Telegram group** <img alt="Image" width="477" height="516" src="https://private-user-images.githubusercontent.com/64865096/491296685-15526918-dd98-4de3-a613-5a4715ee92d9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA5MzM5NTcsIm5iZiI6MTc2MDkzMzY1NywicGF0aCI6Ii82NDg2NTA5Ni80OTEyOTY2ODUtMTU1MjY5MTgtZGQ5OC00ZGUzLWE2MTMtNWE0NzE1ZWU5MmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIwVDA0MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NWIxNGU2YjU3NjIzYzUyYWU5OWRhYzEwZGFlMWNlY2NiZGEwY2JiMmRiMDAxZmIwNmZjYjFiZGNiYmY3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XfSLU2FafvT4inGiXhGTgbRj-56flXYx6VX6dIihNHw">
> 
> Well can't link the group here directly , im sure the AUTHOR will remove any outsider links especially telegram links LMAO
> 
> QR CODE is better than nothing i guess....
> 
> <img alt="Image" width="378" height="482" src="https://private-user-images.githubusercontent.com/64865096/491299450-d698004e-a84b-4091-ac34-b5606a74412e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA5MzM5NTcsIm5iZiI6MTc2MDkzMzY1NywicGF0aCI6Ii82NDg2NTA5Ni80OTEyOTk0NTAtZDY5ODAwNGUtYTg0Yi00MDkxLWFjMzQtYjU2MDZhNzQ0MTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIwVDA0MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlM2MxM2JkYmVlMWJiOWQ5NzkxZTc0ODNjNTUxNDkyYjUyMWI2Zjk4ODU2YWUwNDljOTQ3YmM4NGRlM2I0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o7-J981Q_mj3aFgzKQFlImkd6BKybQtxFlmBV6FhOvc">

can you please accept my request to join the group.
