### ISSUE TITLE
Strange behavior - Pi-hole and Native Tracker (Amazon)

### ISSUE THREAD

**Issue by AS98765** [hagezi/dns-blocklists#3289]
The Adblock link (should be the right one, right?) shows “Number of domains on this list: 0” in the Pi-hole. But adds about 350 domains to the standard StevenBlack (Unified hosts) list.

The Domains link (test) shows “Number of domains on this list: 584” in the Pi-hole. Adds about 540 domains to the standard StevenBlack list.

The Host link behaves exactly the same as the Domains link.

![Screenshot 2024-07-27 083858 - m](https://github.com/user-attachments/assets/cf6a29d0-e744-4ff6-b3a1-f31854d59cb9)

**Comment by hagezi** [comment]
This is a known bug in Pi- hole. This is only a display error and affects lists in adblock format. It has no effect whatsoever.
