### ISSUE TITLE
Ghostery analytic domains

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#329]
#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
```
collector-hpn.ghostery.net
d.ghostery.com
collector-hpn.privacy.ghostery.net
```

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Their analytics are now **[opt-in](https://www.ghostery.com/faq#if-i-opted-in-to-share-my-data-with-the-ghostery-extension-is-that-data-connected-with-my-account)** by default. So the only time a user will contact those domains is if they *want* to give Ghostery user data (that is then anonymized).

`ghosterystore.com` is phishing/malicious AFAIK and **should** stay blocked. I will update you if it turns out otherwise.

**Comment by hagezi** [comment]
I don't really understand why I would whitelist these, whether opt-in or not. I can't imagine why users would want to share data, even if it is supposedly anonymized, especially in the more aggressive lists.

**Comment by yokoffing** [comment]
> I can't imagine why users would want to share data ... especially in the more aggressive lists

Those who want to contribute useful analytics to the devs, hence opt-in.

I see both sides. I just want to make you aware that these domains would only be called if a user intentionally chooses to contribute to their analytics. I believe they're used to contribute to the [WhoTracks.me](https://whotracks.me/trackers.html) database, gain passive feedback for their web extension, monitor for breakage, etc.

I can get you a more definitive answer in a few days, most likely.

**Comment by hagezi** [comment]
I understand your point of view, however, I have a bad feeling about Ghostery because of rumors from the past.

**Comment by durablenapkin** [comment]
I also see both sides and yokoffing raises fair points, personally I'd sleep better at night knowing these domains are blocked (sorry for chiming in), in case of any other add-ons or bugs feeding data to the domains regardless of user settings.

**Comment by hagezi** [comment]
Close here, the domains remain blocked for now.
