### ISSUE TITLE
DNS resolver blocklists

### ISSUE THREAD

**Issue by mvevitsis** [hagezi/dns-blocklists#3290]
`To ensure the bootstrap is your DNS server you must redirect or block standard DNS outbound (TCP/UDP 53) and block all DNS over TLS (TCP 853) outbound.`

Wouldn't it be best to block UDP for 853 as well (DoQ)?

**Comment by hagezi** [comment]
Yes, that's missing from the text.

**Comment by mvevitsis** [comment]
Also might want a warning with the DoH IP blocklist that quad9 can use port 5053 instead of 443.

**Comment by hagezi** [comment]
fixed in next release
