### ISSUE TITLE
Whitelist (www).socket.dev

### ISSUE THREAD

**Issue by orazioedoardo** [hagezi/dns-blocklists#3291]
### Which AdBlocker/DNS cloud service do you use?

Other

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

socket.dev
www.socket.dev

### Why should the domain(s) be unblocked?

They are a software company focused on protection against supply chain attacks, not maliciuous: https://github.com/SocketDev

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Not blocked in the current version.
