### ISSUE TITLE
Whitelist myhome.zone and all subdomains

### ISSUE THREAD

**Issue by dontobi** [hagezi/dns-blocklists#330]
#### What adblocker/DNS cloud service are you using?
AdGuard Home

#### Which blocklists are used?
spamtlds

#### Which domain(s) should be unblocked?
*.myhome.zone
Example: cloud.myhome.zone

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
The domain myhome.zone belongs to me and I use it together with some subdomains. When using the spamtlds list, all subdomains stop working.

**Comment by hagezi** [comment]
Thanks, ping @yokoffing for adding `$denyallow=myhome.zone`

**Comment by dontobi** [comment]
Thanks 👍
