### ISSUE TITLE
Multi Pro++ list Beak Instagram

### ISSUE THREAD

**Issue by HectorRCM** [hagezi/dns-blocklists#3304]
### Which AdBlocker/DNS cloud service do you use?

RethinkDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

graph-fallback.instagram.com
graph.instagram.com

### Why should the domain(s) be unblocked?

intragram app break in android devices

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@HectorRCM 

What exactly is not working? We had tested it several times and found no restrictions. Please send us details on how we can reproduce the problem.

**Comment by HectorRCM** [comment]
Problem Solve in last rethinkdns update.
