### ISSUE TITLE
tawk.to and www.tawk.to

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#331]
#### What adblocker/DNS cloud service are you using?
ControlD

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
```
tawk.to
www.tawk.to
```

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

1. Go to https://www.coextro.com/
2. Bottom of page click on "Start a Live Chat"
3. The tawk.to page is blocked

Coextro is a legitimate Internet service provider: https://www.coextro.com/about-us/

Thank you!

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by hagezi** [comment]
Fixed with https://github.com/hagezi/dns-blocklists/commit/193bb68fbe7a7dc24ec87f85d9ba463aaa82716c
