### ISSUE TITLE
bonuspulsefortune.life

### ISSUE THREAD

**Issue by Skrriply** [hagezi/dns-blocklists#3312]
### Which domain(s) should be blocked?

bonuspulsefortune.life

### Why should these domain(s) be blocked?

[Phishing](https://www.virustotal.com/gui/url/3edf052998a641b3d8e2e67fc45d442fecef6de19270e7b00bc9a8976f741db1)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Thank you, added in https://github.com/iam-py-test/my_filters_001/commit/1630020dbab9aa8e3ffdbdb9d265fdb397e8c138.
