### ISSUE TITLE
Potential Google trackers?

### ISSUE THREAD

**Issue by rANdecHo** [hagezi/dns-blocklists#3318]
### Which domain(s) should be blocked?

spot-pa.googleapis.com
finance-pa.googleapis.com
preprod-discover-pa.googleapis.com
androidpay-users-pa.googleapis.com

### Why should these domain(s) be blocked?

I found there in my logs. I could be completely wrong, but could you please check if they are trackers or telemetry?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`spot-pa.googleapis.com` - could be part of an API used for managing resources within Google Cloud Platform (GCP), specifically related to "Spot" instances. These are preemptible virtual machines (VMs) that run at a lower cost but can be interrupted by Google if they need the capacity back.

`finance-pa.googleapis.com` - seems to be part of Google’s infrastructure for providing financial data, such as stock prices, market indices, currency exchange rates, and other related information. The "Google Finance API" allows developers to integrate financial data into their applications. 

`preprod-discover-pa.googleapis.com` - this appears to be related to Google's infrastructure, possibly a pre-production (preprod) environment for testing purposes. `preprod`: This indicates a pre-production environment. `discover`: This could refer to a discovery service or API, which might be used to automatically find or suggest content, services, or resources.

`androidpay-users-pa.googleapis.com` - appears to be related to Google's Android Pay (now known as Google Pay), which is a mobile payment service that allows users to make payments using their Android devices.

**Comment by hagezi** [comment]
I don't see any direct connection with classic user tracking here. Some of the APIs also seem to be required for important functions such as Google Pay.

**Comment by Retold3202** [comment]
I concur with @hagezi on these domains, only one I think worth blocking here is `preprod-discover-pa.googleapis.com`. This domain is similar to `discover-pa.googleapis.com`, which I found in my testing is responsible for Chromium's "Discovery Feed" promotions & suggested content on mobile (Ex. explained [here](https://www.androidpolice.com/2021/06/29/heres-how-to-get-rid-of-those-suggestions-on-chromes-new-tab-page/). 

Other domains related to this fuctionality include: 

`chromecontentsuggestions-pa.googleapis.com` ([ref](https://codereview.chromium.org/2338133006)).

`chromefeedcontentsuggestions-pa.googleapis.com` (ref [here](https://groups.google.com/a/chromium.org/g/chromium-dev/c/YB9z1Q-Egto) & [here](https://brave.com/blog/ios-browser-first-run/))

`exploresites-pa.googleapis.com` ([ref](https://chromium.googlesource.com/chromium/src.git/%2B/72.0.3626.80/chrome/browser/android/explore_sites/explore_sites_fetcher_unittest.cc)).

`ging-chromecontentsuggestions-pa.googleapis.com` ([ref](https://codereview.chromium.org/2338133006)).

`gsacollections-pa.googleapis.com` ([ref](https://static.googleusercontent.com/media/www.google.ie/en/ie/intl/en_uk/enterprise/pdf/gsa_datasheet.pdf)).

`spot-pa.googleapis.com` could potentially be of interest, but will need more investigation & research, not enough known about it RN.
