### ISSUE TITLE
Requesting permission to list your blocklists in an OpenWrt package

### ISSUE THREAD

**Issue by rickparrish** [hagezi/dns-blocklists#3319]
Hello, I'm experimenting with a package for OpenWrt, specifically a luci front-end for the adblock-lean package.

To make things easy for the user, I'd like to list your dnsmasq-based blocklists in a multi-select list, so then they can just tick off the ones they want without needing to copy/paste URLs.  Here's an example of how this looks:
![image](https://github.com/user-attachments/assets/6d3f138d-17ef-4681-ae95-2a9eea8c9697)

Is this OK?  Would you like any sort of message/disclaimer included?

The full text hidden by the dropdown is: dnsmasq blocklists provided by hagezi. For blocklist information, please check the [online documentation](https://github.com/hagezi/dns-blocklists/blob/main/README.md)

**Comment by hagezi** [comment]
No problem, you can do it that way.
