### ISSUE TITLE
Wi-Fi stops working after applying the Ultimate filter to the Windows Hosts file

### ISSUE THREAD

**Issue by ChaseKnowlden** [hagezi/dns-blocklists#3320]
Whenever I add the Ultimate Hosts file to Windows, the Wi-Fi doesn't work which makes the computer unusable.

**Comment by hagezi** [comment]
Yes, too big. Only light works. 

![image](https://github.com/user-attachments/assets/a8339490-c1a9-41b3-9971-4997335a9199)
