### ISSUE TITLE
README: Reduce too much `*emphasis*`

### ISSUE THREAD

**Issue by KSR-Yasuda** [hagezi/dns-blocklists#3323]
Could you reduce `*emphasis*` in the project `README.md`?
It's too much.

I add `<em>` style `text-decoration: underline;` to recognize them
(since the default `<em>` style, italic, is not displayed with Meiryo font, for Japanese characters).

With the setting, `<em>`-s in the `README.md` are a bit annoying.
![readme_20240801_182255](https://github.com/user-attachments/assets/62768734-7a16-47c1-abd3-a13a27974d84)

**Comment by hagezi** [comment]
Thanks @KSR-Yasuda, please check the customised readme.

**Comment by KSR-Yasuda** [comment]
Thank you, now it looks clean :smile:
