### ISSUE TITLE
Phishing/malware links

### ISSUE THREAD

**Issue by rANdecHo** [hagezi/dns-blocklists#3325]
### Which domain(s) should be blocked?

```
m-isist-emai-nmu-ne-yx8nu6hs7k.vercel.app
m-isist-emai-nmu-ne-6zft4bsbqh.vercel.app
m-isist-emai-nmu-ne-qefa68dvbd.vercel.app
thepatrones.blob.core.windows.net
xyzxyz55.xyz
```

### Why should these domain(s) be blocked?

They are being posted by hacked/hijacked Facebook accounts. I have tried opening one of them but for some reason it redirects me to Amazon.

[Update with more info](https://github.com/uBlockOrigin/uAssets/issues/24719)

I also recommend blocking all `m-isist-emai-nmu-ne- ... .vercel.app`, not just the ones I reported, if possible on DNS.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by JobcenterTycoon** [comment]
Full URLs

```
https://m-isist-emai-nmu-ne-yx8nu6hs7k.vercel.app/
https://m-isist-emai-nmu-ne-6zft4bsbqh.vercel.app/
https://m-isist-emai-nmu-ne-qefa68dvbd.vercel.app/
https://thepatrones.blob.core.windows.net/thepatrone/thepatrones.html
https://xyzxyz55.xyz/?api=1&lan=facebooknew&ht=1
```

**Comment by iam-py-test** [comment]
Added to my blocklist, which is included in hagezi's threat intelligence feeds. Thank you @rANdecHo and @JobcenterTycoon
