### ISSUE TITLE
Banking SMS MFA blocked

### ISSUE THREAD

**Issue by Altycoder** [hagezi/dns-blocklists#3330]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO, Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

signal-collector.gemaltodigitalbankingidcloud.com

### Why should the domain(s) be unblocked?

Blocks MFA SMS verification codes from Coventry Building Society in the UK.

Once added to my nextdns allowlist the SMS MFA messages come through.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@Altycoder The issue was just displayed to me now, for whatever reason. Will be fixed in the next release.

**Comment by Altycoder** [comment]
Thanks @hagezi I have just had my GitHub account unflagged so thanks for picking it up and responding
