### ISSUE TITLE
Twitch channel points

### ISSUE THREAD

**Issue by xxAlex7** [hagezi/dns-blocklists#3333]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

I don't know for sure

### Why should the domain(s) be unblocked?

Another user requested to block Twitch telemetry (https://github.com/hagezi/dns-blocklists/issues/2862), now Twitch channel points are no longer obtained. I also noticed that Twitch has become more unstable after this block.

**Comment by hagezi** [comment]
Have you allowed the domains and checked whether this has solved the problems? What exactly does unstable mean?

**Comment by xxAlex7** [comment]
> Have you allowed the domains and checked whether this has solved the problems? What exactly does unstable mean?

Yes, I whitelisted video-edge-000000.pdx01.abs.hls.ttvnw.net and it worked fine (0 because this part changes constantly and this is the only address that appears blocked for me). About instability, the lives are freezing more frequently.

**Comment by xxAlex7** [comment]
> what browser / os are you on

Chrome and Windows 11, both updated.
