### ISSUE TITLE
sdk-01.moengage.com allow this

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3334]
### Which AdBlocker/DNS cloud service do you use?

ControlD, NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

This is required as without this I can't use olacabs
sdk-01.moengage.com

### Why should the domain(s) be unblocked?

Without this olacab app cant be used
I am using proplus

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Which platform and what exactly is not working?

**Comment by olumolu** [comment]
Maps are not loading i have confirmed this 
Today I cant get the map loaded in ola maps olacab is a cab facility application which provide cab service in india.
After manually allowing that i could get the maps available in the app.

**Comment by olumolu** [comment]
I have fixed the isssue i will keep posted
