### ISSUE TITLE
c.webengage.com block

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3335]
### Which domain(s) should be blocked?

c.webengage.com

### Why should these domain(s) be blocked?

c.webengage.com this is used for analytics purpose 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2409

**Comment by olumolu** [comment]
Can you explain how this is duplicate i can see this is not blocked in pro++

**Comment by hagezi** [comment]
Yes, it is not blocked because it is only a link tracker - referral domain.

Just read ...

https://github.com/hagezi/dns-blocklists/wiki/FAQ#referral

**Comment by olumolu** [comment]
But this can be blocked in the ultimate at least correct me if i am wrong
I find this to be blocked in Steven Black and nextdns own blocklist maybe there are other block list that contains this which i am not aware of.

**Comment by hagezi** [comment]
It makes absolutely no sense to block pure link trackers in DNS. If they also function as normal trackers, they will be blocked in the aggressive lists, as described in the link.

This is a pure link tracker. Even if it is blocked in 100 lists, they are not blocked in my DNS lists.

**Comment by olumolu** [comment]
Ok thanks for your clarification.
