### ISSUE TITLE
Zillow.com Blank Page

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#3346]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

zg-api.com

### Why should the domain(s) be unblocked?

After searching for an address or city the page will briefly load then go completely blank. After unblocking `zg-api.com` The page loads normally.

Example
https://www.zillow.com/homes/Chicago-Heights,-IL_rb/

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by markangus2b** [comment]
@hagezi It appears `e.zg-api.com` is also in the list and required to not cause the site to display a blank page.

**Comment by hagezi** [comment]
@markangus2b 

Are you using a content blocker?

Works for me:

![image](https://github.com/user-attachments/assets/ea69403d-0ed0-477a-8f9e-5516b1512a0e)

**Comment by hagezi** [comment]
Thanks @FadeMind

**Comment by markangus2b** [comment]
I am stumped. With `e.zg-api.com` blocked everything loads perfectly fine on Brave Browser. But on Edge and Firefox my page goes blank.

I've tried disabling the malware and tracking protection, didn't make any difference. Turning on my VPN and using uBlock with only the Pro++ list versus DNS filtering didn't work either.

**Comment by hagezi** [comment]
@markangus2b I can reproduce this in Firefox if I set Firefox Tracking Protection to Strict, on Standard the problem does not occur.

**Comment by markangus2b** [comment]
Good to know. Thank you @hagezi and @FadeMind for investigating this issue. I at this point I have to agree, something on my end is causing the crash.
