### ISSUE TITLE
Looks like a TikTok proxy?

### ISSUE THREAD

**Issue by tjamieg** [hagezi/dns-blocklists#3348]
### Which domain(s) should be blocked?

direct.quic-core-proxy-gcpsg-v3.gcpsg.byteglb.com
direct-http.quic-webcast-proxy-i18n-v3.useast2a.byteglb.com
direct.quic-webcast-core-proxy-i18n-v3.useast2a.byteglb.com
direct-http.quic-tiktok-proxy-i18n-v3.useast2a.byteglb.com

### Why should these domain(s) be blocked?

Encrypted DNS/VPN/TOR/Proxy Bypass DNS Blocklist

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/1445

Only used for Tiktok, blocking makes Tiktok unusable. Not a classic DNS bypass that should be blocked in a bypass list.
