### ISSUE TITLE
TIF Blocklist Source Suggestion

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#335]
Hi.

I came across this new blocklist: [https://github.com/tweedge/emerging-threats-pihole](https://github.com/tweedge/emerging-threats-pihole).

From the blocklist's repo:

> This repository extracts and categorizes malicious/unwanted domains from the Emerging Threats ruleset for people using PiHole to block easily. 
> ...
> **Where is this data coming from / what is Emerging Threats?**
> [Emerging Threats](https://doc.emergingthreats.net/bin/view/Main/EmergingFAQ) is a part of Proofpoint, Inc. They maintain the Emerging Threats ruleset, which is a free (BSD-licensed) list of rules contributed to by their team and security researchers around the world.

There is more context on the creator's Reddit post regarding the blocklist: [https://www.reddit.com/r/pihole/comments/110u8he/new_blocklist_to_help_you_block_malware_phishing/](https://www.reddit.com/r/pihole/comments/110u8he/new_blocklist_to_help_you_block_malware_phishing/)

**Comment by hagezi** [comment]
Thanks, I will check ...

**Comment by hagezi** [comment]
Thanks, I added https://hosts.tweedge.net/malicious.txt from @tweedge to the Threat Intelligence Feeds list. The build is running right now ...

**Comment by hagezi** [comment]
added.
