### ISSUE TITLE
Another fake Vercel domain

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3354]
### Which domain(s) should be blocked?

pr-ue-ba-de-lsa-bermu-ne-xre4pgczsk.vercel.app

### Why should these domain(s) be blocked?

It’s one of those fake Vercel links that were reported a few days ago. They’re found on Facebook and bypass PCs. A mobile user agent is necessary in order to view them, or they will redirect to legitimate websites like Amazon.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added to my blocklist, thanks.

**Comment by MEtICaRT** [comment]
Another one: `pr-ue-ba-de-lsa-bermu-ne-cp5iah/zlw.vercel.app`
