### ISSUE TITLE
Adapted versión for mobile.

### ISSUE THREAD

**Issue by Hell0Earth** [hagezi/dns-blocklists#3360]
On hosts releases can you provide an adapted version for mobile, based on light release to be used on apps like AdAway or local vpn based on host files apps. Light version is good but is too big for mid and lower hardware devices.

**Comment by Hell0Earth** [comment]
> On hosts releases can you provide an adapted version for mobile, based on light release to be used on apps like AdAway or local vpn based on host files apps. Light version is good but is too big for mid and lower hardware devices.

Thanks for your work, I'm using hagezi on next dns, adguard dns and on AdAway(dns bypass and block xiaomi trackers)

**Comment by hagezi** [comment]
That people will still be using stone-age host files in 2024. The Light is already optimised. I don't know offhand what else you could optimise without this list becoming ineffective. Why are you still using Adaway if you are using filtering upstream DNS?
What is the exact target size for such a list?

**Comment by Hell0Earth** [comment]
> That people will still be using stone-age host files in 2024. The Light is already optimised. I don't know offhand what else you could optimise without this list becoming ineffective. Why are you still using Adaway if you are using filtering upstream DNS?
> What is the exact target size for such a list?

On pc of domestic usage a host file is not useful on my opinion, but smartphone is different, host file can be a good backup method to keep a minimum protection from ads, trackers and spyware on public networks that blocks users DNS, in my case, most of my traffic comes form my smartphone, so have an alternative method to kepp a minimum protection is good

**Comment by Hell0Earth** [comment]
> > That people will still be using stone-age host files in 2024. The Light is already optimised. I don't know offhand what else you could optimise without this list becoming ineffective. Why are you still using Adaway if you are using filtering upstream DNS?
> > What is the exact target size for such a list?
> 
> On pc of domestic usage a host file is not useful on my opinion, but smartphone is different, host file can be a good backup method to keep a minimum protection from ads, trackers and spyware on public networks that blocks users DNS, in my case, most of my traffic comes form my smartphone, so have an alternative method to kepp a minimum protection is good

Actually I'm using 12 hosts list most of them to block ads, trackers and malicious sites, around 28.000 domains are blocked

**Comment by hagezi** [comment]
Makes little sense to me if you use a filtered upstream DNS. All the ad blockers that do not support wildcard blocking today and instead work with subdomain or host lists are completely outdated and absolutely ineffective in my opinion.

A todo list actually says to discontinue support for the subdomain and host list format in the normal list versions.

**Comment by Hell0Earth** [comment]
> Makes little sense to me if you use a filtered upstream DNS. All the ad blockers that do not support wildcard blocking today and instead work with subdomain or host lists are completely outdated and absolutely ineffective in my opinion.
> 
> A todo list actually says to discontinue support for the subdomain and host list format in the normal list versions.

Not good for me and hosts users but well, hagezi still good at DNS level and isn't the first list that removes host file support, thanks for your work 👍

**Comment by hagezi** [comment]
@Hell0Earth It's on my to-do list, but that doesn't mean I'm actually going to do it.

What surprises me is that your device can't cope with a 130000 hosts file, how old is the device?
Even Windows can do that. :)

**Comment by Hell0Earth** [comment]
> @Hell0Earth It's on my to-do list, but that doesn't mean I'm actually going to do it.
> 
> What surprises me is that your device can't cope with a 130000 hosts file, how old is the device?
> Even Windows can do that. :)

around 7 years old and on perfect conditions, 4gb ram and SDM 636, the problem is the ram, insufficient for newer apps requirements and to check local hos for every queri, all the time if local host is very "big" 😔 Thanks for add my petition to the to do list, sorry for take your time, have a good night sir 👍
