### ISSUE TITLE
neta.co.th

### ISSUE THREAD

**Issue by annopdanai** [hagezi/dns-blocklists#3361]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

neta.co.th

### Why should the domain(s) be unblocked?

Neta Auto Thailand website

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Not blocked in the current version.
