### ISSUE TITLE
TV4play.se video streaming issue

### ISSUE THREAD

**Issue by BourbonCrow** [hagezi/dns-blocklists#337]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
Hagezi Multi Pro for my family
Hagezi Ultimate for my self

#### Which domain(s) should be unblocked?
se-tv4.videoplaza.tv

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
I know this is a ad domain but TV4 is a Swedish local TV station and they got a website where you can rewatch previous episodes / news / weather or whatever that was on TV and this subdomain "se-tv4" is required else news and other videos on their website don't work. so i'm only asking to unblock that subdomain not entire videoplaza if you allow it or not is up to you since its in the end a ad network. I will white listed it my self so mom and dad can watch the news in any case, thanks for an amazing blocklist and good job

**Comment by hagezi** [comment]
Because it is only relevant for TV4 and thus no videos can be played, I will whitelist Domain - I see no problem in that.

**Comment by hagezi** [comment]
Fixed. Lists in NextDNS are up to date.
