### ISSUE TITLE
ads.brave.com

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#338]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
HaGeZi - Multi PRO

#### Which domain(s) should be unblocked?
ads.brave.com
anonymous.ads.brave.com
search.anonymous.ads.brave.com
geo.ads.brave.com
mywallet.ads.brave.com
static.ads.brave.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocks Brave ads used to collect Basic Attention Tokens (BAT).

**Comment by hagezi** [comment]
Thanks, will whitelist the domains for the Pro version, in the more aggressive lists like Pro++ and Ultimate the domains remain blocked.

**Comment by hagezi** [comment]
Ficed.
