### ISSUE TITLE
Adguard home crashing when updating lists

### ISSUE THREAD

**Issue by Volluris** [hagezi/dns-blocklists#3380]
Hello,

I am using the following lists in AdGuard Home on a Raspberry Pi Zero 2:

HaGeZi's Threat Intelligence Feeds
HaGeZi's Ultimate Blocklist
Dandelion Sprout's Anti-Malware List
HaGeZi's The World's Most Abused TLDs

![image](https://github.com/user-attachments/assets/fe36081f-2947-4e21-8f59-c8ac3276b758)

Whenever AdGuard Home checks for updates to the lists, or if I do it manually; AdGuard Home crashes requiring me to turn off the Pi and start it up again.

Is there a limitation to the device that I need to use a smaller list?

Thank you.

**Comment by hagezi** [comment]
Too little RAM, AGH is quite memory hungry, use the TIF medium or mini instead of the TIF full.

**Comment by Volluris** [comment]
> Too little RAM, AGH is quite memory hungry, use the TIF medium or mini instead of the TIF full.

Fantastic, thank you for clearing that up for me!.

**Comment by hagezi** [comment]
@Volluris For the hardware, I recommend the Ultimate mini + TIF medium + Abused TLDs + Dandelion Sprout Malware
