### ISSUE TITLE
More fake Vercel domains

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3383]
### Which domain(s) should be blocked?

facebook-google-ygggvmvciad74v9lhi.vercel.app
facebook-google-vptyyny63pwfipshmm.vercel.app
facebook-google-15oqyxwtkremqyujsm.vercel.app

### Why should these domain(s) be blocked?

They're pretending to be a shocking news article in Greek and are posted by hacked accounts:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/75c9563a-ca07-44ec-a63c-9d33c23182d3">

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by Mirabis** [comment]
@iam-py-test  wouldn't it make more sense to use a regex block here? 
`facebook-google-[a-z0-9]{18}\.vercel\.app`

Would match all four reported and any that uses the exact same structure.

**Comment by iam-py-test** [comment]
> wouldn't it make more sense to use a regex block here?

Firstly, my blocklist is used in domain blocklists like hagezi's threat intelligence feeds, so it is necessary to individually list each malicious domain.
Secondly, unless there is evidence of larger use of this pattern or a reasonable likelihood of it's reuse (for example, _facebook-google-_ does not seem likely to be used as part of unrelated phishing attacks, but something like _facebook-com-security_ could be), I do not think it necessary to add a rule just for this pattern.
Thank you
