### ISSUE TITLE
neon.ipsator.com, carbon-v2.ipsator.com

### ISSUE THREAD

**Issue by anxiouslelimo** [hagezi/dns-blocklists#339]
What adblocker/DNS cloud service are you using?
NextDNS

Which blocklists are used?
HaGeZi - Multi PRO++

Which domain(s) should be unblocked?
neon.ipsator.com, carbon-v2.ipsator.com

Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
The eCatering Service in IRCTC (OFFICIAL MOBILE APP by Indian Railway Catering And Tourism Corporation Limited (IRCTC)
) is not working with these domains blocked.

**Comment by hagezi** [comment]
Thanks, fixed.
