### ISSUE TITLE
Allow client.px-cdn.net

### ISSUE THREAD

**Issue by maheshrijal** [hagezi/dns-blocklists#3395]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO, Multi PRO++

### Which domain(s) should be unblocked?

client.px-cdn.net

### Why should the domain(s) be unblocked?

When blocked, this domain prevents captcha from loading on https://www.skyscanner.co.in/

![Screenshot from 2024-08-11 20-01-24](https://github.com/user-attachments/assets/39d0ffd0-1f65-44a1-b2cf-6393e5eb8ef2)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
PerimeterX tracker - the app/site thinks you're a bot, for whatever reason, hence the captcha. It's something for the personal allowlist.
