### ISSUE TITLE
block next-cryptopod.xyz

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#340]
#### Which domain(s) should be blocked?
next-cryptopod.xyz

#### Why should the domain(s) be blocked?
telegram crypto scam

🎁 TORN Airdrop 🎁

Tornado Cash is a decentralized, non-custodial privacy solution built on Ethereum. It improves transaction privacy by breaking the on-chain link between recipient and destination addresses. Tornado Cash uses a smart contract that accepts ETH and ERC-20 deposits. These deposits can be withdrawn by any on-chain address. Whenever an asset is withdrawn by the new address, there is no way to link the withdrawal to the deposit, ensuring asset privacy.
    
🎉 Airdrop $200,000 worth of TORN to 1,000 users who:

📲 Join our group
✅ Join airdrop 👇

**Comment by durablenapkin** [comment]
Will be added, thanks!
