### ISSUE TITLE
Google Ads

### ISSUE THREAD

**Issue by SevenFactors** [hagezi/dns-blocklists#3409]
### Which domain(s) should be blocked?

googleads.g.doubleclick.net

### Why should these domain(s) be blocked?

Using Pro++
googleads.g.doubleclick.net is not blocked. I had expected google ads to be blocked at Pro. Tried Pro++ and said domain is not blocked.

I think it should be blocked universally across all lists to help sanitize the web from as many tracking ads as possible. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked in all list versions.

**Comment by hagezi** [comment]
https://www.reddit.com/r/nextdns/comments/1eqki85/google_ads_are_not_blocked_now/

If this is the topic why you opened the issue, then the ads cannot be blocked via DNS.

Disguised ads are loaded on `onlinegdb.com`, these cannot be blocked using DNS, for this you need a browser content blocker such as uBlock. The ads are loaded via `html-load.com`, if you block this domain via DNS, the whole page will no longer work.

A lot can be blocked via DNS, but not everything.

**Comment by SevenFactors** [comment]
> @SevenFactors
> 
> https://www.reddit.com/r/nextdns/comments/1eqki85/google_ads_are_not_blocked_now/
> 
> If this is the topic why you opened the issue, then the ads cannot be blocked via DNS.
> 
> Disguised ads are loaded on `onlinegdb.com`, these cannot be blocked using DNS, for this you need a browser content blocker such as uBlock. The ads are loaded via `html-load.com`, if you block this domain via DNS, the whole page will no longer work.
> 
> A lot can be blocked via DNS, but not everything.


Hello,

The reason I opened the issue is a result of my usage of RethinkDNS app. Researching for block lists, I ran into your work and I was happy to see Rethink also offers your adblock lists for use locally at the app level. I settled for Multi Pro++. Going over the app logs, I noticed that google ad url was not being blocked.  I had figured it was an oversight but surely the ad vs adblock scene is more complicated than meets the eye.

With that said, after further reading and following the recommendations on the Hagezi GitHub page,  I went ahead and added TIF list and OISD.  Funny enough, now RethinkDNS app shows OISD is blocking the google ads url.

You and your team are doing an amazing work. Thank you.
