### ISSUE TITLE
False Positive sentry.sc-prod.net

### ISSUE THREAD

**Issue by DemirSe** [hagezi/dns-blocklists#341]
#### What adblocker/DNS cloud service are you using?
NextDNS

#### Which blocklists are used?
MultiPRO++

#### Which domain(s) should be unblocked?
sentry.sc-prod.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It breaks Snaptchat's avatar editing feature.

**Comment by hagezi** [comment]
Thanks, removed.
