### ISSUE TITLE
Blocked domains cause issues on aegeanair.com

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3415]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

d35vb5cccm4xzp.cloudfront.net
d1mj578wat5n4o.cloudfront.net

### Why should the domain(s) be unblocked?

Either or both of these domains cause infinite loading when searching for tickets on `aegeanair.com`. Please confirm this by selecting a departure location, a destination, and a date. Then click on 'Search' to test it, as I'm not sure which one is responsible for the issue.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`d1mj578wat5n4o.cloudfront.net` causes the problem.
