### ISSUE TITLE
Probable Call of Duty Mobile analytics

### ISSUE THREAD

**Issue by AleIlMagno** [hagezi/dns-blocklists#3416]
### Which domain(s) should be blocked?

itop.qq.com

codm.qq.com (or only hycdn.cn.codm.qq.com)

### Why should these domain(s) be blocked?

Both QQ and Call of Duty Mobile are owned by Tencent, but I don't see any reason why there should be a connection between the game and the messaging application.
These domains seem to not make any difference to the game when blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`itop.qq.com` - https://github.com/hagezi/dns-blocklists/issues/1395

**Comment by hagezi** [comment]
`codm.qq.com` is the official site for the Chinese version of Call of Duty: Mobile (CODM). The site features updates, news, and event information specifically for the Chinese audience. It serves as a hub for players to download the game, check out the latest updates, participate in events, and connect with the community.

`hycdn.cn.codm.qq.com` - Unclear what the domain is used for, some CDN.
