### ISSUE TITLE
Samsung TV blocked urls break the smart system

### ISSUE THREAD

**Issue by viniribeirossa** [hagezi/dns-blocklists#342]
Blocked cases break the smart TV system

samsungcloud.tv
samsungqbe.com
samsungcloudsolution.net
samsungcloudsolution.com

**Comment by hagezi** [comment]
Please give me some more details. 
Which list do you use? 
Which subdomains lead to which functional restrictions?

**Comment by hagezi** [comment]
@viniribeirossa Should be fixed, please test.

**Comment by viniribeirossa** [comment]
@hagezi Thanks for fast support
