### ISSUE TITLE
Salt Bank

### ISSUE THREAD

**Issue by cblinq** [hagezi/dns-blocklists#3422]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

salt.bank
*.salt.bank

### Why should the domain(s) be unblocked?

It is an official bank licensed in Romania owned by Banca Transilvania. (blocked by controld/spam-tlds-folder.json)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by cblinq** [comment]
This hasn't been added yet

**Comment by hagezi** [comment]
@cblinq bank TLD is not blocked in Most Abused TLDs, Update your ControlD folder.
See: https://github.com/hagezi/dns-blocklists/issues/3534
