### ISSUE TITLE
Can you open source the code that checks for plagiarism in ad filtering rules?

### ISSUE THREAD

**Issue by xiulou23** [hagezi/dns-blocklists#3428]
You're using a lot of other people's lists of ad filters. I believe that many parts of the rules of these lists are duplicative, and you should have removed the duplicate rules. I have collected a lot of DNS filters, and I know that many of the rules in these filters are duplicates, so I am looking for code to remove the duplicate rules. If you have code that removes duplicate rules and makes it open source, I'd appreciate it

**Comment by hagezi** [comment]
I simply apply a unique sorting to the sub-domain list and then send it through the AdGuard Hostist compiler for wildcard formats:

https://github.com/AdguardTeam/HostlistCompiler

**Comment by xiulou23** [comment]
> I simply apply a unique sorting to the sub-domain list and then send it through the AdGuard Hostist compiler for wildcard formats:
> 
> https://github.com/AdguardTeam/HostlistCompiler

Thank you
