### ISSUE TITLE
files.catbox.moe

### ISSUE THREAD

**Issue by ChaseKnowlden** [hagezi/dns-blocklists#3439]
### Which domain(s) should be blocked?

[files.catbox.moe](https://files.catbox.moe)

### Why should these domain(s) be blocked?

Domain spotted in My Spectrum app.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Why should the domain be blocked? This is a file sharing service.

**Comment by ChaseKnowlden** [comment]
Closing as not planned.
