### ISSUE TITLE
Domains Queried by Bondee Social Media 

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#344]
#### Which domain(s) should be blocked?

statssg01.cn.ronghub.com
navsg01.cn.ronghub.com

#### Why should the domain(s) be blocked?

I don't know for sure if the domains above are related to tracking but 1Hosts (Pro) blocks the following:
stats.cn.ronghub.com
nav.cn.ronghub.com

I used the [Bondee](https://bondee.net/) social media app in Singapore. That would explain the 'sg01'.

**Comment by hagezi** [comment]
Thanks, added.
