### ISSUE TITLE
gotcha-server.evo.run

### ISSUE THREAD

**Issue by Skrriply** [hagezi/dns-blocklists#3443]
### Which domain(s) should be blocked?

gotcha-server.evo.run

### Why should these domain(s) be blocked?

Metrics
```
https://gotcha-server.evo.run/metrics
```

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Is gotcha-server.evo.run only used for metrics or are other functionalities provided via it?

What triggers the domain?
