### ISSUE TITLE
chromeweb-authenticators.com: badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3445]
### Which domain(s) should be blocked?

chromeweb-authenticators.com

### Why should these domain(s) be blocked?

This is a fake Google Authenticator domain, with a malware payload.

<img width="648" alt="image" src="https://github.com/user-attachments/assets/2e7e3963-2665-43e4-9dd1-235aa5c33c8f">

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Original source: https://www.malwarebytes.com/blog/news/2024/07/threat-actor-impersonates-google-via-fake-ad-for-authenticator
While the website is still up, visiting it returns a dismissable phishing warning from CloudFlare.
Moreover, it seems https://github.com/authe-gogle may have been taken down ([and has been for a little while](http://web.archive.org/web/20240000000000*/https://github.com/authe-gogle/), and the download links now redirect to a parked domain.
Sandbox (behind CloudFlare): https://tria.ge/240818-3teckavfjj/behavioral1
Thanks

**Comment by iam-py-test** [comment]
Odd, it seems sometimes the CloudFlare warning may not appear?
I have blocklisted it. Thank you for reporting this.
