### ISSUE TITLE
api.sec.intl.miui.com tracking domain in miui

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3446]
### Which domain(s) should be blocked?

api.sec.intl.miui.com

### Why should these domain(s) be blocked?

Tracking domain

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/2013

**Comment by olumolu** [comment]
Ok
