### ISSUE TITLE
probably tracking domain 

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3447]
### Which domain(s) should be blocked?

s.youtube.com

### Why should these domain(s) be blocked?

After blocking there is no issue in youtube or playback
I found stiven black have this in there list

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/search?q=s.youtube.com&type=issues

**Comment by olumolu** [comment]
Yes i have seen it but i am testing this one my self but did not find any such error.
