### ISSUE TITLE
tracking domain

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3448]
### Which domain(s) should be blocked?

c.webengage.com

### Why should these domain(s) be blocked?

Tracking domain used in oliverboard

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Referral domain, see: https://github.com/hagezi/dns-blocklists/wiki/FAQ#referral
https://github.com/search?q=repo%3Ahagezi%2Fdns-blocklists+c.webengage.com&type=issues
