### ISSUE TITLE
youtube crypto scam

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#345]
#### Which domain(s) should be blocked?

tesla-bmw.com
teslajust.io
chatgpt-double.com
teslahome.io

#### Why should the domain(s) be blocked?
youtube crypto scam

see https://github.com/badmojr/1Hosts/issues for more info

**Comment by hagezi** [comment]
Thanks, added.

ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued to add, thanks!
