### ISSUE TITLE
monitoring.*.amazonaws.com should be unblocked

### ISSUE THREAD

**Issue by surfaceflinger** [hagezi/dns-blocklists#3455]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Mullvad DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Native Tracker

### Which domain(s) should be unblocked?

monitoring.af-south-1.amazonaws.com
monitoring.ap-east-1.amazonaws.com
monitoring.ap-northeast-1.amazonaws.com
monitoring.ap-northeast-2.amazonaws.com
monitoring.ap-northeast-3.amazonaws.com
monitoring.ap-south-1.amazonaws.com
monitoring.ap-south-2.amazonaws.com
monitoring.ap-southeast-1.amazonaws.com
monitoring.ap-southeast-2.amazonaws.com
monitoring.ap-southeast-3.amazonaws.com
monitoring.ap-southeast-4.amazonaws.com
monitoring.ca-central-1.amazonaws.com
monitoring.ca-west-1.amazonaws.com
monitoring.eu-central-1.amazonaws.com
monitoring.eu-central-2.amazonaws.com
monitoring.eu-north-1.amazonaws.com
monitoring.eu-south-1.amazonaws.com
monitoring.eu-south-2.amazonaws.com
monitoring.eu-west-1.amazonaws.com
monitoring.eu-west-2.amazonaws.com
monitoring.eu-west-3.amazonaws.com
monitoring.il-central-1.amazonaws.com
monitoring.me-central-1.amazonaws.com
monitoring.me-south-1.amazonaws.com
monitoring.prod.cloudwatch.amazonaws.com
monitoring.sa-east-1.amazonaws.com
monitoring.us-east-1.amazonaws.com
monitoring.us-east-2.amazonaws.com
monitoring.us-gov-east-1.amazonaws.com
monitoring.us-gov-west-1.amazonaws.com
monitoring.us-west-1.amazonaws.com
monitoring.us-west-2.amazonaws.com

### Why should the domain(s) be unblocked?

AWS Console is using these to fetch info from AWS CloudWatch regarding alarms and blocking these makes some of my daily work impossible.

Not sure what was the procedure to add these but I'm not aware of any client software that would contact these domains to report telemetry/metrics etc.(?)
![image](https://github.com/user-attachments/assets/fc56f89a-3ace-4ffa-b9a4-f62e2614d7cc)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Also used for Tracking, see: https://github.com/hagezi/dns-blocklists/issues/3014

**Comment by surfaceflinger** [comment]
oooh, okay, thanks

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/6611
