### ISSUE TITLE
A "diff" list for TIF / PopUpAds entries left out in Ultimate list - feasible?

### ISSUE THREAD

**Issue by Redundanz** [hagezi/dns-blocklists#3465]
Hi! 

just a quick inquiry (relating to #2662 ) if it would be possible/feasible/effortless to provide a seperate (small) "diff"-blocklist with the URLs that did not make it into the Ultimate list from the lists that are partially included, namely TIF ~~and PopUpAds~~?

Mainly because it might be a convenient way to reduce a high amount of duplication right at the source with larger rulesets on the appliances. I do not however have the knowledge if generally all filter appliances are completely unaffected performance-wise by duplicates, (disregarding the impact of the size and amount of blocklists).

Thkx!
red

Edit: PopUpAds is included, I have overlooked this.

**Comment by hagezi** [comment]
I don't see any sense in this, duplicates when using Ultimate and Popup ads are eliminated by the AdBlocker in which the lists are used.
