### ISSUE TITLE
rb.gy block

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3468]
### Which domain(s) should be blocked?

https://rb.gy/8s2bql
rb.gy

### Why should these domain(s) be blocked?

Scam url
Sending scam to users.
Want to do bank fraud.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by olumolu** [comment]
Is it blocked in pro+ also as i use this

**Comment by durablenapkin** [comment]
`rb.gy` is a valid link shortener service, the scam url is `3ab48a20-acaa-49ab-95cc-3eb16f1cda78-00-1a0l3yf6hw9aq.sisko.replit.dev` which I'll add to my blocklist

**Comment by durablenapkin** [comment]
Precedent: EasyList allowed it 2 years ago - https://github.com/uBlockOrigin/uAssets/issues/15983

**Comment by hagezi** [comment]
The domain is on many top 1M lists, so it is popular. Not a good idea to block the shortener completely.
