### ISSUE TITLE
Block affixwallet.net

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#347]
#### Which domain(s) should be blocked?
affixwallet.net

#### Why should the domain(s) be blocked?
telegram crypto scam

the DM: Monero XMR (admin):
Do you have any issues with Monero

Did you receive your bonus

https://app.affixwallet.net/?o

Select airdrop and connect your wallet securely manually

**Comment by hagezi** [comment]
Thanks, added.

ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued to add, thanks!
