### ISSUE TITLE
60q565qe5.top: badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3472]
### Which domain(s) should be blocked?

https://t.ly/_MOGC
https://60q565qe5.top/Nc5gbzM6?keyword=downtown&sub_id5=432571222679508

### Why should these domain(s) be blocked?

This scam/phisghing URL is pretending to be the Αthens Urban Transport Organisation and is being promoted by fake accounts on Facebook.

More info `https://www.athenstransport.com/2024/08/dimos-athinaion-facebook-apati/`

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added to my filterlist. Thanks
