### ISSUE TITLE
Blocking youboranqs01.com, and youborafds01.com result in Binge (streaming service) buffering issues

### ISSUE THREAD

**Issue by emeritaacuity0u** [hagezi/dns-blocklists#3474]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL, Multi PRO++

### Which domain(s) should be unblocked?

When watching [Binge](https://en.wikipedia.org/wiki/Binge_(streaming_service), blocking the below domains will gradually cause Samsung TV's to stop working until powered off at the GPO (even the remote stops working).
I presume it ends up logging these entries to a cache, filling the devices memory and freezing the TV.

I daresay it would happen on all Foxtel's streaming services, the parent company to Binge and Stan, and does not seem to be limited to TV's as my handheld devices experience this too.

There is another report of it [here](https://help.nextdns.io/t/60hfsms/youboranqs01-stan-and-australian-streamers).
To quote the source:

> Aussies particularly but other streaming service probably use it. [stan.com.au](http://stan.com.au/) will buffer and pause a lot if you use the OISD list. Put [youboranqs01.com](http://youboranqs01.com/) in the allow list in nextdns and streaming will work normal again. It appears to be something like a timing/ping service used to time the video segments in the stream. I havent dived deeper, but others have said its innocuous and not related to privacy...either way...no streaming until you unblock it. I tried adding a rewrite and it seems to work too, so this would be preferred to unblocking it.
> 
> Rewrite: [youboranqs01.com](http://youboranqs01.com/) → 127.0.0.1
> 
> Hope this helps.

### Why should the domain(s) be unblocked?

youboranqs01.com
youborafds01.com

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by emeritaacuity0u** [comment]
@hagezi these can be added to the blocklist again if you so wish.

It seems that the service has issues on born unfiltered AdGuard DNS and Google DNS after some time longer testing. I can't be positive these domains are required for it to work, but I can be sure it doesn't work permanently with them blocked.

**Comment by hagezi** [comment]
@emeritaacuity0u Thanks!
