### ISSUE TITLE
Whatsapp subdomains

### ISSUE THREAD

**Issue by AleIlMagno** [hagezi/dns-blocklists#3475]
### Which domain(s) should be blocked?

g.whatsapp.net
g-fallback.whatsapp.net

### Why should these domain(s) be blocked?

These domain seem to be called everytime the Whatsapp app is opened.
I've been blocking them for a few months and I would say that they don't affect any functionality. (except maybe the avatar creation which is already blocked in Ultimate)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
g.whatsapp.net is a backend service domain used by WhatsApp to manage the secure and efficient exchange of messages and other data between its users.
