### ISSUE TITLE
PCWorld Article Redirects

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#349]
#### What adblocker/DNS cloud service are you using?

NextDNS, Block Page = Disabled, CNAME Flattening = Disabled

#### Which blocklists are used?
Pro
Pro++
Ultimate

#### Which domain(s) should be unblocked?
`shop-links.co`
`adorama.rfvk.net`
`partners3.stacksocial.com`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking these domains breaks the ability to follow links to products or other sources on PCWord articles.

Example for `shop-links.co` Click, "Samsung Odyssey G50A gaming monitor for $349.99"
https://www.pcworld.com/article/1512324/1512324.html

Example for `adorama.rfvk.net` Click, "HP Victus 15L"
https://www.pcworld.com/article/813362/best-pc-computer-deals.html

Example for `partners3.stacksocial.com` CNAME for shop.pcworld.com Click, "mBeat 14-in-1 USB4 Docking Station"
https://www.pcworld.com/article/1481670/this-14-in-1-docking-station-is-20-off-now.html

**Comment by hagezi** [comment]
Thanks, removed and added to referral whitelist.
