### ISSUE TITLE
block gambling site like rummy poker and someother

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3497]
### Which domain(s) should be blocked?

https://www.rummycircle.com/
https://teenpattigold.com/
https://moonfroglabs.com/
https://www.my11circle.com/
https://www.dream11.com/
https://www.partypoker.com/en/
https://www.pokerlistings.com/
https://www.pokerbaazi.com/
https://www.rummyculture.com/
https://www.mpl.live/
https://www.a23.com/
https://www.rummytime.com/
https://www.classicrummy.com/
https://www.bigcash.live/
https://www.poker-king.com/cash-games/
https://www.playrummy.com/
https://www.silkrummy.com/
https://www.rummy-win.com/
https://www.adda52rummy.com/
https://www.gamezy.com/
https://firstgames.in/rummy-games
https://www.getrushapp.com/
https://www.zupee.com/
https://eazegames.com/
https://www.winzogames.com/
https://www.aio.games/

### Why should these domain(s) be blocked?

This tricks you with there initial winning and afterwards once you are addicted you will loose money.
Beware of online gambling scams. These platforms often lure in with initial wins some give 2 to 3time win some never, but once you're hooked/addicted, mostly works within 2days of playing, you will never win afterwards still you will win but the net result of that will be a loss the certain win will keep you hooked and make you trust this process. people lose money and time due to these deceptive practices. It's essential to be cautious and avoid falling victim to gambling fraud.
Some governments have put a ban on them still they find a flaw in system and law to come up with this.
### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by olumolu** [comment]
@hagezi hi pro plus still not provide this update on ne tdns

**Comment by iam-py-test** [comment]
Pro++ does not block gambling websites. There is a separate gambling list: https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#slot_machine-gambling---protects-against-gambling-content-
Thanks

**Comment by olumolu** [comment]
But nextdns don't have this listed.

**Comment by iam-py-test** [comment]
NextDNS doesn't allow custom lists, so you [either will have to convince them to add it](https://github.com/nextdns/metadata/issues/1337)*, use NextDNS's built in gambling blocking, or use an alternative provider.
I don't think there is anything hagezi can do to change this.
Sorry.
<details>
<summary>Off topic</summary>
Issue 1337...
</details>
