### ISSUE TITLE
youtube crypto scam

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#350]
#### Which domain(s) should be blocked?
teslax2claim.org
teslaeasy.io

#### Why should the domain(s) be blocked?
youtube live crypto scam 

see https://github.com/badmojr/1Hosts/issues for more info

**Comment by durablenapkin** [comment]
Thanks, queued to add to my Scam Blocklist in 1h08m.

**Comment by hagezi** [comment]
Thanks, added.
