### ISSUE TITLE
onevanilla.click: Potential badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3514]
### Which domain(s) should be blocked?

onevanilla.click

### Why should these domain(s) be blocked?

My browser/PC occasionally connects to this domain, likely while I'm browsing the web, but I haven't been able to track its source.

Out of curiosity, I visited the site, and it appears fake and suspicious, possibly pretending to be affiliated with `onevanilla.com`. The reason I feel like it's pretending to be affiliated is because the HTML title says `OneVanilla Card – Official Login To Activate Your OneVanilla Card`.

I could be wrong, but could someone please check it out? If it's potentially dangerous, could you please block it?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@MEtICaRT Looks at first like a non-official info page that refers to https://bilbocine.com/onevanilla-card/. In the article there, reference is made to the official page.

The page has no flags in security services.

Nevertheless, the design is reminiscent of a phishing site; such sites are often associated with fraudulent activities. The domain name “onevanilla.click” is chosen to resemble the official site of OneVanilla, a provider of prepaid cards. Fraudsters use such websites to trick unsuspecting users into revealing their personal data, credit card details or other confidential information.

Very suspicious for me.

@iam-py-test what do you think?

**Comment by iam-py-test** [comment]
> My browser/PC occasionally connects to this domain, likely while I'm browsing the web, but I haven't been able to track its source.

I missed that note. What browser extensions do you have installed? Does it still occur if all tabs are closed?
If you use Chrome, Edge, or another Chromium browser, check chrome://serviceworker-internals and see if there is any service workers from that website. The rough equivalent in Firefox is the service workers section at about:debugging#/runtime/this-firefox. Service workers run in the background, even after a tab is closed, so that could the source of the connections if a tab or extension is not at fault.
Thanks

**Comment by hagezi** [comment]
There is only crap on the IP:

```
alaskasworld.cfd
bilbocine.com
creditcardchase.click
direct2hr.click
marykayintouch.autos
mymercy.click
mymorri.click
onecognizant.click
onevanilla.click
panoramacharter.click
paybyplatema.cfd
surgecardinfo.click
unionplus-card.click
```

I block the domain and the “blog” at the same time.

**Comment by iam-py-test** [comment]
In light of your decision, I too have blocked both domains.
Thank you
