### ISSUE TITLE
cmp.quantcast.com: potential tracker

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3516]
### Which domain(s) should be blocked?

cmp.quantcast.com

### Why should these domain(s) be blocked?

This is a potential tracker domain that is being blocked by other filters, but not by the HaGeZi lists.

<img width="354" alt="image" src="https://github.com/user-attachments/assets/a52eb612-d87d-4c7d-abdf-78f7b73e8509">

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
See: https://github.com/hagezi/dns-blocklists/wiki/FAQ#cmps
