### ISSUE TITLE
Blocked selection options on chicsparrow.com

### ISSUE THREAD

**Issue by Fail-Safe** [hagezi/dns-blocklists#352]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
HaGeZi - Multi PRO++

#### Which domain(s) should be unblocked?
option.boldapps.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
When attempting to visit [this site](https://chicsparrow.com/collections/creme/products/creme-cascade?variant=41436531884212) and make selections for "TN Size" and "Inscription", the two dropdown boxes (and their corresponding labels) do not appear when `option.boldapps.net` is blocked. Without being able to make those selections, an order cannot be completed on the site.

Below is a screenshot of the working page after whitelisting `option.boldapps.net`.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/10307870/219096808-49a63177-6cc9-407f-874f-a4da2d36926c.png">

**Comment by hagezi** [comment]
Thanks for the detailed information, domain has been removed.

Ping source: @badmojr
