### ISSUE TITLE
graph.facebook.com

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3520]
### Which domain(s) should be blocked?

graph.facebook.com

### Why should these domain(s) be blocked?

This seems like analytics url

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked only in Ultimate, see "warning": https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#ultimate
