### ISSUE TITLE
appslist.heimdall.site

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#353]
#### What adblocker/DNS cloud service are you using?

Adguard Home and NextDNS

#### Which blocklists are used?
Ultimate and TLD

#### Which domain(s) should be unblocked?
appslist.heimdall.site

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is a check for icons for those who use heimdall: https://docs.linuxserver.io/images/docker-heimdall

With it being blocked it is blocking the service from grabbing the icon of the service you are trying to bookmark.

**Comment by hagezi** [comment]
Blocked by TLD list only.

ping @yokoffing @bestplayerbot for TLD exclusion

**Comment by yokoffing** [comment]
Fixed: https://github.com/yokoffing/filterlists/commit/21eb98e8d108c539414bac0cc1a835a9a9ff8963
