### ISSUE TITLE
[Enhancement] Blocklist IPs Microsoft Telemetry/Spy and other crap. 

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#3536]
@hagezi 

Maintainer has abandoned the blocklist project ( https://github.com/crazy-max/WindowsSpyBlocker ). Please, I have a huge favor to you, make the **IPs blocking list** for Microsoft products against spy, ads, telemetry.
I know, there it is a hosts format. 
Please consider. 

Regards

**Comment by hagezi** [comment]
I have my Microsoft native tracker list, this can be used as a replacement. Why an IP list? Blocking Microsoft IPs certainly has undesirable side effects because it also blocks other functions. Furthermore, these are also region-specific.
