### ISSUE TITLE
tempisite.com: badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3540]
### Which domain(s) should be blocked?

tempisite.com

### Why should these domain(s) be blocked?

I highly recommend blocking this as it's very often used for malicious purposes.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://www.virustotal.com/gui/domain/tempisite.com/details

**Comment by iam-py-test** [comment]
While I agree it looks suspicious, I do see potential legitimate use:
https://www.instagram.com/trangvit.nee/
https://vn.linkedin.com/in/minh-gia-8901491ab
https://github.com/NamOpt/hdisk
`https://gotartwork.com/ViewProfileBlogs.aspx?&id=160798&title=&dt=05,2024`
I will block the pages subdomain, as it is used in phishing - and the homepage has lorum ipsum text:
https://graibun.wordpress.com/2024/03/27/anuntul-final/
https://www.reddit.com/r/uBlockOrigin/comments/1f2faj4/where_do_i_send_a_phishing_site_to_be_blocked_by/
