### ISSUE TITLE
Do you include OISD, Steven Black etc.?

### ISSUE THREAD

**Issue by Alk2** [hagezi/dns-blocklists#3541]
Hello,

Firstly, thank you so much for this blocklist and the time that you put into curating it, it is much appreciated.

I have a question please: In yokoffing's guide, they say [here](https://github.com/yokoffing/NextDNS-Config?tab=readme-ov-file#why-hagezi) that your list includes:

> Hagezi's primary DNS lists combine multiple [sources](https://github.com/hagezi/dns-blocklists/wiki/FAQ#-which-sources-are-used-for-the-lists-and-how-are-the-lists-compiled-on-the-basis-of-these-sources) including respected community blocklists like [OISD](https://oisd.nl/), [Steven Black](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts), [1Hosts](https://github.com/badmojr/1Hosts#safeguard-your-devices-against-pesky-ads-trackers-and-malware), [notrack](https://gitlab.com/quidsup/notrack#notrack), and [more](https://github.com/hagezi/dns-blocklists/blob/main/sources.md).

But I cannot find in your [sources](https://github.com/hagezi/dns-blocklists/blob/main/sources.md) list, or on your statistics page, any mention of including OISD or Steven Black lists. 
So please forgive me for troubling you, but could you confirm whether you do include OISD and Steven Black blocklists? 
I haven't checked for 1Hosts and notrack, could you confirm that too please?

Thank you very much.

**Comment by hagezi** [comment]
My lists are not simply 1:1 copies of sources, see: https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources
