### ISSUE TITLE
sanadietzman.click: badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3542]
### Which domain(s) should be blocked?

sanadietzman.click/f_bilagod

### Why should these domain(s) be blocked?

This is a fake link in the bios of some Twitter bots that redirects to google.com when opened on a PC, so a mobile user agent is likely necessary for testing. HaGeZi lists do not block it.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added, thanks
