### ISSUE TITLE
Fake Joann websites

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3543]
### Which domain(s) should be blocked?

joannstoressales.shop
joannmax.com
joannofficial.com
joannoutlet.com
joannclearances.com

### Why should these domain(s) be blocked?

Fake phishing domains pretending to be `joann.com`

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added, thanks
