### ISSUE TITLE
Twitch drop progression is being blocked

### ISSUE THREAD

**Issue by BourbonCrow** [hagezi/dns-blocklists#355]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
Hagezi Ultimate

#### Which domain(s) should be unblocked?
*.pdx01.abs.hls.ttvnw.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Twitch drops progression does not go up when this domain is blocked they are stuck at 0% i whitelisted it my self in NextDNS ui and then progression started to go up,  i post a image of NextDNS block log below cause I'm not 100% sure what it means when it shows like that with that arrow pointing to spade.sci.twitch.tv

https://i.imgur.com/11jLE5I.png

**Comment by hagezi** [comment]
Thanks, blocked by CNAME `spade.sci.twitch.tv`, removed.

ping source: @badmojr
