### ISSUE TITLE
Potential badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3550]
### Which domain(s) should be blocked?

m.wyy158.fun
b.cse38.xyz

### Why should these domain(s) be blocked?

These links are spammed in Twitter DMs by bots. They redirect to YouTube.com on PC, so a mobile user agent might be needed for analysis.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added, thanks
