### ISSUE TITLE
jaborcall.app: badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3551]
### Which domain(s) should be blocked?

jaborcall.app

### Why should these domain(s) be blocked?

The domain should be blocked because it is linked to a malicious Trojan horse disguised as a legitimate AI translation meeting app, which is used by scammers to hack and steal confidential information from unsuspecting users.

More info: https://x.com/izutorishima/status/1828044783375532415

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via uBlock Badware

**Comment by iam-py-test** [comment]
Added to my list anyway. Thanks
