### ISSUE TITLE
HaGeZi - Multi PRO++ in NextDNS is blocking HelpScout tech support system

### ISSUE THREAD

**Issue by IanRandall** [hagezi/dns-blocklists#3560]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

https://secure.helpscout.net

### Why should the domain(s) be unblocked?

Its a valid Helpdesk system for user tech support

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/3557
