### ISSUE TITLE
Potential badware domains

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3565]
### Which domain(s) should be blocked?

```
vip󠄺u󠄺rl󠄺.󠄺pro/hotlady
snapbabes9.com
find-singles-online.com
singleflirt.com
jucydate.com
unlimdate.com
charmfling.com
exosrw.com
bestdates.com
```

(There are many more potential domains that could be blocked, just a few visits to the first link can reveal dozens of different URLs)

### Why should these domain(s) be blocked?

The first URL is being posted by fake accounts on xHamster, as seen in the screenshot I attached below.

After opening it, you're being redirected and  prompted with a few questions before being redirected again to a "legit-looking" website that asks for your email to create an account.

However, after entering fake credentials, no account is actually created, from what I understand. Instead, you're redirected to yet another website with more questions, and at the end, it asks you to create another account. This process repeats again and again, with multiple redirects. Each browsing session seems to result in a different scammy redirect.

Another potential indication that this might be a scam domain is the fact that it exists under multiple TLDs, such as .online and .in.

I didn't include the full URLs with the queries because I use Browserling, and it's a bit complicated to copy and paste between the VM and my computer. However, if necessary, I can try to include them.

`exosrw.com` and `find-singles-online.com` are the most suspicious of them all, as they have numerous random character subdomains with similar scammy NSFW content. The others are likely scams as well, due to the fake account processes and forced redirections, but I can imagine the owners might dispute this.

Here is a full URL example for `find-singles-online.com`: `https://w80q7h4j6ti8ivp3jjdmtqd8.find-singles-online.com/vlm-woo-wooi/`

I'm pretty sure there are even more domains to report, but this is what I found from the minimal testing I did.

Please take a look, and based on your expertise, does this seem malicious, and do you think it's worth adding to the filter list?

![image](https://github.com/user-attachments/assets/099e4d8a-fed2-4b30-bf2e-e509b7d59025)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@iam-py-test
https://www.virustotal.com/gui/domain/vipurl.pro/details

**Comment by iam-py-test** [comment]
vipurl.pro seems to be a fully functional URL shortner (though I didn't see any legitimate use of it...), so I do not plan to block it as malicious.
However, the URL in the original post has some unusual characters which alter it's rendering:
![image](https://github.com/user-attachments/assets/02584e40-9851-4558-a096-7a361977f561)
