### ISSUE TITLE
Myprotein App

### ISSUE THREAD

**Issue by IDKwhattoputhere** [hagezi/dns-blocklists#3580]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

Allow:
```
myprotein-de.api.thehut.net
myprotein-en.api.thehut.net
```

Deny:
```
csp.thehut.net
eum.thehut.net
techmktg.thehut.net
```

### Why should the domain(s) be unblocked?

Myprotein Android App needs the first two otherwise the basket stays empty.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by Dynamic5912** [comment]
The Hut Group (https://www.thg.com/) is a well known online retail group. 

I'm not sure why thehut.net is blocked when the majority of their brand apps and websites use it?
