### ISSUE TITLE
Allow qr-code-generator.com

### ISSUE THREAD

**Issue by zhg7** [hagezi/dns-blocklists#3581]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

qr-code-generator.com

### Why should the domain(s) be unblocked?

Self-explanatory.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by bondskin** [comment]
The domain "http://l.ead.me" is pointing to this domain, however, this short name is blocked by NextDNS Threat Intelligence Feed
<img width="264" alt="image" src="https://github.com/user-attachments/assets/3a809ff9-7ea7-47fa-9d70-8ece9cb8be46">
