### ISSUE TITLE
InMobi

### ISSUE THREAD

**Issue by levinberg** [hagezi/dns-blocklists#3582]
### Which domain(s) should be blocked?

`cmp.inmobi.com`

### Why should these domain(s) be blocked?

Loads [InMobi](https://en.wikipedia.org/wiki/InMobi) advertisement. Also blocked by Firefox ETP.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/wiki/FAQ#cmps

https://github.com/hagezi/dns-blocklists/issues/2688
https://github.com/hagezi/dns-blocklists/issues/1981
