### ISSUE TITLE
weborama.fr

### ISSUE THREAD

**Issue by rowboatz** [hagezi/dns-blocklists#3588]
### Which domain(s) should be blocked?

`weborama.fr`

### Why should these domain(s) be blocked?

Weborama is 'an AdTech pioneer in semantic artificial intelligence in France and Europe' (their own words). Your lists contain several subdomains of `weborama.fr`, but not the domain itself even though others like `weborama.com` are listed.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Referral domain allowed:

solution.weborama.fr
