### ISSUE TITLE
google news ads

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3592]
### Which domain(s) should be blocked?

encrypted-tbn3.gstatic.com
encrypted-tbn2.gstatic.com
encrypted-tbn1.gstatic.com
encrypted-tbn0.gstatic.com

### Why should these domain(s) be blocked?

This domain load the news stuff in google news but this are ads as different users will see different news stuff.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
This breaks a lot ...

**Comment by olumolu** [comment]
> This breaks a lot ...

Sorry for asking but i couldn't find anything as such broken.
Mainly I don't use google services i use youtube some gmail some g drive. So couldn't find the broken stuff.

**Comment by hagezi** [comment]
@olumolu Simply research the details online beforehand.

The domains `encrypted-tbn*.gstatic.com` is used by Google and is part of the Content Delivery Network (CDN), which is used to deliver images and other media files to various Google services. The main purpose of this domain and the associated CDN is to load images quickly and efficiently by delivering them via geographically distributed servers.

Google Maps or Google News use these domains, for example, to load images or map sections.
