### ISSUE TITLE
Any chance for an Adhell3 list?

### ISSUE THREAD

**Issue by brn-s** [hagezi/dns-blocklists#3595]
Adhell3 is limited to 15000 domains so it would be very niche.
But it would be nice if there was an alternative to the built-in Adhell3 hosts file. 
Thank you.

**Comment by hagezi** [comment]
No, far too time-consuming and with this maximum size it is difficult to create an effective list.

**Comment by brn-s** [comment]
Thanks for all the work you already do.

Took about a few hours and learned the APK can be rebuilt so I upped the limit to a billion and changed the default blocklist URL to your Ultimate blocklist and added TIF on top.
