### ISSUE TITLE
scam and spam and phishing site

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3602]
### Which domain(s) should be blocked?

ddbca.localmeets.link
localmeets.link

### Why should these domain(s) be blocked?

https://trafficlight.bitdefender.com/info/?url=http://ddbca.localmeets.link
https://www.fortiguard.com/webfilter

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by olumolu** [comment]
I saw it is just added

**Comment by iam-py-test** [comment]
Added to my filterlist. Thanks
