### ISSUE TITLE
Please, add an ad blocker Pro ++

### ISSUE THREAD

**Issue by Seple** [hagezi/dns-blocklists#3606]
### Which domain(s) should be blocked?

+ https://www.lm.pl/
localization baners advertising:
a5.lm.pl
b.lm.pl
*.lm.pl (random.lm.pl)

+ https://www.przegladkoninski.pl/
localization baners advertising:
https://www.przegladkoninski.pl/data/banners/

### Why should these domain(s) be blocked?

Annoying ads (regional newspapers)
Thank you for the good work you have done

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
My lists are DNS lists, in which only domains and subdomains can be blocked, but not URLs.

https://www.przegladkoninski.pl/data/banners/

Cannot be blocked unless I block the main domain, but this blocks the whole site.

**Comment by hagezi** [comment]
@Fademind Can you support whether there is something blockable for DNS?

**Comment by Seple** [comment]
I'm sorry, I didn't know that it was impossible to block this folder: https://www.przegladkoninski.pl/data/banners/

**Comment by hagezi** [comment]
Thanks @FadeMind ;)
