### ISSUE TITLE
mcdreward.com

### ISSUE THREAD

**Issue by 4d62** [hagezi/dns-blocklists#3608]
### Which domain(s) should be blocked?

mcdreward.com

### Why should these domain(s) be blocked?

some scam survey thing found on tiktok 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
> GET YOUR MCDONALD'S $100 GIFT CARD - Follow the steps below to get your Mcdonald's gift card. Click the button below. Answer questions. Fill out information. Complete deals. Get Your $100 Giftcard. CLAIM NOW

Sounds legit.
Blocklisted, thanks.
