### ISSUE TITLE
fake and spam -news- propaganda websites

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3609]
### Which domain(s) should be blocked?

https://opindia.com/
https://postcard.news/
https://swarajyamag.com/
https://indiafacts.org/
https://www.indiafacts.org.in/
https://tfipost.com/

### Why should these domain(s) be blocked?

This websites are genuinely harmful for the sociality and they intentionally pour hate and false fake news and right wing propaganda to the masses and they are mostly funded by the rulling party and a anti social organisation called rss.
They usually fuel the hate and thehy ask for vote in the name of that.
They way it works is "i will save the pure blood of Germany"
And here "i will save the pure blood of hindu"
Here is an another
Source:
1) https://en.wikipedia.org/wiki/OpIndia
2) https://thelondonstory.org/report/atmosphere-of-hate-opindia/
3) https://research.rug.nl/en/publications/an-atmosphere-of-hate-case-of-opindia
4) https://www.boomlive.in/tags/opindia
5) https://indianexpress.com/article/cities/chennai/tamil-nadu-police-book-opindia-ceo-editor-in-chief-fake-news-migrant-workers-8483380/
6) https://www.bellingcat.com/news/2024/05/28/how-hindu-nationalist-far-right-india-websites-money/
7) https://caravanmagazine.in/media/toxic-business-opindia-anti-journalism
8) https://theprint.in/india/postcard-indiatimes-in-poynter-list-of-513-fake-news-websites/230016/
9) https://www.wired.com/story/india-opindia-google-facebook-advertising/

This are the most harmful news organisations providing hate.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by olumolu** [comment]
Add this to pro/pro+/ultimate

**Comment by olumolu** [comment]
Swaraj and opindia are linked to the same man called amit malviya.
Opindia is well known to be the fake news manufacturer.

**Comment by hagezi** [comment]
I try to avoid censorship with the lists. The domains listed include domains that can be found on popular top lists such as Umbrella, Cloudflare and others. In other words, they are popular.

That might be something for a pure fake news list, but I don't maintain such a list.

**Comment by olumolu** [comment]
You have a spam fake catagory and i have given you the proof this was well researched if you need i can give more research about this police have even arrested due to there fake news and which lead to a mob Lynching. And a death. I don't know why you think it is censorship it is not. They make news themself like some days ago they give news that a muslim community destroyed a hindu temple with some images later alt news show that it was a 12 years old image from bangladesh. So you can understand what they do.
I request you to add them.
