### ISSUE TITLE
cstat.cdn-apple.com

### ISSUE THREAD

**Issue by emeritaacuity0u** [hagezi/dns-blocklists#3610]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

cstat.cdn-apple.com

### Why should the domain(s) be unblocked?

It's required to use [Apple's network responsiveness tool](https://support.apple.com/en-us/101942).
On macOS, the test completes with a fault at the end.
On iOS/iPadOS/WatchOS, the test fails to start.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by bondskin** [comment]
@hagezi , it appears to be still blocked, once I removed it from my Allowlist

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/e18b3842-a302-4273-9f9d-45703d662278">

**Comment by hagezi** [comment]
Thanks, fixed on next release.

**Comment by bondskin** [comment]
> Thanks, fixed on next release.

Hi @hagezi , sorry for bumping this topic (again).
I see that cstat.apple.com.edgesuite.net is still blocked

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/3a617bbb-bc56-467d-b1d1-fea9a6718a6e">

**Comment by hagezi** [comment]
This is CNAME of cstat.apple.com which is also blocked.

However, your issue was for cstat.cdn-apple.com.

Does blocking lead to the same problems?

**Comment by bondskin** [comment]
Thanks for your swift reply, I am not noticing any problems but just seeing the block notification.
It seems that there are multiple hostnames for the same server/service.
