### ISSUE TITLE
Redtrack delisting

### ISSUE THREAD

**Issue by mitko9922** [hagezi/dns-blocklists#3612]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO mini, Multi PRO++, Multi PRO++ mini

### Which domain(s) should be unblocked?

redtrack.io
app.redtrack.io
docs.redtrack.io
ecomappbcom.redtrack.io
www.redtrack.io

### Why should the domain(s) be unblocked?

It's a tracking platform and I don't see anything malicious or advertising type. I personally use it for google campaigns and I think it should be delisted.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
It is tracking and therefore blocked.
