### ISSUE TITLE
YouTube Thumbnails not loading on iOS app

### ISSUE THREAD

**Issue by alirizv** [hagezi/dns-blocklists#3618]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

I have already added i.ytimg.com and s.youtube.com to my allowlist. I am not sure what else I can unblock to ensure the thumbnail images load correctly on the YoutTube iOS app

### Why should the domain(s) be unblocked?

s.youtube.com
i.ytimg.com

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The domains are not blocked in my lists and there is no problem with loading the thumbnails. Your problem is not caused by my blocklists.
