### ISSUE TITLE
Site names in other languages?

### ISSUE THREAD

**Issue by mahmoudhamadeh** [hagezi/dns-blocklists#3619]
### Which domain(s) should be blocked?

```
||*บ้*.*
||*า*.*
||*น*.*
||*มื*.*
||*อ*.*
||*ส*.*
||*อ*.*
||*ง*.*
||*ช*.*
||*ล*.*
||*บุ*.*
||*รี*.*
```

### Why should these domain(s) be blocked?

I found my son is able to use some proxy bypass sites found in sources shared between kids in schools like this one "https://sites.google.com/view/wolfunblock/home". IDNs are formed using characters from different scripts, such as Arabic, Chinese, Cyrillic or Devanagari. I was able to add some wildcard to block IDN in my sample, but I'm sure there is a better way to restrict only English scripts.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
For compatibility reasons, I cannot block IDNs with wildcards. My lists are based on valid plain domains that are provided in different formats.

This is something for the personal block list.

There is always a way to get past the bypass list.

**Comment by mahmoudhamadeh** [comment]
understood, thank you!
