### ISSUE TITLE
Pro++ not blocking domains on Spiegel

### ISSUE THREAD

**Issue by Chippel** [hagezi/dns-blocklists#3620]
### Which domain(s) should be blocked?

dspcluster.adfarm1.adition.com
Paid.outbrain.com

### Why should these domain(s) be blocked?

They rollout ads. 

![IMG_1448](https://github.com/user-attachments/assets/d5d0acb1-25b1-482b-b2ff-5e7ee7ff69f3)
![IMG_1449](https://github.com/user-attachments/assets/3587f090-ef6f-440f-b1e3-c883a44c739f)

funny enough though: if I click on these ads they get blocked as expected. I don’t why they are shown beforehand. Seems like other blocklists block those ads. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
dspcluster.adfarm1.adition.com and paid.outbrain.com is blocked in all list versions.

**Comment by Chippel** [comment]
Yes, you’re right. I just checked it and can confirm. This is an odd behavior then. When I use oisd for example I won’t see the ad gou see in the screenshot. I wonder why I see those apps in the app even though they’re blocked. Do you have my idea?

**Comment by hagezi** [comment]
I see the ads from time to time too, I'll have to take a closer look. They sometimes seem to be loaded from internal domains.

**Comment by Chippel** [comment]
Thanks Gerd. Appreciate your work for the community.

**Comment by hagezi** [comment]
@Chippel 
I have found the problem, when the tracker uobsoe.com is blocked, the ads from cdn.prod.www.spiegel.de are loaded. Unblocking the tracker also makes the ads disappear.

![grafik](https://github.com/user-attachments/assets/ce5e11be-e643-48ab-a8fa-d812a25ee6ca)

The domain will be removed with the next update.

**Comment by hagezi** [comment]
Ads are back on spiegel.de, unblocking `benelph.de` makes the ads disappear again. Seems to be used by ad reinjection script for adblock detection. Will be fixed in the next release.

Ref: https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1764
