### ISSUE TITLE
popular websites are not working

### ISSUE THREAD

**Issue by Seple** [hagezi/dns-blocklists#3622]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

filmweb.pl 

you can't watch trailers 
https://www.filmweb.pl/trailers

### Why should the domain(s) be unblocked?

you can't watch trailers

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by Seple** [comment]
another website that doesn't work 

https://[www.kinomaniak.pl](https://www.kinomaniak.pl/)/

is a website created on the model of www.imdb.com. There you will find films with all promotional materials - poster, trailer, announcements in Polish and English and user ratings. It does not offer the opportunity to watch the film for free online. There you will find not only full-length films, but also movies and series with detailed descriptions.

**Comment by Seple** [comment]
Why aren't these sites working?

**Comment by hagezi** [comment]
@Seple

`filmweb.pl` not blocked in my lists.

`kinomaniak.pl` blocked via [KAD](https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADomains.txt) 

```
Secure DNS:
 - 360Secure       OK
 - AliDNS          OK
 - CFIEC           OK
 - CleanBrowsing   OK
 - Cloudflare      OK
 - ComodoSecure    OK
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - DNSWatchGO      OK
 - HaGeZi.TIF      BLOCKED
 - Neustar         BLOCKED
 - NextDNS.TIF_AI  OK
 - NortonCS        OK
 - NRD.DGA.IDN     OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        BLOCKED
 - Umbrella        OK
 - YandexSafe      OK

Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - CONTROLD.AT     BLOCKED
 - DevDansHosts    OK
 - EasyList        OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.TIF      BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          OK
 - OISD.Big        BLOCKED
 - OISD.Small      OK
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
```

https://www.virustotal.com/en/domain/kinomaniak.pl/information/

**Comment by hagezi** [comment]
Thanks @Fademind

**Comment by Seple** [comment]
Kinomaniak.pl is not the same as Kinomaniak.tv (pirate domain), people often confuse them. 

What I care most about is unblocking the very popular film website filmweb.pl in Poland comparable and similar to imdb.com

**Comment by hagezi** [comment]
@Seple It's all above, f`ilmweb.pl` is not blocked in my lists and to watch the trailers I have given you the two ads/tracking domains that you need to unblock.

**Comment by Seple** [comment]
OK! Thank you gentlemen ;)

**Comment by krystian3w** [comment]
Mogę zmienić z `$all` na `$doc` i się odblokuje na HOSTS/DNS/Pi-Hole/Routerze a w uBo można na stałe dodać by zniknęła tam plansza strict block.
