### ISSUE TITLE
Please add rules.

### ISSUE THREAD

**Issue by biange200** [hagezi/dns-blocklists#3625]
http://rssv.cn/adguard/

https://github.com/TG-Twilight/AWAvenue-Ads-Rule
    https://flowus.cn/share/f5b48261-8aed-49a2-bdd2-9b75b20f6ba9

https://ghproxy.net/https://raw.githubusercontent.com/qq5460168/666/master/dns.txt

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources

**Comment by biange200** [comment]
> https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources



![Screenshot_20240904_230142.jpg](https://github.com/user-attachments/assets/2ab8456e-5d91-4571-9a5e-5e23748099ae)

Which of your rules is included in this rule of Awavenue ads ruls?
