### ISSUE TITLE
Can this be blocked permanently?

### ISSUE THREAD

**Issue by Seple** [hagezi/dns-blocklists#3628]
### Which domain(s) should be blocked?

arc.msn.com

Can this be permanently added to ad blocking lists?

### Why should these domain(s) be blocked?

Remove sponsored info slots in the system menu and get rid of frequent domain pinging in windows

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Only in Ultimate, breaks Windows Spotlight/Search and Gamepass GPU Perks.
