### ISSUE TITLE
False positiv 

### ISSUE THREAD

**Issue by T74875** [hagezi/dns-blocklists#363]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?

HaGeZi - Multi PRO++

#### Which domain(s) should be unblocked?

img.yana.asideas.de

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Upday App (IOS) dont load news when this domain is blocked

**Comment by hagezi** [comment]
Thanks, blocked by CNAME `prod-image-fastly-cdn.yana.asideas.de`, will be removed.

ping source: @badmojr
