### ISSUE TITLE
Kodmyra.se E-Commerce Platform Provider (Analytics)

### ISSUE THREAD

**Issue by miansopi** [hagezi/dns-blocklists#3638]
### Which domain(s) should be blocked?

beacon.kodmyra.se

### Why should these domain(s) be blocked?

Used on sites like nkv.se and partyhallen.se. Based on the name and what Kodmyra is saying it can provide to its customers, it seems to be some kind of analytics. Blocked domain, nothing seemed broken.

Script loaded on the sites: https://beacon.kodmyran.se/v1/beacon.js

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Will be fixed in next release.
