### ISSUE TITLE
Block yet another Steam phishing

### ISSUE THREAD

**Issue by zhg7** [hagezi/dns-blocklists#3641]
### Which domain(s) should be blocked?

deadlockbetatest.com

### Why should these domain(s) be blocked?

https://github.com/hagezi/dns-blocklists/issues/3634 https://github.com/hagezi/dns-blocklists/issues/3596
``https://deadlockbetatest.com/invitation``
``https://deadlockbetatest.com/invite``

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added to my blocklist. Thanks
