### ISSUE TITLE
Abusive TLD's Allow for these ee domains

### ISSUE THREAD

**Issue by BourbonCrow** [hagezi/dns-blocklists#3642]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

acs.edb.com
acs2.edb.com
mpi2.sveaekonomi.modirum.com

### Why should the domain(s) be unblocked?

These are being blocked .ee in abusive TLD's
Required for VISA payment on some sites not sure if there is more then acs and acs2  and mpi2 but thats the once i found and had to whitelist since they are blocekd by .ee means its a CNAME (not sure how to look that up so if not to much to ask i leave that to you)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@BourbonCrow .ee os not blocked by Most Abused TLDs

**Comment by BourbonCrow** [comment]
> @BourbonCrow .ee is not blocked by Most Abused TLDs

oh damn sorry, i must have a outdated list then time to make sure its updated, my fault for not confirming that.

**Comment by hagezi** [comment]
No problem, it may be that the TLD was once blocked, but that was a long time ago ;)
