### ISSUE TITLE
Ads domains at IP range `139.45.197.0/24`

### ISSUE THREAD

**Issue by vhpcdpgl** [hagezi/dns-blocklists#3644]
### Which domain(s) should be blocked?

[new 6.txt](https://github.com/user-attachments/files/16906122/new.6.txt)

### Why should these domain(s) be blocked?

Ads domains
Some domains/IPs listed here: `https://gosecure.ai/blog/2024/07/22/web-browser-notification-threat-more-alarming-than-expected/`

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/commit/bebb75010e522d9f24fd4c373e3cfac23abe33b3
