### ISSUE TITLE
Facebook Video CDN

### ISSUE THREAD

**Issue by nilagangmanok** [hagezi/dns-blocklists#3655]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

xy.fbcdn.net
xz.fbcdn.net

### Why should the domain(s) be unblocked?

Some contents (stories, videos) don't load on Facebook mobile app.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by bondskin** [comment]
Hi @nilagangmanok , are you certain?

At the moment it blocks effectively hosts like "...-netseer-ipaddr-assoc.xy.fbcdn.net" and similar.
No issues with videos in FB, may be your videos are coming from a different source?

**Comment by hagezi** [comment]
I can't reproduce this either. I have several Facebook users in the network and so far there have been no complaints.

**Comment by nilagangmanok** [comment]
I'm not certain because I'm unable to reproduce on my end now. I will monitor about this. Thank you.
