### ISSUE TITLE
Remove "a-17.1fichier.com" from TIF Blocklist

### ISSUE THREAD

**Issue by fabianschulz** [hagezi/dns-blocklists#3666]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

a-17.1fichier.com

### Why should the domain(s) be unblocked?

(Using TIF Mini List, but the domain is also present in the Full list)

1fichier.com is a normal Filehost, a-17.1fichier.com is one of their (many) download server-hosts. It should be safe to remove it from the TIF list.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via URLhaus abuse filter
