### ISSUE TITLE
HaGeZi's Gambling Blocklist ||music.amazon.de^

### ISSUE THREAD

**Issue by privacy-advo** [hagezi/dns-blocklists#3669]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### With which block list(s) does the problem occur?

Gambling

### Which domain(s) should be unblocked?

music.amazon.de

### Why should the domain(s) be unblocked?

No gambling

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Thanks, will be removed adap.

Source: @alsyundawy

**Comment by alsyundawy** [comment]
done
