### ISSUE TITLE
Still not blocked - patronus.idata.shopeemobile.com

### ISSUE THREAD

**Issue by nilagangmanok** [hagezi/dns-blocklists#3672]
### Which domain(s) should be blocked?

patronus.idata.shopeemobile.com

### Why should these domain(s) be blocked?

Tracker.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
WTF ... it is allowed ... See: https://github.com/hagezi/dns-blocklists/issues/1428

@nilagangmanok Can you check the reason?

**Comment by nilagangmanok** [comment]
SPayLater uses **h5.paylater.scredit.ph** and **cdn.scredit.sg**, blocking these breaks the SPayLater page.
