### ISSUE TITLE
Subway app can't show ETA for order

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#3673]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO, Threat Intelligence Feeds

### Which domain(s) should be unblocked?

Possibly one or more of these:
```
subwayfranchiseadvertising.data.adobedc.net
api.apptentive.com
dxp.kaxsdc.com
```

I haven't isolated it because of the nature of the bug and it's on my mobile device. However, I wanted to document it.

### Why should the domain(s) be unblocked?

Once you place an order with the Subway app, your ETA for pickup will never load under **Order Details**. This has happened twice now.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
subwayfranchiseadvertising.data.adobedc.net only blocked in Ultimate

api.apptentive.com is widely blocked, e.g. by AdGuardDNS

dxp.kaxsdc.com might be a candidate, via @reverendretro

**Comment by hagezi** [comment]
I don't use the app, nor do I have an account or order there, so I can't test it myself.

**Comment by yokoffing** [comment]
I will try to test again soon. I didn't have time to diagnose because 1) mobile app and 2) on my lunch break lol. It could be something besides those three, but that's what kept popping up in my logs.

**Comment by yokoffing** [comment]
I had to refresh once or twice, but it seems to be working now. Maybe it's just bad app code, which can be common on food apps lol.
