### ISSUE TITLE
www.careerpower.in

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3681]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

www.careerpower.in

### Why should the domain(s) be unblocked?

This is a service that coach for competitive exams 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@bongochong

**Comment by bongochong** [comment]
As usual, thanks for the ping @hagezi!
