### ISSUE TITLE
Wiz mobile app blocked by TLD folder on controld

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3688]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

status.wiz.world
api.wiz.world
ws.wiz.world

### Why should the domain(s) be unblocked?

Wiz is "smart lights" app where I control my home lights.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The domain is already in the TLD allow folder.

https://github.com/hagezi/dns-blocklists/blob/0282f96803ae7d7585f3a43d9b433a8844fb7150/controld/spam-tlds-allow-folder.json#L2237

**Comment by user716253** [comment]
> The domain is already in the TLD allow folder.
> 
> https://github.com/hagezi/dns-blocklists/blob/0282f96803ae7d7585f3a43d9b433a8844fb7150/controld/spam-tlds-allow-folder.json#L2237

I found that the issue is that controld requires these kinds of wildcards to have the * key in front of the domain for it to unblock those subdomains.

so the rule should be *wiz.world

I tried this and it fixed the issue.

more info here
https://docs.controld.com/docs/custom-rules
*.domain.com -> BLOCK	Blocks all subdomains of domain.com but NOT domain.com

**Comment by user716253** [comment]
I have suggested an edit for their docs. let's see if they correct it.

**Comment by hagezi** [comment]
That used to work, then they changed something. I'll have a look when I have time.

**Comment by user716253** [comment]
> That used to work, then they changed something. I'll have a look when I have time.

Thank you. Really appreciate your work here!

**Comment by hagezi** [comment]
@yegors, currently this does not work as described in the documentation to unblock wiz.world and all subdomains, a custom bypass rule must be created for wiz.world and *.wiz.world. Did you change something or is this a bug?

**Comment by yegors** [comment]
There were several changes to the DNS server, but nothing specific to this, so it could be a regression. We're looking into it.

**Comment by hagezi** [comment]
Thanks @yegors, I'll wait for your feedback before I adjust anything in the TLD allow folder.

**Comment by user716253** [comment]
Any new info? @yegors @hagezi

**Comment by hagezi** [comment]
I have not yet received any further information on this, I am still waiting to hear back.

**Comment by yegors** [comment]
We're fixing the issue and putting back the old behavior. Should be deployed soon.

**Comment by hagezi** [comment]
Thanks @yegors

**Comment by yegors** [comment]
We're canarying a fix in some datacenters now. If all is well, it will be widely deployed in the next 24-48hrs.

**Comment by yegors** [comment]
@hagezi This is deployed, and should behave as it did before.

**Comment by hagezi** [comment]
Thanks @yegors, it works again as expected.
