### ISSUE TITLE
Perhaps there are new whatsapp tracking domains

### ISSUE THREAD

**Issue by petergithubuser** [hagezi/dns-blocklists#3729]
### Which domain(s) should be blocked?

Hello, I am using hagezi multi normal list in NextDNS.io

I monitor all input and output connections of my smartphone (an Android 10). I have installed WhatsApp 2.24.18.80 from PlayStore (the latest stable version so far). I realized that my WhatsApp no ​​longer makes any connection to the track domain dit.whatsapp.net (https://faq.whatsapp.com/538382354780857/)

On the other hand, the WhatsApp domain with the largest number of queries on my smartphone is g.Whatsapp.net

When I blocked it, whatsapp automatically tries to send data to g-fallback.whatsapp.net, which was also blocked soon after by me. After the 2 domains blocked, I did all the tests and all services continue to work.

mmg.whatsapp.net and graph.whatsapp.com are used to make voice and video calls

graph.facebook.com is used to load whatsapp profile photos

media-nyc4-2.cdn.whatsapp.net, media.fsdu25-1.fna.whatsapp.net and all "media-...cdn.whatsapp.net" and  "media...whatsapp.net" domains are used to send and receive photos, videos, audio messages and text messages.

Please check on these two domains, but I believe whatsapp has probably migrated the old tracking domain dit.whatsapp.net to g.whatsapp.net and if it fails, then it will try to connnect to g-fallback.whatsapp.net shortly thereafter

Thank you very much

### Why should these domain(s) be blocked?

g.whatsapp.net and g-fallback.whatsapp.net

![image](https://github.com/user-attachments/assets/c2f90029-1308-4558-a2a9-2d438830c406)
![image](https://github.com/user-attachments/assets/e802c3f4-9195-491a-b883-c444285ca3df)
![image](https://github.com/user-attachments/assets/68217a60-64e5-43dc-9fcb-89c287bab488)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
g.whatsapp.net is a backend service domain used by WhatsApp to manage the secure and efficient exchange of messages and other data between its users.

**Comment by petergithubuser** [comment]
In a week period analyzed, there were literally zero queries to dit.whatsapp.net and more than 500 queries to g.whatsapp.net

I don't believe whatsapp has stopped tracking users. That's why I suppose this g.whatsapp.net domain is being used for new purposes, which were once the responsibility of dit.whatsapp.net

**Comment by hagezi** [comment]
I still see the dit calls with the current version. Of course, it is possible that g.whatsapp.net is also used for tracking, like the Facebook Graph tracker. However, this backend service is also used for the secure transmission of messages, the CNAME is chat.cdn.whatsapp.net. I can't imagine that blocking won't lead to any restrictions.

**Comment by hagezi** [comment]
The domain is also used in the WhatsApp API to establish a connection to WhatsApp. E.g. for own projects that use WhatsApp, see under "Connection":

https://github.com/ben221199/WAPI

Not a good idea to block this domain.
