### ISSUE TITLE
Allow games website

### ISSUE THREAD

**Issue by zhg7** [hagezi/dns-blocklists#3730]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

7k7k.com

### Why should the domain(s) be unblocked?

Flash games website

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@bongochong

**Comment by bongochong** [comment]
Thanks @hagezi! Will get on whitelisting this as well.
