### ISSUE TITLE
Fake steam login / game team voting phishing pages

### ISSUE THREAD

**Issue by Codfish246** [hagezi/dns-blocklists#3731]
### Which domain(s) should be blocked?

https://expert.lunarbattle.pro/zone/elite/
https://midway-canada.midwayauth.pro/8f1e4c1d5
https://csbestplayers.com/?vote/teamlions
https://csbestplayers.com/3Z0ToILHY7/figa8rg72p/t1qlptvxwl?q=3Z0ToILHY7&amp;s=54497dfe3eb72c41db96e00d0a10867e

### Why should these domain(s) be blocked?

I understand the note about manually added phishing domains, but one of these domains (midwayauth.pro) has already existed for 2.5 months already
It is a chat message spread phishing campaign which gets you to log in to an official-looking fake steam login window by creating an iframe that looks like a new browser window
![firefox_tEfL4ci5zg](https://github.com/user-attachments/assets/48a8151a-03f7-4bf3-a9ff-9cdb165fc954)
![firefox_pkVes0dZr3](https://github.com/user-attachments/assets/3b527fb1-1a75-47b3-b9db-fbcd3a675eb1)
![firefox_pJMhfkqEgu](https://github.com/user-attachments/assets/45b090da-0fac-42bb-8432-3708a8fa59d4)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added, thanks.
