### ISSUE TITLE
Allow metric.surfshark.com

### ISSUE THREAD

**Issue by FaridZelli** [hagezi/dns-blocklists#3738]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

AdAway

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

metric.surfshark.com

### Why should the domain(s) be unblocked?

Occasionally breaks the Surfshark app

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
What exactly is not working?

**Comment by FaridZelli** [comment]
> What exactly is not working?

1. The app fails to connect to any server before the progress bar even starts.  
2. It's no longer possible to login using a code.  

These issues seem to happen at random, however whitelisting `metric.surfshark.com` solves the problem. I assume they've introduced some sort of scheduled analytics in the 3.9.0 update, as it started happening precisely 480 hours after the update was rolled out (Stable channel, August 27th ).

**Comment by hagezi** [comment]
The domain returns NOERROR but has no A/AAAA record.

I'll unblock it ...
