### ISSUE TITLE
Adblock detection after sequiona update

### ISSUE THREAD

**Issue by pinkyellowed** [hagezi/dns-blocklists#3750]
Updated IOS 
Tradingview now has implemented adblock detection, the same as Youtube
![IMG_5469](https://github.com/user-attachments/assets/7c84f019-6c94-48f1-be89-0b0070e54b77)
What are the chances to remove such prompts?

**Comment by hagezi** [comment]
The message can only be "removed" if the ad/tracking domains that are used for adblock detection are unblocked.

You would first have to find out which blocked domains trigger this message.

Which list version are you using?

**Comment by hagezi** [comment]
I have tested the app on iOS with the Ultimate list. I don't see any AdBlock Detection message ...

**Comment by pinkyellowed** [comment]
i have every single hagezi blocker on except ultimate because it was blocking something a while back that i was trying to connect to that i dont remember what it was. ill try it now

**Comment by pinkyellowed** [comment]
weird im still getting the pop up shown in the picture. i have no antvirus or any other over rides

**Comment by pinkyellowed** [comment]
i just checked on macos. everything is fine. but not on ios and im on the same profile. odd

**Comment by pinkyellowed** [comment]
<img width="1291" alt="Screenshot 2024-09-17 at 2 20 02 PM" src="https://github.com/user-attachments/assets/e7cc36bf-e5fb-4d1b-b8e8-d477e1f46ec0">
its completely blocked already but the ad blocker app detection is getting bypassed

**Comment by hagezi** [comment]
Unfortunately, I can't help until I can reproduce this myself. It doesn't occur with any of my lists in the iOS app.

**Comment by pinkyellowed** [comment]
Have you tried clicking on any ticker and looking at any chart and just click through tue chart time frames, thats when it occurs looking at the actual candle sticks as the time begins counting down. Any forex ticker right now or any crypto can be used right now as they run 24/5

Regards,
Dean
________________________________

**Comment by pinkyellowed** [comment]
It can be seen by being on the actual chart and looking at the candle sticks where the time is counting down. You could try any forex pair right now(dxy) or any crypto (btc/usdt) is when i get it. I get no ads on the actual list of tickers. Its when im on the actual chart clicking through time frames

**Comment by hagezi** [comment]
I can't reproduce it no matter what I do. I've spent some time in the app now, I don't get the message.

**Comment by pinkyellowed** [comment]
In the IOS app head to the top right corner which had a + sign and type   NQ1! 
![IMG_5472](https://github.com/user-attachments/assets/46682025-4ce9-4d23-9836-cbffe0251e18)

a new preview window will appear and click the right-dashed-square on the bottom 
![IMG_5473](https://github.com/user-attachments/assets/a3023315-2675-4392-836a-7ce6c85e8889)


You should now be on the candle stick chart where these ads appear after going through different candle stick time frames
![IMG_5474](https://github.com/user-attachments/assets/9205bb25-afd4-4d74-b4e8-22eb74764f61)



now i get the ads almost within 2mins if i begin flicking through different times. Or it doesnt occur till 5mins or so if i stay on the chart time frame.
Click the number which might be different to yours. It might say eg., 15m(15minutes) 45m (45 minutes)1H (1 hour) etc
![IMG_5475](https://github.com/user-attachments/assets/6c0a72cc-587b-4f2c-9ba5-1d6b1c645b1a)
Mine shows 4H. The letter after the number represents the time frame. M for minutes and H for hourly and M for monthly 

when i begin flicking through any time frames is when i get these ads

**Comment by pinkyellowed** [comment]
> @hagezi @pinkyellowed
> 
> > What are the chances to remove such prompts?
> 
> `g.doubleclick.net` is sometimes on whitelists against Adblock detect scripts etc. Handled directly by Adblockers like Adguard. For set and forget allow in NextDNS dashboard:
> 
> ```
> g.doubleclick.net
> googleapis.com
> pagead2.googlesyndication.com
> ```
> 
> DNS blocking only suplement general blocking ads via external apps like Adguard. iOS have this https://adguard.com/en/adguard-ios/overview.html I using adguard for android app and adguard dns private with custom setup filters and whitelists.
> 
> Sample https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/foreign.txt#L416 Search for `g.doubleclick.net` for stats how many times devs need whitelists.

appreciate your assistances but i whitelisted all, and i still get ad block detection

**Comment by pinkyellowed** [comment]
> Ping @AdamWr @Alex-302

i dont know if it was because of your ping but you gave me an idea and i denied securepubads.g.doubleclick.net
or either adam or alex was so damn quick. i just closed nextdns for 10secs and reebooted tradingview on ios. i dont get ads. just to make sure it was working i turned off nextdns for 10secs and turned it back on, no ad block detection. really appreciate your work everyone!!!

**Comment by pinkyellowed** [comment]
> Ping @AdamWr @Alex-302

i'm back...the issue still persists

**Comment by hagezi** [comment]
As I said, I can't reproduce it with my lists. You have already opened an issue with AdGuard : https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1756
