### ISSUE TITLE
Gardenfence Fediverse

### ISSUE THREAD

**Issue by Eriner** [hagezi/dns-blocklists#3759]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

none

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

noauthority.social and every other server on the gardenfence list

### Why should the domain(s) be unblocked?

You source a blocklist from the following repo: https://github.com/gardenfence/blocklist

I fail to see how a blocklist of Fediverse servers that some Canadian man living in Japan [doesn't like](https://gardenfence.github.io/#what-this-list-is-not) makes my website, or any website on that list, "malware, cryptojacking, scam, spam and phishing".

Not only would I like noauthority.social to be removed from your lists, ceasing your labeling/libeling of my website as "malware, cryptojacking, scam, spam and phishing", but I'd like to see the entire gardenfence list removed as a source.

To the best of my knowledge, NONE of the servers listed there are "malware, cryptojacking, scam, spam and phishing".

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by Eriner** [comment]
No response to the core objection, then?

> Not only would I like noauthority.social to be removed from your lists, ceasing your labeling/libeling of my website as "malware, cryptojacking, scam, spam and phishing", but I'd like to see the entire gardenfence list removed as a source.

> To the best of my knowledge, NONE of the servers listed there are "malware, cryptojacking, scam, spam and phishing".

Can you please explain how the servers on the gardenfence list are "malware, cryptojacking, scam, spam [or] phishing"?

**Comment by hagezi** [comment]
The complete list will be removed with the next release.

**Comment by Eriner** [comment]
Thank you. I appreciate your honesty and amenability.
