### ISSUE TITLE
Allow reolink.club (again)

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#3764]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

reolink.club

### Why should the domain(s) be unblocked?

Legitimate website for Reolink Security. 

Requested to be unblocked previously here - https://github.com/hagezi/dns-blocklists/issues/2809

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Redirects to https://bitly.com/pages/landing/branded-short-domains-powered-by-bitly?bsd=reolink.club.

The domain was excluded from the allowlist. In principle, only popular domains that have been on relevant top lists (Umbrella, Cloudflare, Tranco, Chrome, DomCop, ...) in the last 12 months or disrupt the functionality of popular apps, websites or services are excluded.
The reason for this procedure is that the length of the denyallow/domain modifier in lists formatted for AdGuard or uBlock is limited before the rule becomes invalid. This means that if every normal domain of the corresponding TLD were to be excluded, important rules would become invalid at some point. It must therefore be carefully weighed up what is excluded and what is not.
