### ISSUE TITLE
Processed .home requests of normally blocked domains

### ISSUE THREAD

**Issue by th3m** [hagezi/dns-blocklists#3781]
I am getting some weird .home requests on my Android device that are getting processed.

For example the blocked `telemetry.sdk.inmobi.com` domain is blocked by the lists but occasionally i see a `telemetry.sdk.inmobi.com.home` request that goes through.
Same thing happens with the `qcc.qualcomm.com` domain which is blocked. Occasionally a `qcc.qualcomm.com.home` get processed.

Other .home requests examples that i see (though the non .home domains are not blocked):
`mobile-webview.gmail.com.home`
`api.github.com.home`
`objects.githubusercontent.com.home`

Any advice how to handle this if it is worrying?

**Comment by hagezi** [comment]
Home is apparently your local domain. Almost every OS does the suffix search, the question is why it does this in your case. Looks like a client/DNS/network configuration problem to me. 

This has nothing to do with the blocklists, there are plenty of other resources on the net to clarify such issues.

Example of a similar problem:

https://forum.netgate.com/topic/176156/android-client-appending-local-domain-to-dns-queries
