### ISSUE TITLE
https://www.herooutdoors.com/

### ISSUE THREAD

**Issue by wjang1** [hagezi/dns-blocklists#3782]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Adaway

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

https://www.herooutdoors.com/

### Why should the domain(s) be unblocked?

It's a legit domain for airsoft products. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Not on Pro, but on TIF ..
