### ISSUE TITLE
conceptkart.com

### ISSUE THREAD

**Issue by Nzzyme** [hagezi/dns-blocklists#3784]
### Which AdBlocker/DNS cloud service do you use?

uBlock Origin

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

1. Visit the following page (https://conceptkart.com/collections/best-iem-under-2000)
2. The products are not displayed when the "Pro++ DNS Blocklist" filter is enabled

Screenshot: https://i.ibb.co/R2vBQZC/Untitled.jpg

### Why should the domain(s) be unblocked?

Products do not display on the webpage.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
api.mezereon.net

**Comment by Nzzyme** [comment]
Thank you!
