### ISSUE TITLE
finalsteptogo.com (Hosting infostealer malware)

### ISSUE THREAD

**Issue by AidanGee7** [hagezi/dns-blocklists#3791]
### Which domain(s) should be blocked?

finalsteptogo.com

### Why should these domain(s) be blocked?

This domain is hosting info stealer malware:

https://finalsteptogo[.]com/uploads/tr14.txt
https://finalsteptogo[.]com/uploads/tera14.zip

It looks like it's used as part of one of those new fake captcha "Verify" scams:
https://www.reddit.com/r/antivirus/comments/1fma8aq/allowed_a_virus/ 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Thanks. Added to my blocklist, which is included in hagezi's threat intelligence feeds.
