### ISSUE TITLE
Speedtest.net AT&T Latency Error

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#380]
#### What adblocker/DNS cloud service are you using?

NextDNS, Block Page = Disabled, CNAME flattening = Disabled

#### Which blocklists are used?
Pro++
Ultimate

#### Which domain(s) should be unblocked?
`speedtest.sbcglobal.net`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
The following domain is required to use AT&T speed test servers on speedtest.net. Blocking this domain causes a latency test error message when trying to use the AT&T Cicero, IL server. `cic.speedtest.sbcglobal.net.prod.hosts.ooklaserver.net` is what shows up in my NextDNS logs. `cic.speedtest.sbcglobal.net` is the CNAME required for proper function.

**Comment by hagezi** [comment]
Thanks, will be removed.
