### ISSUE TITLE
Pump.fun

### ISSUE THREAD

**Issue by Hecke92** [hagezi/dns-blocklists#3810]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

pump.fun

### Why should the domain(s) be unblocked?

It is a site where everybody can create new crypto coins

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/3019

@iam-py-test what do you think?

**Comment by Hecke92** [comment]
Hope I may add: for sure some people in pump.fun release a coin to scam people.

But as sure as that people on eBay or Amazon scam people - that doesn't mean to block those.

**Comment by iam-py-test** [comment]
Cryptocurrency is not my area of expertise, so I am not qualified to offer an opinion.
That said, the original report was for one specific cryptocurrency on that platform (all the comments on that cryptocurrency say it is a scam).
Thanks
