### ISSUE TITLE
Messenger app is blocked

### ISSUE THREAD

**Issue by CrossyAtom46** [hagezi/dns-blocklists#3821]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

graph.facebook.com

### Why should the domain(s) be unblocked?

If you won't unblock, you can't sign-in to messenger (PC app and mobile app) or get any notifications from it. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Just read the warning for the Ultimate: https://github.com/hagezi/dns-blocklists#ultimate
