### ISSUE TITLE
Why RethinkDNS removed from README?

### ISSUE THREAD

**Issue by h1toru** [hagezi/dns-blocklists#3822]
i'm just curious, why RethinkDNS removed from [README#Online DNS Services](https://github.com/hagezi/dns-blocklists#dnsservices)? is there any particular reason?

**Comment by hagezi** [comment]
The lists are old, have not been updated for several months and there have been repeated service failures.

**Comment by ignoramous** [comment]
Hi:

> The lists are old, have not been updated for several months and there have been repeated service failures.

The lists are auto-updated *every week*. At times, GitHub or Cloudflare or both collude to break that automation. As for failures, well it is a stretch to call it "repeated" when it has happened twice? Not bad for a single-man running 100+ servers in 40+ locations (:

**Comment by hagezi** [comment]
@ignoramous If everything works again now, I will be happy to add Rethink DNS again. But it had months of old data, nobody knew what was going on.

**Comment by hagezi** [comment]
re-added in https://github.com/hagezi/dns-blocklists/commit/0e8c73814245ec7b74ede037ebfa21dd9824f160
