### ISSUE TITLE
[request] listing company links or information about founders of public free service that use your lists

### ISSUE THREAD

**Issue by redcat42** [hagezi/dns-blocklists#3824]
just to share,

rethinkdns is based in Tamil Nadu, India ([source](https://www.thecompanycheck.com/company/celzero-private-limited/U72900TZ2021PTC036789))

dnswarden is by a Indian developer [Banu Pratapy](https://github.com/bhanupratapys) who claims to run the service on github.io

to me, it matters who i trust my data with, if not my isp, and if i cannot afford a pi hole or other solutions

personally, i trust the two french guys that started NextDNS, Romain Cointepas and Olivier Poitrey ([source](https://help.nextdns.io/t/y4hmv0n/who-is-behind-nextdns)) they also own a public dns service called [https://www.dns0.eu/](https://www.dns0.eu/) that operates in europe

@hagezi if i may make a suggestion/request, the same way you mention where the servers are located for example when you listed dnsforge.de (Germany) (i dont know why it got removed) it would be nice if you could also list a link to the founders/company than owns the service, so users can make a more informed decision as to which public free dns that use your lists, that they might want to use

just sharing my thought

**Comment by hagezi** [comment]
There is a link to the main page, where everyone can inform themselves.

**Comment by redcat42** [comment]
> Why would nationality matter in who you trust? Incredibly shortsighted.

server location matters as the country's policies regarding data. Sweden/Switzerland would be best. I believe, i could be wrong. 
Track record of the Company also matters, to me, it is like, being happy to block tracking at the price of all other dns queries being collected and sold, back to square one.

**Comment by ignoramous** [comment]
> server location matters

Nice deflection. You specifically point out the nationalities of those running the services.

NextDNS has severs in 6+ locations in India, btw. They also use both Google and Cloudflare to store and serve DNS logs, which also have presence in India and in probably many other nationalities you may love to hate.

> Track record of the Company also matters

You mention nothing of the sort in your original post. Besides, what are you insinuating about the track record of my company (which runs Rethink DNS *at a loss* and that's because a LOT of people rely on it for anti-censorship purposes)?

> dns queries being collected and sold

One can very well run a recursive DNS resolver (on your router, for example), if one is truly worried about this.

**Comment by redcat42** [comment]
> > server location matters
> 
> Nice deflection. You specifically point out the nationalities of those running the services.
> 
> NextDNS has severs in 6+ locations in India, btw. They also use both Google and Cloudflare to store and serve DNS logs, which also have presence in India and in probably many other nationalities you may love to hate.
> 
> > Track record of the Company also matters
> 
> You mention nothing of the sort in your original post. Besides, what are you insinuating about the track record of my company (which runs Rethink DNS _at a loss_ and that's because a LOT of people rely on it for anti-censorship purposes)?
> 
> > dns queries being collected and sold
> 
> One can very well run a recursive DNS resolver (on your router, for example), if one is truly worried about this.

it's about transparency, that gives the user a sense of security 

I may ne redcat42 but I'm not publishing anything so being anonymous is fine 

so, in the case of the 'french guys' I know their names, I know how the look, I know what their track record is, I understand their business model

same for control d, the founders, who they are, how they made Windscribe VPN, where they studied, what they're about basically

then, based on what information one gathers, one can make an informed decision, that's about it

I apologize if you've felt hurt in some way because of my post, this is not my intent 

if, for example, I knew who Bhanu Prarap is, he was open to linking his linked in profile, was well known in the IT community, knew his background ... I could potentially make an informed decision about him, maybe he's a great guy and this is just a moonlighting project on the side and he doesn't want the company he works for to know, I don't know, but the more information I have is better 

I'm not interested in anyone nitpicking words and phrases I use or trying to start a fight or looking for one 

I'm interested in information so it can help me make an informed decision  

I wish you well. Whoever you are :)

**Comment by ignoramous** [comment]
> Whoever you are :)

Don't gaslight me.

You think you unearthed some hidden information about Rethink being run from "Tamil Nadu" when that's been mentioned in [our repo's README](https://github.com/celzero/rethink-app?tab=readme-ov-file#backstory) and on our website for 4 years now. Complete with links to LinkedIn and all. 

Besides, you'll be happy to know HaGeZi no longer lists Rethink for whatever reasons. So, you win.

Just don't insult others or bring to question their work for something they cannot change (like ethnicity).

**Comment by hagezi** [comment]
Before this degenerates any further, I'll close it. This is not a discussion forum.
