### ISSUE TITLE
More details on what each version might break

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3825]
I just wanna start out by saying, thank you for these filters. Incredible work! I have a suggestion that I think would help users pick out which version to use.

I know there is the recommended section but I would appreciate some more elaboration.

Like in ultimate there is a warning that it might break facebook/instagram features.

There could be a similar warning on each profile on what it might break.

Normal
- No breakage

Pro
I'm not sure what it might break. Only that it blocks more than normal and it blocks error trackers
So there could be more details on what might break if I use this filter.

Pro plus
- Breaks some ad links for example in google search?

Ultimate
- Might break features in apps/websites.

So a small list of things what might break while using each list.

I hope you understand what I mean😅

**Comment by hagezi** [comment]
Thank you, I know what you mean. I think about what makes sense and implement it.

Suggestions from the community are very welcome.

**Comment by user716253** [comment]
Glad to hear! Thank you and hope you have a great day!

**Comment by user716253** [comment]
Maybe a warning about xbox achievements as well in ultimate

**Comment by hagezi** [comment]
> [Samsung Find] location tracking is blocked in ultimate as well

You mean via userlocation.googleapis.com?

**Comment by user716253** [comment]
It needs
`geomobileservices-pa.googleapis.com`
Otherwise the devices location doesn't update in the map.

**Comment by hagezi** [comment]
Thanks, that shouldn't really be the case, I'll unblock the domain.

**Comment by hagezi** [comment]
Ultimate:

![grafik](https://github.com/user-attachments/assets/1b5de370-7497-4476-92b7-dcd24dcf71f9)

**Comment by hagezi** [comment]
Pro ++:

![grafik](https://github.com/user-attachments/assets/79a110dc-2ca3-4074-8acb-21f1b85ab4f9)

**Comment by hagezi** [comment]
I have made a few adjustments in the ReadMe, which will be rolled out with the next release. That should be enough for now.

**Comment by user716253** [comment]
This is really great, thank you!
