### ISSUE TITLE
Discordium.org

### ISSUE THREAD

**Issue by DevKanui** [hagezi/dns-blocklists#3830]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

Discordium.org

### Why should the domain(s) be unblocked?

This Website is newly created by me, we make Discord Server Lists.

We intend no harm

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via @jarelllama scam list.
