### ISSUE TITLE
Stremio subtitles add ons blocked

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3836]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

opensubtitles.serv00
opensubtitles.stremio.homes
subdl.strem.bar
subsource.strem.bar

### Why should the domain(s) be unblocked?

These domains are needed for subtitles and are not malicious or anything.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
serv00?

**Comment by user716253** [comment]
Serv00.net

My bad

**Comment by user716253** [comment]
I don't see opensubtitles.serv00.net nor opensubtitles.stremio.homes in the allow folder. Is there a reson for it or just a mistake?

**Comment by hagezi** [comment]
serv00.net has no place in the TLD allow folder because .NET TLD is not blocked in the TLD list.

I'll have a look at the other one later.

**Comment by hagezi** [comment]
Fixed,
