### ISSUE TITLE
identifyillustration.com: potential badware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#3838]
### Which domain(s) should be blocked?

identifyillustration.com

### Why should these domain(s) be blocked?

This link keeps opening when attempting to pause or adjust the timeline on certain NSFW websites, such as `xxxgr.net`. The domain is also newly registered at the time of reporting this issue. Could you please check if there is anything suspicious or malicious associated with it?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
I can reproduce the popup, but it detects the IP address of my sandbox and doesn't do anything.

**Comment by hagezi** [comment]
Thanks @ExtRIELICi @iam-py-test ;)
