### ISSUE TITLE
destinycoons.com

### ISSUE THREAD

**Issue by Alex9001** [hagezi/dns-blocklists#3847]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

destinycoons.com

### Why should the domain(s) be unblocked?

its a website that sells cats i dont think they are doing anything bad

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via @jarelllama scam list. @jarelllama Currently there seem to be false positives more often.

**Comment by jarelllama** [comment]
> Via @jarelllama scam list. @jarelllama Currently there seem to be false positives more often.

Will check where they are coming from.

**Comment by jarelllama** [comment]
Hi @hagezi , I looked into `destinycoons.com` and it seems to be an indirect copy of `moscowmainecoons.com`. See: https://www.google.com/search?q=%22Our+desire+to+breed+and+raise+Maine+Coons+is+due+to+our+first+Maine+Coon+Moscow%2C%22

`destinycoons.com` is listed as a scam in [petscams.com](https://petscams.com/puppy-scammer-list/destinycoons-com/) which I use as a source.

**Comment by hagezi** [comment]
Thanks @jarelllama

**Comment by Alex9001** [comment]
There's no indication this is a scam website. This is a business that sells maine coons and there's a bunch of pictures of the cats they sell on the website and scammers dont usually go through the trouble of raising purebred maine coon cats and posting updated pictures of new litters. 


They have a google business profile https://maps.app.goo.gl/8bz7z3gLtBpB1GE79 and a facebook page https://www.facebook.com/people/Destiny-Coons-Cattery/100093261996944/ . They have 1 review on google and 25 reviews on facebook with zero mention of the word "scam". There is, however, a cute kitten alert, so be warned.

**Comment by hagezi** [comment]
I'll rely on the information from @jarelllama and [petscams.com](https://petscams.com/puppy-scammer-list/destinycoons-com/) for now. 

See also: https://www.reddit.com/r/MaineCoon/comments/18x4vcw/breeder_questoon/

**Comment by iam-py-test** [comment]
They claim to be registered with "International Cat Association (TICA) and The Cat Fancier’s Association (CFA)". I have contacted both and am awaiting a response.
No business under the name "Destiny Coons" or "Destiny Coons Cattery" exists in the State of California, though they may be doing business under another name or just aren't a registered business (but are otherwise legitimate). I see no terms of service or privacy policy on their website.
Lastly, the first photo on `https://destinycoons.com/product/paris/` feels like AI. Obviously I could be wrong, but the human's fingers look distorted and the cat is missing a leg. Though, to be fair, cats lose legs and I could be wrong about the fingers.
Thanks

**Comment by Alex9001** [comment]
thanks for the info, I had no idea

**Comment by iam-py-test** [comment]
**I am not saying they are a scam**. Small companies may not be registered (right? not a business lawyer) and the image might not be AI ([nowdays I am very suspicious of AI generated photos, so I overreact to small things in real photos](https://xkcd.com/331/)).
