### ISSUE TITLE
Scam websites

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#3854]
### Which domain(s) should be blocked?

https://foundations-x2024.cloud/
https://foundations-x2024.sbs/

### Why should these domain(s) be blocked?

These are scam websites advertised on Twitter

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
Added to my blocklist, which is included in hagezi's list.
Thanks
