### ISSUE TITLE
polymc.org

### ISSUE THREAD

**Issue by ChaseKnowlden** [hagezi/dns-blocklists#3855]
### Which domain(s) should be blocked?

https://polymc.org

### Why should these domain(s) be blocked?

Unsafe Minecraft Launcher that could put malware in it.

https://www.reddit.com/r/Minecraft/comments/y6lt6s/deleted_by_user/

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
No Flags:
https://www.virustotal.com/en/domain/polymc.org/information/

Open Source:
https://github.com/PolyMC/PolyMC
