### ISSUE TITLE
zippyshare.day

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#3858]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

zippyshare.day

### Why should the domain(s) be unblocked?

Successor to `zippyshare.com`. 
The site is only blocked here. 
Adguard, for example, adds fixes against ads, does not block it. 
Reference `https://github.com/AdguardTeam/AdguardFilters/commit/9e7df26efe2bd33b674f8f80c0d2d5b8e32feb09`
VT: https://www.virustotal.com/gui/url/f1b475d2fb71b978acb3377c531b4c2fee3a86e795b944e01b722a56a938f6d7
ESET: clean. Some minor AV's sees malware there. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@FadeMind https://www.reddit.com/r/PiratedGames/comments/1baxtpf/a_fake_zippyshare_exists_i_havent_used_it_so/

**Comment by AdamWr** [comment]
Even though it might look shady and it's fake old `zippyshare`, it looks like that it's working file hosting.
I have uploaded a text file and then download it, and it opens correctly.
So until there is any evidence that it adds something malicious to files then I don't think we should block it.

**Comment by Alex-302** [comment]
Yep. I think they just don't use antivirus.

**Comment by hagezi** [comment]
Yes, I have blocked it because it is fake.
