### ISSUE TITLE
Finnish trackers

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3862]
### Which domain(s) should be blocked?

recommendations.asunnot.oikotie.fi
tracking.veikonkone.fi

### Why should these domain(s) be blocked?

`recommendations.asunnot.oikotie.fi`
- ad domain that doesn't seem to break anything and is used to show ads in other websites like tori.fi for example

`tracking.veikonkone.fi`
- Based on the name it's a tracker and doesn't seem to break anything

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by user716253** [comment]
Also random question. Do you have some sort of website where you check reported websites so you know what to block? Or how do you determine what to actually block?

**Comment by user716253** [comment]
Found a few more domains.

`analytics.valio.fi`
- Analytics domain for a finnish website

`analytics.twitter.com`
- Twitter analytics

`tnt-production.nm-analytics.nelonenmedia.fi`
- Analytics domain for a finnish website

**Comment by hagezi** [comment]
analytics.twitter.com is a referral domain - used for tweet links.

**Comment by hagezi** [comment]
> Do you have some sort of website where you check reported websites so you know what to block? Or how do you determine what to actually block?

No, this is mainly manual research work on the web or on the page that triggers the potential tracker.

**Comment by user716253** [comment]
> > Do you have some sort of website where you check reported websites so you know what to block? Or how do you determine what to actually block?
> 
> No, this is mainly manual research work on the web or on the page that triggers the potential tracker.
> 
> There are databases for common trackers, such as https://duckduckgo.github.io/tracker-radar-wiki/
> 
> Sometimes ChatGPT or something similar also helps to know something about the domain and sometimes, unfortunately, it's just a gut feeling or a test with try and error blocking.

Okay. Thanks for the info. Always wondered about that. That's a lot of work to do. Appreciate you!
