### ISSUE TITLE
status.o2.co.uk 

### ISSUE THREAD

**Issue by FeeninForMore** [hagezi/dns-blocklists#3863]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

status.o2.co.uk

### Why should the domain(s) be unblocked?

It shows if the service is down or not 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked by CNAME status.o2alerts.com
