### ISSUE TITLE
The domain is not blocked on NextDNS

### ISSUE THREAD

**Issue by Repressed8077** [hagezi/dns-blocklists#3892]
### Which domain(s) should be blocked?

dir-apis.samsungdm.com

### Why should these domain(s) be blocked?

https://github.com/hagezi/dns-blocklists/issues/794#issuecomment-1491434175

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The Domain is related to Device Management (DM).
Samsung offers device management services, especially for enterprises, to manage, control, and secure their mobile devices remotely. This domain is part of the infrastructure enabling those management tasks, such as pushing updates, enforcing security policies, or configuring settings remotely.
