### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3901]
### Which domain(s) should be blocked?

`d1gw63jeifbb1b.cloudfront.net`
`assets-jpcust.jwpsrv.com`
`location-v6-i18n.tiktokv.com`
`mtv.video-tracking.a2d.tv`
`tag-manager.yle.fi`
`yle-recommender-front.api.yle.fi`

### Why should these domain(s) be blocked?

Trackers from finnish sites and location tracking from tiktok. Did not see any breakage with any of these

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
For testing (TikTok Fingerprinting/Ultimate):

```
location-i18n.tiktokv.com
location-sg.tiktokv.com
location.tiktokv.com
location-ttp2.tiktokv.com
location-ttp2.us.tiktokv.com
location.us.tiktokv.com
location-v6-i18n.tiktokv.com
location-v6-ru.tiktokv.com
location-v6-sg.tiktokv.com
location-v6.tiktokv.com
location-v6-va.tiktokv.com
location-va.tiktokv.com
```

**Comment by user716253** [comment]
I have done some further testing and it seems that this domain is actually used to keep track of what you have watched and where you left off with series or movies in a finnish streaming service called **MTV Katsomo** . 
So this should be allowed
`mtv.video-tracking.a2d.tv`

But I did notice that this next domain is used to deliver ads to the video feed and I did not notice any breakage with my testing.

`tvm-mtv-freewheel.akamaized.net`

@hagezi
