### ISSUE TITLE
Samsung trackers?

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3902]
### Which domain(s) should be blocked?

`tos-dev-getdata.samsung-dict.com`
`tos-stg-getdata.samsung-dict.com`
`tos-prod-getdata.samsung-dict.com`

### Why should these domain(s) be blocked?

From what I found out these are somehow related to text predictions on Samsung. But I have these domains blocked and text predictions still work, so these are probably just used to send data to Samsung about texting habits or something. Might want to block on Ultimate?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Linked to speech recognition, dictionary services or text input systems. Dictionary updates, text prediction and auto-correction, language-based functions.

I doubt that they do not lead to any restrictions. I have also found nothing about what is to be tracked.
