### ISSUE TITLE
Domains needed for Windows update in Microsoft (Windows, Office, MSN)

### ISSUE THREAD

**Issue by Uddhav07** [hagezi/dns-blocklists#3923]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Microsoft (Windows, Office, MSN)

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Native Tracker

### Which domain(s) should be unblocked?

the ones which lemme update

### Why should the domain(s) be unblocked?

to update windows or more specificallu the repair version of windows

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@Uddhav07 Which domains should these be? There are no domains on the list that cause such problems.
