### ISSUE TITLE
comodozeropoint.com: badware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#3928]
### Which domain(s) should be blocked?

comodozeropoint.com

### Why should these domain(s) be blocked?

https://x.com/cyberfeeddigest/status/1843656093206995423

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Already blocked in the TIF list.

**Comment by ExtRIELICi** [comment]
In HaGeZi Ultimate too? Or only TIF?
