### ISSUE TITLE
False positive: engagements.appsflyer.com

### ISSUE THREAD

**Issue by sefinek24** [hagezi/dns-blocklists#3947]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

engagements.appsflyer.com

### Why should the domain(s) be unblocked?

I don't know what this subdomain is, but blocking it prevents the game from being downloaded: https://www.strinova.com/?lang=en-US

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Will be removed from Light to Pro and remains blocked in the aggressive lists from Pro++. Will be added to the referral allowlist.
