### ISSUE TITLE
Hurra.com (Marketing and Analytics)

### ISSUE THREAD

**Issue by miansopi** [hagezi/dns-blocklists#3949]
### Which domain(s) should be blocked?

hurra.com

### Why should these domain(s) be blocked?

Marketing, Tracking, Tagging and other types of Analytics.

https://ssl.hurra.com/oti.js?cid=912
https://ssl.hurra.com/ivy.js?v=6666d7d8

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`ssl.hurra.com` is a referral domian.
See: https://github.com/hagezi/dns-blocklists/wiki/FAQ#referral
