### ISSUE TITLE
Ad/tracker domains

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3958]
I did some more testing relating to my previous deny request https://github.com/hagezi/dns-blocklists/issues/3901#issue-2568529770 and found that this one domain is actually used to keep track of what you have watched and where you left off with series or movies in a finnish streaming service called MTV Katsomo.

So this should be allowed:
`mtv.video-tracking.a2d.tv`

I also noticed that these domains are used to deliver ads to the video feed and I did not notice any breakage with my testing:
`tvm-mtv-freewheel.akamaized.net`
`805ba.v.fwmrm.net`

This following domain is a tracker and did not notice any breakage with my testing:
`endpoint.finnpanel.fi`

I have tested these on my phone, PC and TV. All ads are blocked with these domains.

**Comment by hagezi** [comment]
Thanks Leevi, will be adjusted on next release.
