### ISSUE TITLE
Using microsoft host file what am I expecting to break?

### ISSUE THREAD

**Issue by Raj2032** [hagezi/dns-blocklists#3968]
on Windows 10 or 11, using this option: Microsoft (Windows, Office, MSN)

I just wanna know if there is anything that will break?

**Comment by hagezi** [comment]
Windows Spotlight/Search, XBox Gamepass GPU Perks. Also used for Microsoft's advertising/tracking and content delivery services.
`arc.msn.com`

XBox Live Achievements, Microsoft uses the following domains, which are also used for other telemetry data, to display and track Xbox Achievements.
```
v10.events.data.microsoft.com
v20.events.data.microsoft.com
```

Activity history Tracking across Windows devices. It's primarily used in connection with Windows Timeline, a feature introduced in Windows 10 that allows users to see a history of activities they've performed on their devices.
```
activity.windows.com
assets.activity.windows.com
canary.activity.windows.com
edge.activity.windows.com
edge-enterprise.activity.windows.com
enterprise.activity.windows.com
enterprise-eudb.activity.windows.com
ppe.activity.windows.com
```

**Comment by Raj2032** [comment]
@hagezi THanks very much very helpful :)

**Comment by Raj2032** [comment]
@hagezi Hey mate I just got one more question, regarding office 365, would the user still be able to sign in etc?

**Comment by hagezi** [comment]
Yes.
