### ISSUE TITLE
aleperfumeria.pl

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#397]
Polish perfume shopping site

**Comment by krystian3w** [comment]
If exist data about new owner then I can also unlock the domain.

![Screenshot_2023-02-17-15-50-30-610-edit_org mozilla firefox_beta](https://user-images.githubusercontent.com/35370833/219687350-fe2148c1-73ff-4e8c-9f3b-2b83266eab0c.jpg)
