### ISSUE TITLE
Domain 

### ISSUE THREAD

**Issue by chillipal** [hagezi/dns-blocklists#3973]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### Other

Domain incorrectly included included in TIF

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

tiktokgenocide.com

### Why should the domain(s) be unblocked?

Based on my research this domain does not appear to have any malware or is service a c2 for malware.  The real reason for including this domain could be political censorship which is not the intent of TIF. 

urlscan.io returned nothing to suggest any malware or suspicious code. Virus Total returned nothing. 

https://urlscan.io/result/7026552f-0421-484c-ac78-cdbf758cb3af/

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via @jarelllama scam list.

**Comment by chillipal** [comment]
> Via @jarelllama scam list.

I didn’t see any “scam” in their content. The content could be offensive for some but I couldn’t any cyber threat that would justify its inclusion in TIF.
