### ISSUE TITLE
Issue with controld TLD folder

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3975]
Hi, wanted to put this here so we can pinpoint where the issue is.

I am using Hagezi TLD folder in Controld

For some reason it blocks https://www.alvtrade.fi/
I checked that the TLD folder does have .trade TLD in it but why is it blocking it since it uses .fi tld

@hagezi @yegors

**Comment by user716253** [comment]
Nevermind. It was issue on my end

**Comment by hagezi** [comment]
Blocked via CNAME `webnode.fi` (Badware Hoster).
