### ISSUE TITLE
Videos not working due to hosts being blocked

### ISSUE THREAD

**Issue by Wizzo666** [hagezi/dns-blocklists#3977]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole, uBlock Origin

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

7caa2.v.fwmrm.net
d1gw63jeifbb1b.cloudfront.net

### Why should the domain(s) be unblocked?

7caa2.v.fwmrm.net - With this blocked, some videos do not work on at least www.is.fi & www.hs.fi
d1gw63jeifbb1b.cloudfront.net - With this blocked, no videos work on www.il.fi. Example: https://www.iltalehti.fi/kotimaa/a/c45bc53b-420c-4ef6-ab98-4bf4dd35f86c

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
d1gw63jeifbb1b.cloudfront.net is not blocked in my lists.
