### ISSUE TITLE
Block ads & check previously reported entry

### ISSUE THREAD

**Issue by Wizzo666** [hagezi/dns-blocklists#3979]
### Which domain(s) should be blocked?

nostemedia.bbvms.com
strongbox.nostemedia.fi
backstory.ebay.com

### Why should these domain(s) be blocked?

nostemedia.bbvms.com - ads
strongbox.nostemedia.fi - ads
backstory.ebay.com - This was reported in https://github.com/hagezi/dns-blocklists/issues/3945 but it's not blocked?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
backstory.ebay.* https://github.com/hagezi/dns-blocklists/issues/2576
