### ISSUE TITLE
allow bromite website

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3981]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

https://www.bromite.org/

### Why should the domain(s) be unblocked?

Unmaintained browser project opensource.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://infosec.exchange/@divested/113226945978043050

**Comment by olumolu** [comment]
i understand
