### ISSUE TITLE
webnode.com/webnode.cz - incorrectly blocked

### ISSUE THREAD

**Issue by czhook** [hagezi/dns-blocklists#3989]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster

### Which domain(s) should be unblocked?

webnode.cz
webnode.com

cestavelkematky.cz
jelenistezka.cz
pospisilova-lenka.cz

### Why should the domain(s) be unblocked?

Hello Hagezi. webnode is a normal hosting and website builder for free. All normal and useful sites hosted there or created by webnode are not working for me. I gave 3 examples in the box above. Thx for your work! 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@czhook 

Unfortunately, not only normal and useful sites. What does the Badware Hoster list block? See the description:

"_A blocklist for blocking known free hosters that also host badware via user content to prevent the use of these hosters for malicious purposes._"

Badware is also hosted via this hoster without anyone caring. The domains are therefore in the right place on the list.
