### ISSUE TITLE
Inconsistency with *.agora.io

### ISSUE THREAD

**Issue by bondskin** [hagezi/dns-blocklists#3990]
Hi,

I am confused about the blocking logic of various agora.io domains.
(I found https://github.com/hagezi/dns-blocklists/issues/82 and https://github.com/hagezi/dns-blocklists/issues/49)

As of today I see the following behaviour where some sub domains are blocked but others are not.
Is there a specific reason?

<img width="1140" alt="image" src="https://github.com/user-attachments/assets/2367bf33-e487-435f-a835-0381f80de170">

**Comment by hagezi** [comment]
I rather wonder why they are blocked at all. Agora.io enables developers to integrate real-time communication into their applications, be it for video conferencing, online collaboration, streaming or voice calls.

**Comment by hagezi** [comment]
`ap*.agora.io` will be removed on next release.

**Comment by bondskin** [comment]
> `ap*.agora.io` will be removed on next release.

thank you!
