### ISSUE TITLE
ui-portal.de is missing

### ISSUE THREAD

**Issue by Metrokoto** [hagezi/dns-blocklists#4000]
### Which domain(s) should be blocked?

*.ui-portal.de, ui-portal.de

### Why should these domain(s) be blocked?

This domain is used by the same company as urbanairship.com and is used for advertising and analytics, yet no other list blocks it.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocking the main domain makes the above-mentioned protals unusable, e.g. web.de:

![grafik](https://github.com/user-attachments/assets/d4e21d27-9d88-4b09-bb3e-b7ba6e545765)

![grafik](https://github.com/user-attachments/assets/138d5365-720f-454d-a306-6af1b6f24161)
