### ISSUE TITLE
fake rustdesk domains to spread malware

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#4003]
## Which domain(s) should be blocked?

https://rustdesk.io/
https://rustdesk.pl/
https://rustdesk.co.nz/

## Why should these domain(s) be blocked?

Block this domain
They are providing malwares
https://github.com/rustdesk/rustdesk/discussions/9679

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by olumolu** [comment]
rustdesk.io is providing a non malicious file but providing there own relay server i think we can remove
Rustdesk.io website.p

**Comment by iam-py-test** [comment]
As per https://github.com/rustdesk/rustdesk/discussions/9679#discussioncomment-10970002, I am still blocklisting rustdesk[.]io
hagezi may have a differing opinion.
Thank you
