### ISSUE TITLE
Unblock eml.stytch.com

### ISSUE THREAD

**Issue by jhult** [hagezi/dns-blocklists#4011]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

eml.stytch.com

### Why should the domain(s) be unblocked?

Unblocking is necessary to use login via a site which uses [Stytch](https://stytch.com/) for auth.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked by CNAME `telemetry.stytch.com`
