### ISSUE TITLE
Unblock www.suunto.com

### ISSUE THREAD

**Issue by Wizzo666** [hagezi/dns-blocklists#4020]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole, uBlock Origin

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

www.suunto.com

### Why should the domain(s) be unblocked?

This is the official website of Suunto Oy - a Finnish sports watch etc. manufacturer. Www.suunto.com is a CNAME of www.suunto.com.dxcloud.episerver.net -> suoy01mstrc864f.dxp.optimizely.com and optimizely.com is blocked by Multi ULTIMATE.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@Wizzo666 
Blocked by CNAME `suoy01mstrc864f.dxp.optimizely.com`. `optimizely.com` is completely blocked in the Ultimate to block all generated subdomains. I need to see if I can unblock dxp.optimizely.com without compromising its effectiveness.
