### ISSUE TITLE
Pls add these in threat intelligence mini version 

### ISSUE THREAD

**Issue by nhlghost** [hagezi/dns-blocklists#4022]
### Which domain(s) should be blocked?

rvvsvrlfnkj.com
insurecarrot.com
ojbrfiruilbrknn.com
accommodateyours.com

### Why should these domain(s) be blocked?

These should be added to threat intelligence mini bcz I am usung that in brave custom gilter list. But its only blocked threat intelligence feed 
Main version. 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@nhlghost They come from my malicious popup ads, also included in the tif medium. I recommend that you switch to tif medium. in terms of size, this should not be a problem.

The mini only contains a small selection.
