### ISSUE TITLE
Add to gambling blocklist

### ISSUE THREAD

**Issue by nhlghost** [hagezi/dns-blocklists#4027]
### Which domain(s) should be blocked?

There are some Bangladeshi gambling sites which are not included in the gambling blocklist
I can’t specifically mention them though 

### Why should these domain(s) be blocked?

Some sites aren’t included 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
If you or someone else tells me where I can get these domains I will be happy to add them.

**Comment by hagezi** [comment]
I can't really do anything with that. If you can give me exact domains, I'll be happy to add them, until then ...
