### ISSUE TITLE
Jodel ads

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#4037]
### Which domain(s) should be blocked?

`externalimg.assets.jodel.com`
`externalvidthumbnails.assets.jodel.com`

### Why should these domain(s) be blocked?

Blocking these domains removes ads inside the app. Haven't noticed any breakage with my testing.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by user716253** [comment]
For some reason this is not blocked. `externalvidthumbnails.assets.jodel.com`

And I found another ad domain from jodel
`externalvid.assets.jodel.com`

@hagezi

**Comment by hagezi** [comment]
Thanks, I'll have a look ...

**Comment by hagezi** [comment]
It is blocked ...

![grafik](https://github.com/user-attachments/assets/caebf67f-ca4a-4221-832f-2699b704b099)

![grafik](https://github.com/user-attachments/assets/8f6d9ed4-5d8b-41c9-9b5f-1e22aeeae872)
`
externalvid.assets.jodel.com` added ...
