### ISSUE TITLE
heytap browser ads and tracking block

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#4038]
### Which domain(s) should be blocked?

browserfiles.heytapmobile.com
dhfsf.oppomobile.com
dhfs-in.oppomobile.com
dhfs-in.heytapimage.com
winzo.onelink.me
novel.itoon.org
t.y1h1.com
8lkpf.app.link
opt.toiimg.com
browser-api-in.heytapmobile.com

### Why should these domain(s) be blocked?

https://play.google.com/store/apps/details?id=com.heytap.browser
This is a browser that connects to unnecessary urls all are for getting ads and tracking stuff don't know what else it does.
As i have blocked all of them still browser work just reduced no of ads and homepage crap.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Take a look at sportskeeda.com ..

**Comment by olumolu** [comment]
> Take a look at sportskeeda.com ..

Yes i just removed that i have added that by mistake

**Comment by olumolu** [comment]
What details you need i have blocked them and that browser worked is not it enough if you need anything else let me know if i can help i will

**Comment by hagezi** [comment]
It may be that the browser works, but have you ever thought that the blocked domains lead to restrictions elsewhere?

opt.toiimg.com, for example, belongs to the Times of India and is used to deliver images and media.

**Comment by hagezi** [comment]
Unfortunately, it's not as easy as you make it sound. This may work for you if you block the domains. But I block for the masses ...

**Comment by hagezi** [comment]
The website novel.itoon.org is primarily used for reading web novels and online stories. It is a platform under the brand NovelToon, which provides a wide range of genres, including romance, fantasy, urban fiction, and more. Users can read popular titles, follow series, and access completed or ongoing stories. It’s part of the MangaToon ecosystem, where users can also engage with web comics alongside novels.

The platform is popular for serialized stories, particularly in genres like romance and time-travel, with several titles involving themes of rebirth, revenge, and urban fantasy. Users can read stories for free or opt for premium content with in-app purchases.

**Comment by hagezi** [comment]
t.y1h1.com is tracking, added.

**Comment by hagezi** [comment]
The URL winzo.onelink.me is used as a redirect link for downloading the WinZO app, which is a popular gaming platform in India.

**Comment by hagezi** [comment]
8lkpf.app.link only deep linking to https://www.getrushapp.com/

**Comment by hagezi** [comment]
`browserfiles.heytapmobile.com` - DEAD (NXDOMAIN):
```
; <<>> DiG 9.16.50-Debian <<>> browserfiles.heytapmobile.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 49005
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;browserfiles.heytapmobile.com. IN      A

;; AUTHORITY SECTION:
heytapmobile.com.       900     IN      SOA     ns-939.awsdns-53.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 11 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Oct 19 20:37:35 CEST 2024
;; MSG SIZE  rcvd: 139
```

Unclear, no further details found, not blocked anywhere. Seems to be technical domains, primarily used in the background for device functionality:
```
dhfsf.oppomobile.com
dhfs-in.oppomobile.com
dhfs-in.heytapimage.com
```

Seems to be also related to general browser related services. A background service used to enhance or support the browser functionality on Oppo, Realme, or related devices, particularly in India:

`browser-api-in.heytapmobile.com`

**Comment by olumolu** [comment]
> The URL winzo.onelink.me is used as a redirect link for downloading the WinZO app, which is a popular gaming platform in India.

This is a gambling app and ads which promote gambling is a spam so that should also be blocked.

> 8lkpf.app.link only deep linking to https://www.getrushapp.com/

This is also a gambling stuff baked into the browser and ads which promote gambling is a spam.

dhfsf.oppomobile.com
dhfs-in.oppomobile.com
dhfs-in.heytapimage.com
This are used for so called for sync or other stuff but this browser does not offer any such feature so the best is to block this also. And i did not find anything broken after blocking this.
The last domain heytapimages i have looked into it it load static image advertisement into the browser.
Though this does not load if you turn off recommendation from the settings but still this the browser pings that domain

browser-api-in.heytapmobile.com
I did not find anything from internet what it does and i feel no difference whether i block this domain or does not.

**Comment by hagezi** [comment]
Gambling domains are blocked in the gambling list ...

**Comment by olumolu** [comment]
But this are ads block them

**Comment by olumolu** [comment]
winzo.onelink.me
t.y1h1.com
8lkpf.app.link
Have you added them also?

**Comment by hagezi** [comment]
Yes, t.y1h1.com is already blocked. The other will be added to the aggressive lists on next release.

**Comment by olumolu** [comment]
Thanks
