### ISSUE TITLE
New sites from the past few days are not being blocked by DNS services.

### ISSUE THREAD

**Issue by dotshe** [hagezi/dns-blocklists#4056]
Hi Hagezi,

We have detected several sites that do not appear to be blocked by different DNS services (Mullvad, ControlD), even though these sites are included in the following list: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling-onlydomains.txt.

Below is a list of some sites that are not being blocked despite being listed:

https://li.bet/
http://jugabet.cl/
http://thescorebet.com/
http://cachaca777.com/
http://crown4play.com/
https://www.retrobet.com/
http://www.888win14.com/
http://www.23bet8.com/
https://1wutz.com/
https://pari-match-br.com/
http://52bet.com/
https://73bet.com/
https://www.fatfruit.com/
https://liabilitypg.com/
http://wagerattack.ag/
http://blaze-8.com/
http://8855bet.net/
http://73bet.com/
https://777slot.com/
http://bhbet.com/
http://www.crazystar77.com/
http://www.sweetywin.com/
http://gmc03.com/
https://witi.li/9dc02ab6e5
https://z7885.com/
https://1-wins.br.com/
https://www.luckycircus.com/

Do you know what’s happening and how we can assist in resolving this issue?
Should we contact these DNS services directly, and how can we do that?

Thank you for you help.

**Comment by hagezi** [comment]
**Mullvad (updated yesterday)**: https://github.com/mullvad/dns-blocklists/blob/main/lists/doh/gambling/hagezi-gambling @jbjorkang

**ControlD:** I don't know at what intervals the gambling list is updated there. @yegors

**Comment by jbjorkang** [comment]
When you say DNS services, do you mean on our VPN servers, or our Encrypted DNS service?

**Comment by dotshe** [comment]
Hi @jbjorkang,

Thank you for your response.

We are discussing DNS services (over HTTPS), specifically the hostname "all.dns.mullvad.net," which includes the "gambling" category.

There is a discrepancy between the raw data maintained by Hagezi (https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling-onlydomains.txt) and Mullvad's raw data (https://github.com/mullvad/dns-blocklists/blob/main/lists/doh/gambling/hagezi-gambling). For example, the site "li.bet." However, we are not aware of the frequency with which you synchronize your file with Hagezi's. Based on the history on your GitHub, it appears that you synchronize every 7 days, so perhaps the issue with Mullvad is simply related to that.

**Comment by jbjorkang** [comment]
> Hi @jbjorkang,
> 
> Thank you for your response.
> 
> We are discussing DNS services (over HTTPS), specifically the hostname "all.dns.mullvad.net," which includes the "gambling" category.
> 
> There is a discrepancy between the raw data maintained by Hagezi (https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling-onlydomains.txt) and Mullvad's raw data (https://github.com/mullvad/dns-blocklists/blob/main/lists/doh/gambling/hagezi-gambling). For example, the site "li.bet." However, we are not aware of the frequency with which you synchronize your file with Hagezi's. Based on the history on your GitHub, it appears that you synchronize every 7 days, so perhaps the issue with Mullvad is simply related to that.

I'll forward this internally.

**Comment by dotshe** [comment]
Hi @oskaralmlov,

Thank you for your response. Everything is clear now: Mullvad syncs once a week, which might explain the difference between the list maintained by Hagezi and yours.

@yegors, as mentioned in another thread, is the "gambling" filter list synchronized every 30 minutes with Hagezi's raw list? And do we have access to the raw domains of ControlD's filters to ensure that a domain is properly accounted for on your end? We're asking because several sites added by Hagezi in recent days are still accessible when using ControlD's DNS (filter: gambling). We appreciated ControlD because the synchronization with Hagezi's list used to happen in less than 24 hours.

Thank you in advance for your response.

**Comment by hagezi** [comment]
Thanks for the clarification  @jbjorkang and @oskaralmlov.

**Comment by hagezi** [comment]
Thanks @yegors

**Comment by dotshe** [comment]
Thanks @yegors
