### ISSUE TITLE
Newrelic blocking too broad

### ISSUE THREAD

**Issue by oc013** [hagezi/dns-blocklists#4064]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

TechnitiumDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO

### Which domain(s) should be unblocked?

https://one.newrelic.com/

### Why should the domain(s) be unblocked?

The actual website for Newrelic is blocked in the few host lists I've tried. As a result, this prevents my usage of the lists. 

Beyond having a website tracking element, Newrelic also monitors server infrastructure, log files and helps with debugging applications 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The main domain is blocked to intercept numerous collector tracking subdomains. As of Pro this remains blocked.

For light and normal, I'll have to take a closer look first.

**Comment by hagezi** [comment]
Will be fixed in Light and Normal.
