### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by topminipie** [hagezi/dns-blocklists#4070]
### Which domain(s) should be blocked?

scorecardresearch.com
fullcirclestudies.com

### Why should these domain(s) be blocked?

More: [www.scorecardresearch.com](https://www.scorecardresearch.com), [www.fullcirclestudies.com](https://www.fullcirclestudies.com/home)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
scorecardresearch.com already blocked
