### ISSUE TITLE
ticktick.com tracking

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#4073]
### Which domain(s) should be blocked?

ms.ticktick.com
wssp.ticktick.com
wss.ticktick.com

### Why should these domain(s) be blocked?

Tracking TickTick Time Management App

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by aerz** [comment]
Hi @hagezi I would like to suggest that you review this tracking list for TickTick.

The `ms.ticktick.com` breaks the Pomodoro feature when it needs to sync with other devices. I have checked the webapp and this domain is not used for any other purpose. In fact. you could check the variables in [web-ap.js](https://d107mjio2rjf74.cloudfront.net/web/static/build/app/web.ap-ba2a3f93cca74db98401.js)

![ticktick-1](https://github.com/user-attachments/assets/02708501-21d1-4453-8f83-e019f62da2a1)

`wss` and `wssp` open a websocket connection for better sync.

![ticktick-2](https://github.com/user-attachments/assets/54719724-7e51-4a3b-a21b-52455d72be12)

They are using @sentry/browser based on the [third party licences](https://ticktick.com/license/web). I found out that `s.ticktick.com` is the domain where Sentry lives.

![ticktick-3](https://github.com/user-attachments/assets/2fe00fa8-c9c5-4960-8805-52713fdbd33a)

I don't know where you found the information about which domains track the user. I would like to know if I am wrong.

Thanks for the effort to make this blocklist. 🙏

**Comment by hagezi** [comment]
Thanks for the details @aerz, the domains were reported to me by the community. Allegedly tested, I'll have another look.

**Comment by hagezi** [comment]
Will be reverted ...
