### ISSUE TITLE
Blocklist format for Opnsense / Unbound

### ISSUE THREAD

**Issue by Chippel** [hagezi/dns-blocklists#4077]
Hey Hagezi. Unfortunately I couldnt find an answer regarding this. I would like to use the blocklists but I don’t know which format I should use. There a lists were it states it can be used for Opnsense and some saying it can be used for Unbound, which is the dns resolver being used in Opnsense. Any suggestions which to chose?

**Comment by hagezi** [comment]
![image](https://github.com/user-attachments/assets/9251a76e-0f7d-4c62-9036-4d0b499948fe)
