### ISSUE TITLE
Incorrectly blocked domain (metricool.com)

### ISSUE THREAD

**Issue by MRedondoMetricool** [hagezi/dns-blocklists#4079]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS, Other

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Allowlist Referral

### Which domain(s) should be unblocked?

metricool.com
mtr.bio

### Why should the domain(s) be unblocked?

Metricool (www.metricool.com) is a social media manager tool. More than 2 million professionals, agencies and brands use Metricool as their one-stop shop for social media and online ad management.

Some customers are complaining that their ad blocker is denying them access to *.metricool.com and *mtr.bio

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`metricool.com` is not blocked in my lists. `mtr.bio` is blocked in TIF List, via [phishing.army](https://phishing.army/) @drego85.

**Comment by drego85** [comment]
Hi @MRedondoMetricool, sorry for delay,can you help me better understand the use of the domain 'mtr.bio'? 

In some cases it has been used to spread phishing, as a redirect. 

Could this be a shorturl service also abused by criminals?
