### ISSUE TITLE
anydebrid.com

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#409]
premium link generator

**Comment by devipasigner** [comment]
@hagezi are you sure about this? I think more research has to be done, especially for bulk requests. 

See https://www.reddit.com/r/Piracy/comments/nbcnhm/anydebridcom/

**Comment by hagezi** [comment]
Will check. With the mass of issues yesterday, I didn't check everything in detail, just the usual. Thank you for pointing this out.

**Comment by hagezi** [comment]
I currently see nothing that would speak against whitelisting:

```
Domain:
 - anydebrid.com

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocking Lists/DNS:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.ULTIMATE OK
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      OK
 - OISD            OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=anydebrid.com
 - VirusTotal      https://www.virustotal.com/en/domain/anydebrid.com/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/anydebrid.com
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fanydebrid.com
 - FortiGuard      https://www.fortiguard.com/webfilter?q=anydebrid.com
 - Kaspersky       https://opentip.kaspersky.com/anydebrid.com?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=anydebrid.com
 - Norton          https://safeweb.norton.com/report/show?url=anydebrid.com
 - OpenDNS         https://domain.opendns.com/anydebrid.com
 - URLVoid         https://www.urlvoid.com/scan/anydebrid.com/
 - Yandex          https://yandex.com/safety/?l10n=en&url=anydebrid.com

```

**Comment by devipasigner** [comment]
> People are mad nowadays.
> 
> You can opt to not use a service and even deny access to the site because of poor quality and other issues. But you decide because you dislike/don't want to use it, then others mustn't use it and even think you do have the right to do so...
> 
> I cannot understand that.
> 
> This is also the case of #412, #413, #414. These sites are likely to have various issues but they remain on Chrome's top list until last month. And this means many users still choose to shop there. Are they all idiots? Or you think you can decide where they spend money on?
> 
> I have to ask what 's the border for a public blocklist project on earth? Does it exist to block ad, analytics and some nasty things. Or its existence is to block anything you don't like.
> 
> @hagezi

Excuse me? The reddit post I linked has people saying its a scam/ or its malicious in some way. I will check now. It is not enough to simply check using intel providers and checking if its in another blocklist.

**Comment by devipasigner** [comment]
https://www.trustpilot.com/review/anydebrid.com

**Comment by devipasigner** [comment]
I tried myself, they corrupted the file indeed. AND it was such a pain to even use the site. It kept saying adblocker deteded. Had to disable strict protection on ff, disable dns using hagezi, pause ublock.

**Comment by devipasigner** [comment]
What this site does.

Downloads the file and corrupts it.

Makes you watch more ads.

Saids you need to download it again

Repeat

....

**Comment by devipasigner** [comment]
Looks like its just a scam trying to imitate "RealDebrid". Its very popular amongst the piracy community so I can see why this scam would be in the top sites.

**Comment by devipasigner** [comment]
Yep, checked more reddit posts. This is a big scam. The fact that its in the top visited sites is concerning. @durablenapkin

maybe you would want to add it to your blocklist too

**Comment by durablenapkin** [comment]
Agreed, reviewed and will be added in next nightly update.

**Comment by hagezi** [comment]
The re-open issue.

Thanks for testing. Will re-add ...

**Comment by hagezi** [comment]
What should I check here? The pages are blocked because it is scam, and it stays that way.

**Comment by gototheskinny** [comment]
> The pages are blocked.

On MS Edge with adguard with this list it's blocked correctly BUT:
<details>
  <summary>ungoogled chromium and firefox + with ublock and adguard same results, even for adguard for ios with this list added to the app</summary>
  
![SharedScreensasfasfhot](https://github.com/hagezi/dns-blocklists/assets/51786709/0ff7538c-db07-4a5c-be2c-0ad0647a42b3)

  
  
</details>

it's probably on my side i bet
