### ISSUE TITLE
False positive: svd.se

### ISSUE THREAD

**Issue by kribjo** [hagezi/dns-blocklists#4094]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Diversion

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

svd.se

In:
 raw.githubusercontent.com-hagezi-dns-blocklists-main-dnsmasq-pro.txt

(NB, also in nsfw.oisd.nl-dnsmasq2 somehow!)

### Why should the domain(s) be unblocked?

Web site of second largest national mainstream daily newspaper in Sweden.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Not blocked in my lists.

**Comment by kribjo** [comment]
Sorry for false alarm, I must have misinterpreted my search through the files! I agree about the subdomains of course.
