### ISSUE TITLE
Some daily use sites are not properly loaded with pro + and below lists

### ISSUE THREAD

**Issue by CodeCruncher24** [hagezi/dns-blocklists#4096]
Hi there,

Can you pls check if daraz.pk and aliexpress.com are accessible without whitelisting? If we can block tracking and not break functionality or this is a necessary precaution?

Thanks!

**Comment by hagezi** [comment]
I have tested the pages with Ultimate and see no problems or missing elements.


What exactly is the problem?

**Comment by CodeCruncher24** [comment]
Once the initial page loads and you scroll down, the rest of the loading doesn't happen. These sites usually are loaded upon further scroll and eince this isn't happening, other pages do not load as well -- for example: pages.daraz.pk

**Comment by hagezi** [comment]
Is not reproducible for me. Pages load normally and completely.

**Comment by hagezi** [comment]
It must be something in your network or with the DNS.

**Comment by CodeCruncher24** [comment]
Quite strange. I have been using cloudflare as dns and recently switched to dns0 (zero). 

Will switch other lists off from control d and only keep yours for another run. For now, I have manually whitelisted it these domains. 

Also, on a side note -- is it advisable to use iCloud private relay along with control d? I would really like to honestly. Helps with secondary option which is anonymous.
