### ISSUE TITLE
Online DNS Services

### ISSUE THREAD

**Issue by L0RYP0SY** [hagezi/dns-blocklists#4100]
dns: hard.dnsforge.de
lists: hagezi ultimate + tif + oisd 
(without whitelist) (with DNSSEC) (no ecs) (no logs)
server: germany
test: https://www.dnscheck.tools/
https://d3ward.github.io/toolz/adblock.html

**Comment by hagezi** [comment]
Yes, I know that, but I don't include any DNS in the section that offer a compilation of various lists.
