### ISSUE TITLE
https://www.full4movies.my/

### ISSUE THREAD

**Issue by Rachitidk** [hagezi/dns-blocklists#4109]
Poster disappeared when enabled.
HaGeZi's Pro mini DNS/Browser Blocklist.
When enabled 
![1000110848](https://github.com/user-attachments/assets/3b2a4e6a-2dc9-4990-aea8-48e870eca524)
When disabled
![1000110847](https://github.com/user-attachments/assets/e5a5d166-982b-480d-af8d-a476c8f65331)

**Comment by hagezi** [comment]
imgshare.info @bongochomg

**Comment by bongochong** [comment]
Thanks @hagezi! Was away for a few days. Will get this whitelisted.
