### ISSUE TITLE
Add some rules

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4112]
### Which domain(s) should be blocked?

HUAWEI Privacy Collection
||openlocation-drcn.platform.dbankcloud.com
||msch.f.360.cn
||ubacollect-drcn.cloud.dbankcloud.cn

Tomato Novel Software  ad
||ads*-normal-*.zijieapi.com^
||mssdk*.zijieapi.com^
||frontier100-toutiao-lf.fqnovel.com^
||pglstatp-toutiao.com

tencent  ads
||dnet.mb.qq.com
||yun-hl.3g.qq.com
||tmfsdktcpv4.m.qq.com
||dl.txcdns.com
||url.cn
||cdn-go.cn

Other

||bigfun.cn
||biligame.com
||activity.hdslb.com
||interface.bilibili.com
||resolver.dingtalk.com
||loggw.alipay.com
||log-api.pangolin-sdk-toutiao.com
||grpc.biliapi.net
||gepush.com
||getui.net
||igexin.com
||getui.cn
||getui.com
||wts.xinwen.cn
||config.cmpassport.com
||alog.umeng.com
||ulogs.umeng.com
||errlog.umeng.com

### Why should these domain(s) be blocked?

These are some of the domains that I collect for advertising or for privacy, and I don't know if your rules already include these, but I still give you the rules of collection. I've used these rules, and I haven't noticed anything unusual for the time being, and the ad blocking effect is strong. I hope to add it, the top three are the rules about Huawei, then an ad for a software called Tomato Novel, then an ad for Tencent, and then some other software ads

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Thank you @Shura23, I'll take a look in detail.

**Comment by Shura23** [comment]
Sorry, above || mssdk.zijieapi.com should be modified.Change to||mssdk*.zijieapi.com^  There was a little problem

**Comment by Shura23** [comment]
> Thank you @Shura23, I'll take a look in detail.

I made a mistake in copying a rule above, I hope to change it

**Comment by Shura23** [comment]
> Thank you @Shura23, I'll take a look in detail.

I would like to ask if you have included all the rules I have provided, why do I show here that there are no rules?For example, the following domain name is not blocked.
![Screenshot_20241028_162324_com.adguard.android.jpg](https://github.com/user-attachments/assets/b8248dac-149d-47c1-ad2f-a686c3a686e5)
