### ISSUE TITLE
Add some rules

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4117]
### Which domain(s) should be blocked?

baidu  Advertising domains

||activity.baidu.com
||pae.baidu.com
||udpolimeok.baidu.com
||ext.baidu.com^
||mime.baidu.com^
||sepro.baidu.com^
||fxgate.baidu.com^
||pcrec.baidu.com^
||suggestion.baidu.com^
||usug.baidu.com
||miaowu.baidu.com
||nourl.ubs.baidu.com
||libs.baidu.com
||wappass.baidu.com
||mbd.baidu.com
||ms.bdstatic.com
||haoma.baidu.com
||pos.baidu.com
||eclick.baidu.com
||crs.baidu.com
||mbdq02.bdstatic.com

ByteDance Advertising domains

||bds.snssdk.com
||toblog.ctobsnssdk.com
||log-api.pangolin-sdk-toutiao.com
||sf1-be-pack.pglstatp-toutiao.com
||api-access.pangolin-sdk-toutiao.com

Other
||bsccdn.net
||00cdn.com
||88cdn.com
||apd-pcdnwxlogin.teg.tencent-cloud.net
||apd-pcdnwxnat.teg.tencent-cloud.net
||dyp2p-ali.douyucdn.cn
||dyp2p-hw.douyucdn.cn
||kuiniuca.com
||onethingpcs.com
||p2p-ali.douyucdn.cn
||p2p.huya.com
||p2p.qq.com
||p2pchunk-hw.douyucdn.cn
||p2pchunk-table.douyucdn.cn
||p2pchunk-ws.douyucdn.cn
||p2perrorlog.douyucdn.cn
||p2plive-ali.douyucdn.cn
||p2plive-ws.douyucdn.cn
||p2plog.douyucdn.cn
||p2ptun.qq.com
||p2pupdate.gamedl.qq.com
||p2pupgrade.gamedl.qq.com
||p2pvod-ws.douyucdn.cn
||pcdn.yximgs.com
||pkoplink.com
||saxysec.com
||stun.douyucdn.cn
||stun.hitv.com
||stun1.douyucdn.cn
||szbdyd.com
||uhabo.com
||xycdn.com
||*pcdn*.biliapi.net^
||i.snssdk.com
TaoBao  Advertising domains
||wcp.taobao.com
||acs.m.taobao.com

QQ music 
||wnsmusic.qq.com
||tmeadbak.y.qq.com
||ugcup.music.qq.com
||ad.tencentmusic.com
||ipv6.kg.qq.com
||tmeadbak.y.qq.com

Vivo
||h5.vivo.com.cnt
||browser.vivo.com.cn
||zhan.vivo.com.cn
||onewsvod.com
||yidianzixun.com
||ads-marketing-vivofs.vivo.com.cn
||*browser*.vivo.com.cn

kuaishou
||apidns.kwd.inkuai.com
||kuaishou.httpdns.pro
||hdns.ksyun.com
||open.e.kuaishou.com
||open.e.kuaishou.com

NetEase Cloud Music
||netapm.music.163.com
||natdetection.onethingpcs.com
||lbs.netease.im
||ipv6.music.163.com
||ipv4.music.163.com
||iadmusicmat.music.126.net

### Why should these domain(s) be blocked?

These rules are also something I've painstakingly collected and hope to add to the filter

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Most of them were already blocked.

**Comment by Shura23** [comment]
> 他们中的大多数已经被封锁了。将来，请先检查哪些内容没有被阻止，这样可以节省我的工作。此外，有关域的更多详细信息将非常有用，这样我就不必详细分析每个域。我不是想在这里做任何 try 和 error 阻止......

OK
