### ISSUE TITLE
netflix-logariasmos.com: badware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4124]
### Which domain(s) should be blocked?

```
https://lihi.cc/lVY7W
netflix-logariasmos.com
```

### Why should these domain(s) be blocked?

The first link is sent via SMS in Greece with a message stating that “We failed to process your payment. Please change your personal details to avoid account blockage.” Upon opening the link, it redirects to netflix-logariasmos.com, which likely requires a mobile user agent since it appears blank on a PC. Additionally, I’ve observed numerous unusual redirects, as illustrated in the attached screenshot.

<img width="234" alt="image" src="https://github.com/user-attachments/assets/b3756a3c-9a3f-4dfd-a74f-30edb7d339f0">

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`lihi.cc` is a url shortener service ...

**Comment by ExtRIELICi** [comment]
> `lihi.cc` is a general url shortener service ...

I am aware. However, I am asking for `netflix-logariasmos.com` to be blocked, not `lihi.cc`. I put the initial link there for reference and so you can follow the redirection process. @hagezi

**Comment by hagezi** [comment]
Sorry @ExtRIELICi  ...
