### ISSUE TITLE
Falsely blocked steamcommunity.com

### ISSUE THREAD

**Issue by TieJu** [hagezi/dns-blocklists#4126]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

dnsmask

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

steamcommunity.com

### Why should the domain(s) be unblocked?

It is one of the many urls that is used by the steam store ( https://en.wikipedia.org/wiki/Steam_(service) ).
The steamcommunity.com esp is used for community features, like forums and also for authentication for third parties through stream.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@TieJu mot blocked in my lists.
