### ISSUE TITLE
revanced.net allow or block ?

### ISSUE THREAD

**Issue by edouardkleinhans** [hagezi/dns-blocklists#4131]
Why revanced.net is block. It seems to be a way of having YouTube vanced on our smartphone.

https://github.com/revancedapps/revanced.net

**Comment by hagezi** [comment]
Via @iam-py-test anti malware list.

**Comment by burakdede0** [comment]
Official website is revanced.app

.net one isn't affiliated with ReVanced team.

**Comment by user716253** [comment]
Revanced.app is the official one
