### ISSUE TITLE
Add slovakroots.blogspot.com (and perhaps even .blogspot.com) to whitelist

### ISSUE THREAD

**Issue by superduke1010** [hagezi/dns-blocklists#4132]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Unbound/DoT Cloudflare on OPNSense

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Threat Intelligence Feeds, Dynamic DNS, Badware Hoster

### Which domain(s) should be unblocked?

slovakroots.blogspot.com or blogspot.com

### Why should the domain(s) be unblocked?

Doesn't appear to be a threat.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Not blocked in the TIF. Blogspot is blocked in the badware hoster list because a lot of malicious stuff is hosted on it.
