### ISSUE TITLE
Add rules

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4139]
### Which domain(s) should be blocked?

HUAWEI ads
||adx-drcn.op.dbankcloud.cn
||vali-g1.cp31.ott.cibntv.net
||events-drcn.op.dbankcloud.cn

BiliBili ads
||*-pcdn-*.biliapi.net^
||app.bilibili.com

### Why should these domain(s) be blocked?

The first three are Huawei advertising domains, appearing in Huawei Video and Huawei Music software

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`adx-drcn.op.dbankcloud.cn` and `events-drcn.op.dbankcloud.cn` - already blocked.
`app.bilibili.com` on allowlist.

**Comment by Shura23** [comment]
> `adx-drcn.op.dbankcloud.cn` and `events-drcn.op.dbankcloud.cn` - already blocked.
> `app.bilibili.com` on allowlist.

I use your ultimate rule，events-drcn.op.dbankcloud.cn  and adx-drcn.op.dbankcloud.cn are not blocked。I've tested

**Comment by hagezi** [comment]
Yes, they are ...

![grafik](https://github.com/user-attachments/assets/21c8dbf8-a158-473b-8520-598da1ba5353)

![grafik](https://github.com/user-attachments/assets/b01fc1b4-e20f-46dc-a152-fe88ad9006b5)

![grafik](https://github.com/user-attachments/assets/cbd01889-790b-4c7d-86d4-c95bcebb8d7b)

**Comment by Shura23** [comment]
> Yes, they are ...
> 
> ![grafik](https://github.com/user-attachments/assets/21c8dbf8-a158-473b-8520-598da1ba5353)
> 
> ![grafik](https://github.com/user-attachments/assets/b01fc1b4-e20f-46dc-a152-fe88ad9006b5)
> 
> ```
> curl -sl https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/ultimate.txt | grep -P '(adx-drcn.op.dbankcloud.cn|events-drcn.op.dbankcloud.cn)'
> ||adx-drcn.op.dbankcloud.cn^
> ||events-drcn.op.dbankcloud.cn^
> ```
> 
> ![grafik](https://github.com/user-attachments/assets/cbd01889-790b-4c7d-86d4-c95bcebb8d7b)
> 
> 

Look at my situation here
![Screenshot_20241031_044625_com.adguard.android.jpg](https://github.com/user-attachments/assets/8afd352e-3f22-4d5f-8c54-44d4c8323636)

![Screenshot_20241031_044706_com.adguard.android.jpg](https://github.com/user-attachments/assets/f40f86ab-00f9-4347-9a31-4dcd17b4a667)

![Screenshot_20241031_044733_com.adguard.android.jpg](https://github.com/user-attachments/assets/ca02f305-5157-4f3f-8c46-a62af0cd2ff5)

That's why I said that there were no two rules
