### ISSUE TITLE
Potential Xiaomi trackers?

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4141]
### Which domain(s) should be blocked?

```
eu.global.market.xiaomi.com
fr.app.chat.global.xiaomi.net
api.sec.intl.miui.com
eu-gamecenter.api.intl.miui.com
api.gallery.intl.miui.com
appvault-a.api.intl.miui.com
browser.cdn.intl.miui.com
brs.api.intl.miui.com
newsfeed.api.intl.miui.com
weatherapi.intl.xiaomi.com
```
_(I'm pretty sure the last one will break the Weather app, but I'm reporting it anyways, just in case there is something to be found)_

### Why should these domain(s) be blocked?

My Xiaomi smartphone frequently connects to these domains. Many are already blocked by other filter lists, as shown in the screenshot below. However, some remain unblocked and may not be trackers. I thought it would be helpful to report them here. There are many more to report, but the overwhelming amount of spam in my DNS logs makes them difficult to locate and identify.

<img width="355" alt="image" src="https://github.com/user-attachments/assets/e9c4bfd3-f764-47bc-bc9c-086ec46877cf">

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
It's impressive what is blocked in other lists and labelled as trackers. They are on my allowlist because they restrict functions.

But I'll have another look.

**Comment by Shura23** [comment]
> It's impressive what is blocked in other lists and labelled as trackers. They are on my allowlist because they restrict functions.
> 
> But I'll have another look.
> 
> Using DNS lists as de-bloaters is neither useful nor particularly effective. There are tools for that. I will never understand why people use such extreme monitoring devices.

Because Xiaomi phones are cheap

**Comment by ExtRIELICi** [comment]
> I will never understand why people use such extreme monitoring devices.

I bought it years ago because it was the best value-for-money option available.

Unfortunately, Xiaomi phones remain extremely popular in the Balkans and Eastern Europe due to their price and specs, though most people aren’t aware of the potential security and privacy issues.

However, today I only use it as a backup Android phone, as I’ve since switched to an iPhone.

**Comment by Shura23** [comment]
> > I will never understand why people use such extreme monitoring devices.
> 
> I bought it years ago because it was the best value-for-money option available.
> 
> Unfortunately, Xiaomi phones remain extremely popular in the Balkans and Eastern Europe due to their price and specs, though most people aren’t aware of the potential security and privacy issues.
> 
> However, today I only use it as a backup Android phone, as I’ve since switched to an iPhone.
> 
> 

Apple phones aren't secure either

**Comment by ExtRIELICi** [comment]
> Apple phones aren't secure either

Well, they’re actually more private than most Android phones out there. I can also see this in the DNS logs, as my iPhone connects to Apple domains far less frequently than any of my Android devices in my NextDNS setup.

The only truly private OS is GrapheneOS, but Pixel devices don’t work well in unsupported countries, so that’s not a practical option.

As for security, both stock Android and iOS are excellent; the main issues arise from the skins and bloatware that other manufacturers choose to install.
