### ISSUE TITLE
Breaks angry birds 2 game

### ISSUE THREAD

**Issue by Headway4658** [hagezi/dns-blocklists#4145]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi ULTIMATE

### Which domain(s) should be unblocked?

prod.angrybirdsbigadventure.net

### Why should the domain(s) be unblocked?

Breaks angry birds 2 game

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@Headway4658 What exactly is not working? The domain has been blocked because ads are being distributed via it.

**Comment by hagezi** [comment]
Tested, crash on first start.
