### ISSUE TITLE
meta Facebook marketplace support scam

### ISSUE THREAD

**Issue by wowfilip999** [hagezi/dns-blocklists#4153]
### Which domain(s) should be blocked?

feji.us

In Adblock
https://feji.us/facebook-marketsupport

### Why should these domain(s) be blocked?

Scam that pretend to be from meta marketplace support they say if you dont verify you account Will be removed 
![Messenger_creation_F97A7C4E-A8CB-4CC5-84F0-191E7DAD21EB](https://github.com/user-attachments/assets/f8557604-a0da-4141-a23e-73ceac1d57fb)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by durablenapkin** [comment]
`feji.us` is a link shortener service
The link mentioned in first post leads to `facebook-support-team-980.pages.med.br` which I'll block.

**Comment by hagezi** [comment]
Yes, NRD, but ... https://www.virustotal.com/gui/url/fffa5d4bbb9628f3de9601ffab7ef5122e9d45651859c61aa31472e61700111a

**Comment by iam-py-test** [comment]
Sorry for my absence.
I have blocked feji.us as a URL shortener, and the domain mentioned in https://github.com/hagezi/dns-blocklists/issues/4153#issuecomment-2452140418 as phishing.
Thanks
