### ISSUE TITLE
DoH/VPN/TOR/Proxy Bypass - Mode Host

### ISSUE THREAD

**Issue by victorvs0uz4** [hagezi/dns-blocklists#4154]
Hello, would it be possible to have a **DoH/VPN/TOR/Proxy Bypass - Complete Edition** list, in Host mode?

This way I can integrate it with my Mikrotik.

Thank you!

**Comment by hagezi** [comment]
No, this list requires adblockers that support wildcard blocking, i.e. that automatically block all subdomains for a domain on the list.
