### ISSUE TITLE
javplayer.org

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#4164]
### Which domain(s) should be blocked?

javplayer.org

### Why should these domain(s) be blocked?

<details>
  <summary>Screenshot</summary>
  
![20241102-1730549228](https://github.com/user-attachments/assets/ab436a17-4b6f-4724-93c2-5d73d1661584)

</details>

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jordansworld** [comment]
looks like just a porn site
