### ISSUE TITLE
add @@||apissl.ksapisrv.com^

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4166]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

apissl.ksapisrv.com

### Why should the domain(s) be unblocked?

This domain name is used to query the history of Kwai. Disabling this domain name will result in the inability to query historical records.I hope you can also help me add this rule :||*-pcdn-*.biliapi.net^
I submitted this rule to you before, but I found it didn't work. Did you forget to add it?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Again, blocked in all list versions ....

![grafik](https://github.com/user-attachments/assets/c5811c40-aad2-4775-a187-7cd19a253689)

**Comment by Shura23** [comment]
> @Shura23 `||-pcdn-.biliapi.net`: My list contains plain domains, no wildcard adblock rules. The adblock format is also compatible with adblockers that do not allow wildcards in the rules.
> 
> By the way, your rule is not a valid rule, correct would be `||*-pcdn-*.biliapi.net^`

Sorry, I don't know what happened with this rule. There was an error in copying.

**Comment by Shura23** [comment]
> @Shura23 `||-pcdn-.biliapi.net`: My list contains plain domains, no wildcard adblock rules. The adblock format is also compatible with adblockers that do not allow wildcards in the rules.
> 
> By the way, your rule is not a valid rule, correct would be `||*-pcdn-*.biliapi.net^`

Sorry, I don't know what happened with this rule. There was an error in copying.
