### ISSUE TITLE
idnes.cz: mfr.cdn.dopc.cz (CNAME lb1.antiadblock.cz)

### ISSUE THREAD

**Issue by pegasbay** [hagezi/dns-blocklists#4167]
### Which AdBlocker/DNS cloud service do you use?

AdGuard, AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi PRO++ mini, Multi ULTIMATE, Multi ULTIMATE mini

### Which domain(s) should be unblocked?

**EDIT hagezi:**
`mfr.cdn.dopc.cz` (CNAME `lb1.antiadblock.cz`)

### Why should the domain(s) be unblocked?

**EDIT hagezi:**
Breaks site layout on `idnes.cz`

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The main domain `idnes.cz` is not blocked in my lists,

**Comment by pegasbay** [comment]
That’s strange. The webpage is broken or completely inaccessible with the pro++ and ultimate blocklists. However with the pro blocklist the webpage is fine.
![IMG_0152](https://github.com/user-attachments/assets/1faa256d-79db-42a5-98f9-786448e0a4bf)
![IMG_0153](https://github.com/user-attachments/assets/54ac538c-d6fe-4096-bc36-93c905e56001)

**Comment by hagezi** [comment]
@pegasbay Yes, without a browser content blocker, the page is also displayed like this because the anti-adblock script is loaded. The following domains must be allowed if you only use DNS:

`mfr.cdn.dopc.cz` (CNAME `lb1.antiadblock.cz`)

**Comment by pegasbay** [comment]
OK, using Opera for iOS with the in-built content blocker but it is quite weak. Thx for the exceptions, added to AdGuard DNS for iOS and the webpage in question works.
