### ISSUE TITLE
Google ad settings

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#4178]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

`adssettings.google.com`

### Why should the domain(s) be unblocked?

This is only used to change your google account ad settings. Not used for tracking.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by mtheofy** [comment]
Will this be removed from other lists as well? e.g. the Multi.light RPZ list?

**Comment by hagezi** [comment]
Yes
