### ISSUE TITLE
Block trackers

### ISSUE THREAD

**Issue by zhg7** [hagezi/dns-blocklists#4182]
### Which domain(s) should be blocked?

tags.imagin.com
sst.evobanco.com
aaaadagxwrajaaaaaaaaaaa5ci.apm-agt.eu-frankfurt-1.oci.oraclecloud.com
stats.controld.com

### Why should these domain(s) be blocked?

Tealium tag manager, Google tag manager, Oracle real user monitoring, Matomo instance

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
stats.controld.com is a tracker?

**Comment by zhg7** [comment]
![firefox_cREq7tEFgM](https://github.com/user-attachments/assets/9239ac55-7d52-4639-ab96-469c3f76ad99)

**Comment by jordansworld** [comment]
i dont think stats.controld.com is a tracker.
