### ISSUE TITLE
add some rule

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4188]
### Which domain(s) should be blocked?

||pis-tel-pcdn.youku.com^
||player-lg.youku.com^
||qn-livewebbs2pcdn.msstatic.com^
||qn-hydlpcdn.cdn.huya.com^
||qn-fileserverpcdn.cdn.huya.com^
||appcfg.v.qq.com^
||puui.qpic.cn^
||ltsgdty.gtimg.com^
||monitor.l.qq.com^
||gjfzpt.cn
||jomodns.cn
||tpa-hcdn.iqiyi.com
||hw-sh-pcdn-26.biliapi.net
||hw-sh-pcdn-110.biliapi.net
||hw-sh-pcdn-134.biliapi.net
||hw-sh-pcdn-112.biliapi.net
||hw-sh-pcdn-12.biliapi.net
||hw-sh-pcdn-32.biliapi.net
||hw-sh-pcdn-09.biliapi.net
||hw-sh-pcdn-28.biliapi.net
||hw-sh-pcdn-08.biliapi.net
||hw-sh-pcdn-93.biliapi.net
||hw-sh-pcdn-97.biliapi.net
||hw-sh-pcdn-10.biliapi.net
||hw-sh-pcdn-106.biliapi.net
||hw-sh-pcdn-11.biliapi.net
||hw-sh-pcdn-38.biliapi.net
||hw-sh-pcdn-94.biliapi.net
||hw-sh-pcdn-33.biliapi.net
||hw-sh-pcdn-20.biliapi.net
||hw-sh-pcdn-12.biliapi.net
||hw-sh-pcdn-113.biliapi.net
||punch.p2p.qq.com^
||ws-p2p.pull.yximgs.com^
||ws-p2p-pull.live-voip.com^
||ws-p2p-v2.pull.yximgs.com^
||ws-p2p-pull.video-voip.com^
||qn-cdnfile1pcdn.msstatic.com^
||pp-cdnfile1pcdn.msstatic.com^
||qn-fileserverpcdn.cdn.huya.com^
||xy-fileserverpcdn.cdn.huya.com^
||xy-cdnfile1pcdn.msstatic.com^
||xy-livewebbs2pcdn.msstatic.com^
||qn-livewebbs2pcdn.msstatic.com^
||fileserverpcdn.cdn.huya.com^
||livewebbs2pcdn.msstatic.com^
||tx-p2p.pull.yximgs.com^
||tx-p2p-pull.video-voip.com^
||tx-p2p-v2.pull.yximgs.com^
||tx-p2p-pull.live-voip.com^
||ali-bj-pcdn-11.biliapi.net^
||qn-hydlpcdn.cdn.huya.com^
||ks-p2p.pull.yximgs.com^
||hw-p2p-v2.pull.yximgs.com^
||hw-p2p-pull.video-voip.com^
||hw-p2p.pull.yximgs.com^
||hw-p2p-pull.live-voip.com^
||ali-p2p.pull.yximgs.com^
||ali-p2p-v2.pull.yximgs.com^
||pis-tel-pcdn.youku.com^
||player-lg.youku.com^

### Why should these domain(s) be blocked?

Add these ad rules

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Some are already blocked, add the missing ones to the aggressive lists, starting with Pro++.

**Comment by Shura23** [comment]
> Some are already blocked, add the missing ones to the aggressive lists, starting with Pro++.

I would be interested to know if you have added the domain name I provided to the filter. I updated the rules and found that some domains were not blocked. For example, the domain name shown in the figure is not blocked.Did you forget to add this domain name?
![Screenshot_20241105_144432_com.adguard.android.jpg](https://github.com/user-attachments/assets/65183a53-4a08-4051-97f8-511823f80182)

**Comment by hagezi** [comment]
![grafik](https://github.com/user-attachments/assets/32e25867-e160-4fa5-951c-9ea30d17632f)

![grafik](https://github.com/user-attachments/assets/1deda70b-7707-4f85-895e-7694b72c0b92)

**Comment by hagezi** [comment]
![grafik](https://github.com/user-attachments/assets/03633767-7034-4d3a-a480-cb55b990e0ee)

**Comment by Shura23** [comment]
> ![grafik](https://github.com/user-attachments/assets/32e25867-e160-4fa5-951c-9ea30d17632f)
> 
> ![grafik](https://github.com/user-attachments/assets/1deda70b-7707-4f85-895e-7694b72c0b92)
> 

Then I suspect it's a bug in Adguard itself

**Comment by Shura23** [comment]
> ![grafik](https://github.com/user-attachments/assets/03633767-7034-4d3a-a480-cb55b990e0ee)
> 

Could you see if the following domain name is missing.
![Screenshot_20241116_170432_com.adguard.android.jpg](https://github.com/user-attachments/assets/74ae1f69-9492-4dae-bc0c-64b3be234255)

**Comment by hagezi** [comment]
The domain `hw-sh-pcdn-94.biliapi.net` is dead (NXDOMAIN):

```
dig hw-sh-pcdn-94.biliapi.net @1.1.1.1

; <<>> DiG 9.16.50-Debian <<>> hw-sh-pcdn-94.biliapi.net @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 60135
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;hw-sh-pcdn-94.biliapi.net.     IN      A

;; AUTHORITY SECTION:
biliapi.net.            600     IN      SOA     vip1.alidns.com. hostmaster.hichina.com. 2024083011 3600 1200 86400 600

;; Query time: 11 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sat Nov 16 19:13:14 CET 2024
;; MSG SIZE  rcvd: 124
```
