### ISSUE TITLE
Needed to whitelist 2 domains to get SMS MFA working again for Coventry Building Society (UK)

### ISSUE THREAD

**Issue by Altycoder** [hagezi/dns-blocklists#4189]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

*.first.iovation.com
*.mpsnare.iesnare.com

### Why should the domain(s) be unblocked?

SMS verification codes from Coventry Building Society (UK) do not appear otherwise

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@Altycoder Can't find `*.first.iovation.com` and `*.mpsnare.iesnare.com` on my lists. Can you check what the blocking reason is in the NextDNS log?

**Comment by Altycoder** [comment]
Sorry, I'm late reporting it and it's rotated off my logs since.  I can see
other subdomains of iovation.com in your pro list but not the specific one
I've whitelisted you are correct so maybe this was blocked by nextdns.

I'll remove and report back, thanks

**Comment by hagezi** [comment]
Thanks @0mMdy8R6uS8xpP

**Comment by Altycoder** [comment]
> I just tested the domains and it seems they are blocked by NextDNS Ads & Trackers Blocklist instead of hagezi lists

In that case, my apologies

**Comment by Altycoder** [comment]
> I just tested the domains and it seems they are blocked by NextDNS Ads & Trackers Blocklist instead of hagezi lists

In that case, my apologies

**Comment by hagezi** [comment]
No problem @Altycoder ;)
