### ISSUE TITLE
Apple DNS

### ISSUE THREAD

**Issue by vdias** [hagezi/dns-blocklists#4190]
### Which domain(s) should be blocked?

Some Apple DNS host that need to be added to your lists...

*.doh.dns.apple.com.v.aaplimg.com
*.doh.dns.apple.com
*.apple-relay.fastly-edge.com
*.apple-relay.cloudfare.com
*.mask-h2.icloud.com
*.mask.icloud.com

### Why should these domain(s) be blocked?

Apple custom DOH and rely.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@vdias 

Already blocked in the bypass list, missing:

```
apple-relay.fastly-edge.com
apple-relay.cloudfare.com
```

**Comment by vdias** [comment]
What do you mean by "blocked with bypass list"?

I'm using HaGeZi - Multi PRO++ with the NextDNS service. Is this BypassList compatible with my setup?

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#bypass

These domains have no place in my normal lists.

**Comment by vdias** [comment]
NextDNS is becoming a real pain in the ass... What is your actual recommendation for online services as NextDNS?

**Comment by hagezi** [comment]
Features are one thing, performance is another. You can't make a general recommendation, test the services and decide. Here is an overview of which lists are available where: https://github.com/hagezi/dns-blocklists/wiki/FAQ#availablelists

The fact is, NextDNS works very well in most regions and is stable. As far as the features are concerned, nothing has been done for a long time, so the lists behind the features are completely outdated. Other services can do this much better.

**Comment by vdias** [comment]
Sounds like returning to Adguard Home on a free AWS vm open to internet...

**Comment by hagezi** [comment]
Self-hosted and access via DoH/DoT/Quic with access restriction is definitely the most flexible option. But I wouldn't make legacy DNS available to the public.

**Comment by vdias** [comment]
How do you apply "access restriction" for mobile phones over 5G ?

**Comment by hagezi** [comment]
There are instructions on the net, e.g. https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption

1. Use encrypted DNS only with ClientIDs
2. Settings > DNS > DNS Settings > Access Settings > Allowed Clients (by ClientID)
3 ...

Off topic ...
