### ISSUE TITLE
`meredithcorp.io`

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#420]
Pro++

Please check `https://ew.com/theater/britney-spears-broadway-musical-justin-guarini-once-upon-a-one-more-time/`. Images, and possibly video, is blocked.

```
imagesvc.meredithcorp.io
cdn.video.meredithcorp.io
```

**Comment by hagezi** [comment]
Checked, to whitelist:

```
playback.video.meredithcorp.io
imagesvc.meredithcorp.io
cdn.video.meredithcorp.io
```

Will be removed.
