### ISSUE TITLE
multipro ++ traffic-nts-ip-assoc.xy.fbcdn.net being blocked

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4200]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

traffic-nts-ip-assoc.xy.fbcdn.net

### Why should the domain(s) be unblocked?

not a tracker or ad

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
You are completely wrong ...

https://github.com/hagezi/dns-blocklists/blob/64b90694fc9a96110ee2183cb6041d384942cd72/submit_pullrequest_here/deny_pro-ultimate.txt#L15

https://github.com/hagezi/dns-blocklists/issues/3010

https://lemmy.ml/post/10121519
https://mastodon.social/@protonmail/111699323585240444

FYI: @celenityy

**Comment by jordansworld** [comment]
sorry i didnt know it is used for trackinv
