### ISSUE TITLE
Potential Microsoft trackers

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4201]
### Which domain(s) should be blocked?

```
continuum.dds.microsoft.com
cs.dds.microsoft.com
aad.cs.dds.microsoft.com
settings-win.data.microsoft.com
ecn.dev.virtualearth.net
```

### Why should these domain(s) be blocked?

They appear in Windows 11 DNS logs, but I’m not sure if they are trackers. However, all of them are blocked by NextDNS’s Native Tracking Protection and other filter lists, but not by HaGeZi lists, so I thought it might be helpful to share them here.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Why don't you first search for what the domains are used for? Google, ChatGPT, ... provides information ...
