### ISSUE TITLE
some more domains

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4203]
### Which domain(s) should be blocked?

vtrk.dv.tech (doubleverify)
analytics.rawsrv.com
self.events.data.microsoft.com
ads9.textra.me
scorecard.research.com
mon16-normal-useast5.tiktokv.us
mon16-platform-useast5.us.tiktokv.com
hrzn-nxt.com
edoinc.com
edo.com

### Why should these domain(s) be blocked?

trackers

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Some are already blocked ...

**Comment by jordansworld** [comment]
oh. i double checked on my end and they didnt show in my log as blocked by your list. Apologies

**Comment by hagezi** [comment]
Some are only blocked in Ultimate, for good reason. Some are blocked via CNAME, e.g. `ads9.textra.me` is blocked via the CNAME `ads.textra.me`.
