### ISSUE TITLE
Suggestion: Adding Stable Native Trackers (e.g., Xiaomi, Samsung) to the "Normal" Blocklist

### ISSUE THREAD

**Issue by wengkitt** [hagezi/dns-blocklists#4207]
In [the statistics](https://github.com/hagezi/dns-blocklists/blob/main/statistics.md), I noticed that the native trackers for Xiaomi and Samsung no longer have the 'EXPERIMENTAL' label, which suggests they may now be stable. If possible, would you consider adding these to the "normal" blocklist? Also, for any future native trackers that appear stable, it would be wonderful if they could be added to the "normal" blocklist as well. Thank you very much for your work and for considering this request!

**Comment by hagezi** [comment]
I'll do it, it's on my to-do list, but it's a long one. I prefer that.
