### ISSUE TITLE
Apple Support Diagnostics

### ISSUE THREAD

**Issue by mk-au** [hagezi/dns-blocklists#4209]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

odin-signals.apple.com
idiagnostics.apple.com

### Why should the domain(s) be unblocked?

I had to white list both of these to get the Apple Support diagnostics tool to run on my phone.
I booked it for a battery replacement, and they sent me a text with a diag:// url, which opens the Apple diagnostics app on the phone and collects diagnostics info.

With idiagnostics.apple.com blocked, the phone stalled on "Loading Apple Diagnostics" or some sort of similar message, I can't remember the exact wording now.

Once whitelisted, that worked.

The next step collects and submits diagnostic info.

With odin-signals.apple.com blocked, it stalls half way through capturing info from the phone and won't complete.

With both unblocked, the diagnostics loads, runs and finishes properly.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by mk-au** [comment]
I've whitelisted both of these in NextDNS, so this isn't an issue for me going forward, but might be an issue for others. Especially if they go to the Apple store and Apple try to run diagnostics and it doesn't work. I don't know if, when this is run in the Apple Store, it's still dependent on these URLs or not.

**Comment by hagezi** [comment]
Thanks @mk-au 
FYI @celenityy

**Comment by celenityy** [comment]
Good to know. These domains are called on their own, so I think it'd probably still be worth blocking them in Ultimate, but makes sense to remove for the less aggressive lists.

**Comment by hagezi** [comment]
I don't see one call in the family networks with countless Apple devices.

**Comment by celenityy** [comment]
> I don't see one call in the family networks with countless Apple devices.

Really? I see this called frequently.

Just from my iPhone earlier:

![image](https://github.com/user-attachments/assets/d8eb2499-bf8e-4e98-aa8d-568a533b9c26)

I've noticed other Apple devices call it as well.

**Comment by celenityy** [comment]
Ref. [1](https://www.scss.tcd.ie/doug.leith/apple_google.pdf) & [2](https://www.scss.tcd.ie/Doug.Leith/pubs/apple_google_additional_material.pdf):

> When the Settings app is opened and the various options
viewed (but not changed), this action generates multiple net-
work connections:
> 1) A connection is made to idiagnostics.apple.com that
sends the handset hardware serial number

**Comment by hagezi** [comment]
Crazy, I don't see a single call in 30 days.

**Comment by hagezi** [comment]
I will only block the domains in Ultimate.

**Comment by celenityy** [comment]
> Crazy, I don't see a single call in 30 days. I can't trigger this via the Settings app either. However, ‘Share diagnostic data’ is also deactivated for all devices.

Yeah I'm surprised, not sure what's going on here. I also have sharing diagnostic data disabled.
