### ISSUE TITLE
more domains

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4210]
### Which domain(s) should be blocked?

sonar6-atl3-2.xx.fbcdn.net
sonar-atl3-2.xx.fbcdn.net
mmi360.net
quantcast. com
adsymptotic.com
kickoffo.site
amp.akamaized.net

### Why should these domain(s) be blocked?

trackers/ad domains

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`quantcast.com` - CMP, see https://github.com/hagezi/dns-blocklists/wiki/FAQ#cmps

`adsymptotic.com` - dead domain (SERVFAIL):
```
; <<>> DiG 9.16.50-Debian <<>> adsymptotic.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 11930
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1


;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;adsymptotic.com.               IN      A
```

`amp.akamaized.net` - Prevents video players from loading on some sites

What is tracked, please provide more details:
```
sonar6-atl3-2.xx.fbcdn.net
sonar-atl3-2.xx.fbcdn.net
```

**Comment by jordansworld** [comment]
thankyou. does fhat mean that sonar6.xy.fbcdn.net is used for content delivery as well or is that tracking?

**Comment by hagezi** [comment]
You claimed that it is tracking and I wanted to know why and what is being tracked.

**Comment by jordansworld** [comment]
i thought it was tracking because sonar6.xy.fbcdn.net is iin the list.

**Comment by jordansworld** [comment]
hey @hagezi would this be considered part of netseer domains or no?

fc524cd5680-zrvjfqgb1735971915-sonar.snr.fbcdn.net

**Comment by hagezi** [comment]
@jordansworld I haven't found any details on this, I don't see such calls in DNS logs, `*-sonar.snr.fbcdn.net` is not on top 1/10M lists either. Maybe something “new” ...

**Comment by jordansworld** [comment]
it might be new. i only see it requested once in my dns logs but then again i just reset my stats a week ago

**Comment by jordansworld** [comment]
it appeared again in my dns logs last night. i blocked it and have no problems. Should we block or no?

**Comment by hagezi** [comment]
No, what should I block here? The first part of the domain seems to be generic `fc524cd5680-zrvjfqgb1735971915`.
It is also completely unclear what you are blocking.

These domains cannot be found on my merged top list either; it was compiled from top list versions of the last few years and comprises 45 million domains.
