### ISSUE TITLE
TickTick syncing functionality

### ISSUE THREAD

**Issue by lwittwer** [hagezi/dns-blocklists#4218]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL, Multi PRO++, Multi PRO++ mini

### Which domain(s) should be unblocked?

wssp.ticktick.com
wss.ticktick.com
ms.ticktick.com

### Why should the domain(s) be unblocked?

TickTick has a paid feature to sync focus timer status. It does not work correctly without these domains unblocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@lwittwer The domains were already removed in the last release. They are no longer on the lists.
