### ISSUE TITLE
`cbsivideo.com`

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#422]
#### What adblocker/DNS cloud service are you using?

Control D, uBO

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
```
doppler-config.cbsivideo.com
at.cbsi.com (possibly)
```

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Check and see if blocking this breaks video at:
```
https://www.cbsnews.com/live/
https://popculture.com/celebrity/news/austin-butler-tears-up-remembering-lisa-marie-presley/
```

**Comment by hagezi** [comment]
https://popculture.com/celebrity/news/austin-butler-tears-up-remembering-lisa-marie-presley/

For Ultimate the following domains had to be unblocked
```
doppler-config.cbsivideo.com
tags.tiqcdn.com (whitelisted in Pro++)
```
https://www.cbsnews.com/live/

@yokoffing  Can't get it to work with DNS without uBlock, not even with OISD (small/big) only (ping @sjhgvr). After pressing the play button the video window stays black. There is a lot of blocking and I'm trying to figure out what needs to be unblocked, so far without success.

![grafik](https://user-images.githubusercontent.com/104343908/219695804-4f5fa8e9-cfa4-41b3-86ff-c28c988904eb.png)

**Comment by hagezi** [comment]
Thanks Stephan, this is then definitely something for the personal whitelist if you also do not use a content blocker.

**Comment by yokoffing** [comment]
There always seems to be an issue with CBS News. I had it working perfectly for awhile. Now I'm not sure what's going on.

**Comment by hagezi** [comment]
That's almost like the German rtl.de. They have all the trackers and ad networks in use and something is constantly not working and then it does. The plague ...

**Comment by hagezi** [comment]
@yokoffing After you have whitelisted `pubads.g.doubleclick.net`, you have to wait 10 sec after the video start via the play button, then the stream will start. Probably the time in which the stream advertising is normally played.

**Comment by yokoffing** [comment]
@hagezi It did not work on Firefox Nightly, and I haven't tested Firefox stable yet. I was able to get the stream to load fine with Chrome + no adblock extension + `pubads.g.doubleclick.net` allowlisted @ DNS level.

`tags.tiqcdn.com` does break a lot of sites when blocked at the browser level. uBO had a long, long list of site exceptions but removed the block all together a few months back.

**Comment by yokoffing** [comment]
Update: I got uBO working in other browsers. Looks like Firefox's Strict tracking protection is breaking the stream, both in Stable and Nightly.
