### ISSUE TITLE
Expires: 7 days does not equal RPZ SOA EXPIRE seconds

### ISSUE THREAD

**Issue by JonMurphy** [hagezi/dns-blocklists#4221]
For the [amazon tracker rpz list](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/native.amazon.txt) the SOA is:
```
@ SOA localhost. root.localhost. 1730312700 43200 3600 259200 300
```
and Expires equals 259200 seconds or 3 days.

Within the RPZ list itself the comments at the top of the file state:
```
; Expires: 7 days
```

So should the SOA Expire time be set to 604800 seconds for 7 days?

PS - I checked a few of the other tracker RPZ lists and they are the same.

**Comment by hagezi** [comment]
The RPZ lists are every 3 days which I think is OK - I don't have different headers for the lists. The Expires from the comment is for AdBlock, I'll adjust that when I get a chance.

**Comment by JonMurphy** [comment]
This came up because we recently added code to check the SOA line and flag an RPZ file when expires.  

All of the items in the Tracker list seem to be updated every 7 days and the new code threw a flag. 

No rush!  Thank you!!

**Comment by hagezi** [comment]
There are no fixed update times for the tracker lists; if no new trackers are added, the lists do not change for months. That's why I simply set 7 days for AdBlock back then. I didn't even notice the difference in RPZ.

**Comment by JonMurphy** [comment]
>  the lists do not change for months.

Ahhh.  Got it!  That makes things harder when coding our SOA checker!  Time for me to ponder...

Do any other list have long(er) update times?  The few I reviewed expire in 1 day.

**Comment by hagezi** [comment]
Expires indicates when it makes sense to update the list. uBlock uses this for the update cycle, for example. The normal lists, Light to Ultimate, including TIF, actually change daily. There are no fixed times for the other lists. They only change when new domains are added or false positives and dead domains are removed.

**Comment by hagezi** [comment]
I have just seen locally all lists have one day. As there have been no changes yet, the Expire data in the repo has not yet been updated. I will update this for the RPZ lists.

**Comment by JonMurphy** [comment]
> the lists do not change for months

I suggest making the Trackers (only) SOA REFRESH to 1 month (or two weeks at minimum) and maybe the EXPIRE to two months.

**Comment by JonMurphy** [comment]
I think there was an error in the coding for a fix.  The Tracker category SOA EXPIRE changed from 3 days to 1 day.  It should have been longer not shorter.  And the REFRESH should be longer also.  Especially since:

> There are no fixed update times for the tracker lists; if no new trackers are added, the lists do not change for months.

**Comment by hagezi** [comment]
All lists now have one day. https://github.com/hagezi/dns-blocklists/issues/4221#issuecomment-2458703418

**Comment by JonMurphy** [comment]
I saw that.  That is why I sent the post above.
