### ISSUE TITLE
IPv64.net IPv64.de

### ISSUE THREAD

**Issue by ipv64net** [hagezi/dns-blocklists#4228]
### Which AdBlocker/DNS cloud service do you use?

AdGuard, Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Dynamic DNS

### Which domain(s) should be unblocked?

IPv64.net
IPv64.de

### Why should the domain(s) be unblocked?

The IPv64.net DYNDNS service is clean and is regularly cleaned. 
Please remove it from the page.

I am the owner of IPv64.net myself

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The list bocks dyn DNS services, whether ‘clean’ or not ...

"A blocklist for blocking dynamic DNS services ..."

**Comment by bondskin** [comment]
https://ipv64.de leads to a private page, does not seem to be related to https://ipv64.net
