### ISSUE TITLE
Block these domains

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4231]
### Which domain(s) should be blocked?

hw-sh-pcdn-35.biliapi.net
hw-sh-pcdn-98.biliapi.net
tp2p.kg.qq.com
twns.p2ptun.qq.com
musicps.p2p.qq.com

### Why should these domain(s) be blocked?

These are advertising domains

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`hw-sh-pcdn-35.biliapi.net` - already blocked
`hw-sh-pcdn-98.biliapi.net` - dead (NXDOMAIN)
`musicps.p2p.qq.com` - already blocked
