### ISSUE TITLE
What HaGeZi TIF version does ControlD and AdGuard use?

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4235]
I have set up NextDNS for many devices and users, and I think it’s an amazing service. However, I’m concerned about the slow (or non-existent) pace of development, especially regarding security detection. I’d really like to use your Full TIF list, as I find it to be of high quality, and I consider your active contributions to be incredibly valuable.

The NextDNS TIF and AI TIF lists are also good, but the limited development for NextDNS raises concerns about how effective these TIFs (particularly the AI TIF) are in addressing new attack techniques. As a result, I’m actively considering switching from NextDNS to another service, such as ControlD or AdGuard DNS.

I have two questions:

1. Do ControlD and/or AdGuard DNS use the Full HaGeZi TIF version, or do they use something more similar to the Medium TIF or Mini TIF?

2. Which DNS service would you recommend for the best security? A service with an actively developed AI TIF would be especially valuable to me.

**Comment by hagezi** [comment]
1. Yes
2. Features are one thing, performance is another. You need to see which service delivers reasonable performance in your region.

**Comment by KnightmareVIIVIIXC** [comment]
I've used control d and adguard; control d has a lot more features in regards to services that you can block, but it follows a strict hosts rules blocking of one rule per line. Adguard has less features and services, but it is way more flexible with rules that you can add, i.e., regex and wildcard support. Control d has there own lists, which looks impressive; however, the lists 
just combine multiple sources into one.

**Comment by hagezi** [comment]
Yes, ControlD has most of the features, with AdGuardDNS you have maximum flexibility thanks to the option of using AdBlock rules. But, as I said, also look at the performance. There can be big differences depending on the region.

**Comment by ExtRIELICi** [comment]
Is there any tool to compare latency of different DNS services based on my location?

**Comment by hagezi** [comment]
Test each service in the free version for a few days and see how it performs over the course of the day. A snapshot is not representative.
