### ISSUE TITLE
Unblock wappass.baidu.com

### ISSUE THREAD

**Issue by ramdomPTM** [hagezi/dns-blocklists#4240]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

dnsmasq

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++, Multi PRO++ mini, Multi ULTIMATE, Multi ULTIMATE mini

### Which domain(s) should be unblocked?

wappass.baidu.com

### Why should the domain(s) be unblocked?

wappass.baidu.com serves the Baidu account service. With the domain blocked, Baidu services like Baidu Netdisk (pan.baidu.com) cannot be signed in. Unblock the domain locally solves the problem.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
ref: https://github.com/hagezi/dns-blocklists/issues/4117#issue-2617868524 @Shura23

**Comment by ramdomPTM** [comment]
Thank you for your quick fix!
