### ISSUE TITLE
client-allegro.earchiwum.pl

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#4243]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### Other

client-allegro.earchiwum.pl

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

client-allegro.earchiwum.pl

### Why should the domain(s) be unblocked?

`client-allegro.earchiwum.pl` is used by Allegro for delivery terms in PDF.
Sample URL `https://client-allegro.earchiwum.pl/doc/da3a6eedd1ce56202fe12109a9387d113b44929c4c696cb7da05ed19841d0800`

![20241107-1730971974](https://github.com/user-attachments/assets/818addf7-92e5-44c5-882b-ba44464079de)

![20241107-1730972022](https://github.com/user-attachments/assets/c733e220-dc24-470d-92ca-bd83264bbc55)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
via phishing.army @drego85

**Comment by drego85** [comment]
Hi @FadeMind,
the domain was indicated as malicious by report [8251782](https://www.phishtank.com/phish_detail.php?phish_id=8251782) on PhishTank, confirmed by 4 users.

`earchiwum.pl` is probably a domain of eArchiwum, an online service offering digital archiving solutions for electronic documents.

Unfortunately, I cannot find an official website of this company. 🤷‍♂️

Can you confirm that it is a legitimate website (more information is also welcome)? So I can warn PhishTank of the false positive.

**Comment by drego85** [comment]
Thanks you, I opened this ticket on PhishTank:
```
earchiwum.pl is a domain of eArchiwum, an online service offering digital archiving solutions for electronic documents.
It is used in Poland to send new contractual documents (PDF), e.g. from the e-commerce company Allegro.
```
Surely it will soon be reported as non-malicious.

**Comment by hagezi** [comment]
Thanks @drego85 ;)

**Comment by drego85** [comment]
Don't worry, thanks anyway for your valuable help. 
PhishTank closed the ticket and now no longer reports the URL as malicious. In the next few hours, as soon as the lists update, everything will be back to normal.
