### ISSUE TITLE
Do I need to use OISD with hagezi when using nextdns?

### ISSUE THREAD

**Issue by 0mMdy8R6uS8xpP** [hagezi/dns-blocklists#4248]
yokoffing's Nextdns config guide suggest to use OISD with hagezi because it contains some TIF sources missing from NextDNS security features. is this still valid? are there TIF sources not covered by using both nextdns security features with hagezi list?

**Comment by hagezi** [comment]
As an addition to the previous post, the sources used in NextDNS for the security feature are not publicly available. I only know the old sources before they were internalised. The TIF uses these sources and many more. Additionally using the OISD does not cover everything, but it probably helps. What will definitely be missing are some fake, scam, phishing and malicious popup ads, ...
