### ISSUE TITLE
Why www.gaming.gen.tr

### ISSUE THREAD

**Issue by muhasturk** [hagezi/dns-blocklists#4249]
### Which AdBlocker/DNS cloud service do you use?

AdGuard, AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO, Threat Intelligence Feeds, Badware Hoster, Most Abused TLDs

### Which domain(s) should be unblocked?

www.gaming.gen.tr

### Why should the domain(s) be unblocked?

Turkish retail store which is well known

![Screenshot 2024-11-07 220328](https://github.com/user-attachments/assets/c3a168e8-7376-4ad2-a672-daf8c7423c8b)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked by CNAME `xvn3me7s4o.wpdns.site`
 
 ```
dig www.gaming.gen.tr

; <<>> DiG 9.16.50-Debian <<>> www.gaming.gen.tr
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63156
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.gaming.gen.tr.             IN      A

;; ANSWER SECTION:
www.gaming.gen.tr.      300     IN      CNAME   xvn3me7s4o.wpdns.site.
xvn3me7s4o.wpdns.site.  300     IN      A       104.17.145.110
xvn3me7s4o.wpdns.site.  300     IN      A       104.17.144.110
```
