### ISSUE TITLE
Has the adlist been properly added to my pihole?

### ISSUE THREAD

**Issue by leryeo** [hagezi/dns-blocklists#4252]
![Screenshot 2024-11-08 114054](https://github.com/user-attachments/assets/45b2dbb6-7ea5-48b5-ab23-8868db3faa9e)

Stating that all domains are invalid? Never got this problem before when using an adlist.

**Comment by hagezi** [comment]
You seem to have an old version of Pi-hole that does not yet support the AdBlock format. Update your Pi-hole to the latest version.

**Comment by Frmd-git** [comment]
Is it the ABP format the correct one for pi-hole?
It looks in [here](https://discourse.pi-hole.net/t/abp-lists-and-wildcards/74363/5) and [here](https://github.com/pi-hole/FTL/pull/1532) as if that format it's not being parsed properly and maybe the host only format would be better.
Is that correct?
