### ISSUE TITLE
allow

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4255]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

zynga2-a.akamaihd.net
edge-locations5-noneu.truecaller.com
dqa.samsung.com
tracker.istole.it

### Why should the domain(s) be unblocked?

first two i dont think are trackers.
dqa seems to be used to detect bad wifi signal on samsung. the istole tracker is used for torrents

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
> first two i dont think are trackers

If you tell me where they lead to restrictions, I'll be happy to take a look.

`tracker.istole.it` - https://github.com/hagezi/dns-blocklists/issues/2624

The domain `dqa.samsung.com` belongs to Samsung and stands for Device Quality Assurance (DQA). It is used to collect diagnostic data from Samsung devices such as smartphones or tablets. The main purpose of this data transfer is to improve the performance and stability of the devices by detecting and analysing errors.
