### ISSUE TITLE
N26 Support Chat

### ISSUE THREAD

**Issue by backstab5983** [hagezi/dns-blocklists#4265]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

https://lpcdn.lpsnmedia.net/
https://lptag.liveperson.net/
https://lo.v.liveperson.net/
https://accdn.lpsnmedia.net/

### Why should the domain(s) be unblocked?

It is not possible to use the support chat from N26, a widely popular European bank.

I'm not an expert in troubleshooting DNS issues, but I switched DNS to Google's, opened dev tools in Chrome and checked the DNS requests when opening a chat on the website, then looked for similar domains in the pro-plus file and these seem to match. 

I can confirm it doesn't work from iOS either (obviously) when using the same blocklist.

Hope it helps!

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@backstab5983 The domains listed are no longer blocked, can you test the light or normal version?

**Comment by hagezi** [comment]
@backstab5983 You seem to need an account to test it, I don't have one so can't say which domain(s) are causing the problem.

**Comment by hagezi** [comment]
Thanks @backstab5983, will unblock liveperson completely, except for the Ultimate.
