### ISSUE TITLE
TIF false positive

### ISSUE THREAD

**Issue by cliff-cc** [hagezi/dns-blocklists#4270]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

haletone.com

### Why should the domain(s) be unblocked?

Genuine website of a Harmonica group

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Many Flags:

https://www.virustotal.com/gui/url/7b958ce57ad28431add9ab638997d1223549834c585116de14dde2ee3b671037
