### ISSUE TITLE
dichtienghoa.com: badware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4273]
### Which domain(s) should be blocked?

```
dichtienghoa.com/translate/m.imdb.com?u=https://0.gp/greece2
0.gp/greece2
gov.gr93.sbs/gr
```

### Why should these domain(s) be blocked?

This link is being sent to Greek users via email, pretending to be from gov.gr. This domain/link might be affiliated with this [issue](https://github.com/hagezi/dns-blocklists/issues/4191)

<img width="976" alt="image" src="https://github.com/user-attachments/assets/26d2443f-f6e1-4427-a0a0-0305084b1bab">

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
0.gp is a URL shortener and dichtienghoa.com is a translation service. Like Google Translate, it lets you translate websites. See i.e. `https://dichtienghoa.com/translate/example.com?u=https://iam-py-test.github.io` displays the contents of iam-py-test.github.io.
I have blocklisted the .sbs domain.
Thanks
