### ISSUE TITLE
Whether it can provide DNS in China

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4287]
You provide some encrypted DNS with ad filtering in your project, but these DNS have high latency in China, some DNS cannot be used, some DNS can be used in China, but the latency is high, and even some websites cannot be resolved. Can you use China's DNS, such as Alibaba DNS or Huawei DNS?

**Comment by hagezi** [comment]
I provide DNS blocklists, not DNS services. You must address your enquiry to the individual services. This is the wrong place.
