### ISSUE TITLE
Possible FPs in TOP 1M

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#43]
Based on 

https://github.com/hagezi/dns-blocklists/commit/1a832461b5fd5d2ed7158ea26186dba39887163e#diff-f6a2b7e14a91f43dd335d0cd5a2d0011a98d9bf1e6181ae3624b231b77e36160

https://dsi.ut-capitole.fr/blacklists/index_en.php

https://tranco-list.eu/list/82GXV/1000000

See text files in the zip

[common.zip](https://github.com/hagezi/dns-blocklists/files/9646289/common.zip)

**Comment by hagezi** [comment]
Thanks for your work @sr093906 , I'll look at the potential false positive domains and remove them if necessary.

**Comment by hagezi** [comment]
false positive domains were removed
