### ISSUE TITLE
DNS - blocklists not blocked Cosmetic Filter and Ads Script Loading

### ISSUE THREAD

**Issue by digi340** [hagezi/dns-blocklists#4301]
Hy to all. 

DNS - blocklists is very best, but not blocked  Static ad, Dynamic ad, ads.js , pagead.js - Cosmetic Filter and Ads Script Loading.
I use Control C DNS - Hagezi's DNS - Ultimate.

Tested on https://d3ward.github.io/toolz/adblock.

script_ads : false
script_pagead : false

-------------------------
Amazon => n° tests => 4
Google Ads => n° tests => 4
Doubleclick.net => n° tests => 5
Adcolony => n° tests => 4
Media.net => n° tests => 3
Ads => Total n° tests => 20
-------------------------
Google Analytics => n° tests => 4
Hotjar => n° tests => 7
MouseFlow => n° tests => 7
FreshWorks => n° tests => 3
Luckyorange => n° tests => 8
Stats WP Plugin => n° tests => 1
Analytics => Total n° tests => 30
-------------------------
Bugsnag => n° tests => 4
Sentry => n° tests => 2
Error Trackers => Total n° tests => 6
-------------------------
Facebook => n° tests => 2
Twitter => n° tests => 2
LinkedIn => n° tests => 2
Pinterest => n° tests => 4
Reddit => n° tests => 2
YouTube => n° tests => 1
TikTok => n° tests => 7
Social Trackers => Total n° tests => 20
-------------------------
Yahoo => n° tests => 10
Yandex => n° tests => 6
Unity => n° tests => 4
Mix => Total n° tests => 20
-------------------------
Realme => n° tests => 4
Xiaomi => n° tests => 7
Oppo => n° tests => 4
Huawei => n° tests => 6
OnePlus => n° tests => 2
Samsung => n° tests => 5
Apple => n° tests => 7
OEMs => Total n° tests => 35
-------------------------
cosmetic_static_ad : false

-------------------------
cosmetic_dynamic_ad : false

-------------------------

adtago.s3.amazonaws.com - blocked
analyticsengine.s3.amazonaws.com - blocked
analytics.s3.amazonaws.com - blocked
advice-ads.s3.amazonaws.com - blocked
pagead2.googlesyndication.com - blocked
adservice.google.com - blocked
static.media.net - blocked
pagead2.googleadservices.com - blocked
afs.googlesyndication.com - blocked
stats.g.doubleclick.net - blocked
media.net - blocked
ad.doubleclick.net - blocked
adservetx.media.net - blocked
static.doubleclick.net - blocked
m.doubleclick.net - blocked
mediavisor.doubleclick.net - blocked
adm.hotjar.com - blocked
identify.hotjar.com - blocked
ads30.adcolony.com - blocked
insights.hotjar.com - blocked
adc3-launch.adcolony.com - blocked
script.hotjar.com - blocked
events3alt.adcolony.com - blocked
surveys.hotjar.com - blocked
careers.hotjar.com - blocked
wd.adcolony.com - blocked
events.hotjar.io - blocked
o2.mouseflow.com - blocked
gtm.mouseflow.com - blocked
api.mouseflow.com - blocked
analytics.google.com - blocked
click.googleanalytics.com - blocked
freshmarketer.com - blocked
claritybt.freshmarketer.com - blocked
fwtracks.freshmarketer.com - blocked
api.luckyorange.com - blocked
google-analytics.com - blocked
cdn.luckyorange.com - blocked
w1.luckyorange.com - blocked
ssl.google-analytics.com - blocked
upload.luckyorange.net - blocked
cs.luckyorange.net - blocked
settings.luckyorange.net - blocked
browser.sentry-cdn.com - blocked
static.ads-twitter.com - blocked
mouseflow.com - blocked
ads-api.twitter.com - blocked
ads.linkedin.com - blocked
cdn.mouseflow.com - blocked
analytics.pointdrive.linkedin.com - blocked
ads.pinterest.com - blocked
log.pinterest.com - blocked
tools.mouseflow.com - blocked
cdn-test.mouseflow.com - blocked
analytics.pinterest.com - blocked
trk.pinterest.com - blocked
events.reddit.com - blocked
events.redditmedia.com - blocked
luckyorange.com - blocked
realtime.luckyorange.com - blocked
analytics.tiktok.com - blocked
analytics-sg.tiktok.com - blocked
ads-api.tiktok.com - blocked
ads-sg.tiktok.com - blocked
ads.tiktok.com - blocked
business-api.tiktok.com - blocked
log.byteoversea.com - blocked
notify.bugsnag.com - blocked
ads.yahoo.com - blocked
stats.wp.com - blocked
analytics.yahoo.com - blocked
sessions.bugsnag.com - blocked
geo.yahoo.com - blocked
api.bugsnag.com - blocked
udc.yahoo.com - blocked
udcm.yahoo.com - blocked
app.bugsnag.com - blocked
analytics.query.yahoo.com - blocked
app.getsentry.com - blocked
partnerads.ysm.yahoo.com - blocked
gemini.yahoo.com - blocked
pixel.facebook.com - blocked
log.fc.yahoo.com - blocked
an.facebook.com - blocked
adtech.yahooinc.com - blocked
extmaps-api.yandex.net - blocked
appmetrica.yandex.ru - blocked
adfstat.yandex.ru - blocked
metrika.yandex.ru - blocked
offerwall.yandex.net - blocked
adfox.yandex.ru - blocked
ads.youtube.com - blocked
iot-eu-logser.realme.com - blocked
iot-logser.realme.com - blocked
bdapi-ads.realmemobile.com - blocked
bdapi-in-ads.realmemobile.com - blocked
api.ad.xiaomi.com - blocked
data.mistat.xiaomi.com - blocked
data.mistat.india.xiaomi.com - blocked
data.mistat.rus.xiaomi.com - blocked
sdkconfig.ad.xiaomi.com - blocked
tracking.rus.miui.com - blocked
sdkconfig.ad.intl.xiaomi.com - blocked
adsfs.oppomobile.com - blocked
adx.ads.oppomobile.com - blocked
data.ads.oppomobile.com - blocked
ck.ads.oppomobile.com - blocked
metrics.data.hicloud.com - blocked
metrics2.data.hicloud.com - blocked
grs.hicloud.com - blocked
logservice.hicloud.com - blocked
logservice1.hicloud.com - blocked
logbak.hicloud.com - blocked
click.oneplus.cn - blocked
auction.unityads.unity3d.com - blocked
open.oneplus.net - blocked
samsungads.com - blocked
webview.unityads.unity3d.com - blocked
smetrics.samsung.com - blocked
nmetrics.samsung.com - blocked
config.unityads.unity3d.com - blocked
adserver.unityads.unity3d.com - blocked
samsung-com.112.2o7.net - blocked
analytics-api.samsunghealthcn.com - blocked
iadsdk.apple.com - blocked
metrics.icloud.com - blocked
metrics.mzstatic.com - blocked
api-adservices.apple.com - blocked
books-analytics-events.apple.com - blocked
weather-analytics-events.apple.com - blocked
notes-analytics-events.apple.com - blocked
-----
Total : 135
Blocked : 131
Not Blocked : 4

[d3_adb_13_11_2024 11_23_02.json](https://github.com/user-attachments/files/17730224/d3_adb_13_11_2024.11_23_02.json)

**Comment by hagezi** [comment]
DNS blocklists block domains. Browser content blockers such as uBlock with corresponding filter lists are required to block scripts, elements and website content. This cannot be blocked using DNS.

My lists are pure DNS blocklists.

**Comment by digi340** [comment]
> DNS blocklists block domains. Browser content blockers such as uBlock with corresponding filter lists are required to block scripts, elements and website content. This cannot be blocked using DNS.
> 
> My lists are pure DNS blocklists.

Thanks.
