### ISSUE TITLE
Block these domains

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4305]
### Which domain(s) should be blocked?

||log-api.pangolin-sdk-toutiao-b.com^
||xlog.jd.com^
||janapi.jd.com^
||bes-mtj.baidu.com^
||dsp-x.jd.com^
||hmma.baidu.com^

### Why should these domain(s) be blocked?

These domains are either advertisements or trackers.I would like to ask by the way, if I want your upstream rules list to submit a rule, will you sync into your rule? Or do you not synchronize upstream rules?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
All domains are already blocked ...
