### ISSUE TITLE
track.avm.de Not working

### ISSUE THREAD

**Issue by dpeed** [hagezi/dns-blocklists#4306]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Unbound 

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

track.avm.de

### Why should the domain(s) be unblocked?

Bug Tracking System from AVM

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Bug trackers are and will remain blocked from Pro onwards. I will remove this domain for Light and Normal.
