### ISSUE TITLE
app.samsungfood.com

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4309]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

cdn.whisk.com
bunny-image-cdn.whisk.com

### Why should the domain(s) be unblocked?

site broke

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
What exactly is not working? Please provide a link for testing.

**Comment by jordansworld** [comment]
im sorry it wouldnt load at all on data i tried multiple times it now loads. sorry.
