### ISSUE TITLE
PHP-Friends

### ISSUE THREAD

**Issue by DasCanard** [hagezi/dns-blocklists#4315]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster

### Which domain(s) should be unblocked?

php-friends.de

### Why should the domain(s) be unblocked?

It is a legitament hosting provider

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by DasCanard** [comment]
I am a customer at PHP-Friends and also wanted to know how it get on this list.

**Comment by hagezi** [comment]
Take a look at what the list blocks. You should understand what the list blocks when you use it.

The list blocks all free hosters that can also be used to host badware. Not just hosters that definitely host badware.

**Comment by hagezi** [comment]
e.g. `v57018[.]php-friends.de` via Threatfox Abuse CH, see https://www.virustotal.com/gui/url/ac674935053bc13d68f38b1c7dc61afd7cf682c39f03ae123bb1232d40594245

**Comment by DasCanard** [comment]
yeah so this is a php-friends VM with the standard hostname of it

**Comment by DasCanard** [comment]
but how do you know by that, that php-friends is a free hoster?

**Comment by hagezi** [comment]
If there are flags on the main domain, whether free or not, the domain ends up on the hoster list.

**Comment by DasCanard** [comment]
> If there are flags on the main domain, whether free or not, the domain ends up on the hoster list.

yeah but you just sent me a subdomain

**Comment by hagezi** [comment]
I will remove free from the description if that is the problem. What the list blocks is clear, hosters that also host badware.

**Comment by hagezi** [comment]
> yeah but you just sent me a subdomain

The purpose of this list is to block all subdomains, including generic ones, by blocking the main domain. For this reason, the list is only available for adblockers that support wildcard blocking.

**Comment by DasCanard** [comment]
![image](https://github.com/user-attachments/assets/75dc5a26-85d3-4238-8510-eba856d6e106)
ist gesperrt

**Comment by DasCanard** [comment]
🙌🙌🙌
