### ISSUE TITLE
Measurement Lab Speed test

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#432]
#### What adblocker/DNS cloud service are you using?

NextDNS, Block Page = Disabled, CNAME Flattening = Disabled

#### Which blocklists are used?
Pro++
Ultimate

#### Which domain(s) should be unblocked?
`measurement-lab.org`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking this domain doesn't allow `speed.measurementlab.net` to start properly. The test will freeze at "Starting" until unblocked.

**Comment by hagezi** [comment]
Thanks, will be removed.
