### ISSUE TITLE
Does ControlD’s IP-based malware blocking include HaGeZi’s IP TIF list?

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4321]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/bd983975-9475-49cb-8c31-4207a0cfc08f">

**Comment by hagezi** [comment]
I don't know, @Yegors can you say something about that?

**Comment by yegors** [comment]
It does not, but we use many of the same sources.

**Comment by hagezi** [comment]
Thanks @yegors
