### ISSUE TITLE
Crypto scams

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4322]
### Which domain(s) should be blocked?

https://stage3-last.pro/info
https://stage3-last.store/info/
https://stage3-last.club/info/
https://stage3-last.live/info/
https://stage3-last.info/info/

https://stage2024.club/info/

And probably a lot more with different TLDs..

### Why should these domain(s) be blocked?

Obvious crypto scam.

![IMG_8672](https://github.com/user-attachments/assets/f90258b1-63d4-4fa4-9dad-1214cdfd618c)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jarelllama** [comment]
These too:
```
stage3x.online
stage3x.site
stage3x.store
```
