### ISSUE TITLE
Fake Air Up domains

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4327]
### Which domain(s) should be blocked?

```
https://www.airup-bottlegreece.com
https://www.airupgreece.net
https://www.airup-gr.com
```

### Why should these domain(s) be blocked?

These websites appear at the very top of Google Search when you look for "Air Up Greece". The real website is `https://shop.air-up.com/gr/en`

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by ExtRIELICi** [comment]
I found even more domains like this for other countries. Turns out there are a TON of domains for different countries. Any country you can imagine, there is a fake domain(s) for it.
```
https://www.airupbulgaria.com
https://www.airup-romania.com
https://www.airupromania.ro
https://www.airupitaly.it
https://www.airuptürkiye.com
https://www.air-up-turkiye.com
https://www.airupsrbija.com
```
@hagezi

**Comment by jarelllama** [comment]
These too from NRD list: 
```
airup-fi.com
airup-it.shop
```
