### ISSUE TITLE
Whitelist req [sbchill.com]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#433]
#### What adblocker/DNS cloud service are you using?

RethinkDNS App

#### Which blocklists are used?

Pro++

#### Which domain(s) should be unblocked?

https://sbchill.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Video Web Player Platform

**Comment by hagezi** [comment]
Thanks, will be removed.
