### ISSUE TITLE
Adding communical block lists to the project

### ISSUE THREAD

**Issue by Warmax356** [hagezi/dns-blocklists#4331]
Good afternoon all, 

still new to github so please have mercy on me, but i also maintain a community block list on ossmalta.eu/blacklists,  i would like to contribute to this community project aswell but don't know how to start.

the community list webpage is currently a WIP interms of presentation but the text files for the BL lists are setup/format for pihole, ublock origin and adblock they can be found directly at

Malta - https://bl.ossmalta.eu/malta.text
EU (europe) - https://bl.ossmalta.eu/malta.text

With notes in the text file of which are scam sites, fraud, malware etc.. and thier sources such as gov adviseries, community submission, or even from sms spam/phishing they are currently split into Malta and EU, malta being very specific to the nation as thats where the community is based and mostly focused on, and europe wich is a more broader list

but looking at how this project catagoriezes its lists got me wondering if i should follow a similar structure, we (ossmalta) are also willing to collaborate and list the project on the blacklists table we are building and conttribute where ever we may.

Regards,
Warmax356 - obo OSSMalta

**Comment by hagezi** [comment]
Thanks @Warmax356, I'll have a look at the lists after the weekend and get back to you.

**Comment by hagezi** [comment]
Analysis of https://bl.ossmalta.eu/malta.txt:

```
Valid domains:			165
Blocked domains (TIF):	         33
Allowed domains:		  7
Dead domains:			 91
Missing domains:		 34

Blocked:

20winpkr.com
alphafxprime.com
alphaprimefx.com
alphascrypto.com
astronomycrawlingcol.com
azaurgoa.com
bit-codeprime.com
bitcodeprime.site
bov3d-login.web.app
bov.eu
canada777.com
crawledlikely.com
finbondassetltd.com
fun-88.in
gycuniformes.com
hthbet619.com
innovativefxtrade.com
instantglobalstrade.com
investoscope.io
kaiyun.io
l.ead.me
ob9sg.com
onbet111.com
prolifictrades.com
royalinvestmentconsortium.com
sitey.me
stake.mba
tierl-fx.com
traumatizedenied.com
uniglobalinvestltd.com
vkgame11.site
w88br.com
w88kub.com

Allowed:

505games.com
clk.wiki
financerites.com
is.gd
q-r.to
rtbbhub.com
sbobet.com

Dead:

adonisinvestmentlimited.com
alenol.com
allphaglobal-limited.com
alphafxprime.co
alphaglobal-limited.com
alphaprimefx.co
aquilamsv.com
aungundie.com
b0v-ebanking.com
b0v.mt
bet55.com
bison-bb.net
bov3ds.tk
bov-banking.com
bov-ebanking.com
bov-onlinehelp.com
bov.tk
cardinalholdingsltd.com
casiwinner.com
ccfundscapital.ltd
cheapsales2024store.ru
cheflee.com.mt
crypto-novufx.com
dcoinfx.com
delivery-mt-track.com
derivtradinglive.net
doxxonfinance.com
eefteezaltou.com
expertadvancetrade.com
express-pack.net
ey6dmx.com
federalinter-groupe.com
finbondgroupltd.com
forexcryptocurrencyinvestment.com
g0v.mt
gkfxtradingaccount.com
global-postgroup.com
globaltradingearners.com
g-r.to
gvzhlegaluk.com
heptagoninvestments.net
hillwoodlimited.com
horizonfinance.live
hwlimited.com
interactivefinancialinvestment.com
interlandassetmgt.com
interlandassets.com
kintarocapitalinvestment.com
lesamt.com
lesa.work
maltafilm14.com
maltaposta.help
maltaposta.to
maltaposta.work
maltapost.cfd
maltaposte.work
maltapostgroup.icu
maltapost.help
malta-post-office.life
maltapost.pe
maltapost.to
maltapost.work
maltapost.xyz
metamail29.shop
moneybasemt.com
moneybase.pii.at
nsbroker.cc
nsbroker.cypto
nsbroker.eu
nsbroker.info
nsbroker.live
nsbroker.net
nsbroker.online
nsbroker.pro
nsbroker.trade
nsfx.online
paywayglobal.com
pgblimlted.com
primeoptstrade.com
rizzoinvestment.com
rizzoinvestmentltd.com
s9cryptotrade.com
secureinvestnest.com
skyfinint.com
spurtrade.co
trustworthyanchor.com
ups-tracks.info
worldsmartinvestments.com
xougreek.com
zbxchange.com
zbxchange.link

Missing:

ardschatota.com
catcasinosx.com
climaxxasset.com
alert.com.mt
dd.com.mt
dd.mt
fbm8sm.com
heptagoninvestments.com
hesoorda.com
ku2d3a7pa8mdi.com
les-mt.com
lesgov.com
lesmt.com
loveiinair.net
maltapoostt.xyz
n1-bet.ng
nuzaqook.com
ommer-automaten.nl
mhfa.org.mt
orqjcewtud.com
paysenger.com
rounddescribe.com
super8r.com
tegleebs.com
track.trustworthyanchor.com
verniercapitaladvisors.com
very-good.online
visque.capital
vortexoptions.com
bov3ds.web.app
bov3dsapp.web.app
woodwardwirerope.com
wuvq4.com
zougreek.com
```

@Warmax356 The list will be added to TIF, TIF medium and TIF mini in the next release.

**Comment by hagezi** [comment]
Analysis of https://bl.ossmalta.eu/eu.txt:

@Warmax356 The list is not useful to me in its current form, it is a mix of TIF and non TIF domains, what is the source of these domains?
It also contains a lot of false positives (popular domains like `theguardian.co.uk`
) and many dead domains. It is not worthwhile for me to investigate these in more detail.
