### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Shura23** [hagezi/dns-blocklists#4335]
If I submit a rule to your upstream rule list, will your list sync with the upstream rule list?You've used many other people's rule lists, and if those rule lists change, will they be synced into your rules?

**Comment by hagezi** [comment]
Yes, the sources are queried with every release and the domains end up in a basic database. The domains for the individual list versions are compiled individually from this basic database and my extensions. You can also see https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources

My lists are therefore not 1:1 copies of other sources.

I analyse new sources that I receive and then decide whether or not to include them in the basic database. With my lists, I prioritise effectiveness with the smallest possible list size. This means, among other things, that only popular domains end up on the lists. Less is often more. This means that when a new source is added, only popular domains that have been on various domain top lists in the last 12+ months are included. Known false positives and dead domains are removed.
