### ISSUE TITLE
Is there any list to block Newly Active Domains and/or similar?

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4339]
I recently discovered this feature, along with many other similar ones, on [docs.dns0.eu](https://docs.dns0.eu/data-feeds/introduction):

- Newly Observed Domains (NOD)
- Newly Observed Hostnames (NOH)
- Newly Active Hostnames (NAH)
- Newly Issued Certificates (NIC)

However, from what I understand, these features are not available on services like NextDNS, ControlD, or AdGuard.

These features seem very interesting, but with dns0, most of them appear to be either behind a paywall or lack customization and control. This is because they only provide a DNS address, unlike NextDNS, which offers a control center where you can adjust settings to your preferences.

For example, Newly Active Domains are domains that were inactive for a while but have suddenly become active. This behavior is often a strong indicator of malicious activity.

Are there any HaGeZi (or other) filter lists that cover these cases, also shown in the screenshot I attached below? If not, are there any plans to create such lists?

<img width="250" alt="image" src="https://github.com/user-attachments/assets/120d74db-b748-489e-8223-7e6275fda8e8">

**Comment by hagezi** [comment]
@xRuffKez

**Comment by Dynamic5912** [comment]
It's listed right here...

![image](https://github.com/user-attachments/assets/dd631cd2-3e92-45b7-a7f1-df978bc85672)

**Comment by Dynamic5912** [comment]
@xRuffKez - be interested to know what the differences are between the 14/30 days lists and the 14/30 day _phishing_ lists are?

Maybe @hagezi could implement the _phishing_ lists with TIF or something?

**Comment by xRuffKez** [comment]
@Dynamic5912 The phishing nrd list are domains with high entrophie, domains which are likely automatically registered by bad actors, typo squatting and homographic looking domains. Also domains which are using big tech vompanies but are not associated to them. It is simply the nrd list with domains, they are likely fishy.

14days means domains registered, claimed or changed owner in the past 14 days from now on. So it is with the 30 days list.

Sicerely,
xRuffKez

**Comment by xRuffKez** [comment]
@ExtRIELICi thanks for your suggestion! That sounds interesting in manner of security indeed. I will have a look and integrate the feature when applicable.

@Dynamic5912 The phishing nrd list are domains with high entrophie, domains which are likely automatically registered by bad actors, typo squatting and homographic looking domains. Also domains which are using big tech vompanies but are not associated to them. It is simply the nrd list with domains, they are likely fishy.

14days means domains registered, claimed or changed owner in the past 14 days from now on. So it is with the 30 days list.

Sicerely,
xRuffKez

**Comment by hagezi** [comment]
> Maybe @hagezi could implement the _phishing_ lists with TIF or something?

Are already implemented from day one.

**Comment by ExtRIELICi** [comment]
> It's listed right here...
> 
> ![image](https://github.com/user-attachments/assets/dd631cd2-3e92-45b7-a7f1-df978bc85672)

I am aware that NRDs are already included, however, this post is not about NRDs but about similar things that differ from them.

**Comment by jarelllama** [comment]
For the newly active domains list, would it be enough to keep only resolving domains from the NRD list @ExtRIELICi ? This could easily be done by running the NRD list through dead-domain-linter.

**Comment by jarelllama** [comment]
It appears I have the definition wrong:
> Domains that were once live on the Internet and then abandoned are often purchased and reused by criminals in order to avoid immediate detection. Real-time information about domains that are reactivated on the Internet after a period of inactivity can prepare security teams to apply rules to firewalls and mail servers to block inbound and outbound connections to these domains until more information is available about them.

From https://www.domaintools.com/products/threat-intelligence-feeds/domain-visibility/farsight-nad/

My scam blocklist is capable of detecting these domains by checking for resolving-once-dead domains and the same for unparked domains. My "cache" is only 50,000 domains big though, old domains fetched from my sources are disregarded after that. Only domains in the cache are checked for resurrected/unparked domains.

**Comment by jarelllama** [comment]
You can view the number of resurrected/unparked domains in my readme:
![image](https://github.com/user-attachments/assets/e6835d00-5a88-486f-b7ed-9daafdf8733d)
