### ISSUE TITLE
PSA: Yahoo/AOL create fork of Chrome with crapware/adware based on nostalgia Netscape name. 

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#4349]
AOL/Yahoo preyed on Netscape nostalgia by making a Chrome fork and a second variant called AOL Shield Pro. The browsers install in the same place and overwrite each other. 
Enderman review:
https://www.youtube.com/watch?v=pwre8oHZdL4

https://www.aol.com/products/browsers/shield-pro

**Comment by hagezi** [comment]
Yes, that's 'garbage', but what am I supposed to block here. I can't block Yahoo and AOL completely.
