### ISSUE TITLE
qrco.de

### ISSUE THREAD

**Issue by Morku** [hagezi/dns-blocklists#4350]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

qrco.de

### Why should the domain(s) be unblocked?

It's a redirect service from https://support.qr-code-generator.com/hc/en-us/articles/7664232533133-Why-did-a-QR-Code-or-link-bring-me-to-the-Help-Center

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by Morku** [comment]
Thats sad when abused. Today I scaned a legit QR Code and run into that issue. So I had to disable DNS blocking.

The page who try to scam should be blocked, not a redirector service.

**Comment by Morku** [comment]
Here is it:

![a1ebf5065350df5126c5a920ce49744cf338eea9f01238bb05f5875a6e909ef6](https://github.com/user-attachments/assets/bfdc72e6-811c-41bb-ab9c-023718164274)

-> https://qrco.de/bdZedl

Does it mean, you block all link shortener in Multi Pro?

**Comment by hagezi** [comment]
No, I don't usually block shorteners, this was an exception because there were many flags on Virustotal. Sometimes it is “safer” to block such domains. However, most of the flags have disappeared again. I will unblock the domains.
