### ISSUE TITLE
qrcc.me

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#4353]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

qrcc.me

### Why should the domain(s) be unblocked?

Blocks a legitimate QR service an event I went to used.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
via phishing.army @drego85

**Comment by drego85** [comment]
Thank you, I whitelisted this domain.
