### ISSUE TITLE
karan PC fakes

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#4362]
### Which domain(s) should be blocked?

karan-pc.com
karanpcofficial.blogspot.com

### Why should these domain(s) be blocked?

fake sites based on warez karanPC. 
Why legit site `karanpc.com` is on TIF blocked? :> 

![20241118-1731939109](https://github.com/user-attachments/assets/e970c82d-64c3-4d96-baaf-b4d9516b8756)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
legal karanpc.com blocked via @iam-py-test malware list

**Comment by iam-py-test** [comment]
[karanpc.com](https://iam-py-test.github.io/lookup.html?q=karanpc.com) has been removed; it seems the false positive originated from https://github.com/hagezi/dns-blocklists/issues/2955 and was never verified to be malicious.
I have added the two malicious domains. That said, would you mind sharing a link to that social media post (for my own records purposes).
Thanks FadeMind and hagezi

**Comment by iam-py-test** [comment]
Thanks
