### ISSUE TITLE
report-uri.com

### ISSUE THREAD

**Issue by BourbonCrow** [hagezi/dns-blocklists#4367]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

report-uri.com

### Why should the domain(s) be unblocked?

Email / Web security site

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/3667
