### ISSUE TITLE
Ad banner in a website

### ISSUE THREAD

**Issue by Carl298998** [hagezi/dns-blocklists#4368]
Hello Hagezi

I am using Hagezi's DNS Normal list (through ControlD DNS).

Could you please verify the homepage of the brazilian technology website https://gizmodo.uol.com.br/  ?

On the upper right side, there is an icon with the letter "x", apparently is a part of a 300x250 ad banner. The ad banner is there, only invisible in our eyes. But it occupies a space as it does not allow you to click on it behind it, while the icon of the letter X was not clicked for this banner being closed. You can see inspecting Chrome browser elements.

Also, is it possible to block this cookie warning in this website only using Hagezi's DNS Normal DNS? Or will I need to add an adblock browser extension or something similar to "I Don't Care About Cookies" extension? I ask, as it is a limited possibility for many Chrome based browsers for Android Smartphone. It would be very interesting if your DNS list could already block these cookies warnings.

Thank you very much

![Captura de tela_2024-11-18_22-13-48 (1)](https://github.com/user-attachments/assets/244cf724-1a83-4a0e-889d-2d88c4bb2d5e)

![Captura de tela_18-11-2024_222851_ (1)](https://github.com/user-attachments/assets/5c071ad9-d5ee-4bf2-9c6b-33fd5a205a0a)

![Captura de tela_18-11-2024_222910_ (1)](https://github.com/user-attachments/assets/7f59ce71-aa79-4dea-bab9-132f36e5e413)

**Comment by hagezi** [comment]
This cannot be solved with DNS, you need a content blocker like uBlock.

I do not block cookie domains, why? See:  https://github.com/hagezi/dns-blocklists/wiki/FAQ#cmps
