### ISSUE TITLE
fake unsubscribe domains

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4376]
### Which domain(s) should be blocked?

allinoursite.com
doorsstormsy.shop
emailservicesnetau.com
euromaillinnk.com
findthorman.shop
keydoordasher.shop
mybach.xyz
threeneptuneboot.com

### Why should these domain(s) be blocked?

https://github.com/AdguardTeam/AdguardFilters/issues/193249#issue-2672722293

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by dftf-stu** [comment]
Please also add:

glaters.com
makitfornows.com

**Comment by iam-py-test** [comment]
I'm sorry, but without actually receiving one of the spam emails, I unfortunately lack any way to test if these unsubscribe websites work or just cause more spam to be sent, nor decern that from the screenshots provided.
That said, the website makitfornows.com may be misrepresenting it's ownership, and that is something I am capable of investigating and testing.
Sorry.
