### ISSUE TITLE
fr.app.chat.global.xiaomi.net

### ISSUE THREAD

**Issue by ivanzd1** [hagezi/dns-blocklists#4377]
### Which domain(s) should be blocked?

hagezi multi pro not  block this ,its safe to block? 
![IMG_20241119_205832](https://github.com/user-attachments/assets/b8200880-91d1-4281-8dfb-11f9e5c23028)

### Why should these domain(s) be blocked?

fr.app.chat.global.xiaomi.net

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Used for Xiaomi Cloud and messaging services.
