### ISSUE TITLE
More proxies

### ISSUE THREAD

**Issue by Bismuthfallacy** [hagezi/dns-blocklists#4389]
### Which domain(s) should be blocked?

https://www.bestmod.site/

https://autismawareness.design/ 
https://gingerbread.design/ 
https://disciplinary.design/ 
https://jackandthebeanstalk.design/ 
https://petergriffin.design/ 
https://tinfoil-is-ass.xyz/ 
https://commanders.design/ 
https://grammarhelpers.com/ 
https://calculusproblems.online/ 
https://f0lga.tech/ 
https://constitutional.design/ 
https://rakhmatullo.gay/ 
https://cybertruck.design/ 
https://compsci.college/ 
https://notartclass.design/ 
https://hustlersuniversity.pro/ 
[https://tutoeerials.tether-dev.com/](https://tutorials.tether-dev.com/)
https://anatomical.design/ 
https://chubsinfestation.design/  
https://spanish101.college/ 
https://commonapp.college/ 
https://doityourselfcrafts.design/ 
https://edpuzzle.space/ 
https://schoology.help/ 
https://citrik.design/ 
https://tinf0il.tech/ 
https://tinf0il.design// 
https://tinf0il.online/ 
[https://crusty.motorcycles/](https://www.crusty.motorcycles/)
https://chromebook.digital/  
https://eduacation.lol/ 
https://schoology.college/ 
https://zone.actsministries.org/mobile.html
https://help.newhopes.info/mobile.html
https://explore.francomedia.net/mobile.html
https://sescloud.club/
https://www.dvprovider.icu/
https://www.darkfat.com/
Https://Geoguessr.lol
https://www.polarvoid.store/

https://sites.google.com/stu.wisd.org/thenewworld/proxies/ye
^the last site here lists a whole bunch of proxy websites. It obviously can’t be blocked itself because it’s a google site, but maybe the sites on this could be added?

thank you for your work

### Why should these domain(s) be blocked?

Bypass DNS

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
I've taken a few proxies from the site, but not the huge list, I'm not cluttering up my bypass list, it's just a drop in the ocean. There are tons of proxies and they are sprouting up like mushrooms. That makes no sense, because a domain bypass list can easily be bypassed.

We've had discussions about this or similar proxylists here before.

**Comment by Bismuthfallacy** [comment]
Thanks for your reply. 

They are sprouting up like mushrooms, though I’m not sure a domain bypass lid can _always_ be bypassed. For instance, for companies/institutions which enforce a specific customised DNS, prevent removing the DNS settings and also prevent the use of VPNs, the only way for users to get around the DNS’s rules is to use a web proxy, unless I’m missing something?
