### ISSUE TITLE
Unblock youtube.com

### ISSUE THREAD

**Issue by nyawox** [hagezi/dns-blocklists#4391]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

DoH/VPN/TOR/Proxy Bypass

### Which domain(s) should be unblocked?

||youtube.com^

### Why should the domain(s) be unblocked?

last commit a hour ago introduced this change 628457c994ad6522d0beaaf559f85e08331d2e2a
this blocks the entire youtube domain. `ping youtube.com` fails. shouldn't be blocked unless the name of the blocklist was "extreme privacy blocklist" or something😸

https://github.com/hagezi/dns-blocklists/blob/628457c994ad6522d0beaaf559f85e08331d2e2a/adblock/doh-vpn-proxy-bypass.txt#L4435

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@nyawox WTF, will be fixed asap ...

**Comment by nyawox** [comment]
thank you :)

**Comment by hagezi** [comment]
No thanks, that was my mistake. Just stupid. I'm getting old. ;)
