### ISSUE TITLE
YOUTUBE.com is blocked

### ISSUE THREAD

**Issue by SpotlightForBugs** [hagezi/dns-blocklists#4392]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [x] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [x] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

DoH/VPN/TOR/Proxy Bypass

### Which domain(s) should be unblocked?

youtube.com

### Why should the domain(s) be unblocked?

wrong...

![image](https://github.com/user-attachments/assets/2579b4ad-6c1f-42fb-9b59-03934c519647)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by SpotlightForBugs** [comment]
[https://filters.adtidy.org/dns/filter_52.txt](https://filters.adtidy.org/dns/filter_52.txt#:~:text=com%5E%0A%7C%7Cyourinternetproxy.info%5E-,%7C%7Cyoutube.com%5E,-%7C%7Cyoutube%2Dproxy.com)#:~:text=com%5E%0A%7C%7Cyourinternetproxy.info%5E-,%7C%7Cyoutube.com%5E,-%7C%7Cyoutube%2Dproxy.com

**Comment by hagezi** [comment]
It is fixed, see https://github.com/hagezi/dns-blocklists/issues/4391
Wait for the next update in AdGuardDNS.

**Comment by SpotlightForBugs** [comment]
https://github.com/hagezi/dns-blocklists/issues/4391

**Comment by SpotlightForBugs** [comment]
Thank you very much @hagezi 
I should've checked

**Comment by hagezi** [comment]
@SpotlightForBugs I will leave the issue open until AdGuardDNS has updated the lists.

**Comment by SpotlightForBugs** [comment]
Alright:)

**Comment by hagezi** [comment]
@SpotlightForBugs The lists in AdGuardDNS appear to be up-to-date, youtube.com is no longer blocked.

**Comment by SpotlightForBugs** [comment]
@hagezi I can confirm that it's working now
