### ISSUE TITLE
youtube not working because of HaGeZi's Encrypted DNS/VPN/TOR/Proxy list

### ISSUE THREAD

**Issue by jerogabe** [hagezi/dns-blocklists#4394]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

DoH/VPN/TOR/Proxy Bypass

### Which domain(s) should be unblocked?

youtube.com
![Captura de pantalla 2024-11-20 210733](https://github.com/user-attachments/assets/9c8d18e7-f92b-4a83-92cd-1536ee7ab4c3)

### Why should the domain(s) be unblocked?

could this be a bug? Youtube has stopped working on all my devices.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@jerogabe It is fixed, But apparently the lists are not yet synchronized on ADGuard DNS servers in all regions. Wait and see, or add ||youtube.com^$badfilter to the user rules.

https://github.com/hagezi/dns-blocklists/issues/4391
https://github.com/hagezi/dns-blocklists/issues/4392
