### ISSUE TITLE
Add PhishTank to TIF sources 

### ISSUE THREAD

**Issue by gjmveloso** [hagezi/dns-blocklists#4398]
It would be feasible to add PhishTank to your sources list for Phishing data?

Although it’s not as active as in the past it still contains valuable number of phishing sites that are active and stealing people’s information.

Apparently it [provides a free-of-charge](https://phishtank.com/developer_info.php ) method to download its database programmatically.

**Comment by hagezi** [comment]
The data is already included via phishing.army.
