### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by trackerct** [hagezi/dns-blocklists#44]
Can you add blocklist please?
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/light.txt

Trackers by Vivo Mobile (have a couple of dns queries)

tr-vcode-od.vivoglobal.com
tr-vcode-api.vivoglobal.com
tr-st-sl.vivoglobal.com
tr-domaincfg.vivoglobal.com
tr-timesync.vivoglobal.com
tr-romsp-unifyconfig.vivoglobal.com
asia-ex-adlog.vivoglobal.com
asia-analyzer-appstore.vivoglobal.com

Trackers by Vodafone

netperform-is.vodafone.com.tr
vodafonetr.sc.omtrdc.net
mplusps.ims.vodafone.com
mpluswf.ims.vodafone.com

Advertising
advertise.ldplayer.net
creative.eagllwin.com
api.eagllwin.com
storeen.ldmnq.com

Google Spyware (have a couple of dns queries)

telephonyspamprotect-pa.googleapis.com
growth-pa.googleapis.com
deviceintegritytokens-pa.googleapis.com
gmscompliance-pa.googleapis.com
mdh-pa.googleapis.com
firebaseinstallations.googleapis.com
digitalassetlinks.googleapis.com

**Comment by hagezi** [comment]
I don't just blindly add domains without knowing more details. First, an extensive analysis is necessary. That you "recognized" them as trackers is not enough. Some of the domains mentioned are definitely false positives and breaks functionality.
Blocking them may not cause any problems for you, but it probably will for the masses.
I suggest you to put them on your personal blacklist.

See:
https://github.com/StevenBlack/hosts/issues/2100#issuecomment-1259223500
https://github.com/AdAway/adaway.github.io/issues/354
