### ISSUE TITLE
datadog.pool.ntp.org

### ISSUE THREAD

**Issue by celenityy** [hagezi/dns-blocklists#4400]
### Which domain(s) should be blocked?

```sh
0.datadog.pool.ntp.org
1.datadog.pool.ntp.org
2.datadog.pool.ntp.org
3.datadog.pool.ntp.org
datadog.pool.ntp.org
```

### Why should these domain(s) be blocked?

NTP servers like this are usually harmless, as they serve legitimate purposes & provide important functionality.

However, these servers are ran by the analytics company [Datadog](https://www.datadoghq.com), and **appear to be used for the sole, explicit purpose of tracking.**

From their [docs](https://docs.datadoghq.com/integrations/ntp/?tab=host#overview):

> **The Network Time Protocol (NTP) integration is enabled by default and reports the time offset from an ntp server every 15 minutes.** When the local Agent’s time is more than 15 seconds off from the Datadog service and other hosts you are monitoring, you may experience:

>  Incorrect alert triggers
> Metric delays
> Gaps in graphs of metrics

> Data Collected:
> **Metrics**
> ntp.offset
> (gauge)	**The time difference between the NTP reference clock and the local clock.**
> Shown as second

> Service Checks
> ntp.in_sync
> Returns CRITICAL if the host clock is more than the configured threshold away from the NTP time. Returns UNKNOWN if the Agent can not connect to the NTP server. Returns OK otherwise.

This is the first time I've seen an NTP server abused for tracking like this... I wonder if it'll become more common? This type of data is highly fingerprintable.

I initially discovered this via observing various adware mobile games phoning home to the servers. Haven't noticed any issues or heard any complaints with them blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The NTP servers are only used internally in their agent, a normal user of apps and sites that use their services for analytics and the like will never see these calls in the logs.

**Comment by celenityy** [comment]
> The NTP servers are only used internally in their agent, a normal user of apps and sites that use their services for analytics and the like will never see these calls in the logs.

I see these frequently in logs, which is what drew my attention in the first place.

Actually, as recent as a few seconds ago apparently:

![image](https://github.com/user-attachments/assets/3b5ed724-0422-4e25-b500-76b7e275d840)

They appear to be using this for some kind of tracking/fingerprinting, and in my experience, it seems to be coming from mobile games that implement their tracking.

Based on a [ControlD forum post](https://feedback.controld.com/posts/1226/usa-network-live-tv-not-working), it looks like others have also encountered these in the wild:

> 2022-08-21 18:29:36 | PASS | **0.datadog.pool.ntp.org** | 46.17.88.210, 81.21.76.27, 95.215.175.2, 80.87.128.222

> 2022-08-22 08:37:25 | PASS | **0.datadog.pool.ntp.org** | 85.199.214.98, 139.162.219.252, 178.62.16.103, 178.62.68.79

**Comment by hagezi** [comment]
That's wild ...

**Comment by renatoyamane** [comment]
My blocklist is updated (8 December 2024 at 23:47) and I'm also noticing it blocked:
![image](https://github.com/user-attachments/assets/56659aaa-aeb1-428c-a6b4-b48d76d9b9b4)

**Comment by ExtRIELICi** [comment]
This issue only affects Datadog domains? This means that domains like `2.android.pool.ntp.org` or `2.fedora.pool.ntp.org` are unaffected and are used solely for non-tracking activities, correct?

**Comment by celenityy** [comment]
> This issue only affects Datadog domains? This means that domains like `2.android.pool.ntp.org` or `2.fedora.pool.ntp.org` are unaffected and are used solely for non-tracking activities, correct?

The issue does **not** only affect Datadog domains - **any time server** could also technically be used for tracking & fingerprinting in this manner.

**That being said**, ex. both `2.android.pool.ntp.org` or `2.fedora.pool.ntp.org` are used on the OS level; and it's **vital** to keep your operating system's date & time up to date for security reasons. In these cases, the time servers also don't introduce any privacy risks that aren't already there. (For instance, you're already using Google's operating system... there's no data that Google can gain via `2.android.pool.ntp.org` that they're not already getting. Only more work for them and no reward). In cases like these, the security benefits clearly outweighs the minor to **nonexistent** privacy risk here. There are far more important privacy & security concerns with network time to focus on.

There's essentially no point blocking these domains, and I'd highly recommend **against** doing so. Also worth noting that in both Android & Fedora, you can just change the time servers. For Android, I note the ADB commands you need to do this [here](https://celenity.dev/posts/resources/adb/#change-time-server). For Fedora, you could also simply change time servers *(Just edit `/etc/chrony.conf`) - **but** if you'd like to fix the more important privacy & security concerns I alluded to above, you can see my Chrony config [here](https://codeberg.org/celenity/Slingshot/src/branch/pages/slingshot/etc/chrony.slingshot.conf).

With that aside: Datadog's case is different; as their servers aren't used on the OS level or really for any legitimate purpose at all as far as I can tell, unlike ex. `2.android.pool.ntp.org` & `2.fedora.pool.ntp.org`. Datadog's ntp servers are only used in apps with their libraries as an extra data point for tracking. As such, it becomes clear to block them.

**This will be interesting to follow though.** Datadog is the first company I've seen use time servers for tracking like this, so I do wonder if other companies will follow and if this will become more common in the future.

**Comment by ExtRIELICi** [comment]
Thank you for the detailed answer! I really appreciate the effort you put into explaining it so thoroughly.
