### ISSUE TITLE
Any idea on what this might be?

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4403]
I saw this on Reddit and made me wonder:

`https://www.reddit.com/r/nextdns/s/nTc7Sis0tc`

**Comment by hagezi** [comment]
No, I don't know, I checked three random ones, all three don't exist (NXDOMAIN).

**Comment by hagezi** [comment]
https://github.com/IngoZenz/personaldnsfilter/issues/234
