### ISSUE TITLE
Adguard DNS

### ISSUE THREAD

**Issue by vdias** [hagezi/dns-blocklists#4409]
A little offtopic...

I was thinking on moving from NextDNS to AdguardDNS, but just found out, that AdguardDNS do not have a software equivalent to the NextDNS CLI.

How do you guys configure AdGuard DNS so all devices on your LAN are identified on AdGuardDNS?

**Comment by hagezi** [comment]
You can use encrypted DNS on any device, or e.g. https://github.com/AdguardTeam/dnsproxy.

I use encrypted DNS permanently for all mobile devices via a mobileconfig profile (iOS/Apple). Regardless of whether they are in the home WLAN or not. For the local devices in the home network, I use DoT via the FritzBox. If I need separate profiles for certain devices in the home network, I use the above-mentioned DNS proxy as a Docker container.

**Comment by vdias** [comment]
Using DoT on your router, works, but you cannot identify each device request what... i tried DNSproxy, but still same behavior... it redirects all requests, but no device identification...

Opened this issue, because it feels i'm missing something... cannot imagine that no one reported this to Adguard DNS team.
