### ISSUE TITLE
add @@||cgate.zhaopin.com^

### ISSUE THREAD

**Issue by wartaiwan24** [hagezi/dns-blocklists#4410]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

cgate.zhaopin.com^

### Why should the domain(s) be unblocked?

After this domain was blocked, one of the recruitment apps on my phone went wrong

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Not blocked in my lists.

**Comment by wartaiwan24** [comment]
> Not blocked in my lists.

Please see my pictures
![Screenshot_20241123_154057_com.adguard.android.jpg](https://github.com/user-attachments/assets/bc86ec29-960d-44a1-ad62-69ada3b4eef8)

**Comment by wartaiwan24** [comment]
> Not blocked in my lists.

If you've seen my diagram, you'll know what's going on

**Comment by hagezi** [comment]
gtm.zhaopin.com
