### ISSUE TITLE
Add new format: wildcard which starts from `.` (dot)

### ISSUE THREAD

**Issue by catap** [hagezi/dns-blocklists#4416]
Thanks for amazing blacklist!

I'd like to add a suggestion to add a new wildcard format.

Some DNS servers may not support DNS wildcard as it defined in RFC 1034, see https://en.wikipedia.org/wiki/Wildcard_DNS_record

Instead they may implement "any subdomain in that zone". Some DNS servers uses for that syntax `*.example.com` and some illegal name without label such as: `.example.com`, for example OpenBSD unwind.

So, here, as user of OpenBSD unwind which supports `.example.com` as wildcard would like to kindly ask you add such format.

Thanks in advance!

**Comment by hagezi** [comment]
Hi @catap, 8is there a documentation of this? Do you know which DNS servers still support this format?

If I understand correctly, `.example.com` blocks all subdomains, but not `example.com` itself?

The wildcard lists require that the root domain itself is blocked in addition to all subdomains.

**Comment by hagezi** [comment]
You could also convert the list yourself when downloading, e.g.:
`curl -s https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt | grep -Pv '\#' | sed 's/^/\./'`

**Comment by catap** [comment]
@hagezi as far as I know OpenBSD unwind supports it. Yes, you understand it correctly. `.example.com` blocks all subdomains, but not `example.com` itself.

> The wildcard lists require that the root domain itself is blocked in addition to all subdomains.

Unfortently DNS wildcard works differently, see: https://datatracker.ietf.org/doc/html/rfc4592#section-2.2.1

**Comment by catap** [comment]
> You could also convert the list yourself when downloading, e.g.:
> 
> `curl -s https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt | grep -Pv '\#' | sed 's/^/\./' > hagezi_light.txt`

I not sure that it is the right way. `0-02.net` should block `0-02.net` and any subdomain, am I right?

**Comment by hagezi** [comment]
As I mentioned above, the wildcard format is designed to block the root domain and all subdomains. This also works with the DNS servers/adblockers listed under “Should be used for”.

What you need is a list that contains 
```
example.com
.example.com
```
is included. Like OPNsense, only there `*.` is used instead of `.` I do not offer this format.

You could build it yourself from the existing `onlydomains` format:
```
curl -s https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt | grep -Pv '\#' | sed 's/^/\./' > hagezi_light.txt
curl -s https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt | grep -Pv '\#' >> hagezi_light.txt | sort -u
```

**Comment by catap** [comment]
I see.

Just for records, provided commands won't work on BSD sed, it should be something like this:
```
curl -s https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt | sed -E '/^[^#]/p;s,^([^#]+),\.\1,' > hagezi_light.txt
```
