### ISSUE TITLE
sale-friday.store: badware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4417]
### Which domain(s) should be blocked?

https://sale-friday.store/info/

### Why should these domain(s) be blocked?

Elon Musk scam, promoted on Twitter.

![image](https://github.com/user-attachments/assets/43cb95b3-2024-4fc9-ae21-e28db7d1bb1f)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by ExtRIELICi** [comment]
They use different TLDs for the same domain, can someone check for all online domains using the same domain but different TLD?

https://github.com/uBlockOrigin/uAssets/issues/26056

**Comment by jarelllama** [comment]
I'll have a look. Last I checked, there weren't many similar NRDs.

**Comment by jarelllama** [comment]
```
presale-friday.cloud
presale-friday.info
presale-friday.ink
presale-friday.pro
sale-friday.cloud
sale-friday.info
sale-friday.live
sale-friday.pro
stage3-last.cloud
stage3sale.online
stage3sale.store
stage3sale2024.online
stage3sale2024.site
```

**Comment by jarelllama** [comment]
I'll add `presale-friday`, `sale-friday` and `stage3sale` to my NRD regex matching for the scam blocklist.

**Comment by ExtRIELICi** [comment]
https://black-sales.cloud/

New exact scam, again uses different TLDs @hagezi @jarelllama

**Comment by jarelllama** [comment]
Will monitor

**Comment by jarelllama** [comment]
@ExtRIELICi if you want to monitor the status of these domains, you can look at https://github.com/jarelllama/Scam-Blocklist/blob/main/config/phishing_targets.csv. It logs the number of regex matches for each domain in the NRD feed.
