### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#4419]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

www.sahkoinfo.fi

### Why should the domain(s) be unblocked?

Not malicious

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by xRuffKez** [comment]
Can confirm

**Comment by hagezi** [comment]
Blocked by CNAME upcloud.host
