### ISSUE TITLE
dit.whatsapp.net - floods the DNS with requests when blocked

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#4422]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL

### Which domain(s) should be unblocked?

`dit.whatsapp.net`

### Why should the domain(s) be unblocked?

Floods the dns with requests when blocked, possible battery drain on mobile devices.
If not blocked, 1-2 requests are made per day. 

Used for de-identified telemetry (DIT, anonymized telemetry) to collect integrity, reliability and performance data, see: https://faq.whatsapp.com/538382354780857/

Unblocking in the relaxed lists (Light and Normal) only.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jarelllama** [comment]
I only have one request for dit.whatsapp.net in my 90 day log. Might be a region thing.

**Comment by bruvv** [comment]
I'm running HaGeZi - Multi PRO++. And I am still seeing this domain being blocked. Why leave it in the multi pro list ?

**Comment by ani917** [comment]
> I only have one request for dit.whatsapp.net in my 90 day log. Might be a region thing.

long dynamic domains are also used there

WhattsApp is an overly aggressive program that can hog your internet with requests, which is reason enough to uninstall it
