### ISSUE TITLE
Suggest adding https://www.usom.gov.tr/en/address to the blocklist

### ISSUE THREAD

**Issue by emreozudogru** [hagezi/dns-blocklists#4431]
### Which domain(s) should be blocked?

https://www.usom.gov.tr/url-list.txt or https://www.usom.gov.tr/api/

### Why should these domain(s) be blocked?

I am suggesting that the domain https://www.usom.gov.tr/en/address be added to the Threat Intelligence Feeds blocklist. This domain is created by the Turkish government and has the same purpose as the domains currently on the blocklist, which is to block malware, cryptojacking, scams, spam, and phishing.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Already included, see https://github.com/hagezi/dns-blocklists/blob/main/sources.md
