### ISSUE TITLE
TIF blocking meinkonto.telekom-dienste.de in NextDNS

### ISSUE THREAD

**Issue by monzta** [hagezi/dns-blocklists#4436]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

`meinkonto.telekom-dienste.de`

### Why should the domain(s) be unblocked?

In order to confirm a new account, Telekom sends you an email and the link to confirm the account starts with `https://meinkonto.telekom-dienste.de/telekom/email/verification/index.xhtml?vid=abc123`

It's working once I disable Threat-Intelligence-Feeds in the Security tab in my NextDNS profile. I wasn't able to find this domain in your repository here though.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Is not blocked by my lists.

**Comment by monzta** [comment]
Got it, thanks! I thought it was your list that you can enable there.
