### ISSUE TITLE
Block chromewebstoredownload.com

### ISSUE THREAD

**Issue by AleIlMagno** [hagezi/dns-blocklists#4438]
### Which domain(s) should be blocked?

chromewebstoredownload.com

### Why should these domain(s) be blocked?

This site is faking to be tied to chromewebstore.google.com and is being used to deliver malware

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jarelllama** [comment]
Already blocked in Hagezi's TIF list via my Scam Blocklist
