### ISSUE TITLE
Please allow sift.com (Fraud management)

### ISSUE THREAD

**Issue by bondskin** [hagezi/dns-blocklists#4439]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

Please allow
cdn.sift.com
api3.siftscience.com

### Why should the domain(s) be unblocked?

required for online payment (Apple Pay)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
In which app or website does the problem occur? I cannot reproduce a general Apple Pay problem.
