### ISSUE TITLE
forum.hr allowlist request

### ISSUE THREAD

**Issue by HellboyPI** [hagezi/dns-blocklists#4442]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

DoH Bypass IPs

### Which domain(s) should be unblocked?

forum.hr

### Why should the domain(s) be unblocked?

Forum.hr is one of the largest and one of the oldest Croatian general-purpose internet forums. It is not a DNS service.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Which IP blocked in your region?
