### ISSUE TITLE
Allowlist club-3d.com

### ISSUE THREAD

**Issue by butwhoscounting** [hagezi/dns-blocklists#4443]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Little Snitch

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds, Threat Intelligence Feeds medium

### Which domain(s) should be unblocked?

club-3d.com
www.club-3d.com

### Why should the domain(s) be unblocked?

Official website of the computer equipment manufacturer Club 3D (https://en.wikipedia.org/wiki/Club_3D).

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
via @marco-acorte antispam-it

**Comment by marco-acorte** [comment]
> via @marco-acorte antispam-it
@hagezi Yes, but club-3d.com is better to choose marketing service providers that do not buy email databases to spam.

cc: @butwhoscounting  

![image](https://github.com/user-attachments/assets/dd9dda3d-eaed-41b0-a735-9012ec19b97b)

**Comment by butwhoscounting** [comment]
Thank you!
