### ISSUE TITLE
ch3.dlvideosfre.click: Malware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4444]
### Which domain(s) should be blocked?

ch3.dlvideosfre.click/human-verify-system.html

### Why should these domain(s) be blocked?

This domains server as a malware delivery method that uses a fake captcha code to trick users into running malware on their computers. The malware is encoded in base64, which is a way of representing binary data as text. When the user pastes the code into the Windows Run dialog box, it is decoded and executed, which downloads and runs the Luma stealer malware. This malware steals the user's browser session tokens, which can be used to log into the user's accounts.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
`ch3[.].dlvideosfre[.]click `is dead (NXDOMAIN)

```
dig ch3.dlvideosfre.click @8.8.8.8

; <<>> DiG 9.16.50-Debian <<>> ch3.dlvideosfre.click @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26175
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ch3.dlvideosfre.click.         IN      A

;; AUTHORITY SECTION:
click.                  300     IN      SOA     ns.trs-dns.com. trs-ops.tucows.c                                                 om. 1732741450 1800 900 604800 300

;; Query time: 23 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Nov 27 22:11:20 CET 2024
;; MSG SIZE  rcvd: 115

```
