### ISSUE TITLE
Windows Outlook Ads

### ISSUE THREAD

**Issue by PuNkYsHuNgRy** [hagezi/dns-blocklists#4450]
I was wondering if you could or already have a list that blocks ads in outlook for windows? I use AdGaurd DNS Blocker.

**Comment by hagezi** [comment]
Which ads do you mean exactly?

**Comment by PuNkYsHuNgRy** [comment]
In the "New" version of Outlook mail client if you do not have a MS365 paid account there are ads in your inbox. There was a Adgaurd list I was using that blocked them previously but it stopped working.

[cid:b2101690-2853-4644-8420-5b5847ea1a02]

________________________________

**Comment by hagezi** [comment]
Yes, they cannot be blocked with DNS.
