### ISSUE TITLE
domains 2

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4454]
### Which domain(s) should be blocked?

lbs-event.gcp.lineate-33x.net
insights.ninetailed.co
insight.synology.com
telegraph.prd.api.discomax.com

### Why should these domain(s) be blocked?

last one is a hbo max tracker. Similar filter exists in easyprivacy. Other ones were just found in my log

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/4473
