### ISSUE TITLE
Microsoft Xbox Gamepass arc.msn.com

### ISSUE THREAD

**Issue by MAscooby** [hagezi/dns-blocklists#4456]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

arc.msn.com

### Why should the domain(s) be unblocked?

Required for Gamepass functionality on Xbox.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jordansworld** [comment]
what exactly does it break?

**Comment by MAscooby** [comment]
I was unable to load the Gamepass Games or Perks screens on my Xbox Series X until I allowed that URL.

**Comment by jordansworld** [comment]
oh ok. well thanks for explaining that makes sense.

**Comment by hagezi** [comment]
See: https://github.com/hagezi/dns-blocklists/blob/main/share/microsoft.txt

https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#ultimate

![image](https://github.com/user-attachments/assets/f97560f7-c4b9-4363-b808-95149c9dad12)

**Comment by MAscooby** [comment]
Ah, thank you. I missed arc at the top!
