### ISSUE TITLE
block these domain

### ISSUE THREAD

**Issue by wudaodadi** [hagezi/dns-blocklists#4467]
### Which domain(s) should be blocked?

logservice1.dbankcloud.com
mobilelog.kugou.com
bd-p2p.pull.yximgs.com
bd-p2p-v2.pull.yximgs.com
p2p-punch-v6.xxpkg.com
p2p-punch.xxpkg.com

### Why should these domain(s) be blocked?

logservice1.dbankcloud.com is Huawei's tracker domain name

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Details of some domains are missing, please provide the relevant details.

**Comment by wudaodadi** [comment]
> Details of some domains are missing, please provide the relevant details.

I wonder which lists these domains will be added to, ultimate or pro or pro++
