### ISSUE TITLE
roblox telemetry

### ISSUE THREAD

**Issue by Lachine1** [hagezi/dns-blocklists#4469]
### Which domain(s) should be blocked?

35.155.141.13
100.20.191.133
ephemeralcounters.api.roblox.com
metrics.roblox.com

### Why should these domain(s) be blocked?

Roblox telemetry

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
See:
https://github.com/hagezi/dns-blocklists/issues/2811

**Comment by Lachine1** [comment]
> See: #2811
> 
> #2797

But the domain that caused the problem was gold.roblox.com so just block metrics
