### ISSUE TITLE
benlukas.de

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#447]
German shopping site

**Comment by martijk** [comment]
Some of the false positives that you've reported come from the [NoTracking](https://github.com/notracking/hosts-blocklists) list, which in turn got them from [here](https://github.com/stonecrusher/filterlists-pihole/), which with all due respect looks like a pretty obscure and not frequently updated list. There might be a [reason](https://oisd.nl/faq#listnotincluded) why oisd hasn't [included](https://oisd.nl/includedlists/big/0) NoTracking. For me this is reason enough to stay away from the Pro list and higher.

**Comment by hagezi** [comment]
Was classified as a problematic store:

"Those who order here receive inferior goods, have to expect long delivery times, additional costs and problems with returns."

https://www.verbraucherzentrale.de/fakeshopfinder-71560
https://www.watchlist-internet.at/liste-problematischer-shops/shops/benlukasde/

Will not be unblocked for the agressive lists. **Will be removed in Light to Pro.**

```
Domain:
 - benlukas.de

Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      OK
 - CONTROLD.TIF    OK
 - DNS0.eu         OK
 - DNS0.eu.ZERO    OK
 - NextDNS.TIF_AI  OK
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        OK
 - Yandex          OK

Blocking Lists/DNS:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - Lightswitch05   OK
 - NextDNS         OK
 - NoTracking      BLOCKED
 - OISD            OK
 - StevenBlack     OK

Intels:
 - Google          https://transparencyreport.google.com/safe-browsing/search?url=benlukas.de
 - VirusTotal      https://www.virustotal.com/en/domain/benlukas.de/information/
 - AlienVault      https://otx.alienvault.com/indicator/domain/benlukas.de
 - Bitdefender     https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fbenlukas.de
 - FortiGuard      https://www.fortiguard.com/webfilter?q=benlukas.de
 - Kaspersky       https://opentip.kaspersky.com/benlukas.de?tab=web
 - McAfee          https://siteadvisor.com/sitereport.html?url=benlukas.de
 - Norton          https://safeweb.norton.com/report/show?url=benlukas.de
 - OpenDNS         https://domain.opendns.com/benlukas.de
 - URLVoid         https://www.urlvoid.com/scan/benlukas.de/
 - Yandex          https://yandex.com/safety/?l10n=en&url=benlukas.de
```
