### ISSUE TITLE
Brave (Account)

### ISSUE THREAD

**Issue by miansopi** [hagezi/dns-blocklists#4470]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

payment.rewards.brave.com

### Why should the domain(s) be unblocked?

Required to access and view your account details at `account.brave.com`.

![102120](https://github.com/user-attachments/assets/2d83e92c-5953-48d9-987c-049f8a9badba)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Rewards remain blocked in the Ultimate.
