### ISSUE TITLE
donate

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4475]
hey i just wanted to say thankyou so much for the hard work. your list is awesome. i dont see a donate button/link. if you do have anything i can tip or donate to thatd be cool. i think if you add a donation link to github(not sure if thats against the rules?) alot of people would probably donate. i know you obviously maintain this list to help people but it takes away from your freetime and i feel you should be compensated. just my opinion. 😁

**Comment by hagezi** [comment]
Thank you, there is no donate link. Some external native sources were used for the base domain database and I think this is unfair to the other list maintainers. Furthermore, a lot comes from the community, there are some capable people who have contributed to the success of the lists. I am not doing this to “enrich” myself. At the moment it doesn't cost me anything, except a lot of free time that I put into maintaining the lists. It's a hobby.

**Comment by djegoburgo** [comment]
thank you for all the time and effort you’re putting into helping the community. Your commitment is greatly appreciated! :applaudissements:

**Comment by timfeierabend** [comment]
Thank you for all the work you put into maintaining all these block lists. Everyone's time is valuable - even if it's a hobby. I'd buy you a coffee if I could.
