### ISSUE TITLE
block these domain

### ISSUE THREAD

**Issue by wudaodadi** [hagezi/dns-blocklists#4476]
### Which domain(s) should be blocked?

dd.browser.360.cn
qurl.f.360.cn
s.f.360.cn
pscan.f.360.cn

### Why should these domain(s) be blocked?

I don't know if your list already includes these four domains, I found that these four domains detect the URLs that users browse, violating privacy, and if your list does not contain these four domains, it is recommended to add them to your list. By the way, I would like to ask, what level of list will it be added? Will it only be added to ultimate

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Domains for which I am not sure whether they lead to restrictions are only blocked in the aggressive lists, i.e. Pro++ and Ultimate.
