### ISSUE TITLE
These are all advertising domains for Xiaomi devices

### ISSUE THREAD

**Issue by wudaodadi** [hagezi/dns-blocklists#4478]
### Which domain(s) should be blocked?

 519332DA.rtc.youme.im
 ad.doubleclick.net
 ad.hpplay.cn
 ad.mi.com
 ad.xiaomi.com
 ad1.xiaomi.com
 adc.hpplay.cn
 adcdn.hpplay.cn
 adeng.hpplay.cn
 admaster.com.cn
 adv.sec.miui.com
 alert.kuyun.com
 alog.umeng.com
android.bugly.qq.com
 api.ad.xiaomi.com
api.cupid.ptqy.gitv.tv
 api.hpplay.com.cn
 appstore.cdn.pandora.xiaomi.com
 appstore.pandora.xiaomi.com
 assistant.pandora.xiaomi.com
 auth.api.gitv.tv
 b.netcheck.gallery.pandora.xiaomi.com
 broker.mqtt.pandora.xiaomi.com
 bss.pandora.xiaomi.com
cdn.ad.xiaomi.com
 cdn.hpplay.com.cn
 cdn1.hpplay.cn
 cloud.hpplay.cn
 conf.hpplay.cn
config.kuyun.com
 d1.xiaomi.com
data.mistat.xiaomi.com
 de.pandora.xiaomi.com
 devicemgr.hpplay.cn
 dvb.pandora.xiaomi.com
e.ad.xiaomi.com
f1.market.mi-img.com
f1.market.xiaomi.com
f2.market.mi-img.com
f2.market.xiaomi.com
f3.market.mi-img.com
 f3.market.xiaomi.com
 f4.market.mi-img.com
 f4.market.xiaomi.com
 f5.market.mi-img.com
 f5.market.xiaomi.com
 file.xmpush.xiaomi.com
 fix.hpplay.cn
 ftp.hpplay.com.cn
g.dtv.cn.miaozhan.com
g.dtv.cn.miaozhen.com
 gallery.pandora.xiaomi.com
gslb.hpplay.cn
 gvod.aiseejapp.atianqi.com
h5.hpplay.com.cn
hotupgrade.hpplay.cn
hotupgrade.hpplay.cn
 hpplay.cdn.cibn.cc
 hub5btmain.sandai.net
 hub5emu.sandai.net
 image.hpplay.cn
imdns.hpplay.cn
 jellyfish.pandora.xiaomi.com
 leboapi.hpplay.com.cn
 logonext.tv.kuyun.com
 market.xiaomi.com
 metok.sys.miui.com
 milink.pandora.xiaomi.com
 misc.in.duokanbox.com
 misc.pandora.xiaomi.com
 mishop.pandora.xiaomi.com
 mitv.tracking.miui.com
 new.api.ad.xiaomi.com
 o2o.api.xiaomi.com
 omgmta.play.aiseet.atianqi.com
 osfota.cdn.aliyun.com
 osupdateservice.yunos.com
 ota.cdn.pandora.xiaomi.com
 package.box.xiaomi.com
 package.cdn.pandora.xiaomi.com
 pandora.mi.com
 pin.hpplay.cn
 r.browser.miui.com
 redirect.pandora.xiaomi.com
 register.xmpush.xiaomi.com
 resolver.msg.xiaomi.net
 rp.hpplay.cn
 rp.hpplay.com.cn
 rps.hpplay.cn
 sdkauth.hpplay.cn
 sdkconfig.ad.xiaomi.com
 secure-chn.imrworldwide.com
 sl.hpplay.cn
 ssp.ad.xiaomi.com
 staging.ai.api.xiaomi.com
 starfish.pandora.xiaomi.com
 stat.pandora.xiaomi.com
 t7z.cupid.ptqy.gitv.tv
 tat.pandora.xiaomi.com
 test.ad.xiaomi.com
 test.new.api.ad.xiaomi.com
 tracking.miui.com
 tv.aiseet.atianqi.com
 tv.weixin.pandora.xiaomi.com
 tvapi.kuyun.com
 tvapp.hpplay.cn
 tvmanager.pandora.xiaomi.com
 tvmgr.pandora.xiaomi.com
 upgrade.mishop.pandora.xiaomi.com
 upgrade.xl9.xunlei.com
 userapi.hpplay.com.cn
 v.admaster.com.cn
 video.market.xiaomi.com
 vipauth.hpplay.cn
 vipsdkauth.hpplay.cn
 vv.play.aiseet.atianqi.com

### Why should these domain(s) be blocked?

I read your list of advertising domains for Xiaomi devices. Some of the domains I've provided are already on your list, but because there are so many domains, I can't exclude the ones that are already on your list, so I'll only be able to offer them to you. I'm sorry about that. The domain names I provide are all about Xiaomi devices, including Xiaomi phones, Xiaomi TVs, and more

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The Xiaomi list only contains native xiaomi tracker and ad domains, not domains from third-party providers. These are blocked in the normal lists. Xiaomi domains that are not on the native tracker list lead to restrictions and have therefore been unblocked.
