### ISSUE TITLE
amazon alexa tracker

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4479]
### Which domain(s) should be blocked?

amzn-sidewalk-events-us-east-1-prod.s3.amazonaws.com

### Why should these domain(s) be blocked?

keeps pinging home. tracker.

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
What is being tracked? Are you sure it's a tracker?

`amzn-sidewalk-events:` This refers to Amazon Sidewalk, a service designed by Amazon to extend the functionality of devices like Echo or Ring by creating a shared low-bandwidth network.

This domain might be used to serve public or private content related to Amazon Sidewalk Event notifications.

https://docs.sidewalk.amazon/introduction/

**Comment by jordansworld** [comment]
ah. i guess i didnt think of that. i disabled sidewalk so i dont know why it would be pinging that domain
