### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by wudaodadi** [hagezi/dns-blocklists#4494]
According to the text in the image, Pro, as well as Pro++ and Ultimate, already include a list of pop-up ads. But why is it marked yellow instead of green? Doesn't yellow mean partial inclusion? Your description seems to conflict
![图片](https://github.com/user-attachments/assets/9db17bc6-b2aa-41c6-90c7-319848f7d29e)

**Comment by hagezi** [comment]
Just read and look properly ...
As stated in the text below, only part of the PopUpAds list is included. The other part is in the TIF list (malicious popup ads). This means that if you use Pro or higher and TIF, this corresponds to the content of the popup ads list.
