### ISSUE TITLE
Proxy: unmoor

### ISSUE THREAD

**Issue by MrRobojack** [hagezi/dns-blocklists#4513]
### Which domain(s) should be blocked?

https://unmoor.com/

### Why should these domain(s) be blocked?

First google hit now :)

When I can find some time, I'll have a more systematical search and perhaps write a script or sth to automate this process and hopefully I'll keel them coming. Or well, hopefully not, but you catch my drift.

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jarelllama** [comment]
>When I can find some time, I'll have a more systematical search and perhaps write a script or sth to automate this process and hopefully I'll keel them coming. Or well, hopefully not, but you catch my drift.

You can look at the Google Search crawl and regex matching I use for my Scam Blocklist. The code is open source here: https://github.com/jarelllama/Scam-Blocklist/tree/main/scripts

The code you might be interested in is under retrieve_domains.sh

**Comment by MrRobojack** [comment]
Thanks!

Awesome.. will surely check this then. Thx
