### ISSUE TITLE
Advertising/Spam/Paid Backlinks

### ISSUE THREAD

**Issue by darealdemayo** [hagezi/dns-blocklists#4516]
### Which domain(s) should be blocked?

https://talkmarkets.com/
https://www.uitvconnect.com/
https://www.aspirantsg.com/
https://techstory.in/
https://tradebrains.in/
https://www.sociallykeeda.com/
https://byothe.fr/
https://thecurrent-online.com/
https://www.homecrux.com/
https://www.e-architect.com/
https://edinburgharchitecture.co.uk/
https://baltimorepostexaminer.com/
https://granitegrok.com/
https://inspirationfeed.com/

### Why should these domain(s) be blocked?

Got a spam mail offering news articles/backlinks.

I'm not quite sure if all of them should be blocked, some of them are very obviously just collections of random paid/fake news articles and probably created by the spammer, but others (tradebrains, sociallykeeda, inspirationfeed and maybe more) seem like they could be legit websites and the Spammer is only offering to create articles there. Also, none of those domains share the same whois information, registration date, or mail. 3 share the same webhost, but it's cloudflare...

Also, many of the websites have a functioning menu and impress/about me with linked social media of supposedly real people.

> Hi
> I am a link builder & I have a good number of quality
> sites, where I can help you to build contextual links which will help you to
> get good page rank and domain authority, index able all sites have a Great
> domain Authority and visits. I have some websites,"
> 
> Websites	Da	Trafice
> https://talkmarkets.com/	53	55.4K
> https://www.uitvconnect.com/	42	1.19K
> https://www.aspirantsg.com/	59	7.66K
> https://techstory.in/	66	61.6K
> https://tradebrains.in/	42	1.48M
> https://www.sociallykeeda.com/	59	669K
> https://byothe.fr/	67	20.1K
> https://thecurrent-online.com/	56	2.14K
> https://www.homecrux.com/	58	97.7K
> https://www.e-architect.com/	79	94.1K
> https://.edinburgharchitecture.co.uk/	73	4.33K
> https://baltimorepostexaminer.com/	58	29.1K
> https://granitegrok.com/	58	131K
> https://inspirationfeed.com/	69	295K
> 
> I am waiting for your good reply
> Thanks

Please let me know if I should keep reporting domains like these where I'm not sure about whether or not they are spam/scam/fakenews. Thx for your work! <3

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@jarelllama What do you think?

**Comment by jarelllama** [comment]
Most of these seem like article websites. When I occasionally find these on my blocklist, I label them as false positives because there's usually no scam.

I'll have a closer look into those domains though.

**Comment by jarelllama** [comment]
I can't find anything malicious. None of the sites are selling anything or promoting scams/paid transactions. Whether they are spam or fake news, I'm not confident in making that decision.

**Comment by hagezi** [comment]
Thanks @jarelllama

**Comment by manojsaini21** [comment]
Why do you list sociallykeeda.com do you have any idea of fake website or genuine website?

**Comment by aikkeda** [comment]
Why do you list sociallykeeda.com do you have any idea of fake website or genuine website?
