### ISSUE TITLE
URGENT: 

### ISSUE THREAD

**Issue by vdias** [hagezi/dns-blocklists#4526]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

DoH/VPN/TOR/Proxy Bypass

### Which domain(s) should be unblocked?

dns1.nextdns.io
apple.dns.nextdns.io

### Why should the domain(s) be unblocked?

Blocking nextdns service... NextDNS company after long months added your list to their Block Bypass Methods, and now your blocking them... 

https://github.com/nextdns/blocklists/issues/152

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
You should take a close look at what the purpose of the list is.
The list also blocks DNS bypasses and therefore the domains are correctly stored there.

**Comment by vdias** [comment]
This is not a bypass as is... is a service. But ok, will report to the other side...
