### ISSUE TITLE
blocking google.com / google.co.in

### ISSUE THREAD

**Issue by fr0z3nlif3** [hagezi/dns-blocklists#4537]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

forcesafesearch.google.com

### Why should the domain(s) be unblocked?

as its blocking google.com

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by bokkoman** [comment]
Same here. Can't use Google.com anymore. 
In logs:

www.google.com
→ forcesafesearch.google.com | Blocked by HaGeZi - Multi ULTIMATE.

**Comment by pmr0** [comment]
"www.google.com" is blocked when list is enabled in NextDNS:

→ forcesafesearch.google.com | Blocked by HaGeZi - Multi PRO++.

**Comment by alfablac** [comment]
Same thing was happening with hblock the other day, not sure if hazegi is importing it.

**Comment by celenityy** [comment]
I did some testing, and I'm able to replicate the issue myself - it looks like `www.google.com` is being blocked specifically when `Enforce SafeSearch` is enabled under NextDNS' `Parental Control` settings.

Without `Enforce SafeSearch` enabled, `forcesafesearch.google.com` is still blocked, but `www.google.com` at least works correctly.

I'm also able to confirm this isn't NextDNS-specific, `forcesafesearch.google.com` is blocked on AdGuard Home as well.

I wonder how `forcesafesearch.google.com` got blocked? It must've been [mistakenly added to one of the sources somewhere](https://github.com/hagezi/dns-blocklists/blob/main/sources.md).

For reference: My logs show it's also being blocked by `hBlock`. FYI @hectorm, you might want to remove this as well...

**Comment by celenityy** [comment]
> Same thing was happening with hblock the other day, not sure if hazegi is importing it. Using ultimate

Beat me to it... hBlock isn't [listed as a source](https://github.com/hagezi/dns-blocklists/blob/main/sources.md) - and it looks like hBlock [hasn't been updated in ~2 months](https://github.com/hectorm/hblock/commits/master/) anyways, so I doubt it's related. It's weird both were specifically impacted by this though.

**Comment by celenityy** [comment]
Looks like `forcesafesearch.google.com` is blocked on `https://hostfiles.frogeye.fr/firstparty-trackers.txt`, which is where `hBlock`pulled it from. cc: @GeoffreyFrogeye

@hagezi doesn't use this as a source though, so still unclear how it ended up here.`forcesafesearch.google.com` appears to be blocked in `Multi`, `Multi Pro++`, & `Ultimate`.

**Comment by hagezi** [comment]
via @bongochong

**Comment by bongochong** [comment]
This ended up in my lists by way of `https://hostfiles.frogeye.fr/firstparty-trackers.txt`. I'm in a completely different time zone from you @hagezi, so only chanced upon this because my phone vibrated a few times while I was getting up for some water. Will remedy on my end before passing back out.

**Comment by GeoffreyFrogeye** [comment]
Since my list is/I'm mentionned, allow me to add: I did investigate why it ended up there but couldn't find a satisfying answer yet (something with transferring IP ranges and an issue in my code generating the list?), I'll have to dig further. In the meantime I froze the list and removed forcesafesearch.google.com.

**Comment by bongochong** [comment]
By the way, thank you for maintaining your lists, @GeoffreyFrogeye. We have all dealt with unexpected false-positives, but that obviously doesn't detract from the value of your very thorough work cataloging tracking domains and their cname aliases. As I'm sure you know, a fair amount of other list maintainers use at least one of your lists in full or in part, and I would estimate that I've been pulling in ~65% of your first party trackers list to augment my own lists with each update, for at least a couple of years now. You are very much appreciated.

P.S. Apologies for triggering notifications.
