### ISSUE TITLE
Missing lists in the formats I am interested in.

### ISSUE THREAD

**Issue by chrcoluk** [hagezi/dns-blocklists#4538]
I notice some lists contain full domain/subdomain for pfblockerng, but other ones (typically the smaller ones I am interested in) dont.

Also there is no mini (last 12 months only) for the light and normal lists.

Is it possible to produce these?

Specifically I would be either happy with a medium last 12 months only, or if you dont want to do medium mini then pro last 12 months only list in pfblockerng format, as well as the TIF medium pgblockerng format, so those would be great please.

**Comment by hagezi** [comment]
No, it is not possible to determine all subdomains for these lists, which is why they are not offered.
