### ISSUE TITLE
Is it the ABP format the correct one for pi-hole?

### ISSUE THREAD

**Issue by Frmd-git** [hagezi/dns-blocklists#4541]
Is it the ABP format the correct one for pi-hole?
It looks in [here](https://discourse.pi-hole.net/t/abp-lists-and-wildcards/74363/5) and [here](https://github.com/pi-hole/FTL/pull/1532) as if that format it's not being parsed properly and maybe the host only format would be better.
Is that correct?

_Originally posted by @Frmd-git in https://github.com/hagezi/dns-blocklists/issues/4252#issuecomment-2525146746_

**Comment by hagezi** [comment]
The ABP format requires a current Pi-hole version. The old versions can only process the host and domain format.

**Comment by hagezi** [comment]
@Frmd-git My lists do not contain wildcards and are therefore compatible with Pi-hole.

The Adblock format should preferably be used. The huge domain and host lists, which must contain all possible subdomains, are absolutely ineffective.
