### ISSUE TITLE
Nord VPN Sign in page

### ISSUE THREAD

**Issue by christophergarcia-KS** [hagezi/dns-blocklists#4548]
### Which domain(s) should be blocked?

mxo4bkqvdityebzvp.xyz
ndaccount.com
![IMG_4816](https://github.com/user-attachments/assets/729717e7-83a6-46cc-a255-5862eea5795e)

https://github.com/user-attachments/assets/516ce3ae-148d-4586-ab42-6956d0a16d20

![IMG_4818](https://github.com/user-attachments/assets/a43c6cf0-6aea-45f2-9c12-f7ab72feb7f6)

### Why should these domain(s) be blocked?

Used to sign in to nord vpn

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
I don't block sign in for NordVPN, that makes no sense at all.
