### ISSUE TITLE
Paramount+ (again)

### ISSUE THREAD

**Issue by bondskin** [hagezi/dns-blocklists#4551]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

tags.tiqcdn.com
dpm.demdex.net (unsure)

### Why should the domain(s) be unblocked?

It seems that Paramount+ has changed the streaming backend over the last year.
It was very difficult to nail down the minimum essential domains to be whitelisted.
tiqcdn seems to be part of the media CDN, but it is also using conviva.com and their random domains.

I am not entirely sure if demdex.net is really required (I hope not) but did not had time to test it finally.

Personally, it's a nightmare to see how much domains Paramount+ needs / wants to run properly.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@bondskin 

Paramount+ requires the unblocking of `tags.tiqcdn.com`, which is only blocked in Ultimate. As this is a popular tracker, it remains blocked.

Paramount+ works for me on AppleTV with unblocked domain `tags.tiqcdn.com` when using Ultimate.

**Comment by hagezi** [comment]
ref: https://github.com/hagezi/dns-blocklists/blob/main/share/ultimate-known-issues.txt
