### ISSUE TITLE
proxy sites part 5

### ISSUE THREAD

**Issue by Bismuthfallacy** [hagezi/dns-blocklists#4558]
### Which domain(s) should be blocked?

https://www-obamna.gamefr.xyz/
https://www.frlolyt.site/
https://www.net-ml.online/
https://www.noyourmean.xyz/
https://www.nathanielgavin.lol/
https://www.dns-savage.com/
https://www.digital-triumph.store/
https://www.1010000.online/
https://www.itsayx.online/
https://www.harbaletsstudy.com/
https://www.seanfat.club/
https://www.cosmohacker.space/
https://www-proxy.kokecoco.me/
https://www.webbrowser.live/
https://www.yellowshiitake.com/
https://www.rnblyatclub.online/
https://www-xors.30t.online/
https://www.shazamio.online/
https://www.themeaningofallmeaningsforallofthemeaningsmeanings.lol/
https://www-px.jarnus.xyz/
https://www-irankhanomjan.30t.online/
https://www.ryuto07219.com/
https://www.twinklestarknights.com/
https://www.evacraft.xyz/
https://www-pro.kosite.net/
https://www.communismsucks.win/
https://www.videolast.online/
https://www.71745718.online/
https://www-proxy.koirdsuzu.com/
https://www.108023.xyz/
https://www.excitedmurashin.com/
https://www.gwopboyded.com/
https://www.fast-receive.com/
https://www.tancheetiong.online/
https://www.ngsw1234.com/
https://www.nowhiteflags.xyz/
https://www.francis-proxy.top/
https://www.freelux.world/
https://www.monro-stom-plus.info/
https://www.familyfirst.church/
https://www.fun4school.store/

### Why should these domain(s) be blocked?

these are web proxies

thank you

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by kufluiggil** [comment]
thank u guys

**Comment by kufluiggil** [comment]
thanks ricky for the proxys my names jr btw
