### ISSUE TITLE
Badware hoster

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#4570]
### Which domain(s) should be blocked?

blogspot.co.za
core.windows.net
blogspot.com.eg
blogspot.co.ke
blogspot.com.cy
blogspot.com.mt
blogspot.com.by
blogspot.com.ee
blogspot.co.id
blogspot.com.co
sitebeat.crazydomains.com
blogspot.com.ng
blogspot.com.tr
blogspot.com.uy
site.transip.me
sites.freshmember.com
blogspot.com.br
blogspot.com.es
blogspot.co.uk
blogspot.co.il
on.fleek.co
blogspot.com.ar
blogspot.co.nz
ipfs.fleek.cool
blogspot.com.au
site.builderall.net
blogspot.co.at
my.canva.site
glas.cfolks.pl
us-east-1.oortech.com
paas.massivegrid.net
hp.peraichi.com
host.secureserver.net
92.webydo.com
hosted.phplist.com
ipfs.infura-ipfs.io
cloudapp.azure.com
dx.melivo.net
temp.swtest.ru
myzen.co.uk
dev.vtoshop.com
asji.za.com
wp3.mobinteg.com
whyewah.com.sg
srv521322.hstgr.cloud
sgamzn.uingtunnel.me
r.appspot.com
mzqcrhnd.workers.dev
free-account.us.kg
fra1.zeabur.ap

### Why should these domain(s) be blocked?

Most common hosters from my blocklist. This is in addition to my wildcards.txt file.

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@jarelllama These should first be analyzed in more detail, for example `cloudapp.azure.com`, `core.windows.net`, ...

**Comment by xRuffKez** [comment]
```r.appspot.com``` Google App Engine
```cloudapp.azure.com```
```core.windows.net```

Subdomains lead to legit projects and are also favored for malicious content. Let Microsoft and Google sort out the trash.

**Comment by jarelllama** [comment]
@xRuffKez thanks for the info.

**Comment by hagezi** [comment]
The `blogspot.*` trash is already blocked.

**Comment by hagezi** [comment]
Breaking:
```
cloudapp.azure.com
core.windows.net
hosted.phplist.com
host.secureserver.net
myzen.co.uk
on.fleek.co
paas.massivegrid.net
r.appspot.com
```

IPFS:
```
ipfs.fleek.cool
ipfs.infura-ipfs.io
```
