### ISSUE TITLE
[TIF] cdn.nest.rip

### ISSUE THREAD

**Issue by wont-stream** [hagezi/dns-blocklists#4583]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home, uBlock Origin

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

cdn.nest.rip

### Why should the domain(s) be unblocked?

Seems to be just another file host service with a few other things to it,

Causes issues with people using them as a file host for their websites, etc

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by KrystalSkullOfficial** [comment]
Should be noted `cdn` is the image link. The actual link is https://nest.rip/

**Comment by hagezi** [comment]
Via threatview.io
