### ISSUE TITLE
Eneba

### ISSUE THREAD

**Issue by denis-g** [hagezi/dns-blocklists#4584]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole, uBlock Origin

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Gambling

### Which domain(s) should be unblocked?

eneba.com

### Why should the domain(s) be unblocked?

Eneba is a marketplace for digital games and gift cards for Steam, PC, PSN, Xbox, etc. This is not a "gambling" site.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
No longer blocked, update the list.
