### ISSUE TITLE
Social Media list(s) ?

### ISSUE THREAD

**Issue by MrRobojack** [hagezi/dns-blocklists#4589]
I'm pretty new to this, so forgive me if the following question is off topic, out of the scope of this project or has obvious answers that I'm missing.

**Why no Social Media list(s) ?**
    
For me personally, "a better and cleaner internet" more and more also means (the ability to block all or some) social media websites / apps.

https://www.thesocialdilemma.com/
https://jonathanhaidt.com/social-media/
https://www.vpro.nl/programmas/tegenlicht/kijk/afleveringen/2022-2023/digitale-detox.html
etc.

I've checked other issues / requests here (after a few weeks of educating myself, this seems to be the place2be [this and OISD  @sjhgvr] at least for me), but I can't seem to find anyone (here) asking this question explicitly. 

https://github.com/hagezi/dns-blocklists/issues/2416   last comment, mentions it... sort of
https://github.com/hagezi/dns-blocklists/issues/2136   seems to be the issue with the most relevant info regarding this question...

>> I don't want to block social media here
>> Doesn't really make sense for me either

Same here. But what would make sense to me is to block it (all or some Soc Med) somewhere else ?! :)

>> I definitely don't want to maintain lists with NSFW content and host them here. You also have to be careful with that on Github because of the terms of use.

Perhaps the answer I'm looking for lies somewhere in this direction?

The Multi ULTIMATE - Aggressive protection list mentions Facebook and WhatsApp, but nothing like I have in mind.

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.tiktok.extended.txt

Something like this list would be in the direction of what I have in mind, but then for ALL (or many) social media.
Perhaps including a few big/small kind of variations, like: 

- a separate list for every website/app/medium
- a top 10 list (https://en.wikipedia.org/wiki/List_of_social_platforms_with_at_least_100_million_active_users)
- only the most addictive / harmful ones ;) 
         
In any case... 

And if creating, maintaining (and/or even hosting) such a list (or lists) is for some reason the problem here; I've come to dislike social media so much that I would gladly contribute in every way that is needed to accomplish this.

Thanks & keep up the good work!

Cheers

**Comment by hagezi** [comment]
A blocklist for social media has not been a focus for me so far. Social media is broad and can be divided into various categories. Even someone who claims not to use “social media” will probably use services from different categories without realizing it.

General Social Networking - Platforms focused on broad social connections and networking.

    Facebook
    Instagram
    Twitter (now X)
    LinkedIn
    Snapchat

Video Sharing - Platforms designed for uploading, sharing, and streaming videos.

    YouTube
    TikTok
    Vimeo
    Dailymotion
    Twitch

Photo Sharing - Platforms primarily used for photo-centric content.

    Instagram (also general networking)
    Pinterest
    Flickr
    500px

Messaging and Communication - Focused on private and group messaging.

    WhatsApp
    Messenger (by Meta)
    Telegram
    Signal
    Discord
    WeChat
    Line

Professional Networking - Geared towards career building and professional connections.

    LinkedIn
    Xing

Content Discovery and Curation - Platforms for sharing and discovering articles, videos, and ideas.

    Reddit
    Quora
    Tumblr
    Flipboard
    Mix

Interest-Based Communities - Centered around specific hobbies or niches.

    Goodreads (books)
    Letterboxd (films)
    Strava (sports)
    DeviantArt (art and digital design)

Live Streaming - Focused on real-time video streaming.

    Twitch
    YouTube Live
    Facebook Live
    Periscope (integrated into Twitter/X)

Short-Form Content - Geared towards quick, consumable content.

    TikTok
    Instagram Reels
    YouTube Shorts
    Vine (discontinued but foundational in the genre)

Business and Commerce - Focused on business growth and product showcasing.

    Shopify (Social Features)
    Etsy Community
    Amazon Spark (discontinued)
    Depop

Dating - Focused on building romantic connections.

    Tinder
    Bumble
    Hinge
    OkCupid
    Grindr

Gaming and Virtual Reality - Focused on gaming and virtual social spaces.

    Twitch (gaming live streams)
    Discord (gaming communities)
    Roblox
    Steam Community

Audio and Podcasting - Focused on audio content and communities.

    Clubhouse
    Spotify (podcasting and playlists)
    Anchor (by Spotify)
    Twitter Spaces

Regional Platforms - Social media platforms popular in specific regions.

    Weibo (China)
    QQ (China)
    VK (Vkontakte) (Russia)
    KakaoTalk (South Korea)

A complete list makes little sense to me, where does it start and where does it end? Lists by category or better by service make more sense. However, it is already possible to block individual services in some online DNS services such as AdGuard DNS and ControlD. AdGuard Home also offers an option for self-hosting.

**Comment by celenityy** [comment]
FYI @MrRobojack Mullvad has a social media blocklist [here](https://github.com/mullvad/dns-blocklists/blob/main/lists/doh/social/mullvad-social-blocklist) that may meet your needs. You can also use their `Extended` or `All` [public DNS servers](https://mullvad.net/help/dns-over-https-and-dns-over-tls), which include this social media blocklist, as well as other lists (like some of hagezi's).

**Comment by MrRobojack** [comment]
Thanks 4 the quite elaborated answer.

And yeah, I get (better now) that, besides that there's probably also just not a lot of 'animo' (yet?!) / the demand for ppl using such lists would be low, my question was too vague, abstract etc. Or in any case it can use a bit more thought :)

For the demand part: "Lists by category or better by service make more sense." in combination with a time schedule I actually do see some potential there... 

Although for me personally this will work only because I completely disabled cellular inet on my phone. Not a lot of ppl will 'follow my example' there I'm afraid.

@celenityy Thx! Seems like a good starting point for me ;)

For now: thanks 4 the info. I might come back though with a more thought-through version of this question.

Cheers

**Comment by MrRobojack** [comment]
BTW -->

I thought I was already using that, but when I started using Mullvad the social list was not available on VPN:

"Note that social media block lists are **not** available on our VPN server block lists, they are **only** available on the Encrypted DNS service."

NOW however: 

  https://github.com/mullvad/dns-blocklists?tab=readme-ov-file#social-media-blocking-combinations

Merci

**Comment by hagezi** [comment]
@MrRobojack https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#social
