### ISSUE TITLE
Remove www.veo.co

### ISSUE THREAD

**Issue by lennard0711** [hagezi/dns-blocklists#4593]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster

### Which domain(s) should be unblocked?

www.veo.co
veo.co

### Why should the domain(s) be unblocked?

Veo produces an "AI" sports cam which automatically follows the action on the pitch. Many football (and other sport) teams in Germany use the camera and the video service to record their matches.

It is unclear to me why it got on the Badware Hoster list. Especially since you need a subscription to upload content.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked by CNAME `proxy-ssl.webflow.com`
