### ISSUE TITLE
Allow themorrow.digital and www.themorrow.digital

### ISSUE THREAD

**Issue by ChronSyn** [hagezi/dns-blocklists#4596]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster

### Which domain(s) should be unblocked?

www.themorrow.digital
themorrow.digital

### Why should the domain(s) be unblocked?

'Morrow Digital' / 'The Morrow' is a software development agency based in the United Kingdom. The website listed in the domains section above is used to promote their services and provide avenues for contacting the business.

As of writing, the 'badware hoster' blocklist in my local Adguard Home install was updated on 13 December 2024 at 15:04.

Judging by the DNS response (screenshot below), it appears that this issue is due to them using the proxy-ssl webflow, which appears to be a common issue judging by other reports in this repo.

![image](https://github.com/user-attachments/assets/3a63fe8f-4612-4303-bdf1-b864b4f159fe)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/4593
