### ISSUE TITLE
notesnook.com

### ISSUE THREAD

**Issue by fjordt** [hagezi/dns-blocklists#4600]
### Which domain(s) should be blocked?

`events.streetwriters.co`

### Why should these domain(s) be blocked?

[Notesnook](https://notesnook.com/) continuously sends heartbeat requests to the specified URL throughout the entire duration of its usage.

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@fjordt Are you sure that this does not restrict any functions? I found it on an allowlist, but can't find a reason.

**Comment by hagezi** [comment]
@fjordt https://github.com/badmojr/1Hosts/issues/1644

**Comment by hagezi** [comment]
Used for general SSE (Server side events), see https://github.com/TheAjaykrishnanR/notesnook/blob/master/apps/mobile/app/common/database/index.js
