### ISSUE TITLE
amlbot.request.report - Phishing

### ISSUE THREAD

**Issue by AidanGee7** [hagezi/dns-blocklists#4604]
### Which domain(s) should be blocked?

amlbot.request.report
request.report

### Why should these domain(s) be blocked?

Saw this being spammed on Reddit earlier.

The link amlbot.request[.]report is a fake crypto phishing copy of [this site](https://amlbot.com/).

Many thanks
Aidan

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jarelllama** [comment]
Seems to be a common phishing targert:
```
aml-bot.uno
aml-bots.net
aml-checks-bot.xyz
aml-robot.live
amlanalyzerbot.com
amlbot-check.com
amlbot-compliance.com
amlbot-official.xyz
amlbot-risk.net
amlbot-scan.com
amlbot.cam
amlbot.homes
amlbot.ing
amlbot.rocks
amlbot.sbs
amlbotcheck.org
amlbotcheck.services
amlbotcheck.website
amlbotcheck.world
amlbotlite.com
amlbotsafe.org
amlbotscan.com
amlbotsolution.com
```
Will add it to my automatic phishing detection
