### ISSUE TITLE
metrics5.dt.dbankcloud.com – Huawei Analytics

### ISSUE THREAD

**Issue by xip0enix** [hagezi/dns-blocklists#4611]
### Which domain(s) should be blocked?

metrics5.dt.dbankcloud.com

### Why should these domain(s) be blocked?

Most likely another Analytics domain like **metrics-dre.dt.dbankcloud.com** or **metrics2.data.hicloud.com**, which are already blocked

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
```
dig metrics5.dt.dbankcloud.com

; <<>> DiG 9.16.50-Debian <<>> metrics5.dt.dbankcloud.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 24261
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; EDE: 29: (Result from negative cache for entire name)
;; QUESTION SECTION:
;metrics5.dt.dbankcloud.com.    IN      A

;; AUTHORITY SECTION:
dbankcloud.com.         300     IN      SOA     ns1.huaweicloud-dns.org. hwcloud                    s\.cs.huawei.com. 1 7200 900 1209600 300

;; Query time: 267 msec
;; SERVER: 9.9.9.10#53(9.9.9.10)
;; WHEN: Sun Dec 15 21:53:14 CET 2024
;; MSG SIZE  rcvd: 181

```
