### ISSUE TITLE
Incorrectly Blocked Domain

### ISSUE THREAD

**Issue by chriswallace** [hagezi/dns-blocklists#4615]
### Which AdBlocker/DNS cloud service do you use?

uBlock Origin

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi NORMAL

### Which domain(s) should be unblocked?

chriswallace.net
www.chriswallace.net

### Why should the domain(s) be unblocked?

The website has been used as just a normal personal website for years, nothing malicious or concerning about it. 

![Screenshot](https://github.com/user-attachments/assets/9c5bdd20-5fa3-4e83-875f-6ca261ba2d0b)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via MalwareURL:

https://www.virustotal.com/gui/domain/chriswallace.net/detection

![image](https://github.com/user-attachments/assets/c88831d7-6cb7-459a-8f27-6721c00af2d5)

**Comment by chriswallace** [comment]
The website is hosted on Github Pages, is this a possible cause? Because the IP is shared amongst many sites hosting potentially malicious files?

**Comment by hagezi** [comment]
https://www.malwareurl.com/listing.php?domain=chriswallace.net

Yes, I think the page is incorrectly flagged via the IPs. You should remove the flags at Malware URL for your domain. I will allow them permanently.
