### ISSUE TITLE
[Allow] 23.223.17.167, 23.223.17.164

### ISSUE THREAD

**Issue by SpidaXS** [hagezi/dns-blocklists#4626]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds IPs

### Which IP(s) should be unblocked?

23.223.17.167
23.223.17.164

### Why should the IP(s) be unblocked?

For a while I've noticed assets from the ESPN website haven't been loading. For example: team, article, and player images, etc. For a while I thought this was just something wrong on their end but I finally gave it a check today and found that the Threat Intelligence IPs list was these causing issues again.

![image](https://github.com/user-attachments/assets/d420961e-f133-4b25-93b2-70e3c5ba6087)
![image](https://github.com/user-attachments/assets/4bf76587-f641-4e68-bff9-a0867eaf61ae)
![image](https://github.com/user-attachments/assets/458248fc-ea17-4090-8e5b-59418f1dcdce)

As you can see, all assets either don't load at all or have a black placeholder box.

![image](https://github.com/user-attachments/assets/956dd596-91dc-411a-b414-475a13534e87)
![image](https://github.com/user-attachments/assets/db325ddd-3c4c-48f2-b511-225b58a023fd)
![image](https://github.com/user-attachments/assets/252927a4-34c1-485b-9c0a-a2a453f778c1)

As you can see some of the sites these IPs block are secure.espncdn.com, a.espncdn.com, assets.espn.com, secure.espn.com and some others. Honestly it seems like this threat IPs list has more issues than the regular domains list. I am debating whether to keep this or not.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Thanks, fixed.
