### ISSUE TITLE
http://projectcaffe.bplaced.net should be accessible 

### ISSUE THREAD

**Issue by drybx** [hagezi/dns-blocklists#4632]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Little Snitch

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Badware Hoster

### Which domain(s) should be unblocked?

http://projectcaffe.bplaced.net

### Why should the domain(s) be unblocked?

This site is completely legit. It's about a software for espresso machines that I have been consulting from time to time for years now.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Have a look at what the badware hosters are blocking. bplaced.net is known to host badware, that's why it's on the list. If you want to use a subdomain, you have to add it to your personal allowlist.
