### ISSUE TITLE
NextDNS/free ControlD: Adjustments to the aggressive lists for better and more effective protection.

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#4633]
I have made a few adjustments to the aggressive lists Pro++ and Ultimate so that users who cannot use the Popu-Ads and TIF list, for example in NextDNS and free ControlD, get more effective, better protection.

- The popup ads are now fully included.
- From the TIF full list all malicious NRDs (newly registered domains) of the last 30 days are extracted and included in the aggressive lists.

FYI: @yokoffing

**Comment by Dynamic5912** [comment]
Is this just for NextDNS and ControlD?

Are the other blocklist formats affected?

**Comment by hagezi** [comment]
As written, it affects Pro++ and Ultimate in all formats.

**Comment by Dynamic5912** [comment]
> As written, it affects Pro++ and Ultimate in all formats.

What will this increase the domain count to in the AGH formated lists?

**Comment by hagezi** [comment]
+60000

**Comment by Dynamic5912** [comment]
Nice.

So theoretically, there isn't much of a difference now between Pro++ and Ultimate with these recent changes?

What defines a 30-day NRD as being malicious compared to a normal domain in the NRD 30 list?

**Comment by hagezi** [comment]
The difference between Pro++ and Ultimate is the same as before. Only the above-mentioned domains have been added to both.

All domains are extracted from the TIF full that are also on the 30-day NRD list, which is currently ~30000 domains

**Comment by Dynamic5912** [comment]
I mean there's only a 50k domain difference between the two, compared to a 200k+ difference between Pro and Pro++/Ultimate.

I understand Pro++ and Ultimate are aggressive lists, but with such a marginal difference between them, is there still an obviously glaring need/reason to maintain the two rather then consolidate into one Ultimate list?

**Comment by ExtRIELICi** [comment]
You are the best, thank you! @hagezi

**Comment by hagezi** [comment]
Yes, it makes sense. The lists all have their justification. see:

![grafik](https://github.com/user-attachments/assets/324b7548-99df-415d-aab0-2a802df402bc)

The 200K for Pro are subdomains, you have to look at the compressed size. The difference in size between Pro, Pro++ and Ultimate is mainly due to malicious and popupad domains. Compare the size difference of the mini versions, which are mostly without “TIF domains”.

**Comment by yokoffing** [comment]
> Pro++ and Ultimate are aggressive lists, but with such a marginal difference between them

@Dynamic5912 The philosophy of the two are still different enough.

- Ultimate will definitely break your experience; only for users okay fine-tuning their privacy.
- Pro++ will likely break something on a site eventually, but Pro only should on rare occasions.
- Light and Normal should only have very, very rare site failure.

**Comment by Dynamic5912** [comment]
Understood - thanks.

Keep up the great work!

**Comment by Dynamic5912** [comment]
> > Pro++ and Ultimate are aggressive lists, but with such a marginal difference between them
> 
> 
> 
> @Dynamic5912 The philosophy of the two are still different enough.
> 
> 
> 
> - Ultimate will definitely break your experience; only for users okay fine-tuning their privacy.
> 
> - Pro++ will likely break something on a site eventually, but Pro only should on rare occasions.
> 
> - Light and Normal should only have very, very rare site failure.

Thanks.

I've used Ultimate for many, many months now and only had to whitelist a handful (or less) domains and the Facebook/Meta domains.

Other than that it's passed the wife/kid test with no issues.

**Comment by yokoffing** [comment]
@hagezi I know you're an AdGuard Home user, but did you see where paid ControlD allows you to block NRDs that are one week old or one month old? Nice QoL feature for their native filters.

Nevertheless, like you said, this is good for free ControlD users.

**Comment by yokoffing** [comment]
> I've used Ultimate for many, many months now and only had to whitelist a handful (or less) domains and the Facebook/Meta domains. Other than that it's passed the wife/kid test with no issues.

@Dynamic5912 I'm happy for you because I have most of my network on Pro and somehow my significant other seems to find every site with a false positive 😆

Luckily, that only happens every six months or so.

**Comment by hagezi** [comment]
> @hagezi I know you're an AdGuard Home user, but did you see where paid ControlD allows you to block NRDs that are one week old or one month old? Nice QoL feature for their native filters.

Yes, I have seen it. The goal of this change was to extract only the NRDs from the threat feeds, which provides fewer potential false positives than using a complete NRD list.
