### ISSUE TITLE
adhshield sites broken

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4634]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

would you consider removing:

css-load.com
html-load.com
content-loader.com
error-report.com

### Why should the domain(s) be unblocked?

needed for adshield websites to load.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Not blocked in my lists:

css-load.com
html-load.com
content-loader.com

Where exactly does error-report.com lead to problems?

**Comment by jordansworld** [comment]
oh. That's weird i had these allowed for weeks and maybe i misread which list it was sorry

**Comment by jo2dan94** [comment]
@hagezi should we block error-report.com in ultimate since its apart of adshield?

**Comment by PRSXFENG** [comment]
> [@hagezi](https://github.com/hagezi) should we block error-report.com in ultimate since its apart of adshield?

I'm not them but personally I feel like it's a mixed bag to block or not block this domain

I personally do block it but

They are absolutely collecting analytics via this endpoint, the url contains information about what triggered the page to show up
No doubt Ad-Shield is using this to gather info on what works and what doesn't work and what traps were triggered 

On the other hand, I suppose it may be in good interest to let the user know that the website is demanding the user to unblock

But blocking it does lead to unintended side effects too
If you block it, it falls back to using javascript alert boxes to tell you to disable your ad blocker

clicking ok sends you to the error-report domain
clicking cancel reloads the site, restarting the loop

if you block the js alert, the site quickly gets trapped in a endless refresh loop
