### ISSUE TITLE
On and off with *.cbsaavideo.com

### ISSUE THREAD

**Issue by bondskin** [hagezi/dns-blocklists#4640]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

vod-gcs-cedexis.cbsaavideo.com
or *.cbsaavideo.com

### Why should the domain(s) be unblocked?

I noticed yesterday (Dec 18th 2024) an unusual behaviour in my blocking list, see attachment.
So far the domain vod-gcs-cedexis.cbsaavideo.com was never blocked but it suddenly started and went away and came back.
![IMG_7601](https://github.com/user-attachments/assets/49c64061-e0ba-485c-8885-16d4efdd253a)

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Blocked by CNAME `dg-fa-h1.rspcdn.net`, will be removed.
