### ISSUE TITLE
Questions about Domain Wildcards

### ISSUE THREAD

**Issue by biange200** [hagezi/dns-blocklists#4645]
![Screenshot_20241219_065739_com_estrongs_android_pop_JeEditorActivity.jpg](https://github.com/user-attachments/assets/eef4178d-dd1e-4e25-9601-6d7e4dd1c1dd)

This is the domains wildcard of the OISD rule
His rule has an *, why doesn't your domain wildcard rule used on invizible pro have an * ?

Your wildcard is more like a regular domain name rule，This is the rule format I downloaded for your invizible pro

![Screenshot_20241219_234553_bin_mt_plus_ۡ۠۬.jpg](https://github.com/user-attachments/assets/f986de2f-02f3-49b6-973f-e2763183d6b3)

![Screenshot_20241219_235125_com_github_android_RepositoryActivity.jpg](https://github.com/user-attachments/assets/22a5c4d5-38de-4999-85aa-cf0ce31b14fa)

**Comment by hagezi** [comment]
There are two wildcard formats, one with asterisk and one without, as with the oisd.
As far as I know, the format is supported without asterisk.

Wildcard means that the lists do not contain any unnecessary subdomains.

**Comment by biange200** [comment]
> There are two wildcard formats, one with asterisk and one without, as with the oisd.
> As far as I know, the format is supported without asterisk.
> 
> Wildcard means that the lists do not contain any unnecessary subdomains.

I know that wildcard format does not include subdomains, but I actually want to know if your wildcard format can filter subdomains? For example, Ilmssdk *. zijieapi.com

**Comment by hagezi** [comment]
No, this is not possible, except in AdBlock format. My lists do not contain `*` within a domain for reasons of compatibility with all adblockers.

**Comment by biange200** [comment]
mssdk*.zijieapi.com
Is this also not acceptable? Are you saying that your rules cannot access filtered subdomains?

**Comment by biange200** [comment]
This is the explanation written by the original OISD author![Screenshot_20241220_073032_com_microsoft_emmx_ChromeTabbedActivity.jpg](https://github.com/user-attachments/assets/aeca0538-5528-4322-9e4a-fdf3a32cc3a2)

![Screenshot_20241220_073309_com_microsoft_emmx_ChromeTabbedActivity.jpg](https://github.com/user-attachments/assets/0b82fefc-d209-43a4-b734-e15eb0ed0451)

**Comment by biange200** [comment]
I just wanted to ask you, can your domains wildcard filter subdomains?

**Comment by hagezi** [comment]
I have already answered your question, my lists only contain plain valid domains. So no.
