### ISSUE TITLE
Unblock compact-shop.de

### ISSUE THREAD

**Issue by SoftwareRat** [hagezi/dns-blocklists#4647]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

compact-shop.de

### Why should the domain(s) be unblocked?

This is the ecommerce page of the magazine https://www.compact-online.de/. It has no reason for a DNS block

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via Trusted Shops fake list.
