### ISSUE TITLE
False positive samsungtradein.co.nz

### ISSUE THREAD

**Issue by patrickli** [hagezi/dns-blocklists#4649]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

samsungtradein.co.nz

### Why should the domain(s) be unblocked?

This is a legitimate site. It is used to track trade-ins from offical Samsung Shop in New Zealand.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@jarelllama

**Comment by jarelllama** [comment]
@patrickli thanks
