### ISSUE TITLE
joinhoney.com

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#4666]
### Which domain(s) should be blocked?

joinhoney.com

### Why should these domain(s) be blocked?

https://www.reddit.com/r/LinusTechTips/comments/1hjmghm/so_honey_has_been_scamming_affiliate_links_video/

https://www.youtube.com/watch?v=vc4yL3YTwWk

Paypal Honey scamming yt creators and users.  
They collect data about users, switching cookies tags and imitate discounts like adware. 
https://www.google.com/search?q=paypal+honey+scam

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
I have been blocking this for over a year: https://github.com/iam-py-test/my_filters_001/commit/608dec521925dbdc487cf67339473d21bb517694#diff-069f694838bb708cdb03c54e512131f7fcd93feadb460d44828b8f49729297b3R17241
Thanks for the validation FadeMind
