### ISSUE TITLE
Recommended List of Malicious Websites

### ISSUE THREAD

**Issue by tanmarpn** [hagezi/dns-blocklists#4667]
### Which domain(s) should be blocked?

www.kcczai.com
www.bitbitquark.com
bvox11.cc
www.fxnovus.co
uslasry.com
www.hkeusy.com
www.maicoinmn.com

### Why should these domain(s) be blocked?

This is an anti-fraud website operated by the national government of Taiwan (Taipei). The site regularly publishes links to websites identified as fraudulent or malicious by national monitoring systems. 

I have browsed through multiple entries and noticed that some of these websites are not blocked by TIF. 

Hope you can make good use of the information here to ensure safer browsing for our regional users.

Uri:
https://165.npa.gov.tw/#/articles/subclass/3

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jarelllama** [comment]
@hagezi I'll check in the morning if it's possible to use the website as a source for my blocklist

**Comment by hagezi** [comment]
Thanks @tanmarpn and @jarelllama

**Comment by xRuffKez** [comment]
@jarelllama i think you need to scrape it

**Comment by jarelllama** [comment]
Unable to scrape due to Google bot verification

**Comment by tanmarpn** [comment]
@jarelllama  Thank you for checking. 
This is the original API source. Please check if it can be used. Thank you.

Uri:
https://data.gov.tw/dataset/160055

**Comment by jarelllama** [comment]
@tanmarpn it seems I am unable to access the dataset download: https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=3BB8E3CE-8223-43AF-B1AB-5824FA889883. Even if I could, I am not sure the URL stays the same throughout each update, otherwise I would not be able to scrape the data automatically.

**Comment by jarelllama** [comment]
what I can access is the CSV: https://quality.data.gov.tw/dq_download_csv.php?nid=160055&md5_url=45ab3c35d9f3f23d0166ba8f5ab9fd6d. I am not sure if this is the entire dataset of just a part of it. I will try to scrape the domains but I will have to monitor if the URL changes after each update. If that happens I have tested that I can scrape https://data.gov.tw/dataset/160055 directly to get the CSV URL.

**Comment by jarelllama** [comment]
The CSV has 21922 domains dating back 2022. I will only add those from 2024 onwards.

**Comment by hagezi** [comment]
Thank you very much @jarelllama, let me know when it is integrated and your list is updated online.

**Comment by jarelllama** [comment]
Testing build now

**Comment by jarelllama** [comment]
``` console
Source: 165 Anti-fraud
Raw:11219  Final:10790  Whitelisted:   0  Excluded:   3  Toplist:   4
Processing time: 2 second(s)
```
All good 👍 . Thanks @tanmarpn

**Comment by tanmarpn** [comment]
@jarelllama  Thank you very much. I have gathered some information that I hope will be helpful to you.

1) "od.moi.gov.tw" provides the fastest data updates (every 7 days) and has a fixed URL. However, it blocks all IP addresses that are not from Taiwan. If you can provide a Taiwan proxy for your crawler, I believe this would be the best choice. 
Complete API URL: "https://od.moi.gov.tw/api/v1/rest/datastore/A01010000C-002150-013?format=json&limit=0"

2) Data from "165.npa.gov.tw" is updated almost simultaneously with "od.moi.gov.tw", and I have tested it with IP addresses from multiple countries, all of which can access it normally. I did not encounter the "Google bot verification" issue you mentioned, though I am not sure about the design of your crawler system. Since this API is not ideally designed, it includes all the information from the web pages, making it bloated and requiring some logical analysis to extract the necessary links. You might consider adding a longer timeout for it. 
Complete API URL: "https://165.npa.gov.tw/api/article/subclass/3"

3) Using "quality.data.gov.tw", as you mentioned, might be the best solution when the above two methods cannot be used. However, based on my tests, it has a slower data update. The latest data contains 32,218 records (as of 2024/12/17), while it only has 31,538 records (as of 2024/12/03).

**Comment by jarelllama** [comment]
Option number one with the API seems to work fine. I will update the code in a bit. @hagezi I'll let you know when I am done so you can close this issue.

**Comment by jarelllama** [comment]
Where can I check the total number of entries? I'm currently pulling about 35847.

**Comment by jarelllama** [comment]
Anyway its no matter. I will only pull domains from 2024 onwards.

**Comment by tanmarpn** [comment]
@jarelllama Currently, it seems that the total number of entries can only be calculated by visiting the API in method 1, as they do not provide an additional column or annotation for the total count. 
However, the newer data should all be included in 'https://165.npa.gov.tw/api/article/subclass/3'.

**Comment by jarelllama** [comment]
@hagezi @tanmarpn updated the source:
```
Source: 165 Anti-fraud
Raw:11904  Final: 664  Whitelisted:   0  Excluded:   3  Toplist:   6
Processing time: 15 second(s)
----------------------------------------------------------------------
```
Thanks for the help @tanmarpn

**Comment by hagezi** [comment]
Thanls @jarelllama @tanmarpn
