### ISSUE TITLE
meetwoman.online: phishing

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4668]
### Which domain(s) should be blocked?

meetwoman.online/SNC-001.html

### Why should these domain(s) be blocked?

Posted online by bots, phishing according to VirusTotal.

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by xRuffKez** [comment]
@jarelllama

**Comment by ExtRIELICi** [comment]
It's down already. Closing issue.
