### ISSUE TITLE
TIF Source Suggestion

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#4669]
[criminalip/Daily-Mal-Phishing](https://github.com/criminalip/Daily-Mal-Phishing/tree/main)

**Comment by hagezi** [comment]
Thanks, I'll take a look when I have time.

**Comment by jarelllama** [comment]
https://github.com/jarelllama/Blocklist-Checker/issues/132#issuecomment-2558701213

**Comment by jarelllama** [comment]
I don't see any issues with the list. Everything is well formatted and uniform.

**Comment by hagezi** [comment]
Thanks @jarelllama, will you add it to your list, or should I add it as a source?

**Comment by jarelllama** [comment]
You can add it as yours.

**Comment by hagezi** [comment]
WIll be added on next release to TIF, TIF medium and TIF mini,

FYI: @criminalip
