### ISSUE TITLE
Cash App Reward Scam

### ISSUE THREAD

**Issue by christophergarcia-KS** [hagezi/dns-blocklists#4670]
### Which domain(s) should be blocked?

cshrewards.net

### Why should these domain(s) be blocked?

Fraud cash app

![IMG_5309](https://github.com/user-attachments/assets/0dadb83d-a005-4d19-9827-61397ae0b8f2)

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
I get a 404 when visiting their homepage. Is there a specific URL/subdomain/other conditions (user agent, region, referrer) necessary? Moreover, would you mind clarifying why you believe this to be a scam? I'm afraid this type of complex fraud is not my area of expertise.
Thank you

**Comment by christophergarcia-KS** [comment]
It’s https://cshrewards.net/decem?ttclid=E_C_P_Cn2NaFGjLvw3Y12pQFmEFgTGvADPM9okWi5l6_9T8Kg3czRcRDv6FR0W990IAWx2FYqHHGEq6o0K7WBFyQIo3T4hv_U8NiBzP3ZxkT72_Mw_pY_cn8cIwaKLrmv3Ac5Oow9Mqd7BYO1TKwlxv_VDsSAjjKEqYVSWGC-zUrAdIBIEdjIuMA

**Comment by iam-py-test** [comment]
"~[C]omplex fraud~". Blatant scam.
Blocklisted, thank you for reporting this.
