### ISSUE TITLE
Pi-Hole not compatible

### ISSUE THREAD

**Issue by danielkubovic** [hagezi/dns-blocklists#4671]
Hi,
Pi-Hole shows 0 domains in the list. Perhaps "||" should be replaced with "0.0.0.0 "?
Screenshot:
![2024-12-23 02_47_14-Window](https://github.com/user-attachments/assets/7b2e38bf-cbda-45f8-8cb4-f14ddc88b7aa)

Thank you for your time.
Daniel

**Comment by hagezi** [comment]
You should update Pi-hole to the latest version, which supports the AdBlock format.

**Comment by danielkubovic** [comment]
UI issue on Pi-hole side, sorry.
Running the latest version (Pi-hole v5.18.3, FTL v5.25.2, Web Interface v5.21).

List update:
![2024-12-23 03_22_33-Window](https://github.com/user-attachments/assets/4fa4f737-aaf9-421a-bfe6-b5f233c8cacc)

Dashboard:
![image](https://github.com/user-attachments/assets/124d18e6-5dce-453d-8379-4b91c7d3eac3)

Adlist group management:
![image](https://github.com/user-attachments/assets/3b25a92a-1bc8-4394-bbb0-a69068ff2675)

Test:
![image](https://github.com/user-attachments/assets/fbdb8ec0-05a5-402e-8d54-ff65f114853c)

Just thought it might be useful mentioning this for completeness.
