### ISSUE TITLE
Question : Apple appstore not functioning 

### ISSUE THREAD

**Issue by Critical-Break-5818** [hagezi/dns-blocklists#4678]
Hi,

I am using Pro ++ and TIF filter on all apple devices like ios, macos, tvos as well as ipados.

Only issue that i found with filters is that Appstore frequently shows ‘Couldn’t connect’ on all platforms listed above.

Is there any way to fix this? I am annoyed with this issue. Force closing the app few times then it would start working again.

Any domain that i need to whitelist? Any help would be highly appreciated.

**Comment by hagezi** [comment]
@Critical-Break-5818 I cannot reproduce the problem. Nothing is blocked that could cause the problem. I don't see a problem with the blocklists here, otherwise there would certainly already have been issues with such a popular thing.

**Comment by Critical-Break-5818** [comment]
Will soon share screenshot. I am only using hagezi recommended filters.

**Comment by hagezi** [comment]
@Critical-Break-5818 Do you use AdGuard DNS or AdGuard iOS? Then take a look here:

https://github.com/AdguardTeam/AdGuardDNS/issues/777
https://github.com/AdguardTeam/AdguardForiOS/issues/2404

There are apparently a few users who have this problem. I also use AdGuard DNS, but have never been able to reproduce this problem.

**Comment by Critical-Break-5818** [comment]
I am using Adguard DNS with mobile config. But for blocklist, i use only hagezi. I am NOT using Adguard dns filter list.

**Comment by hagezi** [comment]
@Critical-Break-5818 
As I said, this has nothing to do with the block lists. Then you will probably be affected by the "AdGuard DNS problem" mentioned above.

You should report the problem here: https://github.com/AdguardTeam/AdGuardDNS/issues/777

Otherwise, there are also reports of general App Store problems with iOS 18, e.g,
https://www.reddit.com/r/ios/comments/1hdopkm/ios_18_and_the_app_store/

FYI: @ameshkov

**Comment by Critical-Break-5818** [comment]
Thank you so much for the help. If you want to debug further, i can share profile config with you.

**Comment by hagezi** [comment]
As I said, report the problem in the issue mentioned above.
