### ISSUE TITLE
Packetriot subdomains blocked

### ISSUE THREAD

**Issue by somerandoname** [hagezi/dns-blocklists#4681]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

*.packetriot.net
*.pktriot.net

### Why should the domain(s) be unblocked?

These are the (sub)domains of a reverse tunneling service.     
https://packetriot.com/

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
There are some subdomains in threat feeds, which ones lead to which restrictions?

**Comment by somerandoname** [comment]
For me personally only:     
> eu-west-36307.packetriot.net    
eu-central-7075.packetriot.net

It prevents tunnels from being established and with that services from being connectable. I also suspect that Mullvad's DNS service with the malware list is using this blocklist, as it similarly started preventing the name resolution from succeeding.

However, the other subdomains being blocked will probably affect other users too.
