### ISSUE TITLE
Google Advertisements

### ISSUE THREAD

**Issue by renatoyamane** [hagezi/dns-blocklists#4684]
### Which domain(s) should be blocked?

Hi,

I'm using these lists on my [GL-iNet MT3000](https://www.gl-inet.com/products/gl-mt3000/) - Adguard Home.

- Multi Ultimate Mini
- TIF Mini

But I noticed it's not blocking Google Advertisements :-(

![image](https://github.com/user-attachments/assets/e0418932-d436-4c22-94ae-450541dca9b2)

![image](https://github.com/user-attachments/assets/d51434a9-7875-4c2d-a49f-20613d6287dd)
 

### Why should these domain(s) be blocked?

Annoying advertisements :-)

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
That's right, such ads cannot be blocked using DNS, you need a browser content blocker like uBlock Origin.
