### ISSUE TITLE
Potential Spotify tracker/ad delivering domain

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4689]
### Which domain(s) should be blocked?

quicksilver.scdn.co

### Why should these domain(s) be blocked?

This domain is blocked by other filters I use, but not by HaGeZi.

I’m not exactly sure what it is, but I thought it would be helpful to report it here.

I also found it on a list along with numerous other Spotify domains, where it was recommended to block it: `https://gist.github.com/mrprobot/257f3af652c0b4599634c7c063ec2d88`

It appears to be commonly blocked by several filter lists on GitHub:`https://github.com/search?q=quicksilver.scdn.co&type=code`

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by xRuffKez** [comment]
The domain quicksilver.scdn.co is part of Spotify's Content Delivery Network (CDN) and is primarily used for serving Spotify's assets, such as music files, images, or other content. It is not specifically an ad host or tracker, though Spotify may use CDNs like this to optimize the delivery of both regular content and advertisements on its platform.

**Comment by hagezi** [comment]
Thanks @xRuffKez

**Comment by xRuffKez** [comment]
Found mainly CSP Scripts... testing further.

**Comment by xRuffKez** [comment]
Cannot test, domain is never called on Win11 / Alma and Android.

What i've tested:
Login and Registration
Playback (Premium | Freemium)
Playback over Alexa.

No issues so far. Someone can tell when and where the domain is called?

**Comment by hagezi** [comment]
I see a call from an iOS device in my logs. There are many iOS devices in my network that use Spotify, but so far only one device has triggered the domain. I don't know what triggers the call and what exactly the domain is used for.

**Comment by xRuffKez** [comment]
@hagezi thanks for your info. I just scanned the domain randomly for js scripts and found csp scripts.
I cannot sniff it if it does not get called on my Devices.
