### ISSUE TITLE
usps.com-tracking-helpsenf.xyz: badware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4696]
### Which domain(s) should be blocked?

https://usps.com-tracking-helpsenf.xyz/

### Why should these domain(s) be blocked?

Fake website pretending to be USPS

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by xRuffKez** [comment]
@jarelllama

**Comment by jarelllama** [comment]
That domain is supposed to be automatically detected by my NRD regex matching. @xRuffKez I just checked and it appears to not be in your NRD list.

com-tracking-helpsenf.xyz was registered on 2024-12-27.

**Comment by hagezi** [comment]
Yes, I was also surprised that it wasn't an NRD. But I had only looked at the @xruffkez list.
