### ISSUE TITLE
elamigos.site

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#4698]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

elamigos.site

### Why should the domain(s) be unblocked?

https://www.reddit.com/r/PiratedGames/comments/glynve/can_someone_link_me_to_the_correct_elamigos_site/

https://www.reddit.com/r/PiratedGames/comments/mxge01/fellow_gamers_asking_about_legitofficial_elamigos/

Valid site for elamigos repacks 

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by Dynamic5912** [comment]
Should be on the Anti-Piracy list instead?

**Comment by hagezi** [comment]
Yes, it is ...
