### ISSUE TITLE
Potential tracker?

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4699]
### Which domain(s) should be blocked?

smartplugin.youbora.com

### Why should these domain(s) be blocked?

I notice this often in my NextDNS logs whenever I'm watching Cosmote TV (a Greek IPTV/entertainment platform).

According to ChatGPT, _"The domain is associated with NPAW’s YOUBORA Suite, a video analytics platform that tracks and analyzes user interactions with video content. By integrating plugins from this domain into video players, it collects data on user behavior and video performance metrics, such as play events, buffering times, and errors. This information helps content providers optimize the viewing experience."_

I'm not sure whether this is actually true and if it breaks anything, but I would like to report it here.

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@ExtRIELICi see https://github.com/hagezi/dns-blocklists/issues/1243
