### ISSUE TITLE
[Allow] Plume Network

### ISSUE THREAD

**Issue by eyqs** [hagezi/dns-blocklists#4700]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO mini, Multi PRO++, Multi PRO++ mini, Multi ULTIMATE, Multi ULTIMATE mini, Pop-Up Ads, Threat Intelligence Feeds, Threat Intelligence Feeds medium, DoH/VPN/TOR/Proxy Bypass, Gambling

### Which domain(s) should be unblocked?

miles.plumenetwork.xyz

### Why should the domain(s) be unblocked?

I am the co-founder and CTO at Plume Network, a crypto company [recently in the news on Fortune](https://fortune.com/crypto/2024/12/18/tokenization-plume-funding-blockchain-fintech/). The domain miles.plumenetwork.xyz is a legitimate domain where we give users the opportunity to [interact with our blockchain test network](https://x.com/plumenetwork/status/1828893584235663728).

Some deleted GitHub user added this domain to the DNS blocklists mistakenly in #3019 and #3028. Please let me know if you are able to remove them from all the blocklists! Thank you very much.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@iam-py-test @durablenapkin

**Comment by durablenapkin** [comment]
Thank you, queued to be removed in tonight's nightly

**Comment by eyqs** [comment]
Thank you very much!
