### ISSUE TITLE
lapinfo.fr has been blocked today

### ISSUE THREAD

**Issue by AlexTheGeek** [hagezi/dns-blocklists#4701]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

lapinfo.fr

### Why should the domain(s) be unblocked?

The domain has been blocked today in the adblock list HaGeZi's Threat Intelligence Feeds. 
I am the owner of this domain and I certify that it does not fall into this block list category: Blocks Malware, Cryptojacking, Spam, Scam and Phishing. This domain name is for personal use only in the context of my homelab. 
This is why I am asking you to unblock my domain name from this list.

Thank you in advance.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Via @mikhailkasimov phish feed

**Comment by MikhailKasimov** [comment]
Hello!

Indeed, missed on filters. :( Fixed for now: https://github.com/MikhailKasimov/validin-phish-feed/commit/1e9315d124c3060053cb420d3e7fae1c412fe105

Sorry for FP.

**Comment by AlexTheGeek** [comment]
Hello!

thank you for your quick reply and fix :)

**Comment by MikhailKasimov** [comment]
FP is gone:

![image](https://github.com/user-attachments/assets/a47788b8-1a53-4618-97ea-b171fceeaa4a)

**Comment by hagezi** [comment]
Thanks @MikhailKasimov

**Comment by AlexTheGeek** [comment]
Thank you so much @MikhailKasimov & @hagezi
