### ISSUE TITLE
Crypto Sites List - Real and Fake

### ISSUE THREAD

**Issue by Dynamic5912** [hagezi/dns-blocklists#4703]
With reference to https://github.com/hagezi/dns-blocklists/issues/4700 and other Crypto-related posts/issues - is it worth creating (or recommending) a list to block Crypto sites (real and fake ones).

Much like the Gambling list - these should be something that should be optional to block to help protect users and their families/devices etc.

**Comment by hagezi** [comment]
The fakes, as far as is known, are contained in the TIF. I am not focusing on blocking legal crypto sites.
