### ISSUE TITLE
False positive: gp.se

### ISSUE THREAD

**Issue by kribjo** [hagezi/dns-blocklists#4704]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

Diversion

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

gp.se

### Why should the domain(s) be unblocked?

This is the official site of a very large, very mainstream newspaper of the second biggest city in Sweden.
Further information: https://sv.wikipedia.org/wiki/G%C3%B6teborgs-Posten

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@kribjo gp.se is not blocked in my lists.

**Comment by kribjo** [comment]
False alarm and my bad. There was only a subdomain of gp.se listed (and probably for good reasons) which got me confused though. I didn't check as well as I should have. :| Sorry to waste your time!

The real culprit for the block was OISD's NSFW list which had gp.se as "porn"...
