### ISSUE TITLE
issues.frontierstore.net

### ISSUE THREAD

**Issue by Slipi089** [hagezi/dns-blocklists#4710]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

issues.frontierstore.net / *.frontierstore.net

### Why should the domain(s) be unblocked?

This Domain is a Ticket tracker from frontier development (Game Designer&Puplisher})

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@jarelllama

**Comment by jarelllama** [comment]
Thanks for reporting
