### ISSUE TITLE
Domains for TIF Blacklist

### ISSUE THREAD

**Issue by FejbyK** [hagezi/dns-blocklists#4714]
### Which domain(s) should be blocked?

3.digitalxperience.life
3.newdigitalgenius.life
4.itdigitalczpulse.life
5.freshservice.life
6.innov8ionhub.top
7.futuremoderntech.life
9.itdigitalbgnexus.life
9.newtopdigitals.club
abc-pro-zdravi.cz
abm-clinical.webflow.io
airydress.com
akce.store
a.newdigitals.club
archive.ulaanbaatar.mn
avkjr.shop
b92eegumoc.store
baczaoe.top
bagscnshop.top
beintro.site
bereta.shop
bestbuyczech.myshopify.com
blouser.shop
breedenesintacon.tk
btlua.shop
buycz.shop
buy.layoners.com
cccmall.top
ceniusas.alphazgr.work
ceska-televize.springatdelphi.com
cheap.clearance2021.ru
corbata.shop
cos-sale.shop
crypsome.click
cs.uzasnenabidky24.com
cyun.sanni.store
cz1.alfazv.com
cz1.alkotoxv.com
cz1.energy-saving-b0x.com
cz1.flekobalm.pro
cz1.hondrostrc.com
cz1.ketodieti.com
cz1.suganp.com
cz2.cardimednd.com
cz2.landpld.com
cz2.prostatricum.com
cz3.cannadiabv.com
cz3.landlrev.com
cz3.landntrv.com
cz4.ketodietnd.com
cz6.immunity.canabis-oil.com
cz6.parazr.com
cz8.maxisizend.com
cz.adamourv.com
czat.shop
cz.cannajv.com
cz.cannapt.com
cz.cardilinev.com
cz-cardio-nrj.beauty-shopping.net
cz.ceskysystem.zulole25.vip
cz.coolbox24.info
cz.coolboxshop.com
cz.coprv.com
cz.cystov.com
cz.drdermr.com
czech.e-energy-official.com
czech-germixil.beauty-goods.biz
czech.hondrocream.shop
czechshop.su
cze.dwczd.top
cz-eretron-aktiv.greatest-shop.com
cz-eretron-aktiv.urban-deals.com
cz.ezwattpro.com
cz.feizer.com
cz-gadgets.trackey.store
cz.gigantv.com
czhairperfecta.markmax.site
cz.hemorv.com
czh.tactical-xdrone.newsalepro.com
cz.irecommendz.com
cz.ketodietv.com
cz-kneebrace.beauty-goods.biz
cz.landevrv.com
cz.lekarskereporteri24.com
cz.myhealthyblog.com
cz.nanovein.eu
cz-novinky.website
cz.onlinecheap2020.net
cz.otsnd.com
cz.prostero-official.eu
czsale.2021shoponline.com
czsale.2023discountoutlets.com
cz.technoweek.net
cz.thetrackkey.com
cz.thexdrone.org
cz.trackey.store
cz.wlosnd.com
dashingsoul.com
dbnytr.store
deeplin.shop
demonlaboty.cz
denisablahova.cz
diapromin-cz.peoplestorry.com
discount.shoponline2020.net
dreamchaserloveyourself.site
dvdfunny.top
easyland.top
ee.myvention.com
elamba.shop
elaniea.shop
elegantni.shop
eliskabartova.com
eu.realnews.life
f.education1.top
fixmyppcc.site
freelato.shop
fuyas.shop
gamsgo.com
gbrjah.store
gemgolden.com
giavbv.top
goldendood.shop
grammebr.shop
groershop.com
grtwji.store
hefov.shop
heygamersnort.at
hokaoneoneshop.cz
hs50bww.today
hxhjk.myshopify.com
javeng.shop
jdaptablej.monster
jjshouse.cz
jk.axayy.club
jlgdr.shop
kamagralove.shop
keyine.shop
kfxgw.shop
kristinn.shop
kspaceproject.com
kup.amol.cz
lacosteczech.top
lbres.shop
lesni-valecek.myshopify.com
lidbeat.space
lnkuefeo.newherbalfito.com
lnvxnxso.sourcesphyto.com
love-puls.shop
lrrkbnbh.bloghealthup.com
lrvvzglc.bestwellbeings.com
lsplfwoz.newfitosources.com
lufnpbht.fitoremedyheres.com
lujtf.shop
margginkcorcite.tk
mc-go.ml
medgroup.club
milead.click
misetee.top
mled.space
modnidumpraha.cz
moneytg.shop
mrdeny.shop
news.cez-group.xfanclubs.com
newsstart.i-i-i.top
neznost.shop
nuubu.com
obfdj.shop
ocenter.shop
odprezony.shop
oggibenessere.com
ogsxe.shop
oholderdes.shop
okay-world.monster
opbfd.shop
pageanket.com
perfumesonsale.website
pfjhy.shop
poisoil.shop
ppl-cz.505910.site
prodejbotpuma.top
puresuit.shop
qmchp.shop
querid.top
qwtryd.shop
rdbcjf.store
salescz.club
sanke-shen.shop
sexyplastenky.cz
shop1025.carlsplace.org
shop.bymbymp.shop
shop.wwyyggz.shop
siosail.shop
sjuy.store
skwyw.atlor.shop
speedcrossnettbutikk.com
sunglasshut.latest-polarized.com
tazwmzvy.newhealthcarenow.com
tg-lead.space
thenorthfacevyprodej.com
thiyas.tk
try.articblast.co
tryitnow.space
tuubkupp.newhealthylifes.com
twhjbyje.medicphytos.com
uerds.shop
urotrin1cz.doctordays.com
uyjiy.shop
valeroil.shop
veryuseful.ml
vibramfive-fingers.cz
viknok.top
vitahairmax.xfastcart.com
vsetop.cz
wifi-camera.shop
worldandbitcoin.com
wuying.shop
wwnews24.su
xlani.shop
xsykl.shop
xtacticaldrone.xcartpro.com
xtacticaldrone.xfastcart.com
yourketo.diet
zapetos.shop
zelenaazluta.shop
zfjky.shop
zhytd.shop
zv-go.tk

### Why should these domain(s) be blocked?

All these domains have been reported by the Czech Trade Inspection Authority as high-risk e-shops. The list has been filtered to exclude any inactive domains; hopefully, there are no errors present.

(The Czech Trade Inspection Authority (Česká obchodní inspekce) regularly updates a list of high-risk e-shops to warn consumers about potential risks associated with certain online stores.)
https://www.coi.gov.cz/pro-spotrebitele/rizikove-e-shopy/

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by jarelllama** [comment]
@hagezi will add as a source for my blocklist

**Comment by hagezi** [comment]
Thanks @FejbyK  and @jarelllama

Let me know when the source is integrated.

**Comment by jarelllama** [comment]
Checking for false positives now

**Comment by jarelllama** [comment]
Good source. Added to my blocklist:
``` console
Source: Česká obchodní inspekce
Raw:1163  Final:1135  Whitelisted:   0  Excluded:   4  Toplist:  13
Processing time: 5 second(s)
```

**Comment by jarelllama** [comment]
Thanks @FejbyK
