### ISSUE TITLE
ddgo.netlify.app: Potential badware

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4715]
### Which domain(s) should be blocked?

ddgo.netlify.app

### Why should these domain(s) be blocked?

This website appears to be impersonating DuckDuckGo. When I tried searching on it, it redirected me to the real DuckDuckGo, which I find odd. Some buttons I clicked on also redirected to official domains. Could someone verify this?

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by Dynamic5912** [comment]
Looks like it's just a web app of DDG someone is hosting on Netlify.

There's various ones kicking around for Google, DDG etc. all over the place.

**Comment by hagezi** [comment]
Yes, I can't find any flags or anything harmful either.
