### ISSUE TITLE
cybermania.ws

### ISSUE THREAD

**Issue by Morku** [hagezi/dns-blocklists#4716]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Threat Intelligence Feeds

### Which domain(s) should be unblocked?

cybermania.ws

### Why should the domain(s) be unblocked?

It's no Malware, Cryptojacking, Spam, Scam or Phishing.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
```
Secure DNS:
 - 360Secure       OK
 - AliDNS          OK
 - CleanBrowsing   OK
 - Cloudflare      OK
 - ComodoSecure    OK
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - DNSWatchGO      OK
 - HaGeZi.TIF      BLOCKED
 - Neustar         BLOCKED
 - NortonCS        OK
 - Quad9           OK
 - SafeDNS         OK
 - UltraDNS        BLOCKED
 - Umbrella        OK
 - YandexSafe      OK
```
