### ISSUE TITLE
fake apple logins

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4721]
### Which domain(s) should be blocked?

hxxps://icloud.apple.pariet.mhudr.cn/account_int/
hxxps://icloud.apple.street.oanvd.cn/account_int/

### Why should these domain(s) be blocked?

https://x.com/masaomi346/status/1873511461747913038?mx=2

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Already blocked in TIF, TIF medium, TIF mini via Tweetfeed.
