### ISSUE TITLE
ads-Milwaukee.com

### ISSUE THREAD

**Issue by dmbmke** [hagezi/dns-blocklists#4723]
### Which domain(s) should be blocked?

ds-Milwaukee.com

### Why should these domain(s) be blocked?

This is a payment phishing scam to harvest credit card info posing as a municipal parking enforcement. 

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@dmbmke I cannot find any flags and do not see that this is used for phishing. Do you have any sample links?

**Comment by jarelllama** [comment]
ds-milwaukee.com seems to be a copy of https://www.dsparkingportal.com/milwaukee.

The Privacy, Contact Us, and Terms of Use links at the bottom of the page are broken on the fake site.
