### ISSUE TITLE
cdn.onesignal.com

### ISSUE THREAD

**Issue by ExtRIELICi** [hagezi/dns-blocklists#4726]
### Which domain(s) should be blocked?

cdn.onesignal.com

### Why should these domain(s) be blocked?

I noticed that this domain is being blocked by a lot of filters but not by HaGeZi. Is this not a tracker? Should I unblock it?

<img width="318" alt="image" src="https://github.com/user-attachments/assets/8930873a-0a17-4a0a-9e5f-68be5a316b3c" />

### I confirm ...

- [X] that I have checked if there is no other issue for the domain(s) whereby they were unblocked or the blocking was declined.
- [X] that I have checked that the domain(s) are not already blocked.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
OneSignal's CDN (Content Delivery Network). OneSignal is a popular platform for push notifications, and its CDN is used to host scripts, files, and resources needed for implementing their notification services.

Breaks push notifications in some apps.
