### ISSUE TITLE
Removing the problematic lists

### ISSUE THREAD

**Issue by HellboyPI** [hagezi/dns-blocklists#476]
Hello! Recently You got a lot of whitelist requests.  To make your job easier, would it be better to just remove the problematic list(s) (source)? Maybe there are a lot more false positive domains.

**Comment by lyrad87** [comment]
Agreed. This looks like it will be several hundred domains by the time the person is done with it. Maybe not worth the effort or just include it in Ultimate and people can add domains to their Allowlist as they see fit. Up to you, of course.

**Comment by hagezi** [comment]
I will look at the whitelist requests all, they were created based on the Ultimate - no panic. ;)

**Comment by hagezi** [comment]
See: https://github.com/hagezi/dns-blocklists/issues/362

**Comment by hagezi** [comment]
If I remove all the "porpblematic" lists, not much remains, also the OISD would then have to remove. A bit absurd. ;)
If someone wants to help with the analysis, always gladly, otherwise it just takes a while, the colleague has not yet arrived at Z ...

**Comment by devipasigner** [comment]
> If I remove all the "problematic" lists, not much remains, also the OISD would then have to remove. A bit absurd. ;) If someone wants to help with the analysis, always gladly, otherwise it just takes a while, the colleague has not yet arrived at Z ...

I can definitely help sometimes..

**Comment by HellboyPI** [comment]
I understand. Here is a radical idea 😃 --> Don't use OISD, 1Hosts, Notracking, StevenBlack.... lists as a source, because they are list aggregators.  Cherry-pick the lists they use as sources. This would give you more control over your lists and could reduce the false-positive rate.

Or, only use lite/ small versions of their lists as a base/ foundation (OISD small, 1Hosts Lite...) and then cherry-pick the sources they use for bigger versions.

I believe, AdGuard DNS list could also be used as base, because AdGuard uses it for their public DNS servers. Millions of people use these DNS servers. So, the list must be conservative in order to minimize the percentage of false positive domains.

**Comment by devipasigner** [comment]
> I understand. Here is a radical idea 😃 --> Don't use OISD, 1Hosts, Notracking, StevenBlack.... lists as a source, because they are list aggregators. Cherry-pick the lists they use as sources. This would give you more control over your lists and could reduce the false-positive rate.
> 
> Or, only use lite/ small versions of their lists as a base/ foundation (OISD small, 1Hosts Lite...) and then cherry-pick the sources they use for bigger versions.
> 
> I believe, AdGuard DNS list could also be used as base, because AdGuard uses it for their public DNS servers. Millions of people use these DNS servers. So, the list must be conservative in order to minimize the percentage of false positive domains.

I’ve always thought about that idea too. He would then have to check the oisd whitelist with his and see what remaining whitelist domains should he used too

**Comment by hagezi** [comment]
It mainly affects the aggressive lists, especially the Ultimate, which was to be expected. And if someone uses such lists, he should be aware of that. After all, there is a "sticker" on it ;)

The Ultimate in particular still needs some care. It must also be said that these are not popular domains that are reported ...

**Comment by hagezi** [comment]
@devipasigner Thanks for the help with the "thumbs up" on the Toplist Issues. ;)

**Comment by hagezi** [comment]
Most of them came from 1Hosts Pro, an aggressive source, which was to be expected.
As you can see from my whitelist, I've already sorted out a lot from the Umbrella Toplist during my test against 6000 websites. But I didn't focus on sites in the "500000" toplist range, of course. They are flying around my ears now. Is so, tomorrow C come to it ... ;)
