### ISSUE TITLE
community.finanzguru.de

### ISSUE THREAD

**Issue by lyrad87** [hagezi/dns-blocklists#483]
#### What adblocker/DNS cloud service are you using?

NextDNS, both mentioned settings disabled before opening this issue.

#### Which blocklists are used?

Pro++

#### Which domain(s) should be unblocked?

finanzguru.userecho.com 

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

[Finanzguru‘s Community Site](https://community.finanzguru.de/de/communities/7/topics/4677-preismodell-von-finanzguru) cannot be used otherwise. I’m not aware of it being a tracker or an ad so if there is anything mischievous going on in the background, please let me know. I can also just add it to my own Allowlist.

**Comment by hagezi** [comment]
@lyrad87 Thanks.

`community.finanzguru.de` blocked by CNAME `finanzguru.userecho.com` in the aggressive lists, will be removed.

ping source: @badmojr
