### ISSUE TITLE
Prime video

### ISSUE THREAD

**Issue by maghuro** [hagezi/dns-blocklists#484]
#### What adblocker/DNS cloud service are you using?

Nextdns

#### Which blocklists are used?
hagezi Pro++

#### Which domain(s) should be unblocked?
aiv-delivery.net (particularly api.eu-west-1.aiv-delivery.net)

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
I think this domain is used  for telemetry on Amazon Prime Video (because it flattens to global.telemetry.insights.video.a2z.com). However, when blocked, Prime Video breaks. Whitelisting it on Nextdns made the trick and so I'm reporting this false positive.

**Comment by hagezi** [comment]
Thanks, can you specify what exactly is not working? I've had it blocked for ages and Prime Video is used extensively here, even in the wider family - no problems so far. It is Telemetry, that is correct.

**Comment by maghuro** [comment]
The app works, only the movies don't load. As soon as I whitelisted api.eu-west-1.aiv-delivery.net on NextDNS, and cleared local cache, the movies started loading.

**Comment by maghuro** [comment]
UPDATE - I'm so sorry, but that must've been a sad coincidence.
I blocked again that domain, started a movie (using NextDNS to see the domain is called and blocked), and it started streaming right away.
I'm sorry for taking your time - i'll close this issue, further investigate, and reopen if I have new data.

For now, I think it's working.
Thanks once again!

**Comment by hagezi** [comment]
@maghuro 
Thanks, no problem, the pitfalls of technology. If something still occurs, just report. I had just tested again, had no problems. Does not mean of course that works in all situations. If that does not work in the family I get that immediately. ;)
