### ISSUE TITLE
track.gojek.com

### ISSUE THREAD

**Issue by rapdodge** [hagezi/dns-blocklists#486]
#### What adblocker/DNS cloud service are you using?
AdGuard Home (self-hosted)

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
`track.gojek.com`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
`track.gojek.com` are domain for live tracking packages, not for analytics

Additional information (screenshot)
<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/33513626/220031604-cda49599-adf2-4474-b454-ddaf1e3ce482.png">
</details>

**Comment by hagezi** [comment]
Thanks, will be removed.
