### ISSUE TITLE
youexe.com ressources

### ISSUE THREAD

**Issue by Quorum75** [hagezi/dns-blocklists#487]
I use all hagezi lists within NextDNS. 
Today Ultimate is blocking AWS youexe.com website repository. 

I had to whitelist those to be able to download the documents. 

firehose.eu-west-1.amazonaws.com

youexec-resources-down.s3.us-west-2.amazonaws.com

I don't if you want or not whitelist them as they are totally legit.

**Comment by Quorum75** [comment]
Thanks but what about the other link? Without it documents cannot be downloaded.

**Comment by hagezi** [comment]
@Quorum75 
What have I forgotten? Give me a bypass domain.

The following are no longer on my lists:
```
*.firehose.eu-west-1.amazonaws.com
*.youexec-resources-down.s3.us-west-2.amazonaws.com
*. s3-r-w.us-west-2.amazonaws.com
*.youexe.com
```

**Comment by Quorum75** [comment]
> @Quorum75 
> 
> What have I forgotten? Give me a bypass domain.
> 
> 
> 
> The following are no longer on my lists:
> 
> ```
> 
> *.firehose.eu-west-1.amazonaws.com
> 
> *.youexec-resources-down.s3.us-west-2.amazonaws.com
> 
> *.s3-r-w.us-west-2.amazonaws.com
> 
> *.youexe.com
> 
> ```

Sorry but because you didn't mention youexec-resources-down.s3.us-west-2.amazonaws.com I thought it was still in the list. 
All good then, cheers.

**Comment by hagezi** [comment]
No Problem.
