### ISSUE TITLE
disconnect list

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#488]
Disconnect lists have been not updated for some time. There were efforts to make the built-in block list for edge and firebox browsers from official repo https://github.com/disconnectme/disconnect-tracking-protection

An example: https://github.com/erkexzcx/disconnectme-pihole

The maintenance has stopped for months. I don't know specific reasons. Possibly because of the difficulty to remove commonly visited domains from two .json files. 

BTW, duckduckgo's list, included in Vivaldi browser, is also wonderful source given the scanning scale and resource spent on the project. The problem here is still FPs even in [high-confidence entries](https://gitlab.com/quidsup/ntrk-tracker-radar/-/issues/2).

Go back to disconnect list. There may be an easier method to make disconnect list though. On Windows, you can find the list edge use in

C:\Program Files (x86)\Microsoft\Edge\Application\110.0.1587.50\Trust Protection Lists\Mu (if you don't change installation path)

With the project's extensive whitelist, maybe we can revive the disconnect list? (file with name 'content' shall be excluded) @hagezi 

The only concern here is it is not clear whether modifying the files for non-profit use violate licenses.

**Comment by hagezi** [comment]
I have not found anything clear about the license.
