### ISSUE TITLE
hopp.to shouldn't be blocklisted

### ISSUE THREAD

**Issue by shaulgo** [hagezi/dns-blocklists#489]
#### What adblocker/DNS cloud service are you using?
NextDns

#### Which blocklists are used?
HaGeZi(Threat Intelligence Feeds)
HaGeZi (Multi Normal)
HaGeZi (Multi Pro)
HaGeZi (Multi Pro++)
HaGeZi (Ultimate)

#### Which domain(s) should be unblocked?
hopp.to

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It is a url shortener/link-in-bio product by wix. Domain shouldn't be blocked. 
Users get subdomains. So it should be only by subdomains.
Thanks

**Comment by shaulgo** [comment]
Thanks for taking care of this. May I know what service are you using for this report. I recognize virustotal at the top. But how do you get the report under it?

**Comment by hagezi** [comment]
@shaulgo No, it is a shell script based on this script: https://github.com/PeterDaveHello/chkdomain

I just extended it with some functions that query my build system.

**Comment by shaulgo** [comment]
Is it an issue that it's still appearing in th dns-data-collection? 
https://github.com/hagezi/dns-data-collection/blob/335affa6369f36fb5c4e7003ff472db369090598/sources/mitchellkrogza_phishing.database_phishing-domains-new-today.txt#L6055

**Comment by hagezi** [comment]
No, not for my lists, they are just raw data from the sources,
