### ISSUE TITLE
ads trackers

### ISSUE THREAD

**Issue by trackerct** [hagezi/dns-blocklists#49]
for
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/light.txt

collect.analytics.unity3d.com
statsfe2.update.microsoft.com
static.cloudflareinsights.com
mads.amazon-adsystem.com
unagi.amazon.com
fls-na.amazon.com
data.media-lab.ai
r.remarketingpixel.com
toblog.tobsnssdk.com
www.adspirit.com
cdn.consentmanager.mgr.consensu.org
consentmanager.mgr.consensu.org
crm.adflex.com.tr
v10.events.data.microsoft.com
ic3.events.data.microsoft.com
browser.events.data.microsoft.com
browser.events.data.msn.com
report-edge.agora.io
snap.licdn.com
api-js.datadome.co
js.driftt.com
api.leanplum.com
device-metrics-us.amazon.com
log.core.cloud.vewd.com
customerevents.netflix.com IoT Telemetry
nrdp.nccp.netflix.com IoT Telemetry
api.miwifi.com
app.adjust.net.in
androidtvwatsonfe-pa.googleapis.com
functional.events.data.microsoft.com
global.asimov.events.data.trafficmanager.net
onedscolprdcus09.centralus.cloudapp.azure.com
edge.activity.windows.com
edge.activity.windows.com.akadns.net
edge-global.activity.windows.com.akadns.net
edge-emeu1.activity.windows.com.akadns.net
pf2am3-edge.activity.windows.com.akadns.net
a1h91ecnmw3isq-ats.iot.us-west-1.amazonaws.com
device-metrics-us-2.amazon.com
ap-oversea.agora.io
iot-logser.realme.com
iot-eu-logser.realme.com
browser.pipe.aria.microsoft.com
settings.data.microsoft.com
dlwnextsetting.blob.core.windows.net
evoke-windowsservices-tas.msedge.net
web.diagnostic.networking.aws.dev
cdn.segment.com
s.amazon-adsystem.com
performance.radar.cloudflare.com
applog.matrix.easebar.com
sigma-statistics-push.proxima.nie.easebar.com
mcount.easebar.com
who.nie.easebar.com
appdump.nie.easebar.com
usermetrics.lidlplus.com
search-log-1.tapatalk.com
lidlplusprod.blob.core.windows.net
self.events.data.microsoft.com
mobile.pipe.aria.microsoft.com
mon-va.tiktokv.com
psstats.superkinglabs.com
ota.lokalise.co
bundles.live.lokalise.cloud
livelogs.slike.in
mobile.protectt.ai
report-oversea.agora.io
report-oversea2.agora.io
aax-us-east.amazon-adsystem.com
woodpecker.uc.cn
report.banorte.glassboxdigital.io
acs.m.taobao.com
redevents-bigdata.redefine.pl
ipla.hit.stat24.com
pro.hit.gemius.pl
gapl.hit.gemius.pl
total-rekall.metrics.indazn.com
self-events-data.trafficmanager.net
onedscolprdeus02.eastus.cloudapp.azure.com
onedscolprdcus01.centralus.cloudapp.azure.com
biemffjjakefxlbom6zcwmvbiyy1q1663016176.uaid.imrworldwide.com
4ae1981d8d1a370d08bf3d24f50f5baf47ef1b62.cws.conviva.com
hpoahhuy2rocr9xb2kii0o2xeetb41663016176.uaid.imrworldwide.com
dishanalyticsandtesting.sc.omtrdc.net
tuplogpublic.bangcdn.net
akoss.bangcdn.net
mobile-data.onetrust.io
crash-reporting.duowan.com
lcprd1.samsungcloudsolution.net
clickserve.dartsearch.net
sla-intl.trustlook.com
plausible.io
cdn.ftd.agency
suphelper.com
go.trouter.skype.com

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/44#issuecomment-1259319063

**Comment by trackerct** [comment]
> [#44 (comment)](https://github.com/hagezi/dns-blocklists/issues/44#issuecomment-1259319063)

them 100% ads-trackers
no false positive
no need check

**Comment by gothic-bum** [comment]
> them 100% ads-trackers  
> no false positive  
> no need check  

`settings.data.microsoft.com` is used for Windows apps to dynamically update their configuration.  
  
`self.events.data.microsoft.com` is used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. If this is blocked, users won't be able to save documents to the cloud or see their recently used documents.

Etc...
