### ISSUE TITLE
realgift.life

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#490]
#### Which domain(s) should be blocked?

realgift.life

#### Why should the domain(s) be blocked?

Caught blocked by NextDNS AI Threat Detection. The domain is found malicious by multiple threat intelligence databases (Virustotal, Bitdefender, Kaspersky).

Might require further analysis.

**Comment by hagezi** [comment]
`Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           BLOCKED
 - SafeDNS         OK
 - UltraDNS        BLOCKED
 - Yandex          OK`

**Comment by hagezi** [comment]
Secure DNS:
 - CleanBrowsing   OK
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    OK
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - OpenDNS         OK
 - Quad101         OK
 - Quad9           BLOCKED
 - SafeDNS         OK
 - UltraDNS        BLOCKED
 - Yandex          OK

**Comment by hagezi** [comment]
Thanks, will be added.
