### ISSUE TITLE
Fraud & Scam List

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#494]
#### Which domain(s) should be blocked?

1. https://mmmjemp.cn
2. https://bankruptcymelodious.cn
3. https://qxowtod.cn
4. https://crueltyspongy.cn
5. https://ambulancesodium.cn
6. https://negotiatefoam.cn
7. https://deceptivebuffalo.cn

#### Why should the domain(s) be blocked?

_**Confirmed fraud & scam by Indonesian Railways Company**_

> https://www.kai.id/information/full_news/5521-kembali-marak-masyarakat-agar-waspada-penipuan-berkedok-promo-kai

**Comment by hagezi** [comment]
Thanks, will be added.
