### ISSUE TITLE
Possible FPs in ads-tracking-extension.txt

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#496]
Found in https://raw.githubusercontent.com/hagezi/dns-data-collection/main/data/ads-tracking-extension.txt

I now tend to found FPs in each source from dns-data-collection repo,. Welcome others to vet the results. I am ok even you don't agree on all of them. :)

auth-track.goldstarcms.com
bam-tracking.barid.ma
docs.sentry.io
e-tracking.customs.go.th
track.airterra.com
track.amazon.co.uk
track.amazon.com
track.authorhub.elsevier.com
track.bpost.be
track.bpost.cloud
track.clickpost.in
track.cubyn.com
track.delhivery.com
track.dhlparcel.co.uk
track.dpd.co.uk
track.dpdlocal.co.uk
track.dtdc.com
track.easypost.com
track.firstmile.com
track.getconvey.com
track.jetboxinternational.com
track.kuronekoyamato.co.jp
track.livingstonintl.com
track.lumedeo.com
track.mydynalogic.eu
track.omniparcel.com
track.onestepgps.com
track.palmettostatearmory.com
track.puravidabracelets.com
track.quantiumsolutions.com
track.redbubble.com
track.rxo.com
track.ryder.com
track.shipveho.com
track.thailandpost.co.th
track.thailandpost.com
track.toms.com
track.ukrposhta.ua
track.useswyft.com
track.yw56.com.cn
tracker.hivaids.gov.np
tracker.janio.asia
tracker.runtheedge.com
tracker.shadowfax.in
tracking.99minutos.com
tracking.ao.com
tracking.asendia.com
tracking.bring.com
tracking.dpd.de
tracking.dpd.ie
tracking.dpd.pt
tracking.expressone.hu
tracking.novaposhta.ua
tracking.packeta.com
tracking.parcelforce.net
tracking.phlpost.gov.ph
tracking.post.ir
tracking.shipnsd.com
tracking.wanbexpress.com

@hagezi

**Comment by hagezi** [comment]
**The data collection only contains raw data that should not be used as a block list!**. But I'll see if there's anything left in the ultimate. So please don't look for any FPs there, you will find some.

**Comment by hagezi** [comment]
Please ...

There is no point in searching in raw data - you will find the ones that have already been removed from the lists. Please don't make me work unnecessarily.
It is only the raw data for the generation of the block lists. I have made them available for documentation purposes.
