### ISSUE TITLE
Nike Store

### ISSUE THREAD

**Issue by azafrak** [hagezi/dns-blocklists#498]
#### What adblocker/DNS cloud service are you using?
NextDNS

#### Which blocklists are used?

Hagezi Multi Pro++

#### Which domain(s) should be unblocked?

cdn.optimizely.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

In order to reach the payment page of the product added to the cart in the nike store, I need to add this cdn service to the white list. Otherwise, the white page is waiting and the payment screen does not appear. You can add a product to the cart and test it yourself.

### Attacment
![Brahmancow](https://user-images.githubusercontent.com/30311445/220626285-d994d27d-490c-4c53-8aea-b7299b161c03.png)
![Waterdogs](https://user-images.githubusercontent.com/30311445/220626351-6afde0e6-aed7-46f0-ad57-dd17f21ca6a0.png)
![image](https://user-images.githubusercontent.com/30311445/220626503-2b1efe05-3699-4a96-9b32-960ca3f828aa.png)

**Comment by hagezi** [comment]
Thanks, checked, will be removed.
