### ISSUE TITLE
adjarabet.com

### ISSUE THREAD

**Issue by 836874** [hagezi/dns-blocklists#499]
#### What adblocker/DNS cloud service are you using?

disabled

#### Which blocklists are used?
Multi PRO++

#### Which domain(s) should be unblocked?
adjarabet.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
online casino and bookmaker
![Screenshot_20230222-220402](https://user-images.githubusercontent.com/124845740/220716999-fd619e88-d97d-48f8-b31e-b31a8128eaaa.png)

**Comment by hagezi** [comment]
@836874 Thanks, I tried to fix the site layout but I can't test it myself because the page is not accessible from my region (403). Please check it and give me a feedback.

**Comment by 836874** [comment]
> @836874 Thanks, I tried to fix the site layout but I can't test it myself because the page is not accessible from my region (403). Please check it and give me a feedback.

It works, thanks.

**Comment by hagezi** [comment]
Thanks for testing.
