### ISSUE TITLE
de.aukey.com false positive

### ISSUE THREAD

**Issue by Bertaz** [hagezi/dns-blocklists#5]
de.aukey.com is listed in [/data/black.list.fake.vzni](../blob/main/data/black.list.fake.vzni).
It's the german site for Aukey, directly linked on the US site [aukey.com](https://www.aukey.com).

The list source appears to be www.verbraucherzentrale-niedersachsen.de/vorsicht-falle which lists the de.aukey.com domain at www.verbraucherzentrale-niedersachsen.de/vorsicht-falle/deaukeycom-sitz-des-unternehmens-ist-china.
If the auto translation is correct the site is listed because Aukey is located in china, which is true, but I don't understands how that makes it a "fake shop"

**Comment by hagezi** [comment]
Thanks, fixed.
