### ISSUE TITLE
Torrent tracker announce domains being blocked

### ISSUE THREAD

**Issue by fishlvl** [hagezi/dns-blocklists#50]
In https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/personal.txt

I've noticed that these domains are on your list:

- tracker.beyond-hd.me
- tracker.animebytes.tv
- tracker.alpharatio.cc

These are bittorrent tracker announce urls for three different private trackers. I think these three - and I'm sure there are more that I haven't encountered - should be removed.

**Comment by hagezi** [comment]
Thank you, the torrent trackers have been removed. I will check my list again for more torrent trackers.
