### ISSUE TITLE
Fake Shop List

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#500]
#### Which domain(s) should be blocked?

https://www.toko999.shop/
https://toko999.net/
http://goshop.vin/
https://akulaku.me/
https://pasarbali-malls.com/
https://orami.cloud
https://orami.life
https://orami.one

#### Why should the domain(s) be blocked?

there have been many victims who spoke up, the site is a complete scam.
Evidence : 
https://www.trustpilot.com/review/www.toko999.shop
https://www.virustotal.com/gui/url/3bf1d9b3fb82c7a7a52d2947d2c86e0dabb51e330fcf5ea212ac6a298bf0ce2b
https://mediakonsumen.com/2023/01/16/surat-pembaca/penipuan-bisnis-online-mengatasnamakan-pt-akulaku-finance-akulaku-me
https://www.facebook.com/Pasarbali.id2020/posts/643605677772262
https://www.orami.co.id/magazine/hati-hati-terhadap-penipuan-yang-mengatasnamakan-orami

**Comment by hagezi** [comment]
Thanks, will check.

**Comment by hagezi** [comment]
Thanks, added to fake list.
