### ISSUE TITLE
Use List-KR instead of Youslist

### ISSUE THREAD

**Issue by piquark6046** [hagezi/dns-blocklists#52]
Please use [List-KR filter](https://github.com/List-KR/List-KR) instead of [Youslist](https://github.com/yous/YousList) replaced with List-KR in [uBlock Origin](https://github.com/gorhill/uBlock/commit/ed0f7ae3ce1fbc9445e5c9bca0890fb86ab3d0b9).
The number of List-KR commits is larger than the number of YousList commits.

Furthermore, List-KR filter is being supported by AdGuard Software Ltd. This can be proven by reading my GitHub profile.

**Comment by hagezi** [comment]
Thanks @piquark6046, added:
https://adguardteam.github.io/HostlistsRegistry/assets/filter_25.txt
