### ISSUE TITLE
[Suggestion] Split the DoH/VPN/TOR/Proxy Bypass list into 2 lists

### ISSUE THREAD

**Issue by HellboyPI** [hagezi/dns-blocklists#53]
Suggestion -> Split the DoH/VPN/TOR/Proxy Bypass list into 2 lists:
1) encrypted dns servers,
2) VPN/TOR/Proxy.

OR, don't change this list. Create a new list with dns servers only.

Reason:
For users who want to maintain control in their network with DNS blocking, but sometimes need a VPN (to bypass geo blocking for some content, to avoid social media blocks, for streaming...).

**Comment by hagezi** [comment]
Thank you, I prefer to create a separate DoH list. I will tackle this in the days to come.

**Comment by hagezi** [comment]
@HellboyPI

Please check the list: https://github.com/hagezi/dns-blocklists#bypass_dns

Thanls,
Gerd

**Comment by HellboyPI** [comment]
This is it. Thank You!

**Comment by hagezi** [comment]
Thanks, will check later.

**Comment by hagezi** [comment]
@HellboyPI 
Missing DoH domains have been added. Thanks for your support.
