### ISSUE TITLE
baixaki.com.br and api-2-0.spot.im

### ISSUE THREAD

**Issue by luis-oliveira92** [hagezi/dns-blocklists#539]
#### What adblocker/DNS cloud service are you using?

Pi-hole

#### Which blocklists are used?
Multi PRO

#### Which domain(s) should be unblocked?
api-2-0.spot.im
baixaki.com.br

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Baixaki.com.br is one of the oldest brazilian download websites, is there something wrong with it?
api-2-0.spot.im breaks IGN comments.

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by luis-oliveira92** [comment]
Hi, I just noticed that www.baixaki.com.br is being blocked too.

**Comment by hagezi** [comment]
Thanks, will be fixed after next full update.
