### ISSUE TITLE
Aquasana Website Breakage

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#540]
#### What adblocker/DNS cloud service are you using?

NextDNS, Block Page = Disabled, CNAME Flattening = Disabled

#### Which blocklists are used?
Pro++
Ultimate

#### Which domain(s) should be unblocked?
cdn1.affirm.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking this domain breaks the following webpages functionality. Clicking "From my existing faucet" near the middle of the page will result in the loading animation to loop.
Example: https://www.aquasana.com/under-sink-water-filters/

**Comment by hagezi** [comment]
Thanks, will be removed.
