### ISSUE TITLE
Microsoft Viva Insights

### ISSUE THREAD

**Issue by o42o** [hagezi/dns-blocklists#541]
#### What adblocker/DNS cloud service are you using?
I'm using NextDNS. Blockpage and CNAME flattening are disabled in the settings.

#### Which blocklists are used?

Ultimate

#### Which domain(s) should be unblocked?

agave.myanalytics.cdn.office.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

I'm using Microsoft Viva Insights. Since I have activate the Ultimate list in NextDNS, the service can no longer be used in Outlook. I have put this domain into the whitelist and now the service work again.
I can se with the details that it's the Ultimate list that block that domain.

Thank you for your work and your lists!

**Comment by hagezi** [comment]
Thanks, missed that, will be removed.

**Comment by o42o** [comment]
Thank you!
