### ISSUE TITLE
Karen Pryor Academy

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#545]
#### What adblocker/DNS cloud service are you using?

NextDNS, Block Page = Disabled, CNAME Flattening = disabled

#### Which blocklists are used?
Light
Normal
Pro
Pro++
Ultimate
Threat Intelligence Feeds

#### Which domain(s) should be unblocked?
karenpryoracademy.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
The Karen Pryor Academy is an Animal Training & Behavior school.

**Comment by hagezi** [comment]
Was apparently flagged by Google, will investigate.

**Comment by hagezi** [comment]
The domain is still on @elliotwutingfeng Google list:
https://raw.githubusercontent.com/elliotwutingfeng/Inversion-DNSBL-Blocklists/main/Google_hostnames_light.txt

but Google already classifies it as safe:
https://transparencyreport.google.com/safe-browsing/search?url=karenpryoracademy.com

It also does not appear to be flagged anywhere else:
https://www.virustotal.com/en/domain/karenpryoracademy.com/information/

```
Secure DNS:
 - CleanBrowsing OK
 - Cloudflare OK
 - CONTROLD.TIF OK
 - DNS0.eu OK
 - DNS0.eu.ZERO OK
 - NextDNS.TIF_AI OK
 - NRD.DGA.IDN OK
 - OpenDNS OK
 - Quad9 OK
 - SafeDNS OK
 - UltraDNS OK
```

Removing.
