### ISSUE TITLE
TIF Source Suggestions

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#547]
I don't see these lists under the TIF used sources or under "All known sources". Posting them here in the case you have not seen these before.

- https://github.com/RPiList/specials/blob/master/Blocklisten/Phishing-Angriffe (list is 12mb big)
- https://github.com/RPiList/specials/blob/master/Blocklisten/malware

These lists seem to be meta lists that may use sources already in the TIF. Sadly I'm on mobile right now and can't open the lists to investigate without my mobile browser hanging.

**Comment by hagezi** [comment]
Far too many false positives, lots of dead domains. I analysed the lists and decided not to include them.

**Comment by hagezi** [comment]
But I'll have another look at them, it's been a while since I examined them.
You can leave the issue open.

**Comment by hagezi** [comment]
checked, but still not usable for me.
