### ISSUE TITLE
Question regarding TIF list.

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#548]
Hi. 

I have set up NextDNS for some friends and family.
Mainly to block advertisements with minimal breakage so I've been using the Pro list. I have noticed some of them frequently request domains blocked by NextDNS TIF. I would like to block more of these malicious domains without breaking too much functionality.

I am wondering if you would ever make a version of the non-Ultimate blocklists (light, normal, pro, etc.) with your whole TIF included?

**Comment by hagezi** [comment]
The problem, to ensure compatibility for other AdBlockers is the magic limit around 500000 compressed entries. Example AdGuard iOS App. If I would use the TIF, which has over 700000 compressed entries, no list would be compatible anymore.
Therefore, the smaller lists get a TIF light version for phishing, malware and scam.

With the NextDNS security features and the TIF light you are well protected.
