### ISSUE TITLE
Bing Invitation not working on mobile devices

### ISSUE THREAD

**Issue by jostrasser** [hagezi/dns-blocklists#550]
#### What adblocker/DNS cloud service are you using?

NextDNS 

#### Which blocklists are used?
PRO

#### Which domain(s) should be unblocked?
app.adjust.io

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
"New Bing" invitation link in email from Microsoft is not working. The link is referring to the Bing iOS App in the AppStore.

**Comment by jostrasser** [comment]
Found out that this URL is from an App Tracker Company. The best will be to keep it blocked I think.

**Comment by hagezi** [comment]
Thanks, adjust is a tracker:
https://reports.exodus-privacy.eu.org/en/reports/com.adjust.insights/latest/
https://slayterdev.github.io/tracker-radar-wiki/entities/Adjust%20GmbH.html

But, `app.adjust.io` is only used as a [referral domain](https://github.com/hagezi/dns-blocklists#referral), other `app.adjust.*` are already on the referral whitelist. I will add them there. This one is missing.

**Comment by jostrasser** [comment]
Great, thanks Gerd!
