### ISSUE TITLE
Whitelist ping.ui.com

### ISSUE THREAD

**Issue by jostrasser** [hagezi/dns-blocklists#552]
#### What adblocker/DNS cloud service are you using?

NextDNS 

#### Which blocklists are used?
PRO

#### Which domain(s) should be unblocked?
ping.ui.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

ping.ui.com is the default for the internet connectivity monitor in the UniFi controller of Ubiquiti Inc. 

Blocking it will drop network connectivity alarms in the UNA application. 

ping.ui.com is a load balancing instance between 1.1.1.1 and 8.8.8.8

**Comment by hagezi** [comment]
Thanks, ping @notracking.

**Comment by jostrasser** [comment]
Hi @hagezi 
Is there an easy way to check of a URL is blocked by your lists?

Something like this (OISD):

![image](https://user-images.githubusercontent.com/14274103/221361928-4696f9f7-636f-41f7-bad7-c495223ddaa9.jpeg)

**Comment by hagezi** [comment]
@jostrasser 

https://dnswarden.com/search.html

https://rethinkdns.com/search

**Comment by jostrasser** [comment]
> @jostrasser 
> 
> https://dnswarden.com/search.html
> 
> https://rethinkdns.com/search
> 
> 

Thanks!
