### ISSUE TITLE
sdk.iad-03.braze.com and api2.branch.io

### ISSUE THREAD

**Issue by eskitium** [hagezi/dns-blocklists#553]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
Multi NORMAL

#### Which domain(s) should be unblocked?
*.sdk.iad-03.braze.com
*.api2.branch.io

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking them breaks access to TrueMoney Wallet, e-wallet application in Thailand, and some of its features.

**Comment by hagezi** [comment]
These are popular trackers

https://reports.exodus-privacy.eu.org/en/trackers/167/
https://reports.exodus-privacy.eu.org/de/trackers/17/

These I will not whitelist, is something for the personal whitelist.

I would ask the manufacturer why such trackers are necessary for the function of an app.
