### ISSUE TITLE
Guardian Videos not working

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#554]
#### What adblocker/DNS cloud service are you using?
AGH

#### Which blocklists are used?

Hagezi Pro Plus

#### Which domain(s) should be unblocked?

ophan.theguardian.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Videos from The Guardian not working

EDIT:
Looks like it needs more unblocking - actually videos from The Guardian are not working…

**Comment by hagezi** [comment]
I just had to whitelist `sourcepoint.theguardian.com`, tested with the Ultimate. Can you check this please @pictosun?

![grafik](https://user-images.githubusercontent.com/104343908/221375846-75e99188-ca3b-48d8-88c8-d5b3696bf5bf.png)

**Comment by hagezi** [comment]
ping sources: @sjhgvr @badmojr

**Comment by sjhgvr** [comment]
sourcepoint.theguardian.com fixed it for me as well, source; https://raw.githubusercontent.com/brave/adblock-lists/master/brave-lists/brave-firstparty.txt

**Comment by hagezi** [comment]
Thanks Stephan (@sjhgvr)
ping @brave, the rule `||sourcepoint.theguardian.com^` requires an exclusion.
