### ISSUE TITLE
PopAds

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#556]
#### Which domain(s) should be blocked?

1.  pitapbzumvwa.com
2.  strettechoco.com
3.  swanbxca.com
4.  pasadok.com

#### Why should the domain(s) be blocked?

PopAds, which redirects to malicious sites or sometimes redirects to ads heading to playstore.
I can reproduce this ads, see here https://pastebin.com/qXrUxXid except the last one.

**Comment by hagezi** [comment]
Thanks, will be added asap.
