### ISSUE TITLE
Phishing Campaign Domains (Further Analysis Required)

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#560]
#### Which domain(s) should be blocked?

singpost-vip.shop
singpot-mem.net
singpost-vip.com
singpost-info.shop
singpost-member.com
singpoost.com
sgpt-update.cc
updts.at
postjapan.net
update-id8154.com
auspost-au.net
singupdate.cc
auspost-tracking.cc
trackpost.me
new-tracking.com
trackingid9175.one
singpt-update.net
singpt-info.cc
singpt-update.com
singpost-sg.xyz
singpost-sg.online
next-pay.online
next-pay.xyz
next-pay.site
singpost-sg.site
postbank.de.ihre-de.com
sxb1plvwcpnl497368.prod.sxb1.secureserver.net

#### Why should the domain(s) be blocked?

Domains found by researchers as explained in this article: https://www.lookout.com/blog/singapore-post-singtel-phishing

I've yet to check if all these domains are resolving and if they are already blacklisted.

**Comment by hagezi** [comment]
Thanks, will be checked.

**Comment by hagezi** [comment]
Will be added.
