### ISSUE TITLE
Affiliate Links

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#561]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
HaGeZi - Multi PRO

#### Which domain(s) should be unblocked?
lt45.net
converti.se

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
https://lt45.net/c/?wi=222476&si=12971&li=1572060&ws=13004n1wkc3n&dl=pl%2Fproduct%2Fresident-evil-2-remake-ar-xbox-one
https://converti.se/click/c9e72ebe-59844f43-cc80faed/?sid=11004n647jcl&deep_link=https%3A%2F%2Fwww.morele.net%2Fwiejska-zagroda-przysmak-kurze-watrobki-80-g-7315707
Click "Idź do okazji" https://www.pepper.pl/promocje/resident-evil-2-xbox-oneseries-xs-kluczvpn-argentyna-649310 https://www.pepper.pl/promocje/wiejska-zagroda-przysmak-kurze-watrobki-80-g-649747

**Comment by hagezi** [comment]
Thanks, will be checked ...

**Comment by hagezi** [comment]
Will add it to the referral whitelist. ping source @notracking.

**Comment by notracking** [comment]
Thanks! Fixed.
