### ISSUE TITLE
insights.samsung.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#562]
Hi.

Is there a reason `insights.samsung.com` isn't blocked?

The domain isn't dead and l don't see it in the whitelist. It's blocked by 1Host, StevenBlack and NoTracking.

**Comment by hagezi** [comment]
Samsung Business Insights : https://insights.samsung.com/
Why would that be blocked?

**Comment by hagezi** [comment]
Thanks @jarelllama

**Comment by notracking** [comment]
Thanks! Added to the whitelist.
