### ISSUE TITLE
stearncommunjty.net

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#563]
#### Which domain(s) should be blocked?

stearncommunjty.net

#### Why should the domain(s) be blocked?

https://www.reddit.com/r/DotA2/comments/10zj0ty/fyi_new_phishing_scam_i_encountered_which_i/

stearncommunjty.net doesn't seem to have a webpage but stearncommunjty.net/profiles is some weird coding page in Russian.

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
Scam, NRD, will be added.

**Comment by durablenapkin** [comment]
Queued, thanks!
