### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#568]
#### Which domain(s) should be blocked?

```
husqvarnaoutlet.shop
www.husqvarnaoutlet.shop
uscampinghiking.com
www.uscampinghiking.com
onlineadid.com
www.onlineadid.com
bedchichome.com
www.bedchichome.com
```

#### Why should the domain(s) be blocked?

https://www.reddit.com/r/Scams/comments/11dhm9j/wwwbedchichomecom_is_a_scam_part_of_larger_scam/

All the sites' designs are a copy of husqvarnaoutlet.shop.

husqvarnaoutlet.shop seems to be a fake site posing as the genuine husqvarna.com.

The domain names themselves redirect to the www subdomain.

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued for next nightly update, thanks!
