### ISSUE TITLE
*.onlinehome.us

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#569]
#### Which domain(s) should be blocked?

*.onlinehome.us

#### Why should the domain(s) be blocked?

The subdomains of this domain are used in phishing campaigns. The domain itself does not lead to any webpage.

I see the domain is already blocked as a wildcard in the Pro++ and Ultimate lists. I think it should be included in the other lists too as it doesn't look like the domain and subdomains have any legitimate use.

**Comment by hagezi** [comment]
Yes, thanks, you are right, I missed that. ;)
