### ISSUE TITLE
[Suggestion] Include DDNS in the Multi lists

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#57]
What's the rationale for not including the `Dynamic DNS blocking` list with the `Multi` lists? We are [already including](https://github.com/hagezi/dns-blocklists#multi-blocklist-version-and-size-overview) `Threat Intelligence Feeds` list. Should we not also add DDNS protection so that users don't need to add a separate list?

**Comment by hagezi** [comment]
The DDNS block list contains only the parent domains (FLDs) of the DynDNS providers. Example:

`duckdns.org`

The TIF list contains only known subdomains (SLDs) of the DynDNS providers that have been classified as dangerous:

```
dfkklsf.duckdns.org
sdjhjasd.duckdns.org
d777wh.duckdns.org
...
```

So, if you use DDNS blocklist, you block full access to DDNS provider - parent domain including all subdomains (`*.duckdns.org`).
Of course this only works in adblockers that support this wildcard blocking, e.g. AdGuard, but not in Pi-hole.

There are users who use these DDNS services for legal access to their home network. So DynDNS is basically not evil.

So it is obvious why the list is not included in the other blocklists. Every user can decide for himself if he wants to block DDNS completely or not.

**Comment by yokoffing** [comment]
Thank you for clarifying!
