### ISSUE TITLE
uk-wemakewebsites.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#570]
#### Which domain(s) should be blocked?

```
uk-wemakewebsites.com
www.uk-wemakewebsites.com
```

#### Why should the domain(s) be blocked?

https://www.reddit.com/r/Scams/comments/11cqfj6/hey_first_time_dealing_with_this_is_it_real/

Seems to be a fake site of the genuine https://wemakewebsites.com/

Both the domain and www subdomain lead to the same page.

**Comment by hagezi** [comment]
ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued for next nightly update, thanks!
