### ISSUE TITLE
virgo-eth.net

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#571]
#### Which domain(s) should be blocked?

```
virgo-eth.net
www.virgo-eth.net
```

#### Why should the domain(s) be blocked?

Crypto scam. 

https://www.reddit.com/r/Scams/comments/11c4y3g/is_this_website_a_scam_virgoethnet/

https://www.reddit.com/r/Scams/comments/11c4y3g/is_this_website_a_scam_virgoethnet/ja2u9rh/

Both domain and www subdomains leads to the same page.

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks :)
