### ISSUE TITLE
pertinacious-assemblage.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#572]
#### Which domain(s) should be blocked?

```
pertinacious-assemblage.com
www.pertinacious-assemblage.com
```

#### Why should the domain(s) be blocked?

Scam dating site.

NRD: https://www.whois.com/whois/pertinacious-assemblage.com

Asks for credit card and CVC for registration: https://pertinacious-assemblage.com/register.php

Links at the bottom of the page (Terms, Privacy, FAQ) merely goes to the top of current page.

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks again :)
