### ISSUE TITLE
Whitelist youtube.com

### ISSUE THREAD

**Issue by IREK-szef** [hagezi/dns-blocklists#573]
#### What adblocker/DNS cloud service are you using?

Adguard home

#### Which blocklists are used?
[Anti Piracy](https://github.com/hagezi/dns-blocklists#piracy)

#### Which domain(s) should be unblocked?
youtube.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
I don't think I need to explain it ;)

**Comment by hagezi** [comment]
Wait, what? Youtube is not piracy? Fun, I haven't cleaned up yet. Thanks ...
