### ISSUE TITLE
nalzahqp.page.link

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#574]
#### Which domain(s) should be blocked?

nalzahqp.page.link

#### Why should the domain(s) be blocked?

Malicious file download.

https://www.reddit.com/r/Scams/comments/119zjyw/is_this_possible_scam_messaged_me_thru_artstation/

https://www.reddit.com/r/Scams/comments/119zjyw/is_this_possible_scam_messaged_me_thru_artstation/j9pxqjt/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks!
