### ISSUE TITLE
syn.alias.com

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#575]
#### What adblocker/DNS cloud service are you using?

Adguard Home

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?

syn.alias.com
#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is blocking via cname auth.hbogo.com which is needed to auth hbomax.com, I suppose just this domain could be whitelisted, I am currently whitelisting the auth.hbogo.com only.

**Comment by hagezi** [comment]
Thanks, will be removed.
ping source @badmojr
