### ISSUE TITLE
newfootwearshop.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#577]
#### Which domain(s) should be blocked?

```
newfootwearshop.com
www.newfootwearshop.com
```

#### Why should the domain(s) be blocked?

Scam. https://www.reddit.com/r/Scams/comments/11eizsy/beware_newfootwearshopcom_scammed_me/
https://www.reddit.com/r/Scams/comments/11eizsy/beware_newfootwearshopcom_scammed_me/jaemw45/

**Comment by hagezi** [comment]
Thanks, ping@durablenapkin
