### ISSUE TITLE
lootcs.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#578]
#### Which domain(s) should be blocked?

```
lootcs.com
www.lootcs.com
 ```

#### Why should the domain(s) be blocked?

Scam/Steam login phishing. https://www.reddit.com/r/Scams/comments/11eg8wd/steam_lootcscom_scam_fake_steam_login_page_beware/

**Comment by hagezi** [comment]
Thanks, ping@durablenapkin
