### ISSUE TITLE
[adblock rules] automatic update not working

### ISSUE THREAD

**Issue by dnmTX** [hagezi/dns-blocklists#58]
Hi @hagezi 👋  I just loaded the Dynamic DNS blocking in Adguard DNS filter and it seems that some adjustments are needed in order to be updated regularly. This is what is showing on my end:

![Capture](https://user-images.githubusercontent.com/34774426/201153002-b108c0f5-d92f-42e4-9b3b-294fbd5ae021.PNG)

As i'm not very familiar what exactly needs fixing i hope @ameshkov won't mind pitching in with some advise 👍 
Hoping that this will get resolve soon! Thank you 👍 

P.S. Just FYI. AdGuard's DNS filter uses the same syntax as the adblocking rules!

**Comment by ameshkov** [comment]
Definitely looks like an our issue, not the list's.

**Comment by dnmTX** [comment]
@ameshkov thanks for pitching in and clarification 👍 I guess will wait for fix in the upcoming update.
Closing this as it's not a list's issue.

**Comment by hagezi** [comment]
Thanks @dnmTX @ameshkov .

**Comment by ameshkov** [comment]
@dnmTX but please open it on our repo:)
