### ISSUE TITLE
Pull Request to Include TIF into NextDNS?

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#580]
Hi.

I'm wondering if you'd ever consider creating a pull request to add your TIF into the NextDNS list of blocklists? I saw you asked if your TIF could be included into the NextDNS TIF and it got rejected. If it made it into the list of blocklists that would be as great.

**Comment by hagezi** [comment]
https://github.com/nextdns/metadata/issues/1195

**Comment by hagezi** [comment]
It is included in ultimate ...

**Comment by hagezi** [comment]
They do not include TIF-only lists in their blocklists. Not in their TI feeds and not as a blocklist. So, no chance.

**Comment by hagezi** [comment]
@jarelllama ... and thanks for your support and cooperation here. I am glad about it.
