### ISSUE TITLE
`cliqz.com`

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#581]
#### What adblocker/DNS cloud service are you using?

uBO, Control D

#### Which blocklists are used?
Pro++, Ultimate

#### Which domain(s) should be unblocked?
`cliqz.com`

Test: https://cliqz.com/en/magazine

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Website of the former CLIQZ browser. Blogs and resource material still useful. What source blocked this?

**Comment by hagezi** [comment]
Thanks, currently it is not on any source, originally it was on 1Hosts and is on my aggressive blacklist for whatever reason. Will be removed.

**Comment by yokoffing** [comment]
Thanks!
