### ISSUE TITLE
public.am.files.1drv.com

### ISSUE THREAD

**Issue by IbraheemEhab** [hagezi/dns-blocklists#583]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
HaGeZi - Multi NORMAL and HaGeZi - Multi PRO.

#### Which domain(s) should be unblocked?
public.am.files.1drv.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It prevents me from loading my files into my password manager

**Comment by hagezi** [comment]
Thanks, blocked in TIF, will be removed asap.
