### ISSUE TITLE
imgix.datadoghq.com

### ISSUE THREAD

**Issue by nezlobnyj** [hagezi/dns-blocklists#586]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
imgix.datadoghq.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Serves image assets on Datadog documentation website.

**Comment by hagezi** [comment]
Thanks, will be removed. ping source @badmojr
