### ISSUE TITLE
Did I repeat my rule selection?

### ISSUE THREAD

**Issue by biange200** [hagezi/dns-blocklists#587]
![Screenshot_20230302_174414.jpg](https://user-images.githubusercontent.com/37582806/222401197-417792af-dabd-4ed5-aa0d-4b744773d6a1.jpg)

Hello! I want to ask you, your rules include the two rules I chose above? Is there any difference between choosing other rules alone and choosing your rules together?

Do you have any good suggestions for me?

**Comment by hagezi** [comment]
Anti Ad ist included, rentianyu not, but the sources he uses are already covered by other sources i use. I would say with the Ultimate alone you are good to go.

**Comment by biange200** [comment]
> Anti Ad ist included, rentianyu not, but the sources he uses are already covered by other sources i use. I would say with the Ultimate alone you are good to go.

Thank you for your reply, that is to say, the above two rules can be closed and only your ultimate can be used.
