### ISSUE TITLE
aldi-life.vip

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#588]
#### Which domain(s) should be blocked?

aldi-life.vip

#### Why should the domain(s) be blocked?

Pyramid scheme. https://www.reddit.com/r/Scams/comments/11fv6kr/do_not_invest_into_aldilifevip_its_scam_they_dont/

The site uses logos of the grocery store company Aldi. Genuine site: https://www.aldi.us/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks!
