### ISSUE TITLE
mail.office.hiworks.com

### ISSUE THREAD

**Issue by bestplayerbotphone** [hagezi/dns-blocklists#589]
#### What adblocker/DNS cloud service are you using?

uBlock Origin

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
mail.office.hiworks.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
email

**Comment by hagezi** [comment]
Thanks, ping source @notracking

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
