### ISSUE TITLE
Can you include this list

### ISSUE THREAD

**Issue by xenstar** [hagezi/dns-blocklists#59]
Hi, I love your idea, and thanks for creating so many varieties of blocklists.

I have been using this for a few months, can you also include this list so the common domains that are not included in the list? If you add to your list, I will then remove my adguard home and use your list only. 

https://github.com/jerryn70/GoodbyeAds

**Comment by xenstar** [comment]
And this one too - https://anti-ad.net/easylist.txt

**Comment by hagezi** [comment]
Hi,

thank you, you can provide me with your lists, I will then look at whether they provide added value.

But it's not the number of sources used that matters, it's what comes out in the end, the final product should be effective and efficient.
I have examined many lists in detail over months, some are poorly maintained, have lots of dead and false positive domains. In short, they don't add much value, they just inflate the blocklist.
Together with my maintained blacklists I found a good combination with the sources used.
I claim not much blockable is missing in the lists. I put a lot of work into compiling the lists. They are not just lists compiled from existing sources.

To keep the lists compatible with all adblockers, I have to pay attention to the size. Approximately 500,000 compressed domains is the limit for Adblock, for example. The Pro++ list is close to the limit. 

Furthermore, the lists are intended for the masses maximum blocking without limiting functionality.

There are people who have 5,000,000 domains in their blocklist, but less block rate as with the Pro++. Less is sometimes more.

Kind Regards,
Gerd

**Comment by xenstar** [comment]
"There are people who have 5,000,000 domains in their blocklist, but less block rate as with the Pro++. Less is sometimes more."

I completely agree with you. 

Here are some of the lists I am using, but I am sure there are duplicate domains here as well. 

OISD ABP I also use, but that's already included in your list. 

Anti-Ad (Mostly blocks Chinese adverts/trackers) - https://anti-ad.net/easylist.txt

Chinese Domestic Video Websites (Block ads in domestic website) - https://raw.githubusercontent.com/z44499783/ChinaList2.0/master/ChinaList2.0.txt 

Mostly Chinese Websites adverts and trackers - https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt

https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

This one primarily blocks smart-tv adverts - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt


Adguard Cname Blocker - https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt

Goodbye Ads - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt

Youtube Ads - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt

Cat Rules - https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt

**Comment by hagezi** [comment]
Domains from the following lists are already included by used sources or own blacklists:

> This one primarily blocks smart-tv adverts - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
> Adguard Cname Blocker - https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt

You can't block Youtube ads via DNS, using such lists will cause some videos not to load or to break during playback. To block Youtube ads, browser content blockers are the right choice:

> Youtube Ads - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt

I will probably include the following list:

> https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

I'll take a closer look at the other lists.

**Comment by hagezi** [comment]
The following list provides only 5 extractable domains that are already included in my lists, it has significant filtering rules for content blockers:

> Chinese Domestic Video Websites (Block ads in domestic website) - https://raw.githubusercontent.com/z44499783/ChinaList2.0/master/ChinaList2.0.txt

**Comment by hagezi** [comment]
Following list has 42168 dead domains, 11957 safe whitelisted domains and 181172 domains are already on pro++ list. The remaining domains do not add value to my lists:

> Goodbye Ads - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt

**Comment by hagezi** [comment]
Checked the other lists:

Anti-Ad : will add 2032 missing/active domains.
Chinese Domestic Video Websites: will add 232 missing/active domains.
Cat Rules: will add 15 missing/active domains.

**Comment by xenstar** [comment]
Hello, 

Thanks for the update. So the pro++ list is this one, right?

![image](https://user-images.githubusercontent.com/55502651/201482277-c1be75c4-c329-44ce-b044-5983a1b7bcc9.png)


Also, can you confirm, 

Anti-Ad : will add 2032 missing/active domains.
Chinese Domestic Video Websites: will add 232 missing/active domains.
Cat Rules: we will add 15 missing/active domains.

If in the future, these lists add some new domains, they will be added to your pro++ list automatically, right?

**Comment by hagezi** [comment]
Yes, I am currently working on an automatic integration of the 3 lists. Currently, I have only taken over the missing domains. I'll let you know when the automatic integration is implemented.

The antiadblock list is already taken over automatically.

**Comment by xenstar** [comment]
alright. thanks.

and where can I report whitelist of some domain?

e.g I just added your pro+ list and https://appsumo.com/ domain was blocked. But it's a very nice Lifetime deal website.

**Comment by hagezi** [comment]
For a whitelist request you can simply open an issue. Since you reported it here, I have already removed the domain from the lists.

**Comment by hagezi** [comment]
Autoupdate implemented. Closing ...

**Comment by Lixar91** [comment]
Hello!

I would like to ask if you use any blocking filter such as this one: https://github.com/bogachenko/fuckfuckadblock

It aims to block all pop-ups asking you to disable your ad-block and bypass anti-adblock techniques. I'm not pretty sure if there are other filters that do the same job, but, in case you don't know it, here it is.

Thanks for your titanic job @hagezi! ❤️

**Comment by hagezi** [comment]
Hi @Lixar91

It is a pure content blocker list that does not contain extractable rules for DNS:

```
curl -sL https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt | grep -Pc '^\|\|.+\^$'
0
```

I could take over the mining list:

```
curl -sL https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt | grep -Pc '^\|\|.+\^$'
160
```
