### ISSUE TITLE
torrentdia93.com

### ISSUE THREAD

**Issue by bestplayerbotphone** [hagezi/dns-blocklists#590]
#### Which domain(s) should be blocked?
torrentdia93.com
torrentdia94.com
torrentdia95.com
torrentdia96.com
torrentdia97.com
torrentdia98.com
torrentdia99.com
torrentdia100.com
torrentdia101.com
torrentdia102.com
torrentdia103.com
torrentdia104.com
torrentdia105.com
torrentdia106.com
torrentdia107.com
torrentdia108.com

#### Why should the domain(s) be blocked?
torrentdia92.com is no longer used

**Comment by bestplayerbotphone** [comment]
for the anti-piracy list

**Comment by hagezi** [comment]
Thanks, will be added.
