### ISSUE TITLE
behance.net

### ISSUE THREAD

**Issue by o42o** [hagezi/dns-blocklists#593]
#### What adblocker/DNS cloud service are you using?

I'm using NextDNS. Blockpage and CNAME flattening are disabled in the settings.

#### Which blocklists are used?

Ultimate

#### Which domain(s) should be unblocked?

mir-s3-cdn-cf.behance.net or *.behance.net?

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

The images on the site don't show up unless you whitelist that URL. I don't go to the site often, so I don't know if it uses other URLs, but I guess it does by looking at "mir-s3-cdn-cf".

Thank you!

**Comment by hagezi** [comment]
Thanks, will be removed. Ping source @migueldemoura

**Comment by migueldemoura** [comment]
Thanks, fixed in https://github.com/migueldemoura/ublock-umatrix-rulesets/commit/4326b40c5152e14d3db65cd81441b2a3d5056327.
