### ISSUE TITLE
nirvezal.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#594]
#### Which domain(s) should be blocked?

nirvezal.com

#### Why should the domain(s) be blocked?

Scam. The main domain leads to a Bengali site that seems to be a placeholder. The site's FAQ and Privacy Policy lead to a 404 page. Pressing "Place Order" also leads to a 404 page.

Directories of the domain are used in phishing scams: https://www.reddit.com/r/Scams/comments/11gd8nd/is_this_a_scam_i_have_some_packages_supposed_to/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
