### ISSUE TITLE
goldtimeinvest.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#595]
#### Which domain(s) should be blocked?

goldtimeinvest.com

#### Why should the domain(s) be blocked

Crypto scam.

https://www.reddit.com/r/Scams/comments/11g8l28/scammers_trying_to_get_you_to_deposit_your/

https://www.reddit.com/r/Scams/comments/11g8l28/scammers_trying_to_get_you_to_deposit_your/janoq2p/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
