### ISSUE TITLE
t-post.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#598]
#### Which domain(s) should be blocked?

t-post.com

#### Why should the domain(s) be blocked?

Scam. Blocked by NextDNS AI Threat Detection 

https://www.reddit.com/r/Scams/comments/lwgc9b/is_t_post_mag_legit/

https://www.reddit.com/r/Scams/comments/wfesrc/tpost_is_scam_do_not_trust/

**Comment by durablenapkin** [comment]
Will add this and the others, thanks!
