### ISSUE TITLE
Native Ads [macaw.is]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#600]
#### Which domain(s) should be blocked?
macaw.is

#### Why should the domain(s) be blocked?
Well, this company ads redirecting users (from their ads) to fake news site. They attract viewer to click the ads usually use clickbait images.

And often appears on google amp mode even though using Brave Android Adblock.

**Comment by hagezi** [comment]
Thanks, will be added.
