### ISSUE TITLE
Cannot Add Referral Whitelist to Pihole

### ISSUE THREAD

**Issue by AAraonWPaul** [hagezi/dns-blocklists#601]
Hagezi, your referral whitelist cannot be imported to pihole, since it contains * in some of the domains.

**Comment by hagezi** [comment]
That is correct, it is also not a whitelist for Pi-hole. It is used to remove referral domains or patterns from my lists during the build process.

**Comment by MiguVT** [comment]
I tried and still not working, idk if mb but it puts (PI-Hole) like it supported but it isnt
![Image](https://github.com/user-attachments/assets/79a51101-1463-46b0-b9e1-1983777e05d2)

**Comment by MiguVT** [comment]
![Image](https://github.com/user-attachments/assets/50290607-16c9-434b-8966-e171d4da49d0)

**Comment by hagezi** [comment]
@MiguVT You need Pi-hole v6 for this, the version is still in beta and not released.

**Comment by hagezi** [comment]
@MiguVT Pi-hole nightly:

![Image](https://github.com/user-attachments/assets/5a6a158f-9055-45b8-b373-7def25329e8d)

![Image](https://github.com/user-attachments/assets/5c6e3fc5-627a-4cde-8b22-cfa19816b0f8)

![Image](https://github.com/user-attachments/assets/3b7a2bb5-b1f7-4260-9ca3-75deb0e32459)

**Comment by MiguVT** [comment]
Oh ok, tysm, ik it's a beta but it's stable??
