### ISSUE TITLE
Whitelist zadn.vn

### ISSUE THREAD

**Issue by gnadgnaoh** [hagezi/dns-blocklists#602]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?

Pro Plus

#### Which domain(s) should be unblocked?

zadn.vn

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Block it prevent Zalo app loading image

**Comment by hagezi** [comment]
Thanks, will be removed. ping @bongochong.

**Comment by bongochong** [comment]
Thanks for the ping! Remedying this immediately.
