### ISSUE TITLE
maxearningcryp.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#603]
#### Which domain(s) should be blocked?

maxearningcryp.com

#### Why should the domain(s) be blocked?

Crypto get-rich-quick scam: https://www.reddit.com/r/Scams/comments/11hoafb/is_this_wwwmaxearningcrypcom_a_scam_wanted_to/

Site requires sending crypto for KYC validation.

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by andryou** [comment]
Queued to add this and #604, thanks!

**Comment by durablenapkin** [comment]
Queued to add this and #604, thanks!
