### ISSUE TITLE
Malicious Sites

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#604]
#### Which domain(s) should be blocked?

czwcvfbc.page.link
tpqcywcx.page.link

#### Why should the domain(s) be blocked?

Same scam/malicious file download as #574 but with different subdomains.

https://www.reddit.com/r/Scams/comments/11dmylm/i_scanned_the_url_and_it_wasnt_marked_as/

https://www.reddit.com/r/Scams/comments/116xymy/suspicious_message_and_url_from_artsation_more/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
