### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#605]
#### Which blocklists are used?
NextDNS - Cname Disable
HaGeZi - Multi PRO++
HaGeZi - Multi ULTIMATE 

Broken Sites
arsiv.mackolik.com
mackolik.com

False Positive
mr.mc.cubecdn.net
socket.mc.cubecdn.net
secure.cache.images.core.optasports.com

Broken Sites
334kingbetting.com

False Positive
statistics.bcapps.org
vue.comm100.com
cmsbetconstruct.com
eu-swarm-newm.betcoswarm.com

**Comment by hagezi** [comment]
@norilana What is not working due to blocking, please describe in more detail.

In future please open a new issue, this one was already closed.
