### ISSUE TITLE
Scam & Fraud

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#606]
#### Which domain(s) should be blocked?
fms88.shop <- scam/fraud, confirmed.
evidence :
https://www.facebook.com/groups/188766661163915/posts/8611943742179456/

oneparttimejob.com <- scam/fraud, suspected but most likely.
evidence :
https://www.facebook.com/groups/826359317490446/posts/5052565721536430/

jne-express.my.id <- stealing personal information, confirmed.
evidence :
https://twitter.com/silverboys_mate/status/1630762454597922817

h5.vjrniqwekq.com <- scam/fraud, confirmed.
evidence:
https://www.facebook.com/groups/188766661163915/posts/8657715214268975/

bcm8.shop <- scam/fraud, same operation like fms88.shop.

moneymm1688.shop <- scam/fraud, same operation like fms88.shop.

ajdta.com <- fakeshop, impersonate jd.id (the official store is no longer operating or closed).
evidence:
https://scontent-xsp1-1.xx.fbcdn.net/v/t39.30808-6/325350527_544950204237270_3292926409157430137_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=dbeb18&_nc_ohc=rzPnS6qBf50AX8gyzhe&_nc_ht=scontent-xsp1-1.xx&oh=00_AfBPWxTeXr8PZMdkOdED8YhsQCJ_60wcJ6nifdRH8wdeQA&oe=64087B52

wind88.shop <- scam/fraud, same operation like fms88.shop.

tdgrop168.vip <- scam/fraud, same operation like fms88.shop.

#### Why should the domain(s) be blocked?
See above..

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued all, thanks!
