### ISSUE TITLE
click.discord.com blocked

### ISSUE THREAD

**Issue by Xandar-YT** [hagezi/dns-blocklists#607]
What adblocker/DNS cloud service are you using? NextDNS
Which blocklists are used? Multi Ultimate
Which domain(s) should be unblocked? click.discord.com
Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce. It's an official Discord domain used for confirming logging in on a new IP address. It's necessary to be able to log in on a new location.

**Comment by hagezi** [comment]
Thanks, will be removed. ping @bongochong

**Comment by bongochong** [comment]
This is from [PGL Yoyo / Peter Lowe](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext). Tends to block some eMail and click tracking links in his lists with the occasional false-positive slipping in. Will remove. Might want to check his list for other `click.` domains, as I will be doing. Will report upstream as well.

**Comment by bongochong** [comment]
P.S. Check [this commit](https://github.com/bongochong/CombinedPrivacyBlockLists/commit/b7b924cac4d2b0822729380e2429f21ac41c1d45) for three other relevant exclusions I just added to my whitelist.

**Comment by hagezi** [comment]
Many Thanks @bongochong

**Comment by bongochong** [comment]
Likewise!

**Comment by Xandar-YT** [comment]
Thanks for removing this and for making the best blocklist on the internet!
