### ISSUE TITLE
buyfingermoney.company.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#608]
#### Which domain(s) should be blocked?

buyfingermoney.company.com

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11i8cod/pet_scam_beware/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks!
