### ISSUE TITLE
nichibenren.or.jp

### ISSUE THREAD

**Issue by yuuki76** [hagezi/dns-blocklists#610]
#### What adblocker/DNS cloud service are you using?

uBlock Origin

#### Which blocklists are used?
Normal

#### Which domain(s) should be unblocked?
nichibenren.or.jp

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Japan Federation of Bar Associations(Nichibenren) is an association of lawyers established under Japanese law. It is a legitimate website and should be removed.
https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E5%BC%81%E8%AD%B7%E5%A3%AB%E9%80%A3%E5%90%88%E4%BC%9A

**Comment by bestplayerbotphone** [comment]
I think or.jp is only used by the government so *.or.jp should be allowed same with *.or.kr

**Comment by hagezi** [comment]
Thanks, will be removed.
