### ISSUE TITLE
instant-e-app-for-campaign.github.io

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#612]
#### Which domain(s) should be blocked?

instant-e-app-for-campaign.github.io

#### Why should the domain(s) be blocked?

Fake bank scam: https://www.reddit.com/r/Scams/comments/11irptl/how_to_report_these_rampant_scam_hosting_their/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
