### ISSUE TITLE
astoriajob.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#613]
#### Which domain(s) should be blocked?

astoriajob.com

#### Why should the domain(s) be blocked?

Scam: 
https://www.reddit.com/r/Scams/comments/11iokcp/astoriajobcom_is_a_scammed_please_someone_stop/jazfvax/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued this and #612
