### ISSUE TITLE
gig-os.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#619]
#### Which domain(s) should be blocked?

gig-os.com

#### Why should the domain(s) be blocked?

Scam:
https://www.reddit.com/r/Scams/comments/11iur3b/mother_is_falling_for_pyramid_scheme/jb02e53/

 https://www.reddit.com/r/Scams/comments/11iur3b/mother_is_falling_for_pyramid_scheme/jb02ofk/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
