### ISSUE TITLE
Question About Subdomains

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#620]
Hi.

I read Pihole can't use wildcards in a blocklist.

Does this mean if `scam.com` is on your list `www.scam.com` won't be blocked?

I would love to test it out myself but I haven't had my Pihole running in a while.

**Comment by hagezi** [comment]
Yes, for Pi-hole must include the subdomains, including www. This is done in my build process. The missing subdomains are extracted from other lists and from toplists, see also:
https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#subdomains
