### ISSUE TITLE
spring-oreo.itracmediav4.com

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#621]
#### What adblocker/DNS cloud service are you using?
ControlD

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
spring-oreo.itracmediav4.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Received a bill email from my home gas company (I modified uuid and linkid values), used https://www.expandurl.net/expand to track the URLs:

```
    https://pubssl.itmems4.com/itmspring/r?uuid=123&linkid=abc
    https://spring-oreo.itracmediav4.com/r?uuid=123&linkid=abc
    http://www.enbridgegas.com/login
    https://www.enbridgegas.com/login
    https://myaccount.enbridgegas.com/sign-in
```

![Screenshot_2023-03-05_13-02-44](https://user-images.githubusercontent.com/57188837/222977731-7dbb8477-3554-49ff-8067-0496537325b1.png)

**Comment by hagezi** [comment]
Thanks, ping source @sjhgvr

**Comment by hagezi** [comment]
Thanks, will be removed.
