### ISSUE TITLE
mythicalbattle.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#622]
#### Which domain(s) should be blocked?

mythicalbattle.com

#### Why should the domain(s) be blocked?

Steam login phishing: https://www.reddit.com/r/phishing/comments/1143ne6/is_this_a_steam_phishing_page/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

**Comment by durablenapkin** [comment]
Thanks! Queued this and the others
