### ISSUE TITLE
zolrqw.palatlaldate.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#626]
#### Which domain(s) should be blocked?

zolrqw.palatlaldate.com

#### Why should the domain(s) be blocked?

Scam/Malicious URL: https://www.reddit.com/r/Scams/comments/11jmoh4/guys_is_this_a_scam_or_something_else_should_i/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
