### ISSUE TITLE
pateim.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#627]
#### Which domain(s) should be blocked?

pateim.com

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11jesfz/pateimcom_real_or_scam/jb2e44k/

https://www.reddit.com/r/Scams/comments/11jesfz/pateimcom_real_or_scam/jb2fi0s/

https://www.reddit.com/r/Scams/comments/11jesfz/pateimcom_real_or_scam/jb2dnwa/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin
