### ISSUE TITLE
telemetry.vg.ac.pvp.net (Further Analysis Required)

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#629]
#### Which domain(s) should be blocked?

telemetry.vg.ac.pvp.net

#### Why should the domain(s) be blocked?

Riot Games telemetry. Only blocked in HaGeZi Ultimate and [GoodbyeAds](https://github.com/jerryn70/GoodbyeAds).

Further analysis probably required.

**Comment by hagezi** [comment]
Thanks, I haven't really found anything on the net. Someone here who can trigger / test that for me?

**Comment by hagezi** [comment]
Thanks.

**Comment by hagezi** [comment]
@jarelllama any updates?
