### ISSUE TITLE
incorporate VXVault into TIF

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#63]
For [TIF](https://github.com/hagezi/dns-blocklists#threat-intelligence-feeds---increases-security-significantly-), we are using the domains version of iam-py-test's [The malicious website blocklist](https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/Alternative%20list%20formats/antimalware_domains.txt).

But this does not include the VXVault list , which is in the original, adblock formatted list (via `!#include mirrored/vxvault_filter.txt`:
https://github.com/iam-py-test/my_filters_001/blob/1387798ab61b472bfef0783549a1314feb42c084/antimalware.txt#L15487-L15489

https://github.com/iam-py-test/my_filters_001/blob/1387798ab61b472bfef0783549a1314feb42c084/special_lists/anti-malware-ubo-extension.txt#L232-L235

Links:
- VXVault filter [repo](https://github.com/iam-py-test/vxvault_filter)
- VXVault filter [for uBlock Origin](https://github.com/iam-py-test/my_filters_001/blob/main/special_lists/mirrored/vxvault_filter.txt) (adblock list)

**Comment by hagezi** [comment]
Thanks for the tip, will include the domains version:
https://raw.githubusercontent.com/iam-py-test/vxvault_filter/main/domains_file.txt

**Comment by hagezi** [comment]
added, thanks for your support!

**Comment by dnmTX** [comment]
@yokoffing the `$all` modifier when used with AdGuard doesn't block everything from the specific domain.
You can read about it here:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#:~:text=iOS%20and%20Safari.-,all,%27unsafe%2Deval%27%20http%3A%20https%3A%20data%3A%20blob%3A%20mediastream%3A%20filesystem%3A%0A%7C%7Cexample.org%5E,-cookie

Also rule like: `||103.145.253.70^$all` will do nothing. For IP blocking (in AdGuard at least) the proper modifier would be `$network` aka `103.145.253.70$network`

Overall,that list is pretty much useless!

**Comment by yokoffing** [comment]
@dnmTX, I'm aware of basic adblocking syntax. If you review the primary sources, you'll see that the list is intended for uBlock Origin...

Also, it doesn't matter for this repo: This list will be aggregated with the others and be reformatted for their [target format](https://github.com/hagezi/dns-blocklists#threat-intelligence-feeds---increases-security-significantly-).

**Comment by dnmTX** [comment]
uBlock Origin and AdGuard are pretty much inline with their modifiers,this way they can exchange their lists.
Maybe you need to read first before you start arguing for the sake of arguing !!!!!!

**Comment by yokoffing** [comment]
> uBlock Origin and AdGuard are pretty much inline with their modifiers,this way they can exchange their lists.

In many ways, yes.

> Maybe you need to read first

My second point still stands: "This list will be aggregated with the others and be reformatted for their [target format](https://github.com/hagezi/dns-blocklists#threat-intelligence-feeds---increases-security-significantly-)." The original formatting does not matter for our purposes.

If you don't like the author's syntax and/or want to use the list, [open an issue](https://github.com/iam-py-test/my_filters_001/blob/main/special_lists/mirrored/vxvault_filter.txt) with the author.

**Comment by hagezi** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#all
