### ISSUE TITLE
app3.salesmanago.pl

### ISSUE THREAD

**Issue by crssi** [hagezi/dns-blocklists#632]
Please, remove `app3.salesmanago.pl` _and pehaps `app2.salesmanago.pl` also_
from https://github.com/hagezi/dns-blocklists/blob/main/whitelist.txt

`app3.salesmanago.pl` is a tracker.
See an example of use at `https://vecer.com/`

Thank you ❤️

**Comment by hagezi** [comment]
Hi,
this is actually a referral domain: https://github.com/hagezi/dns-blocklists#referral
I'm going to take a closer look.

**Comment by hagezi** [comment]
You are right, it is also called without clicking on a link.

**Comment by hagezi** [comment]
It is also used as a referral, so I will only block it in the more aggressive lists.
