### ISSUE TITLE
Videoproc.com - whitelist

### ISSUE THREAD

**Issue by DevShubam** [hagezi/dns-blocklists#635]
#### What adblocker/DNS cloud service are you using?
NextDNS

#### Which blocklists are used?
HaGeZi Ultimate

#### Which domain(s) should be unblocked?
videoproc.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It's just a video converter software, not sure why it's blocked.

**Comment by hagezi** [comment]
Thanks, blocked by @shadowwhisperer malware list, but I can't find anything malicious. The Domain is flagged by StopForumSpam. No more flags.

**Comment by ShadowWhisperer** [comment]
Thanks, whitelist on my list also. It looks like it the installed used to be bundled with other junk.
