### ISSUE TITLE
iaqorwr.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#638]
#### Which domain(s) should be blocked?

iaqorwr.com

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11kbtcv/got_this_text_it_used_my_real_first_name_which_is/

**Comment by hagezi** [comment]
@dureablenapkin

**Comment by devipasigner** [comment]
> @dureablenapkin

@durablenapkin
