### ISSUE TITLE
Question about light lists

### ISSUE THREAD

**Issue by nezlobnyj** [hagezi/dns-blocklists#639]
Hi @hagezi,

Hope you are well.

May I kindly ask what would you recommend in the following setup: I have Adguard Pro on all my devices with AdGuard cosmetic rules enabled and DoQ to NextDNS afterwards. In NextDNS I have your Ultimate list set up.

In your opinion is it worth to use local DNS filter list in AdGuard? I want to minimise requests to DNS server and block bad ones on the spot.

If no - I'm good :)
If yes - I believe a huge list like Normal/Pro would increase CPU load (and, in case of mobile, battery consumption), so torn between your Light and Personal AdGuard Rules. But I struggle to find difference except personal whitelist part. Which one is more suitable?

Thanks.

P.S. Now that I typed it all - feels paranoid overkill :)

**Comment by hagezi** [comment]
Hi @nezlobnyj,

If you don't need to save data volume and you don't have a slow connection to NextDNS, let NextDNS do the job. Leave only the content filtering to AdGuard.

If you want/need to filter locally, then use MULTI normally as a "pre-filter".

**Comment by nezlobnyj** [comment]
Thanks. I'll stick with filtering on "cloud" DNS then.

Have a great day.
