### ISSUE TITLE
(Discussion) OISD and notracking

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#64]
I am in the process of reformatting my [filterlist repo](https://github.com/yokoffing/filterlists), and I'd like to recommend your lists. However, I'd like to discuss your list categorization.

For your [sources](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#sourcesstatistics) undergirding the lists, we have:

- Light: OISD basic + 1Hosts (Lite) + other lists
- Normal: notracking
- Pro:  OISD full

Unless otherwise noted, OISD=OISD(full).

***

I've explained [here](https://github.com/yokoffing/NextDNS-Config/issues/5#issuecomment-1289887614) how OISD is both more forgiving than notracking and yet also includes some domains that notracking leaves out. But, notracking is more aggressive than OISD (esp. in terms of potential breakage / false positives), yet it's not as aggressive as 1Hosts (Pro). If you reference my [blocklist categorization](https://github.com/yokoffing/NextDNS-Config#blocklists-1), I would put notracking somewhere between `Balanced` and `Strict`. (It's currently under `Balanced` but I'm probably removing it soon.)

The problem is, I am increasingly not seeing notracking as `Balanced` or, to use your list denomination, `Normal`:
- Just today, I saw that notracking [breaks the Chipotle app](https://www.reddit.com/r/nextdns/comments/ytmfmq/chipotle_app/).
- notracking currently [breaks links](https://github.com/notracking/hosts-blocklists/issues/807) from my university email.
- The OISD maintainer responds to false positives within [a few hours to a few days](https://www.reddit.com/r/oisd_blocklist/comments/s70dhx/oisd_domain_blocklist/?sort=new) while notracking can [take weeks to months](https://github.com/notracking/hosts-blocklists/issues) to respond.
- Since notracking blocks some domains that are in 1Hosts (Pro) but not in 1Hosts (Lite), I would use it as a source for `Pro` or `Pro++`, but not `Light` or `Normal`, again using your designations.

For these reasons, I'd like to suggest we do either of the following:

### Option 1: Switch OISD to `Normal` and `notracking` to Pro (small change)
- Light: OISD basic + 1Hosts (Lite) + other lists
- Normal: OISD full
- Pro: notracking

### Option 2: Consolidate lists (big change)
Because OISD is very forgiving, we can go ahead and include it in `Light` and consolidate the list categories:

- Light: ~OISD basic~ OISD full + 1Hosts (Lite) + other lists
- Normal: notracking
- Pro: all lists currently in `Pro++`
- ~Pro++~: removed as a category

***

I've been mulling on this for a few days. Let me know your thoughts or concerns.

**Comment by hagezi** [comment]
Thanks for that! A great compilation! There is really nothing to add.

I agree with you and will implement option 1.

I can't think of a plausible reason why I did it that way back then. I had examined all blocklists in advance and know that the notracking is not balanced. 

Gerd

**Comment by hagezi** [comment]
Just FYI:

I had once tested the effectiveness of individual lists in my family home network and in a test against 6,000 websites from the top list known for excessive tracking, the result:

1. 1Hosts (Lite)
2. OISD
3. Adguard DNS Filter
4. NoTracking
5. Steven Black
6. Denylist

@badmojr's 1Hosts is effective as hell and a necessary source for a blocklist!

**Comment by yokoffing** [comment]
> 1Hosts is effective as hell and a necessary source for a blocklist!

Most certainly 😁

**Comment by yokoffing** [comment]
Sweet. One last things: Do you plan on making [pull requests](https://github.com/nextdns/metadata/pulls/hagezi) for `Light` and `Normal` for [NextDNS](https://help.nextdns.io/t/h7hsypb/blocklist)?

**Comment by hagezi** [comment]
Was not actually planned. But you are welcome to make some. I don't think they'll take any of my lists anyway. In the NextDNS repository there is little to no feedback anyway. You can see it in the open issues and pull requests. Absolutely no feedback. In the help forum no one reacts either. One has the feeling that user requests are skillfully ignored.

Maybe it is the AI that administers NextDNS and feedback it has not yet learned, perhaps in one of the next "updates". :)

**Comment by marcoclg19** [comment]
> Was not actually planned. But you are welcome to make some. I don't think they'll take any of my lists anyway. In the NextDNS repository there is little to no feedback anyway. You can see it in the open issues and pull requests. Absolutely no feedback. In the help forum no one reacts either. One has the feeling that user requests are skillfully ignored.
> 
> Maybe it is the AI that administers NextDNS and feedback it has not yet learned, perhaps in one of the next "updates". :)

Hi, I'm entering the discussion :)
On Reddit, I reported your blocklists to NextDNS but nothing to do. You should ask @badmojr how its 1Hosts(Xtra) list became part of the blocklists.
However, I saw that a list of yours will be added to AdGuardDNS... do you know when it will be available? I cannot wait xd.

(and I forgot to say that your lists are perfect, nice work indeed)

**Comment by hagezi** [comment]
Hi @marcoclg19,

AdGuardDNS will probably include a combination of my personal blacklist and the false positive and referral whitelist, it is the following list: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal-blackwhite.txt
It is intended to serve as a addition to the lists available there.
The list is currently in the test environment of AdGuardDNS, if and when it will find its way into the production environment I unfortunately don't know.

Thanks for the recommendation to include the lists in NextDNS. However, I do not know if and when they will be included. I have not received any feedback on this so far. The existing lists were added 2-3 years ago and since then there has been no new addition.
I cannot do more than offer the lists for inclusion, if they are not included, then so be it. It is their decision, which I respect.
What bothers me is that you get almost zero feedback on all channels.

Gerd

**Comment by yokoffing** [comment]
> The existing lists were added 2-3 years ago and since then there has been no new addition.

1Hosts (Xtra) was [added](https://github.com/nextdns/metadata/commit/5ed13aaca19a7f14b84c2c5cbc6ac6b9a580c3c3) four months ago. That's why they were saying you should ask badmojr how 1Hosts (Xtra) got approved.

**Comment by marcoclg19** [comment]
I wonder why NextDNS doesn't permanently remove the Energized lists. But not only those I would also say those that haven't been updated for years like the NSA… I don't remember exactly or the Disconnect ones.

In my opinion, all lists that are out of date or without any type of support should be removed.

I don't know maybe I'm too paranoid :(

**Comment by hagezi** [comment]
Yes, the current list selection is mostly out of date. I don't understand them either. And I also can't understand why they are holding on to Energized. But who knows what's going on in the background.

**Comment by marcoclg19** [comment]
I saw that NextDNS will make a decision in the next few days on the removal of Energized lists... I hope so!
I also saw that they asked you to move the pull request to the new repository, that's already something.
Btw, your list on AdGuardDNS should be available from next week :)

**Comment by hagezi** [comment]
@marcoclg19 AdGuardDNS list is live: https://github.com/hagezi/dns-blocklists#adguarddns

**Comment by marcoclg19** [comment]
I don't want to make @yokoffing's discussion too long  but I don't think it is appropriate to create a separate issue... 
Could your Pro configuration cause me problems with social networks like Instagram etc?  I noticed that you also add notracking. Then another thing, in the advanced section what TTL do you recommend to put? 10 should be default.

(Sorry if I have bothered you these days, but I always like to learn new things!)

**Comment by hagezi** [comment]
@marcoclg19 No no restrictions on social networks, the Black & White contains my whitelist. I use the standard TTL.
