### ISSUE TITLE
DNS Queries from Streaming Site

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#640]
#### Which domain(s) should be blocked?

delivery190.akamai-video-content.com
akamai-cdn-images.com
tc-13x.mey-cdn.com
hls13x.vidfiles.net

#### Why should the domain(s) be blocked?

From the streaming site `w.go-movies.cyou`.
They aren't actual Akamai domains. According to Whois all these domains were registered under the same Icelandic phone number.

I can't tell if they are malicious but the site still streams with them blocked. Might be something for the more aggressive lists?

**Comment by hagezi** [comment]
This requires further analysis ...

**Comment by hagezi** [comment]
@jarelllama They were registered by a service for Akamai:

Look at `akamai-images-content.com` - legit CDN of Akamai

Domain Name: AKAMAI-IMAGES-CONTENT.COM
   Registry Domain ID: 2669590415_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2022-01-20T05:32:32Z
   Creation Date: 2022-01-20T05:28:15Z
   Registry Expiry Date: 2024-01-20T05:28:15Z
   Registrar: NameCheap, Inc.
   Registrar IANA ID: 1068
   Registrar Abuse Contact Email: abuse@namecheap.com
   Registrar Abuse Contact Phone: +1.6613102107
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: JOSEPHINE.NS.CLOUDFLARE.COM
   Name Server: MARK.NS.CLOUDFLARE.COM
   DNSSEC: unsigned
```

`akamai-cdn-images.com`

```
Domain Name: AKAMAI-CDN-IMAGES.COM
   Registry Domain ID: 2757196896_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2023-02-08T20:31:49Z
   Creation Date: 2023-02-08T20:25:53Z
   Registry Expiry Date: 2025-02-08T20:25:53Z
   Registrar: NameCheap, Inc.
   Registrar IANA ID: 1068
   Registrar Abuse Contact Email: abuse@namecheap.com
   Registrar Abuse Contact Phone: +1.6613102107
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: CARLA.NS.CLOUDFLARE.COM
   Name Server: HUNTS.NS.CLOUDFLARE.COM
   DNSSEC: unsigned
```

`akamai-video-content.com`

```
Domain Name: AKAMAI-VIDEO-CONTENT.COM
   Registry Domain ID: 2756254228_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2023-02-23T19:46:58Z
   Creation Date: 2023-02-05T04:15:06Z
   Registry Expiry Date: 2026-02-05T04:15:06Z
   Registrar: NameCheap, Inc.
   Registrar IANA ID: 1068
   Registrar Abuse Contact Email: abuse@namecheap.com
   Registrar Abuse Contact Phone: +1.6613102107
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: ANDERSON.NS.CLOUDFLARE.COM
   Name Server: KEIRA.NS.CLOUDFLARE.COM
   DNSSEC: unsigned
```

**Comment by hagezi** [comment]
Remains

```
tc-13x.mey-cdn.com
hls13x.vidfiles.net
```
for further analysis

**Comment by hagezi** [comment]
I tried to trigger the call, but for me they are not called when playing the video. If I can trigger them, I can look what is transferred there, possibly it is a tracker ...

**Comment by hagezi** [comment]
Ok, got it, analyzed the network traffic.

there are some CDNs where the video is retrieved/streamed, for example

```
tc-*.mey-cdn.com
tc-*.sun-cdn.com
tc-*.goo-cdn.com
...
```

If one CDN is blocked, it will switch to the next one and eventually end up at `delivery*.akamai-video-content.com` or `hls*.vidfiles.net`. 

So nothing blockable ...

**Comment by hagezi** [comment]
Nothing remains unclear here, sometimes you waste time for nothing, but now we know. Although I'll probably have forgotten about it in a few weeks anyway ... ;)
