### ISSUE TITLE
Whitelist oanda.com

### ISSUE THREAD

**Issue by Xathros1** [hagezi/dns-blocklists#645]
#### What adblocker/DNS cloud service are you using?

Ublock Origin

#### Which blocklists are used?
HaGeZi's Normal DNS Blocklist

#### Which domain(s) should be unblocked?
oanda.com | www.oanda.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Legit site

**Comment by hagezi** [comment]
Thanks, blocked as SCAM. Listed on https://www.globalantiscam.org/scam-websites

https://www.trustpilot.com/review/www.oanda.com
https://reportscammedbitcoin.com/oanda-scam-an-in-depth-analysis-of-the-scheme/
...

![grafik](https://user-images.githubusercontent.com/104343908/223454220-d0723e9c-553c-4b07-8b2e-add35671da5b.png)

If you really want to use this, then it's something for the personal white list ...
