### ISSUE TITLE
[www.zoominfo.com]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#646]
#### What adblocker/DNS cloud service are you using?

AdguardHome

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
www.zoominfo.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Maybe just a false positive ?
https://en.wikipedia.org/wiki/ZoomInfo

**Comment by hagezi** [comment]
Thanls, ping @migueldemoura
