### ISSUE TITLE
FP overclockers.co.uk

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#65]
Hello. The pro.plus list is blocking this domain: 

    ||overclockers.co.uk^

It's a big computer components store in the UK, with an attached community forum (of which I've been a member for decades). I think it's a false positive. Can you please review and remove if appropriate? I can't see a reason they'd be blocked, even on Pro+. Many thanks!

**Comment by hagezi** [comment]
Removed,

Thanks for your support!
