### ISSUE TITLE
www.awin1.com (affiliate link)

### ISSUE THREAD

**Issue by durablenapkin** [hagezi/dns-blocklists#650]
#### What adblocker/DNS cloud service are you using?
ControlD

#### Which blocklists are used?
Normal

#### Which domain(s) should be unblocked?
`www.awin1.com`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
1. Click on "`Deal Link: https://www.samsung.com/ca/`" on https://forums.redflagdeals.com/samsung-samsung-galaxy-z-flip-4-256gb-bespoke-edition-gold-green-green-only-549-2605155/
2. Link is `https://www.awin1.com/cread.php?awinmid=18530&awinaffid=139736&clickref=&p=https://www.samsung.com/ca/`
3. Using ExpandURL.net, it should redirect to: `https://www.samsung.com/ca/?cid=ca_paid_affiliate_awin_none_ecommerce_RedFlagDeals_banner_none_none&awc=18530_1678227370_4b5ba0d69a6de1ea8bb96c7e07e9e940`

**Comment by hagezi** [comment]
Thanks.
