### ISSUE TITLE
Referral List - track.grove.co

### ISSUE THREAD

**Issue by travisboss** [hagezi/dns-blocklists#651]
#### What adblocker/DNS cloud service are you using?

Adgaurd Home

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
track.grove.co

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
I would not unblock but would be a good one to add to your referral whitelist, it is for a service called grove and is needed when accessing there services via email.

**Comment by hagezi** [comment]
Thanks, will be added.
