### ISSUE TITLE
parcel-fee.info

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#652]
#### Which domain(s) should be blocked?

parcel-fee.info

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11lhzl3/received_this_text_today_its_obviously_a_scam_but/

**Comment by durablenapkin** [comment]
Thanks, queued to add to my list

**Comment by hagezi** [comment]
Thanks
