### ISSUE TITLE
Suspected tracker [data-rep.livetech.shopee.co.id]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#653]
#### Which domain(s) should be blocked?

> data-rep.livetech.shopee.co.id

#### Why should the domain(s) be blocked?
It behaves like a tracker. Always make calls when the domain is blocked. And when it's not blocked, this site only made a few calls after which it calmed down.

Blocked this domain doesnt lead to broken in the app itself.

**Comment by hagezi** [comment]
Thanks, will be checked. Is it triggered only in the app or also on the website?

**Comment by MagicalAlchemist** [comment]
App only. I dont see it in the PC web browser.

**Comment by hagezi** [comment]
Will be added.

**Comment by hagezi** [comment]
Thanks, missed some more ...

```
data-rep.livetech.shopee.vn
data-rep.livetech.shopee.ph
data-rep.livetech.shopee.com.my
data-rep.livetech.shopee.co.th
data-rep.livetech.shopee.tw
data-rep.livetech.shopee.sg
data-rep.livetech.shopee.com.mx
data-rep.livetech.shopee.com.co
data-rep.livetech.shopee.com.br
```

**Comment by MagicalAlchemist** [comment]
> Thanks, missed ...
> 
> ```
> data-rep.livetech.shopee.vn
> data-rep.livetech.shopee.ph
> data-rep.livetech.shopee.com.my
> data-rep.livetech.shopee.co.th
> data-rep.livetech.shopee.tw
> data-rep.livetech.shopee.sg
> data-rep.livetech.shopee.com.mx
> data-rep.livetech.shopee.com.co
> data-rep.livetech.shopee.com.br
> ```

good catch :+1:
