### ISSUE TITLE
manic-code list not updating

### ISSUE THREAD

**Issue by manic-code** [hagezi/dns-blocklists#654]
Hello, recently switched my block-list from a hosts based list to a domain based one. Since then new domain additions I've added haven't been reflected on the main list since. Could there be an adjustment needed on your end to ingest the different type of block-list?

**Comment by hagezi** [comment]
Thanks, fixed. It is now included in light to ultimate. Update will be online on next full update.

**Comment by manic-code** [comment]
Sounds great, much appreciated!
