### ISSUE TITLE
TikTok login

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#655]
#### What adblocker/DNS cloud service are you using?

NextDNS - CNAME disabled
μBlock

#### Which blocklists are used?
Light - Domain is in this list.
Pro++

#### Which domain(s) should be unblocked?
log-boot.tiktokv.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Prevents App Login of TikTok

**Comment by hagezi** [comment]
Thanks, will be removed.
