### ISSUE TITLE
Independent.co.uk video can't be played or shown [static.adsafeprotected.com]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#656]
#### What adblocker/DNS cloud service are you using?

NextDNS, CNAME flattening disabled

#### Which blocklists are used?
Pro

#### Which domain(s) should be unblocked?
static.adsafeprotected.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
when this site is blocked, the video player on the independent.co.uk site cannot run. After whitelisting it, the video player works fine.
see here to double check it again: 

1. https://www.independent.co.uk/news/world/middle-east/iran-poisoning-schoolgirls-ayatollah-ali-khamenei-b2296367.html
2. https://www.independent.co.uk/sport/tennis/russia-ukraine-marta-kostyuk-varvara-gracheva-b2294915.html

**Comment by hagezi** [comment]
I knew that the day would come ...

`static.adsafeprotected.com` - Excessive use of browser API's, almost certainly for tracking 

https://slayterdev.github.io/tracker-radar-wiki/domains/adsafeprotected.com.html

Therefore, I would not like to unblock the domain for the masses unless more pages are affected.

**Comment by hagezi** [comment]
```
Blocklists:
 - 1Hosts.Lite     BLOCKED
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      BLOCKED
 - AdGuardDNS      BLOCKED
 - AhaDNS          OK
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        BLOCKED
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   BLOCKED
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            OK
 - QuidsUp.NOTRACK BLOCKED
 - StevenBlack     BLOCKED

```

**Comment by MagicalAlchemist** [comment]
Better to stay blocked.
https://pcvirusescleaner.blogspot.com/2015/08/staticadsafeprotectedcom-removal-guide.html?m=1

**Comment by hagezi** [comment]
Yes, 2015 was all viral, these posts are so pointless. SpyHunter ... lol

**Comment by MagicalAlchemist** [comment]
> Yes, 2015 was all viral, these posts are so pointless. SpyHunter ... lol

https://dictionary.cambridge.org/dictionary/english/out-of-the-frying-pan-into-the-fire :rofl:
