### ISSUE TITLE
expresscourier.delivery

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#659]
#### Which domain(s) should be blocked?

expresscourier.delivery

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11miark/express_courier_scam/

**Comment by hagezi** [comment]
Thanks, ping @durablenapkin

@jarelllama please ping @durablenapkin if you post scam for blacklist, thanks.

**Comment by hagezi** [comment]
@jarelllama Thanks for your support and collaboration here.

**Comment by durablenapkin** [comment]
Queued, thanks!
