### ISSUE TITLE
Low rated review (indicated fraud)

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#661]
#### Which domain(s) should be blocked?

1. importir.org
    Evidence : https://www.kredibel.co.id/review/importir.org

2. orderonline.id
    Evidence : https://www.kredibel.co.id/review/orderonline.id

3. infishta.com
    Evidence : https://www.kredibel.co.id/review/infishta.com

4. vestifarm.com
    Evidence : https://www.kredibel.co.id/business/vestifarm.com

5.  igrow.asia
    Evidence : https://www.kredibel.co.id/business/igrow.asia

#### Why should the domain(s) be blocked?
Most of them is pump & dump scheme. So yeah scam obviously.

**Comment by hagezi** [comment]
Thanks, will be added
