### ISSUE TITLE
steanmconnmunnity.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#662]
#### Which domain(s) should be blocked?

steanmconnmunnity.com

#### Why should the domain(s) be blocked?

Steam login phishing: https://www.reddit.com/r/Scams/comments/11mw19a/hacked_steam_account_sent_me_a_link_which_i/

I see this domain is already added to the full TIF. Up to you to decide whether to add it to the light TIF.

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks!

**Comment by hagezi** [comment]
Thanks, will be added on next update.
