### ISSUE TITLE
injustice.site

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#664]
#### Which domain(s) should be blocked?

injustice.site

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11ndw9i/scam_bot_spamming_scams_in_injustice_2/

Site redirects to bigappboi.com which is already blocked by most blocklists.

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued
