### ISSUE TITLE
False Positive [netbank.nordea.dk]

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#670]
#### What adblocker/DNS cloud service are you using?

AdguardHome

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
netbank.nordea.dk

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
https://help.nextdns.io/t/h7habhp/false-positive-with-threat-intelligence-feeds
Same rule applied by hagezi blocklist.

**Comment by hagezi** [comment]
Thanks, will be removed, source: https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
