### ISSUE TITLE
False positive [captcha.tuyacn.com]

### ISSUE THREAD

**Issue by FiveKnive** [hagezi/dns-blocklists#672]
#### What adblocker/DNS cloud service are you using?

Adguard Home

#### Which blocklists are used?
Pro++ (Domain in this list)
TIF

#### Which domain(s) should be unblocked?
captcha.tuyacn.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Not able to login to Tuya IoT Developement Platform because captcha does not load.

**Comment by hagezi** [comment]
Thanks, will be removed.

Ping source: @badmojr
