### ISSUE TITLE
Zynga API MultiPro++ Max Protect

### ISSUE THREAD

**Issue by xaqpuyrthnbg** [hagezi/dns-blocklists#674]
#### What adblocker/DNS cloud service are you using?

pfblockerng/DNSBL

MultiPro++ Max Protect

api.zynga.com

To my knowledge, the Zynga API is not malicious.

**Comment by hagezi** [comment]
Thanks, will be removed.

ping @bongochong (zynga.com)

blockkable:
```
ads.zynga.com
log-collector.svctr.zynga.com
track.api.zynga.com
```

**Comment by xaqpuyrthnbg** [comment]
Thanks very much.

**Comment by bongochong** [comment]
Will remove `zynga.com` for sure. Thanks @hagezi.
