### ISSUE TITLE
Shopee Telemetry/Tracker/Useless Link

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#675]
#### Which domain(s) should be blocked?
@@api.shopee.co.id^ # Just API
ccms.shopee.io
@@cf.shopee.co.id #Breaking UI for newcomer
dem.shopee.com
@@deo.shopeemobile.com^ # Breaking feature like mini games
df.infra.sz.shopee.co.id
endpoint.mms.shopee.co.id
frd.shopee.co.id
gslb.sgw.shopeemobile.com
@@img.ws.mms.shopee.co.id^ # Breaking product images in search feature
@@live-apm.shopee.co.id^ # Breaking some video with product affiliate (similar to tiktok video with affiliated products)
livetech.shopee.co.id
livetech.live.shopee.co.id
msdk.shopee.co.id
patronus.idata.shopeemobile.com
play-sp.vod.shopee.com
play-src.vod.shopee.com
@@play-ws.vod.shopee.com^ #Breaking some video in review section
@@sv.shopee.co.id^ #Breaking video feature (like tiktok)

I took the source from here:
https://raw.githubusercontent.com/MDP43140/BaDomain/main/BaDomain.txt

#### Why should the domain(s) be blocked?
Shopee, heaviest shopping app i've ever used. With so many useless link involved. 

I've tested it by myself to make sure doesn't break anything or limit some functionality as shopping app . 

Only some links can break the feature if the site i gave @@ mark are blocked.

**Comment by hagezi** [comment]
Oh, a shopping tiktok ... ;)

**Comment by MagicalAlchemist** [comment]
Similar but worse.

**Comment by hagezi** [comment]
It would be easier to block `*.shopee.*` :D

**Comment by MagicalAlchemist** [comment]
We can do that, but I'm not responsible if someone visits your github and gets angry because of which madman blocked the platform they thinks is a rival of tiktok. :joy:

**Comment by MagicalAlchemist** [comment]
Thanks for the input @jarelllama

**Comment by hagezi** [comment]
Added the following rules to my wildcard rules, the domains for the other list types will be extracted from toplists on next full update:

```
! Shoppee - the Shopping "TikTok" ;)
||ccms.shopee.io^
||cvf.shopee.*^
||dem.shopee.com^
||df.infra*.shopee.*^
||endpoint.mms.shopee.*^
||fe-reporting.shopeemobile.com^
||frd.shopee.*^
||gslb.sgw.shopeemobile.com^
||livetech*.shopee.*^
||msdk.shopee.*^
||offline.toc.shopeemobile.com^
||patronus.idata.shopeemobile.com^
||play-sp.vod.shopee.com^
||play-src.vod.shopee.com^
```

**Comment by xenstar** [comment]
Actually some links are for AI to learn your shopping habits and show you products base on your browsing habits.

**Comment by hagezi** [comment]
Ok, so which domains shouldn't be blocked, I can't test this properly either as it's not available for my region.
What I have seen of the website is the absolute plague. Worse than the data octopus TikTok ...

**Comment by MagicalAlchemist** [comment]
> @MagicalAlchemist @jarelllama
> 
> Added the following rules to my wildcard rules, the domains for the other list types will be extracted from toplists on next full update:
> 
> ```
> ! Shopee - the Shopping "TikTok" ;)
> ||ccms.shopee.io^
> ||cvf.shopee.*^
> ||dem.shopee.com^
> ||df.infra*.shopee.*^
> ||endpoint.mms.shopee.*^
> ||fe-reporting.shopeemobile.com^
> ||frd.shopee.*^
> ||gslb.sgw.shopeemobile.com^
> ||livetech*.shopee.*^
> ||msdk.shopee.*^
> ||offline.toc.shopeemobile.com^
> ||patronus.idata.shopeemobile.com^
> ||play-sp.vod.shopee.com^
> ||play-src.vod.shopee.com^
> ```

This one is good. I tested it again and it didn't spoil the shopping experience in the app.

Please note, shopee has weird behavior, with or without a blocklist, i think the app side is not good because sometimes images/video don't occur although our connection is fine.

**Comment by hagezi** [comment]
Ok, thanks.

**Comment by MagicalAlchemist** [comment]
Hallo @hagezi 
Is there any reason for dropping shopee blocklist above ? Has someone reporting some breakage ? I saw this resolved on my adguard home when it was previously on the blocklist.

**Comment by hagezi** [comment]
Something was wrong, but not all of them should be affected. I'll have to take a closer look at this at my leisure.

**Comment by MagicalAlchemist** [comment]
Really? I haven't encountered any breakage so far. I'm an active shopee user.

**Comment by hagezi** [comment]
Fixed with the next update.
