### ISSUE TITLE
Scam: refundpaymentnotify.com

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#676]
#### Which domain(s) should be blocked?

refundpaymentnotify.com

#### Why should the domain(s) be blocked?

Scam, check out this text I received.

![CC17DDC7-EC8E-4655-90CE-238C4BD24109](https://user-images.githubusercontent.com/113001348/224498486-ca2138e3-2774-42f3-89d4-b38d5dd91223.jpeg)

Ping @durablenapkin

**Comment by hagezi** [comment]
Thanks, will be added.

**Comment by devipasigner** [comment]
> Thanks, will be added.

Thanks ❤️

**Comment by durablenapkin** [comment]
Queued, thanks!
