### ISSUE TITLE
heliohost.org 

### ISSUE THREAD

**Issue by IbrahimElSayyid** [hagezi/dns-blocklists#678]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
MULTI ULTIMATE

#### Which domain(s) should be unblocked?
heliohost.org

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is free website hoster, not malicious

**Comment by hagezi** [comment]
Thanks, will be removed.
https://www.virustotal.com/en/domain/heliohost.org/information/
