### ISSUE TITLE
analysis.chess.com

### ISSUE THREAD

**Issue by Rgbaked** [hagezi/dns-blocklists#679]
#### What adblocker/DNS cloud service are you using?

Pi-hole

#### Which blocklists are used?
Ultimate 

#### Which domain(s) should be unblocked?
analysis.chess.com
analysis-va.chess.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Used for chess engine analysis after a game. Whitelisting the two domains returns functionality as expected.
Example https://www.chess.com/analysis/game/live/72309701581

**Comment by Rgbaked** [comment]
An example https://www.chess.com/analysis/game/live/72309701581

**Comment by hagezi** [comment]
Thanks, removed.
