### ISSUE TITLE
FP Oracle Cloud telemetry

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#68]
Oracle Cloud offers a statistics page as part of its VPS/server range, namely to provide monitoring for your server instances (CPU/memory/disk/network usage etc). Unfortunately, the domains required to render this information are included in pro.plus (I didn't check the other lists), and are imho purely FPs. 

The domains 'look' like they should be blocked, and I assume that's why they were included in whichever upstream blocklist served them. Rather, in this case they are serving 'telemetry' to the user, for the user, at the user's request. It is not 'telemetry' in the spyware/tracking sense. Some of the offending domains included in pro.plus are: 

    ||console-telemetry.oci.oraclecloud.com^
    ||console-telemetry.us-phoenix-1.oci.oraclecloud.com^
    ||telemetry.uk-london-1.oraclecloud.com^
    ||telemetry.us-ashburn-1.oraclecloud.com^
    ||telemetry.us-phoenix-1.oraclecloud.com^

These are not *collecting* telemetry, but rather displaying it to the user by request. Blocking these domains stops the server Instances page from showing the VPS statistics graphs (CPU, memory, disk, network etc). I assume the upstream blocklist added them based on their name/appearance only.

Here is the Oracle Cloud server monitoring page with your list enabled: 
![blocked](https://user-images.githubusercontent.com/7565335/202883615-c7f9fe4f-c39a-4bb6-acf5-68b36fb869f3.png)

Now here is the page with the domains whitelisted: 
![whitelisted](https://user-images.githubusercontent.com/7565335/202883646-19011f27-a4a6-439c-9ab2-d3b0762d3ae0.png)

Oracle's location-oriented URL format suggests you may wish to more broadly whitelist `@@||telemetry.*oraclecloud.com^` rather than just removing the above domains specifically. Please note the addition of the dot after 'telemetry.' here. This avoids also inadvertently whitelisting Oracle's `telemetry-ingestion.*` domains, which aren't required to make the stats pages work, and (again falling into the trap of judging solely based on the name) appear to rather be Oracle taking in telemetry from the browser session.

Just a suggestion, thanks for all the great work!

**Comment by hagezi** [comment]
@RainmakerRaw 

Thank you for the explanation. I agree with you and will remove the domains as you suggested.

I will use the pattern *telemetry.*oraclecloud.com.

Gerd
