### ISSUE TITLE
cargotrustcourier.com tripinpremiumsnacks.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#680]
#### Which domain(s) should be blocked?

cargotrustcourier.com
tripinpremiumsnacks.com

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11p6m1b/beware_scam_site/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued this and the two others in 681 and 682
