### ISSUE TITLE
neu-bank.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#690]
#### Which domain(s) should be blocked?

neu-bank.com

#### Why should the domain(s) be blocked?

Scam: NRD, fast money scam, Ponzi scheme.
https://www.reddit.com/r/Scams/comments/11qbuws/is_this_thing_legit_its_a_website_that_that_is/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued this and the others, thanks!
