### ISSUE TITLE
com-coordinates.info

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#695]
#### Which domain(s) should be blocked?

com-coordinates.info
apple.com-coordinates.info

#### Why should the domain(s) be blocked?

Scam: https://www.reddit.com/r/Scams/comments/11rdfj7/stolen_iphone_scam_more_info_in_comments/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued this and #694
