### ISSUE TITLE
tx-rvref.me

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#696]
#### Which domain(s) should be blocked?

tx-rvref.me

#### Why should the domain(s) be blocked?

Scam: NRD, SMS spam
https://www.reddit.com/r/Scams/comments/11slpyx/the_email_address_seems_legit/

@durablenapkin

**Comment by hagezi** [comment]
added

**Comment by durablenapkin** [comment]
Thanks, queued
