### ISSUE TITLE
parisiporlin-ktki.kemkes.go.id

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#698]
#### Which domain(s) should be blocked?

parisiporlin-ktki.kemkes.go.id

#### Why should the domain(s) be blocked?

Scam: SMS spam, phishing
https://www.reddit.com/r/Scams/comments/11t57in/is_this_a_scam_ive_never_gotten_a_text_from/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks! Queued
