### ISSUE TITLE
Using Third-Party Allow Lists to Reduce FPs

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#7]
User feedback is good but maybe limited. How about using allow lists from third parties to reduce FPs?

A few examples:

https://github.com/anudeepND/whitelist/blob/master/domains/whitelist.txt
https://github.com/EnergizedProtection/unblock/blob/master/basic/formats/domains.txt
https://github.com/privacy-protection-tools/dead-horse/blob/master/anti-ad-white-list.txt
https://github.com/bongochong/CombinedPrivacyBlockLists/blob/master/NoFormatting/WhitelistedDomains.txt
https://github.com/ShadowWhisperer/BlockLists/blob/master/Whitelists/Whitelist
https://github.com/mkb2091/blockconvert/blob/master/output/whitelist_domains.txt

Most of the FPs come from feedback.

**Comment by hagezi** [comment]
Thanks, I already use whitelists. I'll see what can be used from it. Less is sometimes more.

Except for the pro list, the lists should actually contain no to very few false positive domains.
