### ISSUE TITLE
metrics.leaptel.com.au

### ISSUE THREAD

**Issue by gyCfjSnO** [hagezi/dns-blocklists#701]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?
HaGeZi Personal Black & White

#### Which domain(s) should be unblocked?
https://metrics.leaptel.com.au/dashboards

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Unable to access Grafana dashboard for my internet provider due to ```|metrics.*.*^```

**Comment by hagezi** [comment]
`|metrics.*.*^` is no longer on the list, update the blocklists in AGH.
