### ISSUE TITLE
Lazada.co.id Telemetry/Tracker/Useless Link

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#702]
#### Which domain(s) should be blocked?
@@||acs-m.lazada.co.id^ # Breaking on web browser
@@||acs-m.lazada.sg^ # Breaking on web browser
@@||amdc.lazada.com^ # Breaking Lazada Feeds 
@@||c.lazada.co.id^ # Referral Link
||filebroker-cdn.lazada.co.id^
||jmacs-m.lazada.co.id^
||member.lazada.co.id^
||msgacs-m.lazada.co.id^
||orange-dc.lazada.com^
||retcode-sg-lazada.arms.aliyuncs.com^
||umlazada.alibaba.com^

Took the source from here:
https://raw.githubusercontent.com/MDP43140/BaDomain/main/BaDomain.txt

#### Why should the domain(s) be blocked?
Blocking doesn't break app and shopping experience itself. Tested by myself over and over again.

**Comment by MagicalAlchemist** [comment]
i will test it.

**Comment by MagicalAlchemist** [comment]
After adding the list from @jarelllama I didn't find any problem in the app or web browser.

However, found something funny regarding lazada feed section (TikTok wannabe). If you block sites in the first thread, you will experience video a slightly longer load, but this can be solved by swiping up/down. And the video plays as usual.

**Comment by hagezi** [comment]
Added the following to wildcard rules:

```
||audid-api-sg.taobao.com^
||cf.aliyun.com^
||filebroker-cdn.lazada.*^
||hybrid.miniapp.taobao.com^
||idfp.tongdun.net^
||ifs.lazada.sg^
||jmacs-m.lazada.*^
||lzd.highway.alibaba-inc.com^
||member.lazada.*^
||msgacs-m.lazada.*^
||orange-dc.lazada.com^
||retcode-sg-lazada.arms.aliyuncs.com^
||sg-wum.alibaba.com^
||sug.lazada.sg^
||umlazada.alibaba.com^
||ynuf.aliapp.org^
||zconfig.alibabausercontent.com^
```
