### ISSUE TITLE
cdn.branch.io

### ISSUE THREAD

**Issue by nichgit** [hagezi/dns-blocklists#708]
#### What adblocker/DNS cloud service are you using?
Diversion

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
cdn.branch.io

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Breaks Strava https://www.strava.com/athlete/routes

**Comment by hagezi** [comment]
It is a popular mobile app tracker:

_"Send Local IP, device_fingerprint_id, identity_id, hardware_id, brand, model, screen_dpi, screen_height and other
Increase mobile revenue with enterprise-grade links built to acquire, engage, and measure across all devices, channels, and platforms."_

https://reports.exodus-privacy.eu.org/en/trackers/167/
https://slayterdev.github.io/tracker-radar-wiki/domains/branch.io.html

Therefore, I will not unblock it for the masses. It's something for the personal whitelist. I would ask the manufacturer why trackers are necessary for the basic function of an app.
