### ISSUE TITLE
Fosscord, Discord alternative

### ISSUE THREAD

**Issue by karlohrvacic** [hagezi/dns-blocklists#712]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?
HaGeZi Threat Intelligence Feeds

#### Which domain(s) should be unblocked?
fosscord.com
www.fosscord.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Main site for https://github.com/fosscord, a free open source selfhostable discord compatible chat, voice and video platform

**Comment by hagezi** [comment]
Thanks, will be removed. Ping source @dogino
