### ISSUE TITLE
fleecejacketsshop.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#716]
#### Which domain(s) should be blocked?

fleecejacketsshop.com

#### Why should the domain(s) be blocked?

Scam: fake store, stolen logo and images, NRD
https://www.reddit.com/r/Scams/comments/11vffdf/httpswwwfleecejacketsshopcom_is_it_a_scam_how_to/jcsugch/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued this and #715
