### ISSUE TITLE
rhm-fxtrading.online

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#717]
#### Which domain(s) should be blocked?

rhm-fxtrading.online

#### Why should the domain(s) be blocked?

Scam: fake address and phone number, typical scam site template 
https://www.reddit.com/r/Scams/comments/11vefvw/is_rhmfxtrading_a_scam/

https://www.reddit.com/r/Scams/comments/11vefvw/is_rhmfxtrading_a_scam/jcsskap/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued
