### ISSUE TITLE
leverage-btc.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#718]
#### Which domain(s) should be blocked?

leverage-btc.com

#### Why should the domain(s) be blocked?

Scam: crypto scam, NRD
https://www.reddit.com/r/Scams/comments/11uwcry/okx_and_leveragebtccom_losing_money_and_possible/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued as well, thank you

**Comment by pahmuh805** [comment]
leverage-btc.com this is a scam
my mail  pahmuh805@gmail.com 
for communication, I am ready to share all available information

**Comment by pahmuh805** [comment]
use the phone number +44 7521 385875

**Comment by pahmuh805** [comment]
it is still active

**Comment by hagezi** [comment]
Blocked in all list versions.
