### ISSUE TITLE
Block Oppo logs

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#719]
HaGeZi - Multi PRO++
HaGeZi - Multi ULTIMATE
Recommended to be added to aggressive lists

#### Which domain(s) should be blocked?
icota-sg.coloros.com
icosa-sg.coloros.com
ifrus-sg.coloros.com
ifsau-sg.coloros.com
lang-sg.coloros.com
icota-eu.coloros.com
icosa-eu.coloros.com
ifrus-eu.coloros.com
ifsau-eu.coloros.com
lang-eu.coloros.com
icota-us.coloros.com
icosa-us.coloros.com
ifrus-us.coloros.com
ifsau-us.coloros.com
lang-us.coloros.com
icota-in.coloros.com
icosa-in.coloros.com
ifrus-in.coloros.com
ifsau-in.coloros.com
lang-in.coloros.com
weather-server-sg.allawnos.com
weather-server-eu.allawnos.com
weather-server-vn.allawnos.com
weather-server-ru.allawnos.com
weather-server-in.allawnos.com
weather-server-us.allawnos.com
weather-server-kz.allawnos.com
iot-earbuds-sg.allawnos.com
iot-earbuds-us.allawnos.com
iot-earbuds-eu.allawnos.com
iot-earbuds-in.allawnos.com
classify-app-sg.allawnos.com
classify-app-eu.allawnos.com
classify-app-us.allawnos.com
classify-app-in.allawnos.com
moa-upload-eu.allawnos.com
moa-upload-sg.allawnos.com
moa-upload-us.allawnos.com
moa-upload-in.allawnos.com
conn-service-gl-01.allawntech.com
conn-service-gl-03.allawntech.com
conn-service-cn-03.allawntech.com
conn-service-cn-04.allawntech.com
conn-service-cn-05.allawntech.com
conn-service-cn-07.allawntech.com
conn-service-cn-08.allawntech.com

#### Why should the domain(s) be blocked?
Potential Oppo logs or analytics data uploader

**Comment by hagezi** [comment]
Thanks, will check ...

**Comment by hagezi** [comment]
Added as recommended. Is online with the next full update.

**Comment by hagezi** [comment]
allawnos.com
```
conn-service-eu-01.allawnos.com
conn-service-eu-02.allawnos.com
conn-service-eu-03.allawnos.com
conn-service-eu-04.allawnos.com
conn-service-eu-05.allawnos.com
conn-service-eu-07.allawnos.com
conn-service-eu-08.allawnos.com
conn-service-in-01.allawnos.com
conn-service-in-03.allawnos.com
conn-service-in-04.allawnos.com
conn-service-in-05.allawnos.com
conn-service-in-07.allawnos.com
conn-service-in-08.allawnos.com
conn-service-us-03.allawnos.com
conn-service-us-04.allawnos.com
conn-service-us-05.allawnos.com
conn-service-us-07.allawnos.com
conn-service-us-08.allawnos.com
opex-service-eu.allawnos.com
opex-service-in.allawnos.com
opex-service-sg.allawnos.com
sau-server-eu.allawnos.com
sau-server-in.allawnos.com
sau-server-sg.allawnos.com
sau-server-us.allawnos.com
```

allawntech.com
`nothing blocked`

coloros.com
```
log-eap.coloros.com
log-eap-in.coloros.com
log-eap-sg.coloros.com
moa-upload-online.coloros.com
```

**Comment by wish13-un** [comment]
> allawnos.com
> 
> ```
> conn-service-eu-01.allawnos.com
> conn-service-eu-02.allawnos.com
> conn-service-eu-03.allawnos.com
> conn-service-eu-04.allawnos.com
> conn-service-eu-05.allawnos.com
> conn-service-eu-07.allawnos.com
> conn-service-eu-08.allawnos.com
> conn-service-in-01.allawnos.com
> conn-service-in-03.allawnos.com
> conn-service-in-04.allawnos.com
> conn-service-in-05.allawnos.com
> conn-service-in-07.allawnos.com
> conn-service-in-08.allawnos.com
> conn-service-us-03.allawnos.com
> conn-service-us-04.allawnos.com
> conn-service-us-05.allawnos.com
> conn-service-us-07.allawnos.com
> conn-service-us-08.allawnos.com
> opex-service-eu.allawnos.com
> opex-service-in.allawnos.com
> opex-service-sg.allawnos.com
> sau-server-eu.allawnos.com
> sau-server-in.allawnos.com
> sau-server-sg.allawnos.com
> sau-server-us.allawnos.com
> ```
> 
> allawntech.com `nothing blocked`
> 
> coloros.com
> 
> ```
> log-eap.coloros.com
> log-eap-in.coloros.com
> log-eap-sg.coloros.com
> moa-upload-online.coloros.com
> ```

Thanks
