### ISSUE TITLE
FP www.manli.com

### ISSUE THREAD

**Issue by spec1re** [hagezi/dns-blocklists#72]
Manli is a GPU AiB, it shouldn't do any harm. :P

https://www.manli.com/en/product-detail-Manli_GeForce_RTX%C2%AE_4090_Gallardo_(M3530+N675)-312.html

Listed in TIF

**Comment by hagezi** [comment]
Thanks, I will fix this as soon as possible. Currently, a build of the lists is already running. When this is finished I will remove the domain.

**Comment by hagezi** [comment]
Fix is online https://github.com/hagezi/dns-blocklists/commit/4abe4fd828089f194e568ad45cc4d8c84f32709d

**Comment by spec1re** [comment]
Thanks!
