### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by 0kJackoo** [hagezi/dns-blocklists#729]
### What adblocker/DNS cloud service are you using?

NextDNS

### Which blocklists are used?

HaGeZi Multi Pro++

### Which domain(s) should be unblocked?

eulatracking-public-service-prod06.ol.epicgames.com

### Why should the domain(s) be unblocked?

When this domain is blocked some users cannot download some games and they will also get errors when verifying game files

https://github.com/badmojr/1Hosts/issues/643

**Comment by hagezi** [comment]
Not on my lists ...

**Comment by 0kJackoo** [comment]
![image](https://user-images.githubusercontent.com/125915142/226468232-7e1abc07-abe6-4cc1-9480-95400c20ad6e.png)

**Comment by hagezi** [comment]
Thanks, blocked by CNAME `eulatracking-svc-prod06-pub-1257580502.us-east-1.elb.amazonaws.com`.
Ping Source @badmojr
