### ISSUE TITLE
Whitelist Request: angi.com

### ISSUE THREAD

**Issue by mahtd** [hagezi/dns-blocklists#731]
#### What adblocker/DNS cloud service are you using?

uBlock Origin / NextDNS

#### Which blocklists are used?
HaGeZi Pro

#### Which domain(s) should be unblocked?
angi.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Popular site for finding contractors. Used to be angieslist.com. Seems to come from NoTracking

**Comment by hagezi** [comment]
Thanks, will be removed. ping @notracking

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
