### ISSUE TITLE
Scam Site List

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#732]
#### Which domain(s) should be blocked?

1. tukeraja.store
2. cma88.vip
3. m.bpfutures.top

#### Why should the domain(s) be blocked?

1. Scam / Fraudulent under the guise of credit exchange.
https://mediakonsumen.com/2023/03/20/surat-pembaca/penipuan-penukaran-pulsa-oleh-situs-tukeraja-store

2.  Scam site under the guise of completing missions to earn money

3.  Fraud trading sites
https://www.facebook.com/groups/188766661163915/posts/9145644958809329

@durablenapkin

**Comment by hagezi** [comment]
Thanks, will be added asap.

**Comment by durablenapkin** [comment]
Queued, thanks!
