### ISSUE TITLE
use.fvr.to

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#733]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?

Ultimate 

#### Which domain(s) should be unblocked?

use.fvr.to

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Email referral for feverup.com

Clicking on email URL: `http://click.email.feverup.com/?qs=<string>` redirects to `https://use.fvr.to/<string>?utm_source=email&utm_content=SG_EML_TRN_ONB_JRN_SGM_OnboardingV1_D0-general_RG_20-3-2023&utm_medium=onboarding`

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
