### ISSUE TITLE
whitelist s01.riotpixels.net

### ISSUE THREAD

**Issue by Uranite** [hagezi/dns-blocklists#734]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
HaGeZi - Multi PRO++

#### Which domain(s) should be unblocked?
s01.riotpixels.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It's a domain where you can see game screenshots
https://en.riotpixels.com/games/life-of-delta/screenshots/17/

**Comment by hagezi** [comment]
Thanks, whitelisted. 
Source: https://gitlab.com/quidsup/notrack
