### ISSUE TITLE
Block https://badiu-matei.ro/

### ISSUE THREAD

**Issue by blancolandau** [hagezi/dns-blocklists#735]
Hi,

I am receiving phishing emails with an URL that ultimately redirect you to this domain badiu-matei.ro

Here is the URL: 
http://sf_rand_string_lowercaseTuesday,%20March%2021,%202023academia@maskodigo.com.sf_rand_string_lowercase.23academia.html21889399999sss.drfamhost.shop./#.aHR0cHM6Ly9iYWRpdS1tYXRlaS5yby93YXAtYWRtaW4vaW1hZ2VzP2U9YWNhZGVtaWFAbWFza29kaWdvLmNvbQ==

**Comment by hagezi** [comment]
Thanks, will be added.
