### ISSUE TITLE
*.movabletype.biz

### ISSUE THREAD

**Issue by Phoroc** [hagezi/dns-blocklists#736]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?

Most Abused TLDs

#### Which domain(s) should be unblocked?

*.movabletype.biz

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Website is blocked by CNAME
- Cyber Physical Security Research Center, AIST: https://www.cpsec.aist.go.jp/index_en.html (aist-nmy0.movabletype.biz)
- Movable Type developer documentation in Japanese: https://www.movabletype.jp/ (mtjp-wvgg.movabletype.biz)

About AIST: https://en.wikipedia.org/wiki/National_Institute_of_Advanced_Industrial_Science_and_Technology
About Movable Type: https://en.wikipedia.org/wiki/Movable_Type

**Comment by hagezi** [comment]
Thanks, will be added as denyallow rule.
