### ISSUE TITLE
d3p8zr0ffa9t17.cloudfront.net

### ISSUE THREAD

**Issue by suricloud** [hagezi/dns-blocklists#737]
#### What adblocker/DNS cloud service are you using?

Controld

#### Which blocklists are used?
Hagezi pro

#### Which domain(s) should be unblocked?
d3p8zr0ffa9t17.cloudfront.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Hi, i see this amazon domain is blocked, and its also on your whitelist but still it blocks.can fix it ?
d3p8zr0ffa9t17.cloudfront.net

**Comment by hagezi** [comment]
It is commented out in the whitelist. It is used as a fallback for sending device metrics. It is also written as a comment above the entry.

Any traceable problems caused by blocking?

I have blocked the domain for years and have not experienced any problems with any Amazon device.

**Comment by suricloud** [comment]
Ok, i taught it would give problems with alexa devices or firestick tv. I will keep monitoring and  see if i get issue or not.

Next thing, when i do a adblock test trough https://d3ward.github.io/toolz/adblock.html on my iphone,android devices i see the following are not blocked, 
ad.doubleclick.net
adservice.google.com
analytics.google.com

Is there a reason for this why not blocked by hagezi pro ?
