### ISSUE TITLE
uspsglobalexpress.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#743]
#### Which domain(s) should be blocked?

uspsglobalexpress.com

#### Why should the domain(s) be blocked?

Scam. Signs: NRD, broken links, phishing
https://www.reddit.com/r/Scams/comments/11zajyh/uspsglobalexpresscom_scam/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks!
