### ISSUE TITLE
omtrdc.net

### ISSUE THREAD

**Issue by maghuro** [hagezi/dns-blocklists#749]
#### What adblocker/DNS cloud service are you using?

Nextdns 

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
omtrdc.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
I know this domain is from adobe marketing. However it breaks many apps/things when blocked. For example, web chats of customer support, Portuguese CETELEM app, etc...

**Comment by hagezi** [comment]
`omtrdc.net` is popular and it is more than marketing: Ad Motivated Tracking, Advertising, Analytics, Audience Measurement, Third-Party Analytics Marketing, CNAME Trackers, ...

Not surprisingly it is completly blocked in aggressive blocklists. Yes, it can restrict functions, but users of an aggressive list version expect such domains to be blocked. If it does cause restrictions, it is something for the personal whitelist if you use an aggressive list. It is just too popular to whitelist for the masses.

Alternatively you could use one of the non-aggressive list versions.

**Comment by maghuro** [comment]
Understood ! Thanks for your prompt help.
