### ISSUE TITLE
gall.dcinside.com

### ISSUE THREAD

**Issue by green1052** [hagezi/dns-blocklists#751]
#### What adblocker/DNS cloud service are you using?

adguard home

#### Which blocklists are used?

Ultimate 

#### Which domain(s) should be unblocked?

gall.dcinside.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

its korean site

**Comment by hagezi** [comment]
Ping @bongochong (md-id-fork)

Will be removed.

**Comment by bongochong** [comment]
That's definitely an entry from the original Immortal Malware Domains list. My goal in keeping that list alive has been bifold: 1. Periodically check it for dead domains (but don't remove them unless they repeatedly show up as inactive for more than two consecutive months). 2. Periodically add new domains that consistently appear in multiple reliable malware feeds. Manually verifying whether or not a site from that list now serves legitimate content is a different story, and a more daunting task, so this helps with that aspect of things. Thanks again. Looks A-OK so will remove.
