### ISSUE TITLE
[NSFW Warning] Ads, Analytics and Tracking Domains

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#754]
#### Which domain(s) should be blocked?
tracker.scoober.com
tracker-api.scoober.com
press-tracking-api.sovendus.com
tracking.vviinn.com
track.shipcloud.io
track.westermann.de
tracking.hostdirectory.in
track.sexcamchats.com
tracking.ant1852.com
analytics.eng.nianticlabs.com
analytics.truyen-hentai.com
bespoke-analytics.razerapi.com
amp-analytics.chip.de
analytics-ingestion.pbpms.de
analytics.uqnic.com
bitwarden.joph-auth.com
target-video.com
www-famousinternetgirls-com.webpkgcache.com
civey.com
ipstatp.com
glomex.cloud
husuko.xyz
webclicks24.com
frauen-zum-ficken.com
tracking.offerista.com
amptracking.sky.de
dynatrace.com
dynatrace.schwarz
abtest.ninebot.com
metadata.pbpms.de
cocos-lookup.web.de
probleme.app
trending-prd.internet.apps.samsung.com
servogram.io
digitalmarketplace.service.gov.uk
namaschine-ersatzteile.de
onkakao.net
huoshanstatic.com
daumcdn.net
daum.net
ais.wetter.de
moyoung.com
track.patpat.com
tracking.cloud.kaufland.de
location-traceroute-sg.bytedance.com
datingarea.life
oextraordin.xyz
trepolan.com
prod.log.defra01.shadow.tech
rawgit.com
matri.eu
mmfit.eu
anyline.com
differture.com
mk-marketing.info
partnerprogramm.otto.de
quality.dpdhl.com

#### Why should the domain(s) be blocked?
rawgit.com is deprecated and project is terminated. Will endup as parked Domain soon.
bitwarden.joph-auth.com Phishing
prod.log.defra01.shadow.tech Log Files for Shadow PC
probleme.app Error logs Integration inapp
namaschine-ersatzteile.de Fake Shop ( Typo is on purpose)
matri.eu Fake shop

**Comment by yokoffing** [comment]
Where did all these come from?

**Comment by xRuffKez** [comment]
> Where did all these come from?

Personal blocklist. I'm having a little rack at home with adguard. Family and friends are using my DNS Server. So far No Problems occured while blocking above listed Domains.

If you need more Infos, Tell me.

**Comment by hagezi** [comment]
No tracker, Foodtracker Lieferando:
```
tracker.scoober.com
tracker-api.scoober.com
```
No tracker, parcel tracking:
`track.shipcloud.io`

Removed (dead domain):
`analytics.eng.nianticlabs.com`

Google Search Cache, no valid domain:
`www-famousinternetgirls-com.webpkgcache.com`

No advertising, tracking, ... and not malicous:
`civey.com` - Opinion research
`dynatrace.com` - Cloud platform
`dynatrace.schwarz` - Cloud platform managed portal
`abtest.ninebot.com` - Segway A/B testing
`probleme.app`
`digitalmarketplace.service.gov.uk` - UK Gov site
`trepolan.com`
`rawgit.com`
`matri.eu` - no fakeshop: https://www.verbraucherzentrale.nrw/fakeshopfinder-71560 
`anyline.com`
`differture.com`
`mk-marketing.info` - Marketing Agency
`partnerprogramm.otto.de` - Otto Affilate

Not sure, further details required:
`ipstatp.com` - Tiktok/Bytedance related 
`metadata.pbpms.de` - Photon Beam Position Monitors
`cocos-lookup.web.de` - Web.de
`huoshanstatic.com` - ?
`ais.wetter.de` - Wetter.de
`moyoung.com` - ?
`prod.log.defra01.shadow.tech` - Shadow PC cloud service

Whitelisted:
`glomex.cloud` - Glomex Video Player
`webclicks24.com` - Referral links
`daumcdn.net / daum.net` - Ad and tracking subdoamins are blocked

Already blocked in all lists:
```
tracking.vviinn.com
track.sexcamchats.com
analytics.truyen-hentai.com
amp-analytics.chip.de
analytics.uqnic.com
husuko.xyz
tracking.cloud.kaufland.de
datingarea.life
mmfit.eu
```

Already blocked in pro++/ultimate. Will be added to the other list versions. 
```
track.westermann.de
bespoke-analytics.razerapi.com
analytics-ingestion.pbpms.de
```

Already blocked in ultimate. Will be added to the other list versions. 
```
tracking.hostdirectory.in
tracking.offerista.com
track.patpat.com
```

Already blocked in pro++/ultimate, possible breakage:
`press-tracking-api.sovendus.com`
`trending-prd.internet.apps.samsung.com`
`servogram.io` - In-house analytics, analytics/tracking subdomains blocked in all list versions 
`onkakao.net` - only tracking subdomains are blocked
`location-traceroute-sg.bytedance.com`

Added to all list versions:
```
tracking.ant1852.com
bitwarden.joph-auth.com
frauen-zum-ficken.com
amptracking.sky.de
namaschine-ersatzteile.de
oextraordin.xyz
```

Added to aggressive lists only. Not sure if it leads to restrictions. e.g. playing videos on various sites:
`target-video.com`

**Comment by xRuffKez** [comment]
Thanks for your Work, i will provide more Infos in next Submission of Domains. I apologize.
