### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by trackerct** [hagezi/dns-blocklists#76]
please remove this domains. Streaming video not working, break sites.

beggarlyfilmingabreast.com
cdn.sgmntfy.com
cdn.segmentify.com
per2.segmentify.com
key.seckeyserv.me

**Comment by hagezi** [comment]
@trackerct Please send me a link where I can check this.

Thanks,
Gerd

**Comment by trackerct** [comment]
`www.gratis.com`

**Comment by hagezi** [comment]
@trackerct `gratis.com` fix is online, please check.

What do the following domains need to be unblocked for:
```
beggarlyfilmingabreast.com
key.seckeyserv.me
```

**Comment by trackerct** [comment]
Thanks. Stream Links will appear around 60 mins prior to game start. :D I'm waiting.

**Comment by hagezi** [comment]
@trackerct 

`*. seckeyserv.me` is not blocked in any of my lists.

`beggarlyfilmingabreast.com` is flagged, DGA domain and blocked by Quad9:

https://www.virustotal.com/gui/domain/beggarlyfilmingabreast.com/details
https://otx.alienvault.com/indicator/domain/beggarlyfilmingabreast.com
...

I will not whitelist it, if it is needed for whatever, put it on your personal whitelist. I advise you against it!

Closing ...

**Comment by trackerct** [comment]
key.seckeyserv.me
`https://js.freestreams-live1.com/nhlnetwork4/`
