### ISSUE TITLE
chsoop.robinhoodproz.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#765]
#### Which domain(s) should be blocked?

chsoop.robinhoodproz.com

#### Why should the domain(s) be blocked?

Scam/fake store.
https://www.reddit.com/r/Scams/comments/11z5sxv/has_anyone_used_ch_shop/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued this and all the others
