### ISSUE TITLE
Fake dark net websites

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#766]
#### Which domain(s) should be blocked?

aasap-market.com
abacus-marketlink.com
alphabay.ca
alphabay-dark-market.com
alphabaydarkmarket.net
alphabaydarknetlive.com
alphabaydarknetmarket.com
alphabay-darknet.net
alphabaydarknet.shop
alphabaydarkserver.com
alphabaydarkweb.net
alphabaydrugs.com
alphabaydrugs.net
alphabay.info
alphabay.ink
alpha-bay.link
alphabay.link
alphabaylink2023.com
alphabaylink24.com
alphabaylinkmarket.com
alphabaylinkmarketplace.com
alphabay-link.net
alphabaymania.com
alphabay-market.cc
alphabay-market.co
alphabaymarketdeal.com
alphabaymarket.info
alphabaymarket.ink
alphabaymarket.link
alphabay--market--link.com
alphabay-marketlink.com
alphabaymarketlink.com
alphabaymarketlink.net
alphabay-market-linkss.com
alphabaymarketlinkss.com
alphabaymarketlinktor.com
alphabay--market.net
alphabay-marketonion.com
alphabaymarketonion.com
alphabaymarketonionx.com
alphabay-market.org
alphabaymarket.org
alphabaymarkets.cc
alphabaymarkets.com
alphabaymarketsdarknet.com
alphabaymarketsonion.com
alphabaymarketsurl.com
alphabaymarketurl.org
alphabaymarketurls.com
alphabaymarketurltor.com
alphabaymarketweb.com
alphabayonion.com
alphabayonionmarketplace.com
alphabayonionmarkets.com
alphabayonion.net
alphabay.org
alphabayurlkeeper.com
alphabayurls.com
archetyp-marketonion.com
asap-darkmarket-online.com
asap-darkwebmarket.com
asap-market.biz
asapmarket.cc
asap-market.com
asapmarkÃ©t.com
asapmarket.in
asapmarket.info
asapmarket.link
asap-marketlink.com
asapmarketlink.info
asap-marketlink.org
asapmarketlinks.com
asapmarketlinks.org
asapmarketonion.com
asapmarket.online
asapmarketonline.com
asap-market.org
asap-marketplace.com
asapmarkets.co
asap-markets.com
asapmarket-shop.com
asapmarketslink.com
asapmarkets.org
asap-markett.com
bestdarknetmarketslinks.com
blackmarketblock.com
bohemia-marketlink.com
cannahome-markets.com
choosetorlinks.com
daek.direct
darkcatalog.com
darkdmarketruglink.link
darkdrugsmarketplace.link
darkdrugweb.shop
darkentlive.com
darkfail.live
darkfoxdarkneturl.com
dark.link
darkmarket.link
dark-market-link.com
darkmarketonionsites.link
darkmarketonline.com
darkmarketpoint.link
darkmarketpremium.com
darkmarketsbank.link
darkmarketsgo.link
darkmarketsurl.com
darkmarketsurllist.link
darknetdarkweb.link
darknet-darkweb-market.com
darknetdruglinks.com
darknet.fail
darknetlinks.xyz
darknet.live
darknet-market24.com
darknet-market.link
darknetmarketlinkz.link
darknetmarketonion.link
darknetmarketplacelink.com
darknetmarketplaceone.com
darknetmarketplaceone.link
darknetmarketplaces.link
darknet-markets24.com
darknetmarkets.com
darknet-markets.link
darknetmarketslink.com
darknet-markets.net
darknetmarketsonion.link
darknetmarketwww.com
darknetone.com
darknetpages.com
darknetplace.com
darknet-tormarkets.link
darknettormarketslinks.com
darknetwebmarket.com
darknetwebmarkets.com
darkonlinemarket.com
dark.pe
darkweb-darknet.link
darkweb-darknet-market.link
darkwebdarknetmarket.link
darkwebdarknetmarkets.link
darkweblink.co
dark-web-link.com
darkweblink.com
darkweblinks.com
darkweblinks.net
darkweblinks.wiki
darkweblive.net
darkwebmagazine.com
darkwebmarketinfo.com
darkwebmarketlinkxx.shop
darkwebmarketlistik.link
darkwebmarket.net
darkwebmarketnet.com
darkweb-markets.link
darkwebmarketslist.link
darkwebofficial.com
darkwebonionmarketplace.com
darkwebonlinemarkets.com
darkwebonlinemarkets.link
darkwebtormarketslinks.com
darkweburls.com
darkworldmarket.com
darlnetlive.com
deepweblinks.live
deepweblinks.net
deepwebsiteslinks.com
dnmlink.com
dnmlinks.xyz
dnstats.net
dork.fail
drdarknetmarkets.com
drdarknetmarkets.link
drugmarketonion.com
hypemarketslinks.link
incognito-marketonion.com
kingdomarketdarkweb.link
kingdomarket.link
livedarknet.com
marketplacetor.com
mmonopolymarket.link
mrdarknet.com
mrdarknet.link
mrdarkweb.link
mrmarketonion.com
mydarkmarket.com
mydarkwebmarketlist.com
mydarkwebmarketplace.com
mydeepdrugurl.link
mydeepmarketsweb.link
nemesis-marketlink.com
oniondarknet.link
oniondarknetmarket.com
onion.live
onionmarkets-darknet.link
onionurl.cc
onionurl.net
onionurl.xyz
royal-marketonion.com
thedarkmarketonline.com
thedarkweblinks.com
thedarkwebmarket.com
thedeep-weblinks.com
tir.taxi [This is a phishing version of our site]
tor2door-marketonion.com
tor.cab [This is a phishing version of our site]
tordarknetmarket2022.link
tordarkwebmarketlink.link
tordarkwebmarketlink.shop
tor-marketplace.com
tormarkets22.com
tormarkt.com
torrez-market-link.com
torrezmarkets.com
tortaxi.info [This is a phishing version of our site]
tot.taxi [This is a phishing version of our site]
versusdarkmarketplace.com
versusdrugsmarket.com
versus-marketplace.com
vice-city-marketlink.com
whitehousemarket-link.com
world-market-darkweb.link

#### Why should the domain(s) be blocked?
Darknet phishing sites 

list provided by tor.taxi

https://tor.taxi/avoid

**Comment by hagezi** [comment]
Thanks, added https://tor.taxi/avoid as source.
