### ISSUE TITLE
TIF Source Suggestion

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#769]
From creator's Reddit post:
> I am a security researcher and I have begun creating a block list based on malicious domains I have found throughout my investigations that I use for myself. 

https://www.reddit.com/r/pihole/comments/11rxs9w/block_list_from_threat_research/

Blocklist: https://github.com/horrorclause/piHoleBlockList

Take note that the entries in the list aren't all in the right format. Some are URLs instead of just domains. For example:
```check.newssolutions.net/N4215/adj/amzn.us.sr.aps
docsend.com/view/mtgpj5dkivzbkpgk
forms.yandex.ru/u/6061b678f62d767e0214584c/
www.dropbox.com/s/dl/2e7ggyxyx4yofa4/

**Comment by hagezi** [comment]
I'll take a look at them and see if anything is missing. Pretty wild, URLs, upper and lower case, ... on a doamain blocklist.

**Comment by hagezi** [comment]
No benefit, poorly maintained, domains that have nothing to do with malware.
