### ISSUE TITLE
experience.tinypass.com 

### ISSUE THREAD

**Issue by cotusandro** [hagezi/dns-blocklists#771]

**Comment by hagezi** [comment]
Can you please describe why the domain should be whitelisted and where it leads to restrictions?

**Comment by cotusandro** [comment]
What adblocker/DNS cloud service are you using?
- NextDNS

Which blocklists are used?
- Multi Pro++

Which domain(s) should be unblocked?
- experience.tinypass.com

Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
- This service “ experience.tinypass.com”  is used by many news sites (e.g thehindu.com), When i whitelisted this i could able to read unlimited news articles bypassing the paywall limit. It is also whitelisted in StevenBlack list when i used this inspite of Multi Pro++. That’s why i think it should be whitelisted, which will enhance user experience.

**Comment by hagezi** [comment]
Thanks, can't find this domain on my lists.

**Comment by hagezi** [comment]
@cotusandro 

It is blocked in the following lists:

![grafik](https://user-images.githubusercontent.com/104343908/227855573-3625138c-3aaa-47fc-8107-404a0725fe27.png)

**Comment by cotusandro** [comment]
Sorry, My mistake, I misinterpreted, I should say to block this url not whitelist. Please consider this again.

**Comment by hagezi** [comment]
OK, I had already thought of something like that. ;)

**Comment by cotusandro** [comment]
Thanks sir, You are truly amazing.

**Comment by hagezi** [comment]
@cotusandro 
I investigated why this is whitelisted. If you block this domain, subscribing will no longer work. There are also some other issues with this topic: https://github.com/search?q=experience.tinypass.com&type=issues

It's more something for the personal blacklist.

**Comment by cotusandro** [comment]
You mentioned that you would only whitelist if it leads to functional restrictions in mass, but not if it leads to functional restrictions on a handful of pages. I have cross checked the sites where the (subscription) issue had arised earlier but now they are working fine.

https://github.com/acnapyx/paywall-remover/issues/3#issue-851771331
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1226#issue-1591994786
https://github.com/lightswitch05/hosts/issues/189#issuecomment-639536698
https://github.com/NanoAdblocker/NanoFilters/issues/291#issuecomment-476786362
https://github.com/lightswitch05/hosts/issues/189#issuecomment-899506351

Maintaining such large lists is hard work. One of the main problems is that domains you unblocked a long time ago because they cause functional restrictions on various pages, apps or devices, might be blocked again today because these restrictions no longer exist due to customization. You need to check your whitelist from time to time. That's very time-consuming.- HaGeZi

**Comment by cotusandro** [comment]
<img src="https://imgtr.ee/images/2023/03/28/9uyzA.jpg" alt="9uyzA.jpg" border="0" />

**Comment by hagezi** [comment]
Thanks for checking, will block it in the agressive lists.
