### ISSUE TITLE
Pro++ FP: events.gfe.nvidia.com

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#772]
Hi Gerd,

I hope things are good with you and that you're keeping well. I have been recommending your lists and an old acquaintance has reported the following FP in Pro++ (but not Pro, they say): 

    events.gfe.nvidia.com

They say: 

> Is a false positive in the Pro++ list. It's blocking updates and game configuration via the GeForce Experience.

Please can you look at this? Many thanks!

Lee

**Comment by hagezi** [comment]
Thanks, will be removed on next update, missed that.

**Comment by RainmakerRaw** [comment]
Thanks very much. Top work as always!
