### ISSUE TITLE
internationalcybersafedating.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#778]
#### Which domain(s) should be blocked?

internationalcybersafedating.com

#### Why should the domain(s) be blocked?

Scam: Signs: NRD, pig butchering scam
https://www.reddit.com/r/Scams/comments/123ct8j/scam_ive_been_talking_to_someone_i_met_online_and/

@durablenapkin

**Comment by hagezi** [comment]
Thanks, will be added on next update.
