### ISSUE TITLE
philsshorthairorientalkittens.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#779]
#### Which domain(s) should be blocked?

philsshorthairorientalkittens.com

#### Why should the domain(s) be blocked?

Scam. Signs: NRD, phone number linked to reported scam
https://www.reddit.com/r/Scams/comments/1236klg/trying_to_get_a_cat_and_found_this_breeder/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued this and the other
