### ISSUE TITLE
classifiedscloud.io - Recommendation to add

### ISSUE THREAD

**Issue by johannes1984** [hagezi/dns-blocklists#78]
Blocking classifiedscloud.io drastically reduces ads in the ebay Kleinanzeigen app. Might be only relevant for Germany but it makes the app very clean. :-)

**Comment by hagezi** [comment]
Thanks, tested and added. Will add to all lists in next update.

Thanks for your support,
Gerd

**Comment by hagezi** [comment]
@johannes1984 

I had clicked through the app and could not find anything negative, however according to umbrella top list there are the following domains that are called:

attachments.eu.corechat-prod.classifiedscloud.io
corechat-prod.classifiedscloud.io
des.ebayk.liberty-prod.classifiedscloud.io
ebayk.liberty-prod.classifiedscloud.io
eu.corechat-prod.classifiedscloud.io
liberty-prod.classifiedscloud.io
lms.ebayk.liberty-prod.classifiedscloud.io

blocking classifiedscloud.io would block all of them in adblocklists. They don't necessarily look like ads now.

Can you test and maybe find out the exact domain which is responsible for ads?

**Comment by johannes1984** [comment]
@hagezi 

Good point, indeed. Same for me, no strange behavior. :-)

But lms.ebayk.liberty-prod.classifiedscloud.io seems to deliver the adds. Currently I have the full domain blocked -> no adds. When I whitelist lms.ebayk.liberty-prod.classifiedscloud.io the ads are back.

**Comment by hagezi** [comment]
Thanks, I will test it.

**Comment by hagezi** [comment]
@johannes1984 
Can you post a screenshot with and without ads? I see ads in the ios app whether lms.ebayk.liberty-prod.classifiedscloud.io is blocked or not.

**Comment by hagezi** [comment]
@johannes1984 
Blocking `lms.ebayk.liberty-prod.classifiedscloud.io` is the right way to go. Added the domain, will go live with the next autoupdate.
