### ISSUE TITLE
onthereelpros.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#781]
#### Which domain(s) should be blocked?

onthereelpros.com

#### Why should the domain(s) be blocked?

Scam. Signs: NRD, fake store
https://www.reddit.com/r/Scams/comments/12413rz/onthereelproscom/jdxbt21/

@durablenapkin

**Comment by hagezi** [comment]
Thanks, added

**Comment by durablenapkin** [comment]
Queued, thanks
