### ISSUE TITLE
alumnialliances.com

### ISSUE THREAD

**Issue by gabeio** [hagezi/dns-blocklists#785]
#### Which domain(s) should be blocked?

alumnialliances.msnd20.com
alumnialliances.com
univau.alumnialliances.com
update.alumnialliances.com
*.alumnialliances.com

#### Why should the domain(s) be blocked?

Phishing campaign, they sent me an email mentioning completely incorrect details about myself and my school history.

<details>

<summary>Subject line (I'm *not* in construction... and I've never been to Auburn University let alone an alumni of them.)</summary>

<img width="687" alt="Screenshot 2023-03-28 at 16 39 04" src="https://user-images.githubusercontent.com/643410/228390466-fa29ce00-1902-4430-947b-251534a9b007.png">

</details>

<details>

<summary>Within the body: (They outright mention that the reason they are reaching out they have no association with.)</summary>

<img width="655" alt="Screenshot 2023-03-28 at 16 39 12" src="https://user-images.githubusercontent.com/643410/228390464-7b636046-c776-47b0-ada9-3e5df4885092.png">

</details>

If you'd like the entire body (as proof) of the email please let me know I'll be *more* than glad to share to get this blocked.

---

the email has been reported as phishing as well to the original sender's smtp service as well as their domain registrar.

**Comment by hagezi** [comment]
Thanks, will be added on next update.
