### ISSUE TITLE
mcsglobalcargo.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#787]
#### Which domain(s) should be blocked?

mcsglobalcargo.com

#### Why should the domain(s) be blocked?

Scam. Signs: delivery scam, advance fee scam
https://www.reddit.com/r/Scams/comments/124x60j/does_anybody_know_anything_about_mcs_global_cargo/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks

**Comment by hagezi** [comment]
Thanks, will be adde on next update.
