### ISSUE TITLE
apple.enablemyidservices.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#788]
#### Which domain(s) should be blocked?

apple.enablemyidservices.com

Take note `enablemyidservices.com` is merely a CNAME of the non-malicious `url.dnspod.com`.

#### Why should the domain(s) be blocked?

Scam. Signs: NRD, SMS phishing
https://www.reddit.com/r/Scams/comments/125flcs/apple_payment_scam/

@durablenapkin

**Comment by hagezi** [comment]
Thanks, will be added on next update.

**Comment by durablenapkin** [comment]
Queued, thanks
