### ISSUE TITLE
performgroup.com

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#789]
#### Which blocklists are used?

HaGeZi - Multi ULTIMATE

#### Which domain(s) should be unblocked?

False Positive

bcapps.net
performgroup.com
visualisation-socketserver.performgroup.com
secure.static.visualisation.performgroup.com
visualisation.performgroup.com
player.performgroup.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

Breaking the match platforms.

https://www.mackolik.com/mac/fu%C5%BEinar-vs-roga%C5%A1ka/5iovqvhdh7kyolu5fwdqqs104
https://github.com/hagezi/dns-blocklists/issues/745

**Comment by hagezi** [comment]
Thanks, will be removed.
