### ISSUE TITLE
Please unblock

### ISSUE THREAD

**Issue by Mind777** [hagezi/dns-blocklists#798]
These sites are being blocked by your blocklist, please whitelist!

https://www.naturalnews.com/index.html
https://www.infowars.com/
https://www.coasttocoastam.com/shows/

**Comment by hagezi** [comment]
Thank, all blocked because they are clickbait, will be re-checked.

**Comment by Mind777** [comment]
> Thanks, all blocked because they are clickbait, will be re-checked.

Not clickbait, just alternative news sources. 

I use your blocklist to protect me from malicious stuff online, not to censor my content!

**Comment by hagezi** [comment]
Take a deep breath, I'll look at it in a minute. Which list version do you use?

**Comment by Mind777** [comment]
Version: 2023.0330.2300.27

Thanks

**Comment by hagezi** [comment]
Light, Normal, Pro, Pro.Plus or Ultimate?

**Comment by Mind777** [comment]
Title: HaGeZi's Pro DNS Blocklist

**Comment by hagezi** [comment]
Fixed.

**Comment by Mind777** [comment]
Thanks!
