### ISSUE TITLE
Crypto Scam

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#799]
#### Which domain(s) should be blocked?

coinstoretra.com
bitstenali.com

#### Why should the domain(s) be blocked?

Scam. Signs: Crypto Ponzi scheme, NRD
https://www.reddit.com/r/Scams/comments/127a4i3/psa_ponzi_crypto_mining_scam_coinstore_pro/

@durablenapkin

**Comment by hagezi** [comment]
Thanks, adeed.

**Comment by durablenapkin** [comment]
Queued both, thanks
