### ISSUE TITLE
FP

### ISSUE THREAD

**Issue by sr093906** [hagezi/dns-blocklists#8]
mail.tsinghua.edu.cn

This is portal of Tsinghua University mail system.

A reminder: one of 1Hosts' source is **top 1m domain list by Cisco Umbrella**. 

https://github.com/badmojr/1Hosts/blob/master/-data/lists/assets.txt (http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip)

Does the source is included in the so-called lite version? Shouldn't this list used more as an allow list? I know there are many ad, tracking and even gambling and porn sites are among the world's top domains. But compared to legit ones, the amount is not many. Using the list as a source is a bold and even aggressive move in my view.

**Comment by hagezi** [comment]
Thanks.

The domain stemmed from the OISD, NoTracking, SomeoneWhocares and Steven Black blocklists.

Domain was removed.

I use the toplists partly for my personal whitelist.

**Comment by hagezi** [comment]
ping @sjhgvr

**Comment by sjhgvr** [comment]
> ping @sjhgvr @notracking @StevenBlack
Fixed in oisd

**Comment by badmojr** [comment]
> Does the source is included in the so-called lite version? Shouldn't this list used more as an allow list? I know there are many ad, tracking and even gambling and porn sites are among the world's top domains. But compared to legit ones, the amount is not many. Using the list as a source is a bold and even aggressive move in my view.

Hello.
It's only included on **Xtra.**

**Comment by notracking** [comment]
Original source is https://someonewhocares.org/hosts/
Fixed in notracking list, thanks for the ping!
