### ISSUE TITLE
filter lists

### ISSUE THREAD

**Issue by suricloud** [hagezi/dns-blocklists#80]
Hi i see you recommend these block list on nextdns  and adguard.
But is adguard dns filter not already included in oisd? 

Normal | 1Hosts (Lite) + AdGuard DNS filter + OISD

**Comment by hagezi** [comment]
Hi,

partly it is included, the AdGuardDNS list contains some domains that are whitelisted in oisd.

But these are probably included in 1 Hosts. One would have to check this.

Kind regards,
Gerd

**Comment by suricloud** [comment]
Hi,

Oh ok,so you recommend to add adguard dns filter in the list?
What about this combination for home wifi and mobile config.
1Hosts pro + AdGuard DNS filter + OISD

**Comment by hagezi** [comment]
Besides the oisd, I think the 1Host list is mandatory, it is extremely effective and catches a lot of what was whitelisted in the osid. The AdGuardDNS list is a bonus that you can take or not.
The important domains are present in the 1Hosts lists.

**Comment by suricloud** [comment]
Ok thanks.

**Comment by hagezi** [comment]
It costs nothing to take the AdGuardDNS list with you, it is a well maintained list.
