### ISSUE TITLE
vod.detik.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#800]
#### What adblocker/DNS cloud service are you using?

AdGuardHome

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
vod.detik.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Blocking makes video in detik.com article unable to play.

**Comment by hagezi** [comment]
Thanks, will be removed.
