### ISSUE TITLE
Scam/Spam Sites

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#804]
#### Which domain(s) should be blocked?

venezuelabaseballjerseys.com
italyworldbaseballclassic.com
storeoregononline.com
tlstoreonline.com
storecollegeonline.com
shoptcuhornedonline.com
shopsyracuseonline.com

#### Why should the domain(s) be blocked?

Sites spammed on GrapheneOS forum. All NRDs.
@durablenapkin

https://discuss.grapheneos.org/d/4222-tim-tebow-in-direction-of-exhibit-baseball-abilities-inside-tryout

https://discuss.grapheneos.org/d/4221-the-10-least-difficult-times-of-the-nationals-postseason-rated

https://discuss.grapheneos.org/d/4220-milwaukee-brewers-69-60-vs-arizona-diamondbacks-61-68

https://discuss.grapheneos.org/d/4219-milwaukee-brewers-57-47-vs-pittsburgh-pirates-42-62

https://discuss.grapheneos.org/d/4218-mvbrewers-5-rowdy-tellez-brew-staff-ball

https://discuss.grapheneos.org/d/4217-brewers-concerning-groups-rying-forandrew-benintendi-for-every-article

https://discuss.grapheneos.org/d/4216-milwaukee-brewers-65-56-los-angeles-dodgers-84-37

**Comment by hagezi** [comment]
Thanks, added.

**Comment by durablenapkin** [comment]
All queued, thanks
