### ISSUE TITLE
Whitelist garry.windscribe.com

### ISSUE THREAD

**Issue by yegors** [hagezi/dns-blocklists#806]
#### What adblocker/DNS cloud service are you using?

Custom

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
garry.windscribe.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Windscribe support livechat/chatbot.

**Comment by hagezi** [comment]
@yokoffing
