### ISSUE TITLE
Afrinic

### ISSUE THREAD

**Issue by xRuffKez** [hagezi/dns-blocklists#814]
#### What adblocker/DNS cloud service are you using?

NextDNS, Adguard, AdAway

#### Which blocklists are used?
Pro

#### Which domain(s) should be unblocked?
afrinic.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
RIRData from ftp.afrinic.net cannot be fetched by my servers.

**Comment by hagezi** [comment]
Thanks,will be removed. Ping @notracking

**Comment by notracking** [comment]
Thanks! Was just solved via: https://github.com/notracking/hosts-blocklists/issues/865
