### ISSUE TITLE
OneTrust Popups/Annoyances

### ISSUE THREAD

**Issue by Eow2022yia** [hagezi/dns-blocklists#815]
#### Which domain(s) should be blocked?

my.onetrust.com
geolocation.onetrust.com
mobile-data.onetrust.io

#### Why should the domain(s) be blocked?

Causing unnecessary pop-ups for cookie consents, services are still functional with these OneTrust domains blacklisted, this request is for ProPlus and Ultimate only

**Comment by hagezi** [comment]
It is not a good idea to completely block cookie dialogues at the DNS level. This breaks things on various pages because the cookie dialogues cannot be confirmed or rejected. Videos that don't start, embedded posts that don't show, images that don't show and more.
I can't block that for the masses.
Content blockers should do the blocking and they do it reliably.

For example, mobile-data.onetrust.io is on the whitelist because otherwise some German and Austrian apps won't start.

**Comment by Eow2022yia** [comment]
> It is not a good idea to completely block cookie dialogues at the DNS level. This breaks things on various pages because the cookie dialogues cannot be confirmed or rejected. Videos that don't start, embedded posts that don't show, images that don't show and more.
> I can't block that for the masses.
> Content blockers should do the blocking and they do it reliably.
> 
> For example, mobile-data.onetrust.io is on the whitelist because otherwise some German and Austrian apps won't start.

Hi Hagezi, thank you for your prompt response.

I do really love your blocklists, I have just discovered them as I never knew about them before, the only issue is that these Cookie messages can't be blocked unless these OneTrust domains are blocked too.

Is there anyway of these being blocked on the Ultimate list only? Or could you not make similar to what QuidsUp makes and do a separate list for just annoyances?

**Comment by hagezi** [comment]
The annoyances that can be blocked at DNS level have been blocked. You can't block everything at DNS level. What can't be blocked there is done by uBlock and co.

If blocking onetrust has no restrictions for you, put it on your personal blacklist.

**Comment by Eow2022yia** [comment]
> The annoyances that can be blocked at DNS level have been blocked. You can't block everything at DNS level. What can't be blocked there is done by uBlock and co.
> 
> If blocking onetrust has no restrictions for you, put it on your personal blacklist.

But these domains are meant to be blocked at a DNS-level to stop the pop-ups from appearing within applications, if this was within a web browser I could just use ublock, this process has been completed before on other blocklists so to state that it is not meant for DNS-level blocking is not true, why not have an annoyance list?

**Comment by hagezi** [comment]
Yes, but blocking breaks things for the masses. Therefore, it is something for the personal blacklist.

**Comment by hagezi** [comment]
You can also use a very strict list like 1Host Xtra.

**Comment by Eow2022yia** [comment]
> You can also use a very strict list like 1Host Xtra.

I can but these lists break a lot of stuff :(
