### ISSUE TITLE
exacttarget.com

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#818]
Hi Gerd,

I just ran into this email tracker, which wasn't blocked using Pro (or Pro++). You block multiple of its subdomains, but not the ones I was targeted by. I would request you consider blocking the root, as the format of the URL I was targeted with (as part of an 'update'/marketing email) suggests they use a lot of generic auto-generated subdomains.

#### Which domain(s) should be blocked?
||exacttarget.com
||exacttraget.com.edgesuite.net

#### Why should the domain(s) be blocked?
Pro only blocks `||scmetrics.exacttarget.com^`. Pro++ blocks: 

```
||ally-mc.exacttarget.com^
||inbox.exacttarget.com^
||mc.login.exacttarget.com^
||mc.exacttarget.com^
||mta.exacttarget.com^
||origin-mc.exacttarget.com^
||s1.exacttarget.com^
||mc.s10.exacttarget.com^
||origin-mc.s10.exacttarget.com^
||mc.s4.exacttarget.com^
||origin-mc.s4.exacttarget.com^
||mc.s6.exacttarget.com^
||origin-mc.s6.exacttarget.com^
||pub.s6.exacttarget.com^
||view.s6.exacttarget.com^
||bounce.s7.exacttarget.com^
||image.s7.exacttarget.com^
||mc.s7.exacttarget.com^
||origin-image.s7.exacttarget.com^
||origin-mc.s7.exacttarget.com^
||view.s7.exacttarget.com^
||scmetrics.exacttarget.com^
```

However, I opened an email from BT/Openreach (UK ISP and broadband infrastructure company) and my logs show the following were allowed (not blocked):

```
click.virt.s50.exacttarget.com
click.info.openreach.co.uk (CNAME of exacttarget.com)
image.info.openreach.co.uk (CNAME of images.s50.exacttarget.com.edgesuite.net)
```

I have now blacklisted them and the email still opens fine visually. No changes at all, just the trackers are blocked. I blocked them thus (which may be too aggressive for your list?):

```
||*exacttarget.com*^
||*info.openreach.*^
```

I wanted to report them for your consideration. The root domain is just a place to advertise/buy tracking so is it really a problem to block it at the root, in order to catch all their auto-generated tracking subdomains? I would suggest not, but your philosophy may differ of course! :) Best wishes as always.

**Comment by hagezi** [comment]
This are referral Domains, see: https://github.com/hagezi/dns-blocklists#referral

**Comment by RainmakerRaw** [comment]
Ah, thanks - I missed that! That would make sense for the `click.*` domain, but not so much for the non-clickable `image.info*' domain. Regardless, it seems from your explanation it is basically harmless. Thank you!

**Comment by hagezi** [comment]
Referral whitelisted:

```
@@||m.exactag.com^
@@||tp-emea.exactag.com^
@@||click.virt.s*.exacttarget.com^
@@||view.virt.s*.exacttarget.com^
```

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt

**Comment by RainmakerRaw** [comment]
Thank you again for the insights.

**Comment by hagezi** [comment]
What is image.info.openreach.co.uk for? Pixel tracker?

**Comment by hagezi** [comment]
I have not found any popular block list that blocks image.info.openreach.co.uk. Tested with deep CNAME inspection.

**Comment by hagezi** [comment]
images.s*.exacttarget.com.edgesuite.net are used for images in e-mails.

**Comment by RainmakerRaw** [comment]
It was the images.info* that drew my attention. The email doesn't appear to load any differently whether that domain is blocked or allowed. However, that could equally be due to caching in my mail clients. I have upgraded back to Pro++ for my own DNS and will monitor accordingly. Thanks again for all your hard work, you should open a tip jar!
