### ISSUE TITLE
limcologisticsusa.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#824]
#### Which domain(s) should be blocked?

limcologisticsusa.com

#### Why should the domain(s) be blocked?

Fake site. Real site is: https://www.limcologistics.com/ , NRD, parcel mule scam

https://www.reddit.com/r/Scams/comments/12b7yc1/got_hired_for_a_packaging_inspector_job/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued
