### ISSUE TITLE
get.mndbdy.ly

### ISSUE THREAD

**Issue by mahtd** [hagezi/dns-blocklists#826]
#### What adblocker/DNS cloud service are you using?

uBlock Origin / NextDNS

#### Which blocklists are used?
HaGeZi Pro

#### Which domain(s) should be unblocked?
get.mndbdy.ly

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Used in the unsubscribe links from Elements Massage emails, in the form `https://get.mndbdy.ly/e/<unique code>`

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by notracking** [comment]
Thanks, fixed!
