### ISSUE TITLE
invol.co

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#827]
#### What adblocker/DNS cloud service are you using?

AdguardHome

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
invol.co

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
I think it's better to leave it in a less aggressive blocklist. This relates to product affiliate links, which influencers use to market a product with a referral link which directs to several shopping sites listed on involve.asia

**Comment by hagezi** [comment]
@MagicalAlchemist 
Whitelist it only for the non agressive lists, light to pro?
It is used for deeplinking, so I am considering whitelisting it for all lists. What do you think?

```
Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          BLOCKED
 - CONTROLD        BLOCKED
 - DNSforge.de     BLOCKED
 - EasyList        OK
 - HaGeZi.LIGHT    BLOCKED
 - HaGeZi.NORMAL   BLOCKED
 - HaGeZi.PERSONAL BLOCKED
 - HaGeZi.PRO      BLOCKED
 - HaGeZi.PRO.PLUS BLOCKED
 - HaGeZi.ULTIMATE BLOCKED
 - hBlock          BLOCKED
 - Lightswitch05   OK
 - NextDNS         BLOCKED
 - NoTracking      BLOCKED
 - OISD            BLOCKED
 - QuidsUp.NOTRACK OK
 - StevenBlack     BLOCKED
```

**Comment by MagicalAlchemist** [comment]
That's fine. Go ahead.

**Comment by MagicalAlchemist** [comment]
After I thought about it, it's better to stay blocked on the ultimate list because invol.co plays a role in showing ads.

For example on the website msn.com

![Screenshot_2](https://github.com/hagezi/dns-blocklists/assets/69599160/a36f8d5d-6c0e-4cf5-8d0b-71d58faeb6a0)

**Comment by mangkoran** [comment]
Sorry for necrobump. I see that invol.co is not whitelisted anymore. Is it intended?

**Comment by hagezi** [comment]
Only blocked in the aggressive lists (Pro++/Ultimate) ...
