### ISSUE TITLE
Unnecessary domains for MyQ App

### ISSUE THREAD

**Issue by Fail-Safe** [hagezi/dns-blocklists#828]
#### Which domain(s) should be blocked?
h29.hubs.tend-us.tendplatform.com
app.isecurityplus.com
app.tendinsights.com
server.seedonk.com

#### Why should the domain(s) be blocked?
While opening the [MyQ](https://www.myq.com/) app on iOS, the above domains are loaded, but do not cause any functionality loss when blocked. Research into these domains led me to find that the latter three domains, in particular, are included in the [1Hosts Xtra list](https://raw.githubusercontent.com/badmojr/1Hosts/master/Xtra/domains.txt) as well.

**Comment by hagezi** [comment]
Hi, thanks.

the domains all belong to https://www.tendinsights.com/ (Home Security Wifi Cameras) and iSecurity+(Home Video Monitoring). They lead to restrictions when using something from the Tend platform or iSecurity+.

The two `app.*` domains point to a login form.

`server.seedonk.com` is a server for Home Video Monitoring: _"After opening the iSecurity+ app, you will be brought to the login screen. ... set to server.seedonk.com unless you are running your own server"_

`*.hubs.tend-us.tendplatform.com` belong to Tend platform hubs.

I don't see anything blockable for the masses here. If not needed, it is rather something for the personal blacklist. I don't see any tracking or anything like that here. Apart from the fact that you should not provide your home videos from security cameras to some external cloud platform.

**Comment by Fail-Safe** [comment]
Understood and thank you for the thorough follow-up on the submission! I agree with where you landed on this one based on your research.

I will keep them on my personal blacklist as they're definitely not needed in my case. Thanks again!

**Comment by hagezi** [comment]
Thank you, of course one can ask why they are contacted if the Tend Platform is not used. This is a question for the manufacturer of the MyQ app.
