### ISSUE TITLE
fake fitgirl sites

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#829]
#### Which domain(s) should be blocked?
fitgirl-repacks-site.org
fitgirlrepacksite.com
fitgirl-repacks.vip

#### Why should the domain(s) be blocked?
fake websites of fitgirl-repacks.site

**Comment by hagezi** [comment]
Thanks, will be added.

**Comment by hagezi** [comment]
@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks
