### ISSUE TITLE
simpleanalytics.com

### ISSUE THREAD

**Issue by ghost** [hagezi/dns-blocklists#830]
#### What adblocker/DNS cloud service are you using?

> NextDNS

#### Which blocklists are used?
> HaGeZi - Multi PRO

#### Which domain(s) should be unblocked?
> simpleanalytics.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
> I use it as a Google Analytics and it's not just a mere analytics thingy.

> You may check to see [why](https://www.simpleanalytics.com/#why) this should be whitelisted.

**Comment by yokoffing** [comment]
To my knowledge, we still block analytics even if they’re privacy-preserving.

**Comment by hagezi** [comment]
Correct @yokoffing, it is analysis and not necessary for the function of websites, therefore it is blocked.
