### ISSUE TITLE
priority-ship.info

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#831]
#### Which domain(s) should be blocked?

priority-ship.info
postcanada.priority-ship.info

#### Why should the domain(s) be blocked?

SMS Phishing, delivery scam, NRD
https://www.reddit.com/r/Scams/comments/12c3k2g/hi_need_help_to_verify/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks
