### ISSUE TITLE
m.coinexeu.vip

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#834]
#### Which domain(s) should be blocked?

m.coinexeu.vip

`coinexeu.vip` itself doesn't resolve.

#### Why should the domain(s) be blocked?

Pig butchering scam, NRD
https://www.reddit.com/r/Scams/comments/12bqiom/is_httpsmcoinexeuviph5_scam/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks
