### ISSUE TITLE
edu.wsj.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#835]
#### What adblocker/DNS cloud service are you using?

Control D

#### Which blocklists are used?
Pro++

#### Which domain(s) should be unblocked?
edu.wsj.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
University edition of the WSJ

**Comment by hagezi** [comment]
Thanks, ping source @notracking

FYI: via AdGuard CNAME trackers - go.pardot.com

**Comment by notracking** [comment]
And also: pi.pardot.com Thanks, fixed!
