### ISSUE TITLE
analytics on element

### ISSUE THREAD

**Issue by cinatime** [hagezi/dns-blocklists#836]
#### Which domain(s) should be blocked?
posthog.hss.element.io

#### Why should the domain(s) be blocked?
Used for analytics in element
posthog.com is already blacklisted in hagezi ultimate

https://github.com/vector-im/element-android/issues/8020
https://github.com/vector-im/element-web/issues/19745
https://www.kuketz-blog.de/matrix-element-client-sendet-ping-an-posthog-hss-element-io/

**Comment by hagezi** [comment]
Thanks, will be added.
