### ISSUE TITLE
hub-odc.samsungapps.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#841]
#### What adblocker/DNS cloud service are you using?

AdGuardHome

#### Which blocklists are used?
Ultimate

#### Which domain(s) should be unblocked?
hub-odc.samsungapps.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Can't connect to Galaxy Themes feature,

**Comment by hagezi** [comment]
Thanks, will be removed.
