### ISSUE TITLE
[PRO++] Again Gofile.io is blocked

### ISSUE THREAD

**Issue by nightznero** [hagezi/dns-blocklists#843]
Helloz HaGeZi,
![Screenshot_20230405_193921_AdGuard](https://user-images.githubusercontent.com/61750641/230161043-984cf918-0486-4482-996a-ec14723351d9.jpg)

Gofile is blocked once again as it was on #625 
Best regards!

**Comment by nightznero** [comment]
There are not much stuffs to block on Gofile.io, there is no ads or anything that  DNS can do. Manifests and others but it's must be ADB-Syntax

**Comment by hagezi** [comment]
Blocked by URLhaus Malware filter, will add `store*.gofile.io` to whitelist.
