### ISSUE TITLE
你的规则源有中国的？

### ISSUE THREAD

**Issue by biange200** [hagezi/dns-blocklists#85]
你好 请问一下 你的规则来源有没有包含中国大陆的规则
如果在中国 应该选择哪个规则？

**Comment by hagezi** [comment]
Yes, try Pro++.

**Comment by biange200** [comment]
Other rule sources don't include rules for China? I'm using rethinkdns and blokada v5 on my phone now



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月02日 13:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [hagezi/dns-blocklists] 你的规则源有中国的？ (Issue #85) |

Yes, try Pro++.

**Comment by hagezi** [comment]
Yes, but most of them are in the Pro++. In RethinkDNS, the Pro++ is also available for selection.

**Comment by biange200** [comment]
你的规则会导致卡网  图片加载不出来或是很慢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月03日 00:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [hagezi/dns-blocklists] 你的规则源有中国的？ (Issue #85) |

Closed #85 as completed.

**Comment by hagezi** [comment]
What rules, where are images not loaded? Without details I can't check.

**Comment by biange200** [comment]
| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月05日 13:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [hagezi/dns-blocklists] 你的规则源有中国的？ (Issue #85) |

What rules, where are images not loaded? Without details I can't check.

**Comment by hagezi** [comment]
![grafik](https://user-images.githubusercontent.com/104343908/205582317-03f7ab17-63ef-445e-9095-9ba9262d8c8a.png)

I see that from your answer?

**Comment by biange200** [comment]
你看 开启你的规则订阅 网络非常卡 如果关闭你的规则订阅 网络会正常
我发了视频给你



***@***.***
***@***.***

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| SVID_20221205_161124_1.mp4 |
| |
| (7.6M,2022年12月20日 16:18 到期) |
| |
| 下载 |
| |
| |

**Comment by hagezi** [comment]
@biange200 
The rules can not be identified. What should I do with it: ***@***.***

Please do not reply via mail but directly in the issue!

**Comment by hagezi** [comment]
I can not see the rules here are only stars displayed! It also does no good if you send me a video as an attachment. Just send me the link to the video.

**Comment by biange200** [comment]
可能被屏蔽了 我这是onedrive的   https://1drv.ms/v/s!App3sf6eizujvkSm1-eJ2eVhY8C5



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月05日 18:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [hagezi/dns-blocklists] 你的规则源有中国的？ (Issue #85) |

I can not see the rules here are only stars displayed! It also does no good if you send me a video as an attachment. Just send me the link to the video.

**Comment by hagezi** [comment]
I give up, if you are able to provide proper information, I will investigate the problem. I don't know if you don't want to understand or something else.

Closing ...

**Comment by hagezi** [comment]
Open https://github.com/hagezi/dns-blocklists/issues/85 in the browser and see what I see. Nothing useful!

**Comment by biange200** [comment]
我看到了 我发给你的截图 全部变成**了 这是怎么回事



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月05日 18:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [hagezi/dns-blocklists] 你的规则源有中国的？ (Issue #85) |

Open #85 in the browser and see what I see. Nothing useful!

**Comment by hagezi** [comment]
For the umpteenth time, do not reply via mail in the issue, but call the link of the issue in the browser and reply there! When replying via mail, some things seem to get lost.
And please, in English.
