### ISSUE TITLE
nlepfpteg.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#852]
#### Which domain(s) should be blocked?

nlepfpteg.com

#### Why should the domain(s) be blocked?

Fake Hoka (hoka.com) store.
https://www.reddit.com/r/Scams/comments/12d7qd6/is_this_website_for_hoka_shoes_a_scam/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks
