### ISSUE TITLE
https://segura-moto.fr

### ISSUE THREAD

**Issue by Quorum75** [hagezi/dns-blocklists#856]
#### What adblocker/DNS cloud service are you using?

HaGeZi - Multi PRO++, HaGeZi - Multi NORMAL, HaGeZi - Multi LIGHT, HaGeZi - Multi PRO and HaGeZi - Multi ULTIMATE.

https://segura-moto.fr

Online motorbike mroducts

**Comment by hagezi** [comment]
Flagged:
https://www.urlvoid.com/scan/segura-moto.fr/

Blocked because of phishing activities.

**Comment by hagezi** [comment]
Trojan detection is from 2020:

![image](https://user-images.githubusercontent.com/104343908/230400789-55729f8c-3ae9-4a2c-918b-d148af002680.jpeg)

Seems to be clean now:

![image](https://user-images.githubusercontent.com/104343908/230401194-6c6aff4b-a49f-4cde-894d-9029a35b0748.jpeg)

Blocked by Phishing.Army: ping @drego85

**Comment by Quorum75** [comment]
Thanks for the info. Still strange feedback. I never had any issue with this site before which is legit.
