### ISSUE TITLE
raiffeisenmining.com

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#862]
#### Which domain(s) should be blocked?

raiffeisenmining.com

#### Why should the domain(s) be blocked?

Crypto scam, pig butchering scam, NRD
https://www.reddit.com/r/Scams/comments/12e9bmz/raiffeisen_bank_mining_is_this_a_scam/

@durablenapkin

**Comment by durablenapkin** [comment]
Thanks, queued this and all prior
