### ISSUE TITLE
content.ctfs.com

### ISSUE THREAD

**Issue by sferna01** [hagezi/dns-blocklists#865]
#### What adblocker/DNS cloud service are you using?

Control - D

#### Which blocklists are used?
Pro-Plus

#### Which domain(s) should be unblocked?
content.ctfs.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is a retailer in Canada. Mobile version (sign-in) does not work when content.ctfs.com is blocked.

**Comment by hagezi** [comment]
Thanks, will be removed, ping @notracking.

**Comment by notracking** [comment]
Thanks, fixed!
