### ISSUE TITLE
Whitelist dns.digitale-gesellschaft.ch

### ISSUE THREAD

**Issue by xopez** [hagezi/dns-blocklists#87]
One of your aggregated blocklists include the domain dns.digitale-gesellschaft.ch. IT's a false positiv. They doesn't track anything since they are an association from Switzerland. On this domain they offer a free uncesored dns server.

**Comment by hagezi** [comment]
ping @notracking

**Comment by hagezi** [comment]
Thanks @xopez will be removed from the lists in the current update.

**Comment by hagezi** [comment]
Fixed

**Comment by notracking** [comment]
Fixed, thanks!
