### ISSUE TITLE
UPS Phishing Sites

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#875]
#### Which domain(s) should be blocked?

7laced.com
vcfdg.com

#### Why should the domain(s) be blocked?

UPS phishing sites.
https://www.reddit.com/r/Scams/comments/12f5dnk/so_i_ordered_a_controller_from_hex_gaming_and_i/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued this and the others, thanks
