### ISSUE TITLE
Antutu Analytics and Telemetry

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#877]
#### Which domain(s) should be blocked?
dg.k.jd.com
bu.antutu.net
yanjiapi.antutu.net
w1.kskwai.com
srtj.antutu.net
mapi.m.jd.com
zt.gifshow.com
autovote.antutu.net
autovote.antutu.club

#### Why should the domain(s) be blocked?
The apps make lots of domain calls after you agree to their privacy terms.

**Comment by hagezi** [comment]
Thanks, since I cannot check this exactly, I will only block the domains in the aggressive lists for the time being.
