### ISSUE TITLE
dana.id

### ISSUE THREAD

**Issue by SantriKode** [hagezi/dns-blocklists#879]
#### What adblocker/DNS cloud service are you using?

RethinkDNS

#### Which blocklists are used?
ULTIMATE

#### Which domain(s) should be unblocked?
dana.id

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It contains link.dana.id for online payment of Indonesian people. Dana Wallet use these link to do payment confirmation from web and application.

**Comment by hagezi** [comment]
ping @notracking

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by notracking** [comment]
> ping @notracking

It's not in the notracking list? (or am I missing something..?)

**Comment by hagezi** [comment]
Sorry, my mistake.

**Comment by SantriKode** [comment]
Recently, still had issue with m.dana.id connection

**Comment by hagezi** [comment]
@SantriKode only mas-log1.saas.dana.id is blocked.

Is it possible that the lists in RethinkDNS have not yet been updated? I think they are only updated every x days.

The CNAMEs are also not blocked:
custom.bnc.lt
m.dana.id.edgekey.net.

**Comment by hagezi** [comment]
@SantriKode https://rethinkdns.com/search?q=link.dana.id
_RethinkDNS blocklists last updated on Sat, 01 Apr 2023 21:56:03 GMT_

**Comment by notracking** [comment]
I had the following still hosted, they should be whitelisted with the next auto update!

```
link.dana.id - adguard cname trackers
bnc.lt (CNAME) - craiu mobile trackers
```
