### ISSUE TITLE
rethinkdns pro++规则卡网

### ISSUE THREAD

**Issue by biange200** [hagezi/dns-blocklists#88]
![Screenshot_20221205_161634.jpg](https://user-images.githubusercontent.com/37582806/205632019-1bc8a02d-7db5-4776-83b4-f08851bab4f2.jpg)![Screenshot_20221205_132002.jpg](https://user-images.githubusercontent.com/37582806/205632197-077063d1-2e21-4991-9494-879092793d00.jpg)![Screenshot_20221205_130451.jpg](https://user-images.githubusercontent.com/37582806/205632222-927ffb90-026a-4e7a-aa97-d6e2e1bce0d8.jpg)![Screenshot_20221205_132002.jpg](https://user-images.githubusercontent.com/37582806/205632257-ba3b150a-54dd-4dd6-bdb1-2134e2c16538.jpg)
![Screenshot_20221205_130641.jpg](https://user-images.githubusercontent.com/37582806/205632402-7e0c9393-0e77-43b6-be53-398d339eee60.jpg)

使用pro或是pro++ 会导致卡网 网络非常慢 图片需要很长时间加载出来 视频无法播放

**Comment by hagezi** [comment]
What should I do with it? Please post the link to the page where the problem occurs, I can't read it from the screenshots.

**Comment by hagezi** [comment]
And again you answer by mail, and again I can't do anything with the answer, I've had enough. Are you kidding me?

What's so hard about posting the link where the video doesn't load?
