### ISSUE TITLE
whitelist request

### ISSUE THREAD

**Issue by 0kJackoo** [hagezi/dns-blocklists#881]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?

HaGeZi Multi PRO

#### Which domain(s) should be unblocked?

nexus.ensighten.com
p11.techlab-cdn.com
logs.juspay.in

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

breaks home depot checkout and login
needed for citizens bank
needed for ola money

**Comment by hagezi** [comment]
Thanks, `ensighten.com` and `techlab-cdn.com` are trackers,, will be whitelisted in the none aggressive lists (light to pro) only.

**Comment by IsHacker003** [comment]
> Thanks, `ensighten.com` and `techlab-cdn.com` are trackers,, will be whitelisted in the none aggressive lists (light to pro) only.

Why was `logs.juspay.in` unblocked? It's a log collection tracker.
