### ISSUE TITLE
tracker.dominos.com incorrectly blocked by Pro, Pro+

### ISSUE THREAD

**Issue by chr-lei** [hagezi/dns-blocklists#882]
#### What adblocker/DNS cloud service are you using?
ControlD

#### Which blocklists are used?
Hagezi Pro+ (also occurs with Pro)

#### Which domain(s) should be unblocked?
tracker.dominos.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This domain is used for the Domino's delivery tracker page/app, and is not a ads tracker. With this domain blocked the Domino's app and website delivery tracking does not work.

**Comment by hagezi** [comment]
Thanks, will be removed.
