### ISSUE TITLE
www.beaute-test.com

### ISSUE THREAD

**Issue by RandomUsername404** [hagezi/dns-blocklists#890]
#### What adblocker/DNS cloud service are you using?

ControlD

#### Which blocklists are used?
Hagezi's DNS - Pro

#### Which domain(s) should be unblocked?
www.beaute-test.com
static.beaute-test.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Beaute-test.com  is a website where people grade beauty products. It's perfectly legit.

**Comment by hagezi** [comment]
Thanks, I will remove the domain when the current full update has run through.

Ping source: @badmojr
