### ISSUE TITLE
FP: Roblox

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#891]
Greetings Gerd, and Happy Easter if you celebrate it!

Regarding `||ephemeralcounters.api.roblox.com^` which is in all your lists. For three days now, I have been chasing down a fatal error in the Windows/Microsoft Store version of the Roblox app. Every time we launch it, the app opens for a second and then just disappears/crashes. No errors are shown. The app had worked perfectly until recently so my children were very vocal about it breaking! :) 

It didn't even cross my mind that this list could be at fault, which is a testament to how excellent it usually is. I even wiped the laptop and reinstalled Windows 11 after basic troubleshooting didn't solve it (reset the app, repair it, reinstall MS Store etc), because I just didn't think DNS would be a problem here. Finally, I realised that the domain mentioned above was being blocked, but that I hadn't seen it in the AGH logs until very recently. 

After unblocking that domain with `||ephemeralcounters.api.roblox.com^$badfilter`, the Roblox app now finally loads again on Windows, and my children have given me some peace. Commenting that rule and blocking the domain again to test causes the app to crash on launch once more. It seems to be a confirmed FP, or at least it interferes with functionality to the extent that the app is rendered useless when it is blocked. 

Please consider removal? Thanks so much.
Best wishes,

Lee

**Comment by hagezi** [comment]
Thank you, also for the details. I will remove the domain when the current full update has run through.

Happy Easter,
Gerd

**Comment by RainmakerRaw** [comment]
Thanks so much again, your work means a lot. Sorry to bother you.
All the best,

Lee
