### ISSUE TITLE
false positive for personal

### ISSUE THREAD

**Issue by humsg** [hagezi/dns-blocklists#9]
Hi, I track down from oisd.nl list, link below for personal is included:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/personal.txt,
please remove d.ifengimg.com from your list, and it is image url for news site of www.ifeng.com

thank you

**Comment by hagezi** [comment]
Thanks, removed. https://github.com/hagezi/dns-blocklists/commit/0149bd91f55abd66be14a761b876aca7332ec728

**Comment by humsg** [comment]
thank you
