### ISSUE TITLE
Do you report dead hosts/domains to source so others can also benefit?

### ISSUE THREAD

**Issue by thomasmerz** [hagezi/dns-blocklists#91]
Hi @hagezi , users that use the same source as you, but not consuming your refined lists, could also benefit from your good work. So their blocklists would be smaller and free from dead hosts/domains. I wonder how many of my many "domains on adlist" are dead…

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/18568381/205956444-179f48f4-fbc4-4002-94e2-82d0cf735c26.png">

So do you (irregularely or automatically) report them to the source? This would really be nice 😄

**Comment by hagezi** [comment]
Of course, anyone who wants to use them can do so. But most don't remove dead domains from malware lists because you don't know when they will come back.

**Comment by hagezi** [comment]
fixed
