### ISSUE TITLE
contaboserver.net

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#913]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?
Multi Ultimate

#### Which domain(s) should be unblocked?
`contaboserver.net`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
It is a VPS, it can break many sites for example `cdn.nickchan.lol`.

**Comment by hagezi** [comment]
Ping @bongochong

**Comment by bongochong** [comment]
Looks like I manually added this to my backend script which generates additional supplements a good while back. Was likely an overzealous addition in response to seeing a few malware-serving subdomains. My mistake. Will remove. Thank you for the ping.
