### ISSUE TITLE
phonearena.com

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#918]
Transferred from reddit:

_Hi, i use your blocklist, Multi Ultimate on Nextdns and today i noticed that phonearena is being blocked, and it is a legitimate site. If you could check this i would appreciate. By the way, thank you for your effort for making this blocklists._

https://www.phonearena.com

**Comment by hagezi** [comment]
ping source: @bigdargon

**Comment by bigdargon** [comment]
@hagezi Removed. Thanks for the ping! This domain, I previously built from Disconnect's basic list https://blocklist-tools.developerdan.com/entries/search?q=phonearena.com
