### ISSUE TITLE
Multi Light Aggressive

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#919]
#### Which blocklists are used?

Multi LIGHT

#### Which domain(s) should be unblocked?

www3.doubleclick.net
securepubads.g.doubleclick.net
dygassets.dygdigital.com
ad.medyanetads.com

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

https://puhutv.com/ruya-6-bolum-izle
https://www.kanald.com.tr/arka-sokaklar/fragmanlar/arka-sokaklar-17-sezon-fragmani

Video contents cannot be played.

**Comment by hagezi** [comment]
Whitelisting doubleclick.net causes ads to be displayed on other pages.
g.doubleclick.net is one of the strongest AdBlock rules.

So it's something for the personal whitelist, but I recommend you to avoid such sites ...

**Comment by hagezi** [comment]
Aggressive? No, `g.doubleclick.net` is blocked in all blocklists. There are some pages that don't work because of this, see also the OISD FAQ from @sjhgvr: https://oisd.nl/faq#knownissues
