### ISSUE TITLE
Fake American Airlines Sites

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#920]
#### Which domain(s) should be blocked?

aadirone.cc
applydiraadd.com

#### Why should the domain(s) be blocked?

Fake American Airlines phishing sites
https://www.reddit.com/r/Scams/comments/12j8l68/is_this_real_i_have_been_looking_for_a_new_job/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks
