### ISSUE TITLE
OJK Scam List #2

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#923]
#### Which domain(s) should be blocked?
www.dompetaman.live
www.duitpanas.top
www.danarakyatol.com
www.danapintar.club
www.danainstan.xyz
www.danadarurat.net
www.cashadvancexy.xyz
www.bantucepat.com
wangsakti.com
www.tunairupiah.xyz
www.uangqu.online
www.selamatpinjam.space
www.punyauang.xyz
www.casha.xyz
www.tigerkash.com
www.ngreditinaja.top
www.majucash.xyz
www.modalsaya.xyz
www.uangmudahapp.com
krediteasypro.com
danapro.net
www.kredit-rupiah.com
www.ringantunai.com
www.pinjamanduit.lol
www.pinjamnow.my.id
pasarkta.pasaruang.id
origin.tnail.cc
newdompet.com
meminjamsaya.com
koperasi.naricash.com
dompetexcellent.com
dearrupiah.com
danasenang.com
danaaman.xyz

#### Why should the domain(s) be blocked?
Scam.
https://www.ojk.go.id/waspada-investasi/id/alert-portal/Pages/default.aspx

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks
