### ISSUE TITLE
ecs-online.ffm.to

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#925]
#### Which domain(s) should be blocked?

ecs-online.ffm.to

#### Why should the domain(s) be blocked?

PayPal phishing scam, SMS spam
https://www.reddit.com/r/Scams/comments/12jl856/this_text_was_sent_to_me_shortly_after_using/

@durablenapkin

**Comment by durablenapkin** [comment]
Queued, thanks
