### ISSUE TITLE
missing domain

### ISSUE THREAD

**Issue by 0kJackoo** [hagezi/dns-blocklists#928]
#### Which domain(s) should be blocked?

https://images.chesscomfiles.com/uploads/ad_image/*

#### Why should the domain(s) be blocked?

serves the banner ads on chess.com

**Comment by hagezi** [comment]
My lists are DNS lists and not content blocker lists. I can block domains, but not URLs. So I could block images.chesscomfiles.com completely, but that would probably result in no images loading at all.
