### ISSUE TITLE
xiaomi acount log in problem

### ISSUE THREAD

**Issue by angeluskun** [hagezi/dns-blocklists#931]
#### What adblocker/DNS cloud service are you using?

nextdns CNAME disabled

#### Which blocklists are used?
hagezi multi pro++

#### Which domain(s) should be unblocked?
find.api.micloud.xiaomi.net

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
after i unblock that domain i can loggin on my mi account note that this dosent apply if you re log in a second time after block again the domain just the first time

![Screenshot_2023-04-13-14-55-40-755_mark via gp](https://user-images.githubusercontent.com/23154910/231869652-a2d8395e-e2fc-43b0-8f9f-55dd91d6386b.jpg)

**Comment by hagezi** [comment]
Thanks, removed.
