### ISSUE TITLE
Piano.io

### ISSUE THREAD

**Issue by adityasam93** [hagezi/dns-blocklists#938]
#### What adblocker/DNS cloud service are you using?

Using Adguard app with Quad 9 Doh

#### Which blocklists are used?

Hagezi Multi Ultimate

#### Which domain(s) should be unblocked?

piano.io

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.

This domain is required to open a news magazine website (Frontline is the name of the magazine). The link is a third party referral link from the emails sent by that magazine. 

Thank you.

**Comment by hagezi** [comment]
@adityasam93 Please post the link, there are some piano.io domains on my lists.

**Comment by cotusandro** [comment]
I have checked the site with pro+ & ultimate list and there is no issue for general user, if any single 3rd party referral url blocking the site to open via “email” should be ignored. He should try normal or pro list for that.
