### ISSUE TITLE
fm.cnbc.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#94]
`fm.cnbc.com` breaks chart at `https://www.cnbc.com/2022/12/07/carvana-shares-tank-as-bankruptcy-concerns-grow-for-used-car-retailer.html`

Using Ultimate list, but curious to know if it affects all lists.

**Comment by hagezi** [comment]
Thanks, removed from pro++ & ultimate.

Source: 1Hosts Pro - ping @badmojr
