### ISSUE TITLE
img.ihreapotheken.de

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#943]
#### What adblocker/DNS cloud service are you using?

NextDNS

#### Which blocklists are used?
Multi PRO

#### Which domain(s) should be unblocked?

img.ihreapotheken.de
#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
Breaks https://ihreapotheken.de/

**Comment by hagezi** [comment]
Thanks, will be removed. Ping source: @badmojr (lite, pro, xtra)
