### ISSUE TITLE
wootility.io

### ISSUE THREAD

**Issue by dalkain** [hagezi/dns-blocklists#944]
#### What adblocker/DNS cloud service are you using?

AdGuard Home

#### Which blocklists are used?
HaGeZi Personal Black & White (through AGH's mirror https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt)
EDIT: It looks like the AGH mirror is actually of "HaGeZi's Light DNS Blocklist" (https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal-blackwhite.txt)

#### Which domain(s) should be unblocked?
wootility.io

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
This is a first-party hosted web app for interfacing with and configuring Wooting brand keyboards

**Comment by hagezi** [comment]
Thanks, will be removed. Source @scamsniffer database.
