### ISSUE TITLE
Fake AusPost Site

### ISSUE THREAD

**Issue by darkmyregaming** [hagezi/dns-blocklists#945]
### Which domain(s) should be blocked?

auspost.your-redelivery-au.com

### Why should these domain(s) be blocked?

Website impersonating Australia Post, used for fake "parcel re-delivery" phishing scam.

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
Thanks, added.

**Comment by hagezi** [comment]
@durablenapkin @jarelllama

**Comment by durablenapkin** [comment]
Thanks, queued
