### ISSUE TITLE
delivery.consentmanager.net

### ISSUE THREAD

**Issue by Morku** [hagezi/dns-blocklists#949]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

delivery.consentmanager.net

### Why should the domain(s) be unblocked?

As long the domain is blocked, videos on https://winfuture.de/video/25097 do not load

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
Thanks, checked, `a.delivery.consentmanager.net` will be removed.
