### ISSUE TITLE
ad.admitad.com

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#950]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

ad.admitad.com

### Why should the domain(s) be unblocked?

Affiliate links `https://ad.admitad.com/g/lhiz91jzmia2162fed5aa0ecd361a1/?i=10&ulp=https://allegro.pl/kategoria/samsung-galaxy-s21-fe-321128`

**Comment by hagezi** [comment]
Thanks, will be added to referral allowlist.
