### ISSUE TITLE
allow api.sbz.vn

### ISSUE THREAD

**Issue by minhtri88** [hagezi/dns-blocklists#952]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

api.sbz.vn

### Why should the domain(s) be unblocked?

this is new support chat feature of IOS banking app name PVMobileBanking

**Comment by hagezi** [comment]
Thanks, will be removed. 

ping sources: @notracking @badmojr @bigdargon

**Comment by bigdargon** [comment]
@hagezi I will remove it but I need to keep the following in mind:
- Bank application but using 3rd party services to support customers?! This is not professional at all!
- Subiz's bot will automatically collect phone number and email while chatting. Has this been agreed to by the customer? https://subiz.com.vn/bot/
- Subiz pop-up will annoy users when they want to entice customers to stay on the site, or ask customers to fill out a form to collect data. https://subiz.com.vn/vi/pop-up/
- Many users complain that Subiz's Live chat is very annoying. It displays the chat panel when visiting any website that has this function inserted. https://subiz.com.vn/vi/feature.html

**Comment by hagezi** [comment]
@bigdargon Thanks for the details, I agree, the Doamin remains blocked in my aggressive lists (pro++ and ultimate).
