### ISSUE TITLE
googletagmanager.com

### ISSUE THREAD

**Issue by Morku** [hagezi/dns-blocklists#953]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

googletagmanager.com

### Why should the domain(s) be unblocked?

Not sure about your point of view here, since the domain is used on multiple pages.
But blocking the domain breaks embedded content (Twitter) on this page: https://www.wn.de/welt/politik/ukrainisches-militaer-schwere-kaempfe-um-bachmut-2741103

**Comment by hagezi** [comment]
Thank you, it is only blocked in the aggressive lists (PRO++ and ULTIMATE).

Google Tag Manager is a popular tracker that is also used as a bypass for blocked Google Analytics, so it remains blocked in the aggressive lists.

![grafik](https://user-images.githubusercontent.com/104343908/233060048-9787dfd7-2559-4e91-996c-a4a8e6973c52.png)

https://slayterdev.github.io/tracker-radar-wiki/domains/googletagmanager.com.html

When using aggressive lists, it is rather something for the personal Allow list. Alternatively, you could switch to the not so aggressive PRO list.
