### ISSUE TITLE
*.attraqt.com

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#955]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

fsm1-cdn.attraqt.com
fsm-vfc.attraqt.com
attraqt.com(?)

### Why should the domain(s) be unblocked?

Breaks:
`fsm1-cdn.attraqt.com` https://www.specsavers.nl/brillen
`fsm-vfc.attraqt.com` https://www.thenorthface.pl/shop/pl/tnf-pl/mczyni-mczyni-specjalna-promocja
![Zrzut ekranu z 2023-04-19 17-16-36](https://user-images.githubusercontent.com/125269947/233121728-de7d890b-5cc9-4488-888d-3de821ecd0f1.png)

**Comment by notracking** [comment]
Thanks, fixed!
