### ISSUE TITLE
False-Positive Report

### ISSUE THREAD

**Issue by LisaATepoq** [hagezi/dns-blocklists#96]
Hello Hagezi, 

one of our business customer just reported that we are on https://dnsforge.de/ Blacklists.

The following domain is affected:

arc.epoq.de

epoq internet services GmbH is a saas company that offers technology solution for webshops, like product searches and product recommendations. Customer using dnsforge partly don't see product content when visting specific webshops.

Could you please remove this domain from your Blacklist? 

Thank you! 

Best regards
Lisa

**Comment by hagezi** [comment]
Thanks, removed.
