### ISSUE TITLE
zurl.co

### ISSUE THREAD

**Issue by hlqviet** [hagezi/dns-blocklists#960]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

```
zurl.co
```

### Why should the domain(s) be unblocked?

It is a URL shortening service. CDKeys.com uses it: https://www.facebook.com/cdkeyscom/

This seems to be the service owner: https://www.zoho.com/social/zurl/

**Comment by hagezi** [comment]
Thanks, will be removed.
