### ISSUE TITLE
pix2.services.tvn.pl

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#961]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

pix2.services.tvn.pl

### Why should the domain(s) be unblocked?

Blocked video
https://eurosport.tvn24.pl/snooker,442/snooker-mistrzostwa-swiata-2023-luca-brecel-mark-williams-wynik-i-relacja-meczu-2-rundy,1143618.html
![Zrzut ekranu z 2023-04-22 07-44-09](https://user-images.githubusercontent.com/125269947/233765298-59e82454-6d8c-4d4e-9f00-482fc763e150.png)

**Comment by hagezi** [comment]
Thanks,removed.
