### ISSUE TITLE
Immowelt Scam

### ISSUE THREAD

**Issue by ruaq** [hagezi/dns-blocklists#966]
### Which domain(s) should be blocked?

*.de-expose.life

### Why should these domain(s) be blocked?

I got an email with a link (https://lmmowelt.de-expose.life/247n45y), which looked like a flat proposal on immowelt.de but is a scam.

![IMG_4281](https://user-images.githubusercontent.com/25234289/233937334-7f6ea0ff-9ba5-4931-a94e-42859317d3d8.png)

**Comment by jarelllama** [comment]
de-expose.life is an NRD. will block
