### ISSUE TITLE
Scam Issue Template

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#967]
I noticed you set up a workflow to automate a task when you label an issue as scam.

Could I suggest a separate template for scams that has the scam label preattached? So you won't have to label each issue as scam manually.

**Comment by hagezi** [comment]
I actually check it manually before I give the label. Automatically, you would have to parse the issue to see if it is a scam. Do you have any ideas?

**Comment by jarelllama** [comment]
If you want, I can help manually check the domain too. Normally when I see a scam domain reported here I manually check it anyways.

If you have a scam issue template that tags me automatically I can check the domain and reply to the issue.

If it's confirmed scam by either one of us, you can attach a new label that pings durablenapkin using a workflow

**Comment by hagezi** [comment]
Thank you, let's see, if the requests get out of hand, I'll be happy to come back to it.
