### ISSUE TITLE
web.snrbox.com

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#968]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

web.snrbox.com

### Why should the domain(s) be unblocked?

Breaks
https://www.komputronik.pl/
![Zrzut ekranu z 2023-04-24 14-17-10](https://user-images.githubusercontent.com/125269947/233993823-74944b22-c615-4d6d-b876-4cfa18e5d6e2.png)
https://www.brw.pl/
![Zrzut ekranu z 2023-04-24 14-18-10](https://user-images.githubusercontent.com/125269947/233993912-3e299a86-5a0b-4928-8904-80c3f9455ec1.png)
![Zrzut ekranu z 2023-04-24 14-18-25](https://user-images.githubusercontent.com/125269947/233993990-7af909f2-26c6-4806-bd2f-67dd512d4e52.png)

**Comment by hagezi** [comment]
Thanks, will be removed. ping @badmojr
