### ISSUE TITLE
tracker.gpcdn.pl

### ISSUE THREAD

**Issue by flav0ring** [hagezi/dns-blocklists#969]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

tracker.gpcdn.pl

### Why should the domain(s) be unblocked?

https://www.pracuj.pl/
![Zrzut ekranu z 2023-04-24 14-30-26](https://user-images.githubusercontent.com/125269947/233998012-3fcec510-f55d-4bce-8ae5-2cccb6aca342.png)

**Comment by hagezi** [comment]
Thanks, will be removed.
