### ISSUE TITLE
600vekil.com

### ISSUE THREAD

**Issue by erentantekin** [hagezi/dns-blocklists#970]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

-

### Which blocklist(s) do you use?

Personal

### Which domain(s) should be unblocked?

600vekil.com

### Why should the domain(s) be unblocked?

I'm the author of 600vekil.com, an election forecast website for the upcoming Turkish election. I'm not sure why my website ended up here.

**Comment by hagezi** [comment]
Thanks, it is flagged by https://www.scamsniffer.io/ as scam. That is why it is on my lists.

Scam Sniffer Data: https://raw.githubusercontent.com/scamsniffer/scam-database/main/blacklist/domains.json

I'll look into it and remove the domain from my lists.
