### ISSUE TITLE
Client-side Error Exception

### ISSUE THREAD

**Issue by Kenny58** [hagezi/dns-blocklists#971]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### Which blocklist(s) do you use?

Personal

### Which domain(s) should be unblocked?

www.googletagservices.com

### Why should the domain(s) be unblocked?

![zPd6w9c](https://user-images.githubusercontent.com/56899816/234100133-f7836577-aba6-49ab-bcf4-c42868d8156c.png)

Parece que o bloqueio deste dominio esta causando esse erro, testei em allow (AdGuard DNS) e funciona.

**Comment by hagezi** [comment]
I can't reproduce this, loads fine with googletagservices.com blocked.

![grafik](https://user-images.githubusercontent.com/104343908/234121494-1c1ff134-f6ff-42e7-a6c2-4c4d407aa29a.png)

**Comment by Kenny58** [comment]
I'm sure you'll be able to reproduce it eventually during the cache reset.

**Comment by hagezi** [comment]
OK, I have tested it with the ultimatelist, in which `googletagmanager.com` is also blocked. Then the behaviour does not occur. If I unblock `googletagmanager.com`, I can reproduce the behaviour.

`googletagservices.com` will be removed from the non-aggressive lists in the current update.
