### ISSUE TITLE
link.peopleinsight.co.uk

### ISSUE THREAD

**Issue by oscarsiles** [hagezi/dns-blocklists#972]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

link.peopleinsight.co.uk

### Why should the domain(s) be unblocked?

Breaks surveys used by some workplaces.

**Comment by hagezi** [comment]
Thanks, blocked by CNAME `track.smtp2go.net`. Will be added to referral allowlist.

**Comment by hagezi** [comment]
fixed.
