### ISSUE TITLE
Make the lists available as Microtik rsc import file

### ISSUE THREAD

**Issue by hagezi** [hagezi/dns-blocklists#974]
Transferred from https://github.com/hagezi/dns-blocklists/pull/973 @proNET-Southtirol

```
# Solution 1 (preferred):
/ip dns static
add type=NXDOMAIN name="1-1ads.com"
 
# Solution 2 (requires additional tcp-reset firewall filter):
/ip dns static
add address=240.0.0.1 name="1-1ads.com"

# Solution 3 (worst, might redirect to local webserver):
/ip dns static
add address=127.0.0.1 name="1-1ads.com"
```

I prefer Solution 1

**Comment by hagezi** [comment]
@proNET-Southtirol 

Which list sizes can be processed at all?

I had read that ~30k domains need about 100 MB RAM. Then the light list would need 2 GB of free RAM.

If this is the case, then the conversion doesn't really make sense.

**Comment by proNET-Southtirol** [comment]
> Transferred from #973 @proNET-Southtirol
> 
> ```
> # Solution 1 (preferred):
> /ip dns static
> add type=NXDOMAIN name="1-1ads.com"
>  
> # Solution 2 (requires additional tcp-reset firewall filter):
> /ip dns static
> add address=240.0.0.1 name="1-1ads.com"
> 
> # Solution 3 (worst, might redirect to local webserver):
> /ip dns static
> add address=127.0.0.1 name="1-1ads.com"
> ```
> 
> I prefer Solution 1

Yes, for sure, the "Solution 1 [type=NXDOMAIN]" could be better if mainly using Windows machines in the network. 👍

**Comment by proNET-Southtirol** [comment]
> 

Well I really don't know how this value has been measured/calculated.
This kind of filter lists should not be used on a "50€-Hardware". We are using the lists on our CHR-based Mikrotik Routers.
CHR-based are simply x86 based installations where RAM would never be a problem, since you can upgrade it anytime.

**Comment by proNET-Southtirol** [comment]
We have done a simple RAM-Test with an adress-list of about 11.000 entries on one of our Routers:

RAM **before import** : 3739MB
RAM **after import** (11.000 entries) : 3700MB (we have done 1.000 DNS queries to be sure eventual caching is consuming RAM)

Some customer based models (<50-100€ models) will maybe handle just some 10k's. We could check this in our lab.

**Comment by proNET-Southtirol** [comment]
Still **no problems** on x86 architecture..

**Comment by proNET-Southtirol** [comment]
> We have done a simple RAM-Test with an adress-list of about 11.000 entries on one of our Routers:
> 
> RAM **before import** : 3739MB RAM **after import** (11.000 entries) : 3700MB (we have done 1.000 DNS queries to be sure eventual caching is consuming RAM)
> 
> Some customer based models (<50-100€ models) will maybe handle just some 10k's. We could check this in our lab.

checked on a **hEX lite**: running fine with 25k 👍

**Comment by hagezi** [comment]
Converting the large lists and offering the format does not make sense to me, as wildcard blocking is not supported either. The Light already has 700,000 domains. I already have problems with the size of the repository because of all the commits. So I will not make the list format available.

You can continue to make them available in your fork, but keep the following in mind: https://github.com/hagezi/dns-blocklists#repository
