### ISSUE TITLE
ad.mailo.com blocks the whole website service

### ISSUE THREAD

**Issue by silomia** [hagezi/dns-blocklists#975]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

ad.mailo.com

### Why should the domain(s) be unblocked?

I am a paying customer of Mailo, a French email service that is more than 20 years old. There is a free service with ads and a $1/month service without ads. Since today I can't log in to the webmail https://www.mailo.com and it blocks all IMAP and SMTP connections with my email software. It seems that the domain "ad.mailo.com" and the other services are connected to the same IP? Unsubscribing from the list solves the blocking problem.
Thank you.

**Comment by hagezi** [comment]
No, it seems to be an general NextDNS problem, tested with unfiltered NextDNS profile and the domain mailo.com does not resolve.

**Comment by hagezi** [comment]
If I use another DNS as upstream, the page loads perfectly, tested with Pihole, Blocklist Ultimate, Quad9 DNS.

![grafik](https://user-images.githubusercontent.com/104343908/234672172-cd5aa88b-550c-4c05-bf63-8aceab18620a.png)

**Comment by hagezi** [comment]
Open a bug in the NextDNS help forum: https://help.nextdns.io/category/bugs

**Comment by hagezi** [comment]
@silomia I have opened an issue with NextDNS: https://help.nextdns.io/t/m1hcsmz

**Comment by hagezi** [comment]
@silomia ​

There seems to be a general problem with mailo.com:

```
5:30 p.m. news bulletin:

The situation is gradually being restored. Access to servers has become possible again.

14:00 a.m. news bulletin:

Following a fire this Wednesday, April 25 at 5 a.m. at Mailo's host, the servers are temporarily inaccessible. So you can't access email on the web or through your usual software and apps.

The situation has stabilized at the host and it is gradually reactivating the impacted services.

Everything is being done to restore service quickly.

We apologize for this inconvenience, beyond our control.

Stay informed on our Twitter and Mastodon accounts.
https://twitter.com/HelloMailo/
https://mastodon.social/@hellomailo
```
Using NextDNS, I'll probably end up on a burning server. ;)
​

**Comment by silomia** [comment]
Thank you for your time. So I totally missed the point!!! ;)
