### ISSUE TITLE
DoorDash tracking blocked

### ISSUE THREAD

**Issue by cmirza** [hagezi/dns-blocklists#976]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

track.doordash.com

### Why should the domain(s) be unblocked?

This is a domain used by DoorDash to provide tracking updates for deliveries.

**Comment by hagezi** [comment]
Thanks, will be removed.
