### ISSUE TITLE
fingerprint.com

### ISSUE THREAD

**Issue by yokoffing** [hagezi/dns-blocklists#979]
### Which AdBlocker/DNS cloud service do you use?

uBlock, ControlD

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

`fingerprint.com`

Example: https://fingerprint.com/blog/apple-id-region-leak/
https://fingerprint.com/blog/can-letterboxing-prevent-browser-fingerprinting/

### Why should the domain(s) be unblocked?

Prevents access to their blogs and news reports, which was referenced by [Surveillance Report](https://www.youtube.com/watch?v=VehvQ3e2x8w).

**Comment by hagezi** [comment]
Thanks, added to allowlist.
