### ISSUE TITLE
xmr.2miners.com is incorrectly blocked it is a monero mining pool

### ISSUE THREAD

**Issue by lthedetective** [hagezi/dns-blocklists#980]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

xmr.2miners.com

### Why should the domain(s) be unblocked?

it is a monero mining pool by two miners

**Comment by hagezi** [comment]
Thanks, I'll have a look at it later. I'm currently doing some rearranging.
