### ISSUE TITLE
Bloomberg.com

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#982]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### Other

N 　 O_o

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

cdn.gotraffic.net
personalization.bloomberg.com
sourcepointcmp.bloomberg.com

### Why should the domain(s) be unblocked?

Breaks site layout and videos on `Bloomberg.com`

**Comment by hagezi** [comment]
@norilana As always, thank you!
What some people put on a block list ...
I'll have a look at it later. I'm currently doing some rearranging.

**Comment by sjhgvr** [comment]
Pong
