### ISSUE TITLE
Qualcomm A-GPS domains

### ISSUE THREAD

**Issue by hlqviet** [hagezi/dns-blocklists#984]
I've just seen these in my DNS log recently:

![image](https://user-images.githubusercontent.com/5486625/235140092-a3f2cf8d-aa9c-4b5f-903e-6f3d4e867ef4.png)

This is what I found: https://gitlab.com/CalyxOS/calyxos/-/issues/370
I also found a blocklist: https://gitlab.com/nobodysu/spyware-hosts/blob/master/lists/qualcomm-mild.txt

I have no idea if they should be whitelisted widely or I just do it myself.

**Comment by hagezi** [comment]
Hi, blocked in the agressive Lists, details:

`German security company Nitrokey proves that Qualcomm chips have a backdoor and are phoning home : privacy`
https://teddit.net/r/privacy/comments/12yii9u/comment/jhojlr7/

**Comment by hagezi** [comment]
Based on GrapheneOS's comment at https://teddit.net/r/privacy/comments/12yii9u/comment/jhojlr7/ and since A-GPS is also used in emergencies, I will remove the domains.

**Comment by hagezi** [comment]
@hlqviet fixed.

**Comment by hagezi** [comment]
Missed: https://github.com/hagezi/dns-blocklists/issues/1023
