### ISSUE TITLE
List has gone offline

### ISSUE THREAD

**Issue by pallebone** [hagezi/dns-blocklists#986]
Hi there,

I was using this list:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/doh-vpn-proxy-bypass.txt

It appears this list is not existing anymore.

What list can I use instead of this list that is identical in nature? This list did doh/vpn/proxy etc for pihole.

Kind regards
Peter

**Comment by hagezi** [comment]
Hi @pallebone,

This list only makes sense with adblockers that also support wildcard blocking, i.e. if a domain is on the list, all subdomains are automatically blocked. This is why support for the host/domain format was discontinued.
In the current Pi-hole version you can use the Adblock format, see https://github.com/hagezi/dns-blocklists#bypass

**Comment by pallebone** [comment]
ok thanks I will use this list instead, but this list says dns blocklist... what about DOH,VPN, Proxy?

**Comment by pallebone** [comment]
Dont worry I figured it out :)
