### ISSUE TITLE
mng.bz

### ISSUE THREAD

**Issue by elliotwutingfeng** [hagezi/dns-blocklists#987]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

pfBlockerNG

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

www.mng.bz
mng.bz

### Why should the domain(s) be unblocked?

Official URL shortener for hyperlinks in books published by [Manning Publications](https://manning.com). Unlikely to be spam or infected with malware.

**Comment by hagezi** [comment]
Thanks @elliotwutingfeng, will be removed.

**Comment by iam-py-test** [comment]
Thank you @hagezi. I have removed the entry, added those domains to my allowlist, and disabled the other domains I copied from the same source, pending manual review of said entries.
