### ISSUE TITLE
False positive - MS Family Safety app on IOS not working with Multi Light blocklist

### ISSUE THREAD

**Issue by dinguz** [hagezi/dns-blocklists#988]
I am using the Multi Light blocklist on my network appliance running OPNsense, using the domain/subdomain version of this blacklist.
All seems to be working well, with one exception: the Microsoft Family Safety app on IOS is no longer working, citing 'network issues'. As soon as I disable the blocklist, the app starts working again.

**Comment by hagezi** [comment]
@dinguz OK, I can't test it myself, so I'm depending on your or other help to know what to whitelist.

**Comment by hagezi** [comment]
Found something, will be fixed.

**Comment by dinguz** [comment]
Can it be mobileaggregator.family.microsoft.com ? If I manually whitelist this one, it seems to work again.

**Comment by hagezi** [comment]
Ok, `*.family.microsoft.com` will be whitelsited.
