### ISSUE TITLE
false positive uber.space on TIF

### ISSUE THREAD

**Issue by ruaq** [hagezi/dns-blocklists#99]
The domain `uber.space` is a false positive in the TIF list.

The domain uber.space is used by uberspace.de (an awesome german hosting provider) for its customers. See https://manual.uberspace.de/web-domains/ for an explanation. If there is a malicious uber.space Domain an [abuse report](https://uberspace.de/en/about/privacy/) would help better. ;-)

**Comment by hagezi** [comment]
Thanks, removed.
