### ISSUE TITLE
consentag.eu

### ISSUE THREAD

**Issue by Algorithm5838** [hagezi/dns-blocklists#990]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

consentag.eu

### Why should the domain(s) be unblocked?

Booking a flight won't go through in:
https://booking.flynas.com/#/booking/flights

**Comment by hagezi** [comment]
Thanks, will be removed.
