### ISSUE TITLE
Pushbullet false positives

### ISSUE THREAD

**Issue by kevindwitama** [hagezi/dns-blocklists#992]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

`api.pushbullet.com`
`api2.pushbullet.com` (possibly)
`static.pushbullet.com`
`stream.pushbullet.com`
`stream-android.pushbullet.com`
`update.pushbullet.com`

### Why should the domain(s) be unblocked?

I use pushbullet to get android notifications on my desktop, as well as to send links/texts/files between devices.

On launch, the desktop (windows) PB tries to connect to the following `*.pushbullet.com` domains: `stream.`, `api.`, `static.`, `update.`, and `zebra.`. It seems to fail to launch if anything but `zebra.` is blocked.

`stream.` and `stream-android.` seem to be used to sync notifications between devices.

I've only seen `api2.` being used by the mobile app. Blocking it doesn't seem to break anything, and I'm inclined to keep it blocked if that's true, but needs more testing.

`zebra.` seems to be the only domain related to telemetry, and should remain blocked.

**Comment by hagezi** [comment]
@kevindwitama Thanks, checked, will fix as you recommended.

**Comment by hagezi** [comment]
fixed.
