### ISSUE TITLE
securenetsystems.net

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#993]
### Which AdBlocker/DNS cloud service do you use?

uBlock, NextDNS

### Other

  O.o

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

securenetsystems.net

### Why should the domain(s) be unblocked?

Audio players

**Comment by hagezi** [comment]
Thanks, will be removed.

**Comment by hagezi** [comment]
fixed in 5 minutes ...
