### ISSUE TITLE
kompas.com

### ISSUE THREAD

**Issue by rapdodge** [hagezi/dns-blocklists#994]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

kompas.com

### Why should the domain(s) be unblocked?

kompas.com is a news portal in Indonesia.

![image](https://user-images.githubusercontent.com/33513626/235352949-3667bb45-1e9a-4745-8c5b-8f5b4ddd0c7b.png)

**Comment by hagezi** [comment]
Thanks, will be removed on next update. Sort out more things in the Ultimate.

**Comment by hagezi** [comment]
@rapdodge fixed.
