### ISSUE TITLE
News9 - KWTV

### ISSUE THREAD

**Issue by TheAnimeElitist** [hagezi/dns-blocklists#996]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### NextDNS users only

- [X] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

www.news9.com

### Why should the domain(s) be unblocked?

It's the news website for KWTV in the US state of Oklahoma.

**Comment by hagezi** [comment]
Thanks, removed.
