### ISSUE TITLE
Additional DOH blocks

### ISSUE THREAD

**Issue by peanut18** [hagezi/dns-blocklists#997]
### Which domain(s) should be blocked?

dns8.org
ns3.cx
ns3.link
ns3.com
n0.eu

Referenced by https://dnsleaktest.org/dns-over-https

### Why should these domain(s) be blocked?

Appear to be DOH resolvers not in the Hagezi lists

They are actually blocked for me with this feed
https://github.com/dibdot/DoH-IP-blocklists

specifically - https://github.com/dibdot/DoH-IP-blocklists/blob/master/doh-domains.txt

**Comment by hagezi** [comment]
@peanut18 thanks, I will add @dibdot DoH as a source.

**Comment by peanut18** [comment]
Thank you for your awesome work, love your lists!

**Comment by hagezi** [comment]
@peanut18 added. Updated lists are online.
