### ISSUE TITLE
Shopee - Video of product blocked

### ISSUE THREAD

**Issue by reggieds** [hagezi/dns-blocklists#999]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

https://shopee.co.id/Hoya-Excavata-i.35643774.14138873544?sp_atk=05115c40-6259-4e1b-8a2d-e9673b4de840&xptdk=05115c40-6259-4e1b-8a2d-e9673b4de840

### Why should the domain(s) be unblocked?

Have issue with product video at Shopee website. Product video blocked.

https://shopee.co.id/Hoya-Excavata-i.35643774.14138873544?sp_atk=05115c40-6259-4e1b-8a2d-e9673b4de840&xptdk=05115c40-6259-4e1b-8a2d-e9673b4de840

**Comment by hagezi** [comment]
Thanks, folo

**Comment by hagezi** [comment]
Thanks @reggieds, the following domains (region-dependent) block the video

```
cvf.shopee.co.id
cvf.shopee.com.my
cvf.shopee.co.th
cvf.shopee.ph
cvf.shopee.sg
cvf.shopee.vn
```

The domains will be removed.

**Comment by hagezi** [comment]
@reggieds fixed.
